### ISSUE TITLE
Graphical glitch in Docker Desktop / MacOS

### ISSUE THREAD

**Issue by samtron3030** [docker/for-mac#5523] opened 2021-03-31 06:29 UTC
Started occuring today when viewing docker-compose defined and initialized cluster. 

See picture: https://pasteboard.co/JV7zKMe.png

Diagnostics-id: DEBF974B-A58F-4216-8D6D-928C1B206705/20210331062004

  - [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ [x]] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Not to have visual glitch

### Actual behavior

Have visual glitch

### Information

  - macOS Version: 10.15.7 Catalina
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-03-31 07:45
Thanks for the report. I believe this is a dupe of #5121, so I'm going to close this copy.

**Closed by stephen-turner** 2021-03-31 07:45 UTC
Labels: version/3.2.2
