### ISSUE TITLE
Docker won't start after 1.13.0 upgrade.

### ISSUE THREAD

**Issue by ermidev** [docker/for-mac#1167] opened 2017-01-20 03:22 UTC
### Expected behavior
Docker should up and running.
### Actual behavior
- com.docker.driver.amd64-linux -db is not running
- /Users/Ermias/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
- Connection refused (ECONNREFUSED) connecting to /Users/Ermias/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/F2F6D4B8-ADD1-4352-AC76-C475774DB05B/20170119-191822.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Ermias/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/Ermias/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Ermias/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/Ermias/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/Ermias/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Ermias/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by tjshipe** [comment] 2017-01-20 03:27
This looks like a duplicate of #1159 

Did you try [this solution](https://github.com/docker/for-mac/issues/1159#issuecomment-273899215)?

**Comment by ermidev** [comment] 2017-01-20 03:31
@tjshipe thanks! I did your suggestion and now it up and running. As your said, the images and contains are gone.

**Comment by djs55** [comment] 2017-01-20 10:24
Thanks @tjshipe and @ermidev. I'll close this as a dup of #1159.

**Closed by djs55** 2017-01-20 10:24 UTC
