### ISSUE TITLE
can't start kubernetes seamlessly in china region, guess block gcr.io registry.  

### ISSUE THREAD

**Issue by xiaods** [docker/for-mac#2648] opened 2018-02-27 21:51 UTC
### Expected behavior
use alternative docker hub registry as kubernetes image registry location

### Actual behavior

can't start kubernetes seamlessly in china region, guess block gcr.io registry.  

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. open preferences... and switch kubernetes panel
  2. enable install kubernetes checkbox
the status always on the installing status. not got done status.

see my Diagnose log below:

```
Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/2D4C2D59-9259-495A-AF16-9200A77CE6BE/20180228-050842.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

[20180228-050842.tar.gz](https://github.com/docker/for-mac/files/1764828/20180228-050842.tar.gz)

docker for mac version:  Version 18.02.0-ce-mac53 (22617)

**Comment by guillaumerose** [comment] 2018-03-12 12:35
Thanks for the report. This issue in our backlog. Duplicate of https://github.com/docker/for-mac/issues/2474

**Closed by guillaumerose** 2018-03-12 12:35 UTC
Labels: version/18.02.0-ce-mac53
