### ISSUE TITLE
Docker cannot build a Docker image.

### ISSUE THREAD

**Issue by Radi0Eng** [docker/for-mac#7419] opened 2024-09-15 19:09 UTC
### Description

I'm facing an application error when trying to build a docker image whose base image is in GitHub.  
Can anyone help me fix this problem. 
<img width="1269" alt="Screenshot 2024-09-15 at 19 58 33" src="https://github.com/user-attachments/assets/2597984c-9db1-4323-bce4-9a430bc41ca2">

ps: my Docker Desktop is upto date:

<img width="1047" alt="Screenshot 2024-09-15 at 20 03 50" src="https://github.com/user-attachments/assets/237327f0-197b-487b-bb02-8e7ddc5f7f95">

<img width="764" alt="Screenshot 2024-09-15 at 20 04 27" src="https://github.com/user-attachments/assets/9bcc6f51-2f98-4729-9ad3-5c16c705933d">

### Reproduce

docker build sampleapp

### Expected behavior

To generate an image.

### docker version

```bash
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.2 (167172)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /Users/alialzahrani/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: 0a432db9-3ad1-4361-b892-5b90fe7da69e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/alialzahrani/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

F96752C3-2504-4FC0-95BB-150C63D6869C/20240915190622

**Comment by SinKingCloud** [comment] 2024-09-17 04:39
请问有解决方案了吗

**Comment by SinKingCloud** [comment] 2024-09-17 04:55
rm -rf ~/Library/Group\ Containers/group.com.docker
rm -rf ~/.docker
关闭docker执行，然后启动docker即可解决

**Comment by jeec** [comment] 2024-10-13 09:13
Yes, it works as well, by the way, how could you find out the root cause?  thanks @Radi0Eng

**Comment by thompson-shaun** [comment] 2024-11-07 01:41
closing as resolved

**Closed by thompson-shaun** 2024-11-07 01:41 UTC
Labels: status/triage, area/build-ui, version/4.34.2
