### ISSUE TITLE
docker 1.12.1 occasionally hangs

### ISSUE THREAD

**Issue by ilg-ul** [docker/for-mac#828] opened 2016-10-20 18:12 UTC
### Expected behavior

long and complex builds are expected to pass
### Actual behavior

long and complex builds occasionally hang; most of the time restarting the build solves the problem, but some times docker hangs from the very beginning, while starting (this last behaviour reminds me to some broken sockets, that have a long timeout to close and to allow the TCP port to be reused)
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/2551401D-1E9A-47AA-A628-C5802377B988/20161020-203554.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

2551401D-1E9A-47AA-A628-C5802377B988
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior

Running the build scripts that cause the problem is easy, but reproducing the environment is a bit more difficult, since the builds also generate manuals, and this requires installing MacTex.

Except MacTex (which is installed in the usual location), the rest of the tools are installed in a custom Homebrew instance, located in `$HOME/opt/homebrew-gae`.

```
git clone https://gist.github.com/46407a070844f764dec6f27bde385797.git ~/Downloads/install-homebrew.gist
bash ~/Downloads/install-homebrew.gist/install-homebrew-openocd.sh
```

The build script is available in a separate project:

```
git clone https://github.com/gnuarmeclipse/build-scripts.git ~/Downloads/build-scripts.git
bash ~/Downloads/build-scripts.git/scripts/build-openocd.sh --all
```

The script creates multi-platform (macOS, Windows and Debian) packages in the `~/Work/openocd` folder.

My first impression was that the problem occurs only if the system enters power saving, and I added `caffeinate` when starting docker, but this did not help, the script occasionally hangs even if the system remains active.

Most of the time the script simply hangs, but there are cases when one of the programs started by the script loops over null characters read from the input file, which seems a problem in the code mounting the mac folder into docker.

Running the script on Linux seems ok, no hangouts recorded, so the problem might be related to virtualisation, possibly to sharing the host folder inside the virtual machine.

If you need more details, please let me know.

**Comment by ilg-ul** [comment] 2016-10-21 07:22
while cleaning my file system, I identified one file in a build that crashed:

```
ilg-mbp:bin ilg$ pwd
/Users/ilg/Work/openocd/install/debian64/openocd/bin
ilg-mbp:bin ilg$ ls -l
total 35477168
-rw-------  1 ilg  staff  18161860608 Oct 20 19:57 libusb-1.0.so.0.1.0
-rwxr-xr-x  1 ilg  staff      2445416 Oct 20 19:36 openocd
ilg-mbp:bin ilg$ 
```

the libusb size is huge, 18 GB. this somehow confirm my feeling that something is wrong with file sharing, since these build scripts create lots of files.

**Comment by ilg-ul** [comment] 2016-10-21 07:25
here is another one, in another project, with even more complex build scripts:

```
ilg-mbp:bin ilg$ pwd
/Users/ilg/Work/qemu/install/debian32/qemu/bin
ilg-mbp:bin ilg$ ls -l
total 4616520
lrwxrwxrwx  1 ilg  staff          20 Oct 20 13:16 libSDL-1.2.so -> libSDL-1.2.so.0.11.4
lrwxrwxrwx  1 ilg  staff          20 Oct 20 13:16 libSDL-1.2.so.0 -> libSDL-1.2.so.0.11.4
-rw-r--r--  1 ilg  staff      566168 Oct 20 13:16 libSDL-1.2.so.0.11.4
lrwxrwxrwx  1 ilg  staff          25 Oct 20 13:16 libSDL_image-1.2.so -> libSDL_image-1.2.so.0.8.2
lrwxrwxrwx  1 ilg  staff          25 Oct 20 13:16 libSDL_image-1.2.so.0 -> libSDL_image-1.2.so.0.8.2
-rw-r--r--  1 ilg  staff       20368 Oct 20 13:16 libSDL_image-1.2.so.0.8.2
-rw-------  1 ilg  staff  2358509568 Oct 20 13:17 libpng16.so.16.17.0
-rwxr-xr-x  1 ilg  staff     4539232 Oct 20 13:16 qemu-system-gnuarmeclipse
```

there is definitely something wrong with file sharing between docker and the macOS file system.

**Comment by dsheets** [comment] 2016-10-21 09:26
Hi! This looks like a duplicate of #495 and #728 which has been fixed in Beta 28. If you are comfortable running the beta channel, trying Beta 28 to see if it fixes the problem would be appreciated.

**Comment by ilg-ul** [comment] 2016-10-21 21:18
Hi @dsheets,

You were right, with Beta 28 the builds passed without any problems. With the VirtualBox versions I had a problem running `strip` on a file located on a mounted folder, so at that time I had to find a workaround (copy the file locally and back to the original location). With the current version I no longer needed the workaround, `strip` performed directly on the mounted file.

However, the builds took ages to complete, I would say much longer than before (although this might be subjective, since I do not have any measurements).

**Comment by ilg-ul** [comment] 2016-10-22 17:56
I was a bit optimistic when I said the builds passed without problems. Occasionally the builds still fail, differently from before, but still fail. :-(

I'll try to get more details, but, until now, I could not reproduce the problem, if I run again the scripts, they pass...

**Comment by ilg-ul** [comment] 2016-10-22 19:10
for example:

```
Running QEMU make install...
config-host.mak is out-of-date, running configure

ERROR: Unknown target name 'gnuarmeclipse-softmmu'

Makefile:35: recipe for target 'config-host.mak' failed
make: *** [config-host.mak] Error 1
```

the script does `make all pdf` followed by `install install-pdf`; it looks like the build folder was corrupted, and `make` failed.

**Comment by dsheets** [comment] 2016-10-23 13:05
@ilg-ul the occasional failures sound frustrating. Could you run `Diagnose & Upload` again so we can take a look at your recent logs?

**Comment by ilg-ul** [comment] 2016-10-23 15:37
Diagnostic ID: D71F5326-0D23-4376-8A06-67DBD61AF38C

next time I'll write down the time when it happens and the actual error in the console.

could you point me the location of the running logs, so I can check them right after detecting a problem?

**Comment by ijc25** [comment] 2016-11-18 16:12
@ilg-ul thanks for the additional info. I've taken a look through the logs with timestamp 20161103-185130 but nothing stands out as an obvious issue.

> next time I'll write down the time when it happens and the actual error in the console.

A time of failure along to correlate with a diagnostic id would indeed be useful. As would the actual failing command, thanks.

> could you point me the location of the running logs, so I can check them right after detecting a problem?

Many of the logs should be visible in the macos `console` command. VM logs, such as `docker.log` should be in `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log`.

**Comment by ilg-ul** [comment] 2016-11-18 16:15
I am currently using the beta versions and, so far, did not encounter such problems; I suggest we close this ticket.

**Comment by ijc25** [comment] 2016-11-18 16:34
@ilg-ul Thanks, closing.

**Closed by ijc25** 2016-11-18 16:34 UTC
Labels: area/mounts, kind/bug, osx/10.12.x, status/0-more-info-needed, status/1-acknowledged, version/1.12.1
