### ISSUE TITLE
Helper install infinite loop

### ISSUE THREAD

**Issue by ehershey** [docker/for-mac#2687] opened 2018-03-12 00:01 UTC
### Expected behavior

First run of Docker.app installs helper then starts normally. 

### Actual behavior

Infinite loop of "Docker needs privileged access" and username/password dialog. 

### Information

Can't run "Diagnose & Feedback" in the menu - selecting the option does nothing (presumably because the privileged access dialog is open and can't be dismissed without exiting). 

```
[ernie@eahimac2 ~]$ /Applications/New/Docker.app//Contents/Resources/bin/docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ernie@eahimac2 ~]$

```

### Steps to reproduce the behavior

  1. Fully uninstall or start fresh
  2. sudo launchctl disable system/com.docker.vmnetd
  3. Launch Docker.app
  4. Shows "We are whaly happy to have you" dialog - click Next
  5. App icon shows up in my dock and I see "Docker needs privileged access" dialog - click OK
  6. Shows "Docker is trying to add a new helper tool" dialog - enter password and click Add Helper
  7. App icon in dock bounces and the "Docker needs privileged access" dialog reappears

**Comment by ehershey** [comment] 2018-03-12 01:01
I somehow got myself into this frustrating state after some combination of old docker machine installs/uninstalls in the past and running "brew upgrade docker" and "brew uninstall --force docker" right before using a version downloaded directly. Once I ran  "sudo launchctl load  -w /Library/LaunchDaemons/com.docker.vmnetd.plist" by hand, which re-enabled the disabled service while loading it, it fixed everything. It's minutely possible I had disabled the service by hand at some point, but I'm pretty sure I didn't.

**Comment by akimd** [comment] 2018-03-12 07:43
Hi @ehershey.  Without diagnostics, there's no debugging we can do.

**Comment by akimd** [comment] 2018-03-26 13:58
No answer, and a new stable was released.

**Comment by xbeta** [comment] 2018-04-13 06:27
Got the same issue, @orefalo's recommendation works!

**Comment by akimd** [comment] 2018-04-13 07:26
That's good news!  But I would like to know in what state Docker was so that this fix was needed.  I don't know how to reproduce it.  Also, I would like to know the versions of Docker for Mac that are troublesome on this regard.

TIA!

**Comment by akimd** [comment] 2018-05-29 07:45
Closing, since it seems that we found a good way to tell the user how to get out of this hell (https://github.com/docker/for-mac/issues/2934).

**Closed by akimd** 2018-05-29 07:45 UTC

**Comment by bjarthur** [comment] 2020-06-22 20:35
rebooting worked for me
