### ISSUE TITLE
weird EPERM for symlink on shared volume (gRPC FUSE related)

### ISSUE THREAD

**Issue by yamt** [docker/for-mac#4862] opened 2020-08-26 05:54 UTC
spacetanuki% mkdir vol
spacetanuki% docker run -it -v $(pwd)/vol:/vol alpine ln -s /xxx /vol/link
ln: /vol/link: Operation not permitted
spacetanuki% 

* it seems the symlink contents (/xxx in the above example) is rejected for some reasons.
* it happens only with "Use gRPC FUSE for file sharing" turned on.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
symlink contents should not be checked

### Actual behavior
symlink fails with EPERM, depending on the symlink contents

### Information

  - macOS Version:

10.14.6 (18G6020)

Darwin spacetanuki.lan 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64

### Diagnostic logs

```
Docker for Mac: version...

```

sorry, i couldn't find "Diagnose & Feedback" in the menu.

"About Docker Desktop" says it's
* version: 2.3.5.0 (47376)
* channel: edge

spacetanuki% docker version
Client: Docker Engine - Community
 Azure integration  0.1.12
 Version:           19.03.13-beta2
 API version:       1.40
 Go version:        go1.13.14
 Git commit:        ff3fbc9d55
 Built:             Mon Aug  3 14:58:48 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13-beta2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.14
  Git commit:       ff3fbc9d55
  Built:            Mon Aug  3 15:06:50 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
spacetanuki% 

### Steps to reproduce the behavior

  1. turn on "Use gRPC FUSE for file sharing"
  2. mkdir vol
  3. docker run -it -v $(pwd)/vol:/vol alpine ln -s /xxx /vol/link

**Comment by techyowl** [comment] 2020-09-03 04:10
I am also experiencing this with my testing of the current edge build. I need some form of work around to even use it.

**Comment by stephen-turner** [comment] 2020-09-08 17:10
@djs55 PTAL Thanks.

**Comment by craigds** [comment] 2020-09-14 04:44
Also experiencing this (docker desktop for mac 2.3.6.1)

* disabling "Use gRPC FUSE for file sharing" works around the issue.
* the _target_ of the symlink matters:
  - creating symlinks with an absolute target outside the same volume mount fails
  - creating symlinks with a relative target inside the same volume seems to work (`ln -s target /path/to/symlink/`)
  - whether the target exists or not seems to be irrelevant

**Comment by djs55** [comment] 2020-09-14 13:56
Thanks for the the report! It reproduces quite easily for me -- it seems to be caused by a path validation step which checks that requested files are in the list of paths shared with containers. Unfortunately we over-zealously verified symlink *targets* as well as the symlink paths themselves, even though targets are allowed to be arbitrary paths and are always checked on open. I've got a candidate fix and will let you know when there are experimental builds to try.

**Comment by simonferquel** [comment] 2020-10-19 09:00
The issue has been fixed in Edge release 2.4.2.0, thank you for reporting it.

**Closed** 2020-10-29 14:31 UTC
Labels: version/2.3.5.0

**Comment by lsloan** [comment] 2020-11-06 14:53
Has the fix appeared in non-Edge releases yet?  Like 2.5.0.0?

**Comment by stephen-turner** [comment] 2020-11-06 15:26
Yes, everything in Edge 2.4.2.0 is in Stable 2.5.0.0.
