### ISSUE TITLE
Docker wont start

### ISSUE THREAD

**Issue by morefromalan** [docker/for-mac#1433] opened 2017-03-15 03:40 UTC
### Expected behavior
Docker should start

### Actual behavior
Docker wont start:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Information
2966B4F1-83FA-4F15-ADCD-865CA5B0038F

### Steps to reproduce the behavior

Machine has been crashing.  Not sure if crashes are related to docker.  Occasionally after crashing, docker will no longer start.

**Comment by djs55** [comment] 2017-03-21 16:21
@arturosaco `tcp://127.0.0.1:32768` sounds like it refers to a remote Docker instance rather than the local Docker for Mac unix domain socket. Could you check if you have a `DOCKER_HOST` (and `DOCKER_TLS_VERIFY`) environment variables set?

**Comment by djs55** [comment] 2017-03-21 16:26
@morefromalan looking in your diagnostic logs I see:
```
2017-03-14 20:37:46-07 ... Docker[com.docker.driver.amd64-linux][1445] <Notice>: com.docker.hyperkit: [ERROR] Found a reference to cluster 50936 outside the file (max cluster 50935) from cluster 75.10896
2017-03-14 20:37:46-07 ... Docker[com.docker.driver.amd64-linux][1445] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure
2017-03-14 20:37:46-07 ... Docker[com.docker.driver.amd64-linux][1445] <Notice>:   "Found a reference to cluster 50936 outside the file (max cluster 50935) from cluster 75.10896")
```
If the machine has been crashing it's possible that the qcow2 file has become corrupt. What may have happened is a block ("cluster") was allocated and the file extended with `ftruncate`. A reference to the new cluster was written into the file and then the machine crashed. It's possible that the `ftruncate` was not persisted but the cluster write was. I suspect this is a duplicate of https://github.com/docker/for-mac/issues/1315

There have been a number of recent qcow bug fixes which might fix this problem, due for release tomorrow on the `edge` channel.

In the meantime the only workaround I can suggest is to `rm -f ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 ` which unfortunately means your containers and images will need to be rebuilt -- sorry for the inconvenience.

I'll close this as a duplicate of https://github.com/docker/for-mac/issues/1315

**Closed by djs55** 2017-03-21 16:26 UTC
Labels: status/0-triage

**Comment by morefromalan** [comment] 2017-03-21 17:51
rebuilding containers not a big problem.  Thank you for the workaround

---
Alan Peters
415-314-1340 | morefromalan@gmail.com
