### ISSUE TITLE
Dashboard/UI opens upon boot/launch/restart and does not hide. Docker does not start backgrounded.

### ISSUE THREAD

**Issue by timfallmk** [docker/for-mac#6372] opened 2022-06-22 22:26 UTC
Possible partial or full regression of #6167 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `8AA04ED2-FE4E-4107-A277-45CCD6E4EF73/20220622222030`

### Expected behavior
When docker starts (or when it starts with the system) is should start in a "backgrounded" state where the UI is not visible and the application is not shown in the dock. By default it should only show in the menu bar.

### Actual behavior
During starts/restarts Docker opens the UI/Dashboard. It does not close this dashboard.

### Information
More details are in the linked issue, but this is generally a high priority usability issue and should be easy to deal with.

Platform: macOS 12.4
Arch: arm64 (M1)
Docker version: 
```
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:20:34 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.1 (81317)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:14:19 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```shell
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior
1. Start with Docker running
2. Stop Docker/shut down machine
3. Start Docker/restart machine (if set to run on boot)

**Comment by trungutt** [comment] 2022-06-30 07:21
If I understand it correctly, we have the possibility to disable opening UI at startup in Settings

<img width="1225" alt="Screen Shot 2022-06-30 at 9 19 55 AM" src="https://user-images.githubusercontent.com/18528548/176617086-ca101712-599d-42d1-aad6-821cd51777b8.png">

**Comment by nicks** [comment] 2022-06-30 21:47
Thanks for reporting! Ya, I confirmed in your diagnostic report that you have the "Open Docker Dashboard at Startup" setting on (as @trungutt pointed out). You can change that setting to get the behavior you want. I'm going to close this as working as intended.

**Closed by nicks** 2022-06-30 21:47 UTC
Labels: version/4.9.1

**Comment by timfallmk** [comment] 2022-07-01 21:45
Ah, I failed to notice that. My bad! Carry on.
