### ISSUE TITLE
Fatal Error : vmstateevent invalid json

### ISSUE THREAD

**Issue by npjonath** [docker/for-mac#228] opened 2016-08-11 09:04 UTC
### Expected behavior
I'm trying to build a fresh new VM from a custom dockerfile. 
I have installed Docker for Mac (Stable channel - 1.12.0 - build 10871 - 9cd1dc28d3ac81cb5177ff9728f65200304b36f6).
I use the command : "docker build ." in order to build my script.

```
 # Load from official php:7-apache images (debian:jessie)
FROM php:7-apache

MAINTAINER NPjonath <npjonath@gmail.com>
LABEL version="1.0"
LABEL description="Apache 2 / PHP 7 - custom build"

 # Declare ENV Type
 # => development / production
ENV APPLICATION_ENV development

 # Add deb source
RUN echo "deb http://www.deb-multimedia.org jessie main non-free" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://www.deb-multimedia.org jessie main non-free" | tee -a /etc/apt/sources.list

 # CORE DEPENDENCIES
RUN apt-get update && apt-get install -y --fix-missing \
        g++ \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libicu-dev \
        openssl \
        libc-client-dev \
        libkrb5-dev \
        libxml2-dev \
        libfreetype6-dev \
        libgd-dev \
        libcurl4-openssl-dev \
        wget \
        apt-utils \
        zip \
        cifs-utils \
        ghostscript \
        texlive-full

 # IMAGEMAGICK DEPENDENCIES
RUN apt-get install -y --fix-missing imagemagick \
        php5-imagick

 # GEN ISO IMAGE DEPENDENCIES
RUN apt-get install -y --fix-missing genisoimage

 # MEDIAINFO DEPENDENCIES
RUN apt-get install -y --fix-missing mediainfo

 # Install kerberos
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
                && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
                && docker-php-ext-configure bcmath \
                && docker-php-ext-install -j$(nproc) imap intl iconv mcrypt gd dom exif mysqli gettext mbstring soap json iconv zip ftp curl \
                && docker-php-ext-install bcmath

 # Copy configuration for apache and php from host repository
COPY php.ini /usr/local/etc/php/
COPY apache2.development.conf /etc/apache2/apache2.development.conf
COPY apache2.production.conf /etc/apache2/apache2.production.conf
COPY pdfcompress.sh /usr/bin/pdfcompress
RUN chmod +x /usr/bin/pdfcompress

 # Install custom font to container
COPY fonts/ttf ~/.fonts
RUN fc-cache -f -v


 # Install Xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

 # Install APC
RUN pear config-set php_ini /usr/local/etc/php/php.ini
RUN pecl config-set php_ini /usr/local/etc/php/php.ini
RUN pecl install apc

 # Enabled apache rewrite
RUN a2enmod rewrite

 # Install Opcache
RUN pecl install -o -f zendopcache \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name opcache.so)" > /usr/local/etc/php/conf.d/opcache.ini

 # Install Composer (php)
RUN curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin

 # Clean
RUN apt-get autoremove -y && apt-get clean all

 # Create virtual dir.
RUN mkdir /storage
RUN mkdir -p /var/log/httpd/

 # Mount remote folder

RUN mkdir -p /mnt/svs_ingest_server/tmp ;
RUN mkdir -p /mnt/svs_ingest_server/Workspace ;
RUN touch /etc/.smbcred
RUN echo "username=dvb" | tee -a /etc/.smbcred
RUN echo "password=" | tee -a /etc/.smbcred
RUN echo "domain=WORKGROUP" | tee -a /etc/.smbcred
RUN chmod 600 /etc/.smbcred
RUN echo "//svs_ingest_server/Workspace   /mnt/svs_ingest_server/Workspace    cifs    _netdev,users,auto,users,credentials=/etc/.smbcred 0 0" | tee -a /etc/fstab
RUN echo "//svs_ingest_server/tmp   /mnt/svs_ingest_server/tmp    cifs    _netdev,users,auto,users,credentials=/etc/.smbcred 0 0" | tee -a /etc/fstab
VOLUME ["/var/www/html", "/storage", "/var/log"]

 # Start process
CMD apache2 -DFOREGROUND -f /etc/apache2/apache2.$APPLICATION_ENV.conf
```

### Actual behavior
1 - Download all missing images is ok.
2 - Running APT-GET install command is ok, but at some point, Docker for Mac unexpectedly crash
### Information

Diagnostic ID: 3EEA13E7-7514-4942-B784-9E84659E69CD
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Build my dockerfile from a fresh clean install of Docker for mac. (I have reset to factory docker before doing this)
2. Docker crash before the end of the build. (tested multiple time): Fatal Error : vmstateevent invalid json:

**Comment by dsheets** [comment] 2016-08-11 09:26
Duplicate of #64.

**Closed by dsheets** 2016-08-11 09:26 UTC

**Comment by djs55** [comment] 2016-09-15 16:25
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
