### ISSUE TITLE
Segementation fault on mac with m1 processor and rosetta emulation when using php-opcache

### ISSUE THREAD

**Issue by timohund** [docker/for-mac#6887] opened 2023-06-23 12:32 UTC
### Description

When i use php-opcache on centos, with rosetta emulation on a mac with an m1 processor i get a segmentation fault.
When i skip `yum install -y php-opcache` composer self-update and all other composer commands are working fine.

Exactly the same commands work fine for my colleagues using a native ubuntu linux environment

### Reproduce

docker run --platform=linux/amd64  -it centos:7

yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum-config-manager --enable remi-php81
yum update -y
yum install -y php
yum install -y php-opcache

curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer self-update 2.2.9

### Expected behavior

No segementation fault (als without php-opcache)

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/xxx/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/xxx/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/xxx/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/xxx/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-scout

Server:
 Containers: 15
  Running: 0
  Paused: 0
  Stopped: 15
 Images: 4
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 9.718GiB
 Name: docker-desktop
 ID: a91bf446-bbc4-4e77-81db-d373d73984f5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

91397CA7-A564-4DC7-B5AD-2FD5B7EDBDE6/20230623122927

**Comment by araeuchle** [comment] 2023-06-23 13:36
I can confirm this. On Linux Ubuntu for example it works like a charm but on MacOs with M1 chip it fails!

**Comment by bsousaa** [comment] 2023-06-26 10:05
Deactivating "Virtualization Framework" under General Settings solves the issue. I'm raising internally at Docker for better understanding.

**Comment by bsousaa** [comment] 2023-06-27 15:13
Make sure you install the latest macOS updates. Just tested with macOS Ventura 13.4.1 (22F82) and it works.

**Comment by bsousaa** [comment] 2023-07-25 10:43
That's strange @NiklasBr, I just upgraded to Mac OS 13.5 and tested with the latest Docker Desktop with Virtualization Framework and Rosetta emulation enabled. Anyone else is facing the issue with the latest Mac OS updates?

**Comment by bschuhmann** [comment] 2023-08-14 16:12
macOS 13.5 and DD 4.22.0. I have the problem with a amd64 image with apache and Rosetta enabled, not sure about opcache though yet. When disabling Rosetta, the same image works as expected after restart.

**Comment by dzuelke** [comment] 2023-10-03 10:07
It's gotten worse now on macOS Sonoma and Docker 4.24; the crash will occur right at the start of a `composer install`, not at the end:

> ```
> rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
> ```

**Comment by dgageot** [comment] 2023-11-21 07:44
Closing as duplicate of https://github.com/docker/for-mac/issues/7037

**Closed by dgageot** 2023-11-21 07:44 UTC
Labels: status/triage, area/m1, area/emulation, version/4.20.1
