### ISSUE TITLE
Fatal error: vmstateevent invalid json: 

### ISSUE THREAD

**Issue by simonmd** [docker/for-mac#86] opened 2016-08-02 23:34 UTC
### Actual behavior
Error appears with no activity

### Information

Diagnostic ID: 6E55A639-AB04-480D-8F1A-74D7C28712AA
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Nothing. Error appears spontaneously without using docker and no containers up.

**Comment by dsheets** [comment] 2016-08-03 10:15
Thank you for the diagnostic report. I am closing this as a duplicate of #80.

**Closed by dsheets** 2016-08-03 10:15 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
