### ISSUE TITLE
Bind mounts: if an open directory is deleted and recreated, the new directory malfunctions

### ISSUE THREAD

**Issue by felixboehm** [docker/for-mac#69] opened 2016-08-02 09:46 UTC
### Expected behavior

1. mount volume
2. able to write to volume in container

### Actual behavior

1. mount volume
2. can't create folder in mounted folder

The weird thing is, this happens only sometimes, when 
removing `data` folder on the host & restarting container. 

Restarting same image (down, up) does not result in same predictable state.

### Information

Diagnostic ID: 3FC76A70-4011-4D1E-B91D-2D6BE3AEDF7F
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.4 (Build 15E65)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

```
docker run --rm -v $(pwd)/data:/data:z -ti ubuntu bash
root@c444e9d68510:/# ll
total 73
drwxr-xr-x  34 root root 4096 Aug  2 09:34 ./
drwxr-xr-x  34 root root 4096 Aug  2 09:34 ../
-rwxr-xr-x   1 root root    0 Aug  2 09:34 .dockerenv*
drwxr-xr-x   2 root root 4096 Jul 13 08:23 bin/
drwxr-xr-x   2 root root 4096 Apr 12 20:14 boot/
drwxr-xr-x   2 root root   68 Aug  2 09:34 data/
drwxr-xr-x   5 root root  380 Aug  2 09:34 dev/
drwxr-xr-x  45 root root 4096 Aug  2 09:34 etc/
drwxr-xr-x   2 root root 4096 Apr 12 20:14 home/
drwxr-xr-x   8 root root 4096 Sep 13  2015 lib/
drwxr-xr-x   2 root root 4096 Jul 13 08:22 lib64/
drwxr-xr-x   2 root root 4096 Jul 13 08:22 media/
drwxr-xr-x   2 root root 4096 Jul 13 08:22 mnt/
drwxr-xr-x   2 root root 4096 Jul 13 08:22 opt/
dr-xr-xr-x 128 root root    0 Aug  2 09:34 proc/
drwx------   2 root root 4096 Jul 13 08:23 root/
drwxr-xr-x   5 root root 4096 Jul 13 08:23 run/
drwxr-xr-x   2 root root 4096 Jul 22 15:19 sbin/
drwxr-xr-x   2 root root 4096 Jul 13 08:22 srv/
dr-xr-xr-x  12 root root    0 Aug  2 09:29 sys/
drwxrwxrwt   2 root root 4096 Jul 13 08:23 tmp/
drwxr-xr-x  11 root root 4096 Jul 22 15:19 usr/
drwxr-xr-x  13 root root 4096 Jul 22 15:19 var/
root@c444e9d68510:/# cd data/
root@c444e9d68510:/data# mkdir test
mkdir: cannot create directory 'test': No such file or directory
```

- tried different volume labels (none, Z, z)
- tried starting via docker-compose, which creates folder `data`
- tried starting without compose

More tries:

```
<x> <master> # docker run --rm -v $(pwd)/data:/data:z -ti ubuntu bash
root@1b19b56ec6ca:/# cd data/
root@1b19b56ec6ca:/data# mkdir test
mkdir: cannot create directory 'test': No such file or directory
root@1b19b56ec6ca:/data# exit
exit

<x> <master> # docker run --rm -v $(pwd)/data:/data2:z -ti ubuntu bash
root@c94b5769b7c5:/# mkdir /data2/test
mkdir: cannot create directory '/data2/test': No such file or directory
root@c94b5769b7c5:/# exit
exit

<x> <master> # docker run --rm -v $(pwd)/data2:/data2:z -ti ubuntu bash
root@3f2b33fd5856:/# mkdir data2/test
root@3f2b33fd5856:/# exit
exit

<x> <master> # docker run --rm -v $(pwd)/data2:/data2:z -ti ubuntu bash
root@c89cce836559:/# mkdir data2/test
root@c89cce836559:/# exit
exit

<x> <master> # docker run --rm -v $(pwd)/data2:/data2:z -ti ubuntu bash
root@d469edd3c2a0:/# mkdir data2/test
mkdir: cannot create directory 'data2/test': File exists
```

**Comment by felixboehm** [comment] 2016-08-03 17:12
Will retest with todays new version.

**Comment by dsheets** [comment] 2016-08-03 18:03
That would be excellent, thank you. My initial intuition about your report is that it corresponds to another defect I'm tracking and working on fix for right now but perhaps not as we don't have a reliable reproducer. Thanks!

**Comment by felixboehm** [comment] 2016-08-08 15:19
Still an issue. Workaround: use another folder on the host (data1, data2, data3, ...)
- rm and mkdir same folder on the host is not solving the issue.
- `docker volume rm $(docker volume ls -q)`  not helping

**Comment by josketres** [comment] 2016-08-29 13:15
I've been having similar problems. It's also difficult to reproduce.
After restarting docker the problem is solved, but it happens again later.

The last time that we were analysing it, we could find out that the virtual machine where docker is running was also not able to write in the broken directory.

```sh
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty  -R
touch /Users/myuser/data/foo 
# this was failing
```

If I can reproduce it soon I'll add more information!

**Comment by josketres** [comment] 2016-08-29 15:39
I could reproduce this issue. 
Follow the instructions here https://gist.github.com/josketres/0411cd3eaf83cb193f817bc96a330648

**Comment by dsheets** [comment] 2016-09-01 08:55
This should be fixed in Beta 24 and will reach the stable channel within the next week. Could you please try Beta 24?

**Closed by dsheets** 2016-09-01 08:55 UTC
Labels: area/mounts, kind/bug

**Comment by felixboehm** [comment] 2016-09-01 19:00
Sure, will do.
