### ISSUE TITLE
Slow (>5sec) DNS resolution with curl

### ISSUE THREAD

**Issue by bandesz** [docker/for-mac#1112] opened 2017-01-06 16:32 UTC
**Description**

On Docker for Mac since the latest update (1.12.5) the DNS resolution is really slow with libcurl. We can see resolution times little over 5 seconds. This happens on everyone's laptop consistently who upgraded to 1.12.5. (Also I didn't find the previous release anywhere (1.12.3), can we download that from somewhere?)

We tried the beta channel as well, but no luck.

**Steps to reproduce the issue:**
1. Start e.g. a debian container and install curl
2. curl --trace-time -v https://google.com

**Describe the results you received:**

[...]
15:03:29.175495 * Hostname was NOT found in DNS cache
15:03:34.722908 *   Trying 216.58.198.238...
[...]

As you can see DNS resolution takes >5 seconds. We see the same results from our node.js app.

If I run nslookup or ping it responds quickly as expected.

**Describe the results you expected:**

DNS resolution should be miliseconds. If I run the same container but with "--dns 8.8.8.8" the DNS resolution will be quick as expected (the same curl call I mean).

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens consistently on multiple different Macbooks. My OS X version is 10.12.2.

Contents of /etc/resolv.conf:
```
domain local
nameserver 192.168.65.1
nameserver 192.168.65.10
nameserver 192.168.65.9
nameserver 192.168.65.8
nameserver 192.168.65.7
nameserver 192.168.65.6
nameserver 192.168.65.5
nameserver 192.168.65.4
nameserver 192.168.65.3
```

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 7UPW:NUYF:NA2F:ZJGU:STME:6VU5:Q5M2:RHBB:GX7C:6TNA:S6MN:N7HY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 29
 System Time: 2017-01-06T15:08:14.181376688Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: bandesz
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by wujashek** [comment] 2017-01-10 14:48
Confirmed. For example wordpress is not usable now.

**Comment by sethvargo** [comment] 2017-01-12 19:43
I'm able to confirm this as well. Here's a very simple script to demonstrate:

```
$ docker run --rm -it python:3.6.0 /bin/sh -c 'curl -sLo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py && chmod +x speedtest-cli && ./speedtest-cli'
Retrieving speedtest.net configuration...
Testing from Verizon Fios (74.109.238.128)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Comcast (Pittsburgh, PA) [6.56 km]: 38.126 ms
Testing download speed................................................................................
Download: 3.93 Mbit/s
Testing upload speed....................................................................................................
Upload: 3.93 Mbit/s
```

Specifying the `--dns` option brings me much closer to my "real" bandwidth:

```text
$ docker run --rm -it --dns=8.8.8.8 python:3.6.0 /bin/sh -c 'curl -sLo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py && chmod +x speedtest-cli && ./speedtest-cli'
Retrieving speedtest.net configuration...
Testing from Verizon Fios (74.109.238.128)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Comcast (Pittsburgh, PA) [6.56 km]: 43.363 ms
Testing download speed................................................................................
Download: 89.88 Mbit/s
Testing upload speed....................................................................................................
Upload: 31.96 Mbit/s
```

I've also tested with `--network=host`, but that did not make a difference.

**Comment by dsheets** [comment] 2017-01-17 10:40
I can reproduce the behavior you are seeing on 1.12.6 (stable channel). On Beta 37, I cannot reproduce this behavior and there have been many DNS improvements on the beta channel since stable branched from Beta 29.2. If you are comfortable running the beta channel (it's pretty solid), I recommend switching to it to get the latest bug fixes. Otherwise, a new synchronizing stable release should be available in the next week or so that should correct this issue.

**Comment by samoht** [comment] 2017-01-30 20:16
This should now be fixed on the stable and beta channel. Please re-open the issue with a new diagnostic ID if the issue still persists for you.

**Closed by samoht** 2017-01-30 20:16 UTC
Labels: area/network, kind/bug, kind/performance, status/4-fix-released-beta, version/1.12.6
