### ISSUE TITLE
Docker Engine UI shows starting even after ready

### ISSUE THREAD

**Issue by Nithanaroy** [docker/for-mac#1108] opened 2017-01-05 09:34 UTC
### Expected behavior
Docker Engine UI should update to started

### Actual behavior
Docker Engine UI shows starting

### Information
- Diagnostic ID: 614DD267-4370-49B2-9C27-42CD43E5F5AD

### Steps to reproduce the behavior
  1. Start Docker Engine
  2. Change VPN or Network while docker engine is running
  3. Restart engine and UI does not update though the engine is ready to take commands

**Comment by dsheets** [comment] 2017-01-16 16:35
I see several critical errors in your log files. It looks like there were crashes in the process that manages the hypervisor and the virtual block device driver. This looks like the same issue as #1143. Thank you for your report, it has helped us find a pattern of behavior and prioritize fixing this issue. I'm going to close this issue as a duplicate of #1143 to help us manage the issue tracker better. Please subscribe to that issue for further updates.

**Closed by dsheets** 2017-01-16 16:35 UTC
Labels: osx/10.12.x, status/0-triage, version/1.12.5
