### ISSUE TITLE
Error running containers with CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE

### ISSUE THREAD

**Issue by mqasimsarfraz** [docker/for-mac#6883] opened 2023-06-20 09:25 UTC
### Description

I am getting an error starting a container with `CAP_PERFMON`, `CAP_BPF`, and `CAP_CHECKPOINT_RESTORE` capabilities. 

### Reproduce

```
→ docker run --cap-add CAP_BPF hello-world
docker: Error response from daemon: invalid CapAdd: capability not supported by your kernel or not available in the current environment: "CAP_BPF".
See 'docker run --help'.
```

### Expected behavior

```
→ docker run --cap-add CAP_BPF hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete 
Digest: sha256:c2e23624975516c7e27b1b25be3682a8c6c4c0cea011b791ce98aa423b5040a0
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
...
...
```

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false

Server:
 Containers: 23
  Running: 1
  Paused: 0
  Stopped: 22
 Images: 112
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 766fd531-2ae0-451e-a007-a83c4bb02e42
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

49A8C3F1-BC71-4652-AD90-9A43A1FEBA6C/20230620092103

### Additional Info

I see that linuxkit services were missing `CAP_PERFMON`, `CAP_BPF`, and `CAP_CHECKPOINT_RESTORE` and was recently [added](https://github.com/linuxkit/linuxkit/pull/3931) using `gocapability`. I believe after these changes the OCI config will now include them if user specifies [all](https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.yml#L87) in capabilities for service containers so perhaps we need to pull in these changes?

**Comment by mqasimsarfraz** [comment] 2023-06-26 09:53
I was able to confirm that `CAP_PERFMON`, `CAP_BPF`, and `CAP_CHECKPOINT_RESTORE` were actually missing from my docker service OCI spec:

```bash
$ docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
$ ctr -n services.linuxkit c info docker
{
    "ID": "docker",
    "Labels": null,
    "Image": "",
    "Runtime": {
        "Name": "io.containerd.runc.v2",
        "Options": null
    },
    "SnapshotKey": "",
    "Snapshotter": "",
    "CreatedAt": "2023-06-26T09:27:24.833733333Z",
    "UpdatedAt": "2023-06-26T09:27:24.833733333Z",
    "Extensions": {},
    "SandboxID": "",
    "Spec": {
        "ociVersion": "1.0.2-dev",
        "process": {
            "user": {
                "uid": 0,
                "gid": 0
            },
            "args": [
                "/usr/libexec/docker/docker-init",
                "/usr/bin/entrypoint.sh"
            ],
            "env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "KUBECONFIG=/etc/kubernetes/admin.conf"
            ],
            "cwd": "/",
            "capabilities": {
                "bounding": [
                    "CAP_AUDIT_CONTROL",
                    "CAP_AUDIT_READ",
                    "CAP_AUDIT_WRITE",
                    "CAP_BLOCK_SUSPEND",
                    "CAP_CHOWN",
                    "CAP_DAC_OVERRIDE",
                    "CAP_DAC_READ_SEARCH",
                    "CAP_FOWNER",
                    "CAP_FSETID",
                    "CAP_IPC_LOCK",
                    "CAP_IPC_OWNER",
                    "CAP_KILL",
                    "CAP_LEASE",
                    "CAP_LINUX_IMMUTABLE",
                    "CAP_MAC_ADMIN",
                    "CAP_MAC_OVERRIDE",
                    "CAP_MKNOD",
                    "CAP_NET_ADMIN",
                    "CAP_NET_BIND_SERVICE",
                    "CAP_NET_BROADCAST",
                    "CAP_NET_RAW",
                    "CAP_SETFCAP",
                    "CAP_SETGID",
                    "CAP_SETPCAP",
                    "CAP_SETUID",
                    "CAP_SYSLOG",
                    "CAP_SYS_ADMIN",
                    "CAP_SYS_BOOT",
                    "CAP_SYS_CHROOT",
                    "CAP_SYS_MODULE",
                    "CAP_SYS_NICE",
                    "CAP_SYS_PACCT",
                    "CAP_SYS_PTRACE",
                    "CAP_SYS_RAWIO",
                    "CAP_SYS_RESOURCE",
                    "CAP_SYS_TIME",
                    "CAP_SYS_TTY_CONFIG",
                    "CAP_WAKE_ALARM"
                ],
                "effective": [
                    "CAP_AUDIT_CONTROL",
                    "CAP_AUDIT_READ",
                    "CAP_AUDIT_WRITE",
                    "CAP_BLOCK_SUSPEND",
                    "CAP_CHOWN",
                    "CAP_DAC_OVERRIDE",
                    "CAP_DAC_READ_SEARCH",
                    "CAP_FOWNER",
                    "CAP_FSETID",
                    "CAP_IPC_LOCK",
                    "CAP_IPC_OWNER",
                    "CAP_KILL",
                    "CAP_LEASE",
                    "CAP_LINUX_IMMUTABLE",
                    "CAP_MAC_ADMIN",
                    "CAP_MAC_OVERRIDE",
                    "CAP_MKNOD",
                    "CAP_NET_ADMIN",
                    "CAP_NET_BIND_SERVICE",
                    "CAP_NET_BROADCAST",
                    "CAP_NET_RAW",
                    "CAP_SETFCAP",
                    "CAP_SETGID",
                    "CAP_SETPCAP",
                    "CAP_SETUID",
                    "CAP_SYSLOG",
                    "CAP_SYS_ADMIN",
                    "CAP_SYS_BOOT",
                    "CAP_SYS_CHROOT",
                    "CAP_SYS_MODULE",
                    "CAP_SYS_NICE",
                    "CAP_SYS_PACCT",
                    "CAP_SYS_PTRACE",
                    "CAP_SYS_RAWIO",
                    "CAP_SYS_RESOURCE",
                    "CAP_SYS_TIME",
                    "CAP_SYS_TTY_CONFIG",
                    "CAP_WAKE_ALARM"
                ],
                "inheritable": [
                    "CAP_AUDIT_CONTROL",
                    "CAP_AUDIT_READ",
                    "CAP_AUDIT_WRITE",
                    "CAP_BLOCK_SUSPEND",
                    "CAP_CHOWN",
                    "CAP_DAC_OVERRIDE",
                    "CAP_DAC_READ_SEARCH",
                    "CAP_FOWNER",
                    "CAP_FSETID",
                    "CAP_IPC_LOCK",
                    "CAP_IPC_OWNER",
                    "CAP_KILL",
                    "CAP_LEASE",
                    "CAP_LINUX_IMMUTABLE",
                    "CAP_MAC_ADMIN",
                    "CAP_MAC_OVERRIDE",
                    "CAP_MKNOD",
                    "CAP_NET_ADMIN",
                    "CAP_NET_BIND_SERVICE",
                    "CAP_NET_BROADCAST",
                    "CAP_NET_RAW",
                    "CAP_SETFCAP",
                    "CAP_SETGID",
                    "CAP_SETPCAP",
                    "CAP_SETUID",
                    "CAP_SYSLOG",
                    "CAP_SYS_ADMIN",
                    "CAP_SYS_BOOT",
                    "CAP_SYS_CHROOT",
                    "CAP_SYS_MODULE",
                    "CAP_SYS_NICE",
                    "CAP_SYS_PACCT",
                    "CAP_SYS_PTRACE",
                    "CAP_SYS_RAWIO",
                    "CAP_SYS_RESOURCE",
                    "CAP_SYS_TIME",
                    "CAP_SYS_TTY_CONFIG",
                    "CAP_WAKE_ALARM"
                ],
                "permitted": [
                    "CAP_AUDIT_CONTROL",
                    "CAP_AUDIT_READ",
                    "CAP_AUDIT_WRITE",
                    "CAP_BLOCK_SUSPEND",
                    "CAP_CHOWN",
                    "CAP_DAC_OVERRIDE",
                    "CAP_DAC_READ_SEARCH",
                    "CAP_FOWNER",
                    "CAP_FSETID",
                    "CAP_IPC_LOCK",
                    "CAP_IPC_OWNER",
                    "CAP_KILL",
                    "CAP_LEASE",
                    "CAP_LINUX_IMMUTABLE",
                    "CAP_MAC_ADMIN",
                    "CAP_MAC_OVERRIDE",
                    "CAP_MKNOD",
                    "CAP_NET_ADMIN",
                    "CAP_NET_BIND_SERVICE",
                    "CAP_NET_BROADCAST",
                    "CAP_NET_RAW",
                    "CAP_SETFCAP",
                    "CAP_SETGID",
                    "CAP_SETPCAP",
                    "CAP_SETUID",
                    "CAP_SYSLOG",
                    "CAP_SYS_ADMIN",
                    "CAP_SYS_BOOT",
                    "CAP_SYS_CHROOT",
                    "CAP_SYS_MODULE",
                    "CAP_SYS_NICE",
                    "CAP_SYS_PACCT",
                    "CAP_SYS_PTRACE",
                    "CAP_SYS_RAWIO",
                    "CAP_SYS_RESOURCE",
                    "CAP_SYS_TIME",
                    "CAP_SYS_TTY_CONFIG",
                    "CAP_WAKE_ALARM"
                ]
            }
        },
        "root": {
            "path": "/containers/services/docker/rootfs"
        },
        "mounts": [
            {
                "destination": "/dev",
                "type": "bind",
                "source": "/dev",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/dev/pts",
                "type": "devpts",
                "source": "devpts",
                "options": [
                    "nosuid",
                    "noexec",
                    "newinstance",
                    "ptmxmode=0666",
                    "mode=0620"
                ]
            },
            {
                "destination": "/etc/cni/net.d",
                "type": "bind",
                "source": "/var/lib/cni/conf",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/etc/kube-images",
                "type": "bind",
                "source": "/etc/kube-images",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/etc/kubernetes",
                "type": "bind",
                "source": "/var/lib/kubeadm",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/etc/os-release",
                "type": "bind",
                "source": "/etc/os-release",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/etc/resolv.conf",
                "type": "bind",
                "source": "/run/resolvconf/resolv.conf",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/etc/vpnkit-expose-port.json",
                "type": "bind",
                "source": "/etc/vpnkit-expose-port.json",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/lib/modules",
                "type": "bind",
                "source": "/lib/modules",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/proc",
                "type": "proc",
                "source": "proc",
                "options": [
                    "nosuid",
                    "nodev",
                    "noexec",
                    "relatime"
                ]
            },
            {
                "destination": "/run/config",
                "type": "bind",
                "source": "/run/config",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/run/desktop",
                "type": "bind",
                "source": "/run/desktop",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/run/guest-services",
                "type": "bind",
                "source": "/run/guest-services",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/run/host-services",
                "type": "bind",
                "source": "/run/host-services",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/sys",
                "type": "sysfs",
                "source": "sysfs",
                "options": [
                    "nosuid",
                    "noexec",
                    "nodev"
                ]
            },
            {
                "destination": "/sys/fs/cgroup",
                "type": "bind",
                "source": "/sys/fs/cgroup",
                "options": [
                    "rw",
                    "rbind",
                    "rshared",
                    "nosuid",
                    "noexec",
                    "nodev",
                    "relatime"
                ]
            },
            {
                "destination": "/usr/bin/lifecycle-server",
                "type": "bind",
                "source": "/usr/bin/lifecycle-server",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/usr/bin/logwrite",
                "type": "bind",
                "source": "/usr/bin/logwrite",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/usr/bin/transfused",
                "type": "bind",
                "source": "/usr/bin/transfused",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/usr/lib/wsl",
                "type": "bind",
                "source": "/usr/lib/wsl",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/usr/libexec/kubernetes/kubelet-plugins",
                "type": "bind",
                "source": "/var/lib/kubelet-plugins",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/var/lib",
                "type": "bind",
                "source": "/var/lib",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/var/log",
                "type": "bind",
                "source": "/var/log",
                "options": [
                    "rshared",
                    "rbind",
                    "rbind"
                ]
            },
            {
                "destination": "/var/run/linuxkit-containerd/containerd.sock",
                "type": "bind",
                "source": "/run/containerd/containerd.sock",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            },
            {
                "destination": "/var/run/linuxkit-external-logging.sock",
                "type": "bind",
                "source": "/run/linuxkit-external-logging.sock",
                "options": [
                    "rw",
                    "rbind",
                    "rshared"
                ]
            }
        ],
        "linux": {
            "resources": {
                "devices": [
                    {
                        "allow": true,
                        "type": "a",
                        "access": "rwm"
                    }
                ]
            },
            "cgroupsPath": "podruntime/docker",
            "namespaces": [
                {
                    "type": "network",
                    "path": "/run/netns/docker"
                },
                {
                    "type": "mount"
                }
            ],
            "rootfsPropagation": "shared"
        }
    }
}
```

So updating linuxkit should fix the issue. I am wondering if there can be a workaround for this before we get an actual fix?

**Comment by dgageot** [comment] 2024-01-04 16:29
I'm going to close this issue because it was fixed. At least, I can't reproduce with 4.26.1.
Feel free to ping us if you think it's not!

**Closed by dgageot** 2024-01-04 16:29 UTC
Labels: status/triage, area/kernel, version/4.20.1
