### ISSUE TITLE
Cannot connect and run any image

### ISSUE THREAD

**Issue by alexei-led** [docker/for-mac#123] opened 2016-08-04 09:25 UTC
### Information

Diagnostic ID: 3E203992-7C63-4973-A8CE-00C00AE7B500
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment] 2016-08-09 02:15
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:15 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
