### ISSUE TITLE
Docker Desktop 2.5.0.1 (49550) high fan speed MBP 16"

### ISSUE THREAD

**Issue by karolistamutis** [docker/for-mac#5098] opened 2020-12-03 21:24 UTC
Is anyone running Docker Desktop on their MBP without their fans going hair dryer mode? I've tried the tricks with removing Volumes because supposedly this is caused by fs sync calls as per https://github.com/docker/for-mac/issues/3499 but no luck. Whenever I launch DD I have to put my headphones on, I can't believe I'm the only one?

2019 16" base MBP

**Comment by justice47** [comment] 2020-12-03 22:55
So , you have high com.docker.hyperkit usage, right?

**Comment by stephen-turner** [comment] 2020-12-04 09:48
This is probably a dupe of #5044: high CPU caused by the new Linux kernel. You could try the experimental build posted near the bottom of that ticket.

**Closed by stephen-turner** 2020-12-04 09:48 UTC
