### ISSUE TITLE
Permissions / Ownerships gets masked for volume mounts

### ISSUE THREAD

**Issue by DanielSchwiperich** [docker/for-mac#2657] opened 2018-03-03 19:09 UTC
### Expected behavior

In Container: A file created in a volume mount as root user will have 0:0 uid and guid on the host system and container
In Host: A file created in a dir which is mounted in a container will have 501:20 (or whatever your current host user and group id is) on the host and container 

### Actual behavior

A file created in the container at the volume mount as root user has 0:0 in the container but 501:20 on the host system

A file created on the host at the location of the volume mount as current system user has 501:20 locally but 0:0 in the container

(I also tested other user like www-data in the container. same results)

### Information

`Docker version 17.12.0-ce, build c97c6d6`
`Docker version 18.02.0-ce-rc1, build 5e1d90a`
`Docker version 17.12.0-ce, build c97c6d6`

Tested on the different macs running above versions. Test with raw and qcow

### Steps to reproduce the behavior

  1. From a host dir of your choice run `touch test.txt`
  2. Then run `docker run -it --rm --name mount-test -v "$PWD":/test -w /test alpine:latest /bin/ash` 
 3. Run `ls -l` or `ls -ln` in the container and see that test.txt belong to the current container user and not the host user
 4. Run `touch test2.txt`, go back to the host system dir and see that test2.txt belong to the host user and group (and also test.txt)

### More infos

It's not only for root, you can also use other users like `games`: `docker run -itu games --rm --name mount-test -v "$PWD":/test -w /test alpine:latest /bin/ash`

And it's also not for alpine images. Tested a debian based and others like php-cli too.

Maybe I missed some big news, and would be glad if some one could point me to it. 
A linux colleague couldn't confirm, main diff we noticed was he was not using overlay2 but aufs as storage driver but as far as I understand storage driver is not used on volumes? (He just had time for a quick test, so no more info and I don't have access to a linux pc right now)

If this is a bug it would actually solve a big `problem`  like described here https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by thorstensiefert** [comment] 2018-03-04 17:31
I have observed the same behavior and can only support the said.

**Comment by djs55** [comment] 2018-03-07 17:11
Hi,

I believe this behaviour is expected on the Mac. The [Ownership](https://docs.docker.com/docker-for-mac/osxfs/) section of the file sharing documentation says that

> Initially, any containerized process that requests ownership metadata of an object is told that its uid and gid own the object. When any containerized process changes the ownership of a shared file system object, such as by using the chown command, the new ownership information is persisted in the com.docker.owner extended attribute of the object. Subsequent requests for ownership metadata return the previously set values. Ownership-based permissions are only enforced at the macOS file system level with all accessing processes behaving as the user running Docker. If the user does not have permission to read extended attributes on an object (such as when that object’s permissions are 0000), osxfs attempts to add an access control list (ACL) entry that allows the user to read and write extended attributes. If this attempt fails, the object appears to be owned by the process accessing it until the extended attribute is readable again.

The goals of the design are:
- to not require root on the host (therefore we can't create files owned by root)
- to guarantee that processes in the container can read any files which are both
  - readable by the host user running Docker (Note Docker runs as a regular user on the Mac, not root)
  - explicitly shared with the container (via `-v`, filtered through the list of paths in the Whale menu -> Preferences -> File sharing)

Looking at the "handling permissions with docker volumes" link, this mechanism is intended to fix the "permissions problem" that it describes. I think the main problem is that this feature is Mac only (so far).

Since I think it's working as designed I'll close this ticket but if there's still a problem, let me know or create another ticket.

Thanks for your report!

**Closed by djs55** 2018-03-07 17:11 UTC
