### ISSUE TITLE
rw mount nested under ro mount is not writeable anymore

### ISSUE THREAD

**Issue by mvdbeek** [docker/for-mac#5778] opened 2021-06-22 15:53 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Can create file in nested rw mount

### Actual behavior

Fails with permission error

### Information

This is a new problem that appeared after updating docker for desktop

  - macOS Version: 11.2.3 
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.4.0

### Steps to reproduce the behavior

```console
$ mkdir -p ro/rw
$ docker run  -v $PWD/ro:/ro:ro -v $PWD/ro/rw:/ro/rw:rw bash touch ro/rw/x
touch: ro/rw/x: Operation not permitted
```

**Comment by stephen-turner** [comment] 2021-06-22 16:25
Thanks for the report, I believe this is a dupe of #5748.

**Closed by stephen-turner** 2021-06-22 16:25 UTC
