### ISSUE TITLE
No way to programatically manage Experimental Features

### ISSUE THREAD

**Issue by sethatron** [docker/for-mac#5129] opened 2020-12-14 16:03 UTC
### Expected behavior
There should be some way to disable experimental features at run-time.

**Comment by sethatron** [comment] 2020-12-14 16:04
Not really much to say on this. Experiemtnal features are enabled by default (namely, gRPC FUSE) and we would like to be able to disable this outside of the GUI without having to modify a .json file

**Comment by stephen-turner** [comment] 2020-12-14 17:42
Thanks for the feature request. This is a dupe of docker/roadmap#172. So I'll close this one, but please add a thumbs-up to that ticket to help prioritise it.

**Closed by stephen-turner** 2020-12-14 17:42 UTC
