### ISSUE TITLE
kubectl shows duplicate contexts docker-desktop and docker-for-desktop

### ISSUE THREAD

**Issue by tekumara** [docker/for-mac#4089] opened 2019-12-02 08:00 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1D52253A-06BD-4ECA-8188-316BAD9AFDD9/20191202075540

### Expected behavior

Only one kubernetes context is shown.

### Actual behavior

Duplicate contexts are shown and I'm confused as to which one to use.

```
$ kubectl config get-contexts
CURRENT   NAME                 CLUSTER          AUTHINFO         NAMESPACE
*         docker-desktop       docker-desktop   docker-desktop
          docker-for-desktop   docker-desktop   docker-desktop
```

### Information

  - macOS Version: 10.14.6 (18G1012)

### Diagnostic logs

```
Docker for Mac: version... 2.1.0.5 (40693) stable

```

### Steps to reproduce the behavior

  1. Install Docker on macOS (on a new mac)
  2. Run `kubectl config get-contexts`

**Comment by tekumara** [comment] 2019-12-02 08:00
Also occurs on Windows see https://github.com/docker/for-win/issues/5089

**Comment by tekumara** [comment] 2019-12-02 08:03
Docker -> Kubernetes only shows the `docker-desktop` context

<img width="417" alt="Screen Shot 2019-12-02 at 7 02 38 pm" src="https://user-images.githubusercontent.com/125105/69940418-5ebbba80-1536-11ea-8227-a3b1162b5dfd.png">

**Comment by mjgallag** [comment] 2019-12-09 19:29
I have this issue too.

**Comment by adamalex** [comment] 2019-12-18 15:06
Confirmed after new reset of disk image. The contexts _are_ identical at least on my machine, so it doesn't matter which one you use. There should probably be only one of these unless there is a good reason to have both, but in the meantime it's just cosmetic.

**Comment by Justkant** [comment] 2020-01-14 17:02
You can use [`kubectx`](https://github.com/ahmetb/kubectx) to remove the `docker-for-desktop` context.
To remove the context use: `kubectx -d docker-for-desktop`.

If you want to know why I choose to remove `docker-for-desktop` and not `docker-desktop`, I found by looking into my `~/.kube/config` that `docker-for-desktop` was a simple alias for `docker-desktop`

**Comment by michaelsync** [comment] 2020-02-19 00:41
Any update on this issue? Is it something that will be fixed soon?

**Comment by giladsh1** [comment] 2020-02-25 15:05
same issue on MacOs  version 2.2.0.3

**Comment by mlopezd** [comment] 2020-02-28 10:36
Still happens with the latest versions for MacOS:
Docker Desktop: 2.2.0.3
Kubernetes: 1.15.5

**Comment by kinowarrior** [comment] 2020-02-29 11:25
Same with:

Docker Desktop: 2.2.1.0
Kubernetes: 1.15.5

**Comment by hiromaily** [comment] 2020-02-29 13:17
+1

**Comment by davidygs** [comment] 2020-03-14 02:44
same same

**Comment by Janaka-Steph** [comment] 2020-03-28 15:08
`kubectl config delete-context docker-for-desktop` will delete the specified context from the kubeconfig

**Comment by mlopezd** [comment] 2020-04-01 09:30
> `kubectl config delete-context docker-for-desktop` will delete the specified context from the kubeconfig

Yes but I shows up again after restart

**Comment by adescalzo** [comment] 2020-04-08 13:41
> > `kubectl config delete-context docker-for-desktop` will delete the specified context from the kubeconfig
> 
> Yes but it shows up again after restart

Same issue

**Comment by mattqzhang** [comment] 2020-05-08 04:33
Same issue:
Mac version: 10.15.4
Docker desktop: 2.2.0.5
Kubernetes: 1.15.5

**Comment by thaJeztah** [comment] 2020-05-08 08:13
Thanks for reporting! This issue is tracked internally, but you can find more details in this issue in the "docker for windows" issue tracker; https://github.com/docker/for-win/issues/5089

**Comment by IronCore864** [comment] 2020-05-12 09:18
Any workaround?

**Comment by o6uoq** [comment] 2020-05-12 14:35
> Any workaround?

Yes, ignore it! 🙈

**Comment by teebu** [comment] 2020-06-05 17:35
I too am confused by it. In the command line it shows both, but in the app it only shows one. 

```
CURRENT   NAME                 CLUSTER          AUTHINFO         NAMESPACE
          docker-desktop       docker-desktop   docker-desktop
*         docker-for-desktop   docker-desktop   docker-desktop
```

![image](https://user-images.githubusercontent.com/5531844/83906342-3cd70680-a718-11ea-860d-9b0a2b476e54.png)

**Comment by ipleten** [comment] 2020-06-26 16:09
We use 'docker-for-desktop' context for a lot of automation, We choose that one because it was recreated each time we delete it. So which one should be removed 'docker-desktop' or 'docker-for-desktop'? Considering that there are "docker for win", "docker for mac". I suppose that "docker for desktop" is quite logical to leave. ¯\_(ツ)_/¯

**Comment by stephen-turner** [comment] 2020-06-26 16:12
This is fixed in the latest Edge release, 2.3.2.0. We have removed the legacy context name that was there for backwards compatibility.

**Closed by stephen-turner** 2020-06-26 16:12 UTC
Labels: version/10.14.6

**Comment by jakerobb** [comment] 2020-07-14 18:26
> We have removed the legacy context name that was there for backwards compatibility.

Fantastic. Which one is the legacy one? 🙂

**Comment by stephen-turner** [comment] 2020-07-15 14:31
Sorry, docker-for-desktop is the old one, docker-desktop is the new one that you should use.

**Comment by djs55** [comment] 2020-09-30 10:18
The change has now made it to the latest stable version 2.4.0.0 for
[Mac](https://desktop.docker.com/mac/stable/48506/Docker.dmg) and
[Windows](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).
