### ISSUE TITLE
vmstateevent invalid json

### ISSUE THREAD

**Issue by jtoler** [docker/for-mac#221] opened 2016-08-10 23:33 UTC
### Information

Diagnostic ID: F2D9E84F-67F6-4BC6-BC2A-B72BFA9453D8
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A286a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Justin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/F2D9E84F-67F6-4BC6-BC2A-B72BFA9453D8/20160810-193224/qemu-img-check.stdout 2> /tmp/F2D9E84F-67F6-4BC6-BC2A-B72BFA9453D8/20160810-193224/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment] 2016-08-10 23:38
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-10 23:38 UTC

**Comment by djs55** [comment] 2016-09-15 16:25
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
