### ISSUE TITLE
fatal error - vmstateevent invalid json

### ISSUE THREAD

**Issue by bonclay7** [docker/for-mac#278] opened 2016-08-15 04:47 UTC
### Steps to reproduce

Similar to https://github.com/docker/for-mac/issues/276 
```
fatal error - vmstateevent invalid json
```
### Information

```
Diagnostic ID: 5B73B9B3-0623-4D4E-AE9F-54D09F2BC0D2
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment] 2016-08-15 10:10
This is a duplicate of #64 and likely unrelated to #276 (10.12 vs 10.10).

**Closed by dsheets** 2016-08-15 10:10 UTC

**Comment by djs55** [comment] 2016-09-15 16:21
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
