### ISSUE TITLE
Docker crashed, won't start/restart

### ISSUE THREAD

**Issue by seripap** [docker/for-mac#835] opened 2016-10-21 20:04 UTC
### Expected behavior

Docker to start
### Actual behavior

Docker won't start/restart, even after quitting/restarting.
### Information

42ACB14D-5306-48C4-BE0C-0C80F3D834B5

Docker for Mac: version: 1.12.2-beta28 (71c4a00)
OS X: version 10.12 (build: 16A323)
logs: /tmp/42ACB14D-5306-48C4-BE0C-0C80F3D834B5/20161021-155843.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior
- Run docker for mac, attempt to start

**Comment by seripap** [comment] 2016-10-21 20:15
No idea what went wrong, I uninstalled docker and reinstalled the stable version and it seems to work.

**Comment by jtbennett** [comment] 2016-10-24 19:25
I have had this happen many times.  Roughly every few hours of active work with Docker running.  All CLI commands hang. Actions in Kitematic (e.g., clicking Stop on a container) do nothing -- no confirmation, no error, no feedback -- nothing.

The only resolution for me has been to go into Docker prefs and "Reset to factory defaults".  After the restart and setup, it works again.  For a while...

Until Docker 1.12 I was on the beta channel.  I uninstalled and reinstalled from the Stable channel.  I am currently running Docker for Mac Version 1.12.1 (build: 12133)

**Comment by jtbennett** [comment] 2016-10-24 19:30
Diagnostic from my latest instance of this problem: 7B27D0DB-CB3E-4BAD-8C70-3ED2B5C00B58

Same problem as above -- could not upload

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/7B27D0DB-CB3E-4BAD-8C70-3ED2B5C00B58/20161024-152809.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by dawnerd** [comment] 2016-10-27 03:52
Same problem:

BEA11C20-0004-4AA0-AF21-3F4C4C772504

Was noticing some odd behavior in a container and decided to use the restart button. Says it started up but docker doesn't respond.

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/BEA11C20-0004-4AA0-AF21-3F4C4C772504/20161026-204930.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by samoht** [comment] 2016-11-03 22:46
@jtbennett you seem to have hit various bugs related to osxfs and to our some of our Objective-C bindings which should all have been fixed in the latest beta (Beta29.3). Could you try to upgrade and see if it works better for you? Thanks!

@dawnerd your issue is different, could you please open an other ticket to track it? Thanks!

**Comment by jtbennett** [comment] 2016-11-08 17:54
@samoht My freeze/crash issue seems to be fixed with Version 1.12.3-beta29.3 (13640).  However, Docker for Mac is waaaay slower now -- mounted volumes are just too slow.  Switching to docker-machine and VirtualBox for the time being.

**Comment by dsheets** [comment] 2016-11-08 18:00
@jtbennett you may have experienced #668 (with work-around <https://github.com/docker/for-mac/issues/668#issuecomment-250406582>) which is a performance regression of the block storage device. We don't know of any other performance regressions in the last several months.

**Comment by jtbennett** [comment] 2016-11-08 18:36
Thanks, @dsheets . Tried that, but still much slower than a docker-machine VirtualBox vm. Not sure what the cause is -- will try to find time to investigate soon.

**Comment by rogaha** [comment] 2016-11-22 09:42
@jtbennett I'm closing this issue as the issue is fixed since `beta29.3`. Please raise another issue for us to track the `slowness` you are experiencing.

**Closed by rogaha** 2016-11-22 09:42 UTC
Labels: osx/10.12.x, status/0-more-info-needed, status/1-acknowledged, version/beta28
