### ISSUE TITLE
docker pull is very slow from private registry

### ISSUE THREAD

**Issue by jcsalem** [docker/for-mac#472] opened 2016-08-30 23:13 UTC
### Expected behavior

docker pull performance from private registry should be on a par when running the same command on Linux
### Actual behavior

docker pull hangs for about 30 seconds while connecting to a private registry. Once it connects, performance is similar to Linux.

This issue appears similar to https://github.com/docker/toolbox/issues/511 however that occurred with the old docker-machine VBox implementation
### Information

Diagnostic ID: 0EF5E71B-1401-4740-B4FA-51853264E6EA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Set up a private registry
2. Run docker pull to get an image from that registry

**Comment by dave-tucker** [comment] 2016-09-01 15:36
Thanks for the report @jcsalem 
Is your private registry configured by IP or domain name?
I'm wondering if it could be a DNS issue (e.g the first N DNS servers failing to respond and we retrying until we get a response).

**Comment by jcsalem** [comment] 2016-09-05 16:51
It's configured by domain name. I agree it's likely a DNS issue (similar to the issue I cited above https://github.com/docker/toolbox/issues/511).
However, with the new docker4mac, I don't seem to have any access to the docker VM itself so I can't change the DNS configuration. Is there any way to ssh into the xhyve VM?

**Comment by b2jrock** [comment] 2016-09-09 21:04
@jcsalem you can connect using screen: 
```screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty```

**Comment by jcsalem** [comment] 2016-09-16 16:30
So the default DNS config on docker4mac was the problem.  I logged in and saw that `/etc/resolv.conf` had 10 different 192.168.X.Y addresses in there by default. 
I deleted all of them and replaced it with the following file:
```search local
nameserver 8.8.8.8
nameserver 4.2.2.1
```

**Comment by jcsalem** [comment] 2016-09-16 16:31
It would be awesome if I didn't have to do this to get reasonable private registry performance on Docker. BTW, I just tried this on 1.12.1 and the same thing happened.

**Comment by djs55** [comment] 2016-09-16 17:12
@jcsalem could you upload another diagnostics report from 1.12.1? I think the report quoted earlier is from 1.12.0 but the diagnostics in 1.12.1 should provide much more DNS information.

I'd also be interested to see what the outgoing DNS traffic on port 53 looks like. If possible could you grab a trace from your Mac with a command like:
```
$ sudo tcpdump -n  -i en0 port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
18:07:15.203441 IP 172.16.10.163.54326 > 8.8.8.8.53: 4114+ A? www.cam.ac.uk. (31)
18:07:15.219518 IP 8.8.8.8.53 > 172.16.10.163.54326: 4114 1/0/0 A 131.111.150.25 (47)
18:07:15.238647 IP 172.16.10.163.49180 > 8.8.8.8.53: 51874+ AAAA? www.cam.ac.uk. (31)
18:07:15.247232 IP 8.8.8.8.53 > 172.16.10.163.49180: 51874 0/1/0 (88)
18:07:15.248035 IP 172.16.10.163.55893 > 8.8.8.8.53: 62902+ MX? www.cam.ac.uk. (31)
18:07:15.264447 IP 8.8.8.8.53 > 172.16.10.163.55893: 62902 0/1/0 (88)
```
I'd like to see whether DNS queries are being sent to reasonable places, and whether responses are coming back. We added support for having multiple upstream DNS servers recently --perhaps the delay is caused by queries being initially sent to an inappropriate server (as we don't currently support zones as often used by VPNs)

**Comment by jcsalem** [comment] 2016-09-22 21:06
Here are the 1.12.1 diagnostics:
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/0EF5E71B-1401-4740-B4FA-51853264E6EA/20160922-170009.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

Let me know if you need the logs file as well.  
Here's the actual /etc/resolv.conf on the VM:
```
search local
nameserver 192.168.65.1
nameserver 192.168.65.10
nameserver 192.168.65.9
nameserver 192.168.65.8
nameserver 192.168.65.7
nameserver 192.168.65.6
nameserver 192.168.65.5
nameserver 192.168.65.4
nameserver 192.168.65.3
```

**Comment by jcsalem** [comment] 2016-09-22 21:17
And here's the tcpdump you requested from my Mac. I looked up the our private registry domain name:
```
$ sudo tcpdump -n  -i en0 port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:14:18.790085 IP 192.168.0.10.58424 > 208.59.247.45.53: 17649+ A? plugins.komand.net. (36)
17:14:19.051286 IP 208.59.247.45.53 > 192.168.0.10.58424: 17649 3/0/0 CNAME plugins-elb-1927119145.us-east-1.elb.amazonaws.com., A 54.86.37.66, A 52.87.21.44 (132)
17:14:38.369854 IP 192.168.0.10.57628 > 208.59.247.45.53: 29359+ A? plugins-elb-1927119145.us-east-1.elb.amazonaws.com. (68)
17:14:38.370873 IP 192.168.0.10.53159 > 208.59.247.45.53: 49635+ AAAA? plugins-elb-1927119145.us-east-1.elb.amazonaws.com. (68)
17:14:38.388533 IP 208.59.247.45.53 > 192.168.0.10.57628: 29359 2/0/0 A 54.86.37.66, A 52.87.21.44 (100)
17:14:38.571175 IP 208.59.247.45.53 > 192.168.0.10.53159: 49635 0/1/0 (150)
17:14:46.430560 IP 192.168.0.10.54469 > 208.59.247.45.53: 56463+ A? plugins-elb-1927119145.us-east-1.elb.amazonaws.com. (68)
17:14:46.681279 IP 208.59.247.45.53 > 192.168.0.10.54469: 56463 2/0/0 A 52.87.21.44, A 54.86.37.66 (100)
```

**Comment by djs55** [comment] 2016-11-18 13:33
Thanks for your patience and your help so far. The DNS forwarder was revamped in beta 30.1 to fix several DNS problems, including one which could cause performance problems. If you have the time, could you give it a try and -- if the problem still manifests -- upload another diagnostics report? The new beta includes better diagnostics too.

Thanks again for your patience with us.

**Comment by jcsalem** [comment] 2016-11-22 15:52
Thanks, @djs55. 
I'm not able to reproduce the performance problem, even on 1.12.3. 
I will try it on the beta at some point but for now, I think you can assume my issue is resolved.

**Comment by djs55** [comment] 2016-11-23 10:18
Thanks for the update- I'll close this issue for now.

**Closed by djs55** 2016-11-23 10:18 UTC
Labels: area/network, kind/performance, osx/10.11.x, status/0-more-info-needed, status/1-acknowledged, version/1.12.0
