### ISSUE TITLE
Unable to update from 3.3.1 to newer version

### ISSUE THREAD

**Issue by flowl** [docker/for-mac#5677] opened 2021-05-11 12:23 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

Docker Desktop for Mac 3.3.1 (63452)
Engine 20.10.5
Compose 1.29.0

After hitting "Download update" and "Update and restart",
the menu item to "Download update" and "Update and restart" still show up.

"Update and restart" doesn't do anything other than restart.

Tried several times in the past days, restarted my macbook,... no error message, the program is just restarting without any update.

![Screenshot 2021-05-10 at 13 12 42](https://user-images.githubusercontent.com/4543262/117650836-7ec2c500-b191-11eb-9a6c-e2a940f93221.png)

**Comment by stusmall** [comment] 2021-05-11 17:30
I'm hitting the same issue. Here is an interesting clue, on the Update screen the version is ()

<img width="691" alt="Screen Shot 2021-05-11 at 11 27 44 AM" src="https://user-images.githubusercontent.com/1697444/117859414-2ef50400-b24c-11eb-8035-6518d5e975d9.png">

**Comment by deltamualpha** [comment] 2021-05-12 01:40
Same behavior, no obvious failures reported. Manually exiting, then downloading and installing 3.3.3 from the website appears to have unstuck it, but who knows what the next update will bring.

**Comment by waleed-dawood** [comment] 2021-05-12 06:16
same issue.

**Comment by flowl** [comment] 2021-05-12 13:37
Feature request: It would be nice if from the "Troubleshoot" modal there was an option to display the applications STDERR or logs.

**Comment by flowl** [comment] 2021-05-17 10:51
After quitting and restarting, Docker Desktop upgraded to 3.3.2 instead of 3.3.3 or newer.
Whole update thing is buggy.

**Comment by hepcat72** [comment] 2021-05-26 14:17
Same issue.  3.3.1.  I also constantly get a dialog a couple times a day and I always click download and update, but it just always comes back and the menu item always has the (!) badge.

**Comment by jeroenvanmaanen** [comment] 2021-05-27 11:44
I had the same issue. I tried Update and Restart a few times with out effect. Then I Quit Docker Dektop and started it again, now I am on 3.3.3. 😅

**Comment by flowl** [comment] 2021-06-15 11:13
The update from 3.3.3 to 3.4.0 seemed to work at first but ended in a seg fault....

![Screenshot 2021-06-15 at 13 10 52](https://user-images.githubusercontent.com/4543262/122043172-56a33300-cddb-11eb-8a52-3cacf8d435f5.png)

I clicked on "Upload Crash Report" but nothing happened. No confirmation, no insight, I don't know if the report got sent or not.

I expect the software to show me the report before sending so I can assert no personal or company related information is getting uploaded.

Not only is the update process bugged since 3.3, there is also a privacy issue now.

**Comment by StefanScherer** [comment] 2021-06-24 08:17
Thanks @flowl for the report. We see more users to have this issue, but we're still investigating why this happens to some users. We couldn't reproduce it on our test machines yet. But we're looking into it.

**Comment by deltamualpha** [comment] 2021-06-25 15:48
Having the same issue upgrading past 3.3.3 now as well. Are there any logs I can pull to help debugging?

**Comment by flowl** [comment] 2021-07-07 11:04
The upgrade from `3.4.1` to `3.5.1` worked perfectly, no seg fault, no loops, no issues.

**Comment by craigotis** [comment] 2021-07-07 21:59
I'm also seeing this on 3.5.0, with a 3.5.1 update available.

**Comment by deltamualpha** [comment] 2021-07-07 22:01
It must have something to do with how Docker for Mac is installed. Or perhaps it's running into a conflict with something installed using homebrew? I know homebrew doesn't love that docker-for-mac installs its own `kubectl`...

**Comment by sgronblo** [comment] 2021-07-22 00:31
My Docker was unable to restart itself with the new version. But after quitting and restarting I finally could go from 3.3.x to 3.5.2.

**Comment by BeatriceThalo** [comment] 2021-08-17 12:53
I'm on Big Sur, started on 3.3.3, the "install and update" button was on a loop, despite shutting off my mac each night for a few weeks and the notification showing each morning. Today, "Quit Docker Desktop" and then relaunching Docker from Launchpad, prompted me with 'Docker will ask you for a password' and then 'Docker needs to install a helper tool' where I typed in my password (my usual fingerprint wasn't offered in the dialog). Then the notification changed to ask about the August 11th update, and About Docker Desktop shows 3.5.2.

**Comment by gennaro-tedesco** [comment] 2021-08-18 10:02
I see the same problem, similar to what is being referenced [here](https://github.com/docker/for-mac/issues/4375). Issues for Docker are being automatically locked and closed after some days without any solution or fix: is anyone looking into it at all? I find it somewhat puzzling that this still happens after so many opened tickets (buggy behaviour in the first place but let it be so).

**Comment by sean-hernon** [comment] 2021-08-18 10:22
> I see the same problem, similar to what is being referenced [here](https://github.com/docker/for-mac/issues/4375). Issues for Docker are being automatically locked and closed after some days without any solution or fix: is anyone looking into it at all? I find it somewhat puzzling that this still happens after so many opened tickets (buggy behaviour in the first place but let it be so).

At least there is the option to skip updates and not be spammed with a pop-up periodically.

Oh wait...

**Comment by netmikey** [comment] 2021-09-06 20:50
Here's another clue: I'm still on 10.15.7 Catalina and I had the same issue from Docker Desktop 3.5.2 to 3.6.0. Explicitly choosing "Quick docker desktop" and relaunching "docker.app" from the quick launch solved it for me too. When docker.app relaunched, I quickly saw macOS's Gatekeeper verifying some downloaded software (you know, just the small window with a security icon and a progress bar). And voila, docker started with v3.6.0.

**Comment by ssb22** [comment] 2021-09-09 10:28
Same on macOS Big Sur 11.5.2 upgrading to Docker Desktop 3.6.0, was repeatedly prompted for Upgrade every time I logged in, and when accepting the upgrade I saw network traffic as it was downloading, only to be prompted again at next login (so it was re-downloading every day, adding unnecessary load to the servers).  Like @netmikey the problem seems to have disappeared after Docker Desktop was explicitly quit and re-launched.  Don't know if this information is useful at all.

**Comment by steezeburger** [comment] 2021-09-27 17:36
13" Apple Silicon MBP, macOS Big Sur 11.5.2 upgrading to Docker Desktop 3.6.0 from 3.5.2.18:

I downloaded and installed Docker Desktop 4. Seemed to fix the issue for me.

**Comment by saludes** [comment] 2021-10-12 07:54
Same here with the same settings of @jwoertink but on macOS 11.6 Apple M1

**Comment by gennaro-tedesco** [comment] 2021-10-20 19:22
It is unreal how bad this is, and nobody looking at it. Might as well just close the issue, it has been months.

**Comment by akkapur** [comment] 2021-10-20 20:03
> With brew I was able to workaround the issue doing
> 
> ```
> ❯ brew upgrade --cask docker --greedy
> ==> Upgrading 1 outdated package:
> docker 3.5.2,66501 -> 4.1.1,69879
> ```
> 
> The upgrade took a lot of time, so be patient. Afterwards I restarted the docker app and everything worked fine again.

Works on my machine!

**Comment by ageron** [comment] 2021-11-07 04:29
I had the same issue on MacOSX 10.15.7, where it kept asking me to update, and never did. I quit Docker Desktop, I waited for a minute, and when I restarted it, it asked me for admin rights (I had to type my password), and when it started it was updated to the latest version. 👍 

So perhaps it's an authorization issue where we're not getting the security popup on MacOSX 10.15.7 or something like that? Hope this helps.

**Comment by sbleon** [comment] 2021-12-07 17:11
Me too. This is pretty irritating, and it's my main complaint about Docker Desktop right now.

**Comment by awnumar** [comment] 2021-12-16 10:58
I'm getting the same issue. Also now the new version of MacOS gives a warning saying Docker needs to update as it'll stop working with a future version of MacOS

**Comment by StefanScherer** [comment] 2021-12-16 12:15
We have a know sporadic issue with the update experience which started in 3.3.x version. For some users it always feels like the update does nothing. 

It normally updates when you quit Docker Desktop and start it again. 

If that still doesn‘t work we recommend to download the latest version of Docker Desktop from the release page https://docs.docker.com/desktop/mac/release-notes/

In newer versions we have fixed this update issue. 
Future updates will work as usual, but you need to update manually once to get it fixed. We apologize for any inconvenience.

**Comment by tapz** [comment] 2021-12-16 17:52
I downloaded and installed 4.3.0 over 3.3.x and the 4.3.1 update is downloaded, but not installed when I select Install & Restart. I need to manually quit and start again Docker Desktop.

**Comment by flowl** [comment] 2021-12-17 12:05
My experience in the last months / last updates is congruent to what @StefanScherer commented.
I don't think any new or relevant information can be shared here unless the update process with current versions still exist (e.g. you want to update from 4.2 to 4.3 and it fails) which is not the case for me.
I don't know about your internal tasks (says 1 of 3 tasks are done) but from my pov this issue can be closed.
Thanks everyone who participated and thanks to the Docker Team for their great product and responsiveness during this issue.

**Comment by tapz** [comment] 2021-12-17 12:40
@flowl How can this be closed when the Update and restart menu item clearly does not work?

**Comment by flowl** [comment] 2021-12-17 13:36
@tapz Oh I think I misunderstood your comment, sorry! The update from 4.3.0 to 4.3.1 should work but if it doesn't, the problem still exists and the issue shouldn't get closed.

**Comment by tapz** [comment] 2021-12-17 13:41
4.x works better than in 3.3.x as the update gets installed after quitting docker desktop. But the Update and restart menu item still does not cause the update to be installed.

**Comment by dhlavaty** [comment] 2021-12-20 15:20
I have "Download will start soon..." message for a few days now. I restarted my Mac, restarted Docker, tried "Update and Restart", several times. Nothing helps.

Big Sur 11.6.2, Docker Desktop 4.1.1

**Comment by zhengyongtao** [comment] 2021-12-28 05:36
In fact, the main reason for this phenomenon is that the restart and update option did not kill the com.docker.vmnetd process. After killing com.docker.vmnetd, the docker process can be updated normally by running it again.

**Comment by JoneSabino** [comment] 2022-01-10 13:21
> brew upgrade --cask docker --greedy

This worked fine. Hope they fix it in the product.

**Comment by rluncasu** [comment] 2022-01-25 10:57
> In fact, the main reason for this phenomenon is that the restart and update option did not kill the com.docker.vmnetd process. After killing com.docker.vmnetd, the docker process can be updated normally by running it again.

- killed com.docker.vmnetd
- clicked on update & restart
- manually closed docker
- started docker
was updated

**Comment by tapz** [comment] 2022-01-25 11:24
For me it's enough to just manually close Docker Desktop and start it again. No need to kill vmnetd. Just updated to 4.4.2 (73305).

**Comment by 1298509345** [comment] 2022-01-26 06:17
> > In fact, the main reason for this phenomenon is that the restart and update option did not kill the com.docker.vmnetd process. After killing com.docker.vmnetd, the docker process can be updated normally by running it again.
> 
> * killed com.docker.vmnetd
> * clicked on update & restart
> * manually closed docker
> * started docker
>   was updated

It still doesn't work😭

**Comment by flowl** [comment] 2022-02-23 12:00
Updating from Version 4.4.2, state of the app is stuck between "Downloading update" and "Ready to apply update".
After waiting for two days without any changes to that state, I restarted Docker and it already had upgraded to 4.5.0.

![Screenshot 2022-02-23 at 12 56 00](https://user-images.githubusercontent.com/4543262/155314802-1e0c1019-5d45-4387-aee4-70e978cd3689.png)

**Comment by flowl** [comment] 2022-03-22 17:23
Version still buggy, download does not start:

You’re currently on version 4.5.0 (74594). The latest version is 4.6.1 (76265)

**Comment by ntvinhit** [comment] 2022-03-23 11:06
Why does this issue still occurs for a year without a bug fix :(

**Comment by flowl** [comment] 2022-03-23 13:01
I don't understand how people are able to create such a revolutionary, genius system like Docker, but at the same time can't fix a simple update process within a year.
The update doesn't work even after restarting, there is always "Download will start soon..."

**Comment by tapz** [comment] 2022-03-23 16:46
I haven't seen this issue since 4.6.0.

**Comment by flowl** [comment] 2022-03-29 08:40
https://github.com/docker/for-mac/issues/6148
https://github.com/docker/for-mac/issues/6144

**Comment by igorkulman** [comment] 2022-04-01 09:07
@flowl same problem here, I "solved" it by deleting Docker Deskop, using https://github.com/abiosoft/colima instead and never looking back.

**Comment by uphlewis** [comment] 2022-04-05 02:35
Same deal here. 

<img width="1835" alt="image" src="https://user-images.githubusercontent.com/43346009/161667837-85278d71-ff5b-41c8-9baf-0dfd755825de.png">

**Comment by mat007** [comment] 2022-04-25 15:46
We have identified an issue with Cisco AnyConnect blocking the internal communication between two components of Docker Desktop and thus preventing the update to be ever downloaded.
If you’re running Cisco AnyConnect, and can disable it, you can try that.
Alternatively, starting with Docker Desktop 4.7.0, we have changed the way the components communicate and it now works around that. So you could just update to [that version](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-470) and then the in-app update to the latest one (4.7.1 at the moment), should work.

**Comment by vedmant** [comment] 2022-05-28 06:14
I have the same issue
MacOs: 12.4 (21F79)
Docker: 4.8.1 (78998)

**Comment by Janpot** [comment] 2022-06-09 13:54
It seems like it got unstuck for me after I enabled "Location services" for "Docker desktop" in MacOS "Security & Privacy" settings. Could that be possible?

**Comment by sdirosa** [comment] 2022-06-20 07:19
> It seems like it got unstuck for me after I enabled "Location services" for "Docker desktop" in MacOS "Security & Privacy" settings. Could that be possible?

This solved the issue for me 🤦🏼‍♂️

**Comment by pich4ya** [comment] 2022-07-01 16:53
> It seems like it got unstuck for me after I enabled "Location services" for "Docker desktop" in MacOS "Security & Privacy" settings. Could that be possible?
> 
> _Edit: just noticed that I had "Send usage statistics" enabled in the settings. assuming that's why you're accessing my location data, you might want to check the implementation and make it fault tolerant._

magically fixed the issue !

**Comment by mokinch** [comment] 2022-08-08 16:37
Few days ago I had the same problem with phpStorm update and it was solved by granting permissions for PhpStorm.app.
Today I faced the same problem with docker and this worked for me:
1. sudo xattr -d com.apple.quarantine /Applications/Docker.app/
2. sudo chmod -R 777 /Applications/Docker.app/

**Comment by maxcleme** [comment] 2022-08-11 15:14
@Janpot @pich4ya @sdirosa 

Hi folks, I'm looking back at this and I was wondering if you could share a hand understand better what happened there regarding Location Services ?

I'm trying to replicate the bug on my end but I was able to update successfully with Location Services being disabled.

May I ask you for the following insights ?

+ Which versions you were at and updating to when disabling Location Services makes it magically works ?
+ Is it something replicable on your end by enabling Location Services again ?
+ If so, are you able to [generate diagnostics](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) for us while being in that unexpected state ? 

https://user-images.githubusercontent.com/7669401/184166112-c63378ef-9770-4b56-b5e4-8e6335b38ce9.mp4

**Comment by Janpot** [comment] 2022-08-11 16:13
> I'm trying to replicate the bug on my end but I was able to update successfully with Location Services being disabled.

Did you make sure to enable sending usage statistics?

![Screenshot 2022-08-11 at 17 59 34](https://user-images.githubusercontent.com/2109932/184178172-d34f224a-42b9-4f44-9b2f-bc3a05910316.png)

> * Which versions you were at and updating to when disabling Location Services makes it magically works ?

Don't remember, sry

> * Is it something replicable on your end by enabling Location Services again ?

I've replicated it at least once in the past, it definitely happened on more than 1 version. Not sure whether it makes a difference, but I've disabled location services for Docker desktop specifically, not the global setting.

> * If so, are you able to [generate diagnostics](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) for us while being in that unexpected state ?

Sure but I'd have to enable sending usage statistics again (which I'm not necessarily keen on doing as it seems to gather information that I don't feel comfortable about sharing) and wait for the next update cycle.

<hr>

Btw, probably not related, but this is what I see in location services for the icon of Docker Desktop:

![Screenshot 2022-08-11 at 18 06 40](https://user-images.githubusercontent.com/2109932/184179138-090c7c08-557a-417b-84b3-6cf98819c68f.png)

**Comment by sdirosa** [comment] 2022-08-11 16:52
@maxcleme I'm still experiencing this issue.

I just uploaded diagnostics with id: `ACC83A3E-6884-4880-A74F-A5607C7F71BE/20220811164722`

Let me know if I can check anything else, I'd be happy to help out.

---

Some screens to show what it looks like:
<img width="261" alt="Screen Shot 2022-08-11 at 18 45 01" src="https://user-images.githubusercontent.com/567826/184188774-8851146a-7f5d-4232-9bfd-85b5599bd1dc.png">

And in the main UI, same behavior:
<img width="969" alt="Screen Shot 2022-08-11 at 18 46 04" src="https://user-images.githubusercontent.com/567826/184188965-8af315fc-bb19-4eed-8c9a-27e252ec631c.png">

And my Location Services are still enabled for Docker Desktop, so that doesn't solve it anymore apparently:
<img width="655" alt="Screen Shot 2022-08-11 at 18 50 11" src="https://user-images.githubusercontent.com/567826/184189725-5cad3e4a-48e6-403e-a34e-cc9321867775.png">

**Comment by maxcleme** [comment] 2022-08-12 09:32
@sdirosa 

Thanks for this diagnostics, I was able to replicate part of the issue on my end by being stuck at "Download will start soon", however when restarting Docker, the update actually performs and I was booting on v4.11.1.

Are you able to confirm that in your current state, quitting Docker Desktop using the tray menu and start it again actually perform the update ?

**Comment by sdirosa** [comment] 2022-08-12 09:50
@maxcleme 

> Are you able to confirm that in your current state, quitting Docker Desktop using the tray menu and start it again actually perform the update ?

Yes, that worked! I'm on 4.11.1. I used the contextual menu `restart` option by the way. 

So it seems we are facing two different issues:

- One is the update not even starting up when Location Services are not active and `Send usage statistics` is enabled. I can't confirm this because my Location Services have been active since I experienced the issue. I could try to disable them again, and see what happens on the next version though.

- The other issue seems to be related to the Application not being able to self-update. Perhaps a simple `restart to apply downloaded updates` button is all we need here.

**Comment by maxcleme** [comment] 2022-08-12 11:55
@sdirosa Thanks again for valuable feedbacks.

I'm into something and I'm going to issue a fix internally to deal with the state being stuck as "Download will start soon", it is misleading since you already have downloaded the update behind-the-scene in that case (can be confirm with the diag you sent to us). Restarting Docker Desktop make the pending update behave correctly.

Regarding "Location Services" I'm still doubtful about being a possible root cause of this issue, after many combinations I still can't replicate the issue. I would better think about user restarting Docker Desktop themselves after updating Location Services and thus falling in above point.

**Comment by flowl** [comment] 2022-08-14 13:20
I have never turned on "Send usage statistics", it might be another bug, different from the initially reported bug.

**Comment by 1200mhz** [comment] 2022-08-18 14:15
The update (4.11.1 for macos monterey) downloaded and installed after I rebooted my laptop

**Comment by andrei-z-albu** [comment] 2022-09-01 17:23
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Closed by andrei-z-albu** 2022-09-01 17:23 UTC
Labels: version/4.11.0
