### ISSUE TITLE
Slow docker-compose performance while talking to a Moby VM while Mac Ethernet adapter is plugged in

### ISSUE THREAD

**Issue by xeger** [docker/for-mac#627] opened 2016-09-15 00:59 UTC
Beginning with the Docker for Mac beta25 update a few days back, I began to see a truly bizarre networking issue. When I run `docker-compose` on my Mac with an empty `DOCKER_HOST` env, operations take 10-60 times longer than they should. This problem does not manifest when I run standard `docker` commands; they're as fast as ever.

To add to the confusion, this issue _only_ manifests while my Thunderbolt Ethernet adapter is plugged in. If I remove it and rely on WiFI, the problem goes away.

### Expected behavior

Invoking `docker-compose` while Ethernet adapter is unplugged:

```
/tmp$ time docker-compose --verbose up -d test 2>&1 | ts
...
Sep 14 17:52:46         0.95 real         0.22 user         0.05 sys
```

### Actual behavior

Once I plug in my Ethernet adapter:

```
/tmp$ time docker-compose --verbose up -d test 2>&1 | ts
...
Sep 14 17:44:47        56.60 real         0.26 user         0.07 sys
```
Almost 60x slower!

Even stranger, the output from `docker-compose` seems to happen in bursts at 5-second intervals, regular as clockwork. It's almost like something is delaying or queuing the API calls it makes over `docker.sock`.

### Steps to Reproduce

Create a trivial composition.

```
version: "2"
services:
  test:
    image: busybox
    command: "sleep 60"
```

Plug in a Thunderbolt adapter.

Run `docker-compose up`

### Information

  - Diagnostic ID: 93F67582-B274-4714-9E27-30E98D1F16C5
  - Ethernet adapter is "Thunderbolt Ethernet" (an Apple peripheral) model A-1433

Extra info that your diagnostic may not have captured:

```
$ ls -la /var/run/docker.sock 
lrwxr-xr-x  1 root  daemon  57 Sep 14 17:39 /var/run/docker.sock -> /Users/tony/Library/Containers/com.docker.docker/Data/s60
```

```
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:bc:32:7e:f2:f1 
	inet6 fe80::aebc:32ff:fe7e:f2f1%en0 prefixlen 64 scopeid 0x4 
	inet 10.10.12.180 netmask 0xfffffe00 broadcast 10.10.13.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 6a:00:00:d1:ba:f0 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 6a:00:00:d1:ba:f1 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 0e:bc:32:7e:f2:f1 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 36:ca:46:7e:cb:0a 
	inet6 fe80::34ca:46ff:fe7e:cb0a%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
bridge0: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether ae:bc:32:e7:de:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
```

**Comment by dsheets** [comment] 2016-09-15 11:02
I believe this is a duplicate of #133. I will make a note there to read the excellent report in this issue. Thank you for your report; we have this on our radar.

**Closed by dsheets** 2016-09-15 11:02 UTC
Labels: status/0-triage
