### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Cabbit** [docker/for-mac#118] opened 2016-08-04 01:41 UTC
### Information

Diagnostic ID: CB334FFD-AC34-4CE5-970B-5D95E5AEAD2C
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by Cabbit** [comment] 2016-08-04 01:42
Um with the current macOS build and docker build after a seemingly random amount of time it'll just crash

**Comment by cocojas** [comment] 2016-08-07 18:12
There's a problem with the go runtime and macOS Sierra. It was fixed in go 1.6.3 and a previous 1.7 rc, but with beta 4, a similar problem arose. There is a memory corruption issue in one of the sys calls in the go runtime which is fixed in 1.7rc5. So, any runtime built prior to 1.7rc5 is going to have a very high chance of getting a bus signal and crashing randomly.

**Comment by dave-tucker** [comment] 2016-08-09 01:34
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 01:34 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
