### ISSUE TITLE
docker crashed after waking up mac from sleep (High Sierra)

### ISSUE THREAD

**Issue by pallymore** [docker/for-mac#2098] opened 2017-09-28 13:02 UTC
### Expected behavior
Not crash?

### Actual behavior
Crashed

### Information
Diagnostic ID: 3BD4F4A9-97F1-48DD-B773-117E51F5EEC8 
I upgraded to High Sierra a few days ago but this just happened today, might be random?

### Steps to reproduce the behavior

  1. put mac to sleep by clicking the Apple logo in the top bar and select Sleep
  2. wake mac up after a few hours (with power cable connected) - see docker crash message

**Comment by Jasrags** [comment] 2017-09-28 13:19
Same for me with Diagnostic ID `0D86BA64-FB3E-4F84-85B0-6CFD2B084BD9`

**Comment by jediorange** [comment] 2017-09-28 16:33
Same here: 8BC72F75-C4DF-457E-B842-F8612989D8D9

**Comment by jmaitrehenry** [comment] 2017-09-28 17:13
Hi, it's a duplicate of https://github.com/docker/for-mac/issues/2095
We can close this issue @thaJeztah

**Comment by thaJeztah** [comment] 2017-09-28 19:29
Thanks, yes, it's a duplicate. But I don't have permissions in this repository, let me try getting that addressed 😅

**Closed** 2017-09-30 02:00 UTC
Labels: status/0-triage
