### ISSUE TITLE
Improve General Interactability throught the app

### ISSUE THREAD

**Issue by WebKenth** [docker/for-mac#6543] opened 2022-10-28 11:08 UTC
Please hear this plea

Every button you press must give some actual feedback as to what is happening

If you navigate to the `Software updates` and click on `Check for Updates` You would expect it yo start looking for an update

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/13419123/198571746-89b603bb-ac02-4064-9470-eee484ca8782.png">

What happens? Nothing, there is a slight hover on the button and when you click, nothing happens
Behind the scenes an update request is fired, but the visual aspect tells absolutely nothing.

Same behaviour is happening on the `Troubleshoot` page:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/13419123/198572091-bb838d13-c5b3-407d-8879-c52b5346e39a.png">
None of these buttons offer any form for interactivity  ( except for maybe a confirm popup ), and once the process is running in the background there is nothing to see and you might come to the conclusion that you should try and push the button again. 

This can cause serious damage to the installation if it is not propperly handled

Alot of the issues i see on this repository could easily be solved by handling user input with care

There is instant feedback when running a command from the terminal, but none what so ever to find from the GUI

Even the start/stop of the docker engine is lacking

I don't think there's a single person using Docker For Mac who isn't a developer and wouldn't benefit from having actual output of what is happening.

A clean error message or red wall of text would help us more in figuring out wether it is a `Docker for Mac` issue or an error in our own setup which you do not support.

if you need some help on the issue check out this article by UXPlanet:
https://uxplanet.org/7-basic-rules-for-button-design-63dcdf5676b4

**Comment by nicks** [comment] 2022-11-01 17:31
Hi! Thanks for the recommendations! This is more of a class of feature requests than a bug report though. I'm going to mark this as a duplicate of https://github.com/docker/for-mac/issues/6387 to centralize discussion there, which is probably closest to what you're looking for.

**Closed by nicks** 2022-11-01 17:31 UTC
