### ISSUE TITLE
Docker for Mac (17.10.0-ce-mac36) segfaults on debian:wheezy/centos:6 images

### ISSUE THREAD

**Issue by welps** [docker/for-mac#2169] opened 2017-10-24 23:31 UTC
### Expected behavior
Running `docker run debian:wheezy` returns exit code 0

### Actual behavior
Running `docker run debian:wheezy` returns exit code 139

### Information

Diagnostic ID: B3DEF8E-B246-47B7-A218-380229307B77
Docker for Mac: version: 17.10.0-ce-mac36 (a38d9cd48bd0ee31ec82c59b783aa2f2817bfb92)
macOS: version 10.13 (build: 17A405)
logs: /tmp/6B3DEF8E-B246-47B7-A218-380229307B77/20171024-190910.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run `docker run debian:wheezy`
  2. Check exit code

Other images that segfault:

* centos:6 - centos:6.9

**Comment by yspro** [comment] 2017-10-25 14:47
Same here... Got the segfault on `docker run redis:3.0.2`

**Comment by cs96and** [comment] 2017-10-25 15:34
Same issue on Windows as well
https://github.com/docker/for-win/issues/1245

**Comment by welps** [comment] 2017-10-25 15:46
@yspro Yeah anything derived from these base images will segfault. Happened to me with mongo.

**Comment by djs55** [comment] 2017-10-26 09:43
Thanks for the report. The problem is a missing `vsyscall=emulate` argument on the kernel command-line which prevents some older binaries from working. There's a fix in the master branch which will be in the next edge release, due at the end of October. In the meantime I recommend working around the problem by switching either to the stable channel or the previous edge build [17.09.0-ce-mac34](https://download.docker.com/mac/edge/19605/Docker.dmg)

**Comment by gtardif** [comment] 2017-11-03 16:11
This should now work with latest edge version, released today (17.11.0-ce-rc2-mac37)

**Comment by welps** [comment] 2017-11-16 04:10
I can confirm this has been fixed. Thanks!

**Closed** 2017-11-16 04:10 UTC
Labels: status/3-fixed, version/17.10.0-ce-mac36
