### ISSUE TITLE
After upgrading, it cannot be fully opened normally

### ISSUE THREAD

**Issue by Payne-Wu** [docker/for-mac#5160] opened 2020-12-19 18:05 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 346B856C-501A-4C41-A985-9E13B2F78A45/20201219174604

### Information

  - macOS Version: 11.0.1  MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ... Upgrade to the latest version
  2. ... Has been starting, but k8s failed to start successfully（The terminal cannot use docker command normally）

**Comment by Payne-Wu** [comment] 2020-12-19 18:27
When I reset it, it works

**Comment by tiborvass** [comment] 2020-12-21 00:19
I verified your diagnostics ID, and it seems you are hitting #5131. Closing as dupe of #5131 which has a workaround at https://github.com/docker/for-mac/issues/5131#issuecomment-748692772

**Closed by tiborvass** 2020-12-21 00:19 UTC
Labels: version/11.0.1  MacBook Pro
