### ISSUE TITLE
High CPU usage on 2.5.0.1

### ISSUE THREAD

**Issue by rbranche** [docker/for-mac#5078] opened 2020-11-19 18:25 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `2435E58B-D199-4C76-BEA8-8DB1B768EBBC/20201119181559`

### Expected behavior

CPU usage being below 10% with no CPU usage from containers

### Actual behavior

100% CPU usage with very small CPU usage from containers

![Screen Shot 2020-11-19 at 10 09 24 AM](https://user-images.githubusercontent.com/1118001/99707505-60d19e80-2a51-11eb-94e9-09e49c7f802e.png)

### Information
  - macOS Version: macOS Big Sur

### Diagnostic logs

Docker for Mac: 2.5.0.1 (49550)

### Steps to reproduce the behavior

Just regular Postgres docker containers running with no CPU usage between them.

**Comment by rbranche** [comment] 2020-11-19 18:26
This is likely a duplicate of #5044

**Comment by stephen-turner** [comment] 2020-11-20 13:58
Yes, dupe of #5044 and #5070.

**Closed by stephen-turner** 2020-11-20 13:58 UTC
Labels: version/2.5.0.1
