### ISSUE TITLE
Docker Installation for Mac-stable version.- Error (Failure to start Supervisor)

### ISSUE THREAD

**Issue by himankvats** [docker/for-mac#2464] opened 2018-01-18 20:57 UTC
I'm getting this error after installation of docker and even on reset to factory settings this issues doesn't seem to be fixed. I have reinstalled the application but the issue still exist. Below is Report generated. Can someone please tell me how to fix this issue. 

Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/69B0193D-21E4-4578-93B5-AB765C905D28/20180118-155450.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/himankvats/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/himankvats/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/himankvats/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/himankvats/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by akimd** [comment] 2018-01-19 15:11
If you are short on disk space, then this is likely a dupe of https://github.com/docker/for-mac/issues/2383.

**Comment by gtardif** [comment] 2018-01-19 21:13
We just released 17.12.0-ce-mac49 on the Stable channel that fies this. (and 18.01 on the Edge channel also fixes this)

**Closed by gtardif** 2018-01-19 21:13 UTC
