### ISSUE TITLE
docker cp is *still* ***still*** not setting correct UID/GID (still, seriously, it's still happening)

### ISSUE THREAD

**Issue by posita** [docker/for-mac#6221] opened 2022-03-07 23:59 UTC
@rbelouin filed #1814 in 2017, which was closed without a fix due to "inactivity". @eli-darkly then filed #5329 in 2021, citing #1814 and pointing out that it was closed automatically without a fix. #5329 was then closed without a fix due to "inactivity". This is the third filing of the same exact issue from almost five years ago.

I have confirmed that this issue is still a problem. The [documentation reads]():

> The cp command behaves like the Unix `cp -a` command in that directories are copied recursively with permissions preserved if possible. Ownership is set to the user and primary group at the destination. For example, files copied to a container are created with `UID:GID` of the root user. Files copied to the local machine are created with the `UID:GID` of the user which invoked the docker cp command. However, if you specify the `-a` option, docker cp sets the ownership to the user and primary group at the source. …

This isn't correct. There doesn't appear to be any meaningful distinction between `docker cp` and `docker cp -a`. To reproduce. In a first shell on the host, do:

``` sh
% docker run -it --name testuser --rm debian:latest
root@043fc399fe34:/# useradd --create-home --uid 1000 --user-group testuser
root@043fc399fe34:/# ls -aln /home/testuser/
total 20
drwxr-xr-x 2 1000 1000 4096 Mar  7 23:53 .
drwxr-xr-x 1    0    0 4096 Mar  7 23:53 ..
-rw-r--r-- 1 1000 1000  220 Aug  4  2021 .bash_logout
-rw-r--r-- 1 1000 1000 3526 Aug  4  2021 .bashrc
-rw-r--r-- 1 1000 1000  807 Aug  4  2021 .profile
```

In a second shell on the host, do:

``` sh
% mkdir /tmp/testuser
% cd /tmp/testuser
% touch perm-test.txt
% sudo chown 501:80 perm-test.txt
% ls -aln
drwxr-xr-x 2  501    0 4096 Mar  7 23:50 .
drwxrwxrwt 1    0    0 4096 Mar  7 23:49 ..
-rw-r--r-- 1  501   80    0 Mar  7 23:50 perm-test.txt
% docker cp perm-test.txt testuser:/home/testuser
% docker exec -it testuser ls -aln /home/testuser
total 20
drwxr-xr-x 2 1000 1000 4096 Mar  7 23:55 .
drwxr-xr-x 1    0    0 4096 Mar  7 23:55 ..
-rw-r--r-- 1 1000 1000  220 Aug  4  2021 .bash_logout
-rw-r--r-- 1 1000 1000 3526 Aug  4  2021 .bashrc
-rw-r--r-- 1 1000 1000  807 Aug  4  2021 .profile
-rw-rw-r-- 1  501   80    0 Mar  7 23:54 perm-test.txt
% docker exec -it testuser rm /home/testuser/perm-test.txt
% docker cp -a perm-test.txt testuser:/home/testuser
% docker exec -it testuser ls -aln /home/testuser
total 20
drwxr-xr-x 2 1000 1000 4096 Mar  7 23:56 .
drwxr-xr-x 1    0    0 4096 Mar  7 23:55 ..
-rw-r--r-- 1 1000 1000  220 Aug  4  2021 .bash_logout
-rw-r--r-- 1 1000 1000 3526 Aug  4  2021 .bashrc
-rw-r--r-- 1 1000 1000  807 Aug  4  2021 .profile
-rw-rw-r-- 1  501   80    0 Mar  7 23:54 perm-test.txt
```

**Comment by posita** [comment] 2022-03-08 00:03
Possible dup of moby/moby#41727?

**Comment by stephen-turner** [comment] 2022-03-24 09:45
Thanks for the report. Yes, I think it's a dupe of that upstream issue. I'll close this copy.

**Closed by stephen-turner** 2022-03-24 09:45 UTC
