### ISSUE TITLE
Message appears every time I turn my computer on.

### ISSUE THREAD

**Issue by akrause414** [docker/for-mac#169] opened 2016-08-08 11:56 UTC
### Expected behavior
Docker has been updated! New version is 1.12.0.  Message appears after updating to 1.12.0 ONCE
### Actual behavior
Docker has been updated! New version is 1.12.0.  Message appears EVERY DAY 
### Information

Diagnostic ID: E7CC3849-391D-4C53-806F-D6397728C5D4
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.1 (Build 15B42)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install docker recent beta version.  Use it for a few days until a new version available msg displays.
2. Go to the site and download 1.12.0 stable.  Install 1.12.0, overwriting prior beta version.  Default settings.
3. Docker has been updated! New version is 1.12.0.  Message appears EVERY DAY

**Comment by dsheets** [comment] 2016-08-08 12:59
This is a duplicate of #51. We are working on a fix which will reach the beta channel first and then stable with 1.12.1. Thanks for the report!

**Closed by dsheets** 2016-08-08 12:59 UTC

**Comment by jdaniel-GIS** [comment] 2016-10-06 15:07
This is closed? Does this mean that I need to file a new issue because the daily message now says that "Docker has been updated! New version is 1.12.1"?

**Comment by dsheets** [comment] 2016-10-10 13:43
@jdaniel-GIS no new issue is necessary. Please follow #51 where this problem was originally reported for updates.
