### ISSUE TITLE
Docker 4.13.0 does not start up on macOS Ventura

### ISSUE THREAD

**Issue by localheinz** [docker/for-mac#6547] opened 2022-10-29 07:36 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
    ```
     229F4003-7498-4C15-9D0E-D7E9216290CD/20221029072820
    ```

### Expected behavior

After attempting to start Docker Desktop for macOS Ventura, I can see Docker Desktop in the macOS menu bar. From there, I can open the Docker Desktop UI.

### Actual behavior

After attempting to start Docker Desktop for macOS Ventura, nothing happens.

### Information

- This issue is reproducible.
- The problem is new, it occurred the first time after updating to macOS Ventura, trying to bring up Docker for a project, and seeing issues in the command line.
  - macOS Version: Ventura 13.0
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.13.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory
[2022-10-29T07:29:00.093261000Z][com.docker.diagnose][I] ipc.NewClient: 565cca7f-diagnose -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func12()
[	common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8c
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1054d7960)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1054d7960)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x1054d7960)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1054d7960, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x88
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1054d79e0, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1054d7ae0, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1054d7d60, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkOnce(0x104f95a60?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1054d7d60, 0x1400019c360?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x14000132010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-10-29T07:29:00.093995000Z][com.docker.diagnose][I] (41ad045c) 565cca7f-diagnose C->S diagnosticsd GET /ping
[2022-10-29T07:29:00.094343000Z][com.docker.diagnose][W] (41ad045c) 565cca7f-diagnose C<-S NoResponse GET /ping (338.917µs): Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:00.094778000Z][com.docker.diagnose][I] ipc.NewClient: 3537dca1-com.docker.diagnose -> lifecycle-server.sock VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x104dca073, 0x13})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0x90
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[	common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x28
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1054d79e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1054d79e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x1054d79e0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1054d79e0, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x88
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1054d7ae0, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1054d7d60, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkOnce(0x104f95a60?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1054d7d60, 0x1400019c360?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x14000132010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-10-29T07:29:00.095600000Z][com.docker.diagnose][I] (80be167a) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-10-29T07:29:00.095871000Z][com.docker.diagnose][W] (80be167a) 3537dca1-com.docker.diagnose C<-S NoResponse GET /docker (269.916µs): Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:00.096069000Z][com.docker.diagnose][I] (80be167a-1) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:00.096307000Z][com.docker.diagnose][W] (80be167a-1) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (237.083µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:01.096678000Z][com.docker.diagnose][I] (80be167a-2) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:01.097675000Z][com.docker.diagnose][W] (80be167a-2) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (993.875µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:02.098627000Z][com.docker.diagnose][I] (80be167a-3) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:02.098957000Z][com.docker.diagnose][W] (80be167a-3) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (329.833µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:03.100236000Z][com.docker.diagnose][I] (80be167a-4) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:03.100728000Z][com.docker.diagnose][W] (80be167a-4) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (489.542µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:04.101663000Z][com.docker.diagnose][I] (80be167a-5) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:04.102068000Z][com.docker.diagnose][W] (80be167a-5) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (402.958µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:05.103039000Z][com.docker.diagnose][I] (80be167a-6) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:05.103483000Z][com.docker.diagnose][W] (80be167a-6) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (441.084µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:06.104466000Z][com.docker.diagnose][I] (80be167a-7) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:06.104933000Z][com.docker.diagnose][W] (80be167a-7) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (463.125µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2022-10-29T07:29:07.105863000Z][com.docker.diagnose][I] (80be167a-8) 3537dca1-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-10-29T07:29:07.106344000Z][com.docker.diagnose][W] (80be167a-8) 3537dca1-com.docker.diagnose C<-S NoResponse GET /ping (478.583µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[PASS] DD0013: is the $PATH ok?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[FAIL] DD0003: is the Docker CLI working? exit status 1
[FAIL] DD0014: are the backend processes running? 5 errors occurred:
	* com.docker.backend is not running
	* vpnkit-bridge is not running
	* com.docker.vpnkit is not running
	* com.docker.driver.amd64-linux is not running
	* qemu-system-aarch64 is not running


[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": dial unix backend.sock: connect: no such file or directory
[2022-10-29T07:29:09.010558000Z][com.docker.diagnose][I] ipc.NewClient: 148e3105-diagnose -> backend.sock BackendAPI
[common/pkg/backend.NewClientForPath({0x104dc1718?, 0x0?}, {0x1400036ea00?, 0x1?})
[	common/pkg/backend/client.go:172 +0x3c
[common/pkg/backend.NewClient({0x104dc1718, 0x8})
[	common/pkg/backend/client.go:167 +0x54
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:25 +0x28
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1054d7de0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1054d7de0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x1054d7de0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1054d7de0, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x88
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1054d7d60, 0x14000671718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkOnce(0x104f95a60?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x1054d7d60, 0x1400019c360?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x14000132010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
```

Looks like the check is still running.

### Steps to reproduce the behavior

1. Navigate to https://www.docker.com/products/docker-desktop/.
2. Click on **Apple Chip**
3. When the download has finished, double-click on **Docker.dmg**
4. Start **Docker**

**Comment by nicks** [comment] 2022-10-29 14:57
Thanks for reporting! You can workaround this by going to your network settings and adjusting the network to 192.168.65.0/24, like so:

![Screenshot from 2022-10-29 10-56-14](https://user-images.githubusercontent.com/278641/198838383-6fd8e57d-6161-4f12-b699-cd2faa041c3c.png)

We're working on a fix for this. I'm going to mark this as a duplicate of https://github.com/docker/for-win/issues/13025 to centralize the communication on it.

**Closed by nicks** 2022-10-29 14:57 UTC
Labels: version/4.13.0

**Comment by localheinz** [comment] 2022-10-29 22:27
@nicks 

On second thought, not sure if you understood the issue description: Docker Desktop does not even start up fully - I neither see the Docker Desktop icon in the menu bar, nor am able to open the UI. In other words, I can not set the Docker subnet.

**Comment by nicks** [comment] 2022-10-29 22:31
oops - ya, if the UI isn't starting, you can edit the settings file manually. it's "vpnkitCIDR" under "~/Library/Group Containers/group.com.docker/settings.json"

**Comment by localheinz** [comment] 2022-10-29 22:36
Thanks a ton, @nicks, this helped!

**Comment by dcmartin** [comment] 2022-11-13 23:47
I am having same issue; Ventura 13.0.1 on Intel (IMac 2017); I have fully removed all Docker references on the machine and reinstalled and do not have any ~/Library/Group.. file to edit.

**Comment by ramonfnasc12** [comment] 2023-01-19 21:54
I'm having the same issue as @dcmartin described above

**Comment by Palwisha-18** [comment] 2023-01-23 22:23
After updating mac OS to Ventura 13.0, my Docker Desktop stopped working. 
Tried uninstalling Docker app.
Installed through both Docker website and cmd line (brew), keep getting docker daemon error and Docker Desktop GUI doesn't open as well.
Activity monitor shows that Docker app is not responding.

**Comment by evan-mick** [comment] 2023-01-29 17:22
I am having this same issue as well

**Comment by ARLunan** [comment] 2023-01-30 14:18
Did same steps as Palwisha  above, direct or brew install does not run Docker Desktop and docker in Activity Monitor crashes. Why is this issue closed as still unable to run Docker on my Mac M1 Ventura?

**Comment by nicks** [comment] 2023-01-30 14:24
If you're having unrelated issues starting docker desktop, please file a new issue with diagnostics - https://docs.docker.com/desktop/troubleshoot/overview/
