### ISSUE TITLE
Docker not responding

### ISSUE THREAD

**Issue by rokcarl** [docker/for-mac#501] opened 2016-09-02 10:37 UTC
### Expected behavior
I do `docker ps`, I get a listing.

### Actual behavior
I do `docker ps` and wait forever, nothing happens. I've also restarted the engine and tried again.

### Information

Diagnostic ID: 34CF52A1-7D50-436A-8307-AAAA3FC0F896
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

No idea.

**Comment by rokcarl** [comment] 2016-09-02 10:52
Restaring the computer restored things to normal.

**Comment by adamj88** [comment] 2016-09-04 15:18
I'm having the same issue, however rebooting does not resolve this. `docker-compose ps` and `docker-compose up` take forever to do anything.

**Comment by pwright08** [comment] 2016-09-07 08:10
To get docker-cli to start working again when this happens I have to:

1. Quit Docker (from the icon on the task bar)
2. Run the following in terminal:

`ps aux | grep docker | grep root | awk {'print $2'} | xargs sudo kill`

**Comment by mchiang0610** [comment] 2016-09-12 17:48
Dupe of #119.

**Closed by mchiang0610** 2016-09-12 17:48 UTC
