### ISSUE TITLE
Updated docker to 3.4 and all of my data was purged 

### ISSUE THREAD

**Issue by jsreed** [docker/for-mac#5754] opened 2021-06-14 23:44 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 78C958A3-5A1E-4A92-9F46-003E738BE462/20210614223128

### Expected behavior
Docker updates without nuking my local environment.
### Actual behavior
I updated docker to 3.4 from an older version, not sure which but it was at least 4 months old, and after docker restarted all of my data was gone. All containers, images, volumes, networks, etc appeared to be purged.

### Information

  - macOS Version: 10.14.6 (18G103)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: currently 3.4.0.5223. Not sure the version I updated from, was at least 4 months old.

### Steps to reproduce the behavior

  1. Update docker

**Comment by rfsx0829** [comment] 2021-06-15 06:01
Is there any progress? I'm having the same problem.

**Comment by simoneborgio** [comment] 2021-06-15 08:52
Same problem here, on Mac/Intel

**Comment by NicolasShinguji** [comment] 2021-06-15 09:10
macOS Version: 11.4 (20F71) 
has same problem

**Comment by llamadeus** [comment] 2021-06-15 11:02
Hey folks, I just had the same problem.

**Good news**: Your data wasn't purged. It seems like they messed something up with the VM file path concatenation which results in Docker looking for the VM in the **wrong directory**.

Previously, the Docker VM was located at `~/Library/Containers/com.docker.docker/Data/vms` which changed to `~/Library/Containers/com.docker.docker/Data/Library/Containers/com.docker.docker/Data/vms`. I assume this is a **bug** because of the duplicated path segments.

As a workaround copy the folder **0** from `~/Library/Containers/com.docker.docker/Data/vms` to `~/Library/Containers/com.docker.docker/Data/Library/Containers/com.docker.docker/Data/vms`.

**Comment by jsreed** [comment] 2021-06-15 13:07
@llamadeus thank you! That did the trick, everything was restored.

**Comment by crberube** [comment] 2021-06-15 14:59
I had this exact issue as well. In docker preferences it claimed it was still looking in the correct location at `~/Library/Containers/com.docker.docker/Data/vms`. 

I fixed the issue in a similar manner as @llamadeus, however in my case I made a copy of `Docker.raw` from the `~/Library/Containers/com.docker.docker/Data/vms` folder and then `Reset to factory defaults` from the Troubleshoot menu. This deleted the `Docker.raw` file from the correct location (`~/Library/Containers/com.docker.docker/Data/vms`) _and_ the incorrect location (`~/Library/Containers/com.docker.docker/Data/Library/Containers/com.docker.docker/Data/vms`). After doing that, I quit docker and moved my copy of `Docker.raw` back to the original location at `~/Library/Containers/com.docker.docker/Data/vms` and everything was back to normal.

This makes me think that the issue has to do specifically with the upgrade process from one version to the next.

**Comment by mat007** [comment] 2021-06-15 16:10
Thanks for the reports, sorry about the inconvenience. This looks indeed like an issue with the settings migration when upgrading.
Does anyone remember which version you upgraded from?
We have tests for upgrading from some versions, but apparently there is at least one missing here…

**Comment by crberube** [comment] 2021-06-15 16:13
I am pretty sure it was 3.2.2 -> 3.4 in my case.

**Comment by sauceofchaos** [comment] 2021-06-15 18:31
I was on the version just prior to this one, 3.3.x (maybe not 3.3.3 but in the 3.3.x range). I usually keep things pretty up to date. So it's not just one version or one minor version.

**Comment by crberube** [comment] 2021-06-15 20:02
Happy to hear things are working @sauceofchaos. Glad you mentioned the subfolder. That's what I get for copy and pasting! I've updated with the correct paths now.

**Comment by mat007** [comment] 2021-06-16 08:49
We’re still trying to figure out what can cause this, but based on your description of a workaround I believe this should do it as well:
1. Quit Docker Desktop
2. Open `~/Library/Group Containers/group.com.docker/settings.json`
3. Locate the `dataFolder` field and change it to e.g. `/Users/mat007/Library/Containers/com.docker.docker/Data/vms/0` using your home folder
4. Save and restart Docker Desktop

**Comment by mat007** [comment] 2021-06-16 09:16
We have now identified the root cause and will fix the settings migration.
This will be available in the next release which at the moment is planned for middle of next week.

If you fix this manually using one of the workarounds from this issue, make sure you have an absolute path as the value for the `dataFolder` field in `~/Library/Group Containers/group.com.docker/settings.json`.
If you don’t know which workaround to use, take the one I described just above (it’s what the migration code will do in the fix).

**Comment by jsreed** [comment] 2021-06-16 13:36
Thank you @mat007 and everyone else! Very much appreciated.

**Comment by ldeck** [comment] 2021-06-22 05:58
@mat007 I tried your recommended work-around, editing, settings.json and restarted Docker. 
This didn't work for me. 

I have updated from 3.3.3 to 3.4.0. Any other suggestions?

**Comment by ldeck** [comment] 2021-06-22 06:20
@mat007 okay I've got it working now. Here's the summary steps.

1. Quit Docker Desktop
1. Open '~/Library/Group Containers/group.com.docker/settings.json'
1. Locate the dataFolder field and change it to e.g. /Users/ldeck/Library/Containers/com.docker.docker/Data/vms/0
1. Go to ~/Library/Containers/com.docker.docker/Data/vms/0
1. Move Docker.raw to Docker.raw.bak
1. Move data/Docker.raw to Docker.raw
1. Save and restart Docker Desktop

**Comment by ldeck** [comment] 2021-06-22 06:23
Now the questions are
1. What are the paths that should remain under ~/Library/Containers/com.docker.docker/?
2. What can be purged?

**Comment by rfsx0829** [comment] 2021-06-22 07:32
I believe that changing the path in `~/Library/Group Containers/group.com.docker/settings.json` is the most correct way, but now there is another problem.

After updating to 3.4.0, due to the bug we discussed, our original data was at location `~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw`, but in recent days the data generated using docker existed with location `~/Library/Containers/com.docker.docker/Data/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw` before the configuration file was changed correctly, so is there any way to merge the data from these two files now?

**Comment by StefanScherer** [comment] 2021-06-23 18:40
We have just released Docker Desktop 3.5.0 which contains a fix for this issue. I'll close this ticket now, but feel free to comment and give us feedback. If there is still a problem, please open a new ticket.

**Closed by StefanScherer** 2021-06-23 18:40 UTC
Labels: version/10.14.6, version/11.4

**Comment by jmmen1** [comment] 2021-07-02 17:23
I just updated to 3.5.0 from 3.4 today, and most of my images (but not all) are gone. I searched ~/Library/Containers/com.docker.docker/Data for `Docker.raw`, but only found `vms/0/data/Docker.raw`.

Does this mean my previous VM that had my other images is now lost?
