### ISSUE TITLE
amd64 New Virtualization Framework host.docker.internal networking broken

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5410] opened 2021-03-02 14:45 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4D073710-26E7-4DA2-9AA5-BFC1A7A6397E/20210302144302

### Expected behavior

Docker Desktop for Mac 3.2.0 - It was suggested that I try out the new Virtualization Framework over in https://github.com/docker/for-mac/issues/5407#issuecomment-788783616

Unfortunately, I immediately found that it doesn't work with NFS (timeout errors)

A bit more exploration showed that host.docker.internal (or networking) doesn't work

I should be able to communicate from inside a container to host.docker.internal, but:

```
$ docker run -it busybox ping -c1 host.docker.internal
PING host.docker.internal (192.168.65.2): 56 data bytes
```

It never succeeds. As a result, xdebug debugging and NFS mounting, among other things, are unusuable.

### Actual behavior

No networking to host.docker.internal

### Information
  - macOS Version: macOS Big Sur 11.2.2
  - Docker Desktop Version: 3.2.0 amd64, new virtualization enabled.

**Comment by stephen-turner** [comment] 2021-03-02 15:37
@djs55 Do we have a fix for this already?

**Comment by aswinmohanme** [comment] 2021-03-07 07:23
I can confirm this, the networking is broken

**Comment by djs55** [comment] 2021-03-08 10:55
Thanks for the report. I think I might know what's going on -- when the experimental feature flag is toggled, we don't restart the DNS server so it still contains old mappings. I suspect if you were to completely exit the application and then relaunch then the DNS would be correct.

I'll add a ticket to our backlog to cover this.

**Comment by jessedobbelaere** [comment] 2021-03-12 17:02
Thanks! I had the same issue, like djs55 mentions: just completely exiting the application and relaunching docker for mac fixed it 👍

**Comment by KatSick** [comment] 2021-03-31 11:58
I have the same issue with "new virtualization enabled" on Docker Desktop Version 3.2.2 and macOS Big Sur 11.2.3

**Comment by lwj5** [comment] 2021-04-05 11:22
> I have the same issue with "new virtualization enabled" on Docker Desktop Version 3.2.2 and macOS Big Sur 11.2.3
> _(restart Mac or Docker does not help)_

I can confirm this as well. Have reverted back for the time being.

**Comment by gjmveloso** [comment] 2021-04-05 17:34
Restoring Docker Desktop to its default settings via `Clear / purge data` then enabling `New virtualization enabled` prevent Docker engine to start:

```
default	13:24:23.661628-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 2m0.371074986s
default	13:26:54.080302-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 4m30.785226495s
default	13:27:24.143848-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 5m0.847885035s
default	13:27:54.226824-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 5m30.929908561s
...
default	13:33:25.055696-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 11m1.774096638s
```

Diagnostic reports:

```
Date/Time:        2021-04-05 13:22:23.336 -0400
End time:         2021-04-05 13:23:45.358 -0400
OS Version:       macOS 11.2.3 (Build 20D91)
Architecture:     x86_64h
Report Version:   32
Incident Identifier: 97E3AEB9-C93E-4D4F-82F9-79502614932D

Data Source:      Microstackshots
Shared Cache:     52762DF1-0E55-3F8B-9588-8169E6D0EB95 slid base address 0x7fff20104000, slide 0x104000

Command:          com.apple.Virtualization.VirtualMachine
Path:             /System/Library/Frameworks/Virtualization.framework/Versions/A/XPCServices/com.apple.Virtualization.VirtualMachine.xpc/Contents/MacOS/com.apple.Virtualization.VirtualMachine
Identifier:       com.apple.Virtualization.VirtualMachine
Version:          1.0 (18.5)
Build Version:    52
Project Name:     Virtualization
Source Version:   18005000000000
Parent:           UNKNOWN [1]
PID:              45955

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 82 seconds (549 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 82s
Duration:         82.02s
Duration Sampled: 81.69s
Steps:            84

Hardware model:   MacBookPro15,2
Active cpus:      8
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Fan speed:        5428 rpm
``` 
Diagnostics ID: `7E4C2CA2-3893-4F77-ACA5-2621A31EB4A5/20210405172525`

**Comment by Zenexer** [comment] 2021-04-14 13:54
Should this be tagged `area/m1` even though the report is for amd64?  I'm not able to reproduce this on M1, v3.3.0 (62632), RC3.

**Comment by Zenexer** [comment] 2021-04-14 13:56
@gjmveloso, that sounds like an unrelated issue; is there a reason you posted it in this issue (e.g., was it while troubleshooting the networking issue)?

**Comment by stephen-turner** [comment] 2021-04-14 14:07
I tagged it "area/m1" because it is due to the new virtualization framework, which at the time was the default on M1 but not on Intel. But I'll untag it again now.

**Comment by gjmveloso** [comment] 2021-04-15 20:59
> @gjmveloso, that sounds like an unrelated issue; is there a reason you posted it in this issue (e.g., was it while troubleshooting the networking issue)?

the reason was this issue was the closest one to what happen when New Virtualization Framework is enabled on Big Sur 11.2.3. From the logs seems like the daemon wait indefinitely for an open socket. 

The same behavior happens on 3.3.0

**Comment by gjmveloso** [comment] 2021-04-16 13:27
Message has changed a little bit on 3.3.1

```
default	09:21:01.627343-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m10.478755979s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
default	09:21:11.639646-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m20.49111389s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
...
default	09:21:31.696991-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m40.548274839s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
default	09:21:41.718591-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 
default	09:23:32.018342-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 5m40.868626094s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
default	09:23:42.035670-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 5m50.885877973s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
default	09:23:52.057899-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 6m0.907944468s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused 
``` 

Diagnostics ID: 7E4C2CA2-3893-4F77-ACA5-2621A31EB4A5/20210416132144

**Comment by karaarda** [comment] 2021-04-28 22:10
For anyone who is experiencing this, it might be needed to change your exports file. Instead of exporting to localhost you should allow connection from the local network.

This would become 
`/Projects -alldirs -mapall=501:20 localhost`

this:
`/Projects -network 192.168.0.0 -mask 255.255.0.0 -alldirs -mapall=501:20`

**Comment by karaarda** [comment] 2021-04-28 22:38
If you are not able to even ping the host you can do the following:

Add an alias for your localhost
`sudo ifconfig lo0 alias 123.123.123.123/24`

Then export your nfs folders to this new IP and docker:
`/Users/arda/Projects -aldirs -mapall=501:20 123.123.123.123 192.168.64.4`

Then you can use the new ip instead of host.docker.internal
`addr=123.123.123.123,ro,nolock,hard,nointr,nocto,acdirmax=120,acdirmin=120,acregmax=120,acregmin=60,rsize=131072,wsize=131072,noatime,nfsvers=3`

**Comment by x8x** [comment] 2021-05-04 17:45
> Message has changed a little bit on 3.3.1
> 
> ```
> default	09:21:01.627343-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m10.478755979s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
> default	09:21:11.639646-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m20.49111389s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
> ...
> default	09:21:31.696991-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 3m40.548274839s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
> default	09:21:41.718591-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 
> default	09:23:32.018342-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 5m40.868626094s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
> default	09:23:42.035670-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 5m50.885877973s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused
> default	09:23:52.057899-0400	com.docker.supervisor	still waiting to update HTTP proxy on http-proxy-control.sock after 6m0.907944468s. Last error was Post "http://localhost/vm/httpproxy": dial unix http-proxy-control.sock: connect: connection refused 
> ```
> 
> Diagnostics ID: `7E4C2CA2-3893-4F77-ACA5-2621A31EB4A5/20210416132144`

Any news on this (sill no go on 3.3.2)? Is it known not working on Intel?
Where is the setting "Use new virtualisation framework" stored? Not found in `~/.docker/daemon.json` so at the moment I found no better solution than `Reset to factory defaults`
Thank you!

**Comment by djs55** [comment] 2021-05-05 08:22
@x8x the `useVirtualizationFramework` setting is in `~/Library/Group\ Containers/group.com.docker/settings.json`.

I notice the timestamp of your diagnositcs `20210416132144` is several weeks old. Could you upload a fresh diagnostics with 3.3.2? Unfortunately the UI for this is broken (a fix will be released imminently in 3.3.3) but you can upload via the command-line:
```
 /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
Thanks in advance!

**Comment by njt1982** [comment] 2021-05-07 10:50
@karaarda 's export change helped a lot here...  I was getting this:

```
ERROR: for ddev-[REDACTED]-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-[REDACTED]_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nthompson/Sites/[REDACTED]:/var/lib/docker/volumes/ddev-[REDACTED]_nfsmount/_data, data: addr=192.168.64.1,hard,nolock: permission denied
```

**Comment by njt1982** [comment] 2021-05-07 11:37
@karaarda does this change expose the docker to the local 192.168.x.x network? Is this a risk if, for example, we visit a cafe and connect to public wifi?

**Comment by x8x** [comment] 2021-05-08 00:29
@djs55 That was @gjmveloso 's diagnostics, here is mine with version 3.3.3:
FEF9C1BD-2417-4FDC-8BB1-E0C8E21A98E0/20210508002404

**Comment by karaarda** [comment] 2021-05-09 10:22
> @karaarda does this change expose the docker to the local 192.168.x.x network? Is this a risk if, for example, we visit a cafe and connect to public wifi?

I am not sure but it might be risky, you may update your exports to have a fixed ip address every time and restart nfsd.

You should be able to find the ip address by using the following command:

`docker run --rm -it --privileged --pid=host alpine nsenter -t 1 -m -u -i -n -p -- ip addr show eth0`

**Comment by gjmveloso** [comment] 2021-05-11 13:29
Message from 3.3.3 is back to 3.2.x wording:

```
default	09:25:22.043375-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 30.069252342s
default	09:25:52.138511-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 1m0.163834817s
default	09:26:22.237005-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 1m30.261378908s
default	09:26:52.339133-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 2m0.362916999s
default	09:27:22.437202-0400	com.docker.driver.amd64-linux	still waiting for docker to respond after 2m30.460263374s
```

Diagnostics ID: `7E4C2CA2-3893-4F77-ACA5-2621A31EB4A5/20210511132459`

**Comment by rfay** [comment] 2021-05-20 16:42
@krukid I imagine your problem is https://github.com/docker/for-mac/issues/5680

**Comment by pauldraper** [comment] 2021-05-20 17:32
The steps directly from Docker's documentation don't work.

https://docs.docker.com/docker-for-mac/networking/

```
 docker run --rm -it alpine sh
 apk add curl
 curl http://host.docker.internal:8000
 exit
 ```

**Comment by MrBenGriffin** [comment] 2021-05-25 14:26
host.docker.internal doesn't work for me. with the new virtualization framework (Docker 3.3.3) on Big Sur Intel - Mac OS 11.4 (20F71) / 3.2 GHz 6-Core Intel Core i7

**Comment by codecakes** [comment] 2021-05-26 09:05
+1 Diagnostics ID:     66528A0C-F315-4AC8-9C86-246FD4BFF365/20210526090239

**Comment by alexcombessie** [comment] 2021-05-28 15:07
I have the same issue on a MacBook Air with an M1 chip. Only solution I found was to deactivate the new virtualization framework.

**Comment by ErickAgrazal** [comment] 2021-05-31 16:24
Getting the same issue on an M1 Mac Mini. Had to deactivate the new virtualization framework to get docker working again.

Mac OS Version: 11.3 (20E232)
Docker Desktop Version: 3.3.3 (64133)
Docker Version: 20.10.6, build 370c289

**Comment by wunderkind2k1** [comment] 2021-06-03 07:44
Getting the same issue on an mavbook pro i9. Had to deactivate the new virtualization framework to get docker working again.

Mac OS Version: 11.4
Docker Desktop Version: 3.3.3 (64133)
Docker Version: 20.10.6, build 370c289

**Comment by djs55** [comment] 2021-06-10 16:45
In Docker Desktop 3.4.0 there is a fix for the internal DNS server to ensure the `*.docker.internal` entries are changed when the `virtualization.framework` mode is switched on and off. I think this issue should now be fixed. I'll mark this issue as closed, but if it is still broken please upload a fresh set of diagnostics, quote the ID here and ping me. I'll take a look and re-open if necessary.

Thanks everyone for your patience!

**Closed by djs55** 2021-06-10 16:45 UTC
Labels: version/3.2.0, version/3.2.2, version/3.3.1, version/3.3.3

**Comment by KatSick** [comment] 2021-06-10 16:46
Yep it works for me! Thanks!

**Comment by gjmveloso** [comment] 2021-06-11 13:00
Worked for me too. Just updated to 3.4.0.5223 and tried to enable the New Virtualization Framework option. Up and running within 30 seconds or so. And computer is **a lot cooler** as well.

Diagnostics ID: `7E4C2CA2-3893-4F77-ACA5-2621A31EB4A5/20210611125808`
