### ISSUE TITLE
Docker does not work for users with home folder on an other disk

### ISSUE THREAD

**Issue by xvolks** [docker/for-mac#842] opened 2016-10-25 08:01 UTC
### Expected behavior

Docker should start / work
### Actual behavior

 /var/run/docker.sock does not exist
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/F5D2B84B-8265-474D-BEC6-540916B47052/20161025-095637.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

F5D2B84B-8265-474D-BEC6-540916B47052
### Steps to reproduce the behavior
- Plug an external drive
- Create a macOS user with HOME on that drive
- Install Docker
- Test Docker
### Workaround
- Manually linking the socket makes it work.
- On my Mac:
  sudo ln -s ~/Library/Containers/com.docker.docker/Data/s60 /var/run/docker.sock

**Comment by samoht** [comment] 2016-11-03 22:30
Closing as a duplicate of #771

**Closed by samoht** 2016-11-03 22:30 UTC
Labels: osx/10.12.x, status/0-triage, status/1-acknowledged, version/1.12.1
