### ISSUE TITLE
docker info or any docker command on macos not working

### ISSUE THREAD

**Issue by tvfischer** [docker/for-mac#491] opened 2016-09-01 12:41 UTC
### Expected behavior

after starting docker, expect to be able to run any docker command in terminal and get results as listed in documentation.

### Actual behavior

After starting docker, the docker commands in the terminal all complain that they cannot connect to docker.

```
tfischer-MBP:ATPDev tfischer$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```
IT claims that the docker deamon is not running but the sock file exists
```
fischer-MBP:ATPDev tfischer$ ls -al  /var/run/docker.sock 
lrwxr-xr-x  1 root  daemon  55  1 Sep 13:35 /var/run/docker.sock -> /var/root/Library/Containers/com.docker.docker/Data/s60
```

### Information

Diagnostic ID: 4500F151-4360-4FDF-8582-D64BCAE69B72
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Permission denied (EACCES) connecting to /var/run/docker.sock: check permissions
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. install docker from dmg
2. run docker wait for docker to say it is started
3. Open terminal session
4. enter docker info in terminal

**Comment by dave-tucker** [comment] 2016-09-01 13:39
@tvfischer 
Thanks for the report. Closing as a dupe of #47
There is also a workaround posted there that should help you out!

**Closed by dave-tucker** 2016-09-01 13:39 UTC
