### ISSUE TITLE
Docker login command accesses random KeyChain entries and fails

### ISSUE THREAD

**Issue by lindseyspratt** [docker/for-mac#1540] opened 2017-04-12 19:26 UTC
Expected behavior:
Running the command
     docker login -u USER -p PASS HOST:8443
should login to the specified repo.

Unexpected behavior:
Running the above command causes docker to ask to access the KeyChain for a randomly chosen entry.
If I deny the request, then the command fails with:
"error getting credentials - err: exit status 1, out: The user name or passphrase you entered is not correct."
If I allow the request, then the command fails with:
"Error saving credentials: error storing credentials - err: exit status 1, out: The specified item already exists in the keychain."

This problem may be related to #1371.

Docker version:
Client:
Version: 17.03.1-ce
API version: 1.27
Go version: go1.7.5
Git commit: c6d412e
Built: Tue Mar 28 00:40:02 2017
OS/Arch: darwin/amd64

Server:
Version: 17.03.1-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: c6d412e
Built: Fri Mar 24 00:00:50 2017
OS/Arch: linux/amd64
Experimental: false

Mac OS X version 10.12.3.

This problem does not appear to occur on Mac OS X version 10.11.6.

(This information was originally entered as a comment on #1371 after it was closed.)

**Comment by dsheets** [comment] 2017-04-13 11:51
What version of Docker for Mac are you running? I believe the credential helper fix was shipped in 17.03.1-ce-mac5. Could you please post the diagnostic ID from :whale: ➡️ `Diagnose and Feedback...` ➡️ `Diagnose & Upload`?

**Comment by lindseyspratt** [comment] 2017-04-13 19:10
From Diagnose and Feedback... 
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.3 (build: 16D32)

**Comment by joelika** [comment] 2017-04-28 03:28
I'm experiencing this same issue with 17.0.3.1-ce-mac5 running on macOS 10.11.6.

When running `docker login` either with `-u` / `-p` or without, macOS prompts to access a random keychain item. If that items is accepted, or denied, docker login fails to the registry.

Same thing happens if I do a `docker pull` at my registry. Running the same test with docker-engine on Ubuntu logins and pulls without issue to the same registry.

I just performed a diagnostic and upload: 464C7B24-64F1-4B84-9F4B-F99C30645BE3

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/464C7B24-64F1-4B84-9F4B-F99C30645BE3/20170427-232203.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by ebriney** [comment] 2017-04-28 12:32
It should be fixed in this version, diagnostics don't help us on this.
I tried to reproduce it with the same version and didn't succeed.
Do you use `secret-service` to secure your logins on ubuntu?

**Comment by joelika** [comment] 2017-04-28 14:11
> It should be fixed in this version, diagnostics don't help us on this.

Does this mean it should be working in docker 17.03.1-ce-mac5 (b18e2a50c), or a future release?

I do not use `secret-service` on Ubuntu, and just to be clear, I don't have an issue there. Just an issue with Docker for Mac. On Ubuntu, `docker login` correctly prompts me for my username and password, then logs in as expected. I was just providing a test that my private registry is indeed working.

With Docker for Mac, it selects a random keychain item, and if I select "Deny" in macOS, I get the error `error getting credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.` and login fails. If I delete whatever keychain item Docker is trying to access, it just picks a different one from my Keychain the next time I attempt to perform a `docker login` or `docker pull` on the Mac.

Happy to provide more info or try other troubleshooting measures if needed. Thanks!

**Comment by mcfusaro** [comment] 2017-04-28 15:05
Docker keeps on asking access to random entries in the keychain.

Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

<img width="546" alt="schermata 2017-04-28 alle 15 52 05" src="https://cloud.githubusercontent.com/assets/7362328/25531797/34e4f984-2c2b-11e7-9067-8206f51a52d6.png">
(sorry for the message in Italian, it's a request to access iPhoto credentials in the keychain)
 
This seems to  happen every time docker tries to access the network.
Commands like "docker images" or "docker ps" don't trigger the issue.

To note that everything worked smoothly until a few days ago. No updates have been installed explicitly.

**Comment by ronfritz** [comment] 2017-05-05 14:30
Seeing the same behavior here.

Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.11.6 (build: 15G1421)

`$ docker pull nexus.my-company.com:8082/ubuntu:17.04`

Keychain prompts for access to FirefoxAccounts. I click 'Deny'.

```
Error response from daemon: Get http://nexus.my-company.com:8082/v2/ubuntu/manifests/17.04: no basic auth credentials
```

Config: 
```
{
  "disable-legacy-registry" : true,
  "insecure-registries" : [
    "nexus.my-company.com:8082"
  ],
  "debug" : true,
  "experimental" : true
}
```

**Comment by NMichas** [comment] 2017-05-26 10:21
Is there a workaround for this? It's currently impossible to push images to private registries on macOS using Version 17.03.1-ce-mac12 (17661)...

**Comment by kevinseidler** [comment] 2017-05-26 10:46
I'm currently using this version and when I do "docker login -u <username> <registry>" it works.

**Comment by joelika** [comment] 2017-05-26 13:17
@kevinseidler, what version of macOS are you running? That command still causes the keychain prompt with a random keychain item (also shown in @mcfusaro comment) for me on macOS 10.12.5.

**Comment by kevinseidler** [comment] 2017-05-26 13:21
@joelika: macOS 10.12.4, but I now recognized that I **removed** `"credsStore": "osxkeychain"` from .docker/config.json in my user's folders

**Comment by NMichas** [comment] 2017-05-26 14:37
I switched to edge (17.05.0-ce-mac11 (17656)), just in case, but the error persists. I ended up removing the `credsStore` from my `config.json` too and now it, obviously, works since it doesn't try to use the Keychain.

* macOS 10.12.5 (16F73)

**Comment by joelika** [comment] 2017-05-26 15:00
Thanks @kevinseidler and @NMichas! I don't have a `~/.docker/config.json` file, but I did end up deleting `/usr/local/bin/docker-credential-osxkeychain`, and that made Docker revert back to using the standard login prompt. I can now do `docker login` or `docker pull` from my private registries. So at least we have a work around until this gets fixed.

**Comment by jasonbivins** [comment] 2017-06-23 14:58
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Closed by jasonbivins** 2017-06-23 14:58 UTC
Labels: status/0-more-info-needed, status/0-triage

**Comment by thiagofborn** [comment] 2018-09-12 10:47
> @joelika: macOS 10.12.4, but I now recognized that I **removed** `"credsStore": "osxkeychain"` from .docker/config.json in my user's folders

I have changed from: 
<pre>
{
  "credSstore" : "osxkeychain",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "stackOrchestrator" : "swarm"
}
</pre>

to: 
<pre>
{
  "credSstore" : "",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "stackOrchestrator" : "swarm"
}
</pre>

Then: 
docker logout 
docker login 
Login using just login name without @domain 
For instance if your login name is: blablabla@gmail.com use just blablabla and the password from your docker account. 

After this docker will encrypt your password on the file: ~/.docker/config.json
<pre> 
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "wefoiughfwepiouhrwpofehrpoi4="
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.06.1-ce (darwin)"
	},
	"stackOrchestrator": "swarm"
}

**Comment by yves-vogl** [comment] 2018-09-13 07:13
You should go for @thiagofborn workaround. Simply removing the line from config.json (or using the corresponding checkbox for this) is not the best solution.
