### ISSUE TITLE
4.25.0 keeps locking up

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#7044] opened 2023-10-26 17:41 UTC
### Description

I've restarted Docker multiple times and even restarted my laptop, but it keeps locking up

### Reproduce

1. Start docker
2. Run any container
3. Wait a minute or two
4. Notice that nothing is working even `docker ps` won't return

### Expected behavior

Docker works

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/dlj/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/dlj/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/dlj/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/dlj/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/dlj/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/dlj/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/dlj/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/dlj/.docker/cli-plugins/docker-scout

Server:
 Containers: 14
  Running: 4
  Paused: 0
  Stopped: 10
 Images: 36
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.759GiB
 Name: linuxkit-e6ae765274d2
 ID: faac2988-5d22-4a25-a96d-4cfc05a665f3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

F14EC0BF-E65E-45F4-B960-78F5BD1C8BD8/20231026173742

**Comment by t3easy** [comment] 2023-10-30 08:10
Had the same problem. After giving at least 512MB swap it's working again.

**Comment by daveisfera** [comment] 2023-10-30 16:38
I hadn't thought of that as a possibility, but I do have swap disabled. I believe that swap doesn't make sense on modern machines and I'd prefer to keep it off. It's worked just fine in the past and sounds like a bug was introduced in 4.25.0

**Comment by t3easy** [comment] 2023-10-30 16:52
> I hadn't thought of that as a possibility, but I do have swap disabled. I believe that swap doesn't make sense on modern machines and I'd prefer to keep it off. It's worked just fine in the past and sounds like a bug was introduced in 4.25.0

@daveisfera Sure, I'm of the same opinion. It was only meant as a workaround to be able to work again quickly.

**Comment by RyutaKojima** [comment] 2023-11-01 07:52
@t3easy 
The same thing happened in my environment and I was able to work around it by setting Resource swap from 0 to 512MB as well.
Thank you so much!!

**Comment by daveisfera** [comment] 2023-11-01 15:17
> > I hadn't thought of that as a possibility, but I do have swap disabled. I believe that swap doesn't make sense on modern machines and I'd prefer to keep it off. It's worked just fine in the past and sounds like a bug was introduced in 4.25.0
> 
> @daveisfera Sure, I'm of the same opinion. It was only meant as a workaround to be able to work again quickly.

Sorry, didn't mean to imply anything negative toward you. Just wanted to point out to the Docker folks that it used to work and I hope it will work again

**Comment by vladimir-mihov** [comment] 2023-11-02 17:49
Same here. Constant freezes and sometimes failure to pull images from Docker hub, e.g.

`ERROR: failed to solve: eclipse-temurin:17-jre-jammy: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/31/31d13e8d1c5e7ebd65b9399c21e128ca9147e2631306928d823cfd1fbb69fda6/data?verify=1698950140-cXzi69jDz%2FBx%2FhBinLJbKfu7vqs%3D": proxyconnect tcp: dial tcp: lookup http.docker.internal on 192.168.65.7:53: read udp 192.168.65.6:56229->192.168.65.7:53: read: connection refused`

Which was fixed by giving it some swap space. Thanks for the workaround!

**Comment by biasedbit** [comment] 2023-11-03 22:37
Consistently happening to me since I upgrade to v4.25.0 (macOS 14.0) and I had swap set to 1GB. Still happening with resources:
- Memory: 16GB
- Swap: 2GB (increased from 1GB)
- Disk: 120GB

This is new since 4.25.0

**Comment by trungdlp-wolffun** [comment] 2023-11-06 07:29
> Had the same problem. After giving at least 512MB swap it's working again.

You're my hero 😇

**Comment by djs55** [comment] 2023-11-07 09:48
Thanks for the report, there is a definitely an issue when the swap is set to zero. I've created a development build with a fix:
 - [Intel Docker.dmg](https://desktop-stage.docker.com/mac/main/amd64/127420/Docker.dmg)
 - [Apple Silicon Docker.dmg](https://desktop-stage.docker.com/mac/main/arm64/127420/Docker.dmg)

If you're having problems with swap, let me know if that helps.

If your case has swap enabled it's probably a different issue. Could you reproduce, upload a diagnostics and quote the ID?

**Comment by CodeNameNinja** [comment] 2023-11-07 12:16
I can't seem to enable Kubernetes in `Docker Desktop 4.25.0`

**Comment by daveisfera** [comment] 2023-11-07 20:52
> Thanks for the report, there is a definitely an issue when the swap is set to zero. I've created a development build with a fix:

I've been running with this today with swap still set at 0 and haven't see any problems

**Comment by lorenrh** [comment] 2023-11-14 10:10
We've released a new version of Docker Desktop containing a fix for this issue, you can see [the release notes](https://docs.docker.com/desktop/release-notes/)! I'll close this issue for now, but if the issue persists, feel free to open a new issue!

**Closed by lorenrh** 2023-11-14 10:10 UTC
Labels: area/startup, status/triage, version/4.25.0

**Comment by daveisfera** [comment] 2023-12-09 17:52
This happened with 4.26.0:
F14EC0BF-E65E-45F4-B960-78F5BD1C8BD8/20231209005500
