### ISSUE TITLE
Cannot mount /var/somefolder on Mac

### ISSUE THREAD

**Issue by mark-lb** [docker/for-mac#705] opened 2016-09-27 07:33 UTC
### Expected behavior
`docker run -ti -v /var/www/vhosts:/var/www/vhosts ubuntu` should work 
### Actual behavior
In version 1.12.1 there is apparently no way to make /var/xxxx on Mac usable for docker. For example, adding `/var/lib/something` to the Docker file sharing preferences actually adds `/private/var/lib/something`, and then the command above does not work
### Information
Also see https://forums.docker.com/t/docker-for-mac-beta-does-not-handle-symlinks-when-mounting-volumes/10955

### Steps to reproduce the behavior

  1. On macOS Sierra open Docker 1.21.1 preferences and attempt to add `/var/lib/something` to the list of host directories that can be mounted into Docker containers 
  2. See that the preferences GUI shows `/private/var/lib/something` since on Mac /var is a symlink to `/private/var`
  3. Docker scripts that reference `/var` will not work

**Comment by dsheets** [comment] 2016-09-27 10:17
This issue is a duplicate of #412. Thanks for reporting this problem. We have increased the priority of the fix. Sorry this is causing issues for you. Thanks for using Docker for Mac!

**Closed by dsheets** 2016-09-27 10:17 UTC
Labels: status/0-triage

**Comment by dsheets** [comment] 2017-01-16 15:48
This was fixed in Beta 33 and has been recently improved in Beta 35 or 36 so that exported directory paths are editable and now manually enterable by editing a blank entry at the end of the list.

Thanks for your patience with this issue and for using Docker for Mac. This improvement should reach the stable channel in a week or two.
