### ISSUE TITLE
run --rm issue

### ISSUE THREAD

**Issue by shinstudio** [docker/for-mac#1420] opened 2017-03-11 01:22 UTC
### Expected behavior
run --rm command should remove instance after execution
### Actual behavior
leaves instance undeleted
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### I was using this docker command...

  1. docker run --rm -v `pwd`:/test nesvold/slimerjs:0.10.3 bash -c "/usr/bin/casperjs test /test/site.js"
  2. docker run --rm -v `pwd`:/test nesvold/slimerjs:0.10.3 bash -c "/usr/bin/casperjs test /test/site.js"
  3. docker run --rm -v `pwd`:/test nesvold/slimerjs:0.10.3 bash -c "/usr/bin/casperjs test /test/site.js"
  4. docker ps -a 

I have forked dockerfile for casperjs/slimerjs, which you can find from https://github.com/shinstudio/slimerjs. After git clone, run `docker build -t nesvold/slimerjs:0.10.3 .`

**Comment by iostat** [comment] 2017-03-13 01:00
Hello there! Just stumbled upon this issue as well. I am running with `--it --rm --ulimit nofile=65535` and two volumes attached via `-v`, one of which is named in the Dockerfile as a `VOLUME`. If anyone needs more info would be happy to assist. At the very least, @shinstudio and myself have attached volumes in common.

**Comment by dsheets** [comment] 2017-03-13 10:07
@shinstudio could you please post your Docker for Mac version and diagnostic ID from 🐳 ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload`? Also, what does `/test/site.js` contain? Do you observe the problem with reduced versions of that file? Could you post a version that reproduces the problem?

@iostat could you please post your Docker for Mac version and diagnostic ID from 🐳 ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload`? Also, if you have a test case that easily reproduces the issue, we would really appreciate it. :-) Thanks!

**Comment by iostat** [comment] 2017-03-13 13:54
@dsheets: I'd be happy to perform a diagnostic later tonight. I should note that this happened with both the Stable and Beta versions, and my diagnostic will be with the Beta version (I switched to see if it made a difference). 

I unfortunately can't reveal the Dockerfiles that led to my direct issue, so I've also been trying to make a minimal test case, to no avail so far. Will keep you updated.

**Comment by iostat** [comment] 2017-03-18 05:04
@dsheets sorry for the wait. on the bright side, I found an incredibly minimal reproduction.
This failing behavior is predicated on the `DOCKER_API_VERSION` being set, in my case being `1.24`.

Diagnostic ID: `B352D9E7-2808-4498-9524-EA431C9E693E`

Reproduction follows:
```shell
#!/bin/sh
echo this will totally work

docker version
docker run --rm --name whoops alpine sh -c "echo hooray"
docker run --rm --name whoops alpine sh -c "echo you will see this"
docker ps -a

echo
echo
echo ================
echo 
echo

echo set sail for fail
DOCKER_API_VERSION=1.24 docker version
DOCKER_API_VERSION=1.24 docker run --rm --name whoops alpine sh -c "echo oh noes"
DOCKER_API_VERSION=1.24 docker run --rm --name whoops alpine sh -c "echo you wont see this"
DOCKER_API_VERSION=1.24 docker ps -a
echo manual rm works though
DOCKER_API_VERSION=1.24 docker rm whoops
DOCKER_API_VERSION=1.24 docker ps -a
```


my output:
```
$ ./repro.sh
this will totally work
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
hooray
you will see this
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES


================


set sail for fail
Client:
 Version:      17.03.0-ce
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
oh noes
docker: Error response from daemon: Conflict. The container name "/whoops" is already in use by container 90f1cc667a66e066cfaa88f0a4ae98711cc60db764ebeb0b0cb82a7284d5f11c. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                              PORTS               NAMES
90f1cc667a66        alpine              "sh -c 'echo oh noes'"   3 days ago          Exited (0) Less than a second ago                       whoops
manual rm works though
whoops
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by iostat** [comment] 2017-03-18 05:14
perhaps related to docker/docker#30341?

**Comment by djs55** [comment] 2017-03-21 14:27
@iostat I confirm this reproduces for me locally. I also suspect this is docker/docker#30341 -- I'll comment over there.

**Comment by djs55** [comment] 2017-03-21 14:37
I'll set the state to acknowledged, although it looks like a generic docker/docker issue rather than a docker/for-mac specific issue. Thanks for your report!

**Comment by avsm** [comment] 2017-03-28 17:55
This should hopefully be fixed in the Edge channel. With `17.03.1-ce-rc1`, I do see `docker --rm` working:

```
this will totally work
Client:
 Version:      17.03.1-ce-rc1
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Fri Mar 17 00:27:41 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce-rc1
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Wed Mar 15 20:28:18 2017
 OS/Arch:      linux/amd64
 Experimental: true
hooray
you will see this
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES


================


set sail for fail
Client:
 Version:      17.03.1-ce-rc1
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Fri Mar 17 00:27:41 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce-rc1
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Wed Mar 15 20:28:18 2017
 OS/Arch:      linux/amd64
 Experimental: true
oh noes
you wont see this
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
manual rm works though
Error response from daemon: No such container: whoops
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

@iostat if you could also confirm your bug is fixed in your main development environment, I'll close this issue.

**Comment by iostat** [comment] 2017-03-29 05:00
@avsm Just tested with `17.03.1-ce-rc1`, works 100% Thanks for the quick fix!

**Comment by avsm** [comment] 2017-03-30 09:45
Awesome, thanks again for taking the time to give us such accurate repro instructions @iostat!

**Closed by avsm** 2017-03-30 09:45 UTC
Labels: kind/bug, status/1-acknowledged
