### ISSUE TITLE
Explicit host network access from within container not working (M1 Preview)

### ISSUE THREAD

**Issue by tunecrew** [docker/for-mac#5432] opened 2021-03-07 20:49 UTC
Docker Desktop for Mac Preview 3.1.0
MacOS 11.2.2
Mac Mini M1

From within a running container on my machine, I am unable to access ports that are exposed on the host machine.

In other words, from my host machine (where in this case I have an ssh tunnel set up to an external database) I can successfully run this command:
```
> telnet localhost 3306
```
From inside a docker container running on my host machine, the following command times out:
```
> telnet docker.for.mac.localhost 3306
```
If I try the same thing using the same container on an Intel Mac (also running MacOS 11.2.2 and Docker Desktop for Mac 3.1.0) it does work as expected.

I'm running the container with `docker-compose up` and with `network_mode: bridge` set in my `docker-compose.yml` file.

Connecting to other local docker containers, however, does work as expected.

**Comment by stephen-turner** [comment] 2021-03-08 08:53
I think this is a dupe of #5410.

**Closed by stephen-turner** 2021-03-08 08:53 UTC

**Comment by tunecrew** [comment] 2021-03-08 12:56
Just to be clear - re. https://github.com/docker/for-mac/issues/5410 - `experimental` is set to `false` in my Docker prefs and restarting does not fix it (and it works w/ 3.1.0 on Intel).

**Comment by tunecrew** [comment] 2021-03-22 00:07
Just want to point out this is till happening in the latest RC version 3.3.0 (62029) on my M1 Mac Mini.

Identical container doing identical thing on an Intel MBP running version 3.2.2 (61853) does work correctly.

Again, I have not set `experimental` to `true` so I don't think this is the same as https://github.com/docker/for-mac/issues/5410

**Comment by hubgit** [comment] 2021-04-09 11:00
Have you tried `docker.for.mac.host.internal` or `host.docker.internal` instead of `docker.for.mac.localhost`?

**Comment by tunecrew** [comment] 2021-04-09 12:45
I have tried all of those, but I have not re-tested since the latest RC version came out.
