### ISSUE TITLE
Docker won't finish restarting

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1437] opened 2017-03-16 22:36 UTC
960549A5-E20C-4E41-B51B-FA16000C14C6

**Comment by djs55** [comment] 2017-03-21 15:57
In the diagnostics logs I can see:
```
2017-03-16 16:21:55-06 Daves-MacBook-Pro Docker[com.docker.driver.amd64-linux][96981] <Notice>: sending SIGTERM to com.docker.hyperkit pid 96986
2017-03-16 16:21:55-06 Daves-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][96781] <Notice>: VM shutdown at 2017-03-16 16:21:55 -0600 MDT
```
but the VM appears to be stuck shutting down:
```
/ # ESC[6n * Stopping local ... [ ok ]
 * Saving random seed ... [ ok ]
 * Stopping Hyper-V daemon: hv_vss_daemon ... * start-stop-daemon: no matching processes found
 [ ok ]
 * Stopping Hyper-V daemon: hv_kvp_daemon ... * start-stop-daemon: no matching processes found
 [ ok ]
 * Stopping busybox crond ... [ ok ]
 * Stopping chronyd ... [ ok ]
 * Stopping docker
 * Stopping proxy port service ... [ ok ]
 * Stopping DHCP Client Daemon ... [ ok ]
 * sysklogd -> stop: klogd ... [ ok ]
 * sysklogd -> stop: syslogd ... [ ok ]
 * Stopping docker socket passthrough ... [ ok ]
 * Stopping FUSE socket passthrough ... * start-stop-daemon: 1 process refused to stop
 * Failed to stop transfused
 [ !! ]
 * ERROR: transfused failed to stop
 * Stopping busybox acpid ... [ ok ]
 * Unmounting loop devices
 * Unmounting filesystems
 *   Unmounting /port ... [ ok ]
```
Looking at a successful reboot the next thing in the shutdown sequence should be:
```
 *   Unmounting /host_docker_app ... [ ok ]
 *   Unmounting /tmp ... *   in use but fuser finds nothing
 [ !! ]
 *   Unmounting /private ... [ ok ]
 *   Unmounting /data ... [ ok ]
 *   Unmounting /Volumes ... [ ok ]
 *   Unmounting /Users ... [ ok ]
 *   Unmounting /Database ... [ ok ]
 *   Unmounting /tmp ... *   in use but fuser finds nothing
 [ !! ]
 *   Unmounting /var ... *   in use but fuser finds nothing
 [ !! ]
 * Stopping busybox mdev ... [ ok ]
 * Setting hardware clock using the system clock [UTC] ... [ ok ]
 * Terminating remaining processes ... [ ok ]
 * Killing remaining processes ... [ ok ]
 * Saving dependency cache ... [ ok ]
 [ ok ]
 * Remounting remaining filesystems read-only ... *   Remounting /tmp read only ... [ ok ]
 *   Remounting /tmp read only ... [ ok ]
 *   Remounting /var read only ... [ ok ]
 *   Remounting / read only ... [ ok ]
 [ ok ]
^MThe system is going down NOW!
^MSent SIGTERM to all processes
^MSent SIGKILL to all processes
^MRequesting system poweroff
reboot: Power down
```
and the following processes are still running:
```
26282 root       0:00 /sbin/openrc shutdown
27294 root       0:00 {localmount} /sbin/openrc-run /etc/init.d/localmount --lockfd 39 stop
27295 root       0:00 {openrc-run.sh} /bin/sh /lib/rc/sh/openrc-run.sh /etc/init.d/localmount stop
27327 root       0:00 mountinfo --quiet /host_docker_app
27525 root       0:00 /bin/ps uax
32734 root       0:07 [kworker/3:2]
```
Since the process watchdog wasn't involved and didn't `SIGKILL` the stuck process this appears to be a duplicate of https://github.com/docker/for-mac/issues/1130#issuecomment-272152506

As a workaround you could kill this process:
```
96986   ??  S    1946:04.79 /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit 
```

I'll close this issue as a duplicate of #1130. Let me know if this is easy to reproduce, as I would also like to discover exactly why the VM shutdown blocked.

Thanks for your report and using Docker for Mac!

**Closed by djs55** 2017-03-21 15:57 UTC
Labels: status/0-triage

**Comment by daveisfera** [comment] 2017-03-21 16:17
This issue only happens occasionally and so I don't know of any way to reproduce it.
