### ISSUE TITLE
Segfault using debian:wheezy

### ISSUE THREAD

**Issue by mtibben** [docker/for-mac#2188] opened 2017-10-31 09:02 UTC
Using Docker Edge 17.10.0-ce-mac36 on High Sierra

### Steps to reproduce the behavior
```
$ docker run -it debian:wheezy bash
Segmentation fault
$ echo $?
139
```

Other images don't have this issue e.g. this works fine
```
docker run -it debian:stretch bash
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
3DDC904E-CED4-4926-9E0F-646B681F5D3E
```

```
Docker for Mac: version: 17.10.0-ce-mac36 (a38d9cd48bd0ee31ec82c59b783aa2f2817bfb92)
macOS: version 10.13 (build: 17A405)
logs: /tmp/3DDC904E-CED4-4926-9E0F-646B681F5D3E/20171031-195721.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by gtardif** [comment] 2017-11-03 16:12
duplicate of #2169. 
This should now work with 17.11.0-ce-rc2-mac37 released today

**Closed by gtardif** 2017-11-03 16:12 UTC
Labels: status/0-triage, version/17.10.0-ce-mac36
