### ISSUE TITLE
Docker is not responding after macOS sleep

### ISSUE THREAD

**Issue by quozd** [docker/for-mac#189] opened 2016-08-09 08:22 UTC
### Expected behavior

Docker works

### Actual behavior

Any command to docker engine is not responding and just hangs. Restart usually crash docker, sometimes restart is successful but docker doesn't work. Reset or reboot fix the issue.

Issue is easily reproducible. On macOS public beta 1 everything worked fine.

### Information

Diagnostic ID: C044C24C-818C-4CBE-B7DE-22924BE6B39C
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Run docker container
2. Put macOS to sleep (tested on MPB, closing the lid is just enough)
3. Wake it up
4. Run docker ps
5. No response

**Comment by dave-tucker** [comment] 2016-08-09 10:24
Closing as this looks like another dupe of #64

**Closed by dave-tucker** 2016-08-09 10:24 UTC

**Comment by djs55** [comment] 2016-09-15 16:27
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
