### ISSUE TITLE
Crash on macOS Sierra Beta 4: vmstateevent invalid json

### ISSUE THREAD

**Issue by mazdak** [docker/for-mac#64] opened 2016-08-02 00:20 UTC
### Information

Diagnostic ID: 03F36B64-C00E-4BEC-A53C-D6220319EE23
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Without doing anything in particular, an error dialog pops up:

vmstatevent invalid json:

No other info.

**Comment by tgautier** [comment] 2016-08-02 09:56
Same problem here with macOS Sierra beta 4 (16A270f)

Docker for Mac doesn't start

```
Diagnostic ID: 286C9B6C-A49D-4643-B12B-C807C3C58F1F
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by avsm** [comment] 2016-08-02 09:57
Thanks -- updating to beta4 now to attempt to repro.

**Comment by saleksandras** [comment] 2016-08-02 13:17
Same here.
Diagnostic ID: E0EC5F4A-4181-4877-A22A-AD1DA289808A

**Comment by jenswellmeyer** [comment] 2016-08-02 13:35
Me too:
811625D4-05BA-424C-9BE2-1FCE8C03DE94

**Comment by simonmd** [comment] 2016-08-02 23:36
same. 6E55A639-AB04-480D-8F1A-74D7C28712AA

**Comment by stolus** [comment] 2016-08-03 11:36
When will this be fixed?

**Comment by toffaletti** [comment] 2016-08-05 17:35
Docker for Mac needs to be built with Go 1.7rc5 or later for this to be resolved. See:

https://github.com/golang/go/issues/16606
https://github.com/golang/go/commit/da070bed19fb23a8dd1b9f974c7fdf1f247fdba0

**Comment by bunchjesse** [comment] 2016-08-05 22:51
@toffaletti Is there any workaround currently or is there a way for me to build D4M locally?

**Comment by toffaletti** [comment] 2016-08-06 04:38
You could theoretically rebuild the open source parts on a pre-sierra Mac and replace the binaries inside the Docker.app bundle, but there are parts that seem to be closed source in a private repo: github.com/docker/pinata

**Comment by stolus** [comment] 2016-08-08 06:04
@bunchjesse You can refer to this issue: [macOS Sierra - Compatibility - Docker for Mac](https://github.com/docker/docker/issues/24675) 
Just simply execute 
`sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist`
will fixed.

**Comment by dsheets** [comment] 2016-08-08 09:52
@stolus @bunchjesse this issue concerns the crashes experienced with Sierra Beta 4 which involve the error popup "vmstateevent invalid json:". We believe this issue to be caused by golang's incorrect binding to Sierra's `gettimeofday` which changed ABI in Beta 4. Disabling the NTP daemon will likely not stop this crash and will cause uncorrected clock skew in the VM after sleep. There is no workaround until we rebuild our various go components with a golang compiler fixed for Sierra Beta 4. The next stable golang release which is supposed to support Sierra is 1.7 which was targeted to be released on August 1 and so should be released any day now. I'm sorry for the inconvenience.

**Comment by bunchjesse** [comment] 2016-08-08 15:33
@dsheets Thanks for the thorough explanation. It is no problem at all. I understand that working with prerelease OS bits can be challenging. Keep up the great work. 👍

**Comment by brockbackups** [comment] 2016-08-09 02:27
So.... after I did a fresh clean install and installed Docker for mac again instead of using upgrade from 10.11.6 or using all docker.app from time machine, working fine without issue.

**Comment by leaxoy** [comment] 2016-08-09 02:30
+1

**Comment by bunchjesse** [comment] 2016-08-09 02:32
@brockbackups When you did the erase install you did install macOS Sierra right? If so, wait for it. D4M might work for a few hours or a day at most but you'll see this error again until Go 1.7 is released and the D4M team is able to rebuild their stack to correct for the incorrect bindings.

**Comment by brockbackups** [comment] 2016-08-09 02:37
Yes did a fresh clean install of macOS Sierra 10.12 DP3 then did a combo update of DP4 and been running with no issues from Docker for mac for about 6 days now

**Comment by RowanKaag** [comment] 2016-08-12 13:49
for those who might've expected that this was resolved with 1.12.0-a, you're out of luck. This was still built with `Go version:   go1.6.3`. Next update might involve this new version. Keep up the good work Docker!

**Comment by mihar** [comment] 2016-08-13 15:52
Beta 5 has same issue `5D0A0B2A-E88A-4E5D-AD8D-AF98D87D8E99`

**Comment by kwojtaszek** [comment] 2016-08-14 09:41
It looks like it isn't related to Go support in Sierra. According to [changelog](https://tip.golang.org/doc/go1.7) support for Sierra was backported to Go 1.6.3.

**Comment by ununseptium** [comment] 2016-08-15 05:44
Can confirm on Mac OS 10.12 (16A286a) 

The app unexpectedly crashes.

**Comment by dsheets** [comment] 2016-08-15 10:15
@kwojtaszek that document is out-of-date. Please see the `golang/go` links up-thread for more up-to-date information regarding golang on the Sierra Beta.

**Comment by glynjackson** [comment] 2016-08-15 12:53
From my understanding, this issue cannot be fixed until the Docker team build against the 1.7 version of Go. I'm aware this is Beta and should not be used in production, but with the update of Mac OS in the very near future can the Docker team give us an update, officially, on this known issue? Thanks in advance.

**Comment by jianbin-wei** [comment] 2016-08-16 02:39
Just FYI that this is still the issue for macOS beta 5.

**Comment by bunchjesse** [comment] 2016-08-16 03:21
It's here! It's here! https://blog.golang.org/go1.7

**Comment by lewisflude** [comment] 2016-08-16 09:04
Is there any other way to get Docker working in the meantime?

**Comment by glynjackson** [comment] 2016-08-16 10:17
@lewisflude I would normally say use Docker Toolbox but that is no longer working on Beta 6 of MacOS for me either! The only way is to NOT use MacOS Sierra. Sierra is almost out tho so fingers crossed the stable version of Docker for Mac is fixed for then!

**Comment by glynjackson** [comment] 2016-08-16 10:20
@dsheets Is there a version of Docker for Mac that we can test build against the fixed version of Go coming out? We are running a number of machines on Sierra due to having to test Xcode beta 6.

**Comment by lewisflude** [comment] 2016-08-16 10:21
@glynjackson TOUCH WOOD docker-toolbox seems to be working so far (didn't the first time). Lots of uninstalling and reinstalling. Seems the included version of VirtualBox was causing some issues so had to update that.

**Comment by dustinwtf** [comment] 2016-08-16 17:09
Now that go 1.7 has been released, when should we expect the Docker For Mac beta to be updated?

**Comment by dsheets** [comment] 2016-08-17 12:43
Docker for Mac Beta 23 has been released which fixes this particular issue with our use of golang and macOS Sierra Beta 4+ by building with golang 1.7. Please report other problems with macOS Sierra Beta in another issue thread.

**Closed by dsheets** 2016-08-17 12:43 UTC

**Comment by jianbin-wei** [comment] 2016-08-17 13:07
After upgrading to it, it works fine on my macOS Sierra Beta 5.

**Comment by mhgs** [comment] 2016-08-17 13:09
Also on macOS Sierra Beta 6 its working fine. I did had to remove all docker related files to get it up and running, followed these instructions https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/

**Comment by jianbin-wei** [comment] 2016-08-17 13:19
I don't need to remove any docker related files though.  

I just start docker, check for upgrade, docker crashes, but the check for upgrade keeps running and finishing the upgrade.

**Comment by ununseptium** [comment] 2016-08-17 13:23
I need to remove everything it kinda bugged out. (Beta 6) 

But FYI Docker has a uninstall option: http://imgur.com/a/yapWX (when you can get into the ui)

**Comment by lewisflude** [comment] 2016-08-17 13:24
I had to do what @mhgs as well as using AppCleaner to manually clean up whatever Docker left behind. It _seems_ that Docker for Mac is working now!

**Comment by codeofsumit** [comment] 2016-08-19 19:49
I still got errors after using AppCleaner and the uninstall steps mentioned in the article - but somehow after restarting a couple of times Docker actually started and is working now. I won't restart it ever again :-)

**Comment by RowanKaag** [comment] 2016-08-21 08:06
@dsheets I've removed Docker with AppCleaner, downloaded the Beta Channel and I'm facing this:

- macOS Sierra - Beta (6?) - build 16A294a
- Docker for Mac - v1.12.1-rc1-beta23

`docker version`
```
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 **Go version:   go1.6.3**
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1-rc1
 API version:  1.24
 **Go version:   go1.6.3**
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Shouldn't this be built with `Go 1.7`?

**Comment by toffaletti** [comment] 2016-08-22 17:18
I've got the same problem, the beta reports being built with go 1.6.3, not go 1.7:

```
$ docker version
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true
```

This is likely the cause of #202 and all of its duplicates.

**Comment by dsheets** [comment] 2016-08-23 09:44
The `docker` client is still built with 1.6.3 as it uses the official engine build. The Docker for Mac-specific binaries which use golang, `com.docker.frontend` in particular, have been built with golang 1.7. #202 is a Swift/OS X only issue and so is unlikely related to the golang/Sierra issues.

**Comment by lexbi** [comment] 2016-09-07 20:23
I'm on macOS Sierra V7, installed and setup Docker today for the first time, got the same thing.

**Comment by dsheets** [comment] 2016-09-08 08:58
@lexbi what version of Docker for Mac are you running? We recommend running Docker for Mac Beta 25 on macOS Sierra Beta.

**Comment by lexbi** [comment] 2016-09-08 21:38
Oh sorry good idea, I'm on the stable version 1.12.0, I'll give that a go, thank you!

**Comment by h3smith** [comment] 2016-09-09 14:31
Getting the "vmstateevent invalid json" myself in macOS Sierra GM. Docker is completely unusable with the GM build of macOS.

**Comment by dsheets** [comment] 2016-09-09 14:40
@h3smith what version of Docker for Mac are you running? We recommend running Docker for Mac Beta 25 on macOS Sierra Beta (or GM) while we are preparing the stable release to coincide with the GA of macOS Sierra.

**Comment by h3smith** [comment] 2016-09-09 14:41
@dsheets I'll upgrade to the beta and see how it works. Thanks!

**Comment by Tuxity** [comment] 2016-09-09 14:44
Where I can find Beta releases ?

**Comment by Tuxity** [comment] 2016-09-09 14:45
@dsheets Where I can find Beta releases ?

**Comment by adammcnamara** [comment] 2016-09-09 14:46
@dsheets Beta 25 only works if it's a clean install on Sierra. The following does not work:

1. Have Docker < 25 installed
2. Upgrade to Sierra
3. Try to run Docker < 25 (corrupts something, appears to be Keychain related)
4. Upgrade to Docker 25

**Comment by dsheets** [comment] 2016-09-09 14:46
The beta channel is downloadable from <https://download.docker.com/mac/beta/Docker.dmg>. Be sure to uninstall any current installation before installing the beta as we do not yet support/test arbitrary channel change migrations. <https://docs.docker.com/docker-for-mac/> has more information about the release channels (and lots of other helpful info).

**Comment by Tuxity** [comment] 2016-09-09 14:47
@dsheets Thanks! Gonna try right now!

**Comment by dsheets** [comment] 2016-09-09 14:49
@adammcnamara that is correct. Betas prior to 25 had severe stability issues caused by some golang incompatibilities (this issue) and a misunderstanding of and slight change in a macOS API (#202). Thanks for pointing out this pitfall. Do you have a suggestion for how we can reduce the damage as both Sierra and Docker for Mac reach stability on 10.12?

**Comment by h3smith** [comment] 2016-09-09 14:51
Without a clean sierra install (what dev can do that lol) - is uninstalling Docker and reinstalling the beta fresh the work around or does that leave keychain issues as reported above?

**Comment by adammcnamara** [comment] 2016-09-09 14:52
@dsheets Could you point out how to completely uninstall Docker for Mac? This would allow me to do a fresh install. Right now:

1. Deleting Docker.app doesn't remove everything.
2. "Uninstall" inside Docker Preferences fails.
3. The command line uninstall suggested [here](https://docs.docker.com/docker-for-mac/#/uninstall-or-reset) doesn't exist.

**Comment by Tuxity** [comment] 2016-09-09 14:54
Seems to work better for me with the beta.
@adammcnamara personally I've uninstalled everything with CleanMyMac app

**Comment by dsheets** [comment] 2016-09-09 16:01
Uninstall from the Docker preferences or running the command-line uninstallation are the best uninstallation methods (if they work). @adammcnamara what was the failure during the Preferences "Uninstall"? Were you already on Sierra when you tried to run that?

**Comment by adammcnamara** [comment] 2016-09-09 16:56
@dsheets Yes, already running on Sierra. Error is this one another user reported: https://github.com/docker/for-mac/issues/488#issuecomment-244136882

**Comment by dsheets** [comment] 2016-09-12 09:32
@adammcnamara yes, unfortunately that error has the same root cause as #202 which was only just fixed in Beta 25.

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
