### ISSUE TITLE
Docker Desktop version 4.19 broke /var/run/docker.sock.raw to resolve docker.sock permission denied

### ISSUE THREAD

**Issue by jeffrozica** [docker/for-mac#6826] opened 2023-05-02 13:26 UTC
Docker desktop version 4.19.0 broke my -v /var/run/docker.sock.raw /var/run/docker.sock.  About 2 years ago, this solved my docker socket permission denied error (See belwo)....  It was working fine up through version 4.18, but after the v4.19 upgrade, it broke again.  Getting this error again.  Had to revert back to version 4.18. Same issue on Windows and Mac versions.

 ```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

Again, no issues until I went to docker desktop version 4.19 and its the same issue on MAC and WINDOWS. The docker.sock.raw was the only viable option for me to fix this.

Mac Version: Ventura 13.3
Windows Version: Windows 11

**Comment by sam-thibault** [comment] 2023-05-04 14:20
This looks like a duplicate of:
- #6823

**Comment by sam-thibault** [comment] 2023-05-04 14:21
Will close in favor of the linked issue above.

**Closed by sam-thibault** 2023-05-04 14:21 UTC
Labels: kind/bug, duplicate, version/4.19.0
