### ISSUE TITLE
Docker crashing on startup on mac

### ISSUE THREAD

**Issue by jonathanrz** [docker/for-mac#2463] opened 2018-01-18 19:36 UTC
### Expected behavior
That docker inits OK

### Actual behavior
Crash screen when docker inits

### Information

Diagnostic ID: 2019378E-67B6-4D17-B6BE-ACDD0F637893
MacOS: 10.13.2
The app crashes when trying to init with the SO or when opening after this.
I just installed the app, it crashed since the first time

**Comment by akimd** [comment] 2018-01-19 09:04
Probably duplicate of #2383.

**Closed by akimd** 2018-01-19 09:04 UTC
