### ISSUE TITLE
crash after set registry mirrors and restart

### ISSUE THREAD

**Issue by xujihui1985** [docker/for-mac#2520] opened 2018-01-27 01:43 UTC
### Expected behavior
apply and restart successfully

### Actual behavior
crash

### Information

mac: 10.13.3
dockerformac: 17.12.0-ce-mac49 

the daemon could be restart successfully if registry mirror leave blank. the registry mirror should be fine because it has been working fine for couple of months with pervious version of dockerformac
I also check the syslog

`allow_other,max_read=1048576,subtype=osxfs /Volumes
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Users
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: Negotiated transfuse notification channel for /tmp
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: Negotiated transfuse notification channel for /private
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: Negotiated transfuse notification channel for /Volumes
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: Negotiated transfuse notification channel for /Users
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: sending continue to client
Jan 27 09:24:07 seandeMacBook-Pro Docker[3287]: Fatal unexpected exception: Socket.Closed
Jan 27 09:24:14 seandeMacBook-Pro Docker[3312]: Logging to Apple System Log
Jan 27 09:26:24 seandeMacBook-Pro com.apple.xpc.launchd[1] (com.docker.vmnetd): Unknown key for string: Version
`
the cause should be `Fatal unexpected exception: Socket.Closed`

**Comment by Genert** [comment] 2018-02-05 13:13
Same behaviour here.

Mac: 10.12.6
Dockerformac: 17.12.0-ce-mac49

**Comment by pgayvallet** [comment] 2018-02-06 16:49
Duplicate of https://github.com/docker/for-mac/issues/2537

**Comment by guillaumerose** [comment] 2018-03-12 12:24
https://github.com/docker/for-mac/issues/2537 is now fixed

**Closed by guillaumerose** 2018-03-12 12:24 UTC
Labels: area/gui, kind/bug, status/1-acknowledged
