### ISSUE TITLE
abnormal startup

### ISSUE THREAD

**Issue by tlerbao** [docker/for-mac#6207] opened 2022-02-28 01:55 UTC
### Information
  - macOS Version:12.2 (21D49)
  - Intel chip or Apple chip:Intel
  - Docker Desktop Version:4.5.0 (74594)
 
  - [x] I have tried with the latest version of Docker Desktop

### Expected behavior

It starts in full background and the menu is complete.

### Actual behavior

Incomplete menu, as shown

<img width="305" alt="image" src="https://user-images.githubusercontent.com/20442232/155911513-44087af9-60a0-4b60-8c6c-30e66680b7b5.png">

Also clicking on the icon doesn't do anything

<img width="328" alt="image" src="https://user-images.githubusercontent.com/20442232/155911570-ba59da53-2e14-42d8-ae2b-214f055d5b6a.png">

It works fine after exiting with command+Q and restarting

**Comment by StefanScherer** [comment] 2022-02-28 13:32
Thanks for the report. It looks like a duplicate of #6206 where we keep track of this issue. I'm closing this ticket now, please follow the other ticket for an update when we know more.

**Closed by StefanScherer** 2022-02-28 13:32 UTC
