### ISSUE TITLE
Wrong CPU architecture in /proc/cpuinfo when using --platform

### ISSUE THREAD

**Issue by wader** [docker/for-mac#5245] opened 2021-01-13 15:23 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D3CC2969-09ED-4A43-A421-17E82049B52F/20210113151536

### Expected behavior

That `/proc/cpuinfo` indicated the emulated CPU.

### Actual behavior

`/proc/cpuinfo` shows intel CPU.

```sh

### Information

macOS version: 10.15.7

Docker for Mac: 3.0.4

$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

### Steps to reproduce the behavior

```sh
$ docker run --rm -ti --platform linux/arm64 alpine:3.12
/ # uname -a
Linux 25e3218c592e 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 aarch64 Linux
/ # cat /proc/cpuinfo | grep model
model		: 142
model name	: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
model		: 142
model name	: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
model		: 142
model name	: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
model		: 142
model name	: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
/ #
```

I first reported the issue here https://github.com/containerd/containerd/issues/4109 but then got unsure it's the correct place.

**Comment by wader** [comment] 2021-01-14 18:25
I noticed this issue while trying to build various software packages locally using docker mac and in github action using qemu. Mainly the problem happens with configure script, cmake script etc that read `/proc/cpuinfo` and builds that ends up using  `gcc -mcpu=native` etc which seems to auto detect cpu using cpuinfo (https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/gcc/config/arm/driver-arm.c). `-mcpu=native` seems to fallback to a default arm config and that can sometimes cause errors like `Error: selected processor does not support `usad8 ip,r4,r5' in ARM mode`

**Comment by StefanScherer** [comment] 2021-01-15 18:07
Thanks for reporting, but this is not a bug. This also happens on Linux hosts with Intel CPU:

```
$ docker run --rm --privileged hypriot/qemu-register
$ docker run --rm -ti --platform linux/arm64 alpine:3.12
/ # uname -a
Linux 64ccc03e91e3 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 aarch64 Linux
/ # cat /proc/cpuinfo | grep model
model		: 158
model name	: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
```

This is becaus it still runs with the Linux kernel on Intel, only with QEMU to emulate the arm64 binaries. And therefore it still shows the cpuinfo from the host. Container are  more or less only namespaces and no full encapsulated emulators across different CPU architectures.

Running containers with a different architecture might  run into issues when the application checks for such information and then mis-interprets that it's running eg. ARM binaries. But that's part of the business logic in the application and we can't do anything about this.

I'll close this ticket,  but feel free to comment if you have questions.

**Closed by StefanScherer** 2021-01-15 18:07 UTC
Labels: version/3.0.4

**Comment by wader** [comment] 2021-01-15 18:12
@StefanScherer Ok! thanks for the answer. Would it be possible for docker to somehow have synthetic proc files to workaround this?

**Comment by StefanScherer** [comment] 2021-01-15 18:34
@wader No, we're not keen on messing around with these proc files. :-)

**Comment by wader** [comment] 2021-01-15 19:33
@StefanScherer true :) i was thinking just cpuinfo and maybe some others that are known to be ”wrong”? maybe its not easy to overlay just some files in proc also?
