### ISSUE TITLE
Adding insecure register on Docker for Mac CE causes fatal error

### ISSUE THREAD

**Issue by egilchri** [docker/for-mac#2595] opened 2018-02-12 17:17 UTC
### Expected behavior
That it be added to the registry
### Actual behavior
A window pops saying Fatal Error and asks if I want to go back to factory defaults
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Launch Docker for Mac
  2. Click on Preferences
 3. Add an insecure registry
4. Docker says it's restarting, and then "poof", the fatal error message comes up
<img width="599" alt="screen shot 2018-02-12 at 11 56 12 am" src="https://user-images.githubusercontent.com/37439/36109890-b819d26e-0fee-11e8-8fc9-3e58fb3a2651.png">

**Comment by egilchri** [comment] 2018-02-12 18:26
Didn't mention, my hardware it 
<img width="314" alt="screen shot 2018-02-12 at 1 26 05 pm" src="https://user-images.githubusercontent.com/37439/36112649-5c364766-0ff8-11e8-8418-3f4c1f2ba512.png">

**Comment by egilchri** [comment] 2018-02-12 18:28
Docker is Docker CE 17.12.0

**Comment by egilchri** [comment] 2018-02-12 18:56
Docker is Docker CE 17.12.0

**Comment by pgayvallet** [comment] 2018-02-13 09:30
Duplicate of https://github.com/docker/for-mac/issues/2478

Will be fixed on next edge & stable. See #2478 for workaround

**Closed by pgayvallet** 2018-02-13 09:30 UTC
