### ISSUE TITLE
2.4.0.0 com.docker.hyperkit very high CPU with low load in containers

### ISSUE THREAD

**Issue by zwass** [docker/for-mac#4981] opened 2020-10-08 16:18 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `FBD1077A-2DEC-4C37-A7E5-7E917A732473/20201008014709`

### Expected behavior

Docker CPU usage is low when container usage is low.

### Actual behavior

Containers are using very little CPU (~5% between all containers as reported by `docker stats`). `com.docker.hyperkit` is using 300% CPU (as reported by Activity Monitor).

![Screen Shot 2020-10-07 at 6 46 59 PM](https://user-images.githubusercontent.com/575602/95485388-7d54c400-0946-11eb-8429-729c43ccae6e.png)

### Information

  - macOS Version: 10.14.6

I think this problem started with Docker 2.4.0.0.

### Diagnostic logs

I don't see this option in the menu. Are you looking for the diagnostics ID asked for above? `FBD1077A-2DEC-4C37-A7E5-7E917A732473/20201008014709`

```
Docker for Mac: 2.4.0.0

```

### Steps to reproduce the behavior

I am running this docker-compose file: https://github.com/kolide/fleet/blob/master/docker-compose.yml

It does not reproduce immediately, but I have seen the issue come up at least 3 or 4 times in the last week.

**Comment by stephen-turner** [comment] 2020-10-08 16:29
Thanks, @zwass, we'll have a look

**Comment by zwass** [comment] 2020-10-08 21:58
I reverted to 2.3.0.5 and have not seen the issue crop up after a few hours of running that compose stack. It was usually happening regularly and quickly with 2.4.0.0 so I suspect there are new changes that introduced the issue.

I will update with further observations.

**Comment by ant-** [comment] 2020-10-09 08:29
It is a [well-known](https://github.com/docker/for-mac/issues/3539#issuecomment-666258889) problem.

**Comment by stephen-turner** [comment] 2020-10-09 09:31
Actually, this one is new. We have now reproduced it and will have a fix soon.

**Comment by zwass** [comment] 2020-10-09 16:18
Glad to hear it and thank you @stephen-turner.

**Comment by djs55** [comment] 2020-10-14 09:32
@zwass, thanks for your report! I notice there's a container which bind-mounts `/`:
```
    {
      "ContainerID": "8ac93e23ff4df2a03be6b3c83a88ba9487de626ec93b339023f17ea7d20d2d8f",
      "Volumes": [
        {
          "HostPath": "/",
          "MountPath": "/rootfs"
        }
    },
```
Using the old file-sharing implementation ("osxfs") this was slightly buggy:

- I can run `docker run -v /:/rootfs alpine sh` even though `/` is not listed in the UI (whale menu -> Preferences -> Resources -> File Sharing).
- it does not watch the host filesystem to inject inotify file events. This may or may not be a problem, depending on the use-case.

Due to the inotify file events bug, the CPU usage is quite low.

Using the new file-sharing implementation ("gRPC FUSE"):

- Again I can run `docker run -v /:/rootfs alpine sh` even though `/` is not listed in the UI.
- It *does* watch the host filesystem to inject inotify events (and more importantly cache invalidation messages)

Unfortunately due to fixing the inotify file events bug, the CPU usage is now very high.

I'm not sure yet what the best way to fix this is. Could you describe your use-case in more detail? What is the `/rootfs` bind-mount used for? Could it be decomposed into smaller bind-mounts like `/var/lib`, `/var/run` etc?

**Comment by zwass** [comment] 2020-10-14 15:21
@djs55 that rootfs mount is just copied out of the [CAdvisor documentation](https://github.com/google/cadvisor#quick-start-running-cadvisor-in-a-docker-container) into the above linked docker-compose file. 

Presumably this issue is effecting anyone who is running CAdvisor (11.3k stars) with the documented instructions.

**Comment by djs55** [comment] 2020-10-14 15:44
@zwass thanks for the explanation, very helpful!

**Comment by simonferquel** [comment] 2020-10-19 08:57
The issue has been fixed in Edge release 2.4.2.0, thank you for reporting it.

**Comment by zwass** [comment] 2020-10-19 16:18
Thank you! Does that mean it should make the next stable release?

**Comment by stephen-turner** [comment] 2020-10-19 16:24
Yes, @zwass.

**Comment by ebriney** [comment] 2020-10-23 12:55
Hi @zwass. We fixed more issues related to gRPC Fuse, can you try that build and give us some feedback please:
https://desktop-stage.docker.com/mac/edge/49130/Docker.dmg

We noticed a performance issue when creating files from a container and we start to work on optimize it.
Thanks for your help.

**Comment by Nuru** [comment] 2020-10-24 21:42
I had a bunch of containers idling and CPU usage was low. Then while doing something in the Opera browser on the host Mac, `com.docker.hyperkit` usage went up to 300% or so for quite a while. I killed a container and that did not stop it. I started to collect diagnostics, which took over a minute, and by the end of the diagnostics collection, hyperkit usage was back down to normal (5-10% CPU).

So, not sure if the diagnostics caught the problem, and not sure if this is the same problem as the OP, but seems close enough to add to this issue rather than open a new one. 

Uploaded Diagnostics ID: `7DDDF979-417F-442C-B930-719FC131249A/20201024212048`

**Comment by Nuru** [comment] 2020-10-29 10:52
Here is another Diagnostic showing `com.docker.hyperkit` using 300% CPU while containers are basically idle, but this time the high usage continued past the end of the diagnostic collection. Usually hyperkit settles down before the end of the collection. Diagnostic ID `7DDDF979-417F-442C-B930-719FC131249A/20201029104525`

**Comment by stephen-turner** [comment] 2020-11-02 18:12
The original bug is fixed in 2.5.0.0. If you have another CPU issue that can't be explained by the CPU load inside the containers, please open a new ticket. Thanks.

**Closed by stephen-turner** 2020-11-02 18:12 UTC
Labels: version/2.4.0.0

**Comment by gauravphoenix** [comment] 2020-11-21 02:47
diag id- `C64F5E31-4180-4AA4-AD76-3DC13EA0CEC6/20201121024501`

**Comment by exoer** [comment] 2020-11-25 16:00
For osx set the `cached` option on bind mounts as there is some filesystem issues. 

```
    volumes:
      - ./api/:/opt/app:cached
      - /opt/app/node_modules
```

**Comment by krebbi** [comment] 2020-12-01 13:29
I disabled Turbo Boost and got the temperature down to 65°C

Not a fix but a way to protect the hardware.

**Comment by vedmant** [comment] 2020-12-18 10:16
I have the same issue, laptop battery is dying in just few hours (normally it lasts 6 hours, on macbook).
