### ISSUE TITLE
Docker Desktop for mac window does not close when CMD+w pressed 

### ISSUE THREAD

**Issue by alexcom** [docker/for-mac#6198] opened 2022-02-23 11:11 UTC
When I press CMD+w combination I expect window to close and remain in memory. Examples: Finder, Slack.

  - [x] I have tried with the latest version of Docker Desktop

### Expected behavior
Window is closed, program keeps running.
### Actual behavior
Nothing happens.

**Comment by laurazard** [comment] 2022-02-28 14:14
Thanks for reporting @alexcom, I've created an internal ticket to track this.

**Comment by timfallmk** [comment] 2022-03-01 21:24
Dupe of #6167

**Closed** 2022-03-02 09:44 UTC
