### ISSUE TITLE
Docker for Mac on Mojave takes too much memory.

### ISSUE THREAD

**Issue by cheburakshu** [docker/for-mac#3304] opened 2018-10-31 18:32 UTC
Prior to my update to Mojave, the Docker used to take around 2.2 - 2.3 GB with the same settings. But, after the update, it consumes much more (3.1+ GB). This is consistent between restarts of Mac and Docker. Is it a problem with Mojave or Docker? This Let me know if you need more information. Are there any other pointers to conserve memory?

### Diagnostics ID : F228A17F-3486-49EC-92A4-2C824BF1BF62/20181031183338

![image](https://user-images.githubusercontent.com/27330002/47810155-3399e280-dd08-11e8-9e34-bf8c89abac44.png)

![image](https://user-images.githubusercontent.com/27330002/47810207-59bf8280-dd08-11e8-8e7a-af407e6341c2.png)

![image](https://user-images.githubusercontent.com/27330002/47810247-722f9d00-dd08-11e8-9b80-29f21520a0ae.png)

**Comment by EduardRakov** [comment] 2018-11-01 13:33
probably the same issue that is discussed here https://github.com/docker/for-mac/issues/3232

**Comment by cheburakshu** [comment] 2018-11-01 15:15
The only difference was it behaved well with the same docker version before my Mojave upgrade.

**Comment by octavioamu** [comment] 2018-11-01 22:41
Same problem since I update to mojave docker is consuming 3.9gb of memory , CPU and also all the energy just a few hours of  battery  with docker running

**Comment by mschipperheyn** [comment] 2018-11-13 11:09
Yeah, battery life is disastrous. Already was previous to Mojave though.

**Comment by eddiemonge** [comment] 2018-11-15 20:45
Duplicate of #178

**Comment by cheburakshu** [comment] 2018-11-15 20:53
Duplicate? Really? #178 is closed and this issue persists! Someone needs to take a closer look, than saying -- "Memory leak.. Oh yeah.. Duplicate of a closed ticket"

**Comment by cheburakshu** [comment] 2018-11-15 20:58
Tip: Reduce the swap from 1 GB to 512 MB. Increase the memory by the same amount (512 MB). Your life will be better. You will see at least 1 GB drop of memory consumption by Docker. 

I checked docker documentation, swap is a penalty of overusing the allocated memory. Should not bother if your app behaves well. This worked well for me as a workaround.

**Comment by eddiemonge** [comment] 2018-11-15 20:59
Why are you getting all mad at me? I don't work for Docker or have any affiliation. I'm merely trying to cut down on the number of issues in the hope that it will get them to spend less time triaging and more time fixing bugs. 178 should never have been closed. Want an open one? This also duplicates #3232 .

**Comment by robotdan** [comment] 2018-11-28 20:09
As mentioned in issue #178 this may be a hyperkit issue? 
https://github.com/moby/hyperkit/issues/231

**Comment by stephen-turner** [comment] 2019-01-24 17:35
Let's move the discussion to #3232.

**Closed by stephen-turner** 2019-01-24 17:35 UTC
Labels: version/18.06.1-ce-mac74
