### ISSUE TITLE
Upgrade to Version 17.12.0-ce-rc2-mac41 (21193) broke Docker install

### ISSUE THREAD

**Issue by BrendonW** [docker/for-mac#2323] opened 2017-12-14 14:10 UTC
### Expected behavior
Upgrade to restart

### Actual behavior
Upgrade left Docker broken. I was able to reset and then restart, but in the process lost all my images, Swarms, etc.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
D0FB2E91-63DA-400F-84FB-DA01B1F52C6F

**NOTE:-**
I think that it would be helpful if I had options other than Exit or Reset EVERYTHING -- I was not expecting it to blow away all my images. 

I'll have to see if I can recover them in some way because recreating everything from scratch will take a lot of time. But I'm not sure where to start looking or how to hook them back into Docker so that I can get back to where I was before the upgrade attempt...

### Steps to reproduce the behavior

  1. Select Upgrade and restart.

**Comment by jeantil** [comment] 2017-12-14 14:34
see discussion in https://github.com/docker/for-mac/issues/2317 as it may help with your issue.

**Comment by gtardif** [comment] 2017-12-15 16:02
Closing as duplicate of #2317

**Closed by gtardif** 2017-12-15 16:02 UTC
