### ISSUE TITLE
Communication with networking components failed

### ISSUE THREAD

**Issue by Mottoweb** [docker/for-mac#478] opened 2016-08-31 09:31 UTC
### Expected behavior

Docker starts

### Actual behavior

Docker communication with networking components failed

### Information

I was running Toolbox before some time, then switched to docker for mac beta and could not work with that, docker was using high cpu https://forums.docker.com/t/com-docker-hyperkit-up-cpu-to-340/13057 , i am trying to test it again but no luck now.
Help appreciated.

Diagnostic ID: 338A5456-0A0C-475E-B5DB-30E79655EE25
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/fedorbuturlin/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/fedorbuturlin/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Install docker-toolbox
2. Remove docker-toolbox
3. Install docker for mac

diagnostic: 338A5456-0A0C-475E-B5DB-30E79655EE25

**Comment by Mottoweb** [comment] 2016-08-31 10:29
Fixed with the help of #8

**Comment by dave-tucker** [comment] 2016-09-01 14:05
Thanks @Mottoweb closing as a dupe of #8

**Closed by dave-tucker** 2016-09-01 14:05 UTC
Labels: area/network, area/startup, osx/10.11.x, version/1.12.0
