### ISSUE TITLE
Fatal error while trying to build a new image on MacOS 10.12 Beta

### ISSUE THREAD

**Issue by richcfml** [docker/for-mac#308] opened 2016-08-16 17:53 UTC
### Steps to reproduce

1. Start Docker for Mac
2. run docker build -t image_name .
3. while pulling the from image the error appears

### Expected behavior

There should not be a fatal error 

### Actual behavior

While building the new image Docker for Mac showed me a fatal error and exit

### Information

```
Diagnostic ID: 4F934153-4AFF-4D8C-8D41-B07451ED2346
**Docker for Mac: 1.12.0-beta22 (Build 11222)**
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment] 2016-08-17 09:14
This is likely caused by the ongoing issues with golang and macOS Sierra Beta. This is a duplicate of #64.

**Closed by dsheets** 2016-08-17 09:14 UTC

**Comment by djs55** [comment] 2016-09-15 16:19
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
