### ISSUE TITLE
Docker for OSX will kernal panic my (Big Sur) Mac book pro when waking from sleep.

### ISSUE THREAD

**Issue by alphex** [docker/for-mac#5715] opened 2021-05-24 22:06 UTC
- [ x ] I have tried with the latest version of Docker Desktop. (I update docker when ever it suggests to)
  - [ x ] I have tried disabling enabled experimental features. (never enabled)
  - [  ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

If my laptop were to go to sleep, when I wake it, it won't report a kernel panic and have completely restarted.

### Actual behavior

Almost consistently, if I let my laptop sleep with Docker running, waking it from that sleep, will result in a kernel panic and a restart of the whole system.

### Information

  - macOS Version: Big Sur 11.3.1 (20E241)
  - Intel chip or Apple chip: Intel i9 8 core 2.4ghz
  - Docker Desktop Version: 3.3.3 (64133)

### Steps to reproduce the behavior

  1.  start the computer, start docker, do work...  walk away from it to get coffee, feed the pets, ponder life and the meaning of it all?   
  2. Return to computer, with enough time having past for the computer to go to full sleep.   Attempt to wake it.

Here is a very common crash dump from the OS

```
panic(cpu 0 caller 0xfffffff020157448): x86 CPU CATERR detected
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 18P4556
macOS version: 20E241
Kernel version: Darwin Kernel Version 20.4.0: Thu Mar  4 23:34:36 PST 2021; root:xnu-7195.101.1~1/RELEASE_ARM64_T8010
Kernel UUID: 3FA744A7-0F34-36DA-AA6D-F6503A3176ED
iBoot version: iBoot-6723.101.4
secure boot?: YES
x86 EFI Boot State: 0x16
x86 System State: 0x0
x86 Power State: 0x0
x86 Shutdown Cause: 0xec
x86 Previous Power Transitions: 0x40001000100
PCIeUp link state: 0x89473611
Paniclog version: 13
Kernel slide:      0x000000001820c000
Kernel text base:  0xfffffff01f210000
mach_absolute_time: 0x1a00d3e7728
Epoch Time:        sec       usec
  Boot    : 0x60aaf39b 0x00024c40
  Sleep   : 0x60ab4052 0x0005aadc
  Wake    : 0x60ab4856 0x000e04c9
  Calendar: 0x60ac1e7a 0x000bd641

Panicked task 0xffffffe199de0630: 3352 pages, 226 threads: pid 0: kernel_task
Panicked thread: 0xffffffe199fdf200, backtrace: 0xffffffe804343700, tid: 406
		  lr: 0xfffffff01f95342c  fp: 0xffffffe804343750
		  lr: 0xfffffff01f953284  fp: 0xffffffe8043437c0
		  lr: 0xfffffff01fa7e938  fp: 0xffffffe804343890
		  lr: 0xfffffff01ff755fc  fp: 0xffffffe8043438a0
		  lr: 0xfffffff01f952fb8  fp: 0xffffffe804343c20
		  lr: 0xfffffff01f952fb8  fp: 0xffffffe804343c80
		  lr: 0xfffffff020973200  fp: 0xffffffe804343ca0
		  lr: 0xfffffff020157448  fp: 0xffffffe804343cd0
		  lr: 0xfffffff0201457d8  fp: 0xffffffe804343d30
		  lr: 0xfffffff0201476d4  fp: 0xffffffe804343dc0
		  lr: 0xfffffff020144e7c  fp: 0xffffffe804343e50
		  lr: 0xfffffff02004a4c4  fp: 0xffffffe804343e80
		  lr: 0xfffffff01fecc90c  fp: 0xffffffe804343ec0
		  lr: 0xfffffff01fecc18c  fp: 0xffffffe804343f00
		  lr: 0xfffffff01ff805a0  fp: 0x0000000000000000


```

**Comment by stephen-turner** [comment] 2021-05-25 10:30
Are you using the new virtualization framework in the experimental settings? We know that is subject to crashes.

**Comment by alphex** [comment] 2021-05-25 13:26
@stephen-turner  Thank you for replying.
No. I don't have any experimental settings enabled.

https://i.alphex.io/bLukz7pe -- screen shot of the unchecked experimental features box.

Let me know if you need any more info.

**Comment by stephen-turner** [comment] 2021-05-25 14:57
Hmm, I'm not sure what else to suggest, we haven't had any other reports of this.

**Comment by alphex** [comment] 2021-05-25 15:02
@stephen-turner maybe turning ON the new virtualization framework :) 

I also just updated to OSX 11.4 which released last night -   thank you for the responses, I'll leave this ticket up for a few days see if anyone else notices it.

**Comment by stephen-turner** [comment] 2021-05-25 15:13
Ah, I wonder if there's something in 11.4, we'll definitely keep an eye on that.

**Comment by alphex** [comment] 2021-05-25 15:26
@stephen-turner 
as of yesterday I was at : 

`macOS Version: Big Sur 11.3.1 (20E241)`

Today as I write this, I am at `11.4 (20F71)`

I'm crossing my fingers that something got fixed updating OSX.

**Comment by jkevincrowell** [comment] 2021-06-08 06:24
I had a similar problem.  It was fixed by sharing only the files/directories you need to use.

[https://github.com/docker/for-mac/issues/5698#issuecomment-843086757](url)

For me, it worked.  Before, the computer was quite slow, but after that it was much faster.

**Comment by djs55** [comment] 2021-06-10 15:59
@alphex since this is a host kernel (`Darwin Kernel Version 20.4.0`) crash rather than a Linux VM kernel crash, it indicates either a bug in macOS or perhaps a problem with your hardware. Docker Desktop is not capable of crashing the machine by itself. I recommend

- using the Apple hardware test: https://support.apple.com/en-us/HT202731 to look for hardware issues
- check you don't have any third-party kernel extensions loaded using `kextstat | grep -v com.apple`. If there are some extensions listed then one of these might be responsible for the crash. Perhaps unload the extensions and see if the bug reproduces without them.

**Comment by groksrc** [comment] 2021-06-23 23:04
Same issue for me. It took me a while to track down, but I am running the same versions and have the same issue.

**Comment by yaronyagoda** [comment] 2021-07-26 06:05
We (3 users in my company) are experiencing the same issue:
Mac Catalina - 10.15.7
Docker - 3.3.1

**Comment by dmitry-semenov** [comment] 2021-07-31 15:34
I was able to repro on 2 different MacBook Pro laptops; both were running `citusdata/citus:7.5.1` (not sure if a specific image can have an impact on the host machine)
Big Sur 11.4 (20F71)
Docker 3.5.2

**Comment by djs55** [comment] 2021-08-04 13:29
A macOS kernel panic means either a bug in macOS or a fault in the hardware. In both cases this should be reported to Apple. Please report to Apple via their Feedback assistant program.

I'll close this issue because unfortunately there is nothing Docker can do to fix bugs in macOS or the hardware.

**Closed by djs55** 2021-08-04 13:29 UTC
Labels: version/3.3.3

**Comment by isaacatmann** [comment] 2021-08-23 21:18
@jkevincrowell What was the fix you found?  The link provided isn't valid.

For what it's worth we're seeing a very high concentration of Wake from Sleep Kernel Panics only with users who are actively running Docker desktop for Mac.  This has been occurring across multiple unique environments and can cause up to 5 Kernel Panics a day depending on how often the machines are set to sleep. Removing Docker seems to resolve.
