### ISSUE TITLE
Applications launched from Spotlight may not get enough info in PATH and be unable to use Docker CLI

### ISSUE THREAD

**Issue by bwateratmsft** [docker/for-mac#4875] opened 2020-09-04 15:08 UTC
I haven't been able to reproduce this issue myself. Opening this due to https://github.com/microsoft/vscode-docker/issues/2254, which has a lot more information--please check it out.

Possible repro steps:
1. Using Spotlight (<kbd>Cmd</kbd> + <kbd>Space</kbd>), launch e.g. VSCode
1. Install the Docker extension for VSCode
1. Open the explorer view

Expected:
Everything works

Actual:
Errors occur, e.g. "Error: /bin/sh: docker: command not found"

The user found that `/usr/local/bin` was not on the `PATH` when VSCode is launched from Spotlight. There is an [ancient bug](https://web.archive.org/web/20100212232552/https://www.digitaledgesw.com/node/31) in OS X that apparently has never been addressed that causes this issue.

Is there anything the Docker Desktop for Mac installer can do to mitigate this problem?

**Comment by stephen-turner** [comment] 2020-09-08 09:10
Thanks, @bwateratmsft. We'll look at it.

**Comment by ebriney** [comment] 2020-09-11 10:03
Hi @bwateratmsft, unfortunately I couldn't reproduce it, following this ticket instruction, nor upstream issues ones.
We can't really do something clean, from what I understand shell command executed in the plugin lack of `/usr/local/bin` in their `PATH` env.
The only thing we could do is creating the symlinks in `/bin` but that's an ugly fix and we never have any complains about issue such this.

**Comment by bwateratmsft** [comment] 2020-09-11 12:37
I agree, that is sort of a weird solution. We've had just two users that have reported hitting it; several of us have tried and been unable to reproduce. Perhaps the right path forward is for them to submit feedback to Apple.

**Comment by stephen-turner** [comment] 2020-09-14 08:34
Agreed, so I'm going to close this ticket.

**Closed by stephen-turner** 2020-09-14 08:34 UTC
