### ISSUE TITLE
docker-compose hangs forever when connected to the internet

### ISSUE THREAD

**Issue by ekiwok** [docker/for-mac#1435] opened 2017-03-16 09:26 UTC
### Expected behavior

docker-compose works when there is internet connection

### Actual behavior

docker-compose hangs when there is internet connection

### Information

Following https://docs.docker.com/docker-for-mac/troubleshoot/#recreate-or-update-your-containers-after-beta-18-upgrade I've added 127.0.0.1 localunixsocket.local to /etc/hosts but it does not solve the problem

 Docker for Mac: version: 17.03.0-ce-mac2 (32de84251)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/D661DB52-4CDA-4A4C-88AE-00AD5D6D8682/20170316-102120.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install Docker for Mac (for me it occurs in beta and stable)
  2. $ docker-compose
  3. It hangs when there is active internet connection. If wifi is disabled it works.

**Comment by ekiwok** [comment] 2017-03-16 10:16
Following this advice https://github.com/docker/compose/issues/3419#issuecomment-221793401 I run tcpdump and noticed that docker-compose looks up for prod.python.map.fastly.net so I added 127.0.0.1 prod.python.map.fastly.net to my /etc/hosts and immediately docker-compose started to work like a charm...

Anyway I guess it's still a bug because docker-compose should not hang if dns lookup fails?

Right now I dunno is it Docker for Mac or docker-compose issue. Please close if you think it does not belong here.

**Comment by djs55** [comment] 2017-03-21 16:46
@ekiwok I'm glad that workaround works for you. I think the nature of the workaround is good evidence that this is a `docker-compose` issue rather than a Docker for Mac one. Therefore I'll close this issue as a duplicate of https://github.com/docker/compose/issues/3419

Thanks for your report and for using Docker for Mac!

**Closed by djs55** 2017-03-21 16:46 UTC
Labels: osx/10.12.x, status/0-triage, version/17.03.0-ce-mac2

**Comment by mobileka** [comment] 2017-04-10 20:51
@djs55 I have a similar issue but the above workaround doesn't work for me (nothing in tcpdump). Moreover, every single docker related command has a 30 second or so latency before it starts doing its job. Even `docker --version` takes more than 30 seconds to output the result.

There're two workarounds in my case:

1. Disable wifi / internet
2. Run all docker-related commands with `sudo`

I tired latest stable and beta releases and got similar results.
My current docker version is 17.03.1-ce-rc1, build 3476dbf.

Should I create a separate issue for this?

**Comment by djs55** [comment] 2017-04-20 15:09
@mobileka sorry for the delay getting back to you. Please do create a separate issue with fresh diagnostics (if you haven't already!)
