### ISSUE TITLE
Fatal Error with Docker Container Using Rosetta on Apple Silicon

### ISSUE THREAD

**Issue by NicoHarms** [docker/for-mac#7320] opened 2024-06-10 15:24 UTC
### Description

Hi, I encountered a fatal error when running a Docker container with Rosetta enabled for x86_64/amd64 emulation on Apple Silicon.

### Reproduce

1. Ensure Rosetta is enabled for x86_64/amd64 emulation on Apple Silicon in Docker Desktop settings.
2. Run the following Docker command:
```bash
docker run -it --rm --platform linux/amd64 docker.osgeo.org/geoserver:2.25.1
```
3. Observe the fatal error produced by the Java Runtime Environment
4. When restarting the container, you might get a NullPointerException during application deployment, or a dump.

### Expected behavior

The container should run without errors under Rosetta emulation.

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/nharms/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/nharms/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/nharms/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/nharms/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/nharms/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/nharms/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/nharms/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nharms/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/nharms/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: f7a6ef72-e685-4605-8a7c-1b1e7195cb0d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/nharms/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.4.0.0/16, Size: 24

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

3C2F3CF6-9B06-40AC-8DFC-096D74496BCB/20240610151958

### Additional Info

**Environment**:

- MacOS Version: 14.5
- RAM: 32GB
- Processor: M1 Pro

**Additional Information**:

- Disabling Rosetta for x86_64/amd64 emulation and running the same container works without any issues.

**Logs**:
[dump.txt](https://github.com/user-attachments/files/15775555/dump.txt)
[fatal.txt](https://github.com/user-attachments/files/15775556/fatal.txt)
[nullpointer.txt](https://github.com/user-attachments/files/15775557/nullpointer.txt)

**Comment by MihaelaStoica** [comment] 2024-06-11 12:18
This seems to be a duplicate of https://github.com/docker/for-mac/issues/7286 and https://github.com/docker/for-mac/issues/7006

**Closed** 2024-06-11 13:08 UTC
Labels: status/triage, area/emulation, version/4.31.0
