### ISSUE TITLE
[3.3.0] Very specific set of circumstances leads to zero-byte (empty) file being created

### ISSUE THREAD

**Issue by epoberezhny** [docker/for-mac#5570] opened 2021-04-13 16:48 UTC
### Information

  - macOS Version: 11.2.3

I'm experiencing this issue https://github.com/docker/for-linux/issues/1015 after updating Docker for Mac to 3.3.0.

### Steps to reproduce the behavior

The issue above contains a good reproducible case

**Comment by as0bu** [comment] 2021-04-13 22:58
I'm also experiencing this on macOS Version 10.15.7 with Docker for Mac 3.3.0.

In my case there is a ruby script that copies data from a cached bind mount to /tmp (overlay2), manipulates the data, and copies it back to the same cached bind mount in a different directory. The files get created but have no content.

After the script runs if I do the same `cp -r` command as the script the content then gets populated.

**Comment by as0bu** [comment] 2021-04-14 15:41
I just wanted to provide the data point that I uninstalled Docker for Mac 3.3.0 and downgraded to 3.2.1 and I no longer have the problem.

**Comment by reshleman** [comment] 2021-04-21 21:20
Also encountering this on macOS 11.2.3 using Docker for Mac 3.3.0.

(FWIW in case others are searching, this manifests in my Rails test suite as unexplained `ActiveStorage::IntegrityError`s.)

**Comment by amanfredi** [comment] 2021-04-21 21:40
Experiencing the same issue - confirmed in Docker for Mac 3.3.0 and 3.3.1

I wonder if it could be related to the umask changes discussed here: https://github.com/docker/for-mac/issues/5527

**Comment by ralph** [comment] 2021-04-22 08:02
For everyone coming here because their Ruby/Rails uploader specs using `Rack::Test::UploadedFile` are breaking, this is what worked for me:

Instead of doing this:

```ruby
Rack::Test::UploadedFile.new(Rails.root.join('spec/files/test.jpg'), 'image/jpeg')
```

I did this ugly patch to work around the circumstances leading to the error:

```ruby
file = File.open(Rails.root.join('spec/files/test.jpg'))
Rack::Test::UploadedFile.new(file, 'image/jpeg', true, original_filename: 'test.jpg')
```

**Comment by amanfredi** [comment] 2021-04-23 22:28
I attempted to dig a bit deeper into this issue using `strace` and this ruby code:

```
require 'fileutils'
require 'tempfile'
tempfile_1 = Tempfile.new(['tempfile_1', ".txt"])
FileUtils.cp('some/mounted/path/example.txt', tempfile_1.path)
tempfile_2 = Tempfile.new(['tempfile_2', ".txt"])
FileUtils.cp(tempfile_1.path, tempfile_2.path)
puts tempfile_2.read # will be empty, but should not be
```

On the working Docker for Mac 3.2.2, the system calls to execute the copies for my 918-byte example file are:
```
655   copy_file_range(7, NULL, 8, NULL, 918, 0) = -1 EXDEV (Invalid cross-device link) <0.000069>
...
655   sendfile(8, 7, NULL, 918)         = 918 <0.000124>
...
655   copy_file_range(8, NULL, 9, NULL, 918, 0) = 918 <0.000104>
```

On the broken Docker for Mac 3.3.1, the system calls to execute the copies are:
```
8791  copy_file_range(7, NULL, 8, NULL, 918, 0) = 918 <0.000150>
...
8791  copy_file_range(8, NULL, 9, NULL, 918, 0) = 0 <0.000106>
```

**Comment by leikind** [comment] 2021-05-03 06:40
having the same issues with Docker for Mac 3.3.0 and 3.3.1

downgrading to 3.1.0 is a temporary workaround

**Comment by leikind** [comment] 2021-05-03 06:55
Having the same problem in Docker for Mac 3.3.0 and 3.3.1, 3.1.0. 
In version 3.2.2 this issue does not exist.

**Comment by ahuglajbclajep** [comment] 2021-05-04 09:03
If you installed Docker for Mac with `brew install --cask docker`, you can force the version to [3.2.2](https://github.com/Homebrew/homebrew-cask/blob/cebb0f5e76/Casks/docker.rb#L6) with the following commands.

```sh
$ brew uninstall docker
$ rm -rf ~/Library/Group\ Containers/group.com.docker/settings.json
$ curl -sSLO https://raw.githubusercontent.com/Homebrew/homebrew-cask/cebb0f5e76/Casks/docker.rb
$ brew install --cask docker.rb
$ open -a Docker
```

`settings.json` is a configuration file related to the amount of memory allocated, etc.
If you are downgrading from 3.3.3 to 3.3.2, you should remove it to avoid configuration compatibility error.
See also: https://github.com/docker/for-mac/issues/4537#issuecomment-626278891.

**Comment by ha4gu** [comment] 2021-05-06 03:32
Confirmed the same problem still occurs in Docker for Mac 3.3.2.

**Comment by mkleint** [comment] 2021-05-12 05:01
this is not mac specific only, we are seeing this on containerized linux boxes as well, see https://github.com/docker/for-linux/issues/1015#issuecomment-839427751 (which has been unfortunately closed)

**Comment by leikind** [comment] 2021-05-12 08:56
Docker for M1 Macs version 3.3.3 has the same behavior

**Comment by stephen-turner** [comment] 2021-05-14 10:08
This appears to be an upstream bug, docker/for-linux#1015, so I've reopened that one and am closing this one.

**Closed by stephen-turner** 2021-05-14 10:08 UTC

**Comment by andypike** [comment] 2021-05-24 15:46
We had this exact same issue which presented itself as the following error in our Ruby on Rails test specs that used an image uploader from CarrierWave and MiniMagick (adding all the keywords to help people searching):

```
Validation failed: Avatar Failed to manipulate with MiniMagick, maybe it is not an image? Original
Error: `identify /tmp/mini_magick20210524-1-1b85gqv.jpg` failed with error:
       identify-im6.q16: insufficient image data in file `/tmp/mini_magick20210524-1-1b85gqv.jpg' @ error/
jpeg.c/ReadJPEGImage/1039.
```

Our fix was to change the path that Ruby's `Tempfile` uses to create files. So rather than placing them in `/tmp` we changed this to `/app/tmp` with the following environment variable change: 

```
TMPDIR=/app/tmp
```

**Comment by TemaMelnikov** [comment] 2021-05-25 08:50
The bug is still present in all versions greater than 3.2.2

**Comment by RafalWalczak** [comment] 2021-05-28 15:37
> For everyone coming here because their Ruby/Rails uploader specs using `Rack::Test::UploadedFile` are breaking, this is what worked for me:
> 
> Instead of doing this:
> 
> ```ruby
> Rack::Test::UploadedFile.new(Rails.root.join('spec/files/test.jpg'), 'image/jpeg')
> ```
> 
> I did this ugly patch to work around the circumstances leading to the error:
> 
> ```ruby
> file = File.open(Rails.root.join('spec/files/test.jpg'))
> Rack::Test::UploadedFile.new(file, 'image/jpeg', true, original_filename: 'test.jpg')
> ```
> 
> UPDATE: I forgot to mention that I’m using Carrierwave. It does not seem to work with ActiveStorage, I’m afraid. 🤷‍♂️

I've extend you solution and it works for ActiveStorage as well:

https://github.com/rails/rails/issues/41991#issuecomment-846947266
