### ISSUE TITLE
Docker stops listening on UDP port

### ISSUE THREAD

**Issue by jabenninghoff** [docker/for-mac#674] opened 2016-09-19 19:58 UTC
### Expected behavior

I'm running [graylog2](https://hub.docker.com/r/graylog2/server/) on Docker for Mac 1.12.1, using `docker-compose` listening on UDP port 1514. Graylog should ingest all log data sent to it via syslog from remote macs.

### Actual behavior

Graylog ingests syslog data for a varying period of time (generally less than an hour), then stops recording new messages. Restarting the graylog container using `docker restart` resumes logging.

### Information

The following error messages appear in `/var/log/system.log` at the time Graylog stops recording new messages:

```
Sep 19 11:31:05 myhost Docker[1365]: Socket.Datagram.recvfrom: dropping partial response
Sep 19 11:31:05 myhost Docker[1365]: udp:0.0.0.0:1514:udp:172.18.0.4:1514: shutting down recvfrom thread: (Failure "Socket.Datagram.recvfrom partial response")
```

Diagnostics:
```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/1D6B63C2-00F4-4689-A324-4081FA1C59A9/20160919-144050.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

### Steps to reproduce the behavior

1. Launch Graylog with `docker-compose up -d` using the `docker-compose.yml` below
2. Add a new Syslog UDP Input from the Systems > Inputs page in Graylog. Select the running node, port 1514, otherwise default settings
3. Configure OS X systems to forward to Graylog per the docs: http://docs.graylog.org/en/2.1/pages/sending_data.html#sending-syslog-from-macos-x-hosts
4. Wait for error message

Here is my `docker-compose.yml` (passwords and secrets have been changed):

```
version: '2'
services:
  mongo:
    image: "mongo:3"
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    environment:
      TZ: US/Central
  elasticsearch:
    image: "elasticsearch:2"
    restart: unless-stopped
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      TZ: US/Central
    ulimits:
      nofile: 65536
  graylog:
    image: graylog2/server:2.1.1-1
    restart: unless-stopped
    volumes:
      - ./data/journal:/usr/share/graylog/data/journal
    environment:
      TZ: US/Central
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_ROOT_TIMEZONE: US/Central
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
```

**Comment by jabenninghoff** [comment] 2016-09-19 23:42
Updated with additional detail for reproducibility.

**Comment by djs55** [comment] 2016-09-20 13:31
Thanks for the report. From the error message it looks like 2 problems interacting together

1. [this code](https://github.com/docker/vpnkit/blob/0c7cf022b6621584101006af9ff241b3405661e6/src/hostnet/lib/forward.ml#L165) assumes that UDP datagrams are going to be less than 2048 bytes in size, when they can be much bigger. I suspect this is a confusion between ethernet frame size and IP datagram size.
2. when a large (> 2048 byte) datagram is received the datagram is truncated and [this code](https://github.com/docker/vpnkit/blob/0c7cf022b6621584101006af9ff241b3405661e6/src/hostnet/lib/host_uwt.ml#L212) considers such a "partial" datagram as a fatal error and stops listening.

I'll start working on a fix and a regression test to make sure "large" UDP packets work.

**Comment by jabenninghoff** [comment] 2016-09-20 13:40
Thanks!

**Comment by djs55** [comment] 2016-09-26 14:28
This has been fixed in the master branch and should be in the next beta (27). I'll update the ticket when the beta is out.

**Comment by jabenninghoff** [comment] 2016-09-26 23:34
Great, thanks for the quick response! I'll try out the beta when it comes out and report back on results.

**Comment by dsheets** [comment] 2016-09-28 19:11
Beta 27 has been released. Could you give it a try and let us know if it resolves the issue for you?

**Comment by jabenninghoff** [comment] 2016-09-29 19:14
I have been running graylog now for ~20 hours and have seen no issues. Syslog UDP has not stopped working and no Docker errors related to UDP in the system.log. Fixed, Thanks!!!

**Closed** 2016-09-29 19:18 UTC
Labels: area/network, osx/10.11.x, status/4-fix-released-beta, version/1.12.1
