### ISSUE TITLE
Docker won't start.

### ISSUE THREAD

**Issue by michaelretrace** [docker/for-mac#762] opened 2016-10-07 16:13 UTC
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/FF5023DC-4F55-4FC1-BF7A-22D947B06894/20161007-105049.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by blahster** [comment] 2016-10-07 16:53
Looks like a duplicate of #761

**Closed** 2016-10-07 20:17 UTC
