### ISSUE TITLE
Registry connectivity error with 3.3.3 MacOS and new virt framework

### ISSUE THREAD

**Issue by iben12** [docker/for-mac#5680] opened 2021-05-11 20:45 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
login/pull/push works with 3.3.3 on Apple M1 with new virtualization framework enabled
### Actual behavior
I get
`Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
error. Not just docker hub, but any registry I tried.
### Information

I experienced this error while on 3.3.3. Could not resolve, so I removed Docker Desktop and re-installed 3.3.1 from dmg. At the first start-up I was informed that Docker must be reset to factory settings because I had a later version installed. I agreed. Everything worked again.

I then updated to 3.3.3 via the update menu and registry connection was broken again. 

I found out that disabling new virtualization framework fixes the issue.

I do not really remember ever enabling new virtualization framework, however they say that at 3.3.2 that was suggested by the application so maybe I did. Anyway, reset to factory should have disable it anyway.  Or I did use 3.3.1 with the new framework without errors, but in this case this is a regression.
  - macOS Version: 11.3
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.3.3(64133)

### Steps to reproduce the behavior

  1. Enable new virtualization framework
  2. Try to `docker login` or `docker pull` or `docker push`

**Comment by iben12** [comment] 2021-05-11 20:45
Oh, just go forward to the question: I do not use VPN.

**Comment by gmsantos** [comment] 2021-05-11 20:56
I can confirm the same problem in intel mac too, it also affects `docker build`; here a diagnostics to help: F423B07D-A600-4B9E-9F9E-7AFB26629699/20210511205453

**Comment by larseggert** [comment] 2021-05-12 10:10
Same issue here.

**Comment by xgt001** [comment] 2021-05-12 14:29
can confirm, same here

**Comment by i2rulloa** [comment] 2021-05-12 17:11
Same issue...

**Comment by phumberdroz** [comment] 2021-05-12 19:44
Same here

**Comment by lordgordon** [comment] 2021-05-13 07:43
Same issue, using Apple M1 and new virtualisation framework. Suggested workaround to rollback to `3.3.1` solved the issue.

**Comment by gmsantos** [comment] 2021-05-13 07:46
@lordgordon disabling new virt on 3.3.3 also works

**Comment by newmaniese** [comment] 2021-05-13 12:45
Just putting it out, and I assume based on the change of the bug name people already know this, but this is occurring on non-M1 Macs as well.

Thanks for looking into this problem, definitely caught me off guard as I was using the new virtualization for some time.

**Comment by stefanodecillis** [comment] 2021-05-14 11:05
Any news regarding the problem? 
As said, it becomes harder to use docker without pulling images

**Comment by gmsantos** [comment] 2021-05-14 11:11
@stefanodecillis did you disabled new virt as a workaround?

Since the new virtualization is experimental, I would not rely on it in my daily tasks.

**Comment by stefanodecillis** [comment] 2021-05-14 11:23
@gmsantos I didn't try to be honest. It is working properly disabling the new virt even if I was hoping to use it ahaha

**Comment by stephen-turner** [comment] 2021-05-14 12:52
@djs55 PTAL. Thanks.

**Comment by djs55** [comment] 2021-05-14 13:06
Thanks for your reports. I recently fixed a problem in this area, could you try an experimental build?
- Apple Silicon: https://desktop-stage.docker.com/mac/stable/arm64/64397/Docker.dmg
- Intel: https://desktop-stage.docker.com/mac/stable/amd64/64397/Docker.dmg

Note I've not notarised the builds so there will probably be a warning from macOS the first time it's launched. Let me know if it works any better. If not, could you upload some diagnostics and quote the ID here? Thanks!

**Comment by iben12** [comment] 2021-05-14 13:33
Hi @djs55,

I can confirm that on this build (3.4.0 64397) `docker pull` works with the new virtualization framework **enabled**, so it seems to fix the bug.

**Comment by iben12** [comment] 2021-05-14 13:37
Whoever wants to try this preview build, just run:
```
xattr -cr /Applications/Docker.app
```
to un-quarantine Docker app and then you can *Cancel* the popup that says the *application is damaged and you have to move it to the bin*.

**Comment by gmsantos** [comment] 2021-05-14 13:47
@djs55 👍  with intel build and new virt framework enabled. Thanks!

**Comment by SwenVanZanten** [comment] 2021-05-14 13:51
Works for me too on M1 and new framework enabled 👍

**Comment by ezpuzz** [comment] 2021-05-14 16:27
Fixed pulling on my M1, thank you @djs55

**Comment by viniciussalmeida** [comment] 2021-05-14 21:32
Hi @djs55 it worked for me too, on Intel and new virtualization framework enabled.

**Comment by genevera** [comment] 2021-05-19 06:08
3.4.0 works for me

**Comment by gmsantos** [comment] 2021-05-20 08:08
@genevera how can I get 3.4.0? It doesn't show in updates for me

**Comment by dduportal** [comment] 2021-05-26 15:17
Same issue with 3.3.3. Worked without the new hypervisor framework. 
The new dev. build is fixing the issue on my Intel mac, great job, thanks a lot folks!

**Comment by jtr109** [comment] 2021-06-03 03:32
> Thanks for your reports. I recently fixed a problem in this area, could you try an experimental build?
> 
> * Apple Silicon: https://desktop-stage.docker.com/mac/stable/arm64/64397/Docker.dmg
> * Intel: https://desktop-stage.docker.com/mac/stable/amd64/64397/Docker.dmg
> 
> Note I've not notarised the builds so there will probably be a warning from macOS the first time it's launched. Let me know if it works any better. If not, could you upload some diagnostics and quote the ID here? Thanks!

It works well! Thank you very much!

**Comment by jtr109** [comment] 2021-06-10 02:18
Hi, everyone:

The Docker Desktop noticed me to update to a new release [Docker Desktop 3.4.0](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-340), but I don't see any information about this issue.

Is this problem attempted be resolved in that version? Should I update to the new version to have a try?

**Comment by gmsantos** [comment] 2021-06-10 07:33
Updating to 3.4.0 and enabling new virt framework worked here.

**Comment by fanvinga** [comment] 2021-06-10 14:02
> Hi, everyone:
> 
> The Docker Desktop noticed me to update to a new release [Docker Desktop 3.4.0](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-340). But I don't see this issue motioned.
> 
> Is this problem attempted be resolved in that version? Should I update to the new version to have a try?

New release version works for me here (Apple Silicon M1),but i don't see this issue mentioned in release note neither.

BTW my issue #5725 also has fixed and hasn't mentioned neither.

**Comment by djs55** [comment] 2021-06-10 15:43
@gmsantos thanks for letting us know it worked for you in 3.4.

@jtr109 @fanvinga this issue should be fixed in 3.4, sorry it wasn't mentioned in the release notes. I'll close the ticket but feel free to open a new one if you experience another problem.

**Closed by djs55** 2021-06-10 15:43 UTC
Labels: version/3.3.3

**Comment by jtr109** [comment] 2021-06-10 23:35
> > Hi, everyone:
> > The Docker Desktop noticed me to update to a new release [Docker Desktop 3.4.0](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-340). But I don't see this issue motioned.
> > Is this problem attempted be resolved in that version? Should I update to the new version to have a try?
> 
> New release version works for me here (Apple Silicon M1),but i don't see this issue mentioned in release note neither.
> 
> BTW my issue #5725 also has fixed and hasn't mentioned neither.

Hi, #fanvinga! Thanks for your reply! I will have a try on the new version.
