### ISSUE TITLE
M1 Preview - oci8 install error with docker-compose

### ISSUE THREAD

**Issue by topcueser** [docker/for-mac#5309] opened 2021-02-01 18:51 UTC
/usr/bin/ld: skipping incompatible //usr/lib/libclntsh.so when searching for -lclntsh
/usr/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
Makefile:211: recipe for target 'oci8.la' failed
make: *** [oci8.la] Error 1
ERROR: `make' failed
ERROR: Service 'container_name' failed to build : The command '/bin/sh -c echo 'instantclient,/usr/local/instantclient' | pecl install oci8-2.2.0' returned a non-zero code: 1

**Comment by stephen-turner** [comment] 2021-02-02 08:43
@topcueser Can you give steps to reproduce please?

**Comment by topcueser** [comment] 2021-02-02 09:11
> @topcueser Can you give steps to reproduce please?

Hi, you can check the setup files from the link. Thanks.

https://github.com/topcueser/docker-files/tree/master/docker

**Comment by djs55** [comment] 2021-02-12 16:36
@topcueser thanks for your report.

I think the root cause of the linking failure is that your Dockerfile is downloading `x64` (also known as `amd64` or `x86_64` i.e. Intel) architecture binaries: https://github.com/topcueser/docker-files/blob/a09b80d1124cce70bcb79f055acac551ea373582/docker/Dockerfile#L38
```
RUN cd /tmp && curl -L https://raw.githubusercontent.com/topcueser/docker-files/master/oci8-instantclient/instantclient-basiclite-linux.x64-19.3.0.0.0dbru.zip -O
RUN cd /tmp && curl -L https://raw.githubusercontent.com/topcueser/docker-files/master/oci8-instantclient/instantclient-sdk-linux.x64-19.3.0.0.0dbru.zip -O
RUN cd /tmp && curl -L https://raw.githubusercontent.com/topcueser/docker-files/master/oci8-instantclient/instantclient-sqlplus-linux.x64-19.3.0.0.0dbru.zip -O
```
but when running on Apple M1 you need `arm64` (also known as `aarch64`) architecture binaries.

Hopefully if you download `arm64` binaries the problem will be resolved. I'll close this ticket as I don't think it's a Docker Desktop specific bug.

**Closed by djs55** 2021-02-12 16:36 UTC
Labels: area/m1
