### ISSUE TITLE
docker ps hangs indefinitely

### ISSUE THREAD

**Issue by picrin** [docker/for-mac#404] opened 2016-08-23 12:58 UTC
### Expected behavior

I expect docker ps to return a list of all running docker containers. As I've just rebooted my machine I'd expect this list to be empty.

### Actual behavior

docker ps hangs indefinitely. Restarting docker and/or the machine does not resolve.

### Information

Diagnostic ID: DFD58759-68A9-41F3-B02F-9C64F54E1C16
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by picrin** [comment] 2016-08-23 13:22
possible a duplicate of #11

Factory Reset fixes the issue (Preferences -> Uninstall/Reset -> Factory Reset)

**Comment by MagnusS** [comment] 2016-08-30 09:40
Thanks for the report. I'm closing this as the issue was resolved and looks like a duplicate of #11. Please reopen if needed.

**Closed by MagnusS** 2016-08-30 09:40 UTC
Labels: area/startup, osx/10.11.x, version/1.12.0
