### ISSUE TITLE
Chromium's 'Hardware Acceleration' Issue - Need setting to disable

### ISSUE THREAD

**Issue by jasonfutch** [docker/for-mac#5207] opened 2020-12-31 16:35 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

To be able to turn off 'hardware acceleration' in chromium as it is affecting the view of docker desktop.

![image](https://user-images.githubusercontent.com/727259/103418212-b5d9f780-4b5b-11eb-962f-1a68f5126b62.png)

![image](https://user-images.githubusercontent.com/727259/103418345-3a2c7a80-4b5c-11eb-90af-95fc7e256251.png)

### Actual behavior

Certain parts of the screen turn green because of hardware acceleration is enabled by default.

![image](https://user-images.githubusercontent.com/727259/103418162-7e6b4b00-4b5b-11eb-80b0-6506d097f5f3.png)

![image](https://user-images.githubusercontent.com/727259/103418491-e40c0700-4b5c-11eb-8ef9-788d4262d1e0.png)

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version 11.1

```

### Steps to correct

The app.disableHardwareAcceleration() Instance method of the app module disables Hardware acceleration for the entire application. This Instance method can only be used before the ready event of the app module is emitted. Hence, this method needs to be called in the main.js file (Main Process). 

```javascript
const { app, BrowserWindow } = require('electron') 
app.disableHardwareAcceleration(); 
```

**Comment by stephen-turner** [comment] 2021-03-08 13:40
Thanks. I'm going to close this as a dupe of #5121, but we will try your solution.

**Closed by stephen-turner** 2021-03-08 13:40 UTC
