### ISSUE TITLE
Docker crashed on MacOS Siera (public beta 3)

### ISSUE THREAD

**Issue by pbelyaev** [docker/for-mac#142] opened 2016-08-05 05:52 UTC
### Information

Diagnostic ID: 4E14288C-F711-4731-80C7-5389F15AA40C
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Open docker for mac
2. Run container
3. Wait till error will apear

**Comment by tgautier** [comment] 2016-08-05 14:18
Duplicate of #64 

Same macOS build number `16A270f`

**Comment by dave-tucker** [comment] 2016-08-09 02:14
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:14 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
