### ISSUE TITLE
yaml.composer.ComposerError: expected a single document in the stream

### ISSUE THREAD

**Issue by meelody** [docker/for-mac#2429] opened 2018-01-14 07:04 UTC
when I type in the 'docker-compose -f samples/bookinfo/kube/bookinfo.yaml up -d' command.This yaml is ok, and the same is true for other files.
There was a mistake：

ERROR: yaml.composer.ComposerError: expected a single document in the stream
  in "./samples/helloworld/helloworld.yaml", line 1, column 1
but found another document
  in "./samples/helloworld/helloworld.yaml", line 14, column 1

**Comment by thaJeztah** [comment] 2018-01-15 00:39
That file (https://github.com/istio/istio/blob/master/samples/bookinfo/kube/bookinfo.yaml) is to be used with kubernetes, it's not a docker-compose file, so it's expected that using that file will fail with docker compose


Closing, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-01-15 00:39 UTC
