### ISSUE TITLE
Docker does not rely on Virtualbox

### ISSUE THREAD

**Issue by betty200744** [docker/for-mac#1343] opened 2017-02-27 08:50 UTC
### Expected behavior

run current
### Actual behavior
docker start faild
### Information

Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
VirtualBox v4.3.26 is currently installed.
Please upgrade or uninstall Virtualbox.

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.4 (build: 15E65)
logs: /tmp/73C89868-D67E-4DB0-A7B3-ED65A833D940/20170227-164710.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/betty/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/betty/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/betty/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/betty/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/betty/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/betty/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MagnusS** [comment] 2017-03-08 13:59
Thanks for the report @betty200744. 

Docker for Mac will not start if the kernel drivers from a Virtualbox version earlier than 4.3.30 are installed. Earlier versions of Virtualbox did not run reliably with applications that use Hypervisor.framework (such as Docker for Mac) which would result in system crashes. 

If you have deleted Virtualbox manually the kernel drivers may still be installed. Please follow https://www.virtualbox.org/manual/ch02.html#idm871 to completely uninstall Virtualbox. 

I'm closing this issue for now, but please let us know if this doesn't solve your issue.

(duplicate of docker/for-mac#78)

**Closed by MagnusS** 2017-03-08 13:59 UTC
Labels: status/0-triage, version/1.13.1
