### ISSUE TITLE
Docker for Mac and docker network access from host

### ISSUE THREAD

**Issue by stefanfoulis** [docker/for-mac#171] opened 2016-08-08 12:02 UTC
### Expected behavior

I can access all containers by ip address from my OSX host directly.
### Actual behavior

I can't access containers by network unless I map ports to 127.0.0.1.
### Information

Diagnostic ID: 13B73004-5CA7-40F3-B597-AA61D1FC6C37
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. `docker run --name=httpd -d httpd`
2. `docker inspect httpd` extract IPAddress from the output (e.g `172.17.0.2`)
3. `curl http://172.17.0.2/` - expected to get the apache page, but get a timeout
### Notes

I understand that the reason for this not working, is that this is due to the documented fact that there is no `docker0` interface available on osx (https://docs.docker.com/docker-for-mac/networking/#/there-is-no-docker0-bridge-on-osx).
For our workflow (allowing the host to access containers directly from the host, without port mapping) it is pretty crucial. So my main question is, if there are plans to support this or if it is an impossible to overcome technical hurdle.

**Comment by onigoetz** [comment] 2016-08-11 09:14
I would also be interested of the status on this.

**Comment by dbpolito** [comment] 2016-08-31 16:48
I would love to see this too.

**Comment by Multiply** [comment] 2016-09-06 08:04
Something like suggested in this thread: https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835

**Comment by charlesporter** [comment] 2016-09-20 05:06
+1 for addressing this

**Comment by AlmirKadric** [comment] 2016-09-25 02:01
+1 for this fix

**Comment by rcarmich** [comment] 2016-10-13 14:44
I believe this is the same issue I'm experiencing. If I start an nginx container that should proxy to some code running on my actual host, I can't do that anymore since upgrading from docker toolbox. I used to be able to proxy requests to 10.0.2.2 or whatever IP my host was given, but now the host has no IP (other than my DHCP given IP) for a reliable proxy destination. Very much a blocker for us, unless I'm missing something.

**Comment by wojas** [comment] 2016-10-31 07:32
As a workaround, I ended up using OpenVPN to access the Docker networks.

My setup can be found here (easy to use Compose file): [wojas/docker-mac-network](https://github.com/wojas/docker-mac-network)

**Comment by belooussov** [comment] 2016-11-09 14:25
+1

**Comment by ijc25** [comment] 2016-11-18 15:20
Closing as dup of #155.

**Closed by ijc25** 2016-11-18 15:20 UTC
Labels: area/network, kind/enhancement, osx/10.11.x, status/1-acknowledged, version/1.12.0

**Comment by AlmirKadric** [comment] 2017-07-19 14:56
I am pasting this for anyone who comes here and feels at a loss
There is a shim workaround for this issue in this project
https://github.com/AlmirKadric-Published/docker-tuntap-osx

More details can be found here:
https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835/21

**Comment by marnen** [comment] 2018-11-04 16:18
@ijc:
> Closing as dup of #155

This *is* #155. Why did you close it as a duplicate of itself? Where should one go for updates now?

**Comment by Multiply** [comment] 2018-11-04 17:21
@marnen This is #177.

**Comment by marnen** [comment] 2018-11-04 17:29
@Multiply Yes it is. I don’t know how I managed to misread the URL, but I feel really silly now. :P Sorry about that!
