### ISSUE TITLE
Fatal error after updating 

### ISSUE THREAD

**Issue by Banjerr** [docker/for-mac#2321] opened 2017-12-14 13:46 UTC
### Expected behavior

Docker starts without issue

### Actual behavior

Docker does not start at all and throws a fatal error

### Information

```Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/15BD6FDF-589A-418A-94A8-7BB635FEC8EF/20171214-084226.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ben/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ben/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ben/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Download update for Docker-For-Mac ( version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622) )
  2. Start Docker

**Comment by jeantil** [comment] 2017-12-14 14:34
see discussion in https://github.com/docker/for-mac/issues/2317 as it may help with this issue

**Comment by gtardif** [comment] 2017-12-15 16:00
Closing as duplicate of #2317

**Closed by gtardif** 2017-12-15 16:00 UTC
