### ISSUE TITLE
Docker not coming up

### ISSUE THREAD

**Issue by cmPrasanna** [docker/for-mac#99] opened 2016-08-03 09:51 UTC
### Expected behavior

Docker should install on Mac

### Actual behavior

Docker is throwing error

### Information

Diagnostic ID: D9057BF2-7E34-4361-834E-57D114F2D5AA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.2 (Build 15C50)
[ERROR]  docker-cli
         wrong Docker version: 1.6.0 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/srp/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/srp/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/D9057BF2-7E34-4361-834E-57D114F2D5AA/20160803-151504/qemu-img-check.stdout 2> /tmp/D9057BF2-7E34-4361-834E-57D114F2D5AA/20160803-151504/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/srp/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/srp/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/srp/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment] 2016-09-09 14:52
I think this is a duplicate of #98

**Closed by djs55** 2016-09-09 14:52 UTC
