### ISSUE TITLE
“Docker” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by bennettp123** [docker/for-mac#7149] opened 2024-01-29 09:46 UTC
### Description

After updating from 4.26.1 to 4.27.0, docker no longer runs, and instead shows an error `“Docker” is damaged and can’t be opened. You should move it to the Bin.`
<img width="372" alt="image" src="https://github.com/docker/for-mac/assets/1610227/93282c8c-5cfc-416f-b03b-bc2e75f09c81">

### Reproduce

Docker → Update & Restart

### Expected behavior

Docker 4.27.0 installs successfully

### docker version

_Edit: this was gathered **after** manually reinstalling:_

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:06:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.0 (135262)
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:35 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

This was the original result:

<img width="1301" alt="image" src="https://github.com/docker/for-mac/assets/1610227/8b4de502-e58f-436f-a7ce-f8069c7dcb1c">

### docker info

_Edit: this was gathered **after** manually reinstalling:_

```bash
Client:
 Version:    25.0.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/bennett/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/bennett/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/bennett/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/bennett/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/bennett/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/bennett/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/bennett/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/bennett/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/bennett/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/bennett/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/bennett/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 33
  Running: 24
  Paused: 0
  Stopped: 9
 Images: 103
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.989GiB
 Name: docker-desktop
 ID: 15e53970-6dd3-47fb-b794-5e8a7c2401b0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  host.docker.internal:5050
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

```

This was the original result:

<img width="1298" alt="image" src="https://github.com/docker/for-mac/assets/1610227/1b5a0e29-de71-47d8-8fb1-cf4aea88ccc0">

### Diagnostics ID

_Edit: this was gathered **after** manually reinstalling:_

```
548C628A-E7BF-4675-86DC-1F0099F26FE2/20240129095553
```

This was the original result:

<img width="1303" alt="image" src="https://github.com/docker/for-mac/assets/1610227/9a52f6cb-e347-483c-a0d4-09cebcffe0df">

### Additional Info

Apologies for the lack of info.

I still have a copy of the damaged Docker.app if necessary—let me know if there's any further troubleshooting commands I can run that might be helpful 😁  

Downloading and installing 4.27.0 from https://docs.docker.com/desktop worked fine

**Comment by Fogh** [comment] 2024-01-29 12:05
The same happened for me. I tried downloading it manual instead, but got version 4.26.1 from the website. Tried updating once again, but now it is stuck on "Installing update"

**Comment by karman-docker** [comment] 2024-01-29 12:58
@bennettp123 Do you recall around what time  4.26.1 to 4.27.0 upgrade was attempted which failed ?

**Comment by bennettp123** [comment] 2024-01-29 16:35
> @bennettp123 Do you recall around what time 4.26.1 to 4.27.0 upgrade was attempted which failed ?

only an estimate—probably about 2024-01-29T09:15:00Z, give or take an hour

**Comment by Fogh** [comment] 2024-01-31 13:44
I still get the error. When trying to install 4.27 my Docker.app becomes damaged. Is this only related to Apple Silicon?

**Comment by bennettp123** [comment] 2024-02-02 06:23
Just installed 4.27.1 (using in-app update)—worked fine 😁

**Comment by jonathan-wondereur** [comment] 2024-02-14 12:37
I get this error whenever I update Docker Desktop via the Docker Desktop client. I have to go and manually download a new copy from the website.

It may be related to trying to update with a user account that is a non-admin on Apple Silicon.

**Comment by bsousaa** [comment] 2024-02-14 16:06
@jonathan-wondereur can you share a diagnostics id? cc @neonima

**Comment by asaha123** [comment] 2024-02-14 22:50
for those who are still getting it, even after installing a new release from the website, this helped for me:

```
$ launchctl remove com.docker.helper
```

Installing the new version after stopping the service, seems to have done it.

**Comment by neonima** [comment] 2024-02-15 00:06
@asaha123 @jonathan-wondereur Would you be able to confirm you've updated to 4.27.1 or higher? Thanks a lot for reporting 🙏 If that's not too disruptive for you, as @bsousaa said, the diag ID would help us finding out more hints into this

**Comment by asaha123** [comment] 2024-02-15 00:09
@neonima i can confirm that i downloaded 4.27.1 and then used the in-app updater to update to 4.27.2.

If I see it again, i can report the diagnostics ID.

**Comment by neonima** [comment] 2024-02-15 01:15
Brilliant thank you! To confirm you've had the damaged when you tried to update to 4.27.1, then you downloaded it and turned off the service and did the update through the app to 4.27.2? or something along these lines?

**Comment by asaha123** [comment] 2024-02-15 01:16
yes i think that's accurate 🙏

**Comment by neonima** [comment] 2024-02-15 01:19
Awesome thanks a lot for the quick answer and for the diag :)

**Comment by neonima** [comment] 2024-02-15 18:46
@jonathan-wondereur @asaha123 After you pressed Update DD, did you see it close and then reopened it by clicking on the DD application?

**Comment by jonathan-wondereur** [comment] 2024-02-15 19:31
It closed but never reopened. I don't understand how it could have updated without asking for an admin user/password, as I do not run as an admin user.

**Comment by asaha123** [comment] 2024-02-15 22:21
> @jonathan-wondereur @asaha123 After you pressed Update DD, did you see it close and then you reopened it by clicking on the DD application?

I think it reopened itself, just to stress the point, i needed to stop the service via launchtl (as per my previous comments), before any of it worked!

**Comment by mshimokura** [comment] 2024-02-20 14:11
I was able to work around this issue (probably similar to the launchctl workaround) by navigating to System Preferences > Login Items, and disabling the docker related items, re-installing docker, opening it (with successful verification), then re-enabling the "login items".

**Comment by evox95** [comment] 2024-03-06 10:42
Put Docker.app in the Applications folder and then install it using CLI
sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
https://docs.docker.com/desktop/install/mac-install/#install-and-run-docker-desktop-on-mac

**Comment by neonima** [comment] 2024-05-10 12:37
Docker being marked as damaged due to symlinked being used at the same time an in-update is happening has been fixed! Please open a new issue if this arises again from 4.30

**Closed by neonima** 2024-05-10 12:37 UTC
Labels: status/triage, status/acknowledged, area/update, version/4.27.0, version/4.27.1

**Comment by SuCicada** [comment] 2025-01-10 02:51
> for those who are still getting it, even after installing a new release from the website, this helped for me:
> 
> ```
> $ launchctl remove com.docker.helper
> ```
> 
> Installing the new version after stopping the service, seems to have done it.

this work for me
