### ISSUE TITLE
No man page for "docker" command

### ISSUE THREAD

**Issue by vsipuli** [docker/for-mac#1089] opened 2016-12-28 21:11 UTC
### Expected behavior

Running "man docker" shows the manual page for the "docker" command.

### Actual behavior

Running "man docker" says that no such manual page exists:

```
$ man docker
No manual entry for docker
```

### Steps to reproduce the behavior

  1. Open Terminal
  2. Run "man docker"

A system utility to be taken seriously is expected to provide a man page.

**Comment by justincormack** [comment] 2017-01-03 10:52
Hi, sorry about this, it is planned but there have been some upstream issues delaying implementation. I will look at this again and see if we can fix the issues.

**Comment by justincormack** [comment] 2017-01-03 10:52
Duplicate of https://github.com/docker/for-mac/issues/743 which is our tracking issue, so closing.

**Closed by justincormack** 2017-01-03 10:52 UTC
