### ISSUE TITLE
fs events not working for services

### ISSUE THREAD

**Issue by cpuguy83** [docker/for-mac#148] opened 2016-08-05 17:15 UTC
### Expected behavior

swarm services with bind mounts should receive fs notifications from OSX
### Actual behavior

fs events are not working
### Steps to reproduce the behavior

https://github.com/rheinwein/inotifywait

**Comment by dsheets** [comment] 2016-08-05 17:16
Thanks for the report!

**Comment by BretFisher** [comment] 2016-08-10 03:57
TL;DR on the repo. How to reproduce:

1. Initialize swarm on Docker for Mac (beta 21.1)
2. create service with bind-mount
```docker service create 
  --name inotify 
  --mount type=bind,source=$(pwd)/watch,target=/opt/watch 
  inotifywait```
3. change files from inside container, inotifywait running in container sees changes
4. change files from mac, inotifywait running in container doesn't see changes
5. files are properly created/updated on both sides of bind-mount, just no filesystem events fired inside container

**Comment by januzis** [comment] 2016-09-16 15:20
The same thing could be reproduced by using `docker-compose` with `volumes_from`. When using `volumes_from` the filesystem events aren't working, but with `volumes` it works fine.

**Comment by fentas** [comment] 2017-06-08 06:34
Having the same problem. Is there any workaround for this? I tried polling mechanism but CPU explodes with this method.

**Comment by TennyZhuang** [comment] 2018-01-21 04:32
A simple workaround is using rsync but not volume to sync your code

really want docker support the fs events for development in container

**Comment by detj** [comment] 2018-02-13 20:03
It would be really awesome to get this working. Stumbled here because I wanted to get [nodemon](https://github.com/remy/nodemon) working from a `docker-compose` bind mount.


```
volumes:
  - .:/usr/src/app
```

Any filesystem events occurring inside app directory should be picked up by nodemon so that it can restart the node server.

What are the challenges to get this working?

**Comment by BretFisher** [comment] 2018-02-13 20:58
@detj on Mac this already works. File events pass from container to host macOS, I just tested nodemon and it restarted when I edited a index.js in a bind mount with docker compose.

If you're here because you're using Docker for Windows, you need to enable nodemon's legacy polling mode with the `-L` option.

https://github.com/remy/nodemon#application-isnt-restarting

**Comment by justinappler** [comment] 2018-03-08 20:41
@BretFisher I think he means events from the host don't propagate to the container, the other way around works fine.

This still does not work.

**Comment by detj** [comment] 2018-03-09 11:33
@BretFisher @justinappler Yes. I meant events from host don't propagate to container. Sorry for not being clear.

**Comment by nhooey** [comment] 2018-03-13 22:40
Is anyone working on fixing this bug?

It would really help Docker development with React when developing on a Mac host.

**Comment by nhooey** [comment] 2018-03-13 23:07
@cpuguy83 Could you mention in the description of this bug that [inotify-proxy](https://github.com/sillypog/inotify-proxy) is a workaround for this problem?

**Comment by djs55** [comment] 2018-06-26 11:43
This was fixed in [18.05.0-ce-mac66] on 2018-05-17 (https://download.docker.com/mac/edge/24545/Docker.dmg). The changelog has

> Fix filesystem event notifications for Swarm services and those using the new-style --mount option

Related to #2217 #2375

**Closed by djs55** 2018-06-26 11:43 UTC
Labels: area/mounts, kind/bug, status/2-in-progress, version/1.12.0

**Comment by rjurney** [comment] 2018-07-31 01:32
I am on Docker for Mac stable Version 18.06.0-ce-mac70 (26399). I have my app's directory mounted using docker-compose and when I run inotifywait in my container, it does not detect changes on the host filesystem.

It would be great if this worked! :)

**Comment by jemc** [comment] 2020-03-12 15:02
I'm seeing the same bug today, with `Docker version 19.03.7, build 7141c19`. Can the ticket be reopened?

Steps to reproduce:
- Run an alpine container with the current working directory of the host mounted to the working directory of the container.
- Inside the container, run `apk add inotify-tools` to install `inotifywatch`
- On the host, run `touch example.txt` to create a file that will be watched.
- Inside the container, run `inotifywatch example.txt`
- On the host, run `echo "foo" >> example.txt`.
- Interrupt the `inotifywatch example.txt` with SIGINT to show that no events were received, as they should have been.
- Repeat the same steps, this time running `echo "foo" >> example.txt` and see that the event *is* observed when the source of the event is inside the container.
