### ISSUE TITLE
Docker hyperkit is consuming 1.64 GB. RAM even there is no active containers

### ISSUE THREAD

**Issue by funkydorian** [docker/for-mac#856] opened 2016-10-27 10:20 UTC
### Expected behavior

Hyperkit should release the memory

### Actual behavior

Hyperkit does not release the memory

### Information

I restarted Docker4Mac and even it seemed restarted during some time "docker images" was giving error, and it restarted itself again

Related screenshots:
<img width="1092" alt="screen shot 2016-10-27 at 10 39 51" src="https://cloud.githubusercontent.com/assets/8745804/19763719/12f4fd60-9c48-11e6-989f-33909a830ad3.png">

<img width="798" alt="screen shot 2016-10-27 at 10 39 37" src="https://cloud.githubusercontent.com/assets/8745804/19763751/36e802f8-9c48-11e6-9620-00aa25bb4a58.png">

After restart:
<img width="774" alt="screen shot 2016-10-27 at 10 41 14" src="https://cloud.githubusercontent.com/assets/8745804/19763718/12f4db96-9c48-11e6-9ec2-adb5699c447e.png">
<img width="484" alt="screen shot 2016-10-27 at 10 40 40" src="https://cloud.githubusercontent.com/assets/8745804/19763717/12f32d00-9c48-11e6-8f2a-4428e53fac9a.png">
<img width="276" alt="screen shot 2016-10-27 at 10 40 03" src="https://cloud.githubusercontent.com/assets/8745804/19763716/12f172b2-9c48-11e6-8fc8-04a31f739f4e.png">

### Steps to reproduce the behavior

  1. Multiple times building and running containers

**Comment by dave-tucker** [comment] 2016-10-27 21:48
Closing as a duplicate of #178 - Please see the description in https://github.com/docker/for-mac/issues/178#issuecomment-238509543 for an explanation of what's happening

**Closed by dave-tucker** 2016-10-27 21:49 UTC
Labels: status/0-triage
