### ISSUE TITLE
MacOS - Docker crashes at first run

### ISSUE THREAD

**Issue by bandrejx** [docker/for-mac#2731] opened 2018-03-26 22:21 UTC
### Expected behavior
Not crashing @first run

### Actual behavior
Crashes @first run (there was an old working version of docker installed in the past however, but was removed later)

### Information
My diagnostic ID: 5C1CEE3A-FC13-48E8-89FF-37F27A2CDE94

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/5C1CEE3A-FC13-48E8-89FF-37F27A2CDE94/20180327-001302.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Volumes/Mars - Profiles/Users/bandrej/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Volumes/Mars - Profiles/Users/bandrej/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Volumes/Mars - Profiles/Users/bandrej/Library/Containers/com.docker.docker/Data/vms/0/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Volumes/Mars - Profiles/Users/bandrej/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Volumes/Mars - Profiles/Users/bandrej/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started
```

### Steps to reproduce the behavior

given
   a macos user installs docker stable or docker edge
when
  docker has been executed on a first run
then
  docker shows the heightened privileges window, then stops responding

**Comment by bandrejx** [comment] 2018-03-27 23:06
So I tried and installed Docker just now (stable ce) on another user account just to see where it goes. It turns out it was installed and started up VM without any problems. It could have something to do with profile path being on external disk for my user account?
In which case the solution would probably be to really wipe some unknown Docker settings from my Mac?

**Comment by JuliaRechkunova** [comment] 2018-03-28 12:49
@bandrejx Reset to factory defaults helped me to fix it

**Comment by gtardif** [comment] 2018-03-28 13:04
Hi @bandrejx, unfortunately this is dues to the socket file name hitting a size limit, partly because your user home folder is in `/Volumes/Mars - Profiles/Users` rather that straight `/Users/...` (See https://unix.stackexchange.com/a/367012/128332).
In the current release, this folder used for vm files is not configurable, the workaround would be change your home folder location.

**Comment by gtardif** [comment] 2018-03-28 13:05
Closing as a duplicate of #2727

**Closed by gtardif** 2018-03-28 13:05 UTC
Labels: version/18.03.0-ce-mac58

**Comment by bandrejx** [comment] 2018-03-28 18:28
Thank you very much for your prompt answer, @gtardif! Sadly, changing my home folder location is not an option atm.

**Comment by akimd** [comment] 2018-04-25 10:15
Hi people,

We believe that the Stable release we are about to make fixes the issues wrt socket name length (https://github.com/docker/pinata/pull/9241).  Could someone check that this preview actually helps you?  Thanks in advance!

https://download.docker.com/mac/stable/24214/Docker.dmg
