### ISSUE TITLE
Docker restarts whenever I change my internet connection

### ISSUE THREAD

**Issue by dharzheim** [docker/for-mac#1789] opened 2017-06-29 09:42 UTC
This only started happening with the latest update Version 17.06.0-ce-mac18 (18433)

### Expected behavior
- Docker doesn't restart

### Actual behavior
- Whenever I change my internet connection (Switch WiFi Network, turn off WiFi, switch to VPN) Docker restarts

### Information

[20170629-113512.tar.gz](https://github.com/docker/for-mac/files/1111546/20170629-113512.tar.gz)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abellion** [comment] 2017-06-29 16:05
Same here !

**Comment by shillem** [comment] 2017-06-29 16:34
I'm experiencing it too. This issue might me connected to #1772

**Comment by tgree** [comment] 2017-06-30 03:02
I have this too.  It's easy to reproduce with an Ethernet cable... just unplug it and the whale icon shows docker restarting.  In the Preferences panel it looks like I have "Experimental features" checked even though I'm sure I never had it checked before updating to 17.06.0-ce-mac18 so I don't know if that's related at all.

With the last stable version changing networks or sleeping/waking my laptop caused no issues at all for docker.

**Comment by nutsoriginal** [comment] 2017-06-30 08:38
The same issue. Docker restarts when I close internet connection.
Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0

**Comment by kvahuja** [comment] 2017-07-01 03:55
can we get a fix on priority or how do I get to the previous version?

Docker is useless for me now and I am stuck with all my development

**Comment by dharzheim** [comment] 2017-07-01 13:01
Previous versions:
https://gist.github.com/franklinyu/5e0bb9d6c0d873f33c78415dd2ea4138

You can also find the older versions that have been replaced in your Trash.

**Comment by timothyallan** [comment] 2017-07-02 07:48
This sounds like the reason Docker hard exits all my containers whenever I start/quit Charles Proxy. Only just started happening after installing `Version 17.06.0-ce-mac18 (18433)`

```
Unexpected API error for dev_webserver-dev_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by naragobear** [comment] 2017-07-02 10:45
I too see this issue. And it rather easily reproducible. 

Here is the output for `docker version`

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by djs55** [comment] 2017-07-03 10:33
Thanks for the report and the uploaded diagnostics. The logs have:
```
Triggering a VM reboot because proxy settings changed from ma
in.proxySettings{http:"", https:"", exclude:"*.local, 169.254/16"} to main.proxySettings{http:"", https:"", exclude:""}
```
This appears to be the same as #1809

HTTP proxies are configured by modifying the environment variables inside the VM, which requires a VM restart whenever the variables change. In this case perhaps it's unnecessary to reboot when the exclude changes, when there is no actual proxy set.

As a workaround try setting: Whale Menu -> Proxies -> No proxies.

**Comment by spaceoi** [comment] 2017-07-04 03:17
Same:
42E0CE8F-B483-490C-B0AC-546DA27CEFA2

**Comment by djs55** [comment] 2017-07-04 10:39
The unnecessary reboot caused by the `exclude` changing when there is no proxy set has been cherry-picked into the branch for 17.06.1, which should hopefully be released later this week. Thanks for your report!

**Comment by djs55** [comment] 2017-07-17 16:53
The unnecessary reboot fix was released in a patch on the stable branch and the end of last week. The fix is in version:
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
I believe this should fix the problem so I'll close this ticket. If you continue to have problems, could you upload fresh diagnostics and let me know?

**Closed by djs55** 2017-07-17 16:53 UTC
Labels: status/0-triage
