### ISSUE TITLE
Unable to Pull Images on Docker 3.3.3 using the new [virtualization.framework]

### ISSUE THREAD

**Issue by jankovandeventer** [docker/for-mac#5731] opened 2021-06-03 07:38 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  B5D40BC8-4AA4-4C09-AB02-6469184040D0/20210603073549

### Expected behavior

docker pull pulls existing image (found while running Packer Build)

### Actual behavior

Docker pull failes immediately
Build fails after ~2 seconds:

Error messages:

```
user@computer folder % docker pull python:2.7
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I initially found it when trying to build a new image with packer.
```
user@computer folder % packer build hulc.json
docker: output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: python:2.7
    docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused
==> docker: Error pulling Docker image: Bad exit status: 1
Build 'docker' errored after 1 second 51 milliseconds: Error pulling Docker image: Bad exit status: 1

==> Wait completed after 1 second 52 milliseconds

==> Some builds didn't complete successfully and had errors:
--> docker: Error pulling Docker image: Bad exit status: 1

==> Builds finished but no artifacts were created.

```

### Information

  - macOS Version: 11.1 (20C69)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

1. On an Intel based Macbook Pro install Docker Desktop 3.3.3
2. use the new Big Sur virtualization.framework
3. run: `docker pull python:2.7`

**Comment by rherrick** [comment] 2021-06-04 02:32
Same issue with OSX 11.4. I turned off the Big Sur virtualization framework and things started working again. I turned it back on and things stopped working again. That's the critical factor.

**Comment by akokshar** [comment] 2021-06-04 08:04
Having similar issue (docker v3.3.3, osx 11.4) - not able to pull images when using virtualization framework, however different error is reported:
```
⟫ docker run -it --rm debian bash                                       
Unable to find image 'debian:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 192.168.64.1:3128: connect: connection refused.
See 'docker run --help'.
```

Able to start containers using locally cached images. Have to switch back to qemu just to pull an image...

**Comment by PortableProgrammer** [comment] 2021-06-04 21:02
Same issue on M1 (docker 3.3.3, macOS 11.5 b2 20G5033c). Disabling the experimental Big Sur virtualization framework resolves the issue.

**Comment by taiidani** [comment] 2021-06-05 17:44
Similar behavior, Intel (Docker v3.3.3, macOS v11.1 20C69). I had to disable the new virtualization framework in order to pull.

**Comment by adamstamper** [comment] 2021-06-06 17:20
Yep same, Docker v3.3.3 on M1 with macOS 11.4 - had to revert to Docker 3.3.1

**Comment by StefanScherer** [comment] 2021-06-07 06:53
Closing this as it's a duplicate of #5680.

**Closed by StefanScherer** 2021-06-07 06:53 UTC
Labels: version/11.1
