### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by GrahamCampbell** [docker/for-mac#5051] opened 2020-11-07 13:50 UTC
MacOS 11.0.1 Beta (20B5022a), Docker for Mac 2.5.0.0.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/2829600/98442967-38b47800-2100-11eb-9598-5ab8ebbcd15b.png">

**Comment by stephen-turner** [comment] 2020-11-10 10:34
Probably a dupe of #5026.

**Closed by stephen-turner** 2020-11-10 10:34 UTC
