### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by DrogoNevets** [docker/for-mac#5304] opened 2021-01-29 09:22 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker opens and runs

### Actual behavior
First get an error asking to reset to factory settings, after doing this it still dies

NOTE: It was working fine

### Information

  - macOS Version: Big Sur (M1)
  - was workign fine, then after restart failed

### Diagnostic logs

```
Docker for Mac: M1 Preview

```

**Comment by DrogoNevets** [comment] 2021-01-29 09:22
Diag ID is: E915BD80-99CD-43F1-83ED-D08404834EA6/20210129084830

**Comment by ronaldmiranda** [comment] 2021-01-30 01:28
I noticed this problem, when you have VPN services on.

**Comment by jiahuigeng** [comment] 2021-01-30 20:36
Same for me, after restarting, not work anymore

**Comment by wrobelda** [comment] 2021-02-05 05:24
Same issue, restarted the system and now it doesn't work anymore. Logs show following entries, repeating cyclically: 

```
2021-02-05 00:22:40.535709-0500  localhost com.docker.driver.amd64-linux[5818]: still waiting for docker to respond after 1m30.277322417s
2021-02-05 00:23:08.325803-0500  localhost Docker[5224]: (CFNetwork) [com.apple.CFNetwork:Coalescing] success removing entry for host <private> config 0x600001c93140
2021-02-05 00:23:08.326205-0500  localhost Docker[5224]: (CFNetwork) Connection 5: cleaning up
2021-02-05 00:23:08.326297-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] [C5 237DE264-5D6D-4EA7-A0FD-4C95BB2DFA4B Hostname#0c0fe62e:443 tcp, url hash: 10a43815, tls] cancel
2021-02-05 00:23:08.326578-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] [C5 237DE264-5D6D-4EA7-A0FD-4C95BB2DFA4B Hostname#0c0fe62e:443 tcp, url hash: 10a43815, tls] cancelled
	[C5.1 4B98FF44-078E-46DE-84E6-DE7EADEFED13 10.0.2.171:50583<->IPv4#5f04c88c:443]
	Connected Path: satisfied (Path is satisfied), viable, interface: en0, ipv4, dns
	Duration: 120.198s, DNS @0.000s took 0.001s, TCP @0.002s took 0.050s, TLS 1.3 took 0.032s
	bytes in/out: 5767/1865, packets in/out: 5/10, rtt: 0.037s, retransmitted bytes: 0, out-of-order bytes: 0
2021-02-05 00:23:08.326649-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_endpoint_handler_cancel [C5 Hostname#0c0fe62e:443 ready resolver (satisfied (Path is satisfied), interface: en0, ipv4, dns)]
2021-02-05 00:23:08.326699-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_association_schedule_deactivation <nw_association Hostname#0c0fe62e:443> will become dormant after 10 seconds of inactivity
2021-02-05 00:23:08.326746-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_endpoint_handler_cancel [C5.1 IPv4#5f04c88c:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)]
2021-02-05 00:23:08.326784-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_association_schedule_deactivation <nw_association IPv4#5f04c88c:443> will become dormant after 10 seconds of inactivity
2021-02-05 00:23:08.326819-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_read_request_report [C5] Receive cancelled
2021-02-05 00:23:08.326980-0500  localhost Docker[5224]: (libboringssl.dylib) [com.apple.network:boringssl] boringssl_context_log_message(1875) [C5.1:2][0x15c84a0a0] Writing SSL3_RT_ALERT 2 bytes
2021-02-05 00:23:08.327875-0500  localhost Docker[5224]: (libboringssl.dylib) [com.apple.network:boringssl] boringssl_context_handle_warning_alert(1782) [C5.1:2][0x15c84a0a0] write alert, level: warning, description: close notify
2021-02-05 00:23:08.327927-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_flow_disconnected [C5.1 IPv4#5f04c88c:443 cancelled socket-flow ((null))] Output protocol disconnected
2021-02-05 00:23:08.331017-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_resolver_cancel [C5] 0x15c84d1f0
2021-02-05 00:23:08.331107-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_connection_report_state_with_handler_on_nw_queue [C5] reporting state cancelled
2021-02-05 00:23:08.331196-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] [C5 Hostname#0c0fe62e:443 tcp, url hash: 10a43815, tls] dealloc
2021-02-05 00:23:08.331234-0500  localhost Docker[5224]: (CFNetwork) Connection 5: done
2021-02-05 00:23:08.331335-0500  localhost Docker[5224]: (libboringssl.dylib) [com.apple.network:boringssl] boringssl_bio_destroy(196)
2021-02-05 00:23:08.331398-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:] nw_path_flow_registration_close Removed flow B15853D7-A385-4197-8335-951DAA8A4826 from 4B98FF44-078E-46DE-84E6-DE7EADEFED13
2021-02-05 00:23:08.331531-0500  localhost Docker[5224]: (Security) [com.apple.securityd:cssm] 0x14b73c1d0 detach module 0x6000023842d0(AppleX509CL)
2021-02-05 00:23:10.657736-0500  localhost com.docker.driver.amd64-linux[5818]: still waiting for docker to respond after 2m0.400458375s
2021-02-05 00:23:18.335467-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_association_schedule_deactivation_block_invoke <nw_association Hostname#0c0fe62e:443> becoming dormant
2021-02-05 00:23:18.335681-0500  localhost Docker[5224]: (libnetwork.dylib) [com.apple.network:connection] nw_association_schedule_deactivation_block_invoke <nw_association IPv4#5f04c88c:443> becoming dormant
```

**Comment by wrobelda** [comment] 2021-02-05 20:23
Additionally, I can see the following flooding the `~/Library/Containers/com.docker.docker/Data/vms/0/console.log`:

```
INFO[0194] connecting to tcp+connect://192.168.64.1:1999...
INFO[0194] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable
```

**Comment by wrobelda** [comment] 2021-02-05 20:40
OK, I figured it out. It was LuLu firewall: despite having been disabled in the UI and the VPN not enabled in Network Preferences is still was messing something up. Only actually quitting it helped.

**Comment by mbatesco** [comment] 2021-02-05 20:56
Ran into a similar issue. I ad to stop and quit ExpressVPN to enable Docker to start up completely.

**Comment by mbatesco** [comment] 2021-02-07 17:03
An update, still not resolved.  I have been working with ExpressVPN on working around the issue.  So far, if the VPN is running and connected Docker will not start. 

When running this command, I get the following:
 docker run -d -p 80:80 docker/getting-started
docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused.

Once I disconnect and stop the VPN, the container works and Docker Decktop works.
One workaround but it sucks, set ExpressVPN Stop All Internet Traffic if the VPN disconnects unexpectedly. Ensure the VPN is disconnected and start Docker, start container. Connect VPN. It works. No container will start until VPN is disconnected.

Wondering what else I can look at to help resolve the issue?  Is this a network configuration within Big Sur?

**Comment by djs55** [comment] 2021-02-12 16:38
We fixed a number of startup bugs in the latest version of the tech preview: https://docs.docker.com/docker-for-mac/apple-m1/ Please give it a try and let us know what happens!

**Comment by mbatesco** [comment] 2021-02-13 16:47
Tried the download last night but seemed like it was corrupted. Tried it again this morning and it is working fine.  Testing now and seems like the VPN issues I had have been resolved, not sure if it was a config issue or a change to the VPN config.

**Comment by wrobelda** [comment] 2021-02-15 19:24
Same here, can't reproduce anymore. Can be closed IMHO.

**Comment by davidbarton** [comment] 2021-02-21 21:07
VPN is very old issue reported here https://github.com/moby/moby/issues/35121 and here https://github.com/moby/moby/issues/33925

There is workaround mentioned that works for most linux folks here https://github.com/docker/for-linux/issues/123#issuecomment-346546953. Do you know how to apply same workaround on mac?

**Comment by stephen-turner** [comment] 2021-03-26 16:36
Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

Also we have too many tickets about VPNs, so I'm going to resolve this one as a dupe of #5208.

**Closed by stephen-turner** 2021-03-26 16:36 UTC
Labels: area/m1, version/0.0.0
