### ISSUE TITLE
Write I/O slow in v1.12.1 (MySQL container)

### ISSUE THREAD

**Issue by bobbypriambodo** [docker/for-mac#677] opened 2016-09-20 15:09 UTC
### Expected behavior

I/O has no problem in v1.12.0, upgraded to v1.12.1, expecting same development experience.

### Actual behavior

Experiencing sluggish I/O, particularly on MySQL official container, from container initialization to `CREATE TABLE` and `INSERT` queries.

### Information

Diagnostic ID: 7D6FCC60-7D60-4004-AB81-24B9404FBA13

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/7D6FCC60-7D60-4004-AB81-24B9404FBA13/20160920-213910.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

### Steps to reproduce the behavior

I haven't tested this in another Mac, but here's the way I can reproduce it in mine (tried resetting to factory defaults and still having the same problem):

  1. Pull the latest mysql image: `docker pull mysql`
  2. Run the container: `docker run -p "3306:3306" --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql` (at this point it takes forever until the container is fully initialized, can be over 5 minutes while eating lots of CPU and RAM; it took only 20 seconds tops before)
  3. Connect to it using a mysql client: `mysql -uroot -h127.0.0.1 -P3306 -pmy-secret-pw`
  4. Create a database: `create database docker_test; use docker_test;`
  5. Run a create table query (this is the query that I used):
```
CREATE TABLE IF NOT EXISTS `portal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `site_url` VARCHAR(255) NOT NULL,
  `logo_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;
```

The query outputs: `Query OK, 0 rows affected (3.41 sec)`. 3 seconds is forever in terms of creating table, no? Furthermore, I tried running a MySQL server on my host and ran the same query, and I got: `Query OK, 0 rows affected (0.17 sec)`.

### Additional notes

Although my case is MySQL-centric and I was tempted to create this issue on the MySQL image repo, I decided to post it here since the the container worked perfectly before. I noticed this when I was running my integration tests against the MySQL container; some DB write tests fails due to timing out (over 2000ms) when they used to pass (under 200ms).

* Edit: fixed command to start container; now exposing ports for client to connect to.

**Comment by bobbypriambodo** [comment] 2016-09-21 03:17
I am aware of [the mounted volume issue](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/4) and thought that this might be related to that, but I have doubts since I'm not using any volumes for the MySQL container.

**Comment by bobbypriambodo** [comment] 2016-09-21 08:30
Okay, I've fiddled more with this and since I previously used Docker Machine with Virtualbox, I figured I might as well try to use it again.

$ docker-machine create --driver virtualbox default

```
Running pre-create checks...
(default) Unable to get the latest Boot2Docker ISO release version:  Error getting a version tag from the Github API response.
(default) You may be getting rate limited by Github.
Creating machine...
(default) Unable to get the latest Boot2Docker ISO release version:  Error getting a version tag from the Github API response.
(default) You may be getting rate limited by Github.
(default) Copying /Users/bobbypriambodo/.docker/machine/cache/boot2docker.iso to /Users/bobbypriambodo/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env default
```

As seen above, I (fortunately) failed to get the latest Boot2Docker.iso, so I ended up with old build:

```
$ docker version

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

Using this new machine, starting the MySQL container starts instantly again. My integration tests are passing in 2 seconds.

```
45 passing (2s)
```

I'll try running `docker-machine upgrade` later to see if the issue persists in docker-machine when using v1.12.1.

At least for now I can continue my work using this setup.

**Comment by dsheets** [comment] 2016-09-21 09:09
I believe this is a duplicate of #668. Please feel free to re-open if your issue is substantially different. Thanks for your report!

**Closed by dsheets** 2016-09-21 09:09 UTC

**Comment by bobbypriambodo** [comment] 2016-09-21 09:23
It certainly seems so, sorry for not noticing earlier. Thanks!

**Comment by jkimau** [comment] 2016-10-05 21:57
having the same issue

**Comment by jsnsimpson** [comment] 2016-10-26 10:44
+1

**Comment by snky1987** [comment] 2016-10-26 13:43
+1

**Comment by andreyors** [comment] 2016-11-01 19:11
+1

**Comment by Chekote** [comment] 2016-11-11 22:47
Been having the same issue here. I just updated to 1.12.3 and it's no better. My entire Dev team is stuck on 1.12.0 because of this.

**Comment by ijc25** [comment] 2016-11-14 14:21
Please subscribe to #668 for more info on this issue, including [a workaround](https://github.com/docker/for-mac/issues/668#issuecomment-250406582) which will restore the 1.12.0 behaviour on newer versions.
