### ISSUE TITLE
qcow2 file so large，how to clean up?

### ISSUE THREAD

**Issue by AntSworD** [docker/for-mac#853] opened 2016-10-27 03:57 UTC
Problem: Docker.qcow2 to large
`109632640 -rw-r--r--  1 ant  staff    52G 10 27 11:50 /Users/ant/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`

How to clean up? my mbp only have 120GB space, this file take half of my disk space

`docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 150
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 219
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: ULJL:5K64:S3NQ:UNE7:JLMV:4LEK:GCVA:GVQC:MXQL:MWZV:SLGK:FEPC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-10-27T03:49:04.402901131Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

`docker version`

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by xiaods** [comment] 2016-11-02 09:41
same here.

**Comment by samoht** [comment] 2016-11-03 22:17
Closing as a duplicate of #371

**Closed by samoht** 2016-11-03 22:17 UTC
Labels: status/0-triage
