### ISSUE TITLE
Cannot Install: Request failed: GET /analyse/startup-failure failed: no response

### ISSUE THREAD

**Issue by salvolpe** [docker/for-mac#4986] opened 2020-10-09 22:49 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 120E8F2C-ED04-4E00-BB52-AD95FA1CCE54/20201015185025

![image](https://user-images.githubusercontent.com/37944330/95637505-df551c80-0a5f-11eb-8fe3-2ffd479b107d.png)

### Expected behavior

Install Docker Desktop

### Actual behavior

Unable to install Docker Desktop

### Information

  - macOS Version: 10.14.6

I have tried uninstalling and reinstalling several times with both versions (Stable and Edge)

Both initially present with: 
` Request failed: GET /analyse/startup-failure failed: no response`

Then after "Resetting to factory default settings," the error I get is:
`mkdir /Users/sal/.docker/run: permission denied`

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Downloaded `.dmg` files from Docker website. Neither of them worked.

**Comment by devin6391** [comment] 2020-10-12 06:26
I am also getting the same error. For me version 2.3.0.4 is working, but anything after that is showing me error.

And like the original post, my diagnosis is also stuck.

<img width="680" alt="docker issue" src="https://user-images.githubusercontent.com/6758230/95712169-f4a99100-0c81-11eb-81bd-bffe07dd3308.png">

**Comment by devin6391** [comment] 2020-10-13 15:50
Hey, I changed my region from India to United States in Mac.
Also changed the language from English(India) to English(US). And restarted, reinstalled docker. It got fixed.

I think there's a bug with Docker regarding timezone and region, that should be fixed.

**Comment by davidxianggao** [comment] 2020-10-13 20:54
I am having the same issue on my mac (Catalina 10.15.7) on the first-time running of Docker Desktop. The file of Docker.img is up to date, which I downloaded today.

**Comment by ebriney** [comment] 2020-10-15 10:12
Hello, can you try to run diagnostics from a shell (so we will know at least where it's stuck):
`/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload`
If it succeeds put the diagnostics ID please.

On the error itself can you check if `com.docker.backend` is running.
If it's running can you try:
`curl --unix-socket ~/Library/Containers/com.docker.docker/Data/docker-api.sock http:/localhost/analyse/startup-failure`

Ultimately you can zip the logs and put it there:
`zip -r logs.zip ~/Library/Containers/com.docker.docker/Data/log`

Thanks for your help.

**Comment by salvolpe** [comment] 2020-10-15 18:54
@ebriney I just appended the Diagnostic ID to the start of this issue

When I ran the `curl` command, I got this response:
`{"reason":"","detail":"","action":0}`

Below I've attached the `logs.zip` that you referenced
[logs.zip](https://github.com/docker/for-mac/files/5387176/logs.zip)

**Comment by ebriney** [comment] 2020-10-16 08:21
thanks @salvolpe

**Comment by ebriney** [comment] 2020-10-16 09:10
@salvolpe can you do `ls -la ~/.docker` to check rights because it's the root cause of the failure, we failed to create a socket in there and so cancel the whole startup.

When you have done it, you can do `sudo rm -rf ~/.docker` to remove the folder, it will recreate it with default configuration on next startup (it cannot be cleaned in the reset to default because of permission denied that is done with user rights).

**Comment by salvolpe** [comment] 2020-10-16 17:32
@ebriney When I ran `ls -la ~/.docker`, the response was:
`ls: .docker: Permission denied`

But then I ran the `sudo rm` that you included and now Docker opens just fine

**Comment by ebriney** [comment] 2020-10-19 08:09
Sorry, you should have run `sudo ls -la ~/.docker` to get the rights on the folder.

Happy that it fixes your setup though I don't know how this folder has been created with root user (I suppose).

We will add instructions in the error dialog, it's pretty easy to detect.

**Comment by Morfild** [comment] 2020-10-19 12:47
I have the same issue, mac os 10.15.7. I tried to remove ~/.docker folder and after setting the rights on the folder still doesn't work...

**Comment by ebriney** [comment] 2020-10-19 13:36
@Morfild can you upload a diagnostic and put ID there please.
Is it the same symptoms?

**Comment by Morfild** [comment] 2020-10-19 13:50
@ebriney I'm able to install docker desktop (I tried to reinstall), it takes a few minutes to start but fails with the error. Happen spontaneously after mac os reboot, used docker for a long time before. It seems to freeze during "Diagnosing...", so I can't upload the diagnostic

**Comment by ebriney** [comment] 2020-10-19 13:53
Even with above instructions @Morfild? (https://github.com/docker/for-mac/issues/4986#issuecomment-709080143)

**Comment by Morfild** [comment] 2020-10-19 13:58
@ebriney It works in this way! Diagnostics ID: ADA59406-85A8-42BA-9861-8EFC497731DC/20201019135500

**Comment by ebriney** [comment] 2020-10-19 14:11
Thanks! I check your diags.

**Comment by ebriney** [comment] 2020-10-19 14:44
Can you try `curl --unix-socket ~/Library/Containers/com.docker.docker/Data/docker-api.sock http:/localhost/ping` @Morfild when the app is launched (you can do it as soon as the whale is animated, you don't have to wait for 2 minutes).
`com.cocker.backend` should return `pong` (that's where it failed in the diag and I have no clues why, I just want to check it worked with curl).

**Comment by Morfild** [comment] 2020-10-20 06:30
@ebriney This command returns `curl: (7) Couldn't connect to server`, it makes no difference whether the application starts or not

**Comment by ebriney** [comment] 2020-10-20 15:42
Ok, thanks for your help, I will close the issue. Feel free to open a new one if you find new bugs.

**Closed by ebriney** 2020-10-20 15:42 UTC
Labels: version/2.4.0.0

**Comment by muratogul** [comment] 2020-11-02 07:47
I had exact same issue on MacOS. The following has been resolved the issue. You may want to try this `on your own risk`.

1. uninstall pre-installed Docker application.

2. Delete the following files and directories after baking them up in case you lost some critical data because of deletion.

3. Install fresh Docker.


/Library/PrivilegedHelperTools/com.docker.vmnetd
/Library/LaunchDaemons/com.docker.vmnetd.plist
/usr/local/lib/docker
~/.docker
~/Library/Application Support/Docker Desktop
~/Library/Preferences/com.docker.docker.plist
~/Library/Saved Application State/com.electron.docker-frontend.savedState
~/Library/Group Containers/group.com.docker
~/Library/Logs/Docker Desktop
~/Library/Preferences/com.electron.docker-frontend.plist
~/Library/Cookies/com.docker.docker.binarycookies
