### ISSUE TITLE
Date synchronisation when Mac wakes up after sleeping

### ISSUE THREAD

**Issue by inkuzmin** [docker/for-mac#1086] opened 2016-12-27 15:30 UTC
### Expected behavior
Date inside the container should be the same as the host date as it is important for many protocols.

### Actual behavior
Docker.app doesn't update date inside the container when Mac wakes up after sleeping.

### Steps to reproduce the behavior

  1. Start the container with Ubuntu
  2. Check date inside the container
  3. Put Mac on sleep
  4. Wake up Mac
  5. Check date inside the container.

**Comment by justincormack** [comment] 2017-01-03 11:00
This is a duplicate of https://github.com/docker/for-mac/issues/17 - this generally seems to happen if your Mac does not have a working ntp setup, see discussion in the issue.

**Closed by justincormack** 2017-01-03 11:00 UTC
