### ISSUE TITLE
Containers tab not showing current state of containers

### ISSUE THREAD

**Issue by DuckThom** [docker/for-mac#6390] opened 2022-07-05 11:37 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 83365C73-D17A-4032-8408-BEA3888B7EBC/20220705113001

### Expected behavior

Container status is updated after starting/stopping a container via the UI

### Actual behavior

All containers show as being "Exited" even though the Redis container is running

![image](https://user-images.githubusercontent.com/6512901/177317638-4488af73-019a-430b-858f-3961e5b9094e.png)

### Information

  - macOS Version: 12.4 (21F79)
  - Intel chip or Apple chip: Apple M1 Max
  - Docker Desktop Version: 4.10.0 (82025)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. If Docker Desktop is running, do "Quit Docker Desktop"
  2. Start Docker
  4. Start a container
  5. There's a 50/50 chance the container will not show up as running, if it's not, continue
  6. Run `docker ps` in a terminal
  7. The container is actually running

**Comment by nicks** [comment] 2022-07-05 20:27
thanks for the report! I'm going to mark this as a duplicate of https://github.com/docker/for-win/issues/9401 to centralize discussion there, because I'm pretty sure it's the same underlying issue.

**Closed by nicks** 2022-07-05 20:27 UTC
Labels: version/4.10.0, version/12.4
