### ISSUE TITLE
14DD065F-AFAF-4D2E-833A-08847468832E/20201007210244

### ISSUE THREAD

**Issue by begrafx** [docker/for-mac#4979] opened 2020-10-07 22:06 UTC
I am getting THIS consistently. 

`ERROR: for ddev-baseline-db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60) 
 
ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60) 
An HTTP request took too long to complete. Retry with --verbose to obtain debug information. 
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60). 
Failed to start baseline: Failed to run docker-compose [-f /Volumes/Big Box/wbmg-dev/baseline/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 18907ee75ab2
Step 3/6 : ARG username
 ---> Using cache
 ---> 664150a25c23
Step 4/6 : ARG uid
 ---> Using cache
 ---> 725a8ac920ef
Step 5/6 : ARG gid
 ---> Using cache
 ---> 0fb76e362f38
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 5560122c1fbd

Successfully built 5560122c1fbd
Successfully tagged drud/ddev-dbserver-mariadb-10.2:v1.15.1-baseline-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> e65bac01b703
Step 3/6 : ARG username
 ---> Using cache
 ---> 90ec9f2071eb
Step 4/6 : ARG uid
 ---> Using cache
 ---> cc506e13235e
Step 5/6 : ARG gid
 ---> Using cache
 ---> 60abb269ed04
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 0b659b4de9b5

Successfully built 0b659b4de9b5
Successfully tagged drud/ddev-webserver:v1.15.3-baseline-built
', stderr='Building db
Building web
Creating ddev-baseline-db ... 

ERROR: for ddev-baseline-db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).' `

This is in spite of the fact that I have manually entered `COMPOSE_HTTP_TIMEOUT=300` multiple times.

  - [X] I have tried with the latest version of my channel (Stable or Edge) Software states "You're up-to-date! Docker 2.4.0.0 is currently the newest version available.

  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
14DD065F-AFAF-4D2E-833A-08847468832E/20201007210244
### Information

  - macOS Version: MacOS Mojave 10.14.6

### Diagnostic logs

```
Docker for Mac: version... 2.4.0.0

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-10-08 09:25
Thanks for the report. I believe this is a dupe of #4957, so I'll close this copy.

**Closed by stephen-turner** 2020-10-08 09:25 UTC
Labels: version/2.4.0.0
