### ISSUE TITLE
3.5.1 update never seems to work

### ISSUE THREAD

**Issue by dcblack** [docker/for-mac#5841] opened 2021-07-14 00:37 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 30FD7359-EF98-49F8-B64D-DCF737AD9648/20210714003148

### Expected behavior
Updates should install
### Actual behavior
I am on Docker Desktop 3.3.0 and it offers to update to version 3.5.1 on a daily basis. I accept, but it never seems to work as I set the exact option later.
### Information

  - macOS Version: Catalina 10.15.7 (install updates as they appear)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.0

### Steps to reproduce the behavior

  1. Just wait for the update notice and click Install & Restart
  2. ...

**Comment by iandees** [comment] 2021-07-14 02:46
I'm stuck on the same Docker version, macOS 11.4 for me.

**Comment by StefanScherer** [comment] 2021-07-14 13:54
Hi @dcblack 
Thank you for the report and diagnostics. It seems like a dupe of #5677 
We're investigating the issue, but couldn't reliably reproduce it on our side yet.
What others have reported as a workaround is just to Quit Docker Desktop and then after some seconds start it again. This often finishes the update.
If you then still encounter the problem the next best way would be to download the latest version from https://docs.docker.com/docker-for-mac/install/
I'm going to close this ticket, but feel free to comment how it worked for you.

**Closed by StefanScherer** 2021-07-14 13:54 UTC
Labels: version/3.3.0

**Comment by iandees** [comment] 2021-07-14 14:51
When I quit via menu bar, it pinwheeled for ~10 seconds and then exited. I waited 5 minutes or so and opened Docker.app again. It finished the upgrade and now I'm on 3.5.1.
