### ISSUE TITLE
error after restart mc

### ISSUE THREAD

**Issue by ryman1981** [docker/for-mac#120] opened 2016-08-04 04:06 UTC
### Information

Diagnostic ID: 92601CD8-319D-4B94-9B2F-B557847994C1
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/liurui/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/92601CD8-319D-4B94-9B2F-B557847994C1/20160804-120333/qemu-img-check.stdout 2> /tmp/92601CD8-319D-4B94-9B2F-B557847994C1/20160804-120333/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment] 2016-08-09 02:11
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:11 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
