### ISSUE TITLE
Cannot change ownership of read-only file in mounted volume

### ISSUE THREAD

**Issue by sameersbn** [docker/for-mac#633] opened 2016-09-15 12:55 UTC
### Expected behavior
Ownership of file should change.

### Actual behavior
Permission denied error displayed by `chown` command

### Information

Diagnostic ID: C6AC4F0F-8770-4592-8AB1-E34D52436EEF
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

```bash
$ mkdir -p sandbox && cd sandbox
$ docker run -it --rm -v $PWD:/data --workdir /data ubuntu:14.04 bash
$ touch sample && chmod 444 sample && ls -la
total 5
drwxr-xr-x  3 root root  102 Sep 15 12:28 .
drwxr-xr-x 35 root root 4096 Sep 15 12:27 ..
-r--r--r--  1 root root    0 Sep 15 12:28 sample
$ chown daemon:daemon sample
chown: changing ownership of 'sample': Permission denied
```

The ownership of the file can however be changed by first changing the mode to `readwrite` mode:

```bash
$ chmod 755 sample
$ chown daemon:daemon sample
$ ls -la sample
total 5
drwxr-xr-x  3 root   root    102 Sep 15 12:51 .
drwxr-xr-x 35 root   root   4096 Sep 15 12:51 ..
-rwxr-xr-x  1 daemon daemon    0 Sep 15 12:51 sample
```

**Comment by dsheets** [comment] 2016-09-15 20:29
This is a (clearer) duplicate of #117 and #263. Thanks for the report. We hope to have a fix out soon.

**Comment by jakajancar** [comment] 2016-09-26 06:14
@dsheets Can you explain what the fix will be? Will you just start saving permissions in OS X extended attributes, or is it going to also remove (uid/gid = current uid/gid)?

**Comment by jakajancar** [comment] 2016-10-11 04:08
Anything new here?

**Comment by dsheets** [comment] 2016-10-26 10:48
This should be fixed in the just-released Beta 29. Sorry for the delay in resolving the issue -- we had a couple of false starts on the design but now we use an ACL entry to make xattrs (containing ownership metadata) behave like inode metadata in most circumstances. Please give it a try and let us know how it works (or doesn't) for you. I'm going to close this issue but if you find related problems, please feel free to re-open. If you find un-related problems, please open a new issue. :-)

Thanks for using Docker for Mac!

**Closed by dsheets** 2016-10-26 10:48 UTC
Labels: area/mounts, kind/bug, osx/10.11.x, status/4-fix-released-beta, version/1.12.0-a
