### ISSUE TITLE
ping any address working

### ISSUE THREAD

**Issue by dbainbri-ciena** [docker/for-mac#758] opened 2016-10-06 23:22 UTC
### Expected behavior
ping would fail

### Actual behavior
ping succeeded

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
767CDAAD-7BF7-4FA6-BC3F-E170518B33FC, but dialog said it couldn't upload
 

### Steps to reproduce the behavior

  1. docker run -ti alpine ash
  2. ping 1.1.1.1 # assume 1.1.1.1 isn't valid in your network

**Comment by yallop** [comment] 2016-10-07 09:01
Thank you for the report.  I believe this is a duplicate of #57.

**Closed by yallop** 2016-10-07 09:01 UTC
