### ISSUE TITLE
Docker execution gets terminated with Error response from daemon: dial unix  ..

### ISSUE THREAD

**Issue by villelaitila** [docker/for-mac#369] opened 2016-08-19 11:16 UTC
### Expected behaviour
When running `docker exec -ti my container bash` and then running some python script code inside the container, the script should be executed normally.

### Actual behavior
After running some python script code inside the container, the execution gets terminated and the container dies with error message Error response from daemon: dial unix  ..

At some runs, the execution goes longer and sometimes it crashes right in the beginning.

The output in the terminal is:

`  
File "/mycode/foo/bar.py", line 21, in run  
  File "/usr/lib/python3.5/codecs.py", line 748, in __exit__
    self.stream.close()
OSError: [Errno 107] Transport endpoint is not connected
root@2dfd6746e84c:/mycode/foo# Error response from daemon: dial unix /Users/user/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
`

### Information

Diagnostic ID: 2B863BCC-5441-4EF3-822D-3AFC8DF3E5E0
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. docker exec -ti my container bash
2. execute some code inside container (tested only with python and perl scripts)
3. wait for the Error response from daemon

**Comment by dsheets** [comment] 2016-08-19 13:26
This is a duplicate of #18. How much RAM do you have allocated to Docker in `Preferences...`?

**Closed by dsheets** 2016-08-19 13:26 UTC
