### ISSUE TITLE
I am stuck on Docker for Mac 3.3.1

### ISSUE THREAD

**Issue by dharmab** [docker/for-mac#5780] opened 2021-06-22 21:02 UTC
- [ ] ~I have tried with the latest version of Docker Desktop~ I cannot update to the latest version.
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9AAA988D-1741-4C7B-B3CA-922769AAF099/20210622205951

### Expected behavior

When I click the update and restart button, I am updated to a newer version of Docker for Mac.

### Actual behavior

When I click the update and restart button, Docker restarts but still shows version 3.3.1 in the About Docker pane.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. Click the "Update and restart" button in the top bar icon.

**Comment by StefanScherer** [comment] 2021-06-24 08:19
Hi @dharmab 
Thank you for the report. Oh that's sad, and we have some other users reporting a similar problem. I'll close this ticket as it's a duplicate of #5677 
As a workaround stop Docker Desktop and download the latest version (3.5.0) from https://docs.docker.com/docker-for-mac/install/
We're still looking to reproduce this situation and fully understand why this happens for some users.

**Closed by StefanScherer** 2021-06-24 08:19 UTC
Labels: version/3.3.1
