### ISSUE TITLE
Bazel not working for AMD64 builds on M1 MacBook Pro

### ISSUE THREAD

**Issue by vidheyoza** [docker/for-mac#5918] opened 2021-08-18 21:50 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Bazel starts server and executes build successfully. 

### Actual behavior

Build fails with error: 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Opening zip "/proc/self/exe": lseek(): Bad file descriptor
[FATAL 21:37:43.679 src/main/cpp/archive_utils.cc:51] Failed to open '/proc/self/exe' as a zip file: (error: 9): Bad file descriptor
```

### Information

  - macOS Version: Big Sur 11.4
  - Intel chip or Apple chip: Apple Silicon M1
  - Docker Desktop Version: 3.6.0

I understand that the warning states how `amd64` images don't emulate well on `arm64` machines, but I have to default to this since I use TensorFlow, and it has no way of building on `arm64` containers. This docker container works on older Intel MacBooks and on other Linux machines in our team, but not on the M1 MacBook. 

There was an older issue on this topic but it was closed without any clear explanation on how to move forward from here. Either I need an ARM64 Ubuntu image with a particular TensorFlow and Bazel installation to begin with, or I need a way to run Bazel on an AMD64 Ubuntu image. Or I can also build Bazel on this platform through Rosetta 2. 

But I don't know how to execute any of these ideas. 

### Steps to reproduce the behavior

  1. Setup Ubuntu 18.04 AMD64 container with Bazel install through script. 
  2. Run Bazel build
  3. Face the error shown above.

**Comment by stephen-turner** [comment] 2021-08-19 08:23
Unfortunately I'm going to close this ticket because it's not a bug in Docker Desktop, it's something that needs changing in the code inside the container, and it's not possible for me to know what. You might be better to ask in the Bazel community.

**Closed by stephen-turner** 2021-08-19 08:23 UTC
