### ISSUE TITLE
Cannot open Docker

### ISSUE THREAD

**Issue by eergecen** [docker/for-mac#2526] opened 2018-01-28 23:45 UTC
When I try to run Docker, I get an error about /usr/local/lib/docker. The error code is ECF5B10C-25ED-4AAE-8A50-20FD49470597.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment] 2018-01-29 14:50
Dupe of #2527.

**Closed by akimd** 2018-01-29 14:50 UTC
