### ISSUE TITLE
17.12.0-ce-rc2-mac41 failed to start

### ISSUE THREAD

**Issue by johnflavin** [docker/for-mac#2315] opened 2017-12-13 20:12 UTC
### Expected behavior
I updated docker to the latest beta version 17.12.0-ce-rc2-mac41 (using the update prompt in the app). Upgrade seemed to go fine. I restarted the app. 

An error message comes up that one of the components failed to start.
```
Fatal Error

com.docker.supervisor failed to start
Exit code 1
```

### Actual behavior
App can start without errors.

### Information

Diagnostic ID: 7FD8482B-5F8C-49E2-A47B-F76B6D9B2007

```
Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/7FD8482B-5F8C-49E2-A47B-F76B6D9B2007/20171213-140634.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/flavin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/flavin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/flavin/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by johnflavin** [comment] 2017-12-13 20:18
Resetting to "factory defaults" fixed the problem.

**Comment by danielpcox** [comment] 2017-12-13 20:48
I also had this problem, with the same error. Resetting fixed it for me too. Thanks for the tip.

**Comment by MartijnWelker** [comment] 2017-12-14 07:54
Seems like the same issue as #2317

**Comment by gtardif** [comment] 2017-12-14 09:57
Closing as a duplicate of #2317 (See #2317 to fix settings without full reset)

**Closed by gtardif** 2017-12-14 09:57 UTC
