### ISSUE TITLE
VirtioFS causes intermittent failures with Rust

### ISSUE THREAD

**Issue by markedwards** [docker/for-mac#7059] opened 2023-11-04 12:39 UTC
### Description

This is a duplicate of #6511 which for some reason was just totally ignored.

In my case I intermittently get the following sort of errors when compiling Rust using `cargo build` or `cargo run`:

```console
/usr/bin/ld: cannot find /workspaces/rust/target/debug/deps/rust_sandbox-52f451132105a34b.287q8y3urr1rjxzw.rcgu.o: No such file or directory
```

Switching from VirtioFS to osxfs eliminates the errors, but I don't want to do this.

### Reproduce

1. spin up a Rust image (https://hub.docker.com/_/rust)
2. `cargo new`
3. `cargo build`

Step 3 fails intermittently.

### Expected behavior

Compilation should never produce these kinds of errors.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/markedwards/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/markedwards/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/markedwards/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/markedwards/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/markedwards/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/markedwards/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/markedwards/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/markedwards/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.758GiB
 Name: linuxkit-1637e9d1e2c1
 ID: 66439519-58e4-4975-9f07-998f86ae4ebd
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 197
  Goroutines: 258
  System Time: 2023-11-04T12:29:41.338283877Z
  EventsListeners: 11
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

4E3078F8-1424-4C4D-9526-93439747F1F3/20231104123413

**Comment by richardpringle** [comment] 2023-11-15 01:33
Seems like this is a concurrency issue of some sort. 

When I run `until cargo build; do echo retry; done;`, eventually my builds will pass. Seems like a dependent compilation step starts but can't find the files that were supposed to be created as an artifact of the previous step. Then, when running `cargo build` again in the next iteration of the `until` loop, it can find the file. 

If you are unfamiliar, cargo/rustc will save outputs from previous steps so you aren't starting from scratch every time

**Comment by richardpringle** [comment] 2023-11-15 01:41
Seems like other had similar issues
https://github.com/docker/for-mac/issues/6511

**Comment by ShaneMurphy2** [comment] 2023-11-21 19:29
Seeing this as well using [cross](https://github.com/cross-rs/cross). Can confirm repeated builds eventually succeed, and that disabling VirtioFS seems to fix it.

**Comment by ShaneMurphy2** [comment] 2023-11-21 20:20
I have some time I can devote to this, but I have no idea how to even begin to debug it. If any maintainers have some tips I'm happy to help.

**Comment by richardpringle** [comment] 2023-11-22 03:36
For Rust, the workaround is to put your `CARGO_TARGET_DIR` in a directory that isn't mounted. Not ideal in some cases, but works for me.

**Comment by mxfactorial** [comment] 2024-01-20 04:45
https://github.com/cross-rs/cross/issues/1272

**Comment by dgageot** [comment] 2024-02-13 10:43
Hi everyone, the issue is fixed on our side, it'll ship with Docker Desktop 4.28.0.

**Comment by dgageot** [comment] 2024-02-26 18:53
Hi everyone, could you give a try to [Docker Desktop 4.28](https://docs.docker.com/desktop/release-notes/#4280)? It should be fixed now.

**Comment by ShaneMurphy2** [comment] 2024-02-26 19:20
Can confirm it appears to be fixed! Out of curiosity, was the root cause anything interesting?

**Comment by ShaneMurphy2** [comment] 2024-02-26 19:58
> > Can confirm it appears to be fixed! Out of curiosity, was the root cause anything interesting?
> 
> It's an issue in Apple's virtiofs implementation that requires a workaround. Roughly, macOS fails to transactionally increment the link count on hardlinks. If I understood correctly, we have to avoid caching entries for files with more than one nlink.

Interesting, must have been tough to track down.

**Comment by dgageot** [comment] 2024-02-26 20:02
All the credits goes to @djs55

**Comment by dgageot** [comment] 2024-02-27 06:59
Thanks for the feedback, I'm closing this issue, then

**Closed by dgageot** 2024-02-27 06:59 UTC
Labels: status/triage, area/VirtioFS, version/4.25.0, version/4.26.1, version/4.27.2

**Comment by dgageot** [comment] 2024-02-27 14:57
> I'm still getting intermittent failures trying to build https://github.com/ava-labs/firewood/ in a docker-desktop dev-environment with VirtioFS where the target-directory inside a volume mounted directory.
> 
> I'm not suggesting you necessarily re-open the issue, but maybe point to the workarounds if anyone has issues like this? I'm more than happy with the workaround.

cc @djs55

**Comment by mxfactorial** [comment] 2024-02-27 22:52
cross issue resolved

rebuild your devcontainer @richardpringle

**Comment by richardpringle** [comment] 2024-02-28 14:53
> cross issue resolved
> 
> rebuild your devcontainer @richardpringle

@mxfactorial, I'm not using cross. 

What does rebuilding the container do? I've restarted the whole engine that controls how the volume is mounted.

**Comment by mxfactorial** [comment] 2024-02-28 18:03
announcing cross issue resolved intended everyone

for your use case, if you created the volume with the devcontainer before 4.28, then create again with 4.28

**Comment by richardpringle** [comment] 2024-02-29 19:48
>announcing cross issue resolved intended everyone

👍 

>for your use case, if you created the volume with the devcontainer before 4.28, then create again with 4.28

What does rebuilding the container do? From my (limited) understanding, it wasn't the way the container was built that was causing the problem. Any insights @dgageot?

**Comment by mxfactorial** [comment] 2024-03-01 00:19
you can help others @richardpringle by reporting whether your issue remains after receiving the previous 2 insights:

1. "we have to avoid caching entries for files with more than one nlink"
2. "if you created the volume with the devcontainer before 4.28, then create again with 4.28"
