### ISSUE TITLE
docker pull: Error response from daemon: Get "https://registry-1.docker.io/v2/": unexpected EOF

### ISSUE THREAD

**Issue by marcusmonteirodesouza** [docker/for-mac#6704] opened 2023-01-25 19:27 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3DFC39C1-C1EF-45B0-8CAD-F4933D7579EB/20230125191301

### Expected behavior

`docker pull` pulls an image from the [Docker Hub](https://hub.docker.com/) registry.

### Actual behavior

`docker pull` fails with the message: 

> Error response from daemon: Get "https://registry-1.docker.io/v2/": unexpected EOF

### Information

The error above happens when trying to pull any image. The issue looks similar to #6528 and #6623.

  - macOS Version: 13.2
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.16.2 (95914)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Try to pull any image from [Docker Hub](https://hub.docker.com/). For example, `docker pull postgres:14.6`.

**Comment by dthauvin** [comment] 2023-01-25 22:20
Same issue , with debug mode i get the following  log from `~/Library/Containers/com.docker.docker/Data/log/vm/dockerd.log `


[2023-01-25T22:18:49.966487110Z][dockerd][I] time="2023-01-25T22:18:49.966280182Z" level=debug msg="Calling HEAD /_ping"
[2023-01-25T22:18:49.973438359Z][dockerd][I] time="2023-01-25T22:18:49.973221757Z" level=debug msg="Calling POST /v1.41/containers/create"
[2023-01-25T22:18:49.973730093Z][dockerd][I] time="2023-01-25T22:18:49.973493228Z" level=debug msg="form data: {\"AttachStderr\":false,\"AttachStdin\":false,\"AttachStdout\":false,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":null,\"ExposedPorts\":{\"80/tcp\":{}},\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"CgroupnsMode\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"DeviceRequests\":null,\"Devices\":[],\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"KernelMemoryTCP\":0
[2023-01-25T22:18:49.978202989Z][dockerd][I] time="2023-01-25T22:18:49.977994697Z" level=debug msg="Calling GET /v1.41/info"
[2023-01-25T22:18:50.314912715Z][dockerd][I] time="2023-01-25T22:18:50.314683564Z" level=debug msg="Calling POST /v1.41/images/create?fromImage=docker%2Fgetting-started&tag=latest"
[2023-01-25T22:18:50.375183153Z][dockerd][I] time="2023-01-25T22:18:50.374941265Z" level=debug msg="Trying to pull docker/getting-started from https://registry-1.docker.io v2"
[2023-01-25T22:18:50.383795870Z][dockerd][I] time="2023-01-25T22:18:50.383598402Z" level=warning msg="Error getting v2 registry: Get \"https://registry-1.docker.io/v2/\": unexpected EOF"
[2023-01-25T22:18:50.383827413Z][dockerd][I] time="2023-01-25T22:18:50.383624065Z" level=info msg="Attempting next endpoint for pull after error: Get \"https://registry-1.docker.io/v2/\": unexpected EOF"
[2023-01-25T22:18:50.385976936Z][dockerd][I] time="2023-01-25T22:18:50.385686264Z" level=error msg="Handler for POST /v1.41/images/create returned error: Get \"https://registry-1.docker.io/v2/\": unexpected EOF"

**Comment by rfay** [comment] 2023-01-27 18:19
This is usually a networking problem; make sure you have temporarily disabled any firewall and VPN when testing.

**Comment by marcusmonteirodesouza** [comment] 2023-01-28 00:26
@rfay My firewall is inactive and I don't use a VPN. Also, in this case, after some unsuccessful attempts to solve the error, I completely erased my hard-drive, installed macOS from scratch, and the first thing that I did was to install Docker Desktop to test it. I got the same error.

**Comment by rfay** [comment] 2023-01-28 01:40
@marcusmonteirodesouza it's almost certainly network trouble then. You can test it with `curl -I` like this. You should get an "unauthorized" like I have here:

```
$ curl -I https://registry-1.docker.io/v2/
HTTP/1.1 401 Unauthorized
content-type: application/json
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
date: Sat, 28 Jan 2023 01:39:06 GMT
content-length: 87
strict-transport-security: max-age=31536000
```

**Comment by marcusmonteirodesouza** [comment] 2023-01-28 03:05
@rfay Yes, I got this result:

```
➜  ~ curl -I https://registry-1.docker.io/v2/
HTTP/1.1 401 Unauthorized
content-type: application/json
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
date: Sat, 28 Jan 2023 03:03:54 GMT
content-length: 87
strict-transport-security: max-age=31536000
```

What does it mean? Can I do something about this?

**Comment by rfay** [comment] 2023-01-28 03:10
I don't have much to offer you, but I would do these things:

1. `docker logout`
2. `docker pull busybox` - if that works, it means basically everything is working
3. Try a different network. Go to your neighbor's network, or a library, etc. Use a phone hotspot. 

People all over the world are able to `docker pull busybox` successfully with dozens of different versions of docker Desktop and on many kinds of networks. 

If you can't sort it out though, you may want to try [Colima](https://github.com/abiosoft/colima) as a different point of view.

**Comment by dannylwe** [comment] 2023-01-28 12:47
I am having the exact same issue as @marcusmonteirodesouza, has someone found a solution/work around?

**Comment by rfay** [comment] 2023-01-28 17:29
Here are some things you folks can do to help the Docker folks to figure out what's going on.

1. Please use the same command every time. Let's say `docker pull busybox`, so that everybody is dealing with the same size image, etc.
2. See if it has to do with a particular network you're on. Sometimes MTU on a network segment can cause things like this. Go to a coffee shop, or use your phone's hotspot, or something.
3. See if it has to do with what version of Docker Desktop you have. You can get all versions of DD from https://docs.docker.com/desktop/release-notes/ - try to sort out whether this happened with a particular version.
4. See if it only has to do with hub.docker.com, try pulling an image from another repo. Try `docker pull ghcr.io/traefik/hub-agent-traefik`, which pulls from GitHub's container registry. Does that work?
5. Are you using the `docker` client provided by Docker Desktop? If you are, then `ls -l $(which docker)` will look like this:
    ```
    $ ls -l $(which docker)
    lrwxr-xr-x  1 root  staff  54 May 18  2022 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
    ```
6. With current Docker Desktop, the docker client's version should be `Docker version 20.10.22, build 3a2c30b`. If you happen to have a different docker client in your path (like from homebrew) it could affect this.
7. Do you have the problem if you use [Colima](https://github.com/abiosoft/colima)? If so, it likely has nothing to do with Docker Desktop (but might still have to do with docker client, try using the homebrew docker client, `brew install docker`)

Without effort like this on your part, this might never be sorted out, but with these tools you might be able to get a solution.

(I'm not associated with Docker, but have lots of experience here. I'm the maintainer of [DDEV](https://github.com/drud/ddev), which uses lots of versions of docker in lots of contexts.)

**Comment by marcusmonteirodesouza** [comment] 2023-01-28 18:32
@rfay Thank you for all those instructions. These are the results:

1. Ok, from now on I will try with `docker pull busybox` unless instructed otherwise.
2. I used my phone hotspot connected to a 5g network instead of my wi-fi. Same error.
3. I did not do it yet. I can get back here when I'm able to do so.
4. Did not work. Results in `Error response from daemon: Get "https://ghcr.io/v2/": unexpected EOF`
5. Yes. It results in `/usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker`
6. I'm using the mentioned version. The output from `docker version` is:
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
7. After uninstalling Docker Desktop and installing [colima](https://github.com/abiosoft/colima), `docker pull busybox` worked:
```
Using default tag: latest
latest: Pulling from library/busybox
205dae5015e7: Pull complete
Digest: sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```

**Comment by rfay** [comment] 2023-01-28 18:39
@marcusmonteirodesouza that should help them. That sure does imply that the problem is in fact with DD. And I assume that you're using the same docker client (the one that comes with DD) for the Colima test?

BTW everybody, you don't have to uninstall DD to do the Colima test.

**Comment by marcusmonteirodesouza** [comment] 2023-01-28 18:56
@rfay For the colima test I uninstalled Docker Desktop first. I used the client installed with `brew install docker`.

**Comment by rfay** [comment] 2023-01-28 18:58
Ah, you'll want to try it with the Docker Desktop version of the docker client, to see if it's specifically the client. (I use the DD-installed client with Colima regularly, nothing wrong with that)

**Comment by marcusmonteirodesouza** [comment] 2023-01-28 19:14
@rfay I ran `brew uninstall docker`, then I installed Docker Desktop with `brew install --cask docker`. With [colima](https://github.com/abiosoft/colima), `docker pull busybox` worked.

**Comment by rfay** [comment] 2023-01-28 19:34
Yeah, that seems to imply it is in fact a Docker Desktop problem.

**Comment by g-deoliveira** [comment] 2023-02-01 03:34
Had the same issue:

1. `docker pull busybox` resulted in 
```
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": unexpected EOF
```
2. network: used my phone's hotspot, same issue
3. my version of docker desktop did not change (4.16.2), but this happened after I upgraded to Mac OS Venture 13.2
4. I did not try this
5. running this `$ ls -l $(which docker)` returned this:
```
lrwxr-xr-x  1 root  admin  54 Mar 31  2022 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
```
6. running `docker version` returned this:
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
7. I used Colima and it worked!

Thank you @rfay this workaround

**Comment by rluta** [comment] 2023-02-01 15:17
Since I also encounter this issue on my corporate laptop (but not my personal laptop) I've collected some diagnostic information about the issue running a clean reinstall + factory reset of Docker Desktop 4.16.2 on an Intel MacBook Pro (MacOS 11.7.3)

If I connect to the `$HOME/Library/Containers/com.docker.docker/Data/vms/0/console.sock`, I see this message repeating every few seconds:
```
[2023-02-01T11:23:53.673027448Z][vpnkit-bridge][W] guest: still waiting for http-proxy-restricted after 30.00085145s
[2023-02-01T11:24:03.672973995Z][vpnkit-bridge][W] guest: still waiting for http-proxy-restricted after 40.001036589s
```

Checking further in the running Docker VM, I can see that indeed the socket `/run/host-services/http-proxy-restricted.sock` does not exist but `$HOME/Library/Containers/com.docker.docker/Data/httpproxy-restricted.sock` does exist on the mac filesystem. Process com.docker.backend is listening to this socket on the mac.

Neither host nor vm log files `$HOME/Library/Containers/com.docker.docker/Data/log/host/*.log` and `$HOME/Library/Containers/com.docker.docker/Data/log/vm/*.log` show errors that seemed to be linked to this issue but configuration passed to vpnkit-bridge (in both host and vm) looks correct:
```
[2023-02-01T14:47:28.490624000Z][vpnkit-bridge][I] listening on AF_UNIX unix+listen+fd: for a file descriptor
[2023-02-01T14:47:28.491049000Z][vpnkit-bridge][I] waiting for connection on AF_UNIX unix+listen+fd:
[2023-02-01T14:47:47.022462000Z][vpnkit-bridge][I] accepted connection on AF_UNIX unix+listen+fd:
[2023-02-01T14:47:47.023481000Z][vpnkit-bridge][I] writing 3721 bytes of service definitions: {
  "guest": {
    "container-filesystem": {
      "guest": "/run/guest-services/container-filesystem.sock",
      "host": "container-filesystem.sock"
    },
    "debug-shell": {
      "guest": "/run/guest-services/debug-shell.sock",
      "host": "debug-shell.sock"
    },
    "devenv-volumes": {
      "guest": "/run/guest-services/devenv-volumes.sock",
      "host": "devenv-volumes.sock"
    },
    "diagnosticd": {
      "guest": "/run/guest-services/diagnosticd.sock",
      "host": "diagnosticd.sock"
    },
    "dns-forwarder": {
      "guest": "/run/guest-services/dns-forwarder.sock",
      "host": "dns-forwarder.sock"
    },
    "docker": {
      "guest": "/run/guest-services/docker.sock",
      "host": "docker.raw.sock"
    },
    "filesystem-event": {
      "guest": "/run/guest-services/filesystem-event.sock",
      "host": "filesystem-event.sock"
    },
    "filesystem-test": {
      "guest": "/run/guest-services/filesystem-test.sock",
      "host": "filesystem-test.sock"
    },
    "http-proxy-control": {
      "guest": "/run/guest-services/http-proxy-control.sock",
      "host": "http-proxy-control.sock"
    },
    "lifecycle-server": {
      "guest": "/run/guest-services/lifecycle-server.sock",
      "host": "lifecycle-server.sock"
    },
    "log": {
      "guest": "/run/guest-services/memlogdq.sock",
      "host": "memlogdq.sock"
    },
    "nat-control": {
      "guest": "/run/guest-services/nat-control.sock",
      "host": "nat-control.sock"
    },
    "procd": {
      "guest": "/run/guest-services/procd.sock",
      "host": "procd.sock"
    },
    "volume-contents": {
      "guest": "/run/guest-services/volume-contents.sock",
      "host": "volume-contents.sock"
    }
  },
  "host": {
    "backend": {
      "guest": "/run/host-services/backend.sock",
      "host": "backend.sock"
    },
    "backend-native": {
      "guest": "/run/host-services/backend.native.sock",
      "host": "backend.native.sock",
      "noopCloseWrite": true
    },
    "dns.internal/grpc": {
      "guest": "/run/host-services/dns.internal.grpc.sock",
      "host": "dns.internal.grpc.sock"
    },
    "dns.system/grpc": {
      "guest": "/run/host-services/dns.system.grpc.sock",
      "host": "dns.system.grpc.sock"
    },
    "docker-proxy": {
      "guest": "/run/host-services/docker.proxy.sock",
      "host": "<HOME>/.docker/run/docker.sock"
    },
    "extensions": {
      "guest": "/run/host-services/extension-manager.sock",
      "host": "extension-manager.sock"
    },
    "filesystem": {
      "guest": "/run/host-services/filesystem.sock",
      "host": "filesystem.sock"
    },
    "http-proxy": {
      "guest": "/run/host-services/http-proxy.sock",
      "host": "httpproxy.sock"
    },
    "http-proxy-restricted": {
      "guest": "/run/host-services/http-proxy-restricted.sock",
      "host": "httpproxy-restricted.sock"
    },
    "hubproxy": {
      "guest": "/run/host-services/hubproxy.sock",
      "host": "hubproxy.sock"
    },
    "network-proxy": {
      "guest": "/run/host-services/network-proxy.sock",
      "host": "networkproxy.sock"
    },
    "ntp": {
      "guest": "/run/host-services/ntp.udp.sock",
      "host": "ntp.udp.sock"
    },
    "socks": {
      "guest": "/run/host-services/socks.sock",
      "host": "socks.sock"
    },
    "ssh-auth": {
      "guest": "/run/host-services/ssh-auth.sock",
      "host": "/private/tmp/com.apple.launchd.M7hrlcWn21/Listeners"
    },
    "vpnkit": {
      "guest": "/run/host-services/vpnkit.sock",
      "host": "vpnkit.eth.sock",
      "noopCloseWrite": true
    },
    "vpnkit-data": {
      "guest": "/run/host-services/vpnkit-data.sock",
      "host": "vpnkit.data.sock"
    }
  }
}
```

To temporarily fix my ability to pull images, I simply aliased the http-proxy.sock to http-proxy-restricted.sock in the VM:
`echo "ln -s /run/host-services/http-proxy.sock /run/host-services/http-proxy-restricted.sock" | nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock`

**Comment by yegorski** [comment] 2023-02-01 17:29
From what we're seeing on our corporate MacBook Pros, Docker with Ventura on M1 is broken:
✅ Ventura on Intel
✅ Monterey on M1
❌ Ventura on M1

**Comment by g-deoliveira** [comment] 2023-02-07 17:08
Ultimately running Colima did not solve this issue _completely_ for me, but rolling back to the prior release of [Docker Desktop](https://docs.docker.com/desktop/previous-versions/3.x-mac/) (version 3.6) did.

**Comment by Lohann** [comment] 2023-02-09 15:24
Same issue, I'm on M1 Macos Ventura:
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by baumac** [comment] 2023-02-10 09:20
On my corporate Macbook M1 Pro (running Ventura) I rolled back to Docker Desktop [4.14.1](https://docs.docker.com/desktop/release-notes/#4141) and it worked for me.

The issue seems to have been introduced in Docker Desktop [4.15.0](https://docs.docker.com/desktop/release-notes/#4150).

**Comment by marcusmonteirodesouza** [comment] 2023-02-11 02:48
Docker Desktop [4.15.0](https://docs.docker.com/desktop/release-notes/#4150) works on my machine too.

**Comment by Zompaktu** [comment] 2023-02-11 08:11
I have the same error on mac and linux boxes.
After
`docker login`
images pulled successfully. Of course  you need Docker Hub account.

**Comment by evict** [comment] 2023-03-08 10:01
I have this same problem after updating Docker to 4.15.0. `docker login` doesn't solve it, as it throws the same error. I am on Apple silicon.

**Comment by ks93** [comment] 2023-03-08 18:14
M1 Max here. Same issue on DD versions after 4.14.1. Works on 4.14.1.

One observation: When running 4.14.1 the first time, I get a prompt that docker needs additional privileges to install network components, which I did not get with <4.15 versions..
<img width="599" alt="image" src="https://user-images.githubusercontent.com/11884461/223795952-7e3f74fe-7d82-4d10-b488-650007f8cea6.png">

**Comment by gcobr** [comment] 2023-04-17 02:15
> @rfay Yes, I got this result:
> 
> ```
> $ curl -I https://registry-1.docker.io/v2/
> HTTP/1.1 401 Unauthorized
> content-type: application/json
> docker-distribution-api-version: registry/2.0
> www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
> date: Sat, 28 Jan 2023 03:03:54 GMT
> content-length: 87
> strict-transport-security: max-age=31536000
> ```
> 
> What does it mean? Can I do something about this?

It means your HTTP request reached the server and was rejected because you did not include an authorization token in "Authorization" HTTP header.

It also proves that your machine is able to:
1. Connect to the server.
2. Perform a successful SSL handshake (no SSL certificate issues).
3. Submit an HTTPS request to the server and receive back a response, even though the response contains an error.

**Comment by gcobr** [comment] 2023-04-17 02:17
> I have this same problem after updating Docker to 4.17.0 from 4.14.1. `docker login` doesn't solve it, as it throws the same error. I am on Apple silicon.

Can you check your logs and see if you have the same symptoms I described [here]( https://github.com/docker/for-mac/issues/6808)?

**Comment by gcobr** [comment] 2023-04-17 02:18
> On my corporate Macbook M1 Pro (running Ventura) I rolled back to Docker Desktop [4.14.1](https://docs.docker.com/desktop/release-notes/#4141) and it worked for me. I then tried installing [4.15.0](https://docs.docker.com/desktop/release-notes/#4150) and this issue occurred.
> 
> The issue seems to have been introduced in Docker Desktop [4.15.0](https://docs.docker.com/desktop/release-notes/#4150).

Can you check your logs and see if you have the same symptoms I described [here]( https://github.com/docker/for-mac/issues/6808)?

**Comment by mfernandes3** [comment] 2023-04-17 11:11
same issue here

**Comment by djs55** [comment] 2023-04-18 20:38
Based on the logs about the `http-proxy-restricted.sock` I've made a build with a possible fix. If anyone would like to try it here it is:

- [Apple Silicon Mac](https://desktop-stage.docker.com/mac/main/arm64/105384/Docker.dmg)
- [Intel Mac](https://desktop-stage.docker.com/mac/main/amd64/105384/Docker.dmg)

If it still doesn't work, please upload some diagnostics and quote the ID here. Thanks for your patience!

**Comment by mminichino** [comment] 2023-04-18 21:51
@djs55 That fixed it for me. I was frequently getting errors like the following on a Mac Studio and the build I downloaded from your post fixed it. 

ERROR: failed to solve: ubuntu:focal: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/focal": dial tcp 18.215.138.58:443: i/o timeout

**Comment by mfernandes3** [comment] 2023-04-19 21:31
Downgrading the version of Docker solved it for me

**Comment by dthauvin** [comment] 2023-04-25 10:13
Hello @djs55 i confirm , it works on my `intel Mac` . Do you need more information ?

**Comment by Martin-Mo** [comment] 2023-05-05 03:22
You should configure your proxy to bypass the following domains: registry-1.docker.io and auth.docker.io.

**Comment by rluta** [comment] 2023-05-09 08:10
@djs55 release 4.19.0 has fixed the issue for me after a full reinstall

**Comment by PLP-GTR** [comment] 2023-09-28 21:22
I was just updating a lot of my containers and (apart from some connection issues which where resolved when just doing a pull again) I stumbled across this issue. In my case I wanted to update [fireflyiii/core](https://hub.docker.com/r/fireflyiii/core).

I then did
$`docker logout` (did not fix it)
$`docker login`
and it was fixed (although not immediately).

There was no internet connection error, I was streaming something and my room mate was playing online.

Could be some kind of thresholding? I know the [rate limits are quite high](https://docs.docker.com/docker-hub/download-rate-limit/) but the re-login fixing it is very suspicious.

My errors where always different from try to try, here in chronological order:
```
[+] Running 2/2
 ✘ fireflyiii-app Error                                                                                                                                                                                                                              11.2s
 ✘ fireflyiii-db Error                                                                                                                                                                                                                               11.2s
Error response from daemon: Head "https://registry-1.docker.io/v2/library/mariadb/manifests/latest": EOF
```
instant retry:
```
[+] Running 2/2
 ✘ fireflyiii-db Error                                                                                                                                                                                                                                5.3s
 ✘ fireflyiii-app Error                                                                                                                                                                                                                               5.3s
Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF
```
instant retry:
```
[+] Pulling 2/2
 ✘ fireflyiii-db Error                                                                                                                                                                                                                                6.0s
 ✘ fireflyiii-app Error                                                                                                                                                                                                                               6.0s
Error response from daemon: Head "https://registry-1.docker.io/v2/fireflyiii/core/manifests/latest": EOF
```
After `docker logout`:
```
[+] Pulling 2/2
 ✘ fireflyiii-app Error                                                                                                                                                                                                                               5.6s
 ✘ fireflyiii-db Error                                                                                                                                                                                                                                5.6s
Error response from daemon: Head "https://registry-1.docker.io/v2/library/mariadb/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fmariadb%3Apull&service=registry.docker.io": EOF
```
After `docker login`:
```
[+] Pulling 9/10
 ⠇ fireflyiii-db 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                                                                                                                                                                                          4.9s
   ✔ 8b5db5f6400d Pull complete                                                                                                                                                                                                                       0.6s
...
   ✔ 52903b30562f Download complete                                                                                                                                                                                                                   1.1s
 ✘ fireflyiii-app Error                                                                                                                                                                                                                               4.9s
Error response from daemon: Head "https://registry-1.docker.io/v2/fireflyiii/core/manifests/latest": received unexpected HTTP status: 503 Service Unavailable
```
Instant retry worked:
```
[+] Pulling 40/40
 ✔ fireflyiii-db 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                           8.9s
   ✔ 8b5db5f6400d Pull complete                                                                                                                                                                                                                       0.5s
...
   ✔ 52903b30562f Pull complete                                                                                                                                                                                                                       4.1s
 ✔ fireflyiii-app 30 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                  93.4s
   ✔ f96ab1515704 Pull complete                                                                                                                                                                                                                      13.6s
   ✔ 1788cf01114b Pull complete                                                                                                                                                                                                                       3.7s
...
```

The system: `Ubuntu 22.04.3 LTS` on `ARM Neoverse-N1` (Oracle Free Tier ARM instance)

**Comment by rfay** [comment] 2023-09-28 21:31
Please check https://status.docker.com before. adding to an issue. It's currently broken.

**Comment by dstyp** [comment] 2023-09-28 21:51
I see this is on macOS but I have this is exact issue after updating a headless Debian machine to bookworm. Any solution? Updated to latest stable docker installation.

`➜  / docker --version      
Docker version 24.0.6, build ed223bc
➜  / docker compose version
Docker Compose version v2.21.0`

**Comment by PLP-GTR** [comment] 2023-09-28 21:55
> Please check https://status.docker.com before. adding to an issue. It's currently broken.

Ooooh I'm so sorry! >.<

This was not mentioned at all in the whole ticket - maybe that was also the problem back then? 👀

**Comment by rfay** [comment] 2023-09-28 22:29
@marcusmonteirodesouza I think this issue has run its course. There does seem to have been a problem with Docker Desktop earlier in the year, but now people are just stumbling on this when hub.docker.com is broken. (There are many comments here to help people sort out the networking trouble when this kind of thing happens.)

Could you close this, maybe adding a link to the various debugging techniques in your closing note?

**Comment by thaJeztah** [comment] 2023-09-28 22:44
Yes, let's close this for now; I'll also lock the ticket to prevent it collecting more comments

**Closed by thaJeztah** 2023-09-28 22:44 UTC
Labels: version/4.16.2
