### ISSUE TITLE
Granting CPUs of 9+ on Docker for M1 Mac causes repeated crashing and restarting

### ISSUE THREAD

**Issue by esilverberg** [docker/for-mac#6102] opened 2021-12-19 18:33 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I adjust the resources tab and grant Docker for Mac access to 9 or 10 CPUs, it should allow this change

### Actual behavior
Docker for mac enters an infinite loop of stopping and starting, similar to: https://github.com/docker/for-mac/issues/5477

### Information
  - macOS Version: 12.0.1
  - Intel chip or Apple chip: M1 Max
  - Docker Desktop Version: 4.3.1 (72247)

Note that I am able to repro this issue 100%

### Steps to reproduce the behavior

  1. Go to the Resources tab
  2. Grant Docker access to 9 or 10 CPUs
  3. It should accept this change 
  4. Instead, it starts in an infinite loop of crashing and restarting

**Comment by StefanScherer** [comment] 2021-12-20 06:31
Thanks @esilverberg for the report. We're looking into the issue, but for now you only can select up to 8 CPUs (the eight high performance cores, the other two are efficiency cores).
I'll close this ticket as it's a duplicate of #6063, please follow the progress there.

**Closed by StefanScherer** 2021-12-20 06:31 UTC
Labels: area/m1, version/4.3.1
