### ISSUE TITLE
docker ps hangs on MacOS Sierra 10.12 Beta (16A269f)

### ISSUE THREAD

**Issue by mikeplavsky** [docker/for-mac#157] opened 2016-08-06 16:18 UTC
### Expected behavior
docker ps works 

### Actual behavior
docker ps hangs 

### Information

Diagnostic ID: 38C8E26A-FD64-4C7B-9F2A-F15CDB67BAF1
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A269f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install Sierra Beta
2. Run docker ps

**Comment by avsm** [comment] 2016-08-08 13:18
Duplicate of #64 -- please see https://github.com/docker/for-mac/issues/64#issuecomment-238191340 for progress on getting this working.

**Closed by avsm** 2016-08-08 13:18 UTC

**Comment by djs55** [comment] 2016-09-15 16:28
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
