### ISSUE TITLE
Unable to reach services behind VPN from docker container (Apple M1 Tech Preview)

### ISSUE THREAD

**Issue by pradeep-cognitiv** [docker/for-mac#5322] opened 2021-02-08 23:07 UTC
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Able to access resources behind VPN (that are accessible from my host machine)

### Actual behavior
Unable to access resources behind VPN

### Information
  - macOS Version: 11.2 (macOS Big Sur), Apple M1 chip 
  - Docker Desktop Version: Tech Preview for Apple M1 (0.0.0(1))
  - The issue is consistently reproducible
  - I am a newbie to docker so need some help/pointers with getting the right logs for the issue 
  - I already tried quite a few things from the post https://github.com/docker/for-mac/issues/2820 (except the bib setting) but none of that worked for me.

### Steps to reproduce the behavior
  1. Connect to VPN, do a curl for the url of interest from host machine and verify that it succeeds
  2. Run a docker container and do the same, request times out. Verify a public url (like google.com) is accessible from docker container.
 
### A few things that are attempted / observed
  1. There doesn't seem to be conflicts between VPN Ip's and docker Ip's but I can give more specific details if that's useful.
  2. My docker is not set up with kubernetes.
  3. I already tried 'docker network prune' and also reset to factory defaults in docker - no use.

**Comment by tetio** [comment] 2021-02-09 11:42
Same issue here.

**Comment by MarcoGarofalo94** [comment] 2021-02-09 12:07
Same problem, seems like the container is not able to resolve VPN DNS.

**Comment by miltonLuiz** [comment] 2021-02-09 15:07
Same thing, all the problems described up here.

**Comment by stephen-turner** [comment] 2021-02-09 15:22
Yes, thank you, we know this doesn't work in the current preview. There are lots of networking things that aren't plumbed through yet.

**Comment by pradeep-cognitiv** [comment] 2021-02-09 15:46
@stephen-turner , thank you for confirming! By any chance, is there a quick work around / patch that I can try to unblock myself while things are being sorted out officially? This is a prerequisite for my development workflow and I'd like to keep my M1 if possible.

**Comment by stephen-turner** [comment] 2021-02-10 09:27
No, sorry. Please bear in mind that this is an early preview. I would say it is "alpha" quality not even "beta".

**Comment by pradeep-cognitiv** [comment] 2021-02-10 19:28
@stephen-turner , thank you for the reply! I understand! I am thankful for the hard work by team @ docker in pulling this!

**Comment by djs55** [comment] 2021-02-12 11:19
@pradeep-cognitiv if you'd like to experiment, it's possible the issue could be worked around with some `pfctl` magic. The same issue affects all users of the virtualization APIs on Big Sur and there are some instructions on this forum post: https://communities.vmware.com/t5/VMware-Fusion-Discussions/Share-host-VPN-with-guest/m-p/2810095/highlight/true#M170151 Note I haven't tried this myself so I don't know if it will work or not. If you decide to try it, please let us know how it goes -- this would be really helpful both to us and to other users.

**Comment by bloomcake** [comment] 2021-02-12 12:49
I tested the `pfctl` magic and after that I could reach our VPN in the container 
my steps:
* `sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2>/dev/null >newrules.conf` 
* find out my tun interface `ifconfig | grep -A2 tun | grep -B1 172.31`
* added new rule `echo "nat on utun6 inet from 192.168.64.0/24 to any -> (utun6) extfilter ei" >>newrules.conf` with `utun6` my vpn interface and `192.168.64.0/24` my configured docker network
* applied the rules `sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f newrules.conf 2>/dev/null`

```
~ % docker run -it alpine:3.13 ping -c 2 172.16.0.1
PING 172.16.0.1 (172.16.0.1): 56 data bytes
64 bytes from 172.16.0.1: seq=0 ttl=61 time=39.479 ms
64 bytes from 172.16.0.1: seq=1 ttl=61 time=32.768 ms

**Comment by JanMalte** [comment] 2021-02-27 11:12
Seems like it is working. Using `192.168.64.0/24` for the networking rules, even if Docker for Mac ist showing `192.168.65.0/24` as Docker network in the Settings UI.

**Comment by colandre** [comment] 2021-02-27 11:36
> I tested the `pfctl` magic and after that I could reach our VPN in the container
> my steps:
> 
> * `sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2>/dev/null >newrules.conf`
> * find out my tun interface `ifconfig | grep -A2 tun | grep -B1 172.31`
> * added new rule `echo "nat on utun6 inet from 192.168.64.0/24 to any -> (utun6) extfilter ei" >>newrules.conf` with `utun6` my vpn interface and `192.168.64.0/24` my configured docker network
> * applied the rules `sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f newrules.conf 2>/dev/null`
> 
> ```
> ~ % docker run -it alpine:3.13 ping -c 2 172.16.0.1
> PING 172.16.0.1 (172.16.0.1): 56 data bytes
> 64 bytes from 172.16.0.1: seq=0 ttl=61 time=39.479 ms
> 64 bytes from 172.16.0.1: seq=1 ttl=61 time=32.768 ms
> ```

Thank you @bloomcake , it works also for me.
For the thread followers convenience, I think this issue is related to this one:
https://github.com/docker/for-mac/issues/5208

and here there is the referenced bash script simplifying the operation.

**Comment by SavantGood** [comment] 2021-03-11 16:08
> I tested the `pfctl` magic and after that I could reach our VPN in the container
> my steps:
> 
> * `sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2>/dev/null >newrules.conf`
> * find out my tun interface `ifconfig | grep -A2 tun | grep -B1 172.31`
> * added new rule `echo "nat on utun6 inet from 192.168.64.0/24 to any -> (utun6) extfilter ei" >>newrules.conf` with `utun6` my vpn interface and `192.168.64.0/24` my configured docker network
> * applied the rules `sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f newrules.conf 2>/dev/null`
> 
> ```
> ~ % docker run -it alpine:3.13 ping -c 2 172.16.0.1
> PING 172.16.0.1 (172.16.0.1): 56 data bytes
> 64 bytes from 172.16.0.1: seq=0 ttl=61 time=39.479 ms
> 64 bytes from 172.16.0.1: seq=1 ttl=61 time=32.768 ms
> ```

it worked for me, though after setting this rule I stopped accessing the docker hub, I get an error. No problem before setting the rule

error text: "Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (*****): *****
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)""

**Comment by zuffko** [comment] 2021-03-12 08:49
I was able to resolve the issue by setting 8.8.8.8 DNS server address in OS network setting (macOS Bis Sur)

**Comment by arnellebalane** [comment] 2021-03-24 11:53
Just noticed today that there's a new update for Docker Desktop for Mac (M1). After updating to this new version, I'm now able to login to and pull images from registries behind VPN 🎉 

![image](https://user-images.githubusercontent.com/1428598/112306018-4d259580-8cda-11eb-8950-88cfbb99ae11.png)

**Comment by thecosmicfrog** [comment] 2021-03-24 12:59
No such luck for me, I'm afraid. Docker for Mac M1 Preview RC1 with Cisco AnyConnect is still failing. Sometimes it fails to start up. Other times it starts up but I get `Error response from daemon: dial unix docker.raw.sock: connect: connection refused` when running `docker login`.

**Comment by eddyw** [comment] 2021-03-26 14:33
I'm having this exact same issue in MacOS Big Sur 11.2.3 (**NOT M1**) after upgrading OS and docker desktop to latest a couple of days ago with:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
After struggling a couple of days getting it to work with my VPNs, double hop VPNs like if life wasn't hard enough (either of these setups):

- 2 OpenVPN Clients -> Wireguard Client -> The Internet
- 2 OpenVPN Clients -> [Private VPN protocol based on OpenVPN] -> The Internet

I've tried the workaround described by this user: https://github.com/lastcosmonaut/docker-m1-vpn-workaround
It didn't work .. but then I made a slight modification to that script (`vpn.sh` in link above) to this:

```bash
# determine your utun interface by running "ifconfig" and look for the utun with an associated IPv4 address
export UTUN_INTF="utun2"

echo "## Previous Configuration"
sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2> /dev/null | tee /tmp/docker_vpn.conf
if sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2> /dev/null | grep 192.168.64.0 | grep -q $UTUN_INTF
then
        echo && echo "Not applying change"
else
        echo "nat on $UTUN_INTF inet from 192.168.64.0/24 to any -> ($UTUN_INTF:0) extfilter ei" >> /tmp/docker_vpn.conf
        sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f /tmp/docker_vpn.conf 2> /dev/null
        echo && echo "## New Configuration"
        cat /tmp/docker_vpn.conf
fi
```
The only change I made to the script was to replace `($UTUN_INTF) extfilter ei` with `($UTUN_INTF:0) extfilter ei` because the first when applied becomes:
```
nat on utun2 inet from 192.168.64.0/24 to any -> (utun2) round-robin extfilter ei
```
But you want:
```
nat on utun2 inet from 192.168.64.0/24 to any -> (utun2:0) extfilter ei
```
I don't know what `round-robin` means but that didn't work but it did after creating the rule with `($UTUN_INTF:0) extfilter ei` instead and of course change `UTUN_INTF` env var to yours.

For my use case, I had to add 2 new rules and not 1 (because of double hop VPN setup or whatever it is called) and `sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2> /dev/null` looks like:
```
nat on utun11 inet from 192.168.64.0/24 to any -> (utun11:0) extfilter ei
nat on en0 inet from 192.168.64.0/24 to any -> (en0:0) extfilter ei
no nat on bridge100 inet from 192.168.64.1 to 192.168.64.0/24
nat on utun3 inet from 192.168.64.0/24 to any -> (utun3:0) extfilter ei
nat on utun2 inet from 192.168.64.0/24 to any -> (utun2:0) extfilter ei
```

So far it's working but the config is reset if either VPN disconnects/reconnects, so it's annoying having to apply every time.

---

Another approach I have tried that somewhat worked was to install `SquidMan` (on same machine where docker-desktop is) to setup a local HTTP proxy server listening on `127.0.0.1:9090` and set docker proxy settings for HTTP and HTTPS to that address. It's silly but this worked because `SquidMan` will route the traffic through the VPN. However, I wasn't able to figure out how to connect to our internal registry 🤷‍♂️ (but maybe this silly approach will work for someone)

**Comment by stephen-turner** [comment] 2021-03-26 15:59
@eddyw Are you using the new virtualization.framework backend from the experimental settings? If so, it will be exactly the same as M1.

**Comment by stephen-turner** [comment] 2021-03-26 16:29
Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

**Comment by stephen-turner** [comment] 2021-03-26 16:31
Also we have too many tickets about VPNs, so I'm going to resolve this as a dupe of #5208.

**Closed** 2021-03-26 16:32 UTC
Labels: area/m1, version/11.2

**Comment by thecosmicfrog** [comment] 2021-03-26 17:57
@stephen-turner RC2 is looking good for me so far! Uninstalled RC1, killed any lingering processes and installed RC2 (all while connected through Cisco AnyConnect VPN client). Docker for Mac starts up and I can `docker login`, `docker run`, `docker pull`, etc.

What a fantastic way to close out a week! Thank you for getting this fixed - it's a massive unblocker for me.

I'll update the other issue if I run into any problems.

**Comment by MarcoGarofalo94** [comment] 2021-03-26 18:00
> Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

I tried the new RC2, now  I am able to reach VPN local network inside container, but (even without connecting to the VPN), i am not able to ping anything on internet like 8.8.8.8 or www.google.com.

**Comment by bobwolff68** [comment] 2021-03-26 18:51
I tried both RC1 and RC2 and they both solved my inability to do a docker login over the VPN (GlobalProtect). I'm pretty happy with what I'm seeing. Great updates.

**Comment by stephen-turner** [comment] 2021-03-26 19:45
> i am not able to ping anything on internet like 8.8.8.8 or [www.google.com](http://www.google.com).

Is anyone else seeing this symptom?

**Comment by djs55** [comment] 2021-03-29 13:20
@MarcoGarofalo94 could you check whether you are using `virtualization.framework` or `qemu` in RC 2? There's a checkbox in the Whale menu -> Preferences -> Experimental Features:

![Screenshot 2564-03-29 at 14 16 51](https://user-images.githubusercontent.com/198586/112842426-70b15d00-9099-11eb-836c-441f4e79aa72.png)

If the checkbox is checked, it means you're using `virtualization.framework`. If it's unchecked, you're using `qemu`. In the screenshot above I'm using `qemu`.

After that, could you reproduce the networking problem and then upload a diagnostic (whale menu -> troubleshoot -> Get Support) and then quote the ID here? This should allow me to look through the logs.

As well as testing with `ping`, could you try something HTTP-based like `curl` or `wget`? The reason I ask is that ICMP is handled specially by the userspace networking stack and may be a bit buggy.

**Comment by MarcoGarofalo94** [comment] 2021-03-29 13:50
@djs55 Hi, I am currently using `3.3.0 (62345)` version. Thanks for you advise about ping, it was actually the issue. I did some tests the same and I can tell you that now (based on curl and an application I made) I can reach both the VPN and internet from the container enabling and disabling `virtualization.framework`

**Comment by djs55** [comment] 2021-03-29 15:33
@MarcoGarofalo94 thanks for the quick confirmation. I'll add a ticket to the backlog to do something about `ping`: either fix it or document the limitation.

**Comment by phucdh2** [comment] 2021-04-11 10:37
> Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

I'm facing the same issue with @stephen-turner. Can anyone have any idea to resolve this problem?

**Comment by donalod** [comment] 2021-04-16 10:44
ICMP Echo Reply (0) and Echo Request (8) (ping) is pretty important for reachability and network path testing, especially hop by hop. It's a precursor to most application-level testing and almost ubiquitous for endpoints to answer (including default gateways, loopbacks, mgmt interfaces, and almost any IP-enabled endpoint). Is there any explanation for this not working at the lower levels as it's not host based firewall-related? I think it's important not to conflate network-level tests with application-level tests. Is it a tweak for the docker service / QEMU such as **https://unix.stackexchange.com/a/154990** ?

**Comment by adelmojunnior** [comment] 2021-05-04 13:17
> @MarcoGarofalo94 could you check whether you are using `virtualization.framework` or `qemu` in RC 2? There's a checkbox in the Whale menu -> Preferences -> Experimental Features:
> 
> ![Screenshot 2564-03-29 at 14 16 51](https://user-images.githubusercontent.com/198586/112842426-70b15d00-9099-11eb-836c-441f4e79aa72.png)
> 
> If the checkbox is checked, it means you're using `virtualization.framework`. If it's unchecked, you're using `qemu`. In the screenshot above I'm using `qemu`.
> 
> After that, could you reproduce the networking problem and then upload a diagnostic (whale menu -> troubleshoot -> Get Support) and then quote the ID here? This should allow me to look through the logs.
> 
> As well as testing with `ping`, could you try something HTTP-based like `curl` or `wget`? The reason I ask is that ICMP is handled specially by the userspace networking stack and may be a bit buggy.

I had this problem with VPN in my company. When I unchecked and restarted docker, resolved!!

**Comment by Tochemey** [comment] 2021-05-12 15:32
Hello the issue still persist I have to downgrade to 3.1.0 to be able to connect via VPN

**Comment by devinus** [comment] 2021-05-13 02:56
This is present on amd64 too, by the way. A version between 3.2.2 and 3.3.3.

**Comment by stephen-turner** [comment] 2021-05-13 08:22
This is expected, and documented, if you're using the new virtualisation framework.
