### ISSUE TITLE
Segmentation fault on macOS Big Sur Release Candidate 11.0.1 Beta (20B5022a)

### ISSUE THREAD

**Issue by AjaxOdessa** [docker/for-mac#5054] opened 2020-11-09 20:19 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

No Diagnostics logs or ID because application cannot start at all.

### Expected behavior
Docker starts and initializes the engine.

### Actual behavior
Docker fails with the "segmentation fault" error

### Information
Application Docker cannot start with the "Segmentation fault" error.
2.4.2.0 (48975)

  - macOS Version: macOS Big Sur Release Candidate 11.0.1 Beta (20B5022a)

### Diagnostic logs
Below is the `docker.log` file, no other logs can be generated since application can't start at all.
`Docker for Mac: 2.4.2.0 (48975)`
```
time="2020-11-09T19:59:26Z" level="error" msg="Logging system already setup"
time="2020-11-09T19:59:26Z" level="info" msg="CrashReport: stderr redirected to /Users/USER/Library/Group Containers/group.com.docker/DockerAppStderr.txt"
time="2020-11-09T19:59:26Z" level="info" msg="DockerApplication: Docker.app starting for USER"
time="2020-11-09T19:59:26Z" level="info" msg="applicationDidFinishLaunching: options.restart = false"
time="2020-11-09T19:59:26Z" level="info" msg="SettingsMigrator: All migrations passed"
time="2020-11-09T19:59:26Z" level="info" msg="AppDelegate: changed currentDirectoryPath to: /Users/USER/Library/Containers/com.docker.docker/Data"
time="2020-11-09T19:59:27Z" level="info" msg="AppDelegate: Application version: 2.4.2.0 (48975)"
time="2020-11-09T19:59:27Z" level="info" msg="AppDelegate: Channel: edge"
time="2020-11-09T19:59:27Z" level="info" msg="AppDelegate: Administrator user: true"
time="2020-11-09T19:59:27Z" level="info" msg="Environment: macOS Version: NSOperatingSystemVersion(majorVersion: 10, minorVersion: 16, patchVersion: 0))"
time="2020-11-09T19:59:27Z" level="info" msg="Environment: Virtualization enabled"
time="2020-11-09T19:59:27Z" level="fault" msg="CrashReport: report: Segmentation violation exception"
time="2020-11-09T19:59:27Z" level="fault" msg="CrashReport: 0   Docker                              0x0000000109bc5469 $s6Docker11CrashReportC6reportyySo11NSExceptionCFZTf4nd_n + 297
1   Docker                              0x0000000109bc41fe $s6Docker11CrashReportC23handleUncaughtException33_4B34A86808A74617BA9D4CB1A9DDDEEFLLySo11NSExceptionCXCSgvpZfiyAGcfU_To + 30
2   CoreFoundation                      0x00007fff20510826 __handleUncaughtException + 716
3   libobjc.A.dylib                     0x00007fff201ce9ab _ZL15_objc_terminatev + 90
4   libc++abi.dylib                     0x00007fff202e6847 _ZSt11__terminatePFvvE + 8
5   libc++abi.dylib                     0x00007fff202e9167 __cxa_get_exception_ptr + 0
6   libc++abi.dylib                     0x00007fff202e912e _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
7   libobjc.A.dylib                     0x00007fff201cc4f7 objc_exception_throw + 350
8   CoreFoundation                      0x00007fff204bd512 +[NSException raise:format:arguments:] + 88
9   Docker                              0x0000000109bc4522 $s6Docker11CrashReportC12handleSignal33_4B34A86808A74617BA9D4CB1A9DDDEEFLLyys5Int32VXCvpZfiyAGcfU_ + 674
10  libsystem_platform.dylib            0x00007fff20366d7d _sigtramp + 29
11  ???                                 0x0000000000000000 0x0 + 0
12  CoreFoundation                      0x00007fff203c9fa3 __CFStringAppendFormatCore + 9462
13  CoreFoundation                      0x00007fff204f8734 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 159
14  CoreFoundation                      0x00007fff203c7a9f _CFStringCreateWithFormatAndArgumentsAux2 + 20
15  Docker                              0x0000000109c0baf7 $sSS6DockerE8localizeySSs7CVarArg_pd_tF + 519
16  Docker                              0x0000000109b7b402 $s6Docker11EnvironmentC22checkVirtualBoxVersion33_25979CC4025DA82A0288B82BDC2BFC60LLSSSgyFZTf4d_n + 1666
17  Docker                              0x0000000109b7a1fe $sSSSgIego_AAIegr_TR97$s6Docker11EnvironmentC22checkVirtualBoxVersion33_25979CC4025DA82A0288B82BDC2BFC60LLSSSgyFZTf4d_nTf3npf_n + 14
18  Docker                              0x0000000109b7b769 $s6Docker11EnvironmentC5checkAC11CheckResultOyFZTf4d_n + 505
19  Docker                              0x0000000109b7113c $s6Docker11AppDelegateC9bootstrapAA16BootstrapStoppedCSgyF + 2780
20  Docker                              0x0000000109b704ac $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVF + 364
21  Docker                              0x0000000109b7062b $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVFTo + 107
22  CoreFoundation                      0x00007fff2040ffdc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
23  CoreFoundation                      0x00007fff204ab89b ___CFXRegistrationPost_block_invoke + 49
24  CoreFoundation                      0x00007fff204ab80f _CFXRegistrationPost + 454
25  CoreFoundation                      0x00007fff203e0bce _CFXNotificationPost + 723
26  Foundation                          0x00007fff2114cabe -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
27  AppKit                              0x00007fff22c350f1 -[NSApplication _postDidFinishNotification] + 305
28  AppKit                              0x00007fff22c34e3f -[NSApplication _sendFinishLaunchingNotification] + 208
29  AppKit                              0x00007fff22c3203a -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541
30  AppKit                              0x00007fff22c31c90 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665
31  Foundation                          0x00007fff21178056 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
32  Foundation                          0x00007fff21177ec6 _NSAppleEventManagerGenericHandler + 80
33  AE                                  0x00007fff261dc0b9 _AppleEventsCheckInAppWithBlock + 15850
34  AE                                  0x00007fff261db7d4 _AppleEventsCheckInAppWithBlock + 13573
35  AE                                  0x00007fff261d4440 aeProcessAppleEvent + 452
36  HIToolbox                           0x00007fff2868ef12 AEProcessAppleEvent + 54
37  AppKit                              0x00007fff22c2c412 _DPSNextEvent + 2048
38  AppKit                              0x00007fff22c2a74b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
39  AppKit                              0x00007fff22c1cbda -[NSApplication run] + 586
40  AppKit                              0x00007fff22bf0f31 NSApplicationMain + 816
41  Docker                              0x0000000109b65a59 main + 9
42  libdyld.dylib                       0x00007fff2033d631 start + 1"
time="2020-11-09T19:59:29Z" level="info" msg="AppDelegate: Initiating Graceful shutdown"
time="2020-11-09T19:59:29Z" level="info" msg="AppDelegate: End of  Graceful shutdown"
time="2020-11-09T19:59:29Z" level="info" msg="AppDelegate: applicationWillTerminate"
```

`Docker for Mac: 2.5.0.0 (49427)`
```
time="2020-11-09T20:08:57Z" level="error" msg="Logging system already setup"
time="2020-11-09T20:08:57Z" level="info" msg="CrashReport: stderr redirected to /Users/USER/Library/Group Containers/group.com.docker/DockerAppStderr.txt"
time="2020-11-09T20:08:57Z" level="info" msg="DockerApplication: Docker.app starting for USER"
time="2020-11-09T20:08:57Z" level="info" msg="applicationDidFinishLaunching: options.restart = false"
time="2020-11-09T20:08:57Z" level="info" msg="SettingsMigrator: All migrations passed"
time="2020-11-09T20:08:57Z" level="info" msg="AppDelegate: changed currentDirectoryPath to: /Users/USER/Library/Containers/com.docker.docker/Data"
time="2020-11-09T20:08:57Z" level="info" msg="AppDelegate: Application version: 2.5.0.0 (49427)"
time="2020-11-09T20:08:57Z" level="info" msg="AppDelegate: Channel: stable"
time="2020-11-09T20:08:57Z" level="info" msg="AppDelegate: Administrator user: true"
time="2020-11-09T20:08:57Z" level="info" msg="Environment: macOS Version: NSOperatingSystemVersion(majorVersion: 10, minorVersion: 16, patchVersion: 0))"
time="2020-11-09T20:08:57Z" level="info" msg="Environment: Virtualization enabled"
time="2020-11-09T20:08:58Z" level="fault" msg="CrashReport: report: Segmentation violation exception"
time="2020-11-09T20:08:58Z" level="fault" msg="CrashReport: 0   Docker                              0x0000000100873b49 $s6Docker11CrashReportC6reportyySo11NSExceptionCFZTf4nd_n + 297
1   Docker                              0x00000001008728de $s6Docker11CrashReportC23handleUncaughtException33_4B34A86808A74617BA9D4CB1A9DDDEEFLLySo11NSExceptionCXCSgvpZfiyAGcfU_To + 30
2   CoreFoundation                      0x00007fff20510826 __handleUncaughtException + 716
3   libobjc.A.dylib                     0x00007fff201ce9ab _ZL15_objc_terminatev + 90
4   libc++abi.dylib                     0x00007fff202e6847 _ZSt11__terminatePFvvE + 8
5   libc++abi.dylib                     0x00007fff202e9167 __cxa_get_exception_ptr + 0
6   libc++abi.dylib                     0x00007fff202e912e _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
7   libobjc.A.dylib                     0x00007fff201cc4f7 objc_exception_throw + 350
8   CoreFoundation                      0x00007fff204bd512 +[NSException raise:format:arguments:] + 88
9   Docker                              0x0000000100872c02 $s6Docker11CrashReportC12handleSignal33_4B34A86808A74617BA9D4CB1A9DDDEEFLLyys5Int32VXCvpZfiyAGcfU_ + 674
10  libsystem_platform.dylib            0x00007fff20366d7d _sigtramp + 29
11  ???                                 0x0000000000000000 0x0 + 0
12  CoreFoundation                      0x00007fff203c9fa3 __CFStringAppendFormatCore + 9462
13  CoreFoundation                      0x00007fff204f8734 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 159
14  CoreFoundation                      0x00007fff203c7a9f _CFStringCreateWithFormatAndArgumentsAux2 + 20
15  Docker                              0x00000001008b9907 $sSS6DockerE8localizeySSs7CVarArg_pd_tF + 519
16  Docker                              0x0000000100829ae2 $s6Docker11EnvironmentC22checkVirtualBoxVersion33_25979CC4025DA82A0288B82BDC2BFC60LLSSSgyFZTf4d_n + 1666
17  Docker                              0x00000001008288de $sSSSgIego_AAIegr_TR97$s6Docker11EnvironmentC22checkVirtualBoxVersion33_25979CC4025DA82A0288B82BDC2BFC60LLSSSgyFZTf4d_nTf3npf_n + 14
18  Docker                              0x0000000100829d50 $s6Docker11EnvironmentC5checkAC11CheckResultOyFZTf4d_n + 496
19  Docker                              0x000000010081fa26 $s6Docker11AppDelegateC9bootstrapAA16BootstrapStoppedCSgyF + 2886
20  Docker                              0x000000010081ed2c $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVF + 364
21  Docker                              0x000000010081eeab $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVFTo + 107
22  CoreFoundation                      0x00007fff2040ffdc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
23  CoreFoundation                      0x00007fff204ab89b ___CFXRegistrationPost_block_invoke + 49
24  CoreFoundation                      0x00007fff204ab80f _CFXRegistrationPost + 454
25  CoreFoundation                      0x00007fff203e0bce _CFXNotificationPost + 723
26  Foundation                          0x00007fff2114cabe -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
27  AppKit                              0x00007fff22c350f1 -[NSApplication _postDidFinishNotification] + 305
28  AppKit                              0x00007fff22c34e3f -[NSApplication _sendFinishLaunchingNotification] + 208
29  AppKit                              0x00007fff22c3203a -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541
30  AppKit                              0x00007fff22c31c90 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665
31  Foundation                          0x00007fff21178056 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
32  Foundation                          0x00007fff21177ec6 _NSAppleEventManagerGenericHandler + 80
33  AE                                  0x00007fff261dc0b9 _AppleEventsCheckInAppWithBlock + 15850
34  AE                                  0x00007fff261db7d4 _AppleEventsCheckInAppWithBlock + 13573
35  AE                                  0x00007fff261d4440 aeProcessAppleEvent + 452
36  HIToolbox                           0x00007fff2868ef12 AEProcessAppleEvent + 54
37  AppKit                              0x00007fff22c2c412 _DPSNextEvent + 2048
38  AppKit                              0x00007fff22c2a74b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
39  AppKit                              0x00007fff22c1cbda -[NSApplication run] + 586
40  AppKit                              0x00007fff22bf0f31 NSApplicationMain + 816
41  Docker                              0x00000001008143e9 main + 9
42  libdyld.dylib                       0x00007fff2033d631 start + 1"
time="2020-11-09T20:09:00Z" level="info" msg="AppDelegate: Initiating Graceful shutdown"
time="2020-11-09T20:09:00Z" level="info" msg="AppDelegate: End of  Graceful shutdown"
time="2020-11-09T20:09:00Z" level="info" msg="AppDelegate: applicationWillTerminate"
```
### Steps to reproduce the behavior
  1. Have macOS 11.0.1 Beta (20B5022a)
  2. Run Docker application.

**Comment by stephen-turner** [comment] 2020-11-10 09:24
Thanks for the report. I suspect it's a dupe of #5026.

**Closed by stephen-turner** 2020-11-10 09:24 UTC
Labels: version/2.5.0.0
