### ISSUE TITLE
Docker does not works on Mac OS Big Sur beta 10 (20A5395g)

### ISSUE THREAD

**Issue by matiasiglesias** [docker/for-mac#4997] opened 2020-10-16 02:35 UTC
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Fatal error on docker startup

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: 2.4.0.0 Bundle 48506

```

### Steps to reproduce the behavior

1. Fresh start Mac Os
2. Open Application folder
3. Double click on docker icon
4. Error is shown <img width="666" alt="Captura de Pantalla 2020-10-15 a la(s) 23 30 36" src="https://user-images.githubusercontent.com/2591889/96206110-93faac80-0f3e-11eb-93c0-83a375042787.png">

**Comment by stephen-turner** [comment] 2020-10-16 09:41
Thanks, it worked in previous Big Sur betas so something must have changed in the OS. We'll look into it.

**Comment by djs55** [comment] 2020-10-16 10:29
@matiasiglesias thanks for your report.

Unfortunately I could not reproduce the failure --  I'm running Docker 2.4.0.0 (48506) on Big Sur beta (20A5395g) and it seems ok so far. Could you upload diagnostics by running
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
when it completes it will print something like
```
Diagnostics Bundle: /tmp/F8200DD3-AD3B-4873-AE41-69BE465E151A/20201016102749.zip
Diagnostics ID:     F8200DD3-AD3B-4873-AE41-69BE465E151A/20201016102749 (uploaded)
```
Please quote the ID on the ticket and I'll take a look at the logs!

**Comment by matiasiglesias** [comment] 2020-10-16 11:34
Diagnostics ID:     4D1109DF-2C36-46F5-A706-AC723CABCE01/20201016113159 
[Diagnostics Bundle:](https://github.com/docker/for-mac/files/5391211/20201016113159.zip)

**Comment by joshelson** [comment] 2020-10-20 06:13
Same issue here on latest Big Sur update with Edge release. If it helps, appears to be a json issue.

```
josh@Macbook Application Scripts % /Applications/Docker.app/Contents/MacOS/Docker
json error: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
INFO : BSG_KSCrashReport.c (1557): void bsg_kscrashreport_writeStandardReport(BSG_KSCrash_Context *const, const char *const): Writing crash report to /Users/josh/Library/Caches/KSCrashReports/Docker/Docker-CrashReport-430E4AA1-0A3F-4173-B08E-C623B6118BEF-w-h-NSGenericException.json
INFO : BSG_KSCrash.m (262): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 1 crash reports
```

**Comment by matiasiglesias** [comment] 2020-10-21 16:18
I've reseted my mbp to factory refaults with Mac OS Big Sur Beta 11 and Docker Desktop 2.4.0.0 build 48506. Everything worked perfect until it occurred to me to install VirtualBox and the _"Segmentation violation exception"_ error reappeared. I could fix it by uninstalling VirtualBox and everything went back to work again

**Comment by joshelson** [comment] 2020-10-21 16:59
Can confirm what @matiasiglesias says. Same issue for me.

**Comment by phedoreanu** [comment] 2020-10-21 17:11
I've also upgraded VirtualBox to `6.1.16,140961` and since then Docker `2.4.2.0,48975` was able to start.

```
==> Upgrading 1 outdated package:
virtualbox 6.1.14,140239 -> 6.1.16,140961
==> Upgrading virtualbox
==> Caveats
virtualbox requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html
```

**Comment by stgarf** [comment] 2020-10-26 05:23
For me removing VirtualBox actually fixes this issue... Eek. Something strange w/ the kernel extension interactions maybe?

**Comment by BrunoVillanova** [comment] 2020-11-04 11:20
Same here. Uninstalled VirutalBox and Docker is working again.

**Comment by stephen-turner** [comment] 2020-11-10 09:25
Thanks for all the reports. We have a workaround incoming.

**Comment by stephen-turner** [comment] 2020-11-10 10:38
And it's fixed in Docker Desktop 2.5.0.1.

**Closed by stephen-turner** 2020-11-10 10:38 UTC
Labels: version/2.4.0.0

**Comment by ajinkya933** [comment] 2020-11-15 09:14
I found a video walkthrough of installation and running docker containers on Mac OS Big Sur: https://youtu.be/RDbARU-SUIE

**Comment by daveisfera** [comment] 2020-11-16 16:31
@stephen-turner Can 2.5 be released to the Edge channel, so users on that aren't stuck with a older/broken build when they update to Big Sur?

**Comment by stephen-turner** [comment] 2020-11-16 16:41
Yes, we're planning to do that later this week.

**Comment by abdullahsasc** [comment] 2020-11-16 19:35
Will it be fine in ARM Mac (m1) ??

**Comment by BrunoVillanova** [comment] 2020-11-16 19:36
> Will it be fine in ARM Mac (m1) ??

https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/?utm_campaign=IT+Pro&utm_content=1605547520&utm_medium=social&utm_source=Organic
