### ISSUE TITLE
2.5.0.1 com.docker.hyperkit very high CPU with low load in containers

### ISSUE THREAD

**Issue by superdtx** [docker/for-mac#5084] opened 2020-11-24 00:21 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1bd3bccd-43fe-4f44-aac8-d2f26e41b7db/20201124001014

### Expected behavior
       lower cpu usage

### Actual behavior
      very high cpu usage for hyperkit with 5 containers running
![image](https://user-images.githubusercontent.com/4489673/100030112-c8287f00-2dc0-11eb-964c-34348692509a.png)

### Information

  - macOS Version: 10.15.7 

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-11-24 09:26
Thanks, I'm going to mark this as a dupe of #5044.

**Closed by stephen-turner** 2020-11-24 09:26 UTC
Labels: version/2.5.0.1
