### ISSUE TITLE
How to set DOCKER_HOST on 4.13.0 without /var/run/docker.sock

### ISSUE THREAD

**Issue by joshua-at-aws** [docker/for-mac#6529] opened 2022-10-21 17:11 UTC
### Expected behavior

- `DOCKER_HOST` working in Docker Desktop 4.13.0

### Actual behavior

- Docker Desktop for Mac removed `/var/run/docker.sock` per 4.13.0 Release Notes: https://docs.docker.com/desktop/release-notes/#docker-desktop-4130 "By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead."

- I use Docker Desktop along with other tools that require `DOCKER_HOST`. The docs say to set this to the `/var/run/docker.sock` https://docs.docker.com/desktop/faqs/general/#how-do-i-connect-to-the-remote-docker-engine-api

Is there a different setting for `DOCKER_HOST` that will work in 4.13.0, or a preference to create the socket?
I poked around a bit but did not find anything in the UI. Thanks in advance!

### Information
  - macOS Version: 12.6 Monterey
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.13.0

### Steps to reproduce the behavior

  1. Install 4.13.0 on Mac
  2. `DOCKER_HOST` not working

**Comment by nicks** [comment] 2022-10-21 19:33
Thanks for reporting!

We're trying to make Docker Desktop more userspace-friendly (e.g., fewer root privileges). As part of that, we're migrating the sockets to user-owned directories rather than root-owned directors (like /var/run).

Everything should work correctly if you `unset DOCKER_HOST` and let the default socket-picking behavior kick in?

There's supposed to be some shim code that fixes this automatically, let me check in with some people and get back to you.

**Comment by joshua-at-aws** [comment] 2022-10-21 20:10
Hi, thanks for the reply!

If I do `unset DOCKER_HOST` then the other tools, e.g. Maven or AWS SAM CLI do not work `Error: Running AWS SAM projects locally requires Docker`.

Could the new user-owned directory for the socket be added to the docs?

**Comment by nicks** [comment] 2022-10-26 14:25
Our current plan is to roll this change back for now and figure out a more orderly upgrade path with docs for client library authors.

**Comment by hopeseekr** [comment] 2022-10-27 15:46
I'd like to add that many thirdparty utilities, particularly IntelliJ and PhpStorm, expect there to be a `/var/run/docker.sock`. This change broke a wide swath of our toolchain.

**Comment by johndutchover** [comment] 2022-10-27 18:33
> Here is the workaround for OSX:
> 
> ```
> sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
> ```
@hopeseekr I needed to force `-f`
`sudo ln -sf "$HOME/.docker/run/docker.sock" /var/run/docker.sock`

**Comment by tbeauvais-imagine** [comment] 2022-10-27 18:39
This wasted 4 hours of my life thinking it was a configuration problem that I had. 

`As no valid configuration was found, execution cannot continue`
`Root cause NoSuchFileException (/var/run/docker.sock)`

I appreciate the intent of this change, yet the intent should have been captured in the release notes. Also, with such changes, you should have a workaround available BEFORE release to ensure people can continue as necessary.

Still though, updated the DOCKER_HOST doesn't work since a lot of 3rd parties rely on the location of the sock descriptor since it has been there for a decade. To change it all of a sudden is really a really bold and strange call.

Hopefully, people find this (though I didn't) and don't waste hours like I did.

**Comment by johndutchover** [comment] 2022-10-27 23:29
> This wasted 4 hours of my life thinking it was a configuration problem that I had.
> 
> `As no valid configuration was found, execution cannot continue` `Root cause NoSuchFileException (/var/run/docker.sock)`
> 
> I appreciate the intent of this change, yet the intent should have been captured in the release notes. Also, with such changes, you should have a workaround available BEFORE release to ensure people can continue as necessary.
> 
> Still though, updated the DOCKER_HOST doesn't work since a lot of 3rd parties rely on the location of the sock descriptor since it has been there for a decade. To change it all of a sudden is really a really bold and strange call.
> 
> Hopefully, people find this (though I didn't) and don't waste hours like I did.

Desktop 4.13.0 (89412) still hangs even with the "workaround", while 4.12.0 (85629) works fine. My env:

macOS Version: 13.0 Ventura (previously didn't work in 12.6 Monterey)
Intel chip or Apple chip: Apple M1 Pro
Docker Desktop Version: 4.13.0,89412

**Comment by johndutchover** [comment] 2022-10-28 14:00
I found an issue when tailing file _DockerAppStderr.txt_ in `~/Library/Group\ Containers/group.com.docker/DockerAppStderr.txt` after launching 4.13.0 (89412):
> time="2022-10-28T12:59:28Z" level="info" msg="GoBackend: notifying bugsnag: setting overrides for proxies: computing HTTPIP of 192.168.65.0/28: prefix of 28 does not accommodate a host numbered 128

I interpreted this to mean that the **default Docker subnet (/28) subnet is too small.** 

Steps taken (in addition to https://github.com/docker/for-mac/issues/6529#issuecomment-1294231081)
1. Launch Docker Desktop 4.12.0 (85629)
2. Navigate: Preferences -> Resources -> Network and changed subnet to __/24__ 
<img width="217" alt="Screenshot 2022-10-28 at 9 24 35 AM" src="https://user-images.githubusercontent.com/1088664/198626763-6071b16b-6144-41b8-8e96-fdd028b785ab.png">
3. Updated in-app to 4.13.0 (89412)

And it's working!

**Comment by chaizeg** [comment] 2022-10-31 15:24
Closing this issue as a fix has been pushed with the new release of Docker Desktop `4.13.1`. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Closed by chaizeg** 2022-10-31 15:24 UTC
Labels: status/1-acknowledged, version/4.13.0, version/13.0 Ventura

**Comment by kiwifellows** [comment] 2023-02-23 22:41
> * export DOCKER_HOST=unix://"$HOME/.docker/run/docker.sock"

Amen is all I can say.... and when I read the "4 hours" yeap same here!! Almost
Updated my ~/.docker/init-zsh.sh with export DOCKER_HOST=unix://"$HOME/.docker/run/docker.sock"
Works

**Comment by niklasschaeffer** [comment] 2023-03-28 14:46
> Thanks for reporting!
> 
> We're trying to make Docker Desktop more userspace-friendly (e.g., fewer root privileges). As part of that, we're migrating the sockets to user-owned directories rather than root-owned directories (like /var/run).
> 
> Everything should work correctly if you `unset DOCKER_HOST` and let the default socket-picking behavior kick in?
> 
> There's supposed to be some shim code that fixes this automatically, let me check in with some people and get back to you.

Hi, Docker-Desktop for Linux User here.
You can't just remove that without any backwards-compatibility flag or fix. PPL depend on /var/run/docker.sock in different scenarios. And literally running a link to this file after every restart is not the way. At least not for me.

this was the fix for me but literally took me hours to fiddle out.

/usr/lib/systemd/user/docker-desktop.service
```
[Service]
ExecStart=/opt/docker-desktop/bin/com.docker.backend && sudo ln -sf "/home/youruser/.docker/desktop/docker.sock" "/var/run/docker.sock" && sudo chmod 666 /var/run/docker.sock
```

**Comment by tsal** [comment] 2023-04-03 14:27
This has returned in Docker 4.17.0; please provide clear documentation about the environment variable. Using `sudo` to create a symlink to a home dir for a user-land socket is _not a safe option_.

**Comment by fharper** [comment] 2023-04-20 18:15
I'm also having this issue on a new laptop with Docker Desktop 4.18.0 (104112). My workaround was to create a symlink `sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock`

**Comment by Darkslide77** [comment] 2023-04-21 22:01
Issue is still occurring, @fharper solution worked for me.

**Comment by niklasschaeffer** [comment] 2023-04-21 22:45
@Darkslide77 @fharper 

I literally found another working solution to this and this was by simply setting the DOCKER_HOST variable like so.

export DOCKER_HOST="$HOME/.docker/desktop/docker.sock" of for your case probably
export DOCKER_HOST="$HOME/.docker/run/docker.sock"

**Comment by fharper** [comment] 2023-04-24 19:34
@niklasschaeffer: nice, but it assume that apps connecting to the socket don't use default path, but use this environment variable no?

**Comment by niklasschaeffer** [comment] 2023-04-24 20:52
@fharper As long as they respect the DOCKER HOST Enviroment variable i think you won't have any problems at all

**Comment by fharper** [comment] 2023-04-24 21:12
@niklasschaeffer yeah, that's why I prefer to symlink. I would assume most people use the default path as it shouldn't NOT be created by Docker, instead of checking an environment variable that needs to be set by the user. Also, in my case, the app didn't check it :)

**Comment by adler-sudo** [comment] 2023-07-18 23:39
This solves the issue without the need for root access

export DOCKER_HOST=unix://"$HOME/.docker/run/docker.sock"

**Comment by ataylormays-duetto** [comment] 2023-09-07 00:47
I'm having this issue using docker desktop version 4.22.1. Running `sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock` fixes the issue, but as mentioned above this is not a great long-term solution, nor one that should require digging through closed issues to find a resolution for.

**Comment by nicks** [comment] 2023-09-07 12:46
Here's a good doc that explains sockets on Docker Desktop on Mac, and why we're moving away from the root-owned `/var/run/docker.sock`:
https://docs.docker.com/desktop/mac/permission-requirements/
