### ISSUE TITLE
Latest stable (2.5.0.1) breaks the chunking handling in case of an error

### ISSUE THREAD

**Issue by bsideup** [docker/for-mac#5059] opened 2020-11-11 13:58 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
HTTP error response is sent correctly

### Actual behavior
transfer closed with outstanding read data remaining

### Information
* Easy to reproduce
* Breaks http://github.com/docker-java/docker-java

### Steps to reproduce the behavior

```shell
$ curl -v --unix-socket /var/run/docker.sock http://localhost/containers/abcd/json
*   Trying /var/run/docker.sock...
* Connected to localhost (docker.sock) port 80 (#0)
> GET /containers/abcd/json HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Api-Version: 1.40
< Content-Type: application/json
< Date: Wed, 11 Nov 2020 13:51:38 GMT
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.13 (linux)
< Transfer-Encoding: chunked
<
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

(note that it inspects a non-existing container assuming that there is no container with `abcd` as an id)

**Comment by gesellix** [comment] 2020-11-11 21:18
Duplicate? #5058 :)

**Comment by Kissy** [comment] 2020-11-12 11:48
This will probably break a lot of different tools.
I noticed that using https://github.com/test-kitchen/kitchen-dokken/ which is not working anymore after upgrade.

Endpoint /containers/{id}/json is failing to return any body, however /containers/{id}/top is correctly returning a JSON body.

**Comment by thaJeztah** [comment] 2020-11-12 12:04
This looks to be an issue with the API proxy used in docker desktop.

Here's performing the request using `/var/run/docker.sock` (which is the proxied API on Docker Desktop);

```console
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock alpine sh -c 'apk add --no-cache --quiet curl && curl -v --unix-socket /var/run/docker.sock http://localhost/containers/abcd/json'

*   Trying /var/run/docker.sock:0...
* Connected to localhost (/run/host-services/docker.proxy.sock) port 80 (#0)
> GET /containers/abcd/json HTTP/1.1
> Host: localhost
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Api-Version: 1.41
< Content-Type: application/json
< Date: Thu, 12 Nov 2020 12:01:48 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/20.10.0-beta1 (linux)
< Transfer-Encoding: chunked
<
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

And here's the same, but this time mounting `/var/run/docker.sock.raw` (which is the "raw", "non-proxied" API socket, so directly connecting to the docker daemon);

```console
$ docker run -it --rm -v /var/run/docker.sock.raw:/var/run/docker.sock.raw alpine sh -c 'apk add --no-cache --quiet curl && curl -v --unix-socket /var/run/docker.sock.raw http://localhost/containers/abcd/json'

*   Trying /var/run/docker.sock.raw:0...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> GET /containers/abcd/json HTTP/1.1
> Host: localhost
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Api-Version: 1.41
< Content-Type: application/json
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/20.10.0-beta1 (linux)
< Date: Thu, 12 Nov 2020 12:03:53 GMT
< Content-Length: 38
<
{"message":"No such container: abcd"}
* Connection #0 to host localhost left intact
```

**Comment by stephen-turner** [comment] 2020-11-12 15:16
Thanks for the report. I'm going to close this as a dupe of #5025. Please follow that ticket for updates.

**Closed by stephen-turner** 2020-11-12 15:16 UTC
