### ISSUE TITLE
related to #6898: still not solved in my eyes

### ISSUE THREAD

**Issue by RogerWeihrauch** [docker/for-mac#7230] opened 2024-03-30 10:43 UTC
### Description

see also: #6898

Could there be added an information (filed) on which app might have changed the config, since there seems to be no solution on itself? I do not want to de-activate the auto-check of config changes in advanced settings.
Thanks and regards,
Roger

### Reproduce

just starting the docker desktop an waiting for the hint/exclamation mark. (right after start for some seconds)

### Expected behavior

at least a hint on which app did do the last change on the config.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435e5f6216828dec57958c490c4f8bae4f98
  Built:            Wed Feb  7 00:39:16 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
~  $
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/rogiwankenobi/.docker/cli-plugins/docker-scout

Server:
 Containers: 61
  Running: 57
  Paused: 0
  Stopped: 4
 Images: 28
 Server Version: 25.0.3
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.755GiB
 Name: docker-desktop
 ID: 09b61d90-7d07-4731-af0a-f3cf794a60ba
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

Diagnostics ID:     B047141E-0DA7-4FD7-9573-4FFFCB97C51E/20240330103820 (uploaded)

### Additional Info

Did not install docker desktop with brew; installed it from latest .dmg file on docker homepage for macOS.
Also had some issues to keep being logged into my account; also had to re-login into it after each restart of Mac/docker desktop; also when it was configured for autostart when starting my mac.

**Comment by dgageot** [comment] 2024-04-10 12:11
Closing as a duplicate of https://github.com/docker/for-mac/issues/7208
@RogerWeihrauch This should be fixed in 4.29

**Closed** 2024-04-10 12:12 UTC
Labels: needs-triage, version/4.28.0
