### ISSUE TITLE
Error when launching Docker

### ISSUE THREAD

**Issue by Nimisha9297** [docker/for-mac#1262] opened 2017-02-06 08:17 UTC
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/E30F2C95-B588-4E94-8183-C8093DBC7A4A/20170206-000150.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/nimishatrivedi/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW

Every time I launch Docker, it fails with "Fatal Error Exit code 1" 

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. From /Applications folder, click on Docker.app.
  2. While Docker is restarting, I get an error dialog and the app exits showing the above diagnostic information.

**Comment by jesperronn** [comment] 2017-02-06 22:42
Duplicate of #1259?

**Comment by ijc25** [comment] 2017-02-20 13:44
@Nimisha9297, thanks for your report. I see two issues in your logs. A qcow corruption issue and a malloc corruption issue

### QCOW2 Corruption
Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

### malloc corruption

The second issue I see is:

```
com.docker.driver.amd64-linux(65589,0xb07be000) malloc: *** error for object 0x7102198: incorrect checksum for freed object - object was probably modified after being freed.
	*** set a breakpoint in malloc_error_break to debug
```
which is a subtle memory corruption bug which we've been unable to track down. If you are still able to reproduce this issue having done the factory reset to solve the first issue then I would be very grateful indeed if you could try the debugging described in #1143 (comment) and report back.

**Comment by Nimisha9297** [comment] 2017-02-21 23:04
Thank you for your reply.  I was able uninstall Docker and then reinstall
it to get past the error.

**Comment by ijc25** [comment] 2017-02-22 12:07
Thanks for letting us know.

**Closed by ijc25** 2017-02-22 12:07 UTC
Labels: osx/10.10.x, status/0-more-info-needed, status/1-acknowledged, version/1.13.0
