### ISSUE TITLE
Constant issue with the docker on mac

### ISSUE THREAD

**Issue by marcinmaciukiewicz** [docker/for-mac#122] opened 2016-08-04 04:40 UTC
### Information

Diagnostic ID: AD609BAA-64C8-49DD-AC8B-86BBAFB8DA56
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Just start the docker for mac and wait 
2. After some time the invalid json will appear

**Comment by dave-tucker** [comment] 2016-08-09 02:15
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:15 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
