### ISSUE TITLE
Invalid filter 'reference' when using containerd for pulling and storing images

### ISSUE THREAD

**Issue by moogle19** [docker/for-mac#6574] opened 2022-11-13 12:09 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
`docker images --filter "reference=foo*"` should filter for images starting with `foo`.
(Same error for `docker images foo`, `docker image ls foo`, ...)

### Actual behavior
`Error response from daemon: invalid filter 'reference'`

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? **YES**
  - macOS Version: 13.0.1
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.13.1

**Comment by nicks** [comment] 2022-11-14 05:16
Thanks for the report! I'm going to close this as a duplicate of https://github.com/moby/moby/issues/43847, so that there's one place to communicate status on this. Please follow along there!

**Closed by nicks** 2022-11-14 05:16 UTC
