### ISSUE TITLE
Docker quits unexpectedly 

### ISSUE THREAD

**Issue by peraage** [docker/for-mac#294] opened 2016-08-16 06:24 UTC
### Expected behavior

Normal operation

### Actual behavior

Quits unexpectedly while idle

### Information

Diagnostic ID: AE98C776-E71F-446E-970E-D9906B2DFCD7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Docker is running idle.

**Comment by dsheets** [comment] 2016-08-16 10:12
Likely a duplicate of #64. If you see similar behavior once that issue is resolved, please report again. Thanks!

**Closed by dsheets** 2016-08-16 10:12 UTC

**Comment by djs55** [comment] 2016-09-15 16:20
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
