### ISSUE TITLE
Opening Docker 1.13.0 Crashes

### ISSUE THREAD

**Issue by johnpneumann** [docker/for-mac#1297] opened 2017-02-13 22:46 UTC
### Expected behavior
Docker opening.

### Actual behavior
It crashes.

### Information

```
Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1
```

```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/C1C7BC40-D938-4FBE-AFC7-CB77F6BA54AB/20170213-164036.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/randomusername/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/randomusername/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/randomusername/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/randomusername/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/randomusername/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/randomusername/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Open docker
  2. Update window opens
  3. Wait 3-5 seconds
  4. Error dialog appears

Alternatively
  1. Open docker
  2. Update window opens
  3. Dismiss update window
  4. Error dialog appears

**Comment by johnpneumann** [comment] 2017-02-13 22:48
This appears to be related to #1288. If it is, please close.

**Comment by ijc25** [comment] 2017-02-20 17:03
@johnpneumann yes, it does seem to be partially related to #1288 in that it appears to be qcow corruption and a factory reset is the best answer, I'm afraid this will require rebuilding your containers, sorry for the inconvenience.

The actual symptom of the corruption which you experienced looks to be one we've not seen before, I've opened an issue in our internal tracker for that.

I'll close this for now, if a factory reset does not resolve your issue then please let us know.

**Closed by ijc25** 2017-02-20 17:03 UTC
Labels: osx/10.11.x, status/0-triage, version/1.13.0

**Comment by ijc25** [comment] 2017-02-22 11:26
In hindsight I should have left this open to be closed along with our internal ticket when the issue is fixed. This was seen again in https://github.com/docker/for-mac/issues/1318 and I have left that one open as the public tracking ticket, please subscribe there for updates. Sorry for the inconvenience.
