### ISSUE TITLE
socks5 proxy not working despite being supported in docker

### ISSUE THREAD

**Issue by alikhajeh1** [docker/for-mac#1238] opened 2017-01-28 13:05 UTC
### Expected behavior
Socks5 proxy support was added in https://github.com/docker/docker/pull/20366/files (https://github.com/docker/docker/pull/20366/files#diff-ed83b2ed4710331b001c50723dbfbe71R81) so it's expected that it should also work on "Docker for Mac" by using the following settings:
<img width="379" alt="screen shot 2017-01-28 at 4 17 56 pm" src="https://cloud.githubusercontent.com/assets/638577/22396729/f3555884-e575-11e6-84ab-8f8d06fa3540.png">

### Actual behavior
Docker returns the following error when pulling an image:
```
$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: http: error connecting to proxy http://socks5://127.0.0.1:1086: dial tcp: lookup socks5 on 192.168.65.1:53: no such host
```

### Information
Diagnostic ID: 7B9AA021-6426-43BE-9349-CCE6CF08004B
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/7B9AA021-6426-43BE-9349-CCE6CF08004B/20170128-161719.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

```
$ docker info
...
Http Proxy: socks5://127.0.0.1:1086
Https Proxy: socks5://127.0.0.1:1086
```

### Steps to reproduce the behavior
1. Assuming you have a socks5 proxy, goto Docker for Mac and click on Preferences > Proxies, set the HTTP and HTTPS inputs to your proxy address, e.g. `socks5://127.0.0.1:1086`
2. Restart Docker
3. Run `docker pull alpine` and notice the following error:
```
$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: http: error connecting to proxy http://socks5://127.0.0.1:1086: dial tcp: lookup socks5 on 192.168.65.1:53: no such host
```
Notice the `http://` prefix in the error, I wonder if docker for Mac is adding that as we set the proxy value to socks5://...

**Comment by samoht** [comment] 2017-01-30 14:26
Hi, thanks for you report. Docker for Mac doesn't yet support SOCKS5, but we plan to support it at one point. I've escalated your request to our networking team and pointed them to your issue, so you should be notified when we start working on this.

**Comment by d0u9** [comment] 2018-04-12 08:25
socks5 proxy support request.

**Comment by dtaniwaki** [comment] 2018-05-20 10:57
Is it already supported?

**Comment by YRM64** [comment] 2018-05-20 18:29
Enabling socks5 proxies, by nathanleclaire; commented approximately 2 years ago.  If there's been an update to this configuration, please post here.  If anyone has accessed release notes (recently), or any other materials relevant to the subject matter, and know of an update to enabling socks5proxies, please provide that update here to share with the development community, otherwise, the following applies:

$ HTTP_PROXY=socks5://local host:5000
docker info

Happy Coding!

**Comment by depfish** [comment] 2019-04-02 10:07
Hi, socks5 proxy still can't work on Docker for Destop Mac
![20190402180355](https://user-images.githubusercontent.com/28501184/55394552-22345b00-5572-11e9-9447-3882598e423f.jpg)
![20190402180457](https://user-images.githubusercontent.com/28501184/55394553-22345b00-5572-11e9-98c4-b81b4f92203e.jpg)

**Comment by bbaksa** [comment] 2019-05-21 13:56
Hi,

SOCKS5 proxy still not working with Docker version 18.06.1-ce, build e68fc7a. (for Ubuntu 16.04)

**Comment by fizbin** [comment] 2019-09-04 15:13
/remove-lifecycle stale

Still an issue. I suspect (but don't know, because docker desktop's code isn't available) that part of what's happening currently is logic that looks like this:

- if a manual http_proxy is set in preferences, strip off the (protocol://) bit if it's there, and interpret the rest as PROXY_HOST:PROXY_PORT
  - set up a port forward from gateway.docker.internal:3128 to PROXY_HOST:PROXY_PORT
  - set the env. variable HTTP_PROXY to "gateway.docker.internal:3128"

And similarly for an https proxy. This leaves the docker running inside qemu thinking that it has an http proxy to talk to. Instead, I'd like to propose that docker use logic like this:

- if a manual http_proxy is set in preferences, strip off BUT REMEMBER the (protocol://) bit if it's there, and interpret the rest as PROXY_HOST:PROXY_PORT
   - set up a port forward from gateway.docker.internal:3128 to PROXY_HOST:PROXY_PORT
   - set the env. variable HTTP_PROXY to "{PROTOCOL}gateway.docker.internal:3128", where {PROTOCOL} is the (protocol://) bit pulled off the manual proxy setting if it was there (and the empty string if not)

(and similar logic for the heeps proxy)

**Comment by fizbin** [comment] 2019-12-28 19:14
/remove-lifecycle stale

Still a problem on the latest release. It feels like it should be a straightforward fix; is there anything I could do to further investigate?

**Comment by dhoffi** [comment] 2020-02-02 14:20
still not working for Mac OSX docker desktop ...

**Comment by iforwms** [comment] 2020-02-16 12:40
Any updates on this?

**Comment by ahtokca** [comment] 2020-04-02 10:08
Same here. 19.03.8 is not working with socks5

**Comment by jeremychauvet** [comment] 2020-04-03 08:44
Same for me (19.03.8 too)

**Comment by kzhui125** [comment] 2020-05-02 09:14
I use socks5 proxy too, please support it.

Now we can convert socks5 proxy to http proxy:

```dockerfile
FROM alpine:3.11

RUN apk update \
    && apk add privoxy \
    && rm -rf /var/cache/apk/*

CMD ["privoxy","--no-daemon","/etc/privoxy/config"]
```
mount custom config file to /etc/privoxy/config:

```
user-manual /usr/share/doc/privoxy/user-manual/
confdir /etc/privoxy
logdir /var/log/privoxy
actionsfile match-all.action # Actions that are applied to all sites and maybe overruled later on.
actionsfile default.action   # Main actions file
actionsfile user.action      # User customizations
filterfile default.filter
filterfile user.filter      # User customizations
logfile privoxy.log
listen-address  0.0.0.0:1080
forward-socks5 / socks5_ip:socks5_port .
toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 0
trusted-cgi-referer http://www.example.org/
forwarded-connect-retries  0
accept-intercepted-requests 0
allow-cgi-request-crunching 0
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
```

    ports:
      - "1080:1080"

**Comment by we08guyy** [comment] 2020-05-22 06:19
Same. 19.03.8. When will working on this?

**Comment by stephen-turner** [comment] 2020-05-22 08:46
We now have a public roadmap, at http://github.com/docker/roadmap, where people can also add and vote on feature requests. As this is a feature request not a bug, I think that would now be the more appropriate place. So I'm going to close this ticket, but whoever is interested in this should create an issue over there. Thanks.

**Closed by stephen-turner** 2020-05-22 08:46 UTC
Labels: area/network, osx/10.12.x, status/1-acknowledged, version/1.13.0

**Comment by sajTempler** [comment] 2020-05-31 18:01
Hey

if anyone is still interested please upvote:
https://github.com/docker/roadmap/issues/100
