### ISSUE TITLE
Docker App Causing mDNSresponder to run on port 53

### ISSUE THREAD

**Issue by cstetson** [docker/for-mac#7033] opened 2023-10-16 03:17 UTC
### Description

When I run Docker Desktop mDNSresponder takes over port 53 tcp/udp. 

After Launching Docker Desktop
```
1|cstetson > sudo lsof -i :53
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mDNSRespo 480 _mdnsresponder   29u  IPv4 0x3476ace87252be0d      0t0  UDP *:domain
mDNSRespo 480 _mdnsresponder   86u  IPv6 0x3476ace87252c60d      0t0  UDP *:domain
mDNSRespo 480 _mdnsresponder   91u  IPv4 0x3476aced4abdf31d      0t0  TCP *:domain (LISTEN)
mDNSRespo 480 _mdnsresponder   92u  IPv6 0x3476aced3816014d      0t0  TCP *:domain (LISTEN)
```
After quitting:
```
2|cstetson > sudo lsof -i :53
3|cstetson >
```
This seems to have started with [4.22.0](https://docs.docker.com/desktop/release-notes/#4220)

Given the history, this looks like it might be a regression as well.

### Reproduce

1. Load Docker.app
2. sudo lsof -i :53
3. Quit Docker.app
4. sudo lsof -i :53

### Expected behavior

mDNSresponder should not load on port 53 tcp/udp

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/cstetson/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/cstetson/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/cstetson/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/cstetson/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/cstetson/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/cstetson/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/cstetson/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/cstetson/.docker/cli-plugins/docker-scout

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 89
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 23.45GiB
 Name: docker-desktop
 ID: 34dc3663-5acf-4cc2-8a2e-5eebfa41f088
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

AA7EA5AD-C17B-45C1-8CD7-686F81A2F0F9/20231016030942

**Comment by bsousaa** [comment] 2023-10-16 10:23
This is a duplicate of https://github.com/docker/for-mac/issues/7008. See temporary workaround at https://github.com/docker/for-mac/issues/7008#issuecomment-1746653802.

**Closed by bsousaa** 2023-10-16 10:23 UTC
Labels: status/duplicate, version/4.24.2
