### ISSUE TITLE
And it still dies, Sierra beta 5

### ISSUE THREAD

**Issue by thatGuy0923** [docker/for-mac#313] opened 2016-08-16 20:30 UTC
### Expected behavior
Run docker and docker commands

### Actual behavior
Unable to launch the docker-cli and error with com.docker.osxfs

### Information
Normal startup on docker osx

Diagnostic ID: E9677F52-FD1F-4369-A9DF-9076A2590E17
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Download docker
2. Run the application on Sierra beta 5

**Comment by dsheets** [comment] 2016-08-17 09:11
This is likely caused by the ongoing issues with golang and macOS Sierra Beta. This is a duplicate of #64.

**Closed by dsheets** 2016-08-17 09:11 UTC

**Comment by djs55** [comment] 2016-09-15 16:19
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
