### ISSUE TITLE
Docker quits on macOS 10.12 Beta

### ISSUE THREAD

**Issue by axelschulz** [docker/for-mac#535] opened 2016-09-07 07:44 UTC
### Expected behavior
Docker keeps running

### Actual behavior
Shortly after starting Docker it quits with a json error message 

### Information

Diagnostic ID: 994EF04C-4744-44D0-BF0E-FAD91D6EA0F0
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install macOS 10.12 Beta 7
2. Run Docker

**Comment by mchiang0610** [comment] 2016-09-07 13:12
@axelschulz Thanks for reporting. We are looking into issues related with macOS Sierra. 

I'm currently running macOS 10.12 beta 7 as well, and am unable to reproduce this.

**Comment by dsheets** [comment] 2016-09-07 13:27
This was tracked by #64 and has been fixed in the beta channel. The fix for the stable channel should arrive within a week.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version.

**Closed by dsheets** 2016-09-07 13:27 UTC
Labels: area/osx, kind/bug, osx/10.12 (beta), version/1.12.0

**Comment by axelschulz** [comment] 2016-09-14 10:12
thx guys

**Comment by djs55** [comment] 2016-09-15 16:05
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
