### ISSUE TITLE
Container logs inspection from Dashboard not shown since 3.3.3

### ISSUE THREAD

**Issue by k3v3n** [docker/for-mac#5688] opened 2021-05-14 11:08 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior

Logs from the container Logs tab should be displayed

### Actual behavior

They are not anymore

### Information
  - macOS Version: 11.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. None

**Comment by hutchy2570** [comment] 2021-05-14 12:27
I see the same on 3.3.3.  Was fine on 3.3.2.

**Comment by stephen-turner** [comment] 2021-05-14 12:49
I can't reproduce this. It's working fine for me. Could you give steps to reproduce please?

**Comment by k3v3n** [comment] 2021-05-14 12:57
Ok so I tried it out again this morning and it seems that it may be related to the way we are logging into our container. I have tested out other containers from the hub and logs do show. I think we should close the ticket.

**Comment by HugoNeves** [comment] 2021-05-20 17:14
> Ok so I tried it out again this morning and it seems that it may be related to the way we are logging into our container. I have tested out other containers from the hub and logs do show. I think we should close the ticket.
Can you explain what do you mean by "the way we are logging into our container"?

I'm having the same issue since version 3.3.3 on Mac also. Was perfect before.

In my case, I'm running a Faust application and only the first lines of the logs appear.

**Comment by StefanScherer** [comment] 2021-06-05 07:04
Thanks for the report. This issue seems to be related to https://github.com/docker/for-win/issues/11251
We found out that stderr is not displayed and we're working on a fix.

**Comment by mat007** [comment] 2021-06-10 06:57
A fix has been released in Docker Desktop 3.4.0, see [the release notes](https://docs.docker.com/docker-for-mac/release-notes/#bug-fixes-and-minor-changes)!

**Closed by mat007** 2021-06-10 06:57 UTC
