### ISSUE TITLE
Docker extracts remote file on add

### ISSUE THREAD

**Issue by huntsberg** [docker/for-mac#1937] opened 2017-08-05 00:12 UTC
### Expected behavior
When adding a compressed file from a remote server, it should copy the file and not extract it, per the documentation.

See:
https://docs.docker.com/engine/reference/builder/#add

- If src is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed.

### Actual behavior
The file is retrieved and extracted as if it were a local file.

### Information
- Version info

Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0

- Dockerfile
<pre><code>FROM centos:7

ADD http://www.cpan.org/src/5.0/perl-5.26.0.tar.gz /opt/perl/</code></pre>

- docker-compose.yml
<pre><code>version: '3'
services:
    test:
        build: .
</code></pre>

### Steps to reproduce the behavior

  1. Run these steps:
`$ docker-compose build`
`$ docker-compose run --rm test bash`
`<container_id># cd /opt/perl`
`<container_id># ls`
  2. The remote archive was extracted into perl-5.26.0 instead of being copied as perl-5.26.0.tar.gz

**Comment by dsheets** [comment] 2017-08-05 13:41
This is a duplicate of #1680 and moby/moby#33849. The fix will be in 17.06.1.

**Closed by dsheets** 2017-08-05 13:41 UTC
