### ISSUE TITLE
HTTP Layer 7 non-transparent (i.e. buggy) proxy with Docker desktop 3.3.1 ?

### ISSUE THREAD

**Issue by paje** [docker/for-mac#5641] opened 2021-04-30 07:59 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

curl should work without problem, directly from the container to the outside

### Actual behavior

Whatever the container is (i.e. Alpine latest, Unbutu Latest, CentOS7 or CentOS8, the curl fails if specifying an host header

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? yes
  - Did the problem appear with an update? yes 
  - macOS Version: BigSur 11.3
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. Install an unix container

    FROM alpine
    ENV container test
    RUN apk add -U --no-cache \
        bash \
        curl 

  2. From the container Try the following command

    docker build . -t test && docker run -it test curl -v -A "MyTest"  --header 'Host: www.nondnshost.com' http://www.google.com

the output is something like 

    *   Trying 142.250.186.100:80...
    * Connected to www.google.com (142.250.186.100) port 80 (#0)
    > GET / HTTP/1.1
    > Host: www.nondnshost.com
    > User-Agent: MyTest
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 500 Internal Server Error
    < Content-Type: text/plain; charset=utf-8
    < X-Content-Type-Options: nosniff
    < Date: Fri, 30 Apr 2021 07:49:51 GMT
    < Content-Length: 59
    <
    lookup www.nondnshost.com on 192.168.65.5:53: no such host
    * Connection #0 to host www.google.com left intact

The line 
**lookup www.nondnshost.com on 192.168.65.5:53: no such host**
- is logically an answer from the website (not part of the -v output)
- Is not answered by the targeted website (in that case google, but whatever the website is, it's the same msg)
- Does not appear on a wireshark investigation on the mac (i.e. not going in/out from the mac)
- Same behavior occurs with python curl (while the unittest to check our website behavior) and other linux distribution --> not curl version dependant
- the host header is normally only interpreted by the webserver (specific HTTP Layer7)  
- Occurs with or without VPN activated on the Mac (i.e. might be related to https://github.com/docker/for-mac/issues/5492 or not)
- On Docker Desktop 3.2 works fine
- Ping is working fine (i.e. website reachable)
  
The only logical reason i would see, is a kind of (buggy) L7 Proxy on the docker side (?!) 

On 3.2, the same command output is clearly an output from the google website

    * Connected to www.google.com (142.250.186.100) port 80 (#0)
    > GET / HTTP/1.1
    > Host: www.nondnshost.com
    > User-Agent: MyTest
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 404 Not Found
    < Content-Type: text/html; charset=UTF-8
    < Referrer-Policy: no-referrer
    < Content-Length: 1561
    < Date: Fri, 30 Apr 2021 07:58:27 GMT
    <
    <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That’s an error.</ins>
      <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
    * Connection #0 to host www.google.com left intact

**Comment by stephen-turner** [comment] 2021-04-30 09:02
Thanks for the report, I believe this is a dupe of #5571.

**Closed by stephen-turner** 2021-04-30 09:02 UTC
