### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by worldchanger** [docker/for-mac#5453] opened 2021-03-13 19:41 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C5D494E3-CCCC-4692-BDDE-38E0F1CCE4BD/20210313193256

### Expected behavior
I expect to be able to bind to port 53

### Actual behavior
When I attempt to start a container and bind to port 53 I get the following error:

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (6e80cf4a0735884899a14fc7231030928ebf45eab607494bc3f7b1cfd964d073): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

### Information
Everything worked fine until I updated to 3.2.1.  I tried downgrading to 3.2.0 but things fail.  Instead, I installed 3.1.0 and everything works fine.  

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.2.1

### Steps to reproduce the behavior
Upgrade Docker Desktop to 3.2.1

`version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'PASSWORD-HERE'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped`

**Comment by StefanScherer** [comment] 2021-03-15 09:11
Thanks @worldchanger for the report. This is a duplicate of #5416. We're working on a fix.

**Closed by StefanScherer** 2021-03-15 09:11 UTC
Labels: version/3.2.1
