### ISSUE TITLE
Docker continuously restarts and never finishes after inline upgrade to 1.13.0-rc3-beta32(14523)

### ISSUE THREAD

**Issue by bclairmont** [docker/for-mac#1043] opened 2016-12-14 14:52 UTC
### Expected behavior
Usually after the upgrades everything is stable, fine and right as rain.

### Actual behavior
Docker icon shows that it never starts up.

### Information
Docker for Mac: version: 1.13.0-rc3-beta32 (9cf974f9e)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/DC8A14B2-E07B-49EF-B193-DBFEEDB18E48/20161214-064754.tar.gz
[20161214-064754.tar.gz](https://github.com/docker/for-mac/files/652023/20161214-064754.tar.gz)

failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Diagnostic-ID: DC8A14B2-E07B-49EF-B193-DBFEEDB18E48

### Steps to reproduce the behavior
rebooted twice and it still stays in restating mode.

**Comment by jeanlaurent** [comment] 2016-12-15 10:24
Hi @bclairmont and we're very sorry you stumble on this one.

The issue is under investigation by the development team.

As a workaround, we invite you to perform a factory reset to get things working again.

**Comment by dsheets** [comment] 2017-01-17 15:47
This was fixed in Beta 34.

**Closed by dsheets** 2017-01-17 15:47 UTC
Labels: kind/bug, osx/10.11.x, status/2-in-progress, version/beta32
