### ISSUE TITLE
Docker for Mac completely broken

### ISSUE THREAD

**Issue by idris** [docker/for-mac#1398] opened 2017-03-06 21:51 UTC
### Expected behavior
Docker for Mac should work as expected.

### Actual behavior
Nothing works.  Not even `docker ps`.  Docker seems to keep restarting, when it realizes it isn't working.

### Information
Diagnostic ID: 9949C8B0-BB4A-4DC0-BC3E-CEECBA24CFE8
Diagnostic Log:
```
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/9949C8B0-BB4A-4DC0-BC3E-CEECBA24CFE8/20170306-132634.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

Diagnostic log gives me different results every time I run it.  Sometimes everything says `OK`, other times just one of `docker-cli` or `oxfs` will show an `ERROR`.

This happens on `Version 17.03.0-ce-mac2 (15654)`, and also happened on the previous release (ending in `-mac1`)

**Comment by buu700** [comment] 2017-03-06 23:34
I ran into this as well after upgrading from `-mac1` to `-mac2`, and then it was consistently reproducible even after downgrading back to `-mac1` and `-mac1` rc1. (I forgot to run the diagnostic before switching to the stable channel, though; sorry.)

**Comment by dsheets** [comment] 2017-03-07 10:17
@idris the issue is a change in the Linux distribution we ship that now puts something in the `/mnt` directory in the VM (compared to earlier versions where it was empty). If you change your file system export settings in :whale: ➡️ `Preferences...` ➡️ `File Sharing` and remove `/mnt` and then re-add more specific directories (e.g. `/mnt/mydrive`) it should resume working.

This is the same issue as #1379 so I'm going to close it as a duplicate of that. Please subscribe there if you wish to track resolution. I've opened an issue to track handling export directory invalidation over Linux upgrades. Thanks for your report and I'm sorry for the inconvenience this has caused. We're improving our component integration to reduce incidents like these in the future.

**Comment by idris** [comment] 2017-03-07 22:26
@dsheets I am unable to change those settings.  I removed `/mnt` and added my more specific directories, then click "Apply & Restart".

Sometimes it does nothing (and when I try to close the settings window it says I have unsaved changes).  Other times it pops up this wonderful EOF alert:
![screen shot 2017-03-07 at 2 25 21 pm](https://cloud.githubusercontent.com/assets/13989/23680993/0a6f4c20-0342-11e7-9328-2a5da75bc0de.png)

**Comment by dsheets** [comment] 2017-03-08 10:16
@idris That is surprising behavior and I can reproduce it locally. I'm sorry but this looks like another issue (possibly related to the VM image/Docker app configuration incompatibility). I will investigate the EOF issue and use this ticket to track its resolution.

In the mean time, you should be able to get back to a working state by doing these steps:

1. `cd ~/Library/Containers/com.docker.docker/Data/database`
2. `git reset --hard`
3. `sed -i -e '/\/mnt:\/mnt/d' com.docker.driver.amd64-linux/mounts`
4. `git add com.docker.driver.amd64-linux/mounts`
5. `git commit -m "manually remove /mnt from mounts due to Docker for Mac issue 1398"`

**Comment by idris** [comment] 2017-03-08 19:13
@dsheets that worked, thanks.

I'd like to take a moment to commend you on these responses.  Not only have you responded in a reasonable amount of time, but your solutions are on point.  I have never seen someone respond to a bug report so thoroughly and efficiently.

Kudos! 🎉

**Closed** 2017-07-24 14:44 UTC
Labels: area/gui, area/linux, area/mounts, kind/bug, osx/10.12.x, status/1-acknowledged, version/17.03.0-ce-mac2
