### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by pulkitsinghal** [docker/for-mac#946] opened 2016-11-14 20:29 UTC
### Expected behavior
docker pull should work

### Actual behavior
docker pull fails

### Information

DIAGNOSTIC ID: 47021F7F-3974-471F-8122-BEBC39EA0ECD

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/47021F7F-3974-471F-8122-BEBC39EA0ECD/20161114-142503.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. docker pull <repo>
  2. doesn't work:

    ```
    Pulling repository docker.io/library/elasticsearch
    Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/elasticsearch/images. You may want to check your internet connection or if you are behind a proxy.
    ```

**Comment by ijc25** [comment] 2016-11-15 11:11
@pulkitsinghal thanks for your report. I believe this is a duplicate of #932. Please subscribe to that ticket for further updates. There are also some workarounds described in the comments which may work for you until a fix is released.

**Closed by ijc25** 2016-11-15 11:11 UTC
Labels: area/network, kind/bug, osx/10.11.x, status/1-acknowledged, version/beta30
