### ISSUE TITLE
Docker Client cannot restart on Mac

### ISSUE THREAD

**Issue by funkydorian** [docker/for-mac#793] opened 2016-10-12 21:04 UTC
### Information

Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/21DEB528-D468-49AA-A480-0592DACD92CC/20161012-235623.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior

https://github.com/docker/dcus-hol-2016/tree/master/docker-developer
1. docker-compose is run for Cats vs Dogs  on UCP (With env variables pointing UCP)
2. On same directory docker-compose is run for Cats vs Dogs (Without env variables pointing UCP, deploying local)
3. localhost:5000 , localhost:5001 is working(Cats and Dogs working on local)
4. app.py under vote directory is changed
5. Docker daemon crashed

My assumption: Both UCP and local tried to refresh themselves after the file change but somehow locked

**Comment by funkydorian** [comment] 2016-10-12 21:34
I uninstalled and installed again, now seems ok

**Comment by samoht** [comment] 2016-10-13 17:17
@funkydorian your log contains:

```
Docker[com.docker.osx.hyperkit.linux][559] <Notice>: Reap com.docker.osxfs (pid 8161): signal: illegal instruction
```

which doesn't sound very good. I'll escalate the issue to the team. Thanks again for your report!

**Comment by samoht** [comment] 2017-01-30 20:31
I am closing this issue as we believe the root cause is now fixed.

**Closed by samoht** 2017-01-30 20:31 UTC
Labels: osx/10.11.x, status/3-fixed, version/beta26.1
