### ISSUE TITLE
Allow manual entries in File Sharing settings of Docker for Mac OSX

### ISSUE THREAD

**Issue by eanvafaei** [docker/for-mac#884] opened 2016-11-02 06:21 UTC
Currently, the only allowed method is selecting from a pop-up, however, the pop-up will not allow selecting volumes like /var or /etc but add them as /private/var or /private/etc. So if the docker config is set to use /var, as it's volume, it will fail to start.
This is a problem where there is a mix of Linux and Mac machines using docker and docker-compose to setup development environment.

**Comment by dsheets** [comment] 2016-11-02 09:58
This is a duplicate of #412 which is on the roadmap for our GUI team. I'm really sorry this is preventing you from reusing your development configuration. Please subscribe to #412 for updates.

**Closed by dsheets** 2016-11-02 09:58 UTC

**Comment by dsheets** [comment] 2017-01-16 15:50
This was fixed in Beta 33 and has been recently improved in Beta 35 or 36 so that exported directory paths are editable and now manually enterable by editing a blank entry at the end of the list.

Thanks for your patience with this issue and for using Docker for Mac. This improvement should reach the stable channel in a week or two.
