### ISSUE TITLE
docker-cli hangs after waking up Macbook from sleep

### ISSUE THREAD

**Issue by harshjv** [docker/for-mac#1097] opened 2016-12-31 11:43 UTC
### Diagnostic ID
    D9AB985C-A83E-4EFB-BD77-79AA72413236

### Expected behavior
`docker start x` should start docker container `x`.

### Actual behavior
`docker start x` hangs and throws error;

    An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/x/start: EOF

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Put Macbook to sleep.
  2. Wake it up and try `docker start x`

**Comment by djs55** [comment] 2017-01-03 11:00
In diagnostic upload D9AB985C-A83E-4EFB-BD77-79AA72413236/20161231-170222 I observe the following:

- you're running 1.12.5, latest stable
- `docker ps` inside the VM works
- `date` inside the VM seems to match `date -u` on the host

The docker log has:
```
time="2016-12-31T11:33:28.089940407Z" level=debug msg="Calling GET /containers/some-mongo/json" 
time="2016-12-31T11:33:28.093226687Z" level=debug msg="Calling POST /v1.24/containers/some-mongo/start" 
time="2016-12-31T11:33:28.097729823Z" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/87e1fb49656c4f50f9cda757b803f1432a2e0782015d2c0918d183b35480a952" 
time="2016-12-31T11:33:28.098549236Z" level=debug msg="Assigning addresses for endpoint some-mongo's interface on network bridge" 
time="2016-12-31T11:33:28.099113898Z" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])" 
time="2016-12-31T11:33:28.111483974Z" level=debug msg="Assigning addresses for endpoint some-mongo's interface on network bridge" 
time="2016-12-31T11:33:28.173707497Z" level=debug msg="Programming external connectivity on endpoint some-mongo (1cf950759e0ea8d9ccb8ab49f3a165ba012637a0a139b45c02bc1fd2a0d5466d)" 
time="2016-12-31T11:33:28.174676720Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 27017 -j DNAT --to-destination 172.17.0.3:27017 ! -i docker0]" 
time="2016-12-31T11:33:28.186634712Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.3 --dport 27017 -j ACCEPT]" 
time="2016-12-31T11:33:28.200494403Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.3 -d 172.17.0.3 --dport 27017 -j MASQUERADE]" 
time="2016-12-31T11:33:28.473369294Z" level=debug msg="sandbox set key processing took 100.65378ms for container 43999159fe90334bf088679320ede147108340d7626e4f7fad79d262e1774309" 
time="2016-12-31T11:33:28.558839684Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"43999159fe90334bf088679320ede147108340d7626e4f7fad79d262e1774309\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc820874b50)}" 
time="2016-12-31T11:33:28.602340312Z" level=debug msg="libcontainerd: event unhandled: type:\"start-container\" id:\"43999159fe90334bf088679320ede147108340d7626e4f7fad79d262e1774309\" timestamp:<seconds:1483184008 nanos:558291659 > " 
time="2016-12-31T11:34:09.754000518Z" level=debug msg="Calling GET /v1.24/containers/json" 
```
The final line is triggered by the `docker ps` from the diagnostic scripts. The previous lines around 11:33:28 seem to correspond to a `docker start`.

@harshjv does this happen every time you wake from sleep? Or perhaps only when the sleeping is for more than a certain amount of time? Are you on battery or plugged into an electricity supply when it happens?

**Comment by joe-mojo** [comment] 2017-01-03 13:45
Diagnosis ID : DC98AAF4-6FF5-41CE-9855-B244654D1197
I have the same issue.

**Comment by harshjv** [comment] 2017-01-03 13:56
@djs55 Macbook was plugged and this doesn't happen every time.

It happened when I kept Macbook sleeping for approximately half a minute and then started it again.

**Comment by djs55** [comment] 2017-01-03 14:46
I've tried to reproduce this by sleeping with `pmset sleepnow` and then `docker start` but I can't seem to trigger the problem. There have been lots of fixes in the docker engine in 1.13 -- could you try the latest beta 34.1, which will soon be released as stable? The latest beta is available from https://download.docker.com/mac/beta/Docker.dmg

**Comment by dcosson** [comment] 2017-01-10 20:00
I have this issue as well. It's difficult to reproduce because I never really know when my mac is going into full sleep. For instance if I wake it shortly after the time out screen lock happens, or if I lock the screen with ctrl+shift+power and then wake it up a few minutes later, I don't get this issue. But waking my computer in the morning after it's been in sleep mode all night almost always causes docker to hang.

I typically have my docker compose environment up at all times with at least one `docker exec` shell to my dev image, and the shell hangs (can't type anything or exit it with ctrl+d) plus docker commands like `docker ps` also hang. I generally quit docker then open it again, and it comes back up after 30 sec to a minute. 

I was on docker for mac 1.12.3 until a couple weeks ago and this happened much less frequently, 1.12.5 seems a lot worse.

**Comment by samoht** [comment] 2017-01-30 14:31
@dcosson would you mind opening a new issue with a diagnostic ID, it will make easier for us to keep track of your issue.

@harshjv I am closing this issue as we didn't hear back from you, but please feel free to re-open it if the issue still persists. If you manage to track down some reproducible steps it would be very useful as well.

**Closed by samoht** 2017-01-30 14:31 UTC

**Comment by dcosson** [comment] 2017-01-30 21:58
@samoht Thanks for following up. I think 1.13 has fixed this issue for me (or it was unrelated and stopped happening for another reason). I'll open a new issue if I start seeing this again.
