### ISSUE TITLE
docker will not start

### ISSUE THREAD

**Issue by connercowling** [docker/for-mac#968] opened 2016-11-18 21:34 UTC
### Expected behavior

Docker starts up on boot.

### Actual behavior

"Docker starting..." indefinitely, even after restarting, quitting, reinstalling

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Here's the diagnose output

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/2C509C29-0392-4595-9E26-D0EDCE75990A/20161118-153237.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by blueshirts** [comment] 2016-11-18 21:57
Ditto...

**Comment by jmaclabs** [comment] 2016-11-19 22:14
I just filed an issue, might be a duplicate of this one. My issue has more/full details: https://github.com/docker/for-mac/issues/970

**Comment by connercowling** [comment] 2016-11-20 02:07
@jmaclabs that worked! thanks much :)

**Closed** 2016-11-20 02:07 UTC
