### ISSUE TITLE
Re. Docker push fails with most builds on my home machine #20936 - please address for OSX

### ISSUE THREAD

**Issue by abawany** [docker/for-mac#621] opened 2016-09-14 15:30 UTC
### Expected behavior

Issues #20936 and #22443 appear to not have been addressed for OSX, afaict. The `docker daemon` command is not supported on OSX and refers the user to `dockerd`, which also appears to be missing. How is an OSX user expected to adjust the`--max-concurrent-uploads` and `--max-concurrent-downloads` parameters to be able to upload images while on poor connections, please? I am running Docker 1.12.0-a.
### Actual behavior

I would like to be able to control the upload/download concurrency parameter so that I can upload/download images on low-bandwidth networks without dealing too much with unnecessary timeouts. The default concurrency of 3 (for download) and 5 (for upload) is hurting performance by causing repeated timeouts and requiring tiresome manual retries to upload relatively small images.
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu: AE207E7C-BB19-470D-B6B5-F9CC25876632
- host distribution and version (OSX 10.10.x, OSX 10.11.x): OSX 10.11.5
### Steps to reproduce the behavior
1. Look at #20936 and #22443 and try to control the concurrency parameter using the steps specified in the push requests.
2. Look in Docker UI for any ability to control concurrency parameter.

EDIT: syntax.

**Comment by thaJeztah** [comment] 2016-09-14 15:46
for reference, the issues referred to are https://github.com/docker/docker/issues/20936, and https://github.com/docker/docker/issues/22443 (in the docker/docker issue tracker)

**Comment by mchiang0610** [comment] 2016-09-14 16:15
@abawany Thanks for submitting this. We will look to reproduce on our side.

**Comment by thaJeztah** [comment] 2016-09-14 16:38
@mchiang0610 it's not really a bug, but more an enhancement; it's currently not possible to configure a daemon.json on docker for Mac, so some settings/configuration changes are not easily made. I saw there's an internal issue tracking the addition of MaxConcurrent uploads/downloads to the UI

**Comment by abawany** [comment] 2016-09-15 16:58
I would add that I would appreciate a pointer to any method to change this behavior on the current version, even if it is complicated. Since my upstream network is problematic, performing image uploads from my OSX machine currently is quite painful.

**Comment by ceharris** [comment] 2016-09-19 10:49
+1

My upstream network bandwidth cannot support the default 5 concurrent uploads (which is, IMO, way too aggressive to use as a default). Any solution to providing `DOCKER_OPTS`, `daemon.json`, or some other alternative for Docker on Mac would be better than the current situation.

As it stands now, I'm back to running Docker in Linux VM on my Mac just so I can push successfully. That sucks.

**Comment by thaJeztah** [comment] 2016-09-19 12:52
@abawany @ceharris it _is_ possible, but **these instructions are at your own risk** 😇 

On your Mac:

    cd ~/Library/Containers/com.docker.docker/Data/database/

That location is a git repo, the key you want is 

    com.docker.driver.amd64-linux/etc/docker/daemon.json

First reset local changes (` git reset --hard --`), then you can add the directory if it doesn't exist;

    mkdir -p com.docker.driver.amd64-linux/etc/docker/

And create a daemon.json containing, for example:

```json
{"labels":["foo=bar"]}
```

Add the file, and commit the changes:

```bash
git add com.docker.driver.amd64-linux/etc/docker/daemon.json
git commit -m 'set labels on daemon'
```

Docker should automatically restart on git commit, but otherwise restart yourself

Afterwards, confirm that your changes applied;

```bash
docker info

[snip]
Registry: https://index.docker.io/v1/
Labels:
 foo=bar
Experimental: true
Insecure Registries:
 127.0.0.0/8
[snip]
```

**Comment by ceharris** [comment] 2016-09-19 13:17
I added a `daemon.json` as noted above containing `{ "max-concurrent-uploads": 2 }` and now I can push successfully. Awesome!

**Comment by john2x** [comment] 2016-10-07 00:35
Just to be clear, the `daemon.json` file should contain `{"max-concurrent-uploads": 2}` (and not {"labels": ["max-concurrent-uploads=2"]}`)

**Comment by Random-Primate** [comment] 2016-11-13 18:24
Awesome, this works great. Plus having the `daemon.json` file around is really great

**Comment by m0smith** [comment] 2016-11-26 23:03
Many thanks!!! Worked for me as well.

**Comment by dsheets** [comment] 2016-12-13 14:44
Since Beta 31, `daemon.json` is editable via :whale: ➡️ `Preferences...` ➡️ `Daemon` ➡️ `Advanced`.

**Comment by samoht** [comment] 2017-01-30 20:22
Closing this as it is now possible to edit the daemon config in the UI on both the stable and beta channels.

**Closed by samoht** 2017-01-30 20:22 UTC
Labels: area/docker, area/gui, kind/enhancement, osx/10.10.x, osx/10.11.x, status/4-fix-released-beta, version/1.12.0
