### ISSUE TITLE
Preferences UI doesn't handle very well adding/removing directories if overlapping

### ISSUE THREAD

**Issue by tpoindessous** [docker/for-mac#1347] opened 2017-02-27 16:05 UTC
### Expected behavior
If I want to remove a shared directory, then add another parent directory, I should be able to do it without restarting Docker at each step.

### Actual behavior

I get an error and I need to restart Docker at each step

### Information

  - Diag number : 4F829609-BE15-45E5-8B5C-A8480FAD563D

### Steps to reproduce the behavior

  1. Change your docker conf and share a sub-directory (in my example : /Users/thomas/Projets/perso )
<img width="391" alt="capture d ecran 2017-02-13 a 19 02 53" src="https://cloud.githubusercontent.com/assets/3054608/23368497/580948d0-fd0e-11e6-9166-e6d0d1ccbe62.png">

  2. Remove that directory by clicking on the minus button

  3. Add a new shared directory which is a parent directory of the previous one (in my example: /Users/thomas)
<img width="387" alt="capture d ecran 2017-02-13 a 19 04 18" src="https://cloud.githubusercontent.com/assets/3054608/23368612/b2a1e432-fd0e-11e6-8e98-a86d97eea774.png">

  4. Click on "Apply & Restart"

  5. I got this error :
<img width="617" alt="capture d ecran 2017-02-13 a 19 04 34" src="https://cloud.githubusercontent.com/assets/3054608/23368658/d5dabb22-fd0e-11e6-8349-6714c620944b.png">

**Comment by dsheets** [comment] 2017-02-28 15:23
I believe this is a duplicate of #139. We are aware that this behavior is far from ideal but, as there is a straightforward work-around and export directory changes are relatively uncommon, we haven't prioritized it. Please subscribe to #139 for updates or re-open this issue if you don't think that it's a duplicate of #139.

**Closed by dsheets** 2017-02-28 15:23 UTC
Labels: status/0-triage
