### ISSUE TITLE
kubernetes rbac rules (still) not enforced

### ISSUE THREAD

**Issue by davidje13** [docker/for-mac#4774] opened 2020-07-14 11:23 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

This is a refresh of #3694, as that issue was believed to be fixed but actually still exists in 2.3.0.3 (45519). The old issue has been locked due to age.

Run the following:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: test-sa
  containers:
  - image: alpine
    name: test-container
    command: [sh]
    args:
    - -ec
    - |
      apk add curl;
      KUBE_NAMESPACE="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)";
      curl \
        --cacert "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" \
        -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
        "https://kubernetes.default.svc/api/v1/namespaces/$KUBE_NAMESPACE/services";
      while true; do sleep 1; done;
```

```sh
kubectl apply -f test.yml
kubectl logs test-pod
```

### Expected behavior

Permissions error (403)

### Actual behavior

API request succeeds

### Information

```sh
kubectl get clusterrolebinding docker-for-desktop-binding -o yaml
```

> ```
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRoleBinding
> metadata:
>   creationTimestamp: "2020-06-22T13:01:34Z"
>   name: docker-for-desktop-binding
>   resourceVersion: "478"
>   selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/docker-for-desktop-binding
>   uid: f4d43180-d35e-448c-ba41-db0a1330baff
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: cluster-admin
> subjects:
> - apiGroup: rbac.authorization.k8s.io
>   kind: Group
>   name: system:serviceaccounts
>   namespace: kube-system
> ```

```sh
kubectl auth can-i --list --as system:serviceaccount
```

> ```
> Resources                                       Non-Resource URLs   Resource Names   Verbs
> *.*                                             []                  []               [*]
>                                                 [*]                 []               [*]
> selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
> selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
>                                                 [/api/*]            []               [get]
>                                                 [/api]              []               [get]
>                                                 [/apis/*]           []               [get]
>                                                 [/apis]             []               [get]
>                                                 [/healthz]          []               [get]
>                                                 [/healthz]          []               [get]
>                                                 [/livez]            []               [get]
>                                                 [/livez]            []               [get]
>                                                 [/openapi/*]        []               [get]
>                                                 [/openapi]          []               [get]
>                                                 [/readyz]           []               [get]
>                                                 [/readyz]           []               [get]
>                                                 [/version/]         []               [get]
>                                                 [/version/]         []               [get]
>                                                 [/version]          []               [get]
>                                                 [/version]          []               [get]
> ```

rnsv posted the necessary fix in the old issue here: https://github.com/docker/for-mac/issues/3694#issuecomment-619474504 (the namespace was applied to the wrong part of the spec)

### Diagnostic logs

```
Docker for Mac: 2.3.0.3 (45519)
```

**Comment by davidje13** [comment] 2020-07-14 11:32
In the meantime, users can patch this issue on their own deploys by running:

```bash
kubectl apply -f - <<EOF                                         
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-for-desktop-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:kube-system
EOF
```

(it will complain about "kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply" but it will work. I don't know if it will cause problems with docker-desktop upgrades in the future)

**Comment by sixeyed** [comment] 2020-07-22 07:12
A patch might be a better workaround - it will fail if the binding doesn't exist:

```
 kubectl patch clusterrolebinding docker-for-desktop-binding --type=json --patch $'[{"op":"replace", "path":"/subjects/0/name", "value":"system:serviceaccounts:kube-system"}]'
```

- or in Powershell which needs the quotes to be escaped:

```
kubectl patch clusterrolebinding docker-for-desktop-binding --type=json --patch '[{\"op\":\"replace\", \"path\":\"/subjects/0/name\", \"value\":\"system:serviceaccounts:kube-system\"}]'
```

**Comment by sixeyed** [comment] 2020-07-22 07:14
@nebuk89 this is quite an important issue, currently it gives all Service Accounts cluster admin role which pretty much defeats RBAC and makes Kube in Desktop (Windows and Mac) behave unlike every other distro :)

**Comment by davidje13** [comment] 2020-11-01 16:58
I have just tested this in 2.4.0.0 (48506) and the issue still exists, so I'm marking this not stale.

For users, the workaround posted by sixeyed seems to be the best option:

```bash
kubectl patch clusterrolebinding docker-for-desktop-binding --type=json --patch $'[{"op":"replace", "path":"/subjects/0/name", "value":"system:serviceaccounts:kube-system"}]'
```

Alternatively I've found that minikube is pretty easy to get going with and seems to create a system which is a bit closer to a "real" kubernetes environment.

/remove-lifecycle stale

**Comment by sixeyed** [comment] 2020-12-16 10:55
Still exists in Desktop 3.0.0

**Comment by sixeyed** [comment] 2021-04-13 20:42
/remove-lifecycle stale

Still exists in 3.2.2

**Comment by davidje13** [comment] 2021-07-12 17:47
maybe it's worth pinging @guillaumerose on this one since it keeps going stale and he [previously asked people to let him know if this issue continued](https://github.com/docker/for-mac/issues/3694#issuecomment-518557271) after the original attempted fix.

/remove-lifecycle stale

**Comment by guillaumerose** [comment] 2021-07-12 17:52
I am no longer working at Docker. 
Maybe @djs55 can help you.

**Comment by cdlliuy** [comment] 2021-08-20 13:51
the issue is still there in 3.4.0 version ..

**Comment by piyush-saurabh** [comment] 2021-09-21 10:10
The issue is still in v4.0.1

**Comment by jpetazzo** [comment] 2021-11-05 10:48
Pinging @thaJeztah - maybe he won't know what to do, but he will know who knows ♥ 

(I need to refresh my look-up table of Docker Inc. folks so that I know better who to ping for that kind of issue 😅)

Short recap:
- Docker Desktop has a ClusterRoleBinding called `docker-for-desktop-binding` that gives `cluster-admin` privileges to _all_ ServiceAccounts
- this means that any Pod running on Docker Desktop has `cluster-admin` privileges
- it should _probably_ be changed to give these privileges only to the ServiceAccount `kube-system:default` (or even removed completely)

This behavior is present at least until Docker Desktop 4.1.1 (69879).

**Comment by mstaicu** [comment] 2021-11-17 15:19
Slightly off-topic but as a first layer of restrictions you could opt out of automounting API credentials for a particular pod via `automountServiceAccountToken` directive ( https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/ ), especially if your pods don't need to communicate with the control plane

**Comment by chrisdoherty4** [comment] 2021-11-24 22:00
This is painful, please fix it.

**Comment by jpetazzo** [comment] 2021-11-25 07:51
@chrisdoherty4 Hi! Can you delete the clusterrolebinding and report if there is any side effect? That would help us all to figure out what the best solution would be. Thank you!

**Comment by chrisdoherty4** [comment] 2021-11-25 15:18
@jpetazzo Done and it performs well. I can correctly define RBAC and `kubectl auth can-i` spits out the expected result (I ran various tests mixing and matching stuff). 

I didn't explicitly try ClusterRole's but I assume it functions fine also.

**Comment by djs55** [comment] 2021-11-25 15:25
I believe the binding should not be installed any more in development builds. If you have time to check, here is the latest one: https://desktop-stage.docker.com/mac/main/amd64/71478/Docker.dmg (replace amd64 with arm64 if you are using an M1). I don't think it will remove a binding that already exists-- it will probably only take effect when the cluster is next initialised.

**Comment by thaJeztah** [comment] 2021-11-29 11:30
> Pinging @thaJeztah - maybe he won't know what to do, but he will know who knows ♥

Oh! Sorry, looks like I didn't reply on this thread. I see it's being worked on though, so 👍 ❤️

**Comment by chrisdoherty4** [comment] 2021-11-29 23:51
@djs55 Awesome work. Thanks!

**Comment by trungutt** [comment] 2021-12-02 14:57
New release 4.3.0 (https://docs.docker.com/desktop/mac/release-notes/) is out and has a fix for this issue

**Closed by trungutt** 2021-12-02 14:57 UTC
