### ISSUE TITLE
Possibility to install/configure Docker for Mac in command line

### ISSUE THREAD

**Issue by martinm82** [docker/for-mac#1273] opened 2017-02-09 07:03 UTC
### Expected behavior
In order to install Docker for Mac via tools like Ansible I need to have the possibility to configure/setup Docker as well via the command line. 

I haven't found any information in the documentation how to proceed in such a case. I for sure know how to mount a DMG and copy stuff from the mounted volume to my applications folder but the documentation says that while running the Docker.App it configures your system (hyperkit, etc.).

If there is already this implemented I am happy to learn something new. If not it would be nice to have a similar option as for uninstalling Docker for Mac via the `--uninstall` argument.

### Actual behavior
Not being able to install Docker for Mac via pure command line without UI interaction.

### Information
- Used version: 1.13

### Steps to reproduce the behavior
-

**Comment by martinm82** [comment] 2017-02-16 17:48
I was wondering whether there is some source code for the Docker for Mac frontend application available?

**Comment by ijc25** [comment] 2017-02-20 15:45
I think this is a duplicate of #717 and #882 so I'm closing this as a dup/wontfix. Please see those tickets for some more background.

The D4M UI is not open source at this time.

**Closed by ijc25** 2017-02-20 15:45 UTC
Labels: status/0-triage

**Comment by martinm82** [comment] 2017-08-22 13:16
Any reason why the D4M UI is not open source?
