### ISSUE TITLE
Docker logs --follow sometimes doesn't work; requires container to be rebuilt

### ISSUE THREAD

**Issue by tjratch** [docker/for-mac#307] opened 2016-08-16 17:43 UTC
### Expected behavior

When I run  `docker logs -f my_container` it should continuously output the STDOUT from the container
### Actual behavior

Sometimes, `docker logs -f my_container` will only output latest from the STDOUT, but not continue to follow. I have found that rebuilding my container fixes the problem, but doing that often wastes a lot of time.
### Information

Diagnostic ID: 502F4185-9F63-42A1-B498-D87A0A0DD908
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.4 (Build 14E46)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. run `docker logs -f my_container`

**Comment by dsheets** [comment] 2016-08-17 10:45
I'm not sure why rebuilding the container would fix the problem -- that is very odd. Do you mean restarting the container fixes it? Perhaps starting your container takes a lot of time?

Would it be possible for you to share an example container/Dockerfile that exhibits this issue? If not your exact use case, perhaps there is a similar container that is freely shareable and shows the same issue?

**Comment by tjratch** [comment] 2016-08-17 13:49
Hi There,

I actually do mean *rebuilding* my containers (i.e. docker-compose build)
fixes the problem. Just restarting them does not seem to work. I can double
check the next time it occurs.

I'm fine if you close this issue for now until I have more information
about the problem.

Tristan

**Comment by hypergig** [comment] 2016-08-17 18:19
I am also seeing this issue.  Seems to be guaranteed to happen if you sleep your mac. 

Restarting an already built container doesn't help, `docker start foo` , the logs still fail to follow.  If you `docker rm foo` and `docker run --name foo <my 500 options>` then following works, `docker logs -f foo`.

**Comment by hypergig** [comment] 2016-08-17 18:24
a very janky workaround

```
watch -t docker logs --tail 50 foo
```

**Comment by dsheets** [comment] 2016-08-18 10:48
I've tried to reproduce this and cannot. Could either of you please post an example `Dockerfile` or `docker-compose.yml` that exhibits the issue along with instructions for how to trigger the issue? Even if it only happens 10% of the time, that's fine.

**Comment by hypergig** [comment] 2016-08-18 11:03
@dsheets sure thing.  Maybe it is actually an issue with the terminal we are using? I am using the native mac Terminal, I can test it with iterm to see if it crops up.

**Comment by hypergig** [comment] 2016-08-18 11:53
So I tried a very simple test
```
docker run -d --name=follow_test busybox sh -c 'while true; do date;sleep 1;done;'
```
Then attempted to restart docker and sleep mac and I also wasn't able to reproduce.

The first time I noticed this issue was with a container derived from the `ethereum/client-go:alpine` image.  After starting up a fresh container, following the logs works great.  Put my mac to sleep and wake it up, the logs do not seem to follow any longer.  With this image I am able to repro it.

Going to dig deeper.

**Comment by chrisbethelepb** [comment] 2016-08-18 12:47
👍  I have the same issue and was just about to submit an issue when I found yours.

### Expected behavior
```docker logs -f [image]``` should follow the logs.

### Actual behavior
After some indeterminate amount of time and restarting a running image, ```docker logs -f``` simply returns to the next line and does not follow the logs.

### Information

Diagnostic ID: 5131D56C-EB5B-4FEB-A9ED-9D0D9BA53417
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start a docker image
2. Run ```docker logs -f --since=1m [imagename]```
3. On a newly created image, this works. After the image has been running for a few days, it stops after restarting the image: ```docker restart [imagename] && docker logs -f since=1m [imagename]```
4. Removing the image and re-creating it resolves the issue for a little while, but the issue comes back.


The image continues to run normally, and ```docker logs --tail 50``` show up-to-date logs for the image. I am just unable to follow the logs with ```docker logs -f [imagename]```

**Comment by chrisbethelepb** [comment] 2016-08-18 12:56
Dockerfile:
```
FROM node:6.3.0

RUN useradd --user-group --create-home --shell /bin/false app 

ENV HOME=/home/app

COPY . $HOME/
RUN chown -R app:app $HOME

USER app
WORKDIR $HOME/

CMD ["node", "app.js"]
```

docker-compose.yml:
```
myproject:
  build: .
  environment:
    NODE_ENV: production 
  ports:
    - '8080'

```


Building the image:
```sh
# build the image
docker build -t myproject:latest .

# create the container
# cd in to project directory
docker create --name=myproject --net=localdev -v $(pwd):/home/app myproject:latest
```



My example just runs a node.js app. You can create an app.js file and put
```js
setInterval(() => {console.log((new Date).getTime())}, 1000);
```

**Comment by hypergig** [comment] 2016-08-18 12:56
@chrisbethelepb I am having some difficulty forcing the issue to happen, when you say "After the image has been running for a few days" is that the only way you have been able to repo it thus far?

**Comment by chrisbethelepb** [comment] 2016-08-18 12:56
@hypergig Yes, it seems to be random intervals of time after it stops working.

**Comment by chrisbethelepb** [comment] 2016-08-18 12:59
@hypergig I typically leave my laptop on and lock the screen after I'm finished working. The machine never goes to full sleep (just turns display off) and my Docker images remain on and produce logs throughout the day. Some of the logs to stdout are very chatty, it's almost like it reaches a certain size and ```logs -f``` just stops working.

**Comment by hypergig** [comment] 2016-08-18 13:04
@chrisbethelepb funny you should suggest that.. I was just testing this exact theory by
```
docker run -d --name=follow_test busybox sh -c 'while true; do date; done;'
```
Which produces about 4211 lines of log per second.  I still wasn't able to repro.  I restarted docker, the container, slept my mac, nothing triggered it.  I wonder what causes the issue...

**Comment by chrisbethelepb** [comment] 2016-08-18 13:07
@hypergig I never had the problem until the v1.12.0-a build 11213. Worked great using the Docker for Mac betas... although I tried installing v1.12.0 (without the -a, original GM release) over top of the current Docker and then it started having the same problem as well.

**Comment by tjratch** [comment] 2016-08-18 13:54
I'm using iTerm, so I don't think it's the terminal

**Comment by ijc25** [comment] 2016-11-16 17:20
This sounds a lot like https://github.com/docker/docker/issues/27779. @thaJeztah does that sound likely to you?

**Comment by tjratch** [comment] 2016-11-16 17:29
I've completely abandoned Docker for Mac and have reverted back to using Kitematic. Docker for mac ended up eating all my CPU and Memory and was somehow slower than Kitematic.

**Comment by thaJeztah** [comment] 2016-11-17 23:51
@ijc25 does look plausible yes

**Comment by ijc25** [comment] 2016-11-18 11:12
@thaJeztah thanks for confirming. This should therefore be fixed in beta when docker for mac switches to the 1.13 rcs and in stable once 1.13 proper is released.

**Comment by testn** [comment] 2016-12-22 00:42
1.13.0-rc3-beta33.1 still has the problem

**Comment by samoht** [comment] 2017-01-30 17:40
I am closing this now that 1.13 got released.

**Closed by samoht** 2017-01-30 17:40 UTC
Labels: area/docker, kind/bug, osx/10.10.x, status/3-fixed, version/1.12.0-a

**Comment by edgarjrg** [comment] 2017-04-18 22:17
I'm havig the same issue with Docker version 17.03.0-ce, build 60ccb22, first time having this issue with Ubuntu.

**Comment by BallisticPain** [comment] 2017-05-06 05:19
I'm on a Mac (macOS Sierra 10.12.4)... iTerm2... 

Docker
```
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc
```

I have my machine set to not go to sleep, but it is allowed to turn off the monitors. I was checking on the process every hour for the first few, then I let it have 3 hours in between. In that 3 hours it had stopped following the logs. I checked a `ps -aux` and `top` none of my processes seemed to be doing anything (0% CPU, 0 MEM), yet they were "running" just were sleeping processes. I had 32 processes and 31 are sleeping from what I recall of the output.

Thankfully in my particular scenario, I was just processing messages off of a queue so I took down the container and just spun it right back up. Of course everything was processing as usual.

I wonder if this would happen if I wasn't using `docker-compose logs -f php_code` as in if I wasn't attempting to follow the logs would it still have the issue?

Upon further research I've tried implementing a few things, but I'm not bringing down my containers to test it until my queue is processed through as I'm doing testing to be sure this is going to work as we're hoping and expecting.

Here's what I've put into my compose file... for each service.
```
   logging:
       driver: json-file
       options:
           max-size: "20M"
           max-file: "10"
```

**Comment by Crashthatch** [comment] 2017-06-21 15:43
We also saw this issue on 17.03. I think the server lost power and we got a bunch (~50?) of NUL (0x00) characters on the end of the json log file (at /var/lib/docker/containers/SHA/SHA-json.log). When the server came back up (container is restart=always) it continued appending JSON records to the same file, but `docker logs` bombs out when it gets to that part of the file. 

/var/log/syslog gets the following written to it when docker logs fails:

    level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value"

I believe this is the root issue causing https://github.com/gliderlabs/logspout/issues/246 downstream.

**Comment by DudeWhoCode** [comment] 2018-05-13 04:54
I am also facing the same issue in docker for mac.

`Docker version 18.03.1-ce, build 9ee9f40`

When the container runs for a long time, the --follow switch doesn't work. When I stop and start the container again, it seems to follow the logs.

**Comment by IzaGz** [comment] 2018-10-26 02:51
same issue - logs not displayed- how to fix this? 
Docker version 18.06.1-ce
docker-compose version 1.21.2

**Comment by IzaGz** [comment] 2018-10-26 12:18
@hypergig  have you fixed it?

**Comment by apurvaSynerzip** [comment] 2018-11-21 10:52
I am also facing this issue.

**Comment by hlyford** [comment] 2018-12-21 00:40
This issue is still occurring. `docker logs -f` requires a container restart whenever there's a code change.
