### ISSUE TITLE
Fatal Error: com.docker.supervisor failed to start. Exit code 1

### ISSUE THREAD

**Issue by KosukeOhmura** [docker/for-mac#2925] opened 2018-05-21 10:19 UTC
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B541CA03-9EA7-4FC3-BA7A-4B2A6A87CC54

### Expected behavior
Keep working

### Actual behavior
Work well for 2-3 days then crash with Fatal Error

### Information
I running Docker for mac for gitlab-runner. Docker for mac crashes every 2-3 days so I need exit and start it again.
  - macOS Version: 10.13.4

### Diagnostic logs
```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/B541CA03-9EA7-4FC3-BA7A-4B2A6A87CC54/20180521-180356.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/uv/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/uv/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/uv/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```

### Steps to reproduce the behavior
  1. Start Docker for mac
  2. Run gitlab-runner on a container and wait for 2-3 days

**Comment by akimd** [comment] 2018-05-25 08:55
Your _full_ diagnostic id is `B541CA03-9EA7-4FC3-BA7A-4B2A6A87CC54/20180525-101422`.

Your problem seems to start with osxfs.
```
2018-05-24 21:40:22.161168+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:22.161290+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:22.566763+0900  localhost com.docker.osxfs[61795]: Volume.stop 7c87ed738b3a7a2da66abbeb9d677d3fcfb61444055a1c862fd4ed29326fcdf5 (paths = [/Users/uv/builds/49c00410/0/be
2018-05-24 21:40:22.793395+0900  localhost com.docker.osxfs[61795]: While invalidating dcache of 3037057 / mime-types.rb: ENOTDIR
2018-05-24 21:40:22.967380+0900  localhost com.docker.driver.amd64-linux[61797]: proxy << POST /v1.25/containers/a4a4037923f161fe527d9b5c451870719c970d0650c2f75913f90d0b75ee5110/stop?t=
2018-05-24 21:40:23.312236+0900  localhost com.docker.driver.amd64-linux[61797]: proxy << POST /v1.25/containers/7c87ed738b3a7a2da66abbeb9d677d3fcfb61444055a1c862fd4ed29326fcdf5/stop?t=
2018-05-24 21:40:23.329814+0900  localhost com.docker.driver.amd64-linux[61797]: proxy >> POST /v1.25/containers/5b13b7fe187b439bb9ab6ddac7b11c9c75d5a10311a453031956fc03ff7fdfbb/stop?t=
2018-05-24 21:40:23.329952+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:23.341714+0900  localhost com.docker.driver.amd64-linux[61797]: proxy >> POST /v1.25/containers/7b69e2de632499b83cfa1be1fe037f98175253770dc702a3054da66965710db8/stop?t=
2018-05-24 21:40:23.341864+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:23.342076+0900  localhost com.docker.driver.amd64-linux[61797]: proxy >> POST /v1.25/containers/0012720e56c6d3e1d2f2bab8723874cbef006654d8cb1fea4db1c124313d3901/stop?t=
2018-05-24 21:40:23.342171+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:23.345641+0900  localhost com.docker.driver.amd64-linux[61797]: proxy >> POST /v1.25/containers/0d89e7d512d33be097d3aac3dfd51fb57fbbce6e26d2484e90be41547d0c60ad/stop?t=
2018-05-24 21:40:23.345788+0900  localhost com.docker.driver.amd64-linux[61797]: Dial Socket vms/0/00000003.00000948
2018-05-24 21:40:23.456816+0900  localhost com.docker.driver.amd64-linux[61797]: Failed to remove container from osxfs: EOF
2018-05-24 21:40:23.467734+0900  localhost com.docker.supervisor[61794]: cannot read stderr from com.docker.osxfs: EOF
2018-05-24 21:40:23.468134+0900  localhost com.docker.supervisor[61794]: cannot read stdout from com.docker.osxfs: EOF
2018-05-24 21:40:23.468338+0900  localhost com.docker.supervisor[61794]: Reap com.docker.osxfs (pid: 61795): exit status 1
2018-05-24 21:40:23.470959+0900  localhost com.docker.supervisor[61794]: Stop 1 children with order 1: [com.docker.driver.amd64-linux (pid: 61797)]
2018-05-24 21:40:23.471090+0900  localhost com.docker.supervisor[61794]: Send signal terminated to com.docker.driver.amd64-linux (pid: 61797)
2018-05-24 21:40:23.474079+0900  localhost com.docker.driver.amd64-linux[61797]: sending SIGTERM to com.docker.hyperkit pid: 61802
2018-05-24 21:40:25.703204+0900  localhost com.docker.driver.amd64-linux[61797]: error reading response from Docker:  unexpected EOF
2018-05-24 21:40:25.703733+0900  localhost com.docker.driver.amd64-linux[61797]: error reading response from Docker:  unexpected EOF
```
but I don't know what caused this.  Maybe @djs55 would have an idea on how to study this?

**Comment by djs55** [comment] 2018-05-30 10:04
I believe this is a duplicate of #2765. I'll close this ticket but please do follow the discussion over there.

**Closed by djs55** 2018-05-30 10:04 UTC
Labels: version/18.03.1-ce-mac65
