### ISSUE TITLE
Cannot get the raw support working (Hi-Sierra/SSD) on APFS

### ISSUE THREAD

**Issue by gabb99** [docker/for-mac#2241] opened 2017-11-17 21:28 UTC
In the release notes for 'Docker Community Edition 17.11.0-ce-rc4-mac39 2017-11-17 (Edge)'
it states that to use this new format (instead of qcow2 format):

**if you want to switch to raw format you need to reset to defaults.**

This does not work.

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 4.833GiB
Name: linuxkit-025000000001
ID: BCND:POFN:W2NC:WE6J:XEUU:VRAF:222P:AGTP:CM4X:LV5D:EFJQ:NMY4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 96
 System Time: 2017-11-17T21:26:48.784369007Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by gabb99** [comment] 2017-11-17 21:33
BTW, I'm using a non-apple SSD (Crucial), but it was recognized when I upgraded to HiSierra).

 Available:	219.06 GB (219,055,214,592 bytes)
  Capacity:	959.99 GB (959,987,367,936 bytes)
  Mount Point:	/
  File System:	APFS
  Writable:	Yes
  Ignore Ownership:	No
  BSD Name:	disk1s1
  Volume UUID:	5EE6C046-544A-3BEE-BD9C-8EB80A782C16
  Physical Drive:
  Device Name:	CT960BX200SSD1
  Media Name:	AppleAPFSMedia
  Medium Type:	SSD
  Protocol:	SATA
  Internal:	Yes
  Partition Map Type:	Unknown

**Comment by khs1994** [comment] 2017-11-18 03:52
Don't work? You meaning?  

`$ cd ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/`  

 `$ ls -ls Docker.raw`  

 `3944768 -rw-r--r--@ 1 user  staff  68719476736 Nov 16 11:19 Docker.raw`

**Comment by gabb99** [comment] 2017-11-18 15:20
I'm still stuck with the Docker.qcow2 as the backing store.

Gabriels-MacBook-Pro-2:com.docker.driver.amd64-linux gabB$ ls -ls
total 41767528
41766552 -rw-r--r--@ 1 gabB  staff  21418868736 17 Nov 18:55 Docker.qcow2
       0 -rw-r--r--  1 gabB  staff        65536 17 Nov 18:00 console-ring
      72 -rw-r--r--  1 gabB  staff        65536 17 Nov 18:00 console-ring.0
      72 -rw-r--r--  1 gabB  staff        65536 17 Nov 17:58 console-ring.1
     792 -rw-r--r--  1 gabB  staff       405504 17 Nov 18:00 database.iso
       8 -rw-r--r--  1 gabB  staff            5 17 Nov 18:00 hypervisor.pid
       0 -rw-r--r--  1 gabB  staff            0 17 Nov 17:57 lock
       0 drwxr-xr-x  2 gabB  staff           64 17 Nov 17:57 log
       8 -rw-r--r--  1 gabB  staff           17 17 Nov 18:00 mac.0
       8 -rw-r--r--  1 gabB  staff           36 17 Nov 17:57 nic1.uuid
       8 -rw-r--r--  1 gabB  staff            5 17 Nov 18:00 pid
       8 -rw-r--r--  1 gabB  staff          188 17 Nov 18:00 syslog
       0 lrwxr-xr-x  1 gabB  staff           12 17 Nov 18:00 tty -> /dev/ttys000

**Comment by khs1994** [comment] 2017-11-18 16:34
You must reset default.

**Comment by khs1994** [comment] 2017-11-18 16:37
![2017-11-19 12 33 58](https://user-images.githubusercontent.com/16733187/32982589-bdb5e71e-ccc1-11e7-9991-d3ca9800d97c.png)
You must reset default.

**Comment by gabb99** [comment] 2017-11-19 16:42
Did the reset to defaults and uninstall a couple of times before opening the bug. I've reproduced this also on another machine with an apple built-in ssd. Same results.

**Comment by djs55** [comment] 2017-11-19 18:56
@gabb99 When Docker starts up it checks for the ability to use sparse files in the directory containing the image. Could you show your `~/Library/Group\ Containers/group.com.docker/settings.json` which should contain a line like
```
  "diskPath" : "/Users/foo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.raw",
```
Could you verify that the directory mentioned there is on your local SSD device and formatted with `apfs` by checking the result of `mount` and the result of `diskutil list` and then `diskutil info /dev/diskNN`? For reference I have

```
$ mount
/dev/disk1s1 on / (apfs, local, journaled)
...
```

```
$ diskutil list
...
/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +499.4 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            461.5 GB   disk1s1
   2:                APFS Volume Preboot                 21.9 MB    disk1s2
   3:                APFS Volume Recovery                520.8 MB   disk1s3
   4:                APFS Volume VM                      9.7 GB     disk1s4
...
```
and
```
$ diskutil info /dev/disk1
   Device Identifier:        disk1
   Device Node:              /dev/disk1
   Whole:                    Yes
   Part of Whole:            disk1
   Device / Media Name:      APPLE SSD SM0512F
...
   Solid State:              Yes
...
```

**Comment by lraphael** [comment] 2017-11-19 19:18
I had the same issue. Factory Defaults and removing and reinstalled haven't resolved the Issue. 
The solution was changing the ~/Library/Group\ Containers/group.com.docker/settings.json
 diskPath from 
``
  "diskPath" : "/Users/myusername/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2",
``
to
``
  "diskPath" : "/Users/myusername/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.raw",
``

**Comment by gabb99** [comment] 2017-11-19 21:06
@djs55 The path was set with the old qcow2 format. I tried as @lraphael did, and it now works (validated with ls -ls, to make sure the image grows properly).

Gabriels-MacBook-Pro-2:com.docker.driver.amd64-linux gabB$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *751.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk2         750.4 GB   disk0s2
   3:       Apple_KernelCoreDump                         655.4 MB   disk0s3


Gabriels-MacBook-Pro-2:com.docker.driver.amd64-linux gabB$ diskutil info /dev/disk0
   Device Identifier:        disk0
   Device Node:              /dev/disk0
   Whole:                    Yes
   Part of Whole:            disk0
   Device / Media Name:      APPLE SSD SM768E

   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

   Content (IOContent):      GUID_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 SATA
   SMART Status:             Verified

   Disk Size:                751.3 GB (751277983744 Bytes) (exactly 1467339812 512-Byte-Units)
   Device Block Size:        512 Bytes

   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

   Device Location:          Internal
   Removable Media:          Fixed

   Solid State:              Yes
   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported

**Comment by gabb99** [comment] 2017-11-19 21:07
My ssd is at /dev/disk0, yours seem to be at dev/disk1

**Comment by gabb99** [comment] 2017-11-19 21:13
Sorry. It think you're lokking for the synthetized disk

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +750.4 GB   disk2
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh SSD           521.7 GB   disk2s1
   2:                APFS Volume Preboot                 19.9 MB    disk2s2
   3:                APFS Volume Recovery                520.8 MB   disk2s3
   4:                APFS Volume VM                      1.1 GB     disk2s4

**Comment by gabb99** [comment] 2017-11-19 21:15
Could this explain the issue?
Gabriels-MacBook-Pro-2:com.docker.driver.amd64-linux gabB$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *751.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk2         750.4 GB   disk0s2
   3:       Apple_KernelCoreDump                         655.4 MB   disk0s3

**/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *31.9 GB    disk1
   1:                  Apple_HFS 32G                     31.9 GB    disk1s1**

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +750.4 GB   disk2
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh SSD           521.7 GB   disk2s1
   2:                APFS Volume Preboot                 19.9 MB    disk2s2
   3:                APFS Volume Recovery                520.8 MB   disk2s3
   4:                APFS Volume VM                      1.1 GB     disk2s4

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *750.2 GB   disk3
   1:                        EFI                         209.7 MB   disk3s1
   2:                  Apple_HFS Macintosh HD            749.8 GB   disk3s2

/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +2.0 TB     disk4
   1:                        EFI EFI                     209.7 MB   disk4s1
   2:                  Apple_HFS Time Machine Backups    2.0 TB     disk4s2

I have a memory card mounted, which changes the disk allocation numbering (same thing at my work computer).

**Comment by djs55** [comment] 2017-11-19 21:44
Interesting -- if changing the path manually to `Docker.raw` in `settings.json` is making it work then there must be a problem with the detection logic. I'll investigate further.

**Comment by gabb99** [comment] 2017-11-20 15:16
Confirmed working on my other machine (by modifying the settings.json). Btw, I had a custom Docker.qcow2 (resized to 100G for my purposes, using the qemu-img tool). Now I'm just chainging the default value in the settings.json

**Comment by vschoener** [comment] 2018-03-03 22:02
I run into the same issue, I tried to reset / uninstall / reinstall and still it doesn't want to change for the raw format.
I had to change manually the json file and set the Docker.raw as written above

**Comment by dsandber** [comment] 2018-03-13 22:51
Is APFS needed to use .raw files?  Because my disk is HFS.

**Comment by djs55** [comment] 2018-03-15 16:42
We've temporarily switched the default back to `qcow2` after we reproduced a corruption bug with sparse files on APFS -- see #2625. The underlying bug seems to be fixed in the recent developer betas of macOs. When the next High Sierra update comes out we'll test again and switch the default back to `raw` if it's working properly.

Sorry for the confusion in the meantime!

**Comment by dsandber** [comment] 2018-03-16 22:41
Good to know, but my question is independent of that bug -- can raw be used with HFS or only APFS?  What happens if it is turned on with HFS? Is the problem just that a huge amount of disk space is used because HFS doesn't support sparse files, or is there a performance/corruption/other issue as well?

**Comment by k-vladyslav** [comment] 2018-03-24 13:00
same here, MacOS High Sierra 10.13.3, installed Docker edge CE 18.03.0-ce-rc4-mac57, did several install/uninstall, then "reset to factory defaults" - no luck disk image named Docker.**qcow2**

**Comment by thaJeztah** [comment] 2018-03-24 13:45
@k-vladyslav read two comments above; raw support was temporarily disabled because of a bug in macOS https://github.com/docker/for-mac/issues/2241#comment-373442996

**Comment by lumaxis** [comment] 2018-03-29 19:31
@thaJeztah ~~macOS 10.13.4 was just released today~~, do you already have any findings if it definitely fixes the corruption issue? If so, is there a way for me to override the default of `qcow2` to use a raw disk again?

_Never mind, looks like I can't properly read, 10.13.4 isn't actually released yet._

**Comment by akimd** [comment] 2018-03-30 09:34
Rest assured that as soon as we believe that 10.13.4 is fixed, we'll release Edge versions restoring APFS support in Docker for Mac.  Please be patient.

**Comment by mathiaslm89** [comment] 2018-04-27 12:50
What's the status here?

**Comment by akimd** [comment] 2018-04-27 13:57
The latest Edge (18.05) restores AFPS for 10.13.4 and above.

**Closed by akimd** 2018-04-27 13:57 UTC
Labels: status/1-acknowledged

**Comment by akimd** [comment] 2018-04-29 11:13
And in case you wonder, yes, of course, the next Stable (18.06) will have APFS on too.  It was too late for Stable 18.03, there were no previous use in an Edge that gave us enough confidence.

**Comment by lfv89** [comment] 2018-06-30 22:35
I'm on docker for mac `18.03.1` and, also having this problem, @lraphael solution perfectly worked.
