### ISSUE TITLE
Used up all disk space

### ISSUE THREAD

**Issue by gihankarunarathne** [docker/for-mac#1161] opened 2017-01-19 21:02 UTC
### Expected behavior
Should be clean up when removing containers and images
### Actual behavior
Not releasing the used disk space
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Continues building images `docker build -t user/test  .`
  2. Used up all the disk space. Initially there was more than 10GB free space

**Comment by djs55** [comment] 2017-01-20 10:33
The current version of Docker for Mac will only reclaim space on the host when

- space has been freed in the VM; and
- 15 minutes have elapsed (there is a background `cron` job running `fstrim /var`); and
- the VM is subsequently rebooted.

Have a look at the "How do I reduce the size of Docker.qcow2?" section here: https://docs.docker.com/docker-for-mac/faqs/

Hopefully a future version will be able to recover space dynamically-- there is code for this already but it needs some more fixing before it's ready. For now I'll label this issue as a feature request.

**Comment by samoht** [comment] 2017-01-31 16:45
Closing as a duplicate of #371 

The feature is partially implemented in recent version of Docker for Mac, but some work remains to be done to have a fully satisfying solution.

**Closed by samoht** 2017-01-31 16:45 UTC
Labels: area/storage, kind/enhancement, status/2-in-progress

**Comment by MrUpsidown** [comment] 2019-10-15 13:58
> The current version of Docker for Mac will only reclaim space on the host when
> 
> * space has been freed in the VM; and
> * 15 minutes have elapsed (there is a background `cron` job running `fstrim /var`); and
> * the VM is subsequently rebooted.
> 
> Have a look at the "How do I reduce the size of Docker.qcow2?" section here: https://docs.docker.com/docker-for-mac/faqs/

Stop claiming that stuff works when it doesn't.
