### ISSUE TITLE
update failed and deleted docker - now listed as corrupted

### ISSUE THREAD

**Issue by the-vampiire** [docker/for-mac#6117] opened 2022-01-01 22:02 UTC
- [ ] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

- download update
- apply and restart
- docker functions with new version

### Actual behavior

- download update
- apply and restart
- froze and disappeared from task and activity bar
- searching for docker in finder shows greyed out symbol - executing states the file is corrupted

### Information

  - macOS Version: 12.1
  - Intel chip or Apple chip: M1 Max
  - Docker Desktop Version: i am unable to check anymore (was current within the last 2 weeks)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

`MacOS` dir and `com.docker.diagnose` file does not exist

contents of `/Applications/Docker.app/Contents`:

```sh
Frameworks
Info.plist
Library
PkgInfo
Resources
embedded.provisionprofile
```

### Steps to reproduce the behavior

  1. download update
  2. apply and restart

**Comment by weitzman** [comment] 2022-01-02 12:01
Me too. Maybe this is a dupe of #6100

**Comment by the-vampiire** [comment] 2022-01-02 20:33
i did a complete wipe (`find / -iname '*docker*' 2> /dev/null`, redirect the "permission denied" outputs to null) then reinstalled. working again now.

will just avoid updates going forward unless its something i need.

**Comment by osinoleg** [comment] 2022-01-23 16:08
me three.

**Comment by chegJH** [comment] 2022-02-19 13:51
still waiting for the fix...

**Comment by the-vampiire** [comment] 2022-02-19 16:06
> still waiting for the fix...

no fix mate. did a clean wipe and reinstall of docker. treating it like a windows machine you cant ever trust - disabled auto updates. 

works as expected now.

**Comment by raftalks** [comment] 2022-03-14 19:13
terrible, it just happened to me too. Now I need to install it again !!

**Comment by causevic** [comment] 2022-03-21 16:58
still happens.

**Comment by daniel-fahl** [comment] 2022-03-28 13:21
Can confirm, happened to me while updating from 4.5 to 4.6.1

**Comment by bkrubnzi** [comment] 2022-04-04 17:53
Also happened to me, 4.6.0 to 4.6.1

**Comment by mat007** [comment] 2022-04-25 14:50
Closing this as a dupe of #6268
While this issue here predates that other one, it’s best to have just a single issue.
See https://github.com/docker/for-mac/issues/6268#issuecomment-1108675842 for a summary.

**Closed by mat007** 2022-04-25 14:50 UTC
