### ISSUE TITLE
"Docker wants to make changes" dialog is broken.

### ISSUE THREAD

**Issue by zegelin** [docker/for-mac#4422] opened 2020-04-04 00:08 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 

### Expected behavior
The "Docker wants to make changes" dialog should have a correctly labeled "Ok" button, and it should align with the other button on the window.

### Actual behavior
The "Docker wants to make changes" dialog has a mis-aligned and unlabelled "Ok" button.

This looks suspicious and gives me concern about entering my authentication credentials.
Also, why doesn't this dialog support Touch ID?

<img width="555" alt="Screen Shot 2020-04-03 at 4 56 09 pm" src="https://user-images.githubusercontent.com/19296634/78413659-4be0f180-75cd-11ea-9b5e-34e713ec1332.png">

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.2.0.5 (43884)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment] 2020-04-06 09:15
Thanks for the report, this is a duplicate of #2856 but you might head directly to https://github.com/moby/moby/issues/39648#issuecomment-518192195 to have a full explanation about why there isn’t much room for use to fix it at the moment.

**Closed by mat007** 2020-04-06 09:15 UTC
