### ISSUE TITLE
Docker build fails when targeting `--platform linux/amd64`, due to `allocate virtual memory` issue

### ISSUE THREAD

**Issue by ryanhefner** [docker/for-mac#5831] opened 2021-07-08 09:44 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Build should succeed, as it did in previous Docker Apple Silicon Preview versions.

### Actual behavior

Build fails once it tries to execute a command, resulting in `allocate virtual memory` issue / `core dumped`, then just hangs.

```
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 289B                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 34B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                                                               0.7s
 => [stage-1 1/3] FROM docker.io/library/node:alpine@sha256:b7e2d75ecd585feed57be69cd3dee973e5c498241e64906899b3baa2169fb35a                                                 0.0s
 => [internal] load build context                                                                                                                                            0.0s
 => => transferring context: 17.88kB                                                                                                                                         0.0s
 => CACHED [stage-1 2/3] WORKDIR /app                                                                                                                                        0.0s
 => CACHED [builder 3/7] COPY ./package*.json ./                                                                                                                             0.0s
 => CACHED [builder 4/7] COPY ./yarn.lock ./                                                                                                                                 0.0s
 => [builder 5/7] RUN yarn install --frozen-lockfile --prod                                                                                                                 11.2s
 => => # #                                                                                                                                                                       
 => => # # Fatal process OOM in CodeRange setup: allocate virtual memory                                                                                                         
 => => # #                                                                                                                                                                       
 => => # qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped  
 ```

### Information

  - macOS Version: `11.4`
  - Intel chip or Apple chip: `Apple M1`
  - Docker Desktop Version: `3.5.1.7`

### Steps to reproduce the behavior

`Dockerfile`

```
FROM node:alpine AS builder
WORKDIR '/app'
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn install --frozen-lockfile --prod
COPY . .
RUN yarn build

FROM node:alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
CMD ["yarn", "start"]
```

Build command (ran via `deploy.sh`):

```
docker build --platform linux/amd64 -t $TAG_ENV -t $TAG_SHA -f ./services/$SERVICE/Dockerfile ./services/$SERVICE
```

**Comment by joninsky** [comment] 2021-07-08 16:16
I'm having the same issue. I have tried to increase available memory for Node through this command in my docker file.

```shell
RUN set NODE_OPTIONS=--max-old-space-size=30720
```

However, the issue is still present.

**Comment by shamelesscookie** [comment] 2021-07-17 09:07
This seems to be exclusive to node.js 16.x. Still affect Docker Desktop 3.5.2 on Apple Silicon.

Any `node` or `npm` command (except `node --version`) produces this behavior.

I reproduced on `debian:bullseye-slim` using latest node.js (16.4.1). node.js 14 and 12 are working.

**Comment by ycordier** [comment] 2021-07-19 12:42
Hello guys,

I'd like to share my experience with this issue.
I have the same problem with my Docker images and Apple M1.
For deploying to production environment on Azure, I must build my Docker images with --platform linux/amd64 option.

With DockerFile "FROM node:16-slim" base, I have the "allocate virtual memory" issue.
With DockerFile "FROM node:14-slim" base, no issue (but the build is verrrrrryyyyyy long...)

Thanks to @shamelesscookie for the observation. I'll set my DockerFiles with node 14 for the moment...

(For all : Is any solution for speedup build --platform linux/amd64 option, please ???)

Thanks for all.
Have a nice day.

**Comment by Nomad-Go** [comment] 2021-07-19 19:50
Thank you @shamelesscookie  for the observation. I changed my base image from `FROM node:current-alpine3.14` to `FROM node:14-alpine3.14` and it works!

**Comment by carlolucadei** [comment] 2021-08-05 10:28
@Nomad-Go @shamelesscookie I'm trying to follow your hint. 🤞 for us!

**Comment by abelce** [comment] 2021-08-15 13:11
@Nomad-Go it`s works

**Comment by edurodriguesdias** [comment] 2021-08-22 02:41
Using `node:14-alpine3.14` works for me! Thank you @shamelesscookie for helping 👍

**Comment by Lazzu** [comment] 2021-08-24 15:16
By trial-and-error I found that using `node:16.3-alpine3.12` fixed this issue for me

**Comment by aaronhmiller** [comment] 2021-09-14 17:53
Thank you @Lazzu! Seconding your find. Something broke starting with Node 16.4.

**Comment by shamelesscookie** [comment] 2021-10-07 16:26
This appears to be fixed with node 16.10.0

```
$ docker run --rm -it --platform=linux/amd64 --entrypoint /bin/sh node:16-alpine 
/ # node -v
v16.10.0
/ # npm -v
7.24.0
```

**Comment by AllanOricil** [comment] 2021-11-10 13:58
Im facing the same problem. And changing the base image did not work for me.

**Comment by AllanOricil** [comment] 2021-11-10 14:07
I can confirm that after upgrading docker desktop to the latest version I was able to build the image on a Mac M1

**Closed** 2021-11-10 14:34 UTC
