### ISSUE TITLE
Unable to install Stable or Edge version

### ISSUE THREAD

**Issue by theyowguy** [docker/for-mac#1487] opened 2017-03-29 22:20 UTC
### Expected behavior
It would be nice if I was able to complete the install so that I could run the product.

### Actual behavior
Error message regarding a communication error.

### Information

Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/AAD6AF2C-1AB3-4A1B-9DC4-A34F0DF15709/20170329-181026.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/bob/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/bob/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/bob/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bob/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/bob/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/bob/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
<img width="682" alt="screen shot 2017-03-29 at 6 18 50 pm" src="https://cloud.githubusercontent.com/assets/24615666/24479235/3464a842-14ac-11e7-8d87-f11603d2d3b6.png">

**Comment by avsm** [comment] 2017-03-29 22:53
It looks like `vmnetd` never got installed for some reason.  When you first ran the app, did it prompt you for your admin password so that you can install a privileged component?

**Comment by theyowguy** [comment] 2017-03-29 22:55
Yes sir, it did.

Is there an option to run with extra logging during the install?

**Comment by avsm** [comment] 2017-03-30 09:14
Thanks for the clarification.  It looks like vmnetd only got half-installed for some reason.

Do you have a `/var/run` and ` /var/tmp` directory on your Mac?  If both of those directories do exist, you can try to delete `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restart the application, at which point it should reinstall it.

**Comment by theyowguy** [comment] 2017-03-30 11:12
I did not have a /var/tmp folder. Once created, I was able to successfully complete the install... thanks!!!

That said, shouldn't the install create the folder if it's required and it doesn't exist? :)

TYVM for the help!!

Cheers.

**Comment by avsm** [comment] 2017-03-30 13:33
@theyowguy thank you very much for confirming the workaround lets you make progress!

I've filed an internal issue on our installer to ensure the existence of these directories.  I'll go ahead and close this bug now as your immediate problem is fixed, and we will address the root cause in a future update of Docker for Mac.

**Closed by avsm** 2017-03-30 13:33 UTC
Labels: osx/10.12.x, status/0-more-info-needed, version/17.03.1-ce-rc1-mac3
