### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by miguel-orange** [docker/for-mac#4071] opened 2019-11-25 18:23 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 537CFBEB-6709-44A3-BBCE-3FB07B7F7470/20191125181619

### Expected behavior
Successfully login
### Actual behavior
> Incorrect authentication credentials
### Information

  - macOS Version: 10.15.1

### Steps to reproduce the behavior

1. Click Sign in
2. Use correct login credentials
3. Go to hub.docker.com
4. Use same exact credentials and successfully login, logout
5. Take the password out of autofill screen
6. Paste into Docker hub window from step 1 & 2
7. Get frustrated as it works on hub.docker.com but not on docker desktop.

**Comment by nolazybits** [comment] 2019-12-03 19:39
Same issue here.

**Comment by davidbarton** [comment] 2019-12-09 15:24
Same issue here.

```
Mac Version 10.15.1 (19B88)
Docker Version 2.1.0.5 (40693)
```

**Comment by stephen-turner** [comment] 2019-12-10 11:24
Thanks for the report, dupe of #4010. Will be fixed in this week's Edge release.

**Closed by stephen-turner** 2019-12-10 11:24 UTC
Labels: version/2.1.0.5
