### ISSUE TITLE
fails during docker build when adding file

### ISSUE THREAD

**Issue by neoreeps** [docker/for-mac#58] opened 2016-08-01 20:43 UTC
### Information

Diagnostic ID: 8221D07F-70A0-4F1E-B1DA-3F641022FDC5
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment] 2016-08-09 02:10
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:10 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
