### ISSUE TITLE
Custom bridge prevent start docker

### ISSUE THREAD

**Issue by RustamGimadiev** [docker/for-mac#1531] opened 2017-04-11 13:17 UTC
### Expected behavior
The daemon starts and I can use docker.
### Actual behavior
The daemon gets stuck, the docker icon doesn't stop it's "in progress" animation and it says "docker is starting" forever. I need to reset to factory defaults to get a working docker environment.
### Information

```
Docker for Mac: version: 17.04.0-ce-mac7 (b598153e2)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/B577B2DF-9037-4892-9CBF-F9C34E73C245/20170411-161140.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

```
cat etc/docker/daemon.json
{"debug":true,"experimental":true,"bridge":"acme"}
```
### Steps to reproduce the behavior

  1. Create custom bridge `acme`
  2. Assign this bridge as default
  3. Restart docker

**Comment by dsheets** [comment] 2017-04-11 16:16
Could you please be more specific in your reproduction steps? Exactly what do you execute to "Create custom bridge `acme`", "Assign this bridge as default", and "Restart docker"?

Thank you!

**Comment by ebriney** [comment] 2017-04-26 09:29
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Closed by ebriney** 2017-04-26 09:29 UTC
Labels: osx/10.12.x, status/0-more-info-needed, status/0-triage, version/17.04.0-ce-mac7
