### ISSUE TITLE
"docker run -p" does not support the full -p syntax on MacOS

### ISSUE THREAD

**Issue by MineCoinChain** [docker/for-mac#5205] opened 2020-12-31 08:03 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
"docker run -p" should support the full -p syntax on MacOS
### Actual behavior
it does not work,when I add localhost IP(not 127.0.0.1),the mapped port and ipaddress has changed.as following:
![image](https://user-images.githubusercontent.com/50442090/103400713-1def0480-4b81-11eb-972d-9f4ac439789f.png)
but it works on other unix system like ubuntu
### Information

  - macOS Version:
     macos Catalina 10.15.7
### Diagnostic logs

```
Docker for Mac: version...
3.0.3
```

### Steps to reproduce the behavior

  1. docker run -p yourlocalhostIP:mappedport:port
  2. it does not works

**Comment by stephen-turner** [comment] 2021-01-04 11:31
Thanks for the report. I believe this is a dupe of #4541.

**Closed by stephen-turner** 2021-01-04 11:31 UTC

**Comment by simonferquel** [comment] 2021-01-25 09:53
We have a preview build that should fix this issue: https://desktop.docker.com/mac/preview/60183/Docker.dmg
