### ISSUE TITLE
Shrinking Docker Disk Image Size DELETES All Other Files In The Same Directory As The Disk Image

### ISSUE THREAD

**Issue by nevrending** [docker/for-mac#5486] opened 2021-03-21 17:10 UTC
The weirdest (and scary) thing just happened to me.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features (not turned on in the first place)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D0BEBD9C-F2E2-4B38-93CF-3AC7C4EC8704/20210321165013

### Expected behavior

Shrinking Docker disk image size does not delete other files in the same directory as the disk image.

### Actual behavior

Shrinking Docker disk image size **deletes all other files in the same directory as the disk image**.

### Information

  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.2.2 (61853)

### Steps to reproduce the behavior

Docker disk image was set at 40GB with 39.8GB being used. I can no longer pull/build new images.
Disk image location is set to `/Users/<username>/dev`
`Docker.raw` is present in above location.
Along with other directories containing development files (600k+ files, dating from 2014 till now).

  1. `docker system prune --all --volumes` --> `Total reclaimed space: 28.89GB`
  2. But in Preferences > Resources > Advanced the `used` did not reduce. Still sitting at `39.8GB used`
  3. I know that shrinking the disk image size will destroy all data (images, volumes, etc.; should be Docker related only data right?), so I did that. Set disk image size to 24GB. Hit `Apply & Restart`
  4. Docker restart took quite a while. Meanwhile `/Users/<username>/dev` was open in a Finder window, and I saw my directories are disappearing one by one.
  5. Had a mini heart attack.
  6. `Docker.raw` was the last file to go before it reappears with `25.77GB` in size.
  7. Confirmed that all of the other files are actually gone.
  8. Fortunately I have a Time Machine backup. (Major heart attack averted).
  9. Managed to restore them all from the backup.
  10. I'm not sure whether Docker deleted any other files from other locations. I checked Disk Utility and it said `601.47 GB (59.71 GB purgeable)`. If it does deletes any other files in other location, I will have a heart attack.

This actually happened.

![Screen Shot 2021-03-22 at 04 09 06](https://user-images.githubusercontent.com/4745298/111914020-78cf3280-8ac4-11eb-864f-3ab807923ac3.png)

**Comment by stephen-turner** [comment] 2021-03-22 14:02
Thanks for the report, looking into it.

**Comment by stephen-turner** [comment] 2021-03-22 15:37
We have reproduced this. It's a legacy from a time when the path was a folder, not an individual file. No-one else has noticed because by default the Docker.raw file does live in its own folder, but obviously if you've moved it you can encounter this bug. We will fix it as high priority. Thank you again for reporting it.

**Comment by nevrending** [comment] 2021-03-22 16:03
Thanks for the update! No worries and looking forward for the fix.

**Comment by stephen-turner** [comment] 2021-04-09 07:55
This is now fixed in Docker Desktop 3.3.0.

**Closed by stephen-turner** 2021-04-09 07:55 UTC
Labels: version/3.2.2
