### ISSUE TITLE
Upgrading docker breaks docker.inspect_container

### ISSUE THREAD

**Issue by maxmelamed** [docker/for-mac#5058] opened 2020-11-10 16:00 UTC
MacOS: Catalina 10.15.6
Docker Version: 2.5.0.1 (upgraded from 2.4.0.0)

I have code that makes essentially the following request: `curl --unix-socket /var/run/docker_sockets/docker.sock http:/v1.30/containers/foo/json`. Previously, this request would fail with `{"message":"No such container:foo"}`. However, after upgrading to 2.5.0.1, it now gives `curl: (18) transfer closed with outstanding read data remaining`. Below are the logs from this request, showing a panic causing no body to be sent in the request response. 

```Filtering the log data using "process MATCHES ".*(ocker|vpnkit).*" OR (process IN {"taskgated-helper", "launchservicesd", "kernel"} AND composedMessage CONTAINS[c] "docker")"
Timestamp                       (process)[PID]    
2020-11-10 10:53:38.891379-0500  localhost com.docker.driver.amd64-linux[36237]: proxy >> GET /containers/foo/json
2020-11-10 10:53:38.892799-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 2020/11/10 10:53:38 http: panic serving : runtime error: invalid memory address or nil pointer dereference
2020-11-10 10:53:38.892893-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: goroutine 413 [running]:
2020-11-10 10:53:38.892955-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: net/http.(*conn).serve.func1(0xc000326000)
2020-11-10 10:53:38.893005-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:1801 +0x147
2020-11-10 10:53:38.893052-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: panic(0x52dfb40, 0x6120640)
2020-11-10 10:53:38.893106-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/runtime/panic.go:975 +0x3e9
2020-11-10 10:53:38.893150-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.(*containerInspectRewriter).rewriteVolumes(0x617c7b8, 0xc0006bc6c0, 0x25, 0x200)
2020-11-10 10:53:38.893195-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/containerinspect.go:97 +0x10c
2020-11-10 10:53:38.893239-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.(*containerInspectRewriter).ResponseRewrite(0x617c7b8, 0xc00022c900, 0xc00079e360, 0x56c3240, 0xc0006e0440, 0xc0001aa720, 0xc0001c2310, 0x203000, 0x0)
2020-11-10 10:53:38.893304-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/containerinspect.go:47 +0x24e
2020-11-10 10:53:38.893388-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.(*passthrough).doHandleHTTP(0xc00046f130, 0xc480818, 0xc000010030, 0x56e98c0, 0xc000166380, 0xc00022c900, 0xbfe2cbc0b51ff5d8, 0x207405ff9fb, 0x614a7a0, 0x203000, ...)
2020-11-10 10:53:38.893442-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/passthrough.go:238 +0x91e
2020-11-10 10:53:38.893485-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.(*passthrough).HandleHTTP(0xc00046f130, 0x56e98c0, 0xc000166380, 0xc00022c900, 0x0, 0x0)
2020-11-10 10:53:38.893526-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/passthrough.go:125 +0x4ff
2020-11-10 10:53:38.893564-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.withError.func1(0x56e98c0, 0xc000166380, 0xc00022c900)
2020-11-10 10:53:38.893605-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/routes.go:16 +0x51
2020-11-10 10:53:38.893647-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: net/http.HandlerFunc.ServeHTTP(0xc000329820, 0x56e98c0, 0xc000166380, 0xc00022c900)
2020-11-10 10:53:38.893685-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:2042 +0x44
2020-11-10 10:53:38.893729-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/docker/pinata/common/pkg/proxy.(*GuiAnalytics).Middleware.func1(0x56e98c0, 0xc000166380, 0xc00022c900)
2020-11-10 10:53:38.893777-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/common/pkg/proxy/analytics.go:62 +0xae
2020-11-10 10:53:38.893838-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: net/http.HandlerFunc.ServeHTTP(0xc0001aa2e0, 0x56e98c0, 0xc000166380, 0xc00022c900)
2020-11-10 10:53:38.893887-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:2042 +0x44
2020-11-10 10:53:38.893929-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000428cc0, 0x56e98c0, 0xc000166380, 0xc00022c700)
2020-11-10 10:53:38.893971-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/jenkins/workspace/sktop_desktop-build_stable-2.5.x/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
2020-11-10 10:53:38.894012-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: net/http.serverHandler.ServeHTTP(0xc0001660e0, 0x56e98c0, 0xc000166380, 0xc00022c700)
2020-11-10 10:53:38.894048-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:2843 +0xa3
2020-11-10 10:53:38.894084-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: net/http.(*conn).serve(0xc000326000, 0x56ec500, 0xc0006e0080)
2020-11-10 10:53:38.894119-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:1925 +0x8ad
2020-11-10 10:53:38.894194-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: created by net/http.(*Server).Serve
2020-11-10 10:53:38.894293-0500  localhost com.docker.supervisor[36227]: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 36237): stderr: 	/Users/administrator/.pinata/downloads/go/1.15.2/go/src/net/http/server.go:2969 +0x36c```

**Comment by gesellix** [comment] 2020-11-11 13:41
Same here. The following one-liner reproduces the issue:

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock alpine:edge ash -c 'apk add -U curl && curl --unix-socket /var/run/docker.sock http://localhost/containers/foo/json -v'
> GET /containers/foo/json HTTP/1.1
> Host: localhost
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Api-Version: 1.40
< Content-Type: application/json
< Date: Wed, 11 Nov 2020 13:35:34 GMT
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.13 (linux)
< Transfer-Encoding: chunked
< 
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

Running a Docker-in-Docker container with the same Docker version (`docker:19.03.13-dind`) doesn't break.

**Comment by stephen-turner** [comment] 2020-11-12 15:16
Thanks for the report. I'm going to close this as a dupe of #5025. Please follow that ticket for updates.

**Closed by stephen-turner** 2020-11-12 15:16 UTC
Labels: version/2.5.0.1
