### ISSUE TITLE
Update failed, daemon cannot start

### ISSUE THREAD

**Issue by trops** [docker/for-mac#2756] opened 2018-03-31 18:22 UTC
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ Y] I have tried with the latest version of my channel (Stable or Edge)
  - [ Y] I have submitted Diagnostics
  - [ Y] I have included the Diagnostics ID in this Issue

### Expected behavior

Docker to start.

### Actual behavior

Docker does not start.

### Information

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/6A4C358D-A89D-487C-A94C-92BD9FBA2961/20180331-141657.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/trops/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/trops/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/trops/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk


```

### Steps to reproduce the behavior

  1. Accept the "Update docker to latest version"
  2. Fails.

**Comment by gtardif** [comment] 2018-04-01 08:41
This is duplicate of #2739. This was due to a problem when migrating straight from 17.09 to 18.03.
It should be fixed with the latest Docker for Mac 18.03.0-mac60 Stable release (you can download at https://download.docker.com/mac/stable/Docker.dmg)

**Closed by gtardif** 2018-04-01 08:41 UTC
Labels: version/18.03.0-ce-mac59
