### ISSUE TITLE
Docker app for mac crashes unexpectedly

### ISSUE THREAD

**Issue by paragmajum** [docker/for-mac#319] opened 2016-08-17 09:38 UTC
### Steps to reproduce
Click docker app on mac to start it.

### Expected behavior
There shouldn't be any error in starting docker

### Actual behavior
Get the following popup but the docker process is running in the mac toolbar.
See screenshot:
<img width="572" alt="screen shot 2016-08-17 at 11 33 57" src="https://cloud.githubusercontent.com/assets/208331/17731709/ca7f8b56-646e-11e6-99b3-9c1de5946c3f.png">

### Information

```
Diagnostic ID: DDC5D94E-8419-4D57-A9BC-90E1812A624E
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment] 2016-08-17 09:49
Duplicate of #64.

**Closed by dsheets** 2016-08-17 09:49 UTC

**Comment by djs55** [comment] 2016-09-15 16:18
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
