### ISSUE TITLE
Error with new Macos

### ISSUE THREAD

**Issue by AkademieOlympia** [docker/for-mac#162] opened 2016-08-07 05:43 UTC
### Information

Diagnostic ID: A05D0968-2E2D-4755-8CA1-5670AD7CE033
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A269f)

### Steps to reproduce

1. ...
2. ...

**Comment by avsm** [comment] 2016-08-08 13:17
Duplicate of #64 -- please see https://github.com/docker/for-mac/issues/64#issuecomment-238191340 for progress on getting this working.

**Closed by avsm** 2016-08-08 13:17 UTC

**Comment by djs55** [comment] 2016-09-15 16:28
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
