### ISSUE TITLE
CLI for Docker For Mac

### ISSUE THREAD

**Issue by nmcalabroso** [docker/for-mac#882] opened 2016-11-01 18:47 UTC
# CLI for Docker For Mac
## Feature Request

Is it possible to have all the features that can be done via the GUI of Docker for Mac to some sort of CLI? This request is coming from an annoying issue from #412 that is holding back people who want to use their containers both for GNU/Linux and MacOS. Thank you!

**Comment by dsheets** [comment] 2017-01-16 15:50
#412 was resolved in Beta 33 and support was improved in Beta 35 or 36. Do you still need this functionality?

**Comment by quantonganh** [comment] 2017-01-19 04:23
> Do you still need this functionality?

Yes, I still need this.

Quoted from this: https://forums.docker.com/t/how-to-run-docker-for-mac-as-a-service-or-deamon/18728

## Expected behavior

There should be a way to install Docker For Mac as a service which runs at system startup.

## Actual behavior

Docker for Mac Beta seems to require a ui based app "Docker.app" to run in a graphical user session. I could not figure out any way on how to start the Docker environment using cli tools.
The older Docker Toolbox allowed the use of e.g. docker-machine command to start its VirtualBox based environment. This allowed to create start-up scripts, to create a server ecosystem at system startup without a user to login.

## Information

We'd like to use the great "Docker for Mac Beta" asap in a productive environment using the elegant integration with the native MacOS virtualization framework. So it would be of cause more robust and user friendly to install and run Docker and it's containers as system services automatically and independent on a user-login. 
I tried to find suitable CLI tools in the Docker.app package but haven't been successful.

Is there any recommended way to install and run "Docker for Mac Beta" and its container as a service automatically at system startup?

**Comment by samoht** [comment] 2017-01-31 15:37
There is no short-term plan to add a command-line interface to Docker for Mac, so closing as "won't fix" (at least in the short/middle term). We understand that this is an important component for some use-cases, but we have no plans to work on this currently.

**Closed by samoht** 2017-01-31 15:37 UTC
Labels: kind/feature, status/0-wont-fix, status/1-acknowledged

**Comment by martinm82** [comment] 2017-08-22 13:22
This is kind of insane. On one side you are developing a tool that is supposed to isolate apps/services and make it easy to deploy them everywhere but if it is about deploying the tool itself on a large number of macOS nodes than that is not supported and won't be.
Right now I am using Ansible to deploy D4M on the nodes and need to pause Ansible in order to configure it manually. 

Any plans to make the D4M UI open source so that this feature could be contributed to you?

**Comment by ebriney** [comment] 2017-08-23 09:29
Hi @martinm82 , we are using that script in our CI, tell me if it works for you.
I put the latest stable url but we can change it of course.

```
curl -f https://download.docker.com/mac/stable/Docker.dmg -o Docker.dmg
hdiutil verify Docker.dmg
hdiutil attach Docker.dmg -mountpoint dmg_mount -nobrowse
rm -rf /Applications/Docker.app
mkdir -p /Applications/Docker.app
cp -av dmg_mount/Docker.app/ /Applications/Docker.app
hdiutil detach dmg_mount
rmdir dmg_mount
sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended
```

**Comment by martinm82** [comment] 2017-08-23 12:03
Hi Emmanuel,
this is really nice. Seems to work. Do you know whether it is as well
possible to extend for example the file sharing via command line?
Thanks a lot.
Martin

**Comment by lyndsey-ferguson** [comment] 2018-01-01 16:07
I really need to install Docker.app via the command line. ` sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended` does not launch the tools needed. Unless I run the app by double clicking it in the GUI, `docker ps` complains about the daemon not running.

I use ansible to set up many Mac minis for Continuous Integration and it is not reasonable that I have to log into each machine via VNC to get Docker to completely install.

**Comment by djs55** [comment] 2018-01-01 16:20
@lyndsey-ferguson the argument `--quit-after-install` shuts everything down after the installation. Try either removing this argument or re-launching the app using `open /Applications/Docker.app` (as a regular user i.e. without `sudo`) afterwards.

**Comment by lyndsey-ferguson** [comment] 2018-01-01 17:04
Thanks, I tried that but the Docker.app doesn't stops responding after a few seconds. I left it running for 30 minutes with the thought that it was so busy that it was not responding on the main thread, but the "not responding" status (in the Activity Monitor app) did not change.

**Comment by lyndsey-ferguson** [comment] 2018-01-01 18:24
The problem was that, in my experimentation, I had started the `/Library/LaunchDaemons/com.docker.vmnetd.plist` LaunchDaemon. Unloading that allowed me to get this setup properly.

**Comment by martinm82** [comment] 2018-01-02 11:05
So in my setup we need to have an open session (logged in) with a specific user.
In order to properly configure Docker I need to run the app (with `--quit-after-install --unattended`) two times, once running as root user to configure properly the `vmnetd` daemon than I need to re-run it but as the user that will be logged-in to configure the rest (settings for D4M like CPUs, memory, etc.).

Configuring automatically additional mount points was as well not straight forward but after some time I figured out that the configuration itself is stored in a git repo (`/Users/{{ docker_username }}/Library/Containers/com.docker.docker/Data/database/`) in the following file `/Users/{{ docker_username }}/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/mounts`.

My custom launchd configuration as well looks a bit different:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tomtom.docker</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/bin/open</string>
      <string>-a</string>
      <string>/Applications/Docker.app</string>
      <string>--args</string>
      <string>--unattended</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```
If I don't specify the additional args I get after a reboot always the welcome dialog and Docker won't start-up (even if I disable the welcome message in the settings.json.

**Comment by lyndsey-ferguson** [comment] 2018-01-02 13:46
Thanks @martinm82, I will use that if we experience the same issue.

**Comment by jensgreen** [comment] 2019-06-27 14:35
We managed to do an unattended install that automatically starts the Docker daemon and launches it on login without the "[We are whaly happy to have you](https://user-images.githubusercontent.com/2438597/60272947-60cd7d80-98f5-11e9-896d-5dba86d5877b.png)" popup.

Steps:
- Install the Docker Desktop .dmg (we used 2.0.0.3)
- Run `/Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended` as root
  - (unless: `pgrep -q -f /Library/PrivilegedHelperTools/com.docker.vmnetd`)
- Set the following lines in`~/Library/Group Containers/group.com.docker/settings.json`:
  ```
  "displayedWelcomeMessage" : true,
  "displayedWelcomeWhale" : true,
  ```
- Run `/usr/bin/open -g -j -a /Applications/Docker.app`
  - (unless: `pgrep -q -f /Applications/Docker.app/Contents/MacOS/Docker`)

The Docker daemon is launched and starts up successfully after reboot.

**Comment by rfay** [comment] 2019-07-31 17:33
As mentioned in https://github.com/docker/for-mac/issues/2359#issuecomment-516945781 the 
```
/Applications/Docker.app/Contents/MacOS/Docker --unattended
/Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended
```
doesn't work any more in Docker Desktop 2.1.0.0 (docker v19.03.1). Now you get the error message:
```
DockerApplication: Docker.app starting for root
Terminator: Running Docker Desktop as root is dangerous. Please run it as a regular user.
```

Which breaks our CI :( For now, I can download earlier version, but Docker folk... please tell us how to do an unattended installation!
