### ISSUE TITLE
com.docker.osxfs is not running  com.docker.driver.amd64-linux -db is not running

### ISSUE THREAD

**Issue by davidfekke** [docker/for-mac#497] opened 2016-09-01 23:43 UTC
### Steps to reproduce

1. I tried to update

### Expected behavior

Docker was supposed to start

### Actual behavior

Docker failed to start after update.

### Information

```
Diagnostic ID: 4A2CE929-0B21-40E3-BEA0-D3AE925BEC1C
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment] 2016-09-01 23:46
Thanks for submitting. 
May be similar to https://github.com/docker/for-mac/issues/484

**Comment by mchiang0610** [comment] 2016-09-12 23:52
#119 

We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Closed by mchiang0610** 2016-09-12 23:52 UTC
Labels: area/linux, area/startup, area/storage, kind/bug, osx/10.12 (beta), version/beta24

**Comment by djs55** [comment] 2016-09-15 16:08
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by dennissheppard** [comment] 2016-10-25 19:21
Same issue with latest beta:

`Docker for Mac: version: 1.12.2-beta28 (71c4a00)
OS X: version 10.12 (build: 16A323)
logs: /tmp/FAFA21A6-76A8-4BA2-A928-37D1C961C0AE/20161025-141957.tar.gz
failure: com.docker.osxfs is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[ERROR]  slirp
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)`

**Comment by Jokersoft** [comment] 2016-10-31 10:11
Same with the newer version

> Docker for Mac: version: 1.12.3-beta29.2 (902414d)
> OS X: version 10.12 (build: 16A323)
> logs: /tmp/406E5697-E959-4636-8B90-A00383A6724F/20161031-110948.tar.gz
> failure: com.docker.slirp is not running
> [OK]     vmnetd
> [OK]     dns
> [ERROR]  driver.amd64-linux
>          com.docker.driver.amd64-linux -db is not running
> [OK]     virtualization VT-X
> [OK]     app
> [OK]     moby
> [OK]     system
> [OK]     moby-syslog
> [OK]     db
> [OK]     env
> [OK]     virtualization kern.hv_support
> [ERROR]  slirp
>          com.docker.slirp is not running
>          slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
> [ERROR]  osxfs
>          com.docker.osxfs is not running
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          docker ps failed
> [OK]     menubar
> [OK]     disk
> Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
>

**Comment by dsheets** [comment] 2016-11-01 12:06
@dennissheppard @Jokersoft please open new issues with what you've observed and your diagnostic reports and IDs. It's unlikely the root cause of your issues are the same as the original poster and we are very unlikely to properly handle your issues on a closed ticket. Thanks!
