### ISSUE TITLE
Cannot push image to local registry

### ISSUE THREAD

**Issue by NFarrington** [docker/for-mac#3611] opened 2019-04-03 10:06 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5B25BFA5-45C6-4E9C-9CCF-31B8375E0A19/20190403095701

### Expected behavior

When following the instructions to run a local registry at https://docs.docker.com/registry/deploying/#run-a-local-registry, you should be able to push an image to a local registry.

### Actual behavior

When following the documentation, pushing to a local registry now fails with the error `Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused`:

```
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
58c57b9042a75706167ef5eb458fb094dec247fed8b509085c186a6ebce23af9
$ docker pull ubuntu:16.04
16.04: Pulling from library/ubuntu
Digest: sha256:58d0da8bc2f434983c6ca4713b08be00ff5586eb5cdff47bcde4b2e88fd40f88
Status: Image is up to date for ubuntu:16.04
$ docker tag ubuntu:16.04 localhost:5000/my-ubuntu
$ docker push localhost:5000/my-ubuntu
The push refers to repository [localhost:5000/my-ubuntu]
Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused
```

### Information

  - macOS Version: 10.14.4

After upgrading from Docker for Mac 2.0.2.1 to 2.0.3.0, Docker is now unable to push images to a local registry via localhost, which should be possible based on https://docs.docker.com/registry/deploying/#run-a-local-registry. I would assume this has been caused by the fixes that were applied in 2.0.3.0 for https://github.com/docker/for-mac/issues/3522

### Diagnostic logs

```
Docker for Mac: version 2.0.3.0
```

### Steps to reproduce the behavior

To reproduce, run the following using version 2.0.3.0:
```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
docker pull ubuntu:16.04
docker tag ubuntu:16.04 localhost:5000/my-ubuntu
docker push localhost:5000/my-ubuntu
```

**Comment by jldec** [comment] 2019-04-03 14:13
We're seeing the same problem (just on Edge v2.0.3.0, not on stable v2.0.0.3) on both Mac and Windows.

The issue manifests if you use an image tag `localhost:5000/...` or `127.0.0.1:5000/...` but _not_ if you use a different hostname e.g. `registry.me` pointed to localhost via /etc/hosts

```
$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	      localhost registry.me
255.255.255.255	broadcasthost
::1             localhost
```

```
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
Unable to find image 'registry:2' locally
2: Pulling from library/registry
c87736221ed0: Pull complete 
1cc8e0bb44df: Pull complete 
54d33bcb37f5: Pull complete 
e8afc091c171: Pull complete 
b4541f6d3db6: Pull complete 
Digest: sha256:3b00e5438ebd8835bcfa7bf5246445a6b57b9a50473e89c02ecc8e575be3ebb5
Status: Downloaded newer image for registry:2
67969b56d8d33056e8d66b1e7cb2e3e01fd79fa3b1af7fa5ed8597ea96cb3924

$ docker pull ubuntu:16.04
16.04: Pulling from library/ubuntu
34667c7e4631: Pull complete 
d18d76a881a4: Pull complete 
119c7358fbfc: Pull complete 
2aaf13f3eff0: Pull complete 
Digest: sha256:58d0da8bc2f434983c6ca4713b08be00ff5586eb5cdff47bcde4b2e88fd40f88
Status: Downloaded newer image for ubuntu:16.04

$ docker tag ubuntu:16.04 localhost:5000/my-ubuntu

$ docker push localhost:5000/my-ubuntu
The push refers to repository [localhost:5000/my-ubuntu]
Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused

$ docker tag ubuntu:16.04 127.0.0.1:5000/my-ubuntu

$ docker push 127.0.0.1:5000/my-ubuntu
The push refers to repository [127.0.0.1:5000/my-ubuntu]
Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused

$ docker tag ubuntu:16.04 registry.me:5000/my-ubuntu

$ docker push registry.me:5000/my-ubuntu
The push refers to repository [registry.me:5000/my-ubuntu]
297fd071ca2f: Pushed 
2f0d1e8214b2: Pushed 
7dd604ffa87f: Pushed 
aa54c2bc1229: Pushed 
latest: digest: sha256:d7d4f38deab29555ed2a9f13f4cb71f33e6f8788529512401d4e0638f2c3ba51 size: 1150
```

note i have those registry names configured as insecure
```
$ cat ~/.docker/daemon.json 
{
  "insecure-registries" : [
    "localhost:5000",
    "127.0.0.1:5000",
    "registry.me:5000"
  ],
  "debug" : true,
  "experimental" : true
}
```

cc: @glyn

**Comment by jldec** [comment] 2019-04-03 14:17
b.t.w the fact that the error messages are slightly different for the different hostnames suggests that maybe this is a problem in the way the daemon is looking up hostnames via DNS.

```
Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused
```
``` 
Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused
```

**Comment by moberg** [comment] 2019-04-24 00:11
I have the exact same issue.

**Comment by djs55** [comment] 2019-05-03 09:17
Thanks for the report (and for the ping via the Docker booth at DockerCon). The fix is merged in the `vpnkit-userland-proxy` helper tool which is inside the VM image. I've made a PR to Docker Desktop itself adding the fix, an end-to-end test to prevent this from happening in future and a release note tagging this issue.

**Comment by jldec** [comment] 2019-06-12 11:48
Confirmed fixed in edge release v2.0.5.0 from June 11. 2019

**Comment by djs55** [comment] 2019-06-12 13:27
@jldec thanks for the confirmation. I'll chose this ticket but feel free to comment again (or make a fresh issue) if there are further problems.

**Closed by djs55** 2019-06-12 13:27 UTC
Labels: version/2.0.3.0

**Comment by vincentcr** [comment] 2019-09-09 20:34
@djs55 I'm experiencing this issue with latest docker: 2.1.0.2. The `/etc/hosts` workaround mentionned above fixed it for me.

**Comment by icechen1** [comment] 2019-10-25 17:42
Same here. The issue is present in v2.1.0.3

**Comment by bjamesvDatica** [comment] 2019-11-13 22:01
Same issue in v2.1.0.4 stable, `/etc/hosts` workaround got me past the problem

**Comment by nonsense** [comment] 2019-12-16 15:12
Same issue with v2.1.0.5, `/etc/hosts` workaround fixed it.

**Comment by jaspreetwaraich** [comment] 2019-12-20 20:24
I've the same issue in windows 10. any suggestions?

**Comment by RAbraham** [comment] 2019-12-23 00:05
same issue on Mac Mojave. https://github.com/docker/for-mac/issues/3611#issuecomment-479507361 suggestion of /etc/hosts worked for me.

**Comment by alfredodeza** [comment] 2020-03-27 18:14
Just ran into this using:

```
$ docker --version
Docker version 19.03.5, build 633a0ea
```

Tagging to `0.0.0.0:5000` worked for me.

**Comment by dtracers** [comment] 2020-05-14 02:16
Ran into this while running github actions

`Docker version 3.0.11+azure, build eb310fca49568dccd87c6136f774ef6fff2a1b51`

```
Get https://0.0.0.0:5000/v2/: read tcp 127.0.0.1:60328->127.0.0.1:5000: read: connection reset by peer
The push refers to repository [0.0.0.0:5000/parseidon]
```

Tried above tag did not work.
