### ISSUE TITLE
docker for mac pop a error window shows:vmstateevent invalid json: 

### ISSUE THREAD

**Issue by testj** [docker/for-mac#780] opened 2016-10-11 08:11 UTC
### Information

Diagnostic ID: E2A8A6C7-3821-4856-98C0-58C0AA7BB659
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment] 2016-10-11 08:26
Duplicate of #80 Please upgrade to either the last stable (1.12.1) or Beta 27 (1.12.2-rc1).

**Closed by samoht** 2016-10-11 08:26 UTC
