### ISSUE TITLE
Upgrading from Docker Desktop 4.2.0 to 4.3.0 breaks any systemd use

### ISSUE THREAD

**Issue by aem12f** [docker/for-mac#6093] opened 2021-12-13 20:56 UTC
If this has been talked about somewhere already, please share a link! Thanks!

  - [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I build my project and systemd is able to to boot as the init process and start services needed. This is fully operational on Docker Desktop 4.2.0

### Actual behavior

The socket is broken and systemd is unable to be the init process.

### Information

  - macOS Version: Mac OS Big Sur 11.6, also tried on Mac Monterrey (new update)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.3.0

### Steps to reproduce the behavior

  1. ... using docker-compose, my base image is from docker pull jrei/systemd-ubuntu, should be able to install and run services as systemd. 
  2. ...

I fully understand the Docker community could care less about systemd, and it was not the intended use for Docker, but it is widely popular, will be for some time, and really serves a great purpose. It would be a shame to see this not work in the future. Thanks to the anyone that contributes.

**Comment by goshdarnitnick** [comment] 2021-12-15 03:35
I'm having the same issue here. I can't use systemd in an Ubuntu 20.04 container, even following the instructions at https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-431.

**Comment by madrover** [comment] 2021-12-17 15:51
See https://github.com/docker/for-mac/issues/6073

**Comment by goshdarnitnick** [comment] 2021-12-18 07:23
> See #6073

That’s what I ended up doing, running the dev build right now using the cgroupv1 config option.

**Comment by StefanScherer** [comment] 2021-12-20 06:26
I'm going to close this issues as it's a duplicate of #6073, please follow the discussion and progress there.

**Closed by StefanScherer** 2021-12-20 06:26 UTC
