### ISSUE TITLE
Updating docker fails on Mac Sierra Beta 16A286a

### ISSUE THREAD

**Issue by luiseduardocolon** [docker/for-mac#335] opened 2016-08-17 20:38 UTC
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 654D69BD-F8A5-4E71-AE60-02F5887301FF
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A286a)
```

**Comment by dsheets** [comment] 2016-08-19 13:42
This is a duplicate of #202.

**Closed by dsheets** 2016-08-19 13:42 UTC

**Comment by djs55** [comment] 2016-09-15 16:17
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
