### ISSUE TITLE
DNS lookup via 196.168.65.1 fails to respect Mac OS X settings

### ISSUE THREAD

**Issue by xeger** [docker/for-mac#1405] opened 2017-03-07 19:50 UTC
### Expected behavior

My DHCP server provides bad DNS config, pointing me to an ISP-provided DNS that does catch-all resolution, and setting a nonsensical search suffix.

On my host OS, I have overridden DNS settings manually, specifying Google DNS and providing a harmless search suffix. Until recently, Docker for Mac was using my override; public DNS queries from inside containers, and/or inside the DfM VM, were being routed to Google DNS.

### Actual behavior

Beginning 2017/03/06, Docker for Mac's behavior changed; now, when the Moby VM boots, `resolv.conf` reflects the bogus settings being provided by my DHCP server, and not the overrides I've configured my Mac to use!

### Information

See diagnostic 0D949E51-A33A-4D7B-A421-744307A69484

### Steps to reproduce the behavior

  1. Configure DHCP server to provide bogus DNS settings
  2. Configure OS X to override with useful settings (under  System Preferences > Network > Advanced > DNS)
  3. Run Docker for Mac; launch a container; observe that DNS is failing

**Comment by matthewbarr** [comment] 2017-03-07 20:21
FYI: This is pretty similar to what I'm seeing in  #1397

**Comment by xeger** [comment] 2017-03-07 20:50
Thanks; looks like a near-duplicate, although I'm not using a VPN so vpnkit is just getting in my way.

Will leave this issue open until a maintainer has triaged, but I suspect this is a dupe of #1397, modulo minor details.

**Comment by matthewbarr** [comment] 2017-03-07 20:52
Upside: You're using 10.12, I'm using 10.11.    And net result is that you probably have a few entries in scutil, if you grep for DNS.  Probably Global, and a few others, which is probably why it's doing the same thing for you as for me.

Checking the contents of the slirp/dns file might be worth verifying, as an additional data point.

**Comment by xeger** [comment] 2017-03-07 21:19
I drew on @djs55's scutil expertise and found a workaround: https://github.com/docker/for-mac/issues/1397#issuecomment-284860424

**Comment by MagnusS** [comment] 2017-03-10 13:41
It looks like the same issue so I'll close this as a duplicate of #1397 for now - please reopen if it turns out not to be the case.

**Closed by MagnusS** 2017-03-10 13:41 UTC
Labels: osx/10.12.x, status/0-triage, version/17.03.0-ce-mac2
