### ISSUE TITLE
On Mac OSX => [ERROR]  driver.amd64-linux com.docker.driver.amd64-linux is not running

### ISSUE THREAD

**Issue by mallaway** [docker/for-mac#2319] opened 2017-12-14 09:48 UTC
### Expected behavior

Docker restarts after update.

### Actual behavior

Docker fails to restart following update.

### Information

Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/F0DF6E1C-64ED-49D5-9488-F1B43086142A/20171214-094011.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mallaway/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mallaway/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mallaway/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Restart Docker.

**Comment by gtardif** [comment] 2017-12-14 10:42
This is a duplicate of #2317 (See comments to fix settings without need for a full reset)

**Closed by gtardif** 2017-12-14 10:42 UTC
