### ISSUE TITLE
Unable to access local Docker registry when proxy enabled

### ISSUE THREAD

**Issue by rbywater** [docker/for-mac#5630] opened 2021-04-26 22:31 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A67103F2-4EC0-4AA8-B2D9-ADF7F76443ED/20210426214508

### Expected behavior
With proxy configured and Proxy Bypass setting set to (e.g.) docker.myregistry.com one should be able to use `docker pull docker.myregistry.com/openjdk:11` and pull the respective image.

### Actual behavior
Unable to pull due to the requests being sent to the configured proxy server which then cannot talk to the internal registry and a "Bad Gateway" error is received.

This issue also affects `docker login`.

### Information

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1 (63152)

This issue started with the 3.3.0 release presumably due to the change to the HTTP Proxy setup. Same setup works fine with 3.2.x

### Steps to reproduce the behavior

  1. Configure Docker with a proxy server that cannot access a particular resource which can be accessed directly
  2. Configure Proxy Bypass for internal registry hostname
  3. Try to `docker pull` an image or `docker login` to the internal registry hostname

**Comment by mcamenzind** [comment] 2021-04-27 09:19
Same here, somehow the "no proxy" or "proxy bypass" settings are not respected in 3.3.x. Our proxy bypass configuration worked fine for 3.2.x, now any interaction with the private repository is impossible.

 We're downgrading.

**Comment by stephen-turner** [comment] 2021-04-27 15:17
Thanks for the report, this is a dupe of #5617. We're still trying to understand the cause.

**Closed by stephen-turner** 2021-04-27 15:17 UTC
Labels: version/3.3.1
