### ISSUE TITLE
docker start failed

### ISSUE THREAD

**Issue by jefyian** [docker/for-mac#2466] opened 2018-01-19 05:37 UTC
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/DFE6456D-ACBC-4972-A2FC-85335F547EF9/20180119-133411.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/blaxun/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/blaxun/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/blaxun/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/blaxun/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/blaxun/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

**Comment by akimd** [comment] 2018-01-19 09:03
Duplicate of #2383.

**Closed by akimd** 2018-01-19 09:03 UTC
