### ISSUE TITLE
The docker crash window pops up while not doing anything with docker.

### ISSUE THREAD

**Issue by martinborgman** [docker/for-mac#312] opened 2016-08-16 20:25 UTC
This is the second time this happened with tis version of docker.

### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 2CD38D77-67BD-4FE9-AAC0-10440BA0B4FD
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[ERROR]  disk
         Docker.qcow2 is corrupt: reset to factory defaults is required
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment] 2016-08-17 09:10
This is likely caused by the ongoing issues with golang and macOS Sierra Beta. This is a duplicate of #64.

**Closed by dsheets** 2016-08-17 09:10 UTC

**Comment by djs55** [comment] 2016-09-15 16:19
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
