### ISSUE TITLE
Network Requests Way Slower Inside Container

### ISSUE THREAD

**Issue by k2xl** [docker/for-mac#860] opened 2016-10-27 20:14 UTC
### Steps to reproduce the behavior
1. Run a container, any container (even with host network enabled) on Mac
2. Install `curl` in the container. Try `time curl google.com`
3. Exit the container. Run `time curl google.com` on host.

I'm getting much slower response when inside container. I just upgraded to Version 1.12.3-beta29.2 (13499) and still seeing this issue.

**Comment by samoht** [comment] 2016-11-03 22:09
Which ratio of slow down do you get? What version of OSX do you run?

**Comment by k2xl** [comment] 2016-11-03 22:31
On Sierra. It is like 10ms vs 1.5 seconds

**Comment by ijc25** [comment] 2016-11-15 16:08
I think this is a duplicate of #727, please subscribe to that issue for further updates.

**Closed by ijc25** 2016-11-15 16:08 UTC
Labels: osx/10.12.x, status/0-triage, version/beta29.2
