### ISSUE TITLE
riscv64 binfmt emulation fails on Docker Desktop Mac 3.3.3

### ISSUE THREAD

**Issue by rvs** [docker/for-mac#5699] opened 2021-05-17 23:24 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features

### Expected behavior

The following command works as it does on Linux's docker with binfmt and qemu-static installed:

$ docker build -t riscv64 https://raw.githubusercontent.com/rvs/eve/riscv64/build-tools/src/scripts/Dockerfile.alpine.bootstrap

### Actual behavior

Command fails with:

```
#12 0.256 qemu-riscv64: unable to find CPU model 'max'
```

### Information
  - macOS Version: 10.15.7
  - Intel chip or Apple chip: x86
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior 

docker build -t riscv64 https://raw.githubusercontent.com/rvs/eve/riscv64/build-tools/src/scripts/Dockerfile.alpine.bootstrap

**Comment by thaJeztah** [comment] 2021-05-18 05:55
Thanks!

**Comment by stephen-turner** [comment] 2021-05-18 11:25
Thanks, this will be fixed in the next version.

**Comment by djs55** [comment] 2021-05-26 15:16
@rvs if you'd like to try an early build with the candidate fix: https://desktop-stage.docker.com/mac/stable/amd64/64870/Docker.dmg . The only snag is it's not notarized so you will probably need to acknowledge a warning from macOS. I added an end-to-end test based on your example so hopefully we'll catch regressions in future.

**Comment by rvs** [comment] 2021-06-01 11:14
Hey @djs55 -- thanks for the update -- I can confirm that the issue is now fixed. Feel free to close this ticket.

**Closed** 2021-06-02 09:26 UTC

**Comment by rvs** [comment] 2021-06-02 09:40
Hey @djs55 while this is not related to this issue -- I've noticed a strange behavior of buildkit with the image you provided. What's the best way to file this other issue?

**Comment by thaJeztah** [comment] 2021-06-02 10:26
@rvs you can open a ticket in this repository with details (if it turns out to be better filed in another issue tracker based on that, we can go from there), thanks!
