### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 1

### ISSUE THREAD

**Issue by lyw007** [docker/for-mac#1676] opened 2017-06-02 01:36 UTC
### Information

iagnostic ID: 5AF69E5E-4EB7-4862-8A8C-B9227DCDFEC9

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/5AF69E5E-4EB7-4862-8A8C-B9227DCDFEC9/20170602-092710.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/romens/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/romens/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/romens/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/romens/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/romens/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/romens/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SantoDE** [comment] 2017-06-02 09:18
+1. I can't even get trough to the diagnostic thingy :) It crashes before it can fetch it

**Comment by avivshafir** [comment] 2017-06-02 09:43
+1

**Comment by SantoDE** [comment] 2017-06-05 10:35
That is probably a duplicate of #1669 ?

**Comment by ebriney** [comment] 2017-06-05 12:18
It seems that your hardware is not supported by Apple hypervisor framework.
```
2017-06-01 18:00:24+08 UserName Docker[com.docker.driver.amd64-linux][19172] <Notice>: Unable to create VM (-85377018)
2017-06-01 18:00:24+08 UserName Docker[com.docker.driver.amd64-linux][19172] <Notice>: vmx_init: processor not supported by Hypervisor.framework
2017-06-01 18:00:24+08 UserName Docker[com.docker.driver.amd64-linux][19172] <Notice>: Hypervisor subprocess has shutdown
2017-06-01 18:00:24+08 UserName Docker[com.docker.osx.hyperkit.linux][19166] <Notice>: Reap com.docker.driver.amd64-linux (pid 19172): exit status 0
```
What kind of hardware is it? From the diag it's a MacBookPro8,1 (MacBook Pro "Core i7" 2.7 13" Early 2011) and it should work on Sandy Bridge.

**Comment by jasonbivins** [comment] 2017-06-23 14:59
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Closed by jasonbivins** 2017-06-23 14:59 UTC
Labels: osx/10.12.x, status/0-more-info-needed, version/17.03.1-ce-mac12
