### ISSUE TITLE
Crash when start on last osx update (beta 3)

### ISSUE THREAD

**Issue by pcollaog** [docker/for-mac#81] opened 2016-08-02 19:31 UTC
### Expected behavior

Just run 

### Actual behavior

Crash when start docker

### Information

Diagnostic ID: EA5BA8B8-98C2-4776-8EBF-836C9BE17CCE
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12 (Build 16A270f)

**Comment by dave-tucker** [comment] 2016-08-09 01:37
Closing as dupe of #64

**Closed by dave-tucker** 2016-08-09 01:37 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
