### ISSUE TITLE
APIError during ruby gem installation activity within container

### ISSUE THREAD

**Issue by goneflyin** [docker/for-mac#678] opened 2016-09-20 15:56 UTC
### Expected behavior

Have been running a set of containers within docker-machine for some time, but now when testing within Docker for Mac I am getting a fairly reproducible occurrence of a crash from Docker, the traceback of which has been submitted numerous times so far. Not sure if this is a repeat of an already reported issue or something new, but it is likely similar to #676 or related to [Hyperkit Issue 50](https://github.com/docker/hyperkit/issues/50)

39712634-BCC7-4878-9DE1-1735D5EC66BE
### Actual behavior

Here's an excerpt from the output/log when it happened:
```
ib-gems_1        | Fetching dependency metadata from https://rubygems.org/.
ib-gems_1        | Resolving dependencies........
ib-gems_1        | Installing rake 10.1.1
ib-gems_1        | Installing Platform 0.4.0
ib-gems_1        | Installing open4 1.3.0
ib-gems_1        | Installing aaronh-chronic 0.3.9
ib-gems_1        | Installing i18n 0.7.0
ib-gems_1        | Installing json 1.8.3 with native extensions
ib-gems_1        | Installing minitest 5.8.4
ib-gems_1        | Installing thread_safe 0.3.5
ib-gems_1        | Installing builder 3.1.4
ib-gems_1        | Installing erubis 2.7.0
ib-gems_1        | Installing mini_portile 0.6.2
ib-gems_1        | Installing rack 1.6.4
ib-gems_1        | Installing mime-types 1.25.1
ib-gems_1        | Installing polyglot 0.3.5
ib-gems_1        | Installing arel 6.0.3
ib-gems_1        | Installing activerecord-oracle_enhanced-adapter 1.6.7
ib-gems_1        | Installing thor 0.19.1
ib-gems_1        | Installing ffi 1.9.10 with native extensions
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/scott.pfister/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```

### Information

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/39712634-BCC7-4878-9DE1-1735D5EC66BE/20160920-104451.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

I'll try to create a simplified Dockerfile and environment to make it reproducible.

### Steps to reproduce the behavior

TBD

**Comment by ijc25** [comment] 2016-09-29 09:41
I've had a dig through the logs and I am fairly confident that this isn't docker/hyperkit#50. Nothing else leapt out at me as being obviously the cause of this issue though. If you are able to provide a reproducer that would likely be very valuable.

**Comment by dsheets** [comment] 2016-09-29 14:27
I see a number of failures like

```
Docker[com.docker.slirp][28728] <Error>: Socket.Datagram.input: bind returned file table overflow
```

which indicate something is either leaking or very rapidly consuming file descriptors. There was one fix for this in relation to many rapid DNS requests in the recently released Beta 27. If you're comfortable trying out a beta (which requires uninstallation and reinstallation of Docker for Mac), it would be great to know if this fixes the problem for you.

**Comment by goneflyin** [comment] 2016-09-29 14:49
Thanks, I'll definitely try that. Installing a large number of ruby gems does, by definition, include a huge number of files being written. Also worth noting, this is being done across volumes (we use a data volume to keep the gems persisted across container rebuilds). 

I'll keep my fingers crossed that we get through it using the new beta. If not, I'll definitely see about creating a stripped down project that just does the gem loading and see if I can trip the failure with a reproducible case.

**Comment by samoht** [comment] 2016-10-14 13:17
Detected symptom of problem 'auplink-segfault' in 39712634-BCC7-4878-9DE1-1735D5EC66BE/20160920-104451.

You hit an issue with the AUFS storage driver that we shipped in previous versions of Docker for Mac. You should upgrade to the latest version of the product which fixes this defect. Thanks!

May be related to docker/for-mac#7

The following log matches:
```
Sep 15 17:22:11 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:11 +0000 UTC kern.info kernel: docker0: port 1(veth9c7137f) entered disabled state
Sep 15 17:22:11 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:11 +0000 UTC kern.info kernel: device veth9c7137f left promiscuous mode
Sep 15 17:22:11 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:11 +0000 UTC kern.info kernel: docker0: port 1(veth9c7137f) entered disabled state
Sep 15 17:22:11 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:11 +0000 UTC kern.info kernel: auplink[2089]: segfault at 7fffc5992cc8 ip 000000000043d049 sp 00007fffc5992cd0 error 6 in auplink[400000+ca000]
Sep 15 17:22:12 spfister Docker[com.docker.driver.amd64-linux][12927] <Warning>: VM: 2016-09-15 22:22:12 +0000 UTC kern.warn kernel: aufs au_plink_put:422:dockerd[1778]: pseudo-link is not flushed
Sep 15 17:22:12 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:12 +0000 UTC kern.info kernel: auplink[2104]: segfault at 7fff30871328 ip 000000000043d049 sp 00007fff30871330 error 6 in auplink[400000+ca000]
Sep 15 17:22:12 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:12 +0000 UTC kern.info kernel: device vethe2131ae entered promiscuous mode
Sep 15 17:22:12 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:12 +0000 UTC kern.info kernel: IPv6: ADDRCONF(NETDEV_UP): vethe2131ae: link is not ready
Sep 15 17:22:12 spfister Docker[com.docker.driver.amd64-linux][12927] <Notice>: VM: 2016-09-15 22:22:12 +0000 UTC kern.info kernel: docker0: port 1(vethe2131ae) entered forwarding state
```

**Closed** 2016-10-23 17:30 UTC
Labels: osx/10.11.x, status/0-triage, version/1.12.1
