### ISSUE TITLE
No route to host trying to access nexus repo

### ISSUE THREAD

**Issue by cheijken** [docker/for-mac#649] opened 2016-09-16 07:40 UTC
### Expected behavior
I want to login to nexus repo to push an image
*docker login nexus.xxxyyyzzz.se:18078*

### Actual behavior
The docker daemon replies no route to host
*Error response from daemon: Get https://nexus.xxxyyyzzz.se:18078/v1/users/: dial tcp x.y.z.a:18078: getsockopt: no route to host*

### Information

ID: 3369B5EA-9BD5-44BC-B21A-FF527512D2C7
OSX 10.10.5 (14F1912)

Obviously i have removed the correct IP and host information.  

I get the same behaviour when I try to push an image.
 
When I run curl from the same command line I have no problem accessing the host and port on the nexus server.

curl -v https://nexus.xxxyyyzz.se:18078/v1/users/
*   Trying x.y.z.a...
* Connected to nexus.xxxyyyzzz.se (x.y.z.a) port 18078 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.xxxyyyzzz.se
* Server certificate: DigiCert SHA2 Secure Server CA
> GET /v1/users/ HTTP/1.1
> Host: nexus.xxxyyyzzz.se:18078
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 16 Sep 2016 07:18:41 GMT
< Server: Nexus/3.0.0-03 (OSS)
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Content-Length: 0
< 
* Connection #0 to host nexus.xxxyyyzzz.se left intact

### Steps to reproduce the behavior

Don't expect this to be that reproducible. Sorry.
The same command worked a week ago. Don't know that changed.
I would suspect something with xhyve and routing.

**Comment by cheijken** [comment] 2016-09-20 06:31
Workaround:
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
And restart docker.

**Comment by dsheets** [comment] 2016-09-26 18:57
I'm glad this is working for you now. It sounds like quite an odd error -- perhaps it was caused by disk image corruption that was fixed with your qcow2 reset? If you encounter this bug again, please feel free to re-open this issue. Thanks for using Docker for Mac!

**Closed by dsheets** 2016-09-26 18:57 UTC
Labels: osx/10.10.x, status/0-triage, version/beta26

**Comment by DejaAugustine** [comment] 2017-06-06 14:55
This issue is happening for me on a regular basis. Roughly once per week. Is there any new insight into what is causing this?

```
Docker
Community Edition

Version 17.03.1-ce-mac12 (17661)
Channel: stable
d1db12684b
```
