### ISSUE TITLE
Sooooo slow...

### ISSUE THREAD

**Issue by raptor235** [docker/for-mac#1018] opened 2016-12-06 19:08 UTC
Hey guys,

This is not really a bug but just trying to gain some understand of what's going on... I've been running docker-machine-nfs for a while now... tried to switch to docker for mac a few times but I just can't stomach the slow speed.... how can they push that product so hard when it's so bad at performance... doesn't anyone else have the same issues?

For example I'm running the same site, same db, same codebase... on a new mbp 2016 that I just installed and this is the results of a WordPress backend...

Docker for mac (16s load time)
http://i.imgur.com/EyV50vO.png

Docker toolbox (6s load time)
http://i.imgur.com/fKGmhgD.png

Docker toolbox NSF mounted (https://github.com/adlogix/docker-machine-nfs) (2s load time)
http://i.imgur.com/lk0LhNL.png

Horrible... anyone else experiencing the same thing?

Saying that is docker-machine-nfs something that will be made available for docker for mac? I'm really hoping they don't EOL docker toolbox anytime soon.

**Comment by Luthien-in-edhil** [comment] 2016-12-07 11:01
Not sure if it's a bug but it's sure bugging the hell out of me. 

We switched to using Docker for our development environment sometime ago. The environment consists of Neo4J, Postgres, Tomcat & Apache - all dockerised. One of my colleagues is running Docker on Linux, while I'm using Mac OS (Sierra - 10.12) with the latest Docker beta _1.13.0-rc2-beta31 (14387)_.

For him, a docker restart for Tomcat takes ~19 seconds while I have to wait a whopping 205 seconds. First I thought that it was maybe my machine, a mid-2011 iMac (2.5 GHz i5 / 16 GB) because it still had a conventional disk. But I upgraded it to use an SSD and while the machine is now overall about 5 times as fast, docker restart Tomcat still takes 205 - 230 seconds. 

I would expect maybe to take twice as long because he has a newer machine, but surely not more than 10 times as long. 

In fact, this makes debugging a lot harder for me than before we used Docker, if I have to wait for almost four minutes after every source file edit before I can run it. 

That's 'progress' for you - I don't think that I even had to wait this long back in, what was it, 1998 :(

**Comment by raptor235** [comment] 2016-12-07 14:57
Startup problems are different... I've seen those issues before with internal hosts files not being setup properly.

The issues I'm describing are on every page load... it's just a slow as hell and seems to be because of how volumes are being mounted.

**Comment by Vanuan** [comment] 2016-12-07 18:26
Likely the duplicate of #77

**Comment by TehesFR** [comment] 2016-12-08 09:27
@raptor235 as mentioned by @Vanuan you can see in #77 that you are definitely not alone facing this issue.

So far, the best solution that I've tested on Mac is https://github.com/codekitchen/dinghy with xhyve provider.

Lately, I've tried Docker for Mac, Dinghy with virtualbox provier, and Dinghy with xhyve provider.
With each one, I've created a docker container with a shared volume, and executed this command inside the container:

    dd if=/dev/zero of=testfile bs=20480 count=100000

- Speed results with Docker for Mac: 29.6 MB/s
- Speed results with Dinghy and Virtualbox: 49.9 MB/s
- Speed results with Dinghy and Xhyve: 85.2 MB/s

Maybe it could be interesting if you can test Dinghy with Xhyve and see if your page load time is better.

**Comment by rogaha** [comment] 2016-12-09 10:52
closing this in favor of #77. @raptor235 please use that `issue` for any further discussions. thanks!

**Closed by rogaha** 2016-12-09 10:52 UTC
Labels: status/0-triage
