### ISSUE TITLE
Docker app not runnning with error message "communication with networking components failed"

### ISSUE THREAD

**Issue by xbax486** [docker/for-mac#1364] opened 2017-03-01 22:17 UTC
![screen shot 2017-03-02 at 9 15 57 am](https://cloud.githubusercontent.com/assets/12993446/23483947/06beb1aa-ff29-11e6-8bbd-7cc16a6dd97d.png)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rogaha** [comment] 2017-03-02 12:18
@xbax486 can you please click on  `Diagnose & Feedback` and copy/paste the diagnose ID here? It will help us to find the root-cause of that issue.

**Comment by xbax486** [comment] 2017-03-02 22:36
Diagnostic ID: 31D8991A-0FF1-4752-8E84-511C3387236A

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/31D8991A-0FF1-4752-8E84-511C3387236A/20170303-093530.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/andy.ba/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/andy.ba/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/andy.ba/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy.ba/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/andy.ba/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy.ba/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by rogaha** [comment] 2017-03-03 16:50
@xbax486 can you try this? 

```
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac
```

If it doesn't work, is it possible to re-install it from scratch?

**Comment by MagnusS** [comment] 2017-03-08 16:38
It looks like this is a duplicate of https://github.com/docker/for-mac/issues/1373, so closing this issue.

**Closed by MagnusS** 2017-03-08 16:38 UTC
Labels: status/0-more-info-needed, status/0-triage
