### ISSUE TITLE
docker push doesn't implement https proxy properly

### ISSUE THREAD

**Issue by dlfoo** [docker/for-mac#6162] opened 2022-02-08 14:11 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 

### Expected behavior

docker push registry.example.com/myimage 
<-success->

### Actual behavior

docker push registry.example.com/myimage                                    
Using default tag: latest
The push refers to repository [registry.example.com/myimage]
Get "https://registry.example.com/v2/": dial tcp: lookup registry.example.com on 8.8.8.8:53: no such host

### Information

Basically docker desktop is trying to resolve the repository name instead of just connecting to the proxy and forwarding on the request down the TCP connection.  See rfc7231 Notably *host name* not ip.

https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6

```
A client sending a CONNECT request MUST send the authority form of
   request-target (rfc7230#section-5.3); i.e., the request-target
   consists of only the host name and port number of the tunnel
   destination, separated by a colon.  For example,

     CONNECT server.example.com:80 HTTP/1.1
     Host: server.example.com:80
```  

Below are two captures from wireshark, one from docker with a static dns entry in /etc/hosts and the other with curl 

DNS: registry.example.com == 10.0.0.1

#### [BAD]  docker push resolving registry name and sending static ip instead of registry name

```sh
docker push registry.example.com/myimage

CONNECT 10.0.0.1:443 HTTP/1.1
host: 10.0.0.1:443
user-agent: ocaml-cohttp/2.1.2

HTTP/1.0 200 Connection established
Proxy-agent: proxy/1.34
```

#### [GOOD] curl sending registry name not static ip.

```sh
https_proxy=192.168.0.2:8080 curl https://registry.example.com/v2/

CONNECT registry.example.com:443 HTTP/1.1
Host: registry.example.com:443
User-Agent: curl/7.77.0
Proxy-Connection: Keep-Alive

HTTP/1.0 200 Connection established
Proxy-agent: proxy/1.34
```

More:
  - macOS Version: 12.2 Monterey
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.4.2 (73305)

### Steps to reproduce the behavior
1. Preferences > Resources > Proxies
2. Add "192.168.0.2:8080" to HTTPS field.
3. Apply and restart.

**Comment by dolbyjoab** [comment] 2022-02-08 20:03
Same error here

**Comment by thaJeztah** [comment] 2022-02-10 12:24
Looks like there's a ticket in the Docker Desktop for Mac issue tracker as well (which also has some links to test-builds); https://github.com/docker/for-mac/issues/6152

Let me close this as duplicate of https://github.com/docker/for-mac/issues/6152

**Closed by thaJeztah** 2022-02-10 12:24 UTC
Labels: version/4.4.2
