### ISSUE TITLE
The date of the note or how long has it been out?

### ISSUE THREAD

**Issue by nonopolarity** [docker/for-mac#6434] opened 2022-07-31 05:49 UTC
This is a doc issue.

https://docs.docker.com/desktop/mac/apple-silicon/

> Docker Desktop for Apple silicon
> Estimated reading time: 4 minutes
> 
> Docker Desktop for Mac on Apple silicon is now available as a GA release.

whether it is a 4 minute read or 15 minute read depends on the person, and it is not so important.  What is more important is the date of this note.  Has it been one week?  Has it been 6 months?  Generally users want to know how stable it is.

**Comment by nicks** [comment] 2022-08-01 12:57
thanks for the feedback! Will pass this onto the docs team. This is currently working as intended, so closing this issue.

**Closed by nicks** 2022-08-01 12:57 UTC
