### ISSUE TITLE
Upgraded to 17.03.0-ce-mac1 (15583)now deploying containers to Openstack does not assign floating IP

### ISSUE THREAD

**Issue by dmccullo** [docker/for-mac#1383] opened 2017-03-03 16:27 UTC
The previous version had no issues i ran 
docker-machine create  --openstack-flavor-name s1.medium --openstack-image-id 97527772-e68c-415d-a498-3ca1942788b0 --openstack-nova-network -d openstack March3test
this creates a machine but no Floating IP I have 4 available in my tenant at present.

March3test
Ubuntu 14.04	
10.0.39.6
s1.medium | 4GB RAM | 2 VCPU | 40.0GB Disk

Prior to this release I could deploy instances with docker-Machine and it would grab a floating IP and asking and finish ssh setup and let me docker-machine ssh to it in about 3 minutes now It gets stuck here:

$ docker-machine create  --openstack-flavor-name s1.medium --openstack-image-id 97527772-e68c-415d-a498-3ca1942788b0 --openstack-nova-network -d openstack March3test
Running pre-create checks...
Creating machine...
(March3test) Creating machine...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...

any help would be appreciated!

### Information
Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/0D8AD6CC-418D-4808-B3E7-EE36B25DF659/20170303-112020.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dmccullo** [comment] 2017-03-03 16:51
Arggg a config issue on my part ignore....

**Comment by rogaha** [comment] 2017-03-03 16:52
thanks for the update @dmccullo

**Comment by dmccullo** [comment] 2017-03-03 16:57
One weird thing that might be an issue...  is I used to get errors when variables were not set...
these were not set and the command above still tried to del=ploy the instance.... and actually created it but with just a fixed IP.   something to worry about?

**Comment by dmccullo** [comment] 2017-03-03 18:37
The Variables that were not set were 
# Docker Details required to deply containers

export OS_SECURITY_GROUPS=
        echo Security Groups saved
#DAIR Specific details that are required to configure your API access
        echo Dair Specific details being saved!
export OS_NETWORK_NAME=
export OS_FLOATINGIP_POOL=
        echo all Network Variables defined
export OS_SSH_USER=
        echo SSH User defined
echo all DAIR specific details saved

this is part of a environment Variable script I run to use docker with openstack...  with non of these set and the command above run I received no variables not set errors.

**Comment by MagnusS** [comment] 2017-03-09 16:58
Thanks for the report @dmccullo. This seems to be related to docker-machine or openstack, not Docker for Mac? I'm closing this ticket for now as the original issue seems to be resolved. If you still have problems with Docker for Mac please open a new issue with a new diagnostic upload and steps to reproduce the problem if possible. Thanks!

**Closed by MagnusS** 2017-03-09 16:58 UTC
Labels: osx/10.11.x, status/0-triage, version/17.03.0-ce-mac1
