### ISSUE TITLE
Docker Apple Sillicon Preview 7 unable to pull image

### ISSUE THREAD

**Issue by cyaoz94** [docker/for-mac#5255] opened 2021-01-15 05:30 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8A695FEF-FBE0-460C-9E6A-E5CD375B7FE3/20210115051747

### Expected behavior
Docker images can be pulled from docker hub

### Actual behavior
Connection refused
```
docker image pull mariadb:10.4
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.7:47694->192.168.64.1:53: read: connection refused
```

### Information
  - macOS Version: Big Sur Version 11.1

### Diagnostic logs

```
Docker for Mac: Docker version 20.10.1, build 831ebeae96

```

### Steps to reproduce the behavior

  1. Install docker desktop
  2. Attempt to pull image

**Comment by cyaoz94** [comment] 2021-01-15 06:13
After exploring issues outside of the area/m1 label. I found out that this is the same issue as #5186 
After restarting the dnsmasq services everything was working. :D

**Comment by stephen-turner** [comment] 2021-01-15 08:35
OK, I'll close this one as a dupe of #5186.

**Closed by stephen-turner** 2021-01-15 08:35 UTC
Labels: version/0.0.0
