### ISSUE TITLE
Kitematic on Mac OSX issue

### ISSUE THREAD

**Issue by fwlab** [docker/for-mac#1888] opened 2017-07-20 05:36 UTC
### Expected behavior
Kitematic starts normally

### Actual behavior
**Kitematic** worked for a few days previously.
An error screen is presented in kitematic, resetting, as suggested did not work.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/2F4212BE-8C8C-445D-BA68-6D9C2E9C4D00/20170720-073010.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Use kitematic on a Mac Sierra, perform OS upgrades, etc.
  2. Keep using kitematic 
<img width="1081" alt="schermata 2017-07-20 alle 07 33 36" src="https://user-images.githubusercontent.com/2357086/28402019-cd55a6b8-6d1d-11e7-945a-4181df35b3a5.png">

**Comment by alihalabyah** [comment] 2018-01-21 07:21
Any updates on this one?

**Comment by LoreenRH** [comment] 2018-02-07 15:19
Unfortunately I'm unable to reproduce this, but you can follow [these steps](https://github.com/docker/kitematic/issues/3514#issuecomment-359589533). If your problem persists I believe the [docker/kitematic](https://github.com/docker/kitematic/issues) repository is a better place for this. 

I'll be closing this issue :)

**Closed by LoreenRH** 2018-02-07 15:19 UTC
Labels: osx/10.12.x, status/0-triage, version/17.06.0-ce-mac19
