### ISSUE TITLE
insecure-registries doesn't work on Big Sur / Mac M1

### ISSUE THREAD

**Issue by mnett0** [docker/for-mac#5522] opened 2021-03-30 08:30 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F68744DD-1018-4D85-A228-A5B8D44D1E5B/20210330071851

### Expected behavior

I want to send my image created with buildx with the command : 

`$ docker buildx build --platform linux/arm/v7 -t 192.168.1.23:5000/carboard-api:latest --push .`

On my local registry in HTTP

### Actual behavior

To send the image to my local registry in http I added the configuration:

```
{
  "features": {
    "buildkit": true
  },
  "experimental": false,
  "insecure-registries": [
    "192.168.1.23:5000"
  ]
}
```

When I run the build with buildx I always have the error:

`error: failed to solve: rpc error: code = Unknown desc = failed to do request: Head https://192.168.1.23:5000/v2/carboard-api/blobs/sha256:0979495883c873201ed9cd5af778e9bdd1d0ddfb45da8502125c0c7df32f38fy: http: server gave HTTP response to HTTPS client`

Unable to send the image to the registry in HTTP.

### Information

  - Hardware : MacBook Pro M1
  - macOS Version: Big Sur 11.2.3
  - Docker Desktop Version: 3.3.0 RC 2

On my old MacBook on macOS Mojave with the 'same configuration' everything works fine. 

### Steps to reproduce the behavior

  1. Install a registry on your local network, on another machine : [Tutorial](https://docs.docker.com/registry/deploying/)
  2. On the build machine (on macOS Big Sur), add the configuration in Docker --> Preferences --> Docker Engine : 
```
{
  "features": {
    "buildkit": true
  },
  "experimental": false,
  "insecure-registries": [
    "192.168.1.23:5000"
  ]
}
```
Apply and restart docker
3. Create and send any docker image to the registry created above with the command:
`docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t IP_OF_YOUR_LOCAL_REGISTRY:5000/HelloWorld --push .`
Don't forget to setup the IP of your local registry.
4. Observe the result

**Comment by stephen-turner** [comment] 2021-03-30 13:30
I think this is a dupe of #5520.

**Closed by stephen-turner** 2021-03-30 13:30 UTC
Labels: version/3.3.0

**Comment by djs55** [comment] 2021-04-06 19:01
@mnett0 thanks for your report. I think the core problem is that the new `buildkit` builder is configured differently to the old builder which was part of the Docker engine. To enable insecure registry support for `buildkit` you need to create a config file, for example: (from https://github.com/docker/buildx/issues/534#issuecomment-774587577 )

```
% cat config.toml                                                                                                                       
debug = true
# root is where all buildkit state is stored.
root = "/var/lib/buildkit"
# insecure-entitlements allows insecure entitlements, disabled by default.
insecure-entitlements = [ "network.host", "security.insecure"]

[registry."192.168.1.148:5000"]
  http = true
  insecure = true
```
(where `192.168.1.148:5000` should be replaced with your insecure registry IP)

Next, create and use a `buildkit` instance:
```
docker buildx create --config config.toml --use   
```
This replaces the default instance which was automatically created the first time you used `buildkit`.

Now the push should work:
```
 % docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t 192.168.1.148:5000/hello-world --push  .
[+] Building 1.8s (10/10) FINISHED                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                         0.1s
 => => transferring dockerfile: 31B                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                                              0.0s
 => [linux/amd64 internal] load metadata for docker.io/library/hello-world:latest                                                                                                            1.5s
 => [linux/arm/v7 internal] load metadata for docker.io/library/hello-world:latest                                                                                                           1.5s
 => [linux/arm64 internal] load metadata for docker.io/library/hello-world:latest                                                                                                            1.4s
 => [auth] library/hello-world:pull token for registry-1.docker.io                                                                                                                           0.0s
 => CACHED [linux/arm/v7 1/1] FROM docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                     0.0s
 => => resolve docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                                         0.0s
 => [linux/arm64 1/1] FROM docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                             0.0s
 => => resolve docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                                         0.0s
 => CACHED [linux/amd64 1/1] FROM docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                      0.0s
 => => resolve docker.io/library/hello-world@sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24                                                                         0.0s
 => exporting to image                                                                                                                                                                       0.1s
 => => exporting layers                                                                                                                                                                      0.0s
 => => exporting manifest sha256:927756ec6739884299f1d500f30354745b75974374551305abe81a11fee5d92e                                                                                            0.0s
 => => exporting config sha256:0134c289bb5d1a1493eb0f490221876a7ec39abc055e407b0b96cb650a2ed42d                                                                                              0.0s
 => => exporting manifest sha256:bcf34d063e79f713162b24ecbe8174063f3b2782bbf3e880b4302e661af19669                                                                                            0.0s
 => => exporting config sha256:e42fdd67b6ec1014eb7c04d3d680cfcd8fac586877d5384d5d23aa794c1bb324                                                                                              0.0s
 => => exporting manifest sha256:8e3db1495d7a9841a5d726cc51edc9af8d59dc5d06674bb7b58d2d3fe79f7d55                                                                                            0.0s
 => => exporting config sha256:5f812ca0fddc8877ef454735907ee4a70a75f22341c02677068c0daab50da69d                                                                                              0.0s
 => => exporting manifest list sha256:d26dfd2ebf2554386e53dab977799dcf26c41bf19d1992b86f26a89b60be0792                                                                                       0.0s
 => => pushing layers                                                                                                                                                                        0.0s
 => => pushing manifest for 192.168.1.148:5000/hello-world:latest                                                                                                                            0.1s
```
I hope that helps!
