### ISSUE TITLE
Memory Leak on M1 Macs

### ISSUE THREAD

**Issue by monney** [docker/for-mac#5204] opened 2020-12-31 03:36 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics

### Expected behavior
Memory should be correctly freed
### Actual behavior
Memory is not correctly freed
### Information
When running dockers on M1, memory is not properly freed, even when quitting the corresponding docker container. My actual scripts keep encountering out of memory errors which they don't do on my intel Mac, so this doesn't seem to be a tracking issue.

  - macOS Version: Big Sur 11.1
```
Docker for Mac: Docker version 20.10.1, build 831ebeae96

```

### Steps to reproduce the behavior
use the official python 3.8 container under x86_64 emulation or on arm chip directly
run the following minimal example:
```python
pip install numpy
python
import numpy as np
l = []
for _ in range(1000):
    l+=[np.random.rand(512,512)]
del l
```
In activity monitor memory allocated by docker will never go away until quitting docker. htop within the container may or may not correctly reflect the memory usage, it is not consistent.

a more complex example for my use case using ray (x86_64 emulation) continually builds up memory when scheduling arbitrary tasks even if objects are no longer referenced and will encounter an out of memory error.

**Comment by czhDavid** [comment] 2021-01-06 09:20
Are you sure this is a bug? Resources are not per container but are allocated at all times by docker. At least in my case with my macbook pro and intel i7 procesor. So same behaviour as yours with intel based mac. You can change how much RAM the docker has available in preferences -> resources.

**Comment by monney** [comment] 2021-01-06 15:43
@czhDavid I'm fairly certain there is a bug. I think you're correct about this behavior, meaning I need a new minimal example. I'm working to isolate it better since the minimal example here doesn't really "replicate" it.

Essentially I'm performing many tasks in parallel. First I was using ray under x86_64 emulation and it kept crashing due to out of memory. This behavior under even smaller resource allocation to docker, for the same task does not happen on my intel Mac. I then tried rewriting the task using multiprocessing and running in arm directly. I encounter the same behavior. 

Currently trying to isolate the issue a bit better, and come up with a better minimal example.

**Comment by monney** [comment] 2021-01-08 02:55
Closing till I can isolate the issue better

**Comment by plamenh** [comment] 2021-01-26 07:55
I think I have a similar issue. My phpfpm container keeps hitting out of memory errors despite allocating huge amounts of memory to it.

**Comment by luancschmitz** [comment] 2021-02-05 19:06
I have the same problem.
While on an Intel mac I have a docker running perfectly with 5gb of memory and 2gb of swap (Preferences -> Resources -> Advanced). The mac with m1 is experiencing an out of memory error with 5GB of memory and 2.5GB of swap.

**Comment by megafinz** [comment] 2021-02-08 09:03
I'm not sure if this is related, but I noticed that after some time of docker running on my M1 MBA other apps start crashing, and dotnet builds start failing with various errors like too many open files. Problems go away after I close the docker app.

**Comment by plamenh** [comment] 2021-02-08 09:58
@monney could you reopen the issue? It looks like this is quite widespread.

**Comment by monney** [comment] 2021-02-08 12:55
hopefully someone can come up with a minimal example

**Comment by luancschmitz** [comment] 2021-02-08 13:15
on some Magento 2 pages (PHP framework for ecommerce), mainly in the admin, this error message appears:

Fatal error: Out of memory (allocated 22396928) (tried to allocate 7864352 bytes) in /var/www/html/vendor/colinmollenhour/credis/Client.php on line 1457

Something that doesn't happen on mac with Intel with the same settings set in Preferences -> Resources. 

print settings: https://prnt.sc/ypmsnf

print error in Site: https://prnt.sc/ypmv37

print error in some terminals commands(composer update, bin/magento setup:di:compile, and others): https://prnt.sc/ypnkcm

command "free -h"in docker container: https://prnt.sc/ypnopk

**Comment by stephen-turner** [comment] 2021-02-08 16:39
Interesting. We've seen something similar when running amd64 containers under emulation. Is that the situation people are seeing this in, or are you seeing it with pure arm64 containers too?

**Comment by luancschmitz** [comment] 2021-02-08 16:54
This occurs with pure images. I am using the following images:
"nginx:1.18-alpine"
"php:7.4-fpm-buster"
"mariadb:10.4.17"
"redis:5.0-alpine"
"rabbitmq:3.7-management-alpine"
"elasticsearch:7.10.1"

All the images I checked have support for m1 ARM.
But I believe that this memory error is more related to the php image.

**Comment by plamenh** [comment] 2021-02-09 14:29
@luancschmitz I have the exact same issue with m2.4 image (/var/www/html/vendor/colinmollenhour/credis/Client.php on line 1457)

**Comment by luancschmitz** [comment] 2021-02-09 14:34
@plamenh this seems to be something related to the docker that is not able to allocate memory, or free up used memory. But I'm not sure what the real mistake is.

**Comment by balintant** [comment] 2021-02-10 08:34
We are using a custom (php) image, based on centos (same as on our servers). On m1 - with `--platform linux/amd64` -, it fails when trying to allocate more than ~8-12MB of memory, even when there is 4+GiB of free memory (double-checked on container level with `free -g` too, php limits are OK, and we are not experiencing this with the same image on linux/for-windows/intel-for-mac).

@luancschmitz I think it's "not able to allocate memory", as in my example it has the free memory already.

**Comment by luancschmitz** [comment] 2021-02-10 16:13
@balintant @plamenh @stephen-turner 

I was using the following docker for magento 2:
https://github.com/markshust/docker-magento

checking the project's custom Dockerfiles, I verified that some x86 libraries were being installed. Possibly even the base images being ARM, the docker emulated these libs in Rosseta. The libs were:
- mkcert-v1.4.1-linux-amd64 (https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/)
- ioncube_loaders_lin_x86-64 (https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz)
- mhsendmail_linux_amd64 (https://github.com/mailhog/mhsendmail/releases/download/v0.2.0)

Each of them has its version for arm.

After creating a custom Dockerfile on my machine and exchanging the x64 libs for the ARM libs, the "out of memory" problem has not yet happened.

So I believe that as mentioned by @stephen-turner  this error occurs if it is necessary to use Rosseta 2 to emulate something x86.

**Comment by plamenh** [comment] 2021-02-16 05:42
@luancschmitz can you share your docker-compose.yaml?

**Comment by luancschmitz** [comment] 2021-02-16 14:40
Hi @plamenh . 
Here is the fork I made from the original project:
https://github.com/luancschmitz/docker-magento-mac-m1/blob/master/compose/docker-compose.yml

Look especially in the Dockerfile of nginx and PHP, which had libs in x86, which I already switched to libs in ARM. 
With that, the "out of memory" error stopped happening.

**Comment by balintant** [comment] 2021-02-17 08:06
I just updated to the latest version of Docker Tech Preview (released on February 11, 2021) and the issue seems to be resolved (still using platform linux/amd64).

@luancschmitz, Can you confirm if the issue is still present on your side?

_(note: there's no auto-update, you have to download it from the website)_

cc: @plamenh @stephen-turner

**Comment by luancschmitz** [comment] 2021-02-17 13:30
Hi @balintant 

as soon as possible I will do the test. I already have the latest version of the tech preview released. (Updated Yesterday)
The version of the Dockerfile I am using is no longer occurring, as I switched all x86 dependencies to ARM dependencies. But I will do the test with the original Dockerfile (with the x86 dependencies) and I will inform you as soon as I finish the tests.

**Comment by plamenh** [comment] 2021-03-01 14:32
@balintant, happy to confirm latest tech preview works fine (Feb 12).

**Comment by balintant** [comment] 2021-03-01 17:36
@monney the issue seems to be resolved. I think you can close it now.

**Comment by plamenh** [comment] 2021-03-20 10:07
Just downloaded latest Docker Desktop for Mac (3.3.0) and the issue is back.

**Comment by mtiller** [comment] 2021-03-20 13:26
I'm running `3.3.0 (63029)` and I'm getting out of memory issues unrelated to "magneto 2".  I randomly get errors that look like this:

```
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Out of Memory! Heap size: 136 MiB. Returning NULL!
```

Adding more memory doesn't help and these processes are *not* running out of memory (they don't use very much).  Furthermore, I suspect this is the same issue as what is being reported [here](https://github.com/NixOS/nix/issues/4485).  The issue in that ticket seems to be reliably reproducible whereas mine is intermittent.

There definitely seems to be some issue with memory allocation on M1 Macs with `3.3.0 (62029)`.

**Comment by plamenh** [comment] 2021-03-20 13:43
@mtiller this release appears to have had it sorted out: 

Docker Tech Preview (February 11, 2021)

If you can get your hands on it, maybe it will work for you. Otherwise, I can suggest you try building the php-fpm container from @luancschmitz's repo fork.

**Comment by mtiller** [comment] 2021-03-21 16:16
@plamenh I hate to have to downgrade because I had other issues with some of the previous releases.  I could give it a try though.  Too bad this issue came back and worse that this issue is marked as closed.  I have to wonder if this is actually on anybody's radar.

The php-fpm container doesn't help me, I'm not using PHP.  I just go the same error in another context so I was just lending my voice that this isn't just an issue with PHP related images, it is a general issue.

**Comment by plamenh** [comment] 2021-03-22 10:38
In this case you should try to find arm compatible images.

**Comment by balintant** [comment] 2021-03-22 19:13
That's often not possible. There's an issue with `--platform linux/amd64` and Qemu on a basic level (easily replicated with basically any environment), that is expected to work. It's either Docker for Mac not supporting non-arm images or resolving these issues.

@monney can we reopen the issue? It seems the current RC has it again.

**Comment by monney** [comment] 2021-03-23 00:50
@balintant my original container also used an arm emulated one

**Comment by stephen-turner** [comment] 2021-03-23 10:54
> There's an issue with `--platform linux/amd64` and Qemu on a basic level that is expected to work.

This expectation is incorrect. There are lots of examples of containers that qemu can't run successfully, and it is out of our control to fix it. We strongly recommend running only arm64 containers, and encouraging container authors to provide arm64 images, and regarding the emulation as a temporary workaround only.

**Comment by graemelambert** [comment] 2021-03-24 17:22
@luancschmitz thank you for your fork, this worked perfectly for me on a 2020 MacBook Air with the M1 chip

**Comment by luancschmitz** [comment] 2021-03-24 20:21
Hi @mtiller!
What containers are you trying to run on the docker?
if you can share docker-composer.yml.
Well maybe you can find the arm versions of the containers, and so possibly the error will go away.

**Comment by antoniocarboni** [comment] 2021-04-02 14:57
Tested with RC3 on Mac Mini 2020 M1.
Same issue. php-fpm and elasticsearch containers have problems with memory usage.

**Comment by ocean** [comment] 2021-04-07 07:12
I'm hitting this same issue with Composer tasks running out of memory when running. However, this is happening for me when I'm trying to build multi-architecture images (composer runs in some of the images during the build stage), and so this is quite a blocker for me. I understand that for running on my machine I should be building and running `arm64` images, but I'm also trying to build and push multi-architecture manifests of these images to Docker Hub so others can use them, and this is preventing me from doing that.

I'll try setting up Docker Buildx in a GitHub Workflow and building my multi-arch upstream images in there to see if the reverse emulation mode (building `arm64` images on an Ubuntu `amd64` VM) handles Composer better.

**Comment by ocean** [comment] 2021-04-08 02:27
Sorry that sounds whiny, it had been a long day of broken image builds when I wrote that previous comment.

Obviously I understand this is not the Docker Team's problem, as it's something in QEMU that is doing the memory allocation.

Thanks @stephen-turner and other Docker team members for your patient comments 👍

**Comment by balintant** [comment] 2021-04-08 17:02
https://github.com/docker/for-mac/issues/5204#issuecomment-776536512
Same issue on CentOS 8's latest **ARM** image on the current RC of Docker. (Works fine with Docker Tech Preview 7 with both archs.)

**Comment by garyrojas** [comment] 2021-04-09 17:33
I have the same issue for Mac M1.
Getting error 
`
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 102944768) (tried to allocate 7864352 bytes) in vendor/colinmollenhour/credis/Client.php on line 1457
`

For some process using this configuration:
https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml

**Comment by garyrojas** [comment] 2021-04-09 17:37
I have the same issue for Mac M1.
Getting error

```
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 102944768) (tried to allocate 7864352 bytes) in vendor/colinmollenhour/credis/Client.php on line 1457
```

For some processes using this configuration:
https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml

**Comment by luancschmitz** [comment] 2021-04-09 17:44
HI @garyrojas,

try using the fork that I made from the mark docker. The link is here:

https://github.com/luancschmitz/docker-magento-mac-m1

I replaced all x86 libraries with arm libraries.

**Comment by garyrojas** [comment] 2021-04-09 19:01
Hi @luancschmitz,

You're a lifesaver, works perfectly fine :)

Many thanks

**Comment by gianniguida** [comment] 2021-04-12 15:01
Same problem with my Mac M1. 

```
flarum-playground-php_1    |  WARNING: [pool flarum] child 155 said into stderr: "mmap() failed: [12] Out of memory"
flarum-playground-php_1    |  WARNING: [pool flarum] child 155 said into stderr: "mmap() failed: [12] Out of memory"
flarum-playground-php_1    |  WARNING: [pool flarum] child 155 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Out of memory (allocated 48865280) (tried to allocate 4822920 bytes) in /opt/flarum/vendor/wikimedia/less.php/lib/Less/Parser.php on line 2658"
flarum-playground-php_1    |  172.19.0.3 -  12/Apr/2021:14:20:13 +0000 "GET /index.php" 500
flarum-playground-nginx_1  |  [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Out of memory (allocated 48865280) (tried to allocate 4822920 bytes) in /opt/flarum/vendor/wikimedia/less.php/lib/Less/Parser.php on line 2658" while reading response header from upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost:8888"
```

Already tried to add more memory. Docker `3.3.0 (62632)`

Anyone knows of a possible workaround? If you need more information, don't hesitate to ask.

Any help is very much appreciated. Thanks a lot!

**Comment by stephen-turner** [comment] 2021-04-12 15:09
The workaround is to use only arm64 containers. Running amd64 containers under emulation is "best effort": it may not work, and even when it does it will not be performant.

**Comment by RobertHR** [comment] 2021-04-15 20:47
I am getting a similar error on Docker 3.3.1 (63152) running Apple M1
I am using PHP Laravel application and when I have a lot of migrations I am getting:
```
mmap() failed: [12] Cannot allocate memory
Segmentation fault
```
I would like to mention that this segfault did not happen with the latest Docker preview version.

**Comment by gianniguida** [comment] 2021-04-16 09:05
> The workaround is to use only arm64 containers. Running amd64 containers under emulation is "best effort": it may not work, and even when it does it will not be performant.

@stephen-turner Do you know if this issue is going to be resolved in the near future? or it's probably gonna stay like this for a bit?

**Comment by Eigilak** [comment] 2021-04-16 23:01
i'm currently also experiencing the issue with running out of memory on my m1 when I'm running composer install.

RUN composer install --no-ansi --no-interaction --no-progress  --optimize-autoloader --classmap-authoritative --dev
#38 32.12 
#38 32.12 mmap() failed: [12] Cannot allocate memory

**Comment by knirb** [comment] 2021-04-23 11:28
Having the same with the m1 issue on `RUN composer dump-autoload`

```zsh
#27 9.130 mmap() failed: [12] Out of memory
#27 9.137 Segmentation fault
```
Tried allocating over 10gb of memory to docker and still didn't work.

**Comment by kosmicke** [comment] 2021-04-25 20:33
> i'm currently also experiencing the issue with running out of memory on my m1 when I'm running composer install.
> 
> RUN composer install --no-ansi --no-interaction --no-progress --optimize-autoloader --classmap-authoritative --dev
> #38 32.12
> #38 32.12 mmap() failed: [12] Cannot allocate memory

Im experience the exactly same issue when I run composer install. After download all the dependencies, when it starts to generate autoload files I receive the same error message:

<img width="1232" alt="Screen Shot 2021-04-25 at 17 31 58" src="https://user-images.githubusercontent.com/32934713/116008681-25cd2b80-a5ec-11eb-9488-fef4296fa778.png">

These are my settings:
<img width="1232" alt="Screen Shot 2021-04-25 at 17 32 51" src="https://user-images.githubusercontent.com/32934713/116008710-45fcea80-a5ec-11eb-8ea2-c497e9b51034.png">

**Comment by mariusmarais** [comment] 2021-04-26 08:10
Hi @kosmicke, you can try to restart Docker and re-run your build. Hopefully some layers are cached and you get a little bit further every time.

Not ideal, but working for me on a complicated NodeJS build.

**Comment by Eigilak** [comment] 2021-04-26 08:13
@mariusmarais i have run my build 10 times in a row and it came out with the same result :( 
Have you done anything else that made the build come trough @mariusmarais ?

**Comment by czhDavid** [comment] 2021-04-26 08:14
Are we sure that this is memory leak error? If docker container runs out of memory it should end with OOM error https://docs.docker.com/config/containers/resource_constraints/ . Which is none of the above reports. 
All of the issues reported here seems to be problems with app configuration (For example setting memory setting for PHP is quite tricky)

**Comment by mariusmarais** [comment] 2021-04-26 08:26
@Eigilak Did you restart Docker itself from the menubar between runs? That worked for me.

**Comment by stephen-turner** [comment] 2021-04-26 08:33
Everything I've seen on this thread suggests that the problem is to do with trying to run amd64 containers on an M1, which is always going to be best effort only. Has anyone seen this symptom with ARM-based containers?

**Comment by mariusmarais** [comment] 2021-04-26 09:03
@czhDavid The exact same configuration works 100% of the time on an Intel Mac for me, running Node.  Running a native arm64 base image, Docker is actually working a lot harder since almost everything needs to be recompiled in my case, but it also works 100% of the time.  Only the amd64 base image on M1 is running into memory allocation errors, some of the time.

I do agree that we're not necessarily seeing an "Out of memory" error, as in there isn't any more available, but rather "Cannot allocate memory", for some other reason related to Qemu. Maybe fragmentation, maybe leak, maybe race condition, maybe everything takes 2x on M1 under Qemu, maybe it works on Tuesdays, IDK.

E.g:
```
#19 58.00
#19 58.00 /build/.pnp.js:30121
#19 58.00   wasmMemory = new WebAssembly.Memory({
#19 58.00                ^
#19 58.00 RangeError: WebAssembly.Memory(): could not allocate memory
#19 58.00     at Object.368 (/build/.pnp.js:30121:16)
#19 58.00     at __webpack_require__ (/build/.pnp.js:34227:41)
#19 58.00     at getLibzipSync (/build/.pnp.js:28020:41)
#19 58.00     at Object.936 (/build/.pnp.js:29694:13)
#19 58.00     at __webpack_require__ (/build/.pnp.js:34227:41)
#19 58.00     at /build/.pnp.js:34267:18
#19 58.00     at /build/.pnp.js:34268:12
#19 58.00     at webpackUniversalModuleDefinition (/build/.pnp.js:23659:20)
#19 58.00     at Object.<anonymous> (/build/.pnp.js:23666:3)
#19 58.00     at Module._compile (internal/modules/cjs/loader.js:1063:30)
```


While app config issues are certainly possible, it seems unlikely that so many different types of apps would exhibit the same errors only now.

@stephen-turner Working for me with native arm64/M1 builds. Should a different issue be logged for emulation?

**Comment by stephen-turner** [comment] 2021-04-26 09:24
> @stephen-turner Working for me with native arm64/M1 builds. Should a different issue be logged for emulation?

No, emulation is out of our control. We specifically call it out in the documentation as best effort only: i.e., we do not regard failures in emulation as a bug.

**Comment by paolomainardi** [comment] 2021-04-26 09:58
same here building a php image: 


```
 > [develop 3/3] RUN mkdir /composer-libs     && mkdir -p /drush/cache     && chmod -R 775 /composer-libs     && chmod -R 775 /drush/cache     && curl -L -o /usr/local/bin/composer https://github.com/composer/composer/releases/download/1.10.13/composer.phar     && chmod +x /usr/local/bin/composer     && composer global require hirak/prestissimo:0.3.10     && composer global require symfony/var-dumper:3.0.3     && echo "PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]$\[\033[0m\] '" >> /etc/profile     && echo "export TERM=xterm" >> /etc/profile     && echo -e "\nauto_prepend_file=/composer-libs/vendor/autoload.php" >> /usr/local/etc/php/conf.d/docker.ini:
#8 0.356   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#8 0.357                                  Dload  Upload   Total   Spent    Left  Speed
100   617  100   617    0     0   1051      0 --:--:-- --:--:-- --:--:--  1069
100 1947k  100 1947k    0     0  1225k      0  0:00:01  0:00:01 --:--:-- 3229k
#8 2.214 Changed current directory to /composer-libs
#8 2.220 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#8 2.788 Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
#8 5.258
#8 5.258 mmap() failed: [12] Out of memory
#8 5.259
#8 5.259 mmap() failed: [12] Out of memory
#8 5.259
#8 5.259 Fatal error: Out of memory (allocated 52330496) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php on line 288
```

The fun fact that it worked in the previous releases, i also tried to enable/disable virtualization framework marked as experimental, but the very same effect.

**Comment by kosmicke** [comment] 2021-04-26 12:16
@mariusmarais I've already cleaned the cache and rebuilt it several times, even purged everything and tried again. It keeps showing the same error. I have two M1 MacBooks, one with 8GB of ram and the other with 16gb, and the error happens in both of them.

Even if I run **COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1  `which composer` composer install** the error keeps happening.

**Comment by kosmicke** [comment] 2021-04-27 14:55
> Everything I've seen on this thread suggests that the problem is to do with trying to run amd64 containers on an M1, which is always going to be best effort only. Has anyone seen this symptom with ARM-based containers?

@stephen-turner I built the images in arm64 and now the problem is gone, no more memory leaks:

<img width="1317" alt="Screen Shot 2021-04-27 at 11 54 51" src="https://user-images.githubusercontent.com/32934713/116262981-61ccd180-a74f-11eb-9844-2ad862899d9e.png">

<img width="1343" alt="Screen Shot 2021-04-27 at 11 49 31" src="https://user-images.githubusercontent.com/32934713/116262871-45309980-a74f-11eb-9cc3-9deecaeef3fb.png">

**Comment by Eigilak** [comment] 2021-04-29 21:47
@kosmicke i'd wish that would solve the problem, but a lot of my packages is only supported by amd64 container

**Comment by paolomainardi** [comment] 2021-04-29 22:21
The problem here is that is started to happen since the first stable release of docker for mac, I built the very same php packages for amd64 with no issues.

**Comment by mariusmarais** [comment] 2021-04-30 05:34
I'm trying to check against the preview versions now, but I can't find the download links. Are the preview versions still available somewhere?

**Comment by Weetbix** [comment] 2021-04-30 09:20
@mariusmarais I had the same issue, I was attempting to roll back to one of the previews that was claimed to work, but couldn't find them anywhere. All the old links on the docker domain are dead, too.

**Comment by stephen-turner** [comment] 2021-04-30 09:58
We removed the previews when we released the actual GA version. They were time-limited anyway.

**Comment by mariusmarais** [comment] 2021-05-03 05:19
@stephen-turner Can you provide the removed links so we can test if this is a regression or not?

Or do you just want to close the ticket as "Unsupported" and move on?

**Comment by kosmicke** [comment] 2021-05-03 14:22
> @kosmicke i'd wish that would solve the problem, but a lot of my packages is only supported by amd64 container

Yes, it's happening with my project too. My back-end container is now working, but my front-end container has some packages that only works in amd64, and when I try to emulate it, it gets really slow.

@paolomainardi Yes. The same project that im trying to make work now, used to work really fine on the preview version of Docker.

**Comment by stephen-turner** [comment] 2021-05-07 08:06
In version 3.3.2, we are launching qemu with an additional argument that may help in some cases. We would be interested to know whether it has solved this problem.

However, note that qemu emulation should only ever be regarded as "best effort". Even when it works it will use more memory and have worse performance. The real solution is to run arm64 containers on M1 hardware.

I'm going to close this ticket now, because there's nothing further that we can do.

**Closed by stephen-turner** 2021-05-07 08:06 UTC
Labels: area/m1

**Comment by Eigilak** [comment] 2021-05-07 11:53
@stephen-turner where can these arguments be found? :)

**Comment by stephen-turner** [comment] 2021-05-07 12:02
Sorry, that was a bit cryptic, wasn't it? It's `-cpu max`. See #5561 for a discussion.

**Comment by richardsondx** [comment] 2021-05-19 00:59
@stephen-turner How can I access Docker Desktop qemu log or backtrace? I think there's a similar issue that breaks ruby/rails bundler.

**Comment by kolyabres** [comment] 2021-05-31 13:11
The same issue on my M1 
`compser udpate`

>mmap() failed: [12] Out of memory

resources:
![image](https://user-images.githubusercontent.com/1358026/120198325-a5bd6580-c22a-11eb-93b4-f677e98e2861.png)
version
![image](https://user-images.githubusercontent.com/1358026/120198426-bb328f80-c22a-11eb-8546-d89518d21cd5.png)

**Comment by laurenz-glueck** [comment] 2021-06-04 09:47
We are having the same "out of memory" issue with running `composer install` in a PHP docker container on a M1 MacBook.

We also tried to run it with `COMPOSER_MEMORY_LIMIT=-1 composer install` but it's still running out of memory.

Has anyone found a solutions for this so far?

**Comment by paolomainardi** [comment] 2021-06-04 09:53
The latest update solved the issues we faced, I don’t remember if I’m using qemu or the native vm framework tho.

**Comment by mariusmarais** [comment] 2021-06-04 10:13
> The latest update solved the issues we faced, I don’t remember if I’m using qemu or the native vm framework tho.

Still have the same issues, even with the latest update. (`yarn` in NodeJS)

Previously I said we could work around it by restarting Docker and carrying on with cached layers, but that doesn't work for all our NodeJS projects.

**Comment by raviolican** [comment] 2021-06-09 11:03
The problem ist that qemu emulates amd64. Which is ressource intenseive. See: https://docs.docker.com/docker-for-mac/apple-silicon/. If you switch the image to arm64 it should fix the error.

**Comment by ryanhefner** [comment] 2021-07-08 09:16
I am running into a similar issue when trying to build images targeted for deployment on `linux/amd64` platforms. If I remove the `--platform` flag, the build completes fine. But, when the `--platform` flag is included, I get the following error:

```
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 34B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                                                               0.8s
 => [internal] load build context                                                                                                                                            0.0s
 => => transferring context: 17.62kB                                                                                                                                         0.0s
 => [builder 1/7] FROM docker.io/library/node:alpine@sha256:b7e2d75ecd585feed57be69cd3dee973e5c498241e64906899b3baa2169fb35a                                                 0.0s
 => CACHED [builder 2/7] WORKDIR /app                                                                                                                                        0.0s
 => CACHED [builder 3/7] COPY ./package*.json ./                                                                                                                             0.0s
 => CACHED [builder 4/7] COPY ./yarn.lock ./                                                                                                                                 0.0s
 => [builder 5/7] RUN yarn install --frozen-lockfile                                                                                                                         8.2s
 => => # #                                                                                                                                                                       
 => => # # Fatal process OOM in CodeRange setup: allocate virtual memory                                                                                                         
 => => # #                                                                                                                                                                       
 => => # qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped  
 ```

**Comment by stephen-turner** [comment] 2021-07-08 09:34
I'm going to lock this issue because we're getting a lot of "me too"s even though the behaviour is expected and documented.

To summarise: Running Intel binaries on Arm hardware uses emulation. It is "best effort" only. It is always less efficient, and it occasionally crashes. We cannot make any further improvements in this area. The solution is to use the correct containers for your CPU architecture.
