### ISSUE TITLE
Can't mount anything under /var/

### ISSUE THREAD

**Issue by empath** [docker/for-mac#1532] opened 2017-04-11 15:59 UTC
### Expected behavior

docker run -v /var/folders/qw/v0dbs38s4wx3s31g9nqrmzz40000gn/T/packer-docker499684549:/packer-files -d -i -t ubuntu /bin/bash

It should mount the volume.

I attempted to add /var as an allowed mount in preferences, but it says it's already allowed via /private.  If i remove private and add /var, it changes it to /private/var

packer attempts to mount volumes using /var -- and apparently docker can't tell that that is a symlink to /private/var

### Actual behavior
❯ docker run -v /var/folders/qw/v0dbs38s4wx3s31g9nqrmzz40000gn/T/packer-docker499684549:/packer-files -d -i -t ubuntu /bin/bash
1bf8fbf11e2f07741ec2f08339b2e6631ce50c1fcd362b7f68c70103ad0bbe01
docker: Error response from daemon: Mounts denied: -for-mac/osxfs/#namespaces for more info.
.
s31g9nqrmzz40000gn/T/packer-docker499684549
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

 try and use packer with docker for mac.

**Comment by empath** [comment] 2017-04-11 16:29
if i add /private/var/folders and then manually edit it to say
/var/folders, it still won't let me save it if '/private' is allowed, due
to over lap

**Comment by dsheets** [comment] 2017-04-11 16:35
You may have to add and remove conflicting paths in separate steps (see #139).

**Comment by empath** [comment] 2017-04-11 16:36
I removed /private, and now it tells me that "Failure to find export state
for path
/private/var/folders/qw/v0dbs38s4wx3s31g9nqrmzz40000gn/T/packer-docker209966685".

Looks like i'm damned if I do, damned if I don't.

**Comment by dsheets** [comment] 2017-04-11 16:41
You may need *both* `/private/var/folders` and `/var/folders` exported :confused:. Sorry this is so painful.

**Comment by balrajsingh** [comment] 2017-05-03 13:48
Hopefully @dsheets last suggestion was enough to make it work.  
I'm closing this issue now.  Feel free to reopen if it's still a problem.

**Closed** 2017-05-03 13:49 UTC
Labels: status/0-more-info-needed, status/0-triage

**Comment by mrooney** [comment] 2017-08-16 20:29
"Feel free to reopen if it's still a problem." I'll reopen as it is still a problem on 17.06.0-ce-mac19 (18663). Our Dockerfiles specify volumes like "/var/lib/foo", but even if you add and manually edit a path, Docker won't let you do it.

Steps to reproduce:
1. Navigate to the directory you want, like /var/lib/foo. Docker will turn this into /private/var/lib/foo.
2. Click to edit the field and manually change to /var/lib/foo.
3. You'll get the error "The path /var/lib/foo is reserved by Docker however it may be possible to export specific subdirectories." This happens whether or not you remove any /private shares first.

Any tips?

**Comment by dsheets** [comment] 2017-08-17 08:58
@mrooney is `/var/lib/foo` actually `/var/lib/dhcpd`, `/var/lib/docker`, or `/var/lib/misc`? Those paths exist in the VM inside DfM and can't be exported (yet) from the host. If you want to mount the VM's version of those paths, you can simply mount them directly without adding them via the File Sharing preference panel. Does that help?

**Comment by mrooney** [comment] 2017-08-17 18:51
@dsheets thanks for the reply! Though, it isn't those directories. It is random ones that didn't exist before a `mkdir`, for specific apps, like `/var/lib/grafana` and `/var/lib/influxdb`. So, I don't think that's the issue. Would the direct mounting approach still work for those? Either way, it still seems like a bug that the UI doesn't work and mangles paths that you type in.

**Comment by dsheets** [comment] 2017-08-18 11:34
@mrooney sorry, I'm having difficulty understanding your situation. Do `/var/lib/grafana` or `/var/lib/influxdb` exist on the host? What do you mean that the UI doesn't work? Unfortunately, the path mangling (symlink dereference) is a macOS file picker 'feature' that seems to be impossible to disable. I had `/Users`, `/Volumes`, `/private`, and `/tmp` shared and then I added ~`/private/var/lib/postfix`~ `/var/lib/postfix` and clicked `Apply & Restart` and it worked successfully.

Could you please open a new issue with a complete description of what you've run, how you've configured Docker for Mac, any UI issues and anything else relevant?

**Comment by kennblvnp** [comment] 2019-11-01 08:04
**2019**

> Adding /var


Cannot change shared directories

The path /var is reserved by Docker however it may be possible to export specific subdirectories.
Please see the documentation for more information.

**Comment by brandon-fryslie** [comment] 2019-12-19 21:33
> Please see the documentation for more information.
Has anyone actually been able to find this documentation?  I have been trying and am unable to locate it

**Comment by Teoble** [comment] 2020-04-17 12:21
Found this article very helpful: https://medium.com/@yorickjacquin/fixing-the-var-folders-error-in-docker-for-mac-v2-2-3-2a40e776132d
