### ISSUE TITLE
Docker 1.12.2-rc1-beta27 on OSX does not work

### ISSUE THREAD

**Issue by nelsonenzo** [docker/for-mac#730] opened 2016-09-30 18:46 UTC
### Expected behavior
docker ps to return containers running

### Actual behavior
docker ps just sits there and spins.  all commands do

### Information
appears to have started after the most recent update
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.10.5 (build: 14F1912)
logs: /tmp/457B79B0-21CB-4F55-B889-E73EFBC7D2D1/20160930-114235.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

install the latest bet on osx
start the docker client
try any docker command.

**Comment by szechyjs** [comment] 2016-10-01 00:42
dupe of #721

**Comment by samoht** [comment] 2016-10-14 12:13
Detected symptom of problem 'hypervisor-framework-acpi-crash' in 457B79B0-21CB-4F55-B889-E73EFBC7D2D1/20160930-114235.

It looks like at least some cases can be explained by a bug in the workaround for a hypervisor.framework ACPI crash bug. We are not sure whether the workaround is still needed -- the underlying crash may well have been fixed by Apple, especially in the most recent versions and updates of MacOS.

May be related to docker/for-mac#85

The following log matches:
```
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: Asking com.docker.hyperkit to thaw vcpus
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: vcpu 3 received signal, resuming
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: vcpu 1 received signal, resuming
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: vcpu 2 received signal, resuming
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: vm exit[2]
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: 	reason		VMX
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: 	rip		0xffffffff81099c1c
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: 	inst_length	3
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: 	status		0
Sep 27 09:57:48 admins-MacBook-Pro-4.local Docker[com.docker.driver.amd64-linux][66169] <Notice>: 	exit_reason	2
```

**Closed by samoht** 2016-10-14 12:13 UTC
Labels: osx/10.10.x, status/0-triage, version/beta27
