### ISSUE TITLE
Python Error when trying to execute docker-compose on MAC after updating Docker Desktop to version 2.2.0.0 (42247)

### ISSUE THREAD

**Issue by ArgV04** [docker/for-mac#4221] opened 2020-01-24 11:35 UTC
macOS Version: 10.12.6

### Diagnostic logs

```
Docker for Mac:
Docker Desktop 2.2.0.0 (42247)
docker version: 19.03.5
compose version: v1.25.2
```

### Steps to reproduce the behavior

  1. run docker-compose up
  
printing the following error:

```
[947] Error loading Python lib '/Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python': dlopen: dlopen(/Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python, 10): Symbol not found: _futimens
  Referenced from: /Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python
```

**Comment by stephen-turner** [comment] 2020-01-24 11:36
I think this is a dupe of docker/compose#7185, so I'll close this copy.

**Closed by stephen-turner** 2020-01-24 11:36 UTC
