### ISSUE TITLE
bash: /dev/null: Permission denied

### ISSUE THREAD

**Issue by Razique** [docker/for-mac#5559] opened 2021-04-09 17:03 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `ED222C15-0120-413C-BCA5-2AFF5B408AF4/20210409165732`

### Expected behavior
Regular user should be able to write to `/dev/null`
### Actual behavior
Bash returns a `bash: /dev/null: Permission denied` upon connecting to the container

### Information

  - macOS Version: `10.15.7 (19H524)`
  - Docker Desktop Version: `Docker Desktop 3.3.0 (62916)`

### Steps to reproduce the behavior

1.
Build a basic Fedora-based containers with the following Dockerfile:

```
FROM    fedora:32 as base

LABEL   Maintainer="Raz <test@test.com>" \
        Description="This build creates a Fedora-based toolbox"

ENV     build_env=/tmp/build-environment/ \
        repo_dir=/etc/yum.repos.d/ \
        gpg_dir=/etc/pki/rpm-gpg/ \
        gpg_key=RPM-GPG-KEY-rht-curriculum-530679EE \
        user=raz \
        user_name='Raz' \
        user_email='raz@test.com' \
        password='$1$.ZqJNP79$uDGZBE0PsWt0fYa7VBjHd0' \
        github_priv_key='github_rsa' \
        github_pub_key='github_rsa.pub'
ENV     PATH="/home/${user}/bin:${PATH}"

# Installation of base tools
RUN     dnf -y install \
        make \
        cyrus-sasl-gssapi \
        git \
        gcc \
        vim \
        gnupg \
        pinentry \
        python3-pip \
        crudini \
        git \
        nss \
        python-devel \
        python3-virtualenv \
        krb5-workstation \
        krb5-devel \
        openldap-devel \
        openldap-clients \
        sudo && \
        dnf clean all && \
        rm -rf /var/cache/dnf

RUN     python -m pip install --upgrade pip && \
        python -m pip install --upgrade wheel setuptools && \
        python -m pip install ansible==2.9.17 && \
        pip install aws-shell

RUN     useradd -d /home/${user} -ms /bin/bash -G wheel -p ${password} ${user} && \
        chmod 644 /etc/certs/* && \
        update-ca-trust

# Customize the user environment
USER    ${user}
RUN     echo -e "alias vi='vim'\nPS1=\"[\[\033[0;32m\]\u\[\033[0m\]@\[\033[0;37m\]\h\[\033[0m\] \W]$ \"" >> \
        /home/${user}/.bashrc
RUN     mkdir /home/${user}/bin && \
        git config --global user.email "${user_email}" && \
        git config --global user.name "${user_name}"

USER    ${user}
WORKDIR /home/${user}

```
  2. Start the container, a lot of permission denied errors will show up.
  3. This is the fix:
```
rm /dev/null
mknod /dev/null c 1 3
chmod 666 /dev/null
```

Notice that I have used the same Dockerfile for a few years now, and this is the first time that the issue shows up after installing this newer version.

**Comment by stephen-turner** [comment] 2021-04-09 17:20
Thanks for the report. I think it's actually the same underlying cause as #5527 so I'm going to close this as a dupe. We understand the problem and will fix it soon.

**Comment by gharik** [comment] 2021-04-12 18:53
Hi, same problem seems to be present when Docker Desktop 3.3.0 is run on Windows.

**Comment by stephen-turner** [comment] 2021-04-13 11:04
Closing as dupe of #5527, follow there for updates.

**Closed** 2021-04-13 11:04 UTC
Labels: version/3.3.0
