### ISSUE TITLE
Docker crashes with a "vmstateevent invalid json:" fatal error

### ISSUE THREAD

**Issue by messick** [docker/for-mac#134] opened 2016-08-04 21:56 UTC
### Expected behavior

Docker runs 
### Actual behavior
Docker crashes with a "vmstateevent invalid json:" fatal error
### Information

Diagnostic ID: 37E3B416-4C2B-4125-A4BC-B4ABE0FDCD10
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

Run `docker restart <container name>` brings problem immediately.  Although it will crash all on it's own.

**Comment by coryzibell** [comment] 2016-08-04 23:05
Having the same problem. Believe it is tied to macOS 10.12 beta, as it doesn't occur on my other El Capitan machine running Docker.

**Comment by chgu82837** [comment] 2016-08-05 03:56
Same problem here. But I got this problem when the docker native starts

```
Docker for Mac: version: mac-v1.12.0-beta21.1
OS X: version 10.12 (build: 16A270f)
logs: /tmp/A33DBF58-A22E-4F7C-967C-B5D478B7CE36/20160805-115223.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by glynjackson** [comment] 2016-08-05 10:20
Sae issue here ``vmstateevent invalid json``  Please see https://forums.docker.com/t/fatal-error-while-using-docker-v-1-11-2-beta15/15267/11

**Comment by dave-tucker** [comment] 2016-08-09 01:28
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 01:28 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
