### ISSUE TITLE
Docker does not start, com.docker.hyperkit over 100% CPU

### ISSUE THREAD

**Issue by kurtsplunk** [docker/for-mac#4101] opened 2019-12-05 22:38 UTC
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 0A392B24-416C-40DC-BB6A-09DD4FD569AC/20191205222340

### Expected behavior
- Docker Starts

### Actual behavior
- Docker does not start
### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version 2.1.0.5 stable

### Steps to reproduce the behavior
  1. Start Docker

**Comment by m8rge** [comment] 2019-12-22 10:57
I think this is duplicate of https://github.com/docker/for-mac/issues/4064

**Closed** 2019-12-23 17:20 UTC
Labels: version/2.1.0.5
