### ISSUE TITLE
M1 preview: disable "Use gRPC FUSE for file sharing"

### ISSUE THREAD

**Issue by jesperveldhuizen** [docker/for-mac#5240] opened 2021-01-11 16:39 UTC
At our company we are using docker for web development (mostly Symfony apps). We are now trying out a new M1 macbook (16 gb ram), and the M1 preview 7. 

In our experience it turned out that the osxfs filesharing is quicker then the new experimental gPRC FUSE filesharing. I'm trying out to disable this feature but Docker won't start.

I have tried to clean / purge data, and also factory reset.

I know osxfs is legacy, but I'm not sure what the status is on this? Will this for example be a feature in the future? So that users can choose with filesharing they like?

### Expected behavior

I expect docker to start when I disable gRPC FUSE for filesharing.

### Actual behavior

Docker won't start.

Docker for Mac: M1 preview 7

**Comment by stephen-turner** [comment] 2021-01-11 16:45
I'm surprised that it won't start with osxfs, that is not intentional (and shouldn't even make a difference until you start up a container that uses a bind mount).

So we'll look into that. However, osxfs will not be supported long term. We can't maintain both solutions.

**Comment by mattPiratt** [comment] 2021-01-17 15:41
I have the same. Docker will not start at all. Even after I clean everything. No images, no containers. Clean install. Will not start.
And using gRPC FUSE is not an option for my, since I cannot mount volumes, that inside (in subdirectory) have binds to other external filesystem. This binds do not work. Empty directory.
Looking forward this become working again, as it was before on osxfs.

**Comment by cdaguerre** [comment] 2021-01-21 09:01
This is a duplicate of https://github.com/docker/for-mac/issues/5147 (a month old).

**Comment by cdaguerre** [comment] 2021-01-21 09:15
@stephen-turner is there something we can do to help debugging this?

**Comment by stephen-turner** [comment] 2021-01-21 09:45
Thanks, but not at the moment. Please remember that the M1 build is an early preview. There's lots that isn't working yet.

**Comment by martinb3** [comment] 2021-01-25 17:46
Is there a way to query via CLI for the gRPC FUSE setting being enabled/disabled? We're also hoping to turn it off and advise folks when it accidentally remains on/enabled.

**Comment by stephen-turner** [comment] 2021-01-25 18:40
Not directly (see docker/roadmap#172), but you can check the settings.json.

**Comment by omarsotillo** [comment] 2021-03-19 19:24
After migrating to Docker Desktop RC 1 it seems to work 🎉  https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by stephen-turner** [comment] 2021-05-07 18:58
I think this is obsolete, I'm going to close it. If there are still startup issues, please open a new ticket with diagnostics.

**Closed by stephen-turner** 2021-05-07 18:58 UTC
Labels: area/m1
