### ISSUE TITLE
2.5.0.1 High CPU usage

### ISSUE THREAD

**Issue by Nuru** [docker/for-mac#5092] opened 2020-11-30 18:57 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7DDDF979-417F-442C-B930-719FC131249A/20201130184239

### Actual behavior

I have several containers running which mount my home directory into the containers with `--volume=$HOME:/local`. Running a shell script from a host terminal (that presumably obtained some sort of file lock on the directory) in one of those directories sent Hyperkit into > 300% CPU usage.

### Information

  - macOS Version: macOS 10.15.7 (19H15) (Catalina)
  - `Use gRPC FUSE for file sharing` enabled

My guess is that #5044 is actually several issues in one and this is one of them.

### Diagnostic logs

```
Docker for Mac: 2.5.0.1 (49550)
```

**Comment by stephen-turner** [comment] 2020-12-01 08:57
I guess the question is what the shell script actually does. If it does a lot of file changes, then it wouldn't surprise me that hyperkit gets very busy as everything has to be sync'ed across the VM boundary. But if there's something particular that the shell script is doing that confuses hyperkit, then that's a bug that could be fixed.

**Comment by Nuru** [comment] 2020-12-01 14:36
@stephen-turner As it turns out, the script had a bug, and it was just running an infinite recursive loop. Should not have been doing anything to the file system, just eating up CPU and memory. 
```bash
function foo() { foo bar baz; }
```

**Comment by kumarunster** [comment] 2020-12-03 17:50
similar issue here. After upgrade docker for mac to the version 2.5.0.1 I see relatively high cpu time on com.docker.hypervisor process. It is incredibly how fast the battery is empty. as well it seems to be the cause for running fans on my macbook.

For me it looks as the same issue from 2019, closed few weeks ago: https://github.com/docker/for-mac/issues/4981

Containers itself are idle, nearly zero cpu usage, but docker engine is running incredible high amount of cpu.

<img width="1408" alt="Bildschirmfoto 2020-12-03 um 18 46 01" src="https://user-images.githubusercontent.com/2104820/101067516-edbf4080-3597-11eb-9b1e-e229ea53487c.png">

PID file analytics:
[Analyse von „com.docker.hyperkit“.txt](https://github.com/docker/for-mac/files/5637955/Analyse.von.com.docker.hyperkit.txt)

**Comment by stephen-turner** [comment] 2020-12-03 17:54
Could you both try the most recent build pasted in #5044? We discovered a regression in the latest Linux kernel. That build reverts the kernel to an earlier version, and most users say it has solved their CPU problems.

**Comment by kumarunster** [comment] 2020-12-03 19:43
@stephen-turner many thanks for the link! seems that the new version reduced the load by half.

**Comment by retrodude** [comment] 2020-12-04 09:01
I tried different [offcial versions](https://docs.docker.com/docker-for-mac/release-notes/) 2.5.0.1, 2.4.0, 2.3.0.4 but with all of them, hyperkit had very high CPU > 600% (without any running containers) on my system. 
Luckily I found the Link to [Version 2.4.2](https://desktop-stage.docker.com/mac/edge/48862/Docker.dmg)  in [this thread](https://github.com/docker/for-mac/issues/5044) which workes for me! (CPU 8%).

MacOS 10.14.6, MacBook Pro 3,1 Ghz i7 (4 Cores, 8 Hyperthreads) 16GB 
Docker configured Resources: CPU: 6, Memory: 10 GB, Swap 4 GB.

**Comment by n13** [comment] 2020-12-06 17:32
> I tried different [offcial versions](https://docs.docker.com/docker-for-mac/release-notes/) 2.5.0.1, 2.4.0, 2.3.0.4 but with all of them, hyperkit had very high CPU > 600% (without any running containers) on my system.
> Luckily I found the Link to [Version 2.4.2](https://desktop-stage.docker.com/mac/edge/48862/Docker.dmg) in [this thread](https://github.com/docker/for-mac/issues/5044) which workes for me! (CPU 8%).
> 
> Addendum: the new [Version 2.5.4](https://desktop-stage.docker.com/mac/edge/50373/Docker.dmg) workes too!
> 
> MacOS 10.14.6, MacBook Pro 3,1 Ghz i7 (4 Cores, 8 Hyperthreads) 16GB
> Docker configured Resources: CPU: 6, Memory: 10 GB, Swap 4 GB.

Where - on what official page - can this 2.5.4 release be found? I only see up to 2.5.3 on the "edge" releases on the Docker page.

I need to verify it's an actual legitimate build before letting it run wild on my system (I really need VMs running OS X...)

**Comment by stephen-turner** [comment] 2020-12-07 11:17
2.5.4 is not released yet. We're expecting to release it later today, but it might not be that exact build.

**Comment by n13** [comment] 2020-12-07 14:33
Great thanks ! Would be very nice.

**Comment by stephen-turner** [comment] 2020-12-07 16:05
Yup, 2.5.4 (build 50534) is now released and fixes this bug, so I'll close this ticket.

If you're on the Stable channel, we're planning a release including this later this week.

**Closed by stephen-turner** 2020-12-07 16:05 UTC
Labels: version/2.5.0.1

**Comment by n13** [comment] 2020-12-07 16:40
This build dropped CPU to 2% with 1 core assigned to Docker - much better than before, still less than ideal but I guess on par with what it was before. I don't understand why it's using any CPU when no containers are running.

**Comment by stephen-turner** [comment] 2020-12-07 16:49
The VM is always running and may use a little bit of CPU.

**Comment by Niek** [comment] 2020-12-09 10:36
I can confirm that upgrading to 2.5.4 fixed high idle CPU for me.
