### ISSUE TITLE
After updating Docker, it crashes on its own (macOS Sierra B4)

### ISSUE THREAD

**Issue by Mike-AgileBits** [docker/for-mac#154] opened 2016-08-06 13:52 UTC
### Information

Diagnostic ID: 12A1B9FB-C129-4561-90AB-97994316F63E
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

After upgrading the app, I left it running in the menu bar but hasn't done anything yet. After a few minutes, it crashed with the above message.

**Comment by avsm** [comment] 2016-08-08 13:18
Duplicate of #64 -- please see https://github.com/docker/for-mac/issues/64#issuecomment-238191340 for progress on getting this working.

**Closed by avsm** 2016-08-08 13:18 UTC

**Comment by djs55** [comment] 2016-09-15 16:28
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
