### ISSUE TITLE
Docker Fatal Error

### ISSUE THREAD

**Issue by jbosse** [docker/for-mac#1430] opened 2017-03-14 13:34 UTC
Everything was working fine until this morning,

### Expected behavior
Docker launches

### Actual behavior
Docker gets fatal error "com.docker.osx.hyperkit.linux failed to start Exit code 1."

### Information

```
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/DDFD5E14-1C8A-4F07-A5D3-DCEF2663E691/20170314-092925.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ankura/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ankura/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ankura/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ankura/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/ankura/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ankura/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Launch docker.

**Comment by gkontokotsios** [comment] 2017-03-14 18:32
I am also experiencing this issue. My diagnostic ID is 5E3BA170-69EE-4DF6-BD5D-EB1717B5E508.

**Comment by jbosse** [comment] 2017-03-14 20:07
@gkontokotsios https://github.com/docker/for-mac/issues/1071#issuecomment-274360145 worked for me.

**Comment by djs55** [comment] 2017-03-21 14:23
@jbosse Looking at the diagnostics, I think this is a duplicate of https://github.com/docker/for-mac/issues/1315

```
2017-03-14 07:57:12-04 ... Docker[com.docker.driver.amd64-linux][1558] <Notice>: com.docker.hyperkit: [ERROR] Found a reference to cluster 201229 outside the file (max cluster 199992) from cluster 26821.42744
2017-03-14 07:57:12-04 ... Docker[com.docker.driver.amd64-linux][1558] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure
2017-03-14 07:57:12-04 ... Docker[com.docker.driver.amd64-linux][1558] <Notice>:   "Found a reference to cluster 201229 outside the file (max cluster 199992) from cluster 26821.42744")```
```
I'm glad the workaround worked for you. There have been several bug fixes in the soon-to-be-released `edge` release. Hopefully the new code will prove to be more stable.

@gkontokotsios your logs look different and don't contain the same error. Unfortunately some of the other diagnostic info is missing. If this still reproduces for you, could you open a fresh ticket and describe what happened in more detail?

**Closed by djs55** 2017-03-21 14:23 UTC
Labels: osx/10.12.x, status/0-triage, version/17.03.0-ce-mac2

**Comment by gkontokotsios** [comment] 2017-03-21 18:19
@jbosse Thanks for the heads up.

@djs55 The difference for me is that it happens only from time to time. Since I reported in this ticket I only saw a fatal error today. Unfortunately I didn't keep my diagnostic ID. Also I "Reset to factory defaults" to see if it helps. If it happens again I will open a fresh ticket as you suggested.

**Comment by jbosse** [comment] 2017-03-24 14:13
@gkontokotsios our team is operating under the current theory that our speed hacks (`echo -n false > ./com.docker.driver.amd64-linux/disk/full-sync-on-flush` and `echo -n none > ./com.docker.driver.amd64-linux/disk/on-flush`) have created a scenario where disconnecting from the Thunderbolt Display while Docker is running can result in corrupt bits.
