### ISSUE TITLE
Unable to resolve hosts ending in '.local'

### ISSUE THREAD

**Issue by andybrucenet** [docker/for-mac#1843] opened 2017-07-10 20:29 UTC
### Expected behavior
We have local DNS that resolves name 'redmine.hlsdev.local':
```
; <<>> DiG 9.8.3-P1 <<>> redmine.hlsdev.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50314
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;redmine.hlsdev.local.		IN	A

;; ANSWER SECTION:
redmine.hlsdev.local.	0	IN	A	172.20.132.29

;; Query time: 1 msec
;; SERVER: 172.24.6.239#53(172.24.6.239)
;; WHEN: Mon Jul 10 16:14:13 2017
;; MSG SIZE  rcvd: 54
```

We expect docker to do the same with default resolver.

### Actual behavior
Docker resolver simply does not attempt to resolve any FQDN with `.local`

```
/ # hostname
moby

/ # uname -a
Linux moby 4.9.31-moby #1 SMP Sat Jun 24 06:29:23 UTC 2017 x86_64 Linux

/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
v3.5.2-127-g1a53597add [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
OK: 5658 distinct packages available

/ # apk add bind-tools
(1/4) Installing libgcc (6.2.1-r1)
(2/4) Installing libxml2 (2.9.4-r3)
(3/4) Installing bind-libs (9.10.4_p8-r0)
(4/4) Installing bind-tools (9.10.4_p8-r0)
Executing busybox-1.25.1-r0.trigger
OK: 42 MiB in 54 packages

/ # dig redmine.hlsdev.local

; <<>> DiG 9.10.4-P8 <<>> redmine.hlsdev.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43104
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;redmine.hlsdev.local.          IN      A

;; Query time: 0 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Mon Jul 10 20:16:05 UTC 2017
;; MSG SIZE  rcvd: 38

```

### Information

Output from Docker diagnose:
```
Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/676DE2D2-B64F-4BA4-A83F-E26AB091EB3B/20170710-161200.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --style syslog --last 4d | grep -i docker > \"/tmp/676DE2D2-B64F-4BA4-A83F-E26AB091EB3B/20170710-161200/docker-system-os.log\": exit 1")
[OK]     docker-cli
[OK]     menubar
[OK]     disk

```

### Steps to reproduce the behavior

1. Add `dig` to Docker xhyve VM as demonstrated above.
1. Modify Docker xhyve VM's /etc/resolv.conf with explicit DNS:
    ```
    / # cat /etc/resolv.conf
    # Generated by dhcpcd from eth0.dhcp
    # /etc/resolv.conf.head can replace this line
    domain local
    #nameserver 192.168.65.1
    nameserver 172.24.6.239
    # /etc/resolv.conf.tail can replace this line
    ```
1. DNS lookup works correctly:
    ```
    / # dig redmine.hlsdev.local

    ; <<>> DiG 9.10.4-P8 <<>> redmine.hlsdev.local
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4193
    ;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;redmine.hlsdev.local.          IN      A

    ;; ANSWER SECTION:
    redmine.hlsdev.local.   0       IN      A       172.20.132.29

    ;; Query time: 1 msec
    ;; SERVER: 172.24.6.239#53(172.24.6.239)
    ;; WHEN: Mon Jul 10 20:20:15 UTC 2017
    ;; MSG SIZE  rcvd: 54
    ```
1. Tried several alternative configurations on `/etc/resolv.conf` with no success:
    Set the domain to something other than `.local`
    ```
    domain bogus.lcl
    nameserver 192.168.65.1
    ```
    No joy. Try to set options to force DNS resolution:
    ```
    domain bogus.lcl
    nameserver 192.168.65.1
    options ndots:1
    ```
    Still no joy.
1. Also verified that the Docker system log is not showing any lookups for any FQDNs ending in `.local`.
    ```
    / # dig redmine.hlsdev.foo

    ; <<>> DiG 9.10.4-P8 <<>> redmine.hlsdev.foo
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 28836
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;redmine.hlsdev.foo.            IN      A

    ;; Query time: 2 msec
    ;; SERVER: 192.168.65.1#53(192.168.65.1)
    ;; WHEN: Mon Jul 10 20:26:57 UTC 2017
    ;; MSG SIZE  rcvd: 36
    ```

    The above results in:
    ```
    CloudraticSolutionsLLCs-MacBook-Pro:~ cloudraticadmin$ syslog -w -k Sender Docker
    NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
    Jul 10 16:15:56 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Notice>: DNS lookup dl-cdn.alpinelinux.org AAAA: dl-cdn.alpinelinux.org <IN|2251> [CNAME (global.prod.fastly.net)]
    Jul 10 16:15:56 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Notice>: DNS lookup dl-cdn.alpinelinux.org A: dl-cdn.alpinelinux.org <IN|2251> [CNAME (global.prod.fastly.net)], global.prod.fastly.net <IN|12> [A (151.101.32.249)]
    --- last message repeated 1 time ---
    Jul 10 16:16:01 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Warning>: DNS lookup dl-cdn.alpinelinux.org AAAA: NoSuchRecord
    Jul 10 16:26:57 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Warning>: DNS lookup redmine.hlsdev.foo A: NoSuchRecord
    ```

    Repeating the test with `.local` FQDN:
    ```
    / # dig redmine.hlsdev.local

    ; <<>> DiG 9.10.4-P8 <<>> redmine.hlsdev.local
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58190
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;redmine.hlsdev.local.          IN      A

    ;; Query time: 0 msec
    ;; SERVER: 192.168.65.1#53(192.168.65.1)
    ;; WHEN: Mon Jul 10 20:27:59 UTC 2017
    ;; MSG SIZE  rcvd: 38
    ```

    This time - no entry displayed in Docker system logs (note that output is unchanged from the previous call:
    ```
    CloudraticSolutionsLLCs-MacBook-Pro:~ cloudraticadmin$ syslog -w -k Sender Docker
    NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
    Jul 10 16:15:56 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Notice>: DNS lookup dl-cdn.alpinelinux.org AAAA: dl-cdn.alpinelinux.org <IN|2251> [CNAME (global.prod.fastly.net)]
    Jul 10 16:15:56 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Notice>: DNS lookup dl-cdn.alpinelinux.org A: dl-cdn.alpinelinux.org <IN|2251> [CNAME (global.prod.fastly.net)], global.prod.fastly.net <IN|12> [A (151.101.32.249)]
    --- last message repeated 1 time ---
    Jul 10 16:16:01 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Warning>: DNS lookup dl-cdn.alpinelinux.org AAAA: NoSuchRecord
    Jul 10 16:26:57 CloudraticSolutionsLLCs-MacBook-Pro Docker[81084] <Warning>: DNS lookup redmine.hlsdev.foo A: NoSuchRecord
    ```

That is all.

**Comment by djs55** [comment] 2017-07-10 20:56
Thanks for your detailed report. I believe this is a duplicate of #1811. Happily this issue has been fixed in the `17.06` stable branch and should be included in the next patch release, due very soon. Whenever there is a build suitable for testing I'll let you know.

**Comment by djs55** [comment] 2017-07-14 12:16
I believe this is fixed in the latest stable patch
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
If it still doesn't work, could you upload a fresh diagnostic and let me know?

Thanks again for your report!

**Closed by djs55** 2017-07-14 12:16 UTC
Labels: kind/bug, status/1-acknowledged

**Comment by andybrucenet** [comment] 2017-07-14 20:36
Works when '.local' is in DNS.

However, I had a case where 'dockerregistry.hlsdev.local' is both in DNS and local /etc/hosts

From docker alpine: unable to ping it until I remove from /etc/hosts.

Is that expected?

Thanks,
Andy
