### ISSUE TITLE
Docker fails to pull container images with Virtualization + vmnet when docker is restarted from dashboard troubleshoot->restart option

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#6094] opened 2021-12-14 02:01 UTC
Docker fails to pull container images from docker hub when enabling Virtualization + vmnet and restarting docker using docker dashboard.

The following error message is reported:
```
user@host ~ % docker run -it centos /bin/bash
Unable to find image 'centos:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.5:3128: connect: connection refused.
```

The issue is reproducible on both ARM and Intel Mac devices. 

Steps To Reproduce:
1. Download & Install Latest Docker Desktop 4.3.0 for Mac (The issue can also be reproduced with older Docker Desktop: 4.2.0)
2. Make sure you don’t have container images already present. 
3. Issue “docker system prune -af” to remove all existing images and containers. 
4. Issue “docker images -a” to verify no images are present.
5. Modify ~/Library/Group Containers/group.com.docker/settings.json as follows to enable Virtualization + vmnet:

```
  "useVirtualizationFramework": true,
  "useVpnkit": false,
```

6. Now restart docker using Docker dashboard i.e. On Docker Dashboard click on Troubleshoot -> Restart Docker Desktop.
7. Once docker has restarted try to pull docker images using command `docker pull centos`. The command will fail with below message:

```
Unable to find image 'centos:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.5:3128: connect: connection refused.
```

8. The issue will get fixed if you issue a full docker stop by quitting docker desktop and again starting docker desktop.

**Comment by fredericdalleau** [comment] 2021-12-16 10:47
Hi @BenjaminPoulain,
This issue has reproduced. We have generated this diagnostic : 06B3EE99-BA8B-4987-99DC-36FD6EC3D79B/20211216104201.
Thanks for reporting
Frederic

**Comment by stephen-turner** [comment] 2021-12-20 10:10
Thanks, @BenjaminPoulain. We're marking this as Won't Fix because there is no UI to turn off vpnkit and there is a simple workaround. Obviously if we expose the setting publicly in the future, we will make sure that we restart the correct components when the setting is changed.

**Closed by stephen-turner** 2021-12-20 10:10 UTC
Labels: version/4.2.0
