### ISSUE TITLE
upgrade failed on 10.13.2 (17C88)

### ISSUE THREAD

**Issue by phunt** [docker/for-mac#2314] opened 2017-12-13 16:30 UTC
### Expected behavior

I upgraded to the latest version and it failed. Gave an error message and opened diags.

D595C349-813E-4279-AABF-DA70EF902F3F

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/D595C349-813E-4279-AABF-DA70EF902F3F/20171213-082558.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/phunt/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/phunt/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/phunt/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by phunt** [comment] 2017-12-13 16:48
I did a factory reset and that recovered, however I lost all the images, etc...

**Comment by Modicrumb** [comment] 2017-12-13 22:48
I have this same issue my diagnostic id is D9789FAA-ECB7-4816-825E-027D5893A761

**Comment by gtardif** [comment] 2017-12-14 11:35
closing as duplicate of #2317 (See comments to fix settings without full reset)

**Closed by gtardif** 2017-12-14 11:35 UTC
