### ISSUE TITLE
UDP problem when one socket talk with 2 or more sockets. [Version 1.12.3 (13776)]

### ISSUE THREAD

**Issue by samchang8826** [docker/for-mac#926] opened 2016-11-10 09:43 UTC
### Expected behavior
each received sockets address should correct.

### Actual behavior
not correct on mac, it's correct on ubuntu docker.
correct on container with `--net=host` enabled, but it's useless as we can't find the host/port of the hyperkit vm, and we can't use `-p` option.

### Information
remote1 console >
```
$ python remote1.py 
received: test => remote1 from ('192.168.65.104', 54027)
received: test => remote1 from ('192.168.65.104', 54027)
```

remote2 console >
```
$ python remote2.py 
received: test => remote2 from ('192.168.65.104', 50080)
received: test => remote2 from ('192.168.65.104', 50080)
```

container console >
```
root@9fc17b6c53d5:~# python test.py 
received: remote1 => test from ('192.168.65.104', 10002)
received: remote2 => test from ('192.168.65.104', 10002)
received: remote2 => test from ('192.168.65.104', 10002)
received: remote1 => test from ('192.168.65.104', 10002)
```
**all the `from` are same, it's incorrect.**

compare with follows:

test.py on mac console >
```
$ python test.py 
received: remote2 => test from ('192.168.65.104', 10002)
received: remote1 => test from ('192.168.65.104', 10001)
received: remote1 => test from ('192.168.65.104', 10001)
received: remote2 => test from ('192.168.65.104', 10002)
```

container with --net=host console >
```
root@moby:~# python test.py 
received: remote1 => test from ('192.168.65.104', 10001)
received: remote2 => test from ('192.168.65.104', 10002)
received: remote1 => test from ('192.168.65.104', 10001)
received: remote2 => test from ('192.168.65.104', 10002)
```

### Steps to reproduce the behavior

  1. run two python scripts on mac
remote1.py
```
import socket

address = ('0.0.0.0', 10001)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(address)

while True:
    data, addr = s.recvfrom(2048)
    print "received:", data, "from", addr
    s.sendto("remote1 => test", addr)

s.close()
```

remote2.py
```
import socket

address = ('0.0.0.0', 10002)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(address)

while True:
    data, addr = s.recvfrom(2048)
    print "received:", data, "from", addr
    s.sendto("remote2 => test", addr)

s.close()
```
  2. run a new container, install python, and change the ip inside test.py to your mac host.
test.py
```
import socket
import time

remote1 = ('192.168.65.104', 10001)
remote2 = ('192.168.65.104', 10002)

address = ('0.0.0.0', 12345)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(address)

while True:
    s.sendto("test => remote1", remote1)
    s.sendto("test => remote2", remote2)
    data, addr = s.recvfrom(2048)
    print "received:", data, "from", addr
    data, addr = s.recvfrom(2048)
    print "received:", data, "from", addr
    time.sleep(1)

s.close()
```
  3.  run test.py inside container.

**Comment by djs55** [comment] 2016-11-10 11:03
Thanks for the report and the very easy to follow reproduction steps. I can see the same effect on my machine. Furthermore if I permute the `s.sendto` lines in `test.py` then the last source port "wins".

It looks like the flow is:

- [recv_ba](https://github.com/docker/vpnkit/blob/a595bbe7207ac6337ed0c4c8309fad71d03dd9c3/src/hostnet/host_uwt.ml#L175) from `libuv` receives the buffer and the remote socket address
- [flow.reply](https://github.com/docker/vpnkit/blob/a595bbe7207ac6337ed0c4c8309fad71d03dd9c3/src/hostnet/host_uwt.ml#L191) is called with only the buffer: this clearly fails to act on the remote socket address

**Comment by djs55** [comment] 2016-11-18 16:47
Beta30.1 has fixed a number of bugs in this area. When I run the test example I now see:

```
host python remote1.py
received: test => remote1 from ('172.16.13.207', 59598)
```
and
```
host python remote2.py
received: test => remote2 from ('172.16.13.207', 59598)
```
and
```
container python test.py
received: remote1 => test from ('172.16.13.207', 10001)
received: remote2 => test from ('172.16.13.207', 10002)
received: remote1 => test from ('172.16.13.207', 10001)
received: remote2 => test from ('172.16.13.207', 10002)
```
Note the source ports received in the container (`10001` and `10002`) are preserved properly.

Please try beta 30.1 and let me know what you think. Thanks for using Docker for Mac!

**Comment by samchang8826** [comment] 2016-11-19 05:46
I did verified my project on beta30.1, it works well, thanks for your great work!

**Comment by samoht** [comment] 2017-01-30 20:19
The fix is now released on both the beta and stable channels so I am closing the issue. Please re-open (or open a new one) with a new diagnostic ID you still have that problem.

**Closed by samoht** 2017-01-30 20:19 UTC
Labels: area/network, status/4-fix-released-beta
