### ISSUE TITLE
Docker won't start on 3.2.0

### ISSUE THREAD

**Issue by snypelife** [docker/for-mac#5406] opened 2021-03-01 20:36 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DEF7F841-1ADA-4956-875E-C6AB2A2F9001
  - ~Can't open app, so can't get diagnostic info~

### Expected behavior
Docker to start and be accessible.

### Actual behavior
Docker process hangs and does nothing.

### Information

  - macOS Version: 11.2.2
  - Docker Desktop Version: 3.2.0

### Steps to reproduce the behavior

  1. Upgrade from 3.1.0 to 3.2.0
  2. Run Docker app
  3. That's it

Docker won't start properly for me, it just hangs when it's opened. Eventually activity monitor just marks the app as not responding and you have to kill it.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/1965406/109555544-ac113980-7aa3-11eb-8550-afa72ec3cb4c.png">

**Comment by snypelife** [comment] 2021-03-01 20:45
I'll see if I can get some more useful info.

**Comment by snypelife** [comment] 2021-03-01 20:56
Both in-app upgrade from 3.1.0 to 3.2.0 and fresh uninstall of 3.2.0 suffer from the same issue.

If I had to guess, I'd say it's something to do with 
> Add experimental support to use the new Apple Virtualization framework (requires macOS Big Sur 11.1 or later)

But then again, I don't really know the internals of Docker too well. Could be solar flares for all I know 🤷‍♂️

**Comment by erwanriou** [comment] 2021-03-01 20:56
Same here... I am desinstalling and trying to install from fresh to check.

**Comment by StefanScherer** [comment] 2021-03-01 20:59
Oh that's sad to see that you have problems with version 3.2.0.
It's not the new Apple Virtualization which is not enabled by default.
Could you try to gather and upload diagnostics from the command line as describe here https://docs.docker.com/docker-for-mac/troubleshoot/#diagnosing-from-the-terminal ?
Thanks!

**Comment by snypelife** [comment] 2021-03-01 21:01
Neat, that worked. 

DEF7F841-1ADA-4956-875E-C6AB2A2F9001 / 20210301210012

**Comment by snypelife** [comment] 2021-03-01 21:06
That command is super handy. Could a link to that page or even the command itself be included in the GH Issue template?

**Comment by mauriciolucas22** [comment] 2021-03-01 21:21
Hey guys, how are you? I had the same problem today. I closed Docker and com.docker.vmnet in the process manager.

When I started again he lost permissions and my password to install something. It must have been some network component, at the moment I didn't register it.

Now it's back up and running.

**Comment by snypelife** [comment] 2021-03-01 21:30
Sadly that does not work for me. I already tried killing the processes and restarting the app. Doesn't change anything. 😿

**Comment by tiefenb** [comment] 2021-03-01 21:52
I have the same setup and issue

**Comment by ericvn** [comment] 2021-03-01 22:48
Same here. Going to try and reinstall 3.1.0 over top. Seems better.

**Comment by ghedwards** [comment] 2021-03-01 22:52
Likewise, and I've lost my images.

**Comment by stugots** [comment] 2021-03-01 23:07
ditto

**Comment by oranges13** [comment] 2021-03-01 23:20
Diagnostics ID 10BAC153-4FDD-4189-814D-86DBBD71B6EB/20210301231926

**Comment by Andruten** [comment] 2021-03-01 23:23
Diagnostics ID:     6B26A600-5286-47A5-8C19-649C3BE32303/20210301231627

**Comment by ghedwards** [comment] 2021-03-01 23:31
Can the auto update to 3.2.0 be pulled ? I can install 3.1.0 but then any time I quit docker desktop it auto updates back to 3.2.0, very frustrating.

**Comment by stugots** [comment] 2021-03-01 23:32
where can I find 3.1.0?

**Comment by snypelife** [comment] 2021-03-01 23:34
@stugots https://github.com/docker/for-mac/issues/5406#issuecomment-788269675

**Comment by heston** [comment] 2021-03-02 00:25
+1 Same issue as reported by others. This was a fresh install (no prior version of Docker or other VMs installed).

Running Mac OS 11.2.1

Diagnostics ID: B34F82FE-6C2B-4942-9CA8-043083D79E4C/20210302002340

**Comment by ddellspe** [comment] 2021-03-02 00:38
I was getting errors on the startup related to:
`sysctl: unknown oid 'sysctl.proc_translated'`
This seems to be the ARM-checking system.

**Comment by StefanScherer** [comment] 2021-03-02 00:43
We see a higher error rate with the 3.2.0 release on Mac and we stopped rolling it out. We also see that stopping the rollout seems to relax the problem you encounter. So try to terminate Docker and start it again, the chances are high that it then normally starts. If it does not start, you can install 3.1.0 for now and as long we haven't started to rollout with a fixed version you don't see any updates to 3.2.0.
We'll investigate further the issue in the updater and keep you informed.

**Comment by karimsan** [comment] 2021-03-02 00:48
I had the same issue after the update. However, force-killing the process and starting the app again did solve the issue. After restart, it asked for network privileges - maybe it causes the issue.

**Comment by h3x00r** [comment] 2021-03-02 08:10
Just for posterity, after the upgrade to 3.2.0 I was unable to perform anything towards diagnostics or resolution. Even the CLI uninstall process failed. The only solution was to manually revert to 3.1.0.

**Comment by jasongordon** [comment] 2021-03-02 12:00
I too had this problem.  I killed the main docker process and also com.docker.vmnetd.  
Then I restarted the app, it prompted to reinstall the helper and then I was up and running.

```
$ ps auxwww | grep -i docker
root                99   0.0  0.0  4999656   7164   ??  Ss    5:09PM   0:00.11 /Library/PrivilegedHelperTools/com.docker.vmnetd
jgordon          28280   0.0  0.0  4279320    868 s000  S+    6:41AM   0:00.00 grep -i docker
$ sudo kill -9 99
$ ps auxwww | grep -i docker
jgordon          28295   0.0  0.0  4286488    864 s000  S+    6:41AM   0:00.00 grep -i docker
```

**Comment by StefanScherer** [comment] 2021-03-02 20:09
Thanks @jasongordon. Indeed we could narrow down the problem to `com.docker.vmnetd` still running during the update. We're working on a fix and will keep you informed once we continue the rollout.

**Comment by pires** [comment] 2021-03-03 12:49
Just downloaded the tech preview from the website and it simply won't start. Uninstalled. Clean/Purge. Reset to defaults. None has worked so far. ID 6E2D6E1A-1215-4D5E-9C58-2134BCDE0943/20210303124554

**Comment by erwanriou** [comment] 2021-03-03 16:15
@StefanScherer Indead, working with mac because more and more tedious each time. The last M1 chip is great but make everything complicate to run docker on it. 

Just for you to know, the only reason i keep using a mac is because ubuntu don't have a docker/kubernetes desktop integration like mac and we have to deal with minikube instead (that is really not practical sometime when you want to switch context or anything related to kubernetes). Would this extension exist that i would had abandoned mac a long time ago (and probably a lot of other developers too).

**Comment by StefanScherer** [comment] 2021-03-03 17:30
Thanks @erwanriou for your feedback. Have you voted for Docker Desktop on Linux in this roadmap ticket? https://github.com/docker/roadmap/issues/39
 😃

**Comment by jakob-fiegerl** [comment] 2021-03-05 12:42
> Just downloaded the tech preview from the website and it simply won't start. Uninstalled. Clean/Purge. Reset to defaults. None has worked so far. ID 6E2D6E1A-1215-4D5E-9C58-2134BCDE0943/20210303124554
> 
> Update: version is 3.1.0 (60984)
> 
> ```
>  ps auxwww | grep -i docker
> pires            26184   1.1  0.3 409917568  57632   ??  S    12:43PM   0:04.24 /Applications/Docker.app/Contents/MacOS/Docker
> pires            26326   0.0  0.4  8551596  71056   ??  S    12:43PM   0:00.06 com.docker.vpnkit --ethernet fd:3 --diagnostics fd:4 --pcap fd:5 --vsock-path vms/0/connect --host-names host.docker.internal,docker.for.mac.host.internal,docker.for.mac.localhost --listen-backlog 32 --mtu 1500 --allowed-bind-addresses 0.0.0.0 --http /Users/pires/Library/Group Containers/group.com.docker/http_proxy.json --dhcp /Users/pires/Library/Group Containers/group.com.docker/dhcp.json --port-max-idle-time 300 --max-connections 2000 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.254 --log-destination asl --gc-compact-interval 1800
> pires            26324   0.0  0.2  8510704  39296   ??  S    12:43PM   0:00.02 com.docker.osxfs serve --address fd:3 --transfused transfused.sock --control fd:4
> pires            26316   0.0  0.1 408827232  20272   ??  S    12:43PM   0:00.07 /Applications/Docker.app/Contents/MacOS/com.docker.supervisor -watchdog
> root             26315   0.0  0.0 408699248   6080   ??  Ss   12:43PM   0:00.03 /Library/PrivilegedHelperTools/com.docker.vmnetd
> pires            26198   0.0  0.3 408849104  44384   ??  S    12:43PM   0:00.69 /Applications/Docker.app/Contents/MacOS/com.docker.backend -watchdog
> pires            32205   0.0  0.0  8328668   6704 s002  R+   12:49PM   0:00.01 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i docker
> pires            29187   0.0  3.3 13886696 558032   ??  S    12:45PM   0:05.04 /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper (Renderer).app/Contents/MacOS/Docker Desktop Helper (Renderer) --type=renderer --field-trial-handle=1718379636,12124603741433818563,6664596460188816102,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --app-path=/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/app.asar --node-integration --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --enable-spellcheck --enable-websql --disable-electron-site-instance-overrides --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files
> pires            29185   0.0  0.7  9153488 123312   ??  S    12:45PM   0:00.16 /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper.app/Contents/MacOS/Docker Desktop Helper --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=1718379636,12124603741433818563,6664596460188816102,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --shared-files --seatbelt-client=47
> pires            29182   0.0  1.1 10024260 179184   ??  S    12:45PM   0:02.12 /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Frameworks/Docker Desktop Helper (GPU).app/Contents/MacOS/Docker Desktop Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,12124603741433818563,6664596460188816102,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAA6AAAABwAAADgAAAAAAAAAOgAAAAAAAAA8AAAAAAAAAD4AAAAAAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAAAAAAABwAAABAAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAAAAAA0AAAAQAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAABgAAABAAAAAAAAAAAQAAAAcAAAAQAAAAAAAAAAEAAAAIAAAAEAAAAAAAAAABAAAACgAAABAAAAAAAAAAAQAAAAsAAAAQAAAAAAAAAAEAAAANAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABgAAAAAAAAAQAAAAAAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAABwAAABAAAAAAAAAABgAAAAgAAAAQAAAAAAAAAAYAAAAKAAAAEAAAAAAAAAAGAAAACwAAABAAAAAAAAAABgAAAA0AAAA= --shared-files
> pires            29069   0.0  3.4 14568556 568224   ??  S    12:45PM   0:04.64 /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop --name=settings
> pires            26349   0.0  0.1 409251696  17424   ??  S    12:43PM   0:00.04 /Applications/Docker.app/Contents/MacOS/com.docker.virtualization --kernel /Applications/Docker.app/Contents/Resources/linuxkit/kernel --cmdline page_poison=1 vsyscall=emulate panic=1 nospec_store_bypass_disable noibrs noibpb no_stf_barrier mitigations=off console=hvc0 irqaffinity=0 vpnkit.connect=tcp+bootstrap+client://gateway.docker.internal:51553/5c8b650f2761bbcbddae931401c333252edfc23a5dfd10f0860b6fccfc19b96d --ramdisk /Applications/Docker.app/Contents/Resources/linuxkit/initrd.img --disk /Users/pires/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw --macaddr-filename vms/0/macaddr --cpus 4 --memoryMiB 2048 --console-log vms/0/console.log --console vms/0/console.sock
> pires            26331   0.0  0.6  9202912 107568   ??  S    12:43PM   0:00.19 docker serve --address unix:///Users/pires/.docker/run/docker-cli-api.sock
> pires            26330   0.0  0.2 408838976  34224   ??  S    12:43PM   0:01.38 com.docker.driver.amd64-linux -addr fd:3 -debug
> ```
> 
> Update 2: Firewall must be disabled for Docker for Mac to (re)start successfully. I couldn't find this information anywhere in the TP webpage so I strongly suggest it to be added there.

Thanks @pires. Disabling the firewall worked for me!

**Comment by StefanScherer** [comment] 2021-03-05 14:39
Heads up, dear 3.2.0 users. We found the root cause of this problem that happens while we ship a new release.
We continue to rollout the new version 3.2.1 that has a fix for that, but users that have 3.2.0 installed may see the startup problem again. 

We've added a known issues section to our 3.2.0 release notes https://docs.docker.com/docker-for-mac/release-notes/#known-issue

> Docker Desktop can sometimes fail to start after updating to version 3.2.0. If you are experiencing this issue, we recommend that you uninstall 3.2.0 and manually install [Docker Desktop 3.2.1](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-321).

**Comment by ericvn** [comment] 2021-03-05 15:24
My upgrade from 3.2.0 to 3.2.1 appears to have worked (note that I had done the work-around to get 3.2.0 prompt and start and was running it fine).

**Comment by stephen-turner** [comment] 2021-03-05 15:28
I'm going to close this issue as the fix is now released, but feel free to continue commenting.

**Closed by stephen-turner** 2021-03-05 15:28 UTC
Labels: version/3.1.0, version/3.2.0

**Comment by StefanScherer** [comment] 2021-03-05 15:59
@ericvn Good to know. And yes if you have DD 3.2.0 already running it will automatically download the update to 3.2.1 and show it in the whale icon and menu. 
And starting DD 3.2.0 often works, but could hang sometimes.

**Comment by snypelife** [comment] 2021-03-05 18:47
Can confirm 3.2.1 works now on macOS 11.11.2 👍

Thank you @StefanScherer  and the Docker Team for fixing that so quickly! Keep up the good work ♥️

**Comment by linhnguyen-okta** [comment] 2021-03-05 19:34
Can anyone point me to the right resource on how to uninstall 3.2.0 when I cannot open the app and do uninstall on the app?

**Comment by StefanScherer** [comment] 2021-03-05 19:47
@linhnguyen-okta 
Open the Activity Monitor and filter for docker processes. If you see some of the following, then Force Quit them to have all processes stopped.

<img width="933" alt="macos-activity-monitor-docker-processes" src="https://user-images.githubusercontent.com/207759/110165710-99746880-7df3-11eb-8913-ea649c9d9f25.png">

Then open Finder and go to Applications folder, search for the Docker application, and drag and drop it into the bin.

<img width="850" alt="finder-applications-docker" src="https://user-images.githubusercontent.com/207759/110165917-e7896c00-7df3-11eb-95dd-f4840c439297.png">

After that you should be fine to install 3.2.1.

**Comment by linhnguyen-okta** [comment] 2021-03-05 19:49
Thanks a lot, it worked now

**Comment by manpreetchime** [comment] 2021-03-15 04:52
I faced the same issue even after installing 3.2.1. Had to downgrade to 3.1.0 to make it work.
