### ISSUE TITLE
Error driver.amd64-linux, moby 

### ISSUE THREAD

**Issue by MelchiSalins** [docker/for-mac#1261] opened 2017-02-05 23:36 UTC
### Behavior
Docker for Mac: version: 1.13.1-rc1-beta40 (0d026e19d)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/D1255A9E-7952-4960-836A-939FB48D0EE7/20170206-103323.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/salinsm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/salinsm/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by jesperronn** [comment] 2017-02-06 22:43
Duplicate of #1259?

**Comment by ijc25** [comment] 2017-02-20 13:39
@MelchiSalins towards the end of your logs I see:
```
<Critical>: 9p: (Sys_error
          "/Users/.../Library/Containers/com.docker.docker/Data/database/.git/tmp/43b5a1b52006752fc7293a0569af88cbcedf4b7f9e6fwrite: No space left on device")
```
which suggests that your Mac's disk has filled up.

I also see evidence of some qcow corruption which seems likely to be related (or perhaps preexisting). I would recommend a factory reset after you free some space on your system.

If your disk was full because of the size of the `Docker.qcow2` grew too large then you may find the instructions in https://github.com/docker/for-mac/issues/1118#issuecomment-271399701 useful to set a default size more suitable for the amount of space you have available.

I'm going to close this for now, please don't hesitate to reopen (with a fresh diagnostic upload) if you still have issues after sorting out the disk space.

**Closed by ijc25** 2017-02-20 13:39 UTC
Labels: osx/10.12.x, status/0-triage, version/beta40
