### ISSUE TITLE
A138477F-CF78-464A-9CBA-95A4E14AB6F4/20200414212345

### ISSUE THREAD

**Issue by rimbu002** [docker/for-mac#4453] opened 2020-04-14 21:34 UTC
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A138477F-CF78-464A-9CBA-95A4E14AB6F4/20200414212345

### Actual behavior
I am using Docker with a couple of ddev projects and everything starting to very slow in past week or so, after that last update I believe.

### Information

  - macOS Version: Catalina 10.15.4

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-04-15 07:57
Closing as dupe of #4423. Please continue the discussion there.

**Closed by stephen-turner** 2020-04-15 07:57 UTC
Labels: status/0-triage, version/2.2.0.5
