### ISSUE TITLE
Docker 3 Cannot start service php: Mounts denied: approving php.ini not found - but file exists in folder

### ISSUE THREAD

**Issue by chaznied** [docker/for-mac#5118] opened 2020-12-10 20:04 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by chaznied** [comment] 2020-12-10 20:05
I just updated and this happened

**Comment by bismark64** [comment] 2020-12-10 20:18
Same here for my Rails project: `Cannot start service app: Mounts denied: approving /path/to/project: file does not exist`

**Comment by roger6106** [comment] 2020-12-10 20:36
Same issue on my end. This command worked fine for me this morning, but now that I've updated I have this error. 

```
docker run -v ~/Downloads/cred/:/cred:ro --rm alpine:latest
```
Returns:
> docker: Error response from daemon: Mounts denied: approving /Users/roger/Downloads/cred: file does not exist.
> ERRO[0000] error waiting for container: context canceled

**Comment by roger6106** [comment] 2020-12-10 20:37
Duplicate of https://github.com/docker/for-mac/issues/5115

**Comment by stephen-turner** [comment] 2020-12-10 22:29
Closing as dupe

**Closed by stephen-turner** 2020-12-10 22:29 UTC
