### ISSUE TITLE
Got "The Apple Silicon preview build has expired" on Docker preview 5

### ISSUE THREAD

**Issue by spksoft** [docker/for-mac#5138] opened 2020-12-16 12:20 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker preview 5 for apple M1 should start correctly

### Actual behavior
Got alert box show the message "The Apple Silicon preview build has expired. Please download Docker Desktop from https://www.docker.com/"

<img width="596" alt="Screen Shot 2563-12-16 at 19 15 02" src="https://user-images.githubusercontent.com/1377991/102347434-01749900-3fd3-11eb-9194-1f5497ef5a8b.png">

### Information

  - macOS Version: Macbook air M1, 2020 with macOS 11.0.1 

### Diagnostic logs

```
Docker for Mac: Docker-AppleSilicon-Preview5

time="2020-12-16T12:08:26Z" level="info" msg="AppDelegate: Initiating Graceful shutdown"
time="2020-12-16T12:08:26Z" level="info" msg="AppDelegate: End of  Graceful shutdown"
time="2020-12-16T12:08:26Z" level="info" msg="AppDelegate: applicationWillTerminate"
time="2020-12-16T12:12:42Z" level="error" msg="Logging system already setup"
time="2020-12-16T12:12:42Z" level="info" msg="CrashReport: stderr redirected to /Users/spksoft/Library/Group Containers/group.com.docker/DockerAppStderr.txt"
time="2020-12-16T12:12:42Z" level="info" msg="DockerApplication: Docker.app starting for spksoft"
time="2020-12-16T12:12:42Z" level="info" msg="applicationDidFinishLaunching: options.restart = false"
time="2020-12-16T12:12:42Z" level="error" msg="bootstrap: preview build has expired"
time="2020-12-16T12:12:42Z" level="fault" msg="Terminator: The Apple Silicon preview build has expired. Please download Docker Desktop from https://www.docker.com/"
time="2020-12-16T12:12:42Z" level="fault" msg="Terminator: 0   Docker                              0x0000000100910f28 $s6Docker10TerminatorC19displayFatalAndQuit_14onlyExitButton11diagnostics8exitCode5titleySS_SbSSSgs5Int32VAItFZTf4nnnnnd_n + 160
1   Docker                              0x00000001009132c8 $s6Docker11AppDelegateC9bootstrapAA16BootstrapStoppedCSgyF + 844
2   Docker                              0x0000000100912df0 $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVF + 392
3   Docker                              0x0000000100912f44 $s6Docker11AppDelegateC29applicationDidFinishLaunchingyy10Foundation12NotificationVFTo + 108
4   CoreFoundation                      0x0000000197528598 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
5   CoreFoundation                      0x00000001975c97d4 ___CFXRegistrationPost_block_invoke + 52
6   CoreFoundation                      0x00000001975c9740 _CFXRegistrationPost + 440
7   CoreFoundation                      0x00000001974f7080 _CFXNotificationPost + 720
8   Foundation                          0x000000019825e650 -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
9   AppKit                              0x0000000199d1044c -[NSApplication _postDidFinishNotification] + 340
10  AppKit                              0x0000000199d10164 -[NSApplication _sendFinishLaunchingNotification] + 236
11  AppKit                              0x0000000199d0d258 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 580
12  AppKit                              0x0000000199d0ce40 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 780
13  Foundation                          0x000000019828b840 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 344
14  Foundation                          0x000000019828b678 _NSAppleEventManagerGenericHandler + 96
15  AE                                  0x000000019d196d34 _AppleEventsCheckInAppWithBlock + 15964
16  AE                                  0x000000019d196590 _AppleEventsCheckInAppWithBlock + 14008
17  AE                                  0x000000019d18f000 aeProcessAppleEvent + 520
18  HIToolbox                           0x000000019f04cc58 AEProcessAppleEvent + 68
19  AppKit                              0x0000000199d07194 _DPSNextEvent + 1864
20  AppKit                              0x0000000199d05730 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1312
21  AppKit                              0x0000000199cf758c -[NSApplication run] + 600
22  AppKit                              0x0000000199cc8d74 NSApplicationMain + 1064
23  Docker                              0x0000000100908884 main + 12
24  libdyld.dylib                       0x0000000197454f54 start + 4"
```

### Steps to reproduce the behavior

  1. Download the Docker for mac m1 preview 5 from Slack 
  2. Drag and Drop Docker icon to Application folder
  3. Start docker by click docker preview icon

**Comment by stephen-turner** [comment] 2020-12-16 14:30
This is probably a dupe of #5126. You can fix it by setting your calendar to the western calendar.

**Closed by stephen-turner** 2020-12-16 14:30 UTC
