### ISSUE TITLE
docker keeps saying killes whenever i type the command "docker"

### ISSUE THREAD

**Issue by ZardashtKaya** [docker/for-mac#264] opened 2016-08-13 13:50 UTC
### Information

Diagnostic ID: F39F284C-5088-4A93-A8B0-BCA730197F8C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.2 (Build 15C50)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment] 2016-09-29 14:50
Your logs contain many instances of
```
kernel[kern][0] <Notice>: OSTIARIUS: /Applications/Docker.app/Contents/Resources/bin/docker is from the internet & is unsigned -> BLOCKING!
``

**Comment by samoht** [comment] 2016-10-12 14:57
Thanks for your report, but I am closing that issue as a duplicate of #713. Please follow the resolution of that issue for further updates.

**Closed by samoht** 2016-10-12 14:57 UTC
Labels: area/startup, kind/bug, osx/10.11.x, status/0-triage, version/1.12.0-a
