### ISSUE TITLE
Error starting after upgrade to 17.12.0-ce-rc2-mac41: E3910038-1187-4D64-B606-380D1E260B14

### ISSUE THREAD

**Issue by mattscilipoti** [docker/for-mac#2317] opened 2017-12-14 04:55 UTC
### Expected behavior
Starts without errors.

### Actual behavior
com.docker.supervisor failed to start.  Exit code 1

### Information

  - Diagnostic ID: E3910038-1187-4D64-B606-380D1E260B14

### Steps to reproduce the behavior

  1. Upgrade to 17.12.0-ce-rc2-mac41.  Failed on restart.
  2. Attempt to start, again, after the upgrade.

**Comment by mattscilipoti** [comment] 2017-12-14 06:18
Reboot did not solve it.

**Comment by gjastrab** [comment] 2017-12-14 06:21
Hey Matt 👋 

Same issue for me. Other potentially relevant info - I'm on Sierra 10.12.6 and here is the output from Diagnose:

```
Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.12.6 (build: 16G1114)
logs: /tmp/E43835BB-09B2-4942-8300-845C404B2C7A/20171214-011705.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/gjastrab/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/gjastrab/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/gjastrab/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by halhenke** [comment] 2017-12-14 06:54
High Sierra v10.13.2 and have the exact same error message as gjastrab.

**Comment by javathought** [comment] 2017-12-14 07:01
same error, Sierra 10.12.6
diagnostic ID : 05734D46-8A69-4113-BE83-5F948B53DA66

**Comment by MikeMitterer** [comment] 2017-12-14 07:07
Same here: DID: 5DBB1891-D9D2-4C60-96C0-D2BECBEA8070
El Captain 10.11.6

**Comment by chrisdhaan** [comment] 2017-12-14 07:41
Experiencing the same issue.

**Comment by MartijnWelker** [comment] 2017-12-14 07:49
El Capitan, same error message 3CCB72ED-08DB-4B39-B387-72044BE5EE4D

**Comment by andrekully** [comment] 2017-12-14 08:05
Had the same error on High Sierra 10.13.2 / 17.12.0-ce-rc2-mac41 
Pressing the "Reset to factory defaults" button seems to solve it as far as I can see. 
Unfortunately all local images and containers will be lost but can recreated and downloaded again.

**Comment by edsinclair** [comment] 2017-12-14 08:43
3A00D026-0165-4A06-9CDE-1FF7CFE5A800 same issue. Mac OS 10.13.2

**Comment by gtardif** [comment] 2017-12-14 09:54
Looking at the diags, it seems that you have "/" in the shared folders, which causes mount failures. Without a full reset, you can edit `~/Library/Group\ Containers/group.com.docker/settings.json` and remove "/" in the shared folders, Docker For Mac should restart fine after that.
We are investigating if there are any update scenarios that might add this "/", updating from older releases ; ATM I cannot reproduce this.

**Comment by edsinclair** [comment] 2017-12-14 10:06
@gtardif are you referring to the `filesharingDirectories` array? If so, I tried doing as you suggested and Docker still refuses to start with the same error. 3A00D026-0165-4A06-9CDE-1FF7CFE5A800

I changed the following
```
"filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/tmp",
    "/private",
    "/Users/eirik/Library/Containers/com.docker.docker/Data"
  ]
```

and I updated it to this:

```
"filesharingDirectories" : [
    "Users",
    "Volumes",
    "tmp",
    "private",
    "Users/eirik/Library/Containers/com.docker.docker/Data"
  ]
```

**Comment by gtardif** [comment] 2017-12-14 10:32
@edsinclair Ah this is a slightly different issue ; in your case it's "Users/eirik/..." that cannot be shared in the VM. you need to change your filesharingDirectories to : 
```"filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/tmp",
    "/private"
  ]```
(In your case this folder comes from older versions of Docker For Mac, we will include a fix to remove this during the update)

**Comment by gtardif** [comment] 2017-12-14 10:40
Other diags show settings with : 
```
"filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/tmp",
    "/private", 
    "/"
  ]
```
the last ` , "/"` needs to be removed from the array

**Comment by MikeMitterer** [comment] 2017-12-14 12:23
Removing the `/` solved the problem - Thanks!

![capturfiles-20171214_012131](https://user-images.githubusercontent.com/116654/33992164-d99bda6e-e0d1-11e7-9747-0e1da2f2e1b2.png)

**Comment by edsinclair** [comment] 2017-12-14 13:17
@gtardif thanks. That did the trick for me.

**Comment by jeantil** [comment] 2017-12-14 14:33
I have the same issue where 
``` 
"/Users/jean/Library/Containers/com.docker.docker/Data"
``` 
is in the shared directories

remonving this offending  line solved the startup issue.

**Comment by ulope** [comment] 2017-12-14 15:35
Same here, removing `/Users/ulo/Library/Containers/com.docker.docker/Data` from 
```
  "filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/tmp",
    "/private",
    "/Users/ulo/Library/Containers/com.docker.docker/Data"
  ],
```
solved the issue. 

I'm quite sure that I didn't add this directory.

**Comment by vinitkumar** [comment] 2017-12-14 19:06
Can't get Docker for mac to run with the latest edge version:

Here are my logs:


```
Docker for Mac: version: 17.12.0-ce-rc2-mac41 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/A58EB61F-6542-4073-9DDB-CC05326D9624/20171215-003506.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/vinitkumar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/vinitkumar/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/vinitkumar/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/vinitkumar/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```

**Comment by javathought** [comment] 2017-12-14 20:32
@gtardif thanks, ok for me 👌

**Comment by CarlQLange** [comment] 2017-12-15 00:40
Same here - had `filesharingDirectories: [""]`, removed the blank string and solved my issue.

**Comment by ycaille** [comment] 2017-12-15 01:16
@gtardif Many thanks for the fix. I removed a `"/"` entry in the `filesharingDirectories` section and that solved my startup issue.

**Comment by glynd** [comment] 2017-12-15 08:32
Removing the 'Data' folder allowed it to start for me
I still have the remaining paths starting with a '/'

**Comment by BrendonW** [comment] 2017-12-15 13:47
It really would have been helpful for Docker to NOT quit when it couldn't start properly, since accessing the configuration, setting, help, etc. available from the whale menu would be helpful. And less devastating than losing all your images.

May I suggest adding an option to "run broken" so that users can investigate/make changes or wait for an upgrade that might fix the problem.

**Comment by BrendonW** [comment] 2017-12-15 13:49
A followup question, how can I recover my images after a reset -- which at the time seemed to be the only option. And in particular, recovery of the data volumes?

A warning about the loss would have been great! I thought it reset config, not cause catastrophic data loss!

**Comment by kudos** [comment] 2017-12-16 13:28
@BrendonW if losing your images or data volumes is catastrophic, I would suggest not using the edge builds. The way to recover the images is to rebuild them, the data volumes are lost.

**Comment by BrendonW** [comment] 2017-12-16 16:43
@kudos I was in the middle of transitioning them from monolith to services and my latest development data sets are in the volume -- and my working development environment. So only catastrophic in the sense of not wanting to be forced to move backwards or forwards to get back to a 100% working development & test environment.  In a small startup, time is the most critical resource... followed by cash!

I do have regular backups, so I CAN go back in time. The real question is -- what do I want to pull out of history and how do I move it into the latest install. If I can't do it here and now, how will I recover things after a mistake/crash/act of god in production? I might as well learn here and now, before this kind of mistake kills the company, which taking production down for hours or days will do...

**Comment by halhenke** [comment] 2017-12-21 02:53
If this helps at all - here is what i get searching logs in Console App:

```
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /tmp
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Volumes
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Users
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: Negotiated transfuse notification channel for /private
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: Negotiated transfuse notification channel for /tmp
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: Negotiated transfuse notification channel for /Volumes
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: Negotiated transfuse notification channel for /Users
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: sending continue to client
Dec 21 13:44:42 Hals-MacBook-Pro Docker[57882]: Fatal unexpected exception: Socket.Closed
```

**Comment by KyungSun4** [comment] 2018-01-10 04:22
I am still having the same issue after following these instructions

**Comment by achal272** [comment] 2018-01-10 13:05
I'm still having the same issue after following all the instructions above.
I was trying to install Docker for the first time and it failed with the following diagnostics.
I did try resetting it as well, but it returned with the same error : 

Fatal Error
com.docker.supervisor failed to start
Exit code 1

It is stuck at "Docker is starting.."

### Information

Diagnostic ID : EBA1FC5C-21A8-431F-832A-D4B3ADBFE56E

```
Docker for Mac: version: 17.12.0-ce-mac46 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/EBA1FC5C-21A8-431F-832A-D4B3ADBFE56E/20180110-172744.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/achalagrawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/achalagrawal/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/achalagrawal/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/achalagrawal/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```
### Steps to reproduce the behavior

  Nothing specific. Just drag and drop the installer to Applications, and it fails.

### What I already tried

I tried to reboot, and reset docker - Didn't work.
I checked the settings.json file and it doesn't have the above issue.

```
{
  "proxyHttpMode" : "system",
  "diskPath" : "/Users/achalagrawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.raw",
  "diskSizeMiB" : 65536,
  "cpus" : 2,
  "defaultMachineMigrationStatus" : 4,
  "memoryMiB" : 2048,
  "displayedWelcomeWhale" : true,
  "buildNumber" : "21698",
  "filesharingDirectories" : [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp"
  ],
  "channelID" : "stable",
  "settingsVersion" : 1,
  "version" : "17.12.0-ce-mac46",
  "displayedWelcomeMessage" : true,
  "dockerAppLaunchPath" : "/Applications/Docker.app",
  "linuxDaemonConfigCreationDate" : "2018-01-10 12:53:10 +0000"
}
```

**Comment by chrisid** [comment] 2018-01-11 09:33
Having the same issue, even removing every thing from filesharingDirectories : [] won't work.

*desperate here!

**Comment by samfranklin** [comment] 2018-01-11 10:58
Yeah, same issue I think. Downloaded Docker for Mac Stable Version and installed for the first Time on High Sierra 10.13.2.

#### Diagnostic Log
```
Docker for Mac: version: 17.12.0-ce-mac46 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/BBCC4D49-F4D3-42F4-8149-714375B3F9AF/20180111-105041.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/samfranklin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/samfranklin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/samfranklin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/samfranklin/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

#### edited settings.json as above comments to
```json
{
  "proxyHttpMode" : "system",
  "diskPath" : "/Users/samfranklin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.raw",
  "diskSizeMiB" : 65536,
  "cpus" : 2,
  "defaultMachineMigrationStatus" : 4,
  "memoryMiB" : 2048,
  "diagnosticID" : "BBCC4D49-F4D3-42F4-8149-714375B3F9AF",
  "displayedWelcomeWhale" : true,
  "buildNumber" : "21698",
  "filesharingDirectories" : [
    "Users",
    "Volumes",
    "private",
    "tmp"
  ],
  "channelID" : "stable",
  "settingsVersion" : 1,
  "version" : "17.12.0-ce-mac46",
  "displayedWelcomeMessage" : true,
  "dockerAppLaunchPath" : "/Applications/Docker.app",
  "linuxDaemonConfigCreationDate" : "2018-01-11 10:44:45 +0000"
}
```

**Comment by dunglp** [comment] 2018-01-13 14:43
I just install for the 1st time and experience this issue. 

Here is the diagnostic: 

```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/E79D497F-C82F-41C1-BCE0-ECBAEE62CF6C/20180113-214209.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/bi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bi/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/bi/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/bi/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```

**Comment by thedewpoint** [comment] 2018-01-13 15:32
+1 Same issue here

**Comment by thedewpoint** [comment] 2018-01-13 23:37
@achal272 any luck?

**Comment by twof** [comment] 2018-01-14 17:35
Also experiencing the same issue 
```
Fatal Error
com.docker.supervisor failed to start
Exit code 1
```
on fresh install. I get the same thing after restoring and entering my admin password again.

Diagnostic ID: 16BEFBC8-ACB8-4568-B244-E78968D70D39

```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/16BEFBC8-ACB8-4568-B244-E78968D70D39/20180114-093010.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/fnord/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/fnord/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/fnord/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/fnord/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by twof** [comment] 2018-01-14 18:27
Resolved by running Docker's uninstall script
`$ /Applications/Docker.app/Contents/MacOS/Docker --uninstall`
Reinstalling using the installer on the Docker site, and then restarting my machine. Docker was stuck on `Docker is starting` after I reinstalled and then successfully ran after the restart. 

A reinstall may have been unnecessary.

**Comment by halhenke** [comment] 2018-01-15 02:41
I removed the `Users` folder and that helped once but on next reset the problem started again.

However after biting the bullet and hitting "Reset to Defaults" the issue seemed to resolve itself. Didn't lose any images either as far as i can tell ¯\_(ツ)_/¯

**Comment by dunglp** [comment] 2018-01-15 03:40
Here is how I get my docker started.

1. Move docker.app to trash
2. Run uninstall.sh from https://github.com/docker/toolbox/blob/master/osx/uninstall.sh
3. Download Stable version, installed and it worked.

Hope this can help.

**Comment by lunaczp** [comment] 2018-01-17 03:08
similar steps like @twof recommend works for me.
0. stop docker
1.  rm -rf ~/Library/Group\ Containers/group.com.docker/ ~/Library/Containers/com.docker.docker ~/.docker
2. start docker
It shows 'Docker is staring...'.  Never mind.  Just reboot your computer.  Docker is working!

**Comment by maccth** [comment] 2018-01-17 20:37
Hello!
I'm having the same issues. I've checked `~/Library/Group\ Containers/group.com.docker/settings.json` and there is no `"/"` in the `filesharingDirectories` entry.
I've tried the other suggested solutions on this page such as uninstalling, reinstalling, and then restarting and they haven't worked either.

Any help would be very much appreciated, thanks in advance!

My DID is `177A0653-8038-4EC9-9CD2-2209CBD253E3` and the diagnostic is:
```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/177A0653-8038-4EC9-9CD2-2209CBD253E3/20180117-203402.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/christophermacca/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/christophermacca/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/christophermacca/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/christophermacca/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by gtardif** [comment] 2018-01-17 23:17
Hi @maccth, 
from the diagnostics the issue you're having is actually a duplicate of #2383.
If you get a chance, can you uninstall and then try this test build: https://download-stage.docker.com/mac/pr/21935/Docker.dmg.
Keep in mind this is a test build. Ignore any update it might propose, and after the test you will have to reinstall an Edge or Stable version to get proper updates again.
Let us know if this works (or upload diagnostics if not) ; if this works fine we'll integrate this fix in a proper release soon.

**Comment by halo** [comment] 2018-01-18 11:11
@gtardif I can confirm that the edge version `7.12.0-ce-mac49 (21935)` which you just posted solves the issue and Docker starts properly.

Earlier I tried to 
- reset docker
- uninstall and reinstall
- use the uninstall.sh script
- reboot the mac
- edit `settings.json`

But none of those worked. So whatever you did there - thank you! 😌

**Comment by cdrlee** [comment] 2018-01-18 11:19
+1 same issue, fresh install, mac 10.13.2

**Comment by achal272** [comment] 2018-01-18 12:43
rm -rf ~/Library/Group\ Containers/group.com.docker/ ~/Library/Containers/com.docker.docker ~/.docker

This process by @lunaczp solved my issue. I didn't have to reboot my computer. It just started, almost magically.

**Comment by maccth** [comment] 2018-01-22 14:00
@gtardif That worked for me - thanks!

**Closed** 2018-01-22 19:30 UTC
Labels: status/0-triage

**Comment by uushaggy** [comment] 2018-02-18 14:39
hmmm...had to execute docker from cli as root:

sudo /Applications/Docker.app/Contents/MacOS/Docker &

Now it works!

**Comment by maludwig** [comment] 2018-02-27 17:03
On OSX, my laptop battery is kinda sketch and when I am on battery, it has a 1% chance of randomly turning off every hour. I suspect this is a problem with a touch or a lock file that's not being cleaned up.

Tried "rm -rf ~/.docker", nope.
Tried "rm -f ~/Library/Containers/com.docker.docker/Data/task.lock", nope.
Tried "mv ~/Library/Containers/com.docker.docker/Data /tmp/DockerData", VICTORY!
But then I moved it back "mv /tmp/DockerData ~/Library/Containers/com.docker.docker/Data", and disturbingly, it just started just fine...

Not sure what this means. I'll bookmark this Issue for next time my laptop crashes and let you guys know what else I find.

**Comment by maludwig** [comment] 2018-02-27 21:53
Battery died again.
Tried these, in order:
```
mkdir /tmp/troubleshooting/
cd ~/Library/Containers/com.docker.docker/Data
mv * /tmp/troubleshooting/
mv /tmp/troubleshooting/com.docker.driver.amd64-linux ./
# Failed to launch, problem must be in com.docker.driver.amd64-linux
cd com.docker.driver.amd64-linux
rm Docker.qcow2
# Docker starts
```

Looks like all you need to do is erase every image you've got on your machine...and cry...
```
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
```

**Comment by BrendonW** [comment] 2018-02-27 23:02
There is an attitude where nothing in containers should be important... which is unfortunate. I think some of us using containers to do development end up with a lot of state in containers and images that is a pain to recreate... so being able to recover containers & images from a backup would be very, very useful. 

If anybody knows how to pull images and containers out of backup files... I'd love to know.

**Comment by akimd** [comment] 2018-03-06 13:57
@BrendonW Sorry about that, be sure that we are _not_ happy about asking you to start anew.  However, bugs have been fixed, and if you still experience them _with recent versions_ (eg., https://download.docker.com/mac/edge/23022/Docker.dmg), then open new issues.  Thanks!

**Comment by SeanLee97** [comment] 2019-10-12 06:49
all suggestions can`t solve the problem on my machine: macOS Mojave (version 10.14)

when I started docker desktop, failed  and reported:
```
Fatal Error
StartAll failed: cannot start /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux: fork/exec /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux: no such file or directory
```

I tried to reset docker to factory defaults, reset my machine, reinstall docker. but all were failed.

**Comment by Spacebody** [comment] 2019-10-15 09:33
@SeanLee97 I also have the same problem.

**Comment by SeanLee97** [comment] 2019-10-15 10:29
@Spacebody I have solved the issue by installing the latest [edge](https://download.docker.com/mac/edge/Docker.dmg) version.

**Comment by hao031410** [comment] 2019-10-15 11:31
> @Spacebody I have solved the issue by installing the latest [edge](https://download.docker.com/mac/edge/Docker.dmg) version.

thanks, i have solved as you say!

**Comment by Spacebody** [comment] 2019-10-18 15:01
> @Spacebody I have solved the issue by installing the latest [edge](https://download.docker.com/mac/edge/Docker.dmg) version.

Thanks!
