### ISSUE TITLE
Startup Problem when there isn't Internet Connection

### ISSUE THREAD

**Issue by andresnatanael** [docker/for-mac#554] opened 2016-09-08 18:33 UTC
### Information

Diagnostic ID: EB6AFE2E-34AA-4617-B849-D79863CDC40C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/asoria/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/asoria/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/asoria/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment] 2016-09-12 18:10
Unable to reproduce. It's working on the latest beta. 
Can you try resetting to factory defaults? It should solve this problem. 

Closing for now.

**Closed by mchiang0610** 2016-09-12 18:10 UTC
