### ISSUE TITLE
macOS beta kill docker for mac

### ISSUE THREAD

**Issue by geminiyellow** [docker/for-mac#364] opened 2016-08-19 03:38 UTC
### Steps to reproduce

1. Check for Update
2. Download Update
3. Install
4. Die

### Expected behavior

install and relaunch

### Actual behavior

error box

### Information

```
Diagnostic ID: 07F190F6-E819-4A77-8319-50B18DB4CAE7
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by dsheets** [comment] 2016-08-19 12:42
This is a duplicate of #202.

**Closed by dsheets** 2016-08-19 12:42 UTC

**Comment by djs55** [comment] 2016-09-15 16:16
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by samoht** [comment] 2016-10-12 16:47
Detected symptom of problem 'assertion-failed' in ED507C23-6D50-42B8-9C71-6FBE2F698B77/20160820-135929.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug 20 13:49:58 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: VM: 2016-08-19 06:23:13 +0000 UTC daemon.info vsudd: 709 Done. read: 110 written: 99
Aug 20 13:50:03 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: VM: 2016-08-19 06:23:19 +0000 UTC daemon.info vsudd: Connection 710 to: 2376 from: 00000000
Aug 20 13:50:03 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: VM: 2016-08-19 06:23:19 +0000 UTC daemon.info vsudd: 710 Done. read: 100 written: 145
Aug 20 13:50:05 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug 20 13:50:05 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=7d77f855-d57a-49e0-ab0f-93c0ae2f74e8,path=/Users/ckeyer/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/ckeyer/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Aug 20 13:50:05 C Docker[com.docker.driver.amd64-linux][61811] <Notice>: Interface will have uuid 7d77f855-d57a-49e0-ab0f-93c0ae2f74e8
```
