### ISSUE TITLE
Docker for Mac - client does not respect macOS DNS resolver

### ISSUE THREAD

**Issue by stepanstipl** [docker/for-mac#988] opened 2016-11-25 17:40 UTC
### Expected behavior

Docker pull should be fast.

### Actual behavior

Docker pull hangs for about 20 seconds and only then sends request to docker daemon.

### Information

Docker client is trying to resolve docker registry DNS before dispatching request to docker daemon and it does not respect macOS dns resolver correctly.

In my case I have DNS configured correctly for Docker VM (via record in ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/hosts), but docker client is unable to resolve the DNS which is configured via record in /etc/resolver/my.domain only for specific domain.

Output of scutil --dns:
```
resolver #9
  domain   : my.domain
  nameserver[0] : 10.50.16.2
  flags    : Request A records
  reach    : Reachable
```

This typically happens when Golang binary is compiled withou `CGO_ENABLED=1`.

### Steps to reproduce the behavior

1. You need Docker registry, IP of which is resolvable only via specific DNS server, let's assume `registry.my.domain` with IP `1.2.3.4`, and DNS server running at `192.168.0.1` for this example.
2. Configure Moby to resolve this correctly via adding line `1.2.3.4 registry.my.domain` into `~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/host`, commit & restart docker
3. Configure macOS to resolve records for `my.domain` via given DNS server by creating file `/etc/resolver/my.domain` with content `nameserver 1.2.3.4`
4. Pull image form registry `docker pull registry.my.domain/alpine`.

You'll see docker client hanging for about 20 secs while trying to resolve DNS name (without success) before even dispatching request to docker daemon inside the VM.

I can see actually 2 issues here - Docker client does not need to, nor should, do any DNS resolution before dispatching the request and when it does, it's not respecting native macOS resolver.

**Comment by djs55** [comment] 2016-12-22 13:05
Related to https://github.com/docker/for-mac/issues/974

**Comment by djs55** [comment] 2016-12-22 14:04
Thanks for the report. Over the next few releases we hope to improve the DNS support in Docker for Mac. I've escalated this to the Docker for Mac networking team -- once we support `/etc/resolver` properly on the server-side then we'll take a look at the client.

**Comment by samoht** [comment] 2017-01-31 16:18
This should now be fixed in both the beta and stable channels. Please re-open the issue (or open a new issue with a fresh diagnostic ID) if that's not the case. Thanks again for you report!

**Comment by djs55** [comment] 2017-05-09 11:20
I'm having difficulty reproducing this DNS issue with the latest edge `Version 17.05.0-ce-rc1-mac8 (16582)`. Could you try to reproduce?

If it still reproduces, could you try:
```
GODEBUG=netdns=1 docker pull registry.my.domain/ubuntu
```
and then
```
GODEBUG=netdns=cgo+1 docker pull registry.my.domain/ubuntu
```
Thanks!

**Comment by gtardif** [comment] 2017-05-24 13:24
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Closed by gtardif** 2017-05-24 13:24 UTC
Labels: area/network, kind/bug, status/0-more-info-needed, status/1-acknowledged
