### ISSUE TITLE
7D1525D7-38F5-4663-91DA-70F3A277620D

### ISSUE THREAD

**Issue by reisfrancislei** [docker/for-mac#1357] opened 2017-02-28 19:55 UTC
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Docker for Mac: version: 1.13.1-beta42 (2ffb2b491)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/7D1525D7-38F5-4663-91DA-70F3A277620D/20170228-165710.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by seehuhn** [comment] 2017-03-04 00:15
This may be another duplicate of issue #1337 .

**Comment by seehuhn** [comment] 2017-03-04 17:12
Maybe this is the same problem as in issue docker/docker#31487 ?

**Comment by MagnusS** [comment] 2017-03-08 14:51
Thanks for the report @reisfrancislei. Unfortunately the diagnose tool was unable to upload your logs. The upload problem may have been temporary, so it may help to try to run Diagnose & Upload again.

Do you still have this issue with the latest version of Docker for Mac (17.03.0-ce-mac2)?

**Comment by djs55** [comment] 2017-03-23 10:19
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Closed by djs55** 2017-03-23 10:19 UTC
Labels: osx/10.12.x, status/0-more-info-needed, status/0-triage, version/beta42
