### ISSUE TITLE
Fatal ErrorIllegal instruction exception

### ISSUE THREAD

**Issue by moqimoqidea** [docker/for-mac#5464] opened 2021-03-16 09:53 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 21B19EB6-4D4D-467F-AF2C-543096C3676F/20210316094220

### Expected behavior

Docker Desktop running normally.

### Actual behavior

Docker Desktop show "Fatal Error illegal instruction exception" again and again.

### Information

  - macOS Version: 11.2.3
  - mac: 15-inch, 2018, Intel i9
  - Docker Desktop Version: 3.2.1(61626)
  - Docker Engine: 20.10.5
  - Is it reproducible? yes
  - Is the problem new? yes

### Steps to reproduce the behavior

  1. start docker desktop
  2. fatal error appear.
  3. click 'reset docker to factory defaults'
  4. docker show factory reset success.
  5. docker restart
  6. loop to 1

<img width="598" alt="docker_desktop_fatal_error_illegal_instruction_exception" src="https://user-images.githubusercontent.com/39821951/111289854-888fe680-8680-11eb-87b8-f0dac35ae13c.png">

**Comment by stephen-turner** [comment] 2021-03-16 10:36
Thanks, closing as dupe of #5459.

**Closed by stephen-turner** 2021-03-16 10:36 UTC
Labels: version/3.2.1
