### ISSUE TITLE
Remote Repository pull is not working

### ISSUE THREAD

**Issue by willisweb** [docker/for-mac#5152] opened 2020-12-17 18:33 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD90ADC0-B546-49B3-87FB-13404DBF5E26/20201217181045

### Expected behavior
When you click on the 'Pull' button an image should be pulled from remote registry
### Actual behavior
Clicking the button jumps you to the 'Local' images view
### Information

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac: version… AppleSilicon-Preview7 (first noticed on Preview5)

```

### Steps to reproduce the behavior

1. Go to the Images menu on the left and select the 'Remote repositories'.
2. Connect to docker hub, see the list of images. 
3. As you roll over each of them two buttons appear, 'View in hub' and 'Pull'. 
4. Click 'Pull' the window view just jumps to the 'Local' tab and the remote image is not pulled.

You can pull successfully from the terminal. Once the image is pulled in terminal it then appears on the Docker Desktop Local tab.

**Comment by willisweb** [comment] 2020-12-17 18:34
This was also confirmed by two others on the Slack #dev-preview-program channel

**Comment by alistanis** [comment] 2020-12-18 00:37
I was one of those that commented there as well. I had problems logging in and pulling from a private repository:

`docker login --username alistanis
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by vifer** [comment] 2021-01-05 13:50
We are facing the same issue here, We aren't able to pull images from a private remote repository.

**Comment by ashmckenzie** [comment] 2021-01-13 03:09
I see the following on my M1:

```sh
$ docker pull docker/getting-started:latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

and by chance, I disabled my VPN (NordVPN) and things magically started working again:

```sh
$ docker pull docker/getting-started:latest
latest: Pulling from docker/getting-started
5f621e34cdf4: Pull complete
d1746659b915: Pull complete
6b3fae0121ad: Pull complete
e4b6f618dd36: Pull complete
42acf67661e8: Pull complete
17f967310751: Pull complete
04aef298f643: Pull complete
Digest: sha256:b821569034e3b5fae03b40e64a866017067f3bf17effe185b782bdbf02179528
Status: Downloaded newer image for docker/getting-started:latest
docker.io/docker/getting-started:latest
```

**Comment by magicshui** [comment] 2021-01-13 06:11
facing the same issue when fetch private registry's docker image.

```
Error response from daemon: Get https://docker.DOMAIN_OF_PRIVATE_REGISTRY.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by alistanis** [comment] 2021-01-13 06:26
@ashmckenzie I observed that behavior as well for images off of Docker Hub, but private repositories still fail to pull for me (as login doesn't work). I suspect this is probably a known issue and related to their handling of dns/network translation but it's still good for us to document everything 👍

**Comment by t1m0** [comment] 2021-01-20 06:05
Hi,
I'm facing the same Problem on my Macbook 13" with M1.
Disabling my VPN didn't help. 
I also tried changing Proxy and DNS (as recommended in other issues)- without success.

Anything else I can try?

**Comment by thomasphilibert** [comment] 2021-01-20 15:17
Just wait for a new update of Docker.

**Comment by omh1280** [comment] 2021-01-20 16:18
Closing because this will be fixed in next update

**Comment by lastcosmonaut** [comment] 2021-01-26 08:47
Try this workaround:
https://github.com/lastcosmonaut/docker-m1-vpn-workaround

**Comment by t1m0** [comment] 2021-01-26 09:04
Hi @lastcosmonaut,
thanks for sharing the workaround.
I tried it, but the workaround did not work for me.

ifconfig showed the following
`utun2: flags=80d1<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST> mtu 1160
	inet 10.170.83.213 --> 10.170.83.213 netmask 0xfffffe00 `

So I kept the vpn.sh with `export UTUN_INTF="utun2"`

**Comment by t1m0** [comment] 2021-02-10 05:48
Is anyone aware if there is a fix for this in the pipeline and until when we can expect it in another preview?
As of now I haven't seen a timeline for M1 Support nor a fix for this issue?

**Comment by stephen-turner** [comment] 2021-03-26 16:39
Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

Also we have too many tickets about VPNs, so I'm going to resolve this one as a dupe of #5208.

**Closed by stephen-turner** 2021-03-26 16:39 UTC
Labels: area/m1, version/0.0.0
