### ISSUE TITLE
com.docker.hyperkit process has constant 120% CPU load after restart

### ISSUE THREAD

**Issue by fredfredfred** [docker/for-mac#1344] opened 2017-02-27 08:54 UTC
### Expected behavior

Low or normal CPU load for all docker related processes if no docker images is up and running. 

### Actual behavior

- com.docker.hyperkit process has constant 120% CPU load after restart of Mac and after update to latest beta version (see below). 
- No docker containers are running (docker ps shows nothing)
- Restarting docker does not finish (Menu icon stays orange)

### Information
Version:
Version 17.03.0-ce-rc1-mac1 (15471)
Channel: beta
51beb3eed3

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.0-ce-rc1-mac1 (51beb3eed)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/F73C8B48-6A7E-4364-A438-D77C6D1D45FD/20170227-094247.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
Sorry, nothing here. Just restarted my Mac.
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Upgrade to 17.03.0-ce-rc1-mac1 (51beb3eed)
  2. Start docker
  3. Restart docker (takes forever)
  4. Quit docker from the menu... hyperkit process is still running => killed it and will try again
  5. Killing the hyperkit process and restarting docker helped. Is now up and running with normal CPU

**Comment by fredfredfred** [comment] 2017-02-27 09:07
Some logs, if that helps:
=================== system.log ============================
2017-02-27 09:17:22,448 Docker[500]: VM started at 2017-02-27 09:17:22 +0100 CET
2017-02-27 09:22:12,000 kernel[0]: process com.docker.hyper[508] caught causing excessive wakeups. Observed wakeups rate (per sec): 150; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45009
2017-02-27 09:22:16,527 spindump[647]: Saved wakeups_resource.diag report for com.docker.hyperkit version ??? (???) to /Library/Logs/DiagnosticReports/com.docker.hyperkit_2017-02-27-092216_workhorse.wakeups_resource.diag
2017-02-27 09:41:58,979 Docker[501]: sending SIGTERM to com.docker.hyperkit pid 508
2017-02-27 09:41:58,982 Docker[500]: VM shutdown at 2017-02-27 09:41:58 +0100 CET
2017-02-27 09:42:00,522 Docker[477]: Analytics: Sent actionRestart event.
2017-02-27 09:42:26,773 Docker[477]: Analytics: Sent actionMenuCheckForUpdate event.
2017-02-27 09:42:43,361 Docker[477]: TextView: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
2017-02-27 09:42:43,753 Docker[477]: Analytics: Sent actionMenuFeedback event.
2017-02-27 09:42:47,233 Docker[1392]: EOF reading packet from Unix domain socket: closing
2017-02-27 09:42:47,234 Docker[1392]: Failed to read hello from client
2017-02-27 09:42:47,234 Docker[499]: Using protocol TwoThousandU msize 8215
2017-02-27 09:43:01,867 Docker[477]: WizardMessage: docker-diagnose exited with status code 0
2017-02-27 09:45:16,515 Docker[477]: Analytics: Sent actionMenuAbout event.
2017-02-27 09:54:30,761 Docker[477]: HyperkitLinux: Closing com.docker.osx.hyperkit.linux wathdog pipe
2017-02-27 09:54:30,761 Docker[495]: EOF on watchdog pipe: shutting down
2017-02-27 09:54:30,761 Docker[495]: Received SIGTERM, shutting down
2017-02-27 09:54:30,761 Docker[495]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 501)
2017-02-27 09:54:30,761 Docker[495]: Signal terminated to com.docker.driver.amd64-linux (pid 501)
2017-02-27 09:54:30,765 Docker[477]: AppDelegate: applicationWillTerminate
2017-02-27 09:55:11,736 Docker[498]: Fatal unexpected exception: Socket.Closed
2017-02-27 09:55:11,736 Docker[501]: Hypervisor subprocess has shutdown
2017-02-27 09:55:11,737 Docker[495]: Reap com.docker.osxfs (pid 498): exit status 1
2017-02-27 09:55:11,748 Docker[500]: VM shutdown at 2017-02-27 09:55:11 +0100 CET
2017-02-27 09:55:11,749 Docker[495]: Reap com.docker.driver.amd64-linux (pid 501): exit status 0
2017-02-27 09:55:11,803 Docker[495]: Stop 2 children with order 2: com.docker.osxfs (pid 498), com.docker.slirp (pid 499)
2017-02-27 09:55:11,804 Docker[495]: Signal terminated to com.docker.slirp (pid 499)
2017-02-27 09:55:11,806 Docker[495]: Reap com.docker.slirp (pid 499): signal: terminated
2017-02-27 09:55:11,904 Docker[495]: Stop 1 children with order 3: com.docker.osx.hyperkit.linux (pid 500)
2017-02-27 09:55:11,904 Docker[495]: Signal terminated to com.docker.osx.hyperkit.linux (pid 500)
2017-02-27 09:55:11,906 Docker[495]: Reap com.docker.osx.hyperkit.linux (pid 500): signal: terminated
2017-02-27 09:55:12,008 Docker[495]: Stop 1 children with order 4: com.docker.db (pid 497)
2017-02-27 09:55:12,008 Docker[495]: Signal terminated to com.docker.db (pid 497)
2017-02-27 09:55:12,011 Docker[495]: Reap com.docker.db (pid 497): exit status 1
2017-02-27 09:56:48,265 Docker[1675]: CrashReport: stderr redirected to /var/folders/6q/t1wyc69d6b5485m04sywfhg40000gn/T/Dockererr.txt
===============================================

==================== hyperkit dump ===========================
Date/Time:       2017-02-27 09:17:13 +0100
OS Version:      Mac OS X 10.11.6 (Build 15G1217)
Architecture:    x86_64
Report Version:  19

Command:         com.docker.hyperkit
Path:            /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit
Version:         ??? (???)
Parent:          com.docker.driver.amd64-linux [501]
Responsible:     Docker [477]
PID:             508

Event:           wakeups (microstackshots only)
Wakeups:         150 wakeups per second for 300 seconds
Duration:        300.00s
Steps:           298

Hardware model:  MacBookPro11,5
Active cpus:     8

Fan speed:       3666 rpm


Powerstats for:  com.docker.hyper [508]
UUID:            02A600CB-8C63-3B89-9C62-C63473779FF9
Start time:      2017-02-27 09:17:14 +0100
End time:        2017-02-27 09:22:12 +0100
Parent:          com.docker.drive
Responsible:     Docker
Microstackshots: 273 samples (91%)
Primary state:   248 samples Non-Frontmost App, Kernel mode, Thread QoS Legacy
User Activity:   0 samples Idle, 273 samples Active
Power Source:    0 samples on Battery, 273 samples on AC
  160 thread_start + 13 (libsystem_pthread.dylib) [0x7fff8e51d351]
    160 _pthread_start + 168 (libsystem_pthread.dylib) [0x7fff8e51f91a]
      160 _pthread_body + 131 (libsystem_pthread.dylib) [0x7fff8e51f99d]
        117 vcpu_thread + 1215 (com.docker.hyperkit) [0x106f38bbe]
          71  xh_vm_run + 4707 (com.docker.hyperkit) [0x106f1d844]
            62  vmx_run + 364 (com.docker.hyperkit) [0x106f12617]
              62  hv_vcpu_run + 16 (Hypervisor) [0x1073650b7]
                4   <User mode>
            2   vmx_run + 6989 (com.docker.hyperkit) [0x106f13ff8]
              2   <User mode>
            2   vmx_run + 383 (com.docker.hyperkit) [0x106f1262a]
              2   vcpu_read_vmcs_id + 31 (Hypervisor) [0x107365997]
                2   <User mode>
            1   DYLD-STUB$$hv_vmx_read_capability + 6 (com.docker.hyperkit) [0x106f3c59c]
              1   <User mode>
            1   vmx_run + 1470 (com.docker.hyperkit) [0x106f12a69]
              1   hv_vmx_vcpu_read_register + 4 (Hypervisor) [0x10736510f]
                1   <User mode>
            1   vmx_run + 4564 (com.docker.hyperkit) [0x106f1367f]
              1   <User mode>
            1   vmx_run + 8922 (com.docker.hyperkit) [0x106f14785]
              1   vlapic_update_ppr + 106 (com.docker.hyperkit) [0x106f189bc]
                1   <User mode>
            1   hv_vmx_vcpu_write_msr + 376 (Hypervisor) [0x10736562c]
              1   <User mode>
          45  xh_vm_run + 4725 (com.docker.hyperkit) [0x106f1d856]
            45  vcpu_require_state + 15 (com.docker.hyperkit) [0x106f1b982]
              35  vcpu_set_state + 50 (com.docker.hyperkit) [0x106f1b547]
                34  __psynch_mutexwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cde6]
                1   _pthread_mutex_lock_wait + 34 (libsystem_pthread.dylib) [0x7fff8e51fe13]
                  1   <User mode>
              7   pthread_mutex_lock + 84 (libsystem_pthread.dylib) [0x7fff8e51d4b0]
                7   <User mode>
              1   pthread_mutex_lock + 57 (libsystem_pthread.dylib) [0x7fff8e51d495]
                1   <User mode>
              1   vcpu_set_state + 8 (com.docker.hyperkit) [0x106f1b51d]
                1   <User mode>
              1   pthread_mutex_lock + 26 (libsystem_pthread.dylib) [0x7fff8e51d476]
                1   <User mode>
          1   xh_vm_run + 1576 (com.docker.hyperkit) [0x106f1cc09]
            1   __psynch_cvwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cdb6]
        42  vcpu_thread + 1192 (com.docker.hyperkit) [0x106f38ba7]
          42  vmexit_inout + 311 (com.docker.hyperkit) [0x106f37aa9]
            39  lpc_uart_io_handler + 136 (com.docker.hyperkit) [0x106f2a532]
              38  uart_write + 23 (com.docker.hyperkit) [0x106f34975]
                38  __psynch_mutexwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cde6]
              1   uart_write + 504 (com.docker.hyperkit) [0x106f34b56]
                1   __psynch_mutexdrop + 10 (libsystem_kernel.dylib) [0x7fff9f94cdce]
            3   lpc_uart_io_handler + 51 (com.docker.hyperkit) [0x106f2a4dd]
              2   uart_read + 20 (com.docker.hyperkit) [0x106f34d6a]
                2   __psynch_mutexwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cde6]
              1   uart_read + 341 (com.docker.hyperkit) [0x106f34eab]
                1   lpc_uart_intr_assert + 32 (com.docker.hyperkit) [0x106f2a45c]
                  1   vatpic_set_irqstate + 151 (com.docker.hyperkit) [0x106f15ef1]
                    1   vatpic_notify_intr + 245 (com.docker.hyperkit) [0x106f16100]
                      1   <User mode>
        1   callout_thread_func + 236 (com.docker.hyperkit) [0x106f1e799]
          1   vlapic_callout_handler + 92 (com.docker.hyperkit) [0x106f1875f]
            1   vcpu_notify_event + 46 (com.docker.hyperkit) [0x106f1b8c1]
              1   __psynch_mutexwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cde6]
  113 start + 1 (libdyld.dylib) [0x7fff8ca685ad]
    98  main + 11643 (com.docker.hyperkit) [0x106f3bbcc]
      94  uart_drain + 31 (com.docker.hyperkit) [0x106f354b0]
        94  __psynch_mutexwait + 10 (libsystem_kernel.dylib) [0x7fff9f94cde6]
      2   __psynch_mutexdrop + 10 (libsystem_kernel.dylib) [0x7fff9f94cdce]
      2   uart_drain + 74 (com.docker.hyperkit) [0x106f354db]
        2   read + 10 (libsystem_kernel.dylib) [0x7fff9f94e362]
    15  kevent + 10 (libsystem_kernel.dylib) [0x7fff9f94deca]

  Binary Images:
         0x106deb000 -        0x106f93fff  com.docker.hyperkit (0) <02A600CB-8C63-3B89-9C62-C63473779FF9> /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit
         0x107364000 -        0x107368fff  com.apple.Hypervisor 1.0 (1) <0E462CB0-61C2-3792-987F-BDF81390C641> /System/Library/Frameworks/Hypervisor.framework/Versions/A/Hypervisor
      0x7fff8ca65000 -     0x7fff8ca68ffb  libdyld.dylib (360.22) <F103B2FB-D383-38CB-992A-E16BDCB00A03> /usr/lib/system/libdyld.dylib
      0x7fff8e51c000 -     0x7fff8e525ff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
      0x7fff9f936000 -     0x7fff9f954ff7  libsystem_kernel.dylib (3248.60.11.2.1) <19B06617-EDC1-3925-8A09-BC775F3D6A08> /usr/lib/system/libsystem_kernel.dylib
===============================================

**Comment by MagnusS** [comment] 2017-03-10 17:39
Thanks for the report @fredfredfred. It is not clear from the logs what happened, but from the contents of `console-ring` it looks like something was spamming the console in the VM. I've notified the dev team about what happened, but as it is hard to debug without more information we may have to add more details to the debugging info in a future release. In the mean time I'll close this issue as it seems to have been resolved by a restart. Please open a new issue (or reopen this one) if this happens frequently with the latest version of Docker for Mac. If there is a reliable way to reproduce it it could also be very helpful for debugging.

**Closed by MagnusS** 2017-03-10 17:39 UTC
Labels: osx/10.11.x, status/0-triage, version/17.03.0-ce-rc1-mac1
