### ISSUE TITLE
Please fix /proc/cpuinfo 

### ISSUE THREAD

**Issue by chadbrewbaker** [docker/for-mac#6512] opened 2022-10-10 14:07 UTC
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: NA

### Expected behavior
cat /proc/cpuinfo on M1 should give the same output that @marcan emits for Ashanti Linux.

I don't care if this is a total hack like --overload-cpuinfo=FILE .

### Actual behavior
```bash
processor	: 0
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint
CPU implementer	: 0x00
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 0
```

### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: Docker version 20.10.17, build 100c701

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
All pass except:
[SKIP] DD0030: is the image access management authorized?
### Steps to reproduce the behavior

cat /proc/cpuinfo

**Comment by chadbrewbaker** [comment] 2022-10-10 15:09
This returns the exact Apple CPU model. I couldn't find an OSX command fully equivalent to /proc/cpuinfo.
```bash
sysctl -a machdep.cpu.brand_string
#machdep.cpu.brand_string: Apple M1
```

**Comment by chadbrewbaker** [comment] 2022-10-10 15:18
https://github.com/klauspost/cpuid/pull/105/files

This is what the Go folk are using to pull cpuinfo for Apple Silicon chips.

**Comment by chadbrewbaker** [comment] 2022-10-10 15:23
https://github.com/dotnet/runtime/pull/62958/files

.Net folk are also dumping this for CPU features.
```bash
sysctl -a  hw.optional
```
hw.optional.arm.FEAT_FlagM: 1
hw.optional.arm.FEAT_FlagM2: 1
hw.optional.arm.FEAT_FHM: 1
hw.optional.arm.FEAT_DotProd: 1
hw.optional.arm.FEAT_SHA3: 1
hw.optional.arm.FEAT_RDM: 1
hw.optional.arm.FEAT_LSE: 1
hw.optional.arm.FEAT_SHA256: 1
hw.optional.arm.FEAT_SHA512: 1
hw.optional.arm.FEAT_SHA1: 1
hw.optional.arm.FEAT_AES: 1
hw.optional.arm.FEAT_PMULL: 1
hw.optional.arm.FEAT_SPECRES: 0
hw.optional.arm.FEAT_SB: 1
hw.optional.arm.FEAT_FRINTTS: 1
hw.optional.arm.FEAT_LRCPC: 1
hw.optional.arm.FEAT_LRCPC2: 1
hw.optional.arm.FEAT_FCMA: 1
hw.optional.arm.FEAT_JSCVT: 1
hw.optional.arm.FEAT_PAuth: 1
hw.optional.arm.FEAT_PAuth2: 0
hw.optional.arm.FEAT_FPAC: 0
hw.optional.arm.FEAT_DPB: 1
hw.optional.arm.FEAT_DPB2: 1
hw.optional.arm.FEAT_BF16: 0
hw.optional.arm.FEAT_I8MM: 0
hw.optional.arm.FEAT_ECV: 1
hw.optional.arm.FEAT_LSE2: 1
hw.optional.arm.FEAT_CSV2: 1
hw.optional.arm.FEAT_CSV3: 1
hw.optional.arm.FEAT_FP16: 1
hw.optional.arm.FEAT_SSBS: 1
hw.optional.arm.FEAT_BTI: 0
hw.optional.floatingpoint: 1
hw.optional.neon: 1
hw.optional.neon_hpfp: 1
hw.optional.neon_fp16: 1
hw.optional.armv8_1_atomics: 1
hw.optional.armv8_2_fhm: 1
hw.optional.armv8_2_sha512: 1
hw.optional.armv8_2_sha3: 1
hw.optional.armv8_3_compnum: 1
hw.optional.watchpoint: 4
hw.optional.breakpoint: 6
hw.optional.armv8_crc32: 1
hw.optional.armv8_gpi: 1
hw.optional.AdvSIMD: 1
hw.optional.AdvSIMD_HPFPCvt: 1
hw.optional.ucnormal_mem: 1
hw.optional.arm64: 1

**Comment by jannau** [comment] 2022-10-10 17:22
This request doesn't make much sense as far as I understand the docker architecture on macos. The reported CPU flags have to be the flags supported by the virtual CPU in the used hypervisor. These are not necessarily identical to the features supported on the host CPU. If there is anything to be changed it needs to be at the hypervisor config. The docker environment must not expose additional features over kernel running in the hypervisor.

**Comment by nicks** [comment] 2022-10-11 21:24
I'm going to mark this as a duplicate of https://gitlab.com/qemu-project/qemu/-/issues/750 (see the discussion there on the technical issues)

**Closed by nicks** 2022-10-11 21:24 UTC
