### ISSUE TITLE
Malloc panic on 18.02.0-ce-rc1-mac50 (22256)

### ISSUE THREAD

**Issue by VojtechVitek** [docker/for-mac#2544] opened 2018-02-01 00:26 UTC
After receiving the latest "unstable" update - `18.02.0-ce-rc1-mac50 (22256)`, I ran into this weird malloc PANIC:

It's probably below Docker itself, somewhere in Golang stdlib, but I thought it might be helpful to report anyway:

```
$ docker run -it alpine:3.4 sh
failed MSpanList_Insert 0x8f2000 0x85cbbde8ace95 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x80e7ab)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff230 sp=0x7ffeefbff200
runtime.MSpanList_Insert(0x847ea8, 0x8f2000)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbff258 sp=0x7ffeefbff230
MHeap_FreeSpanLocked(0x844aa0, 0x8f2000, 0x100)
	/usr/local/go/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbff298 sp=0x7ffeefbff258
MHeap_Grow(0x844aa0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbff2d8 sp=0x7ffeefbff298
MHeap_AllocSpanLocked(0x844aa0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbff318 sp=0x7ffeefbff2d8
mheap_alloc(0x844aa0, 0x1, 0x12, 0x0)
	/usr/local/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbff340 sp=0x7ffeefbff318
runtime.MHeap_Alloc(0x844aa0, 0x1, 0x10000000012, 0x107f9)
	/usr/local/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbff378 sp=0x7ffeefbff340
MCentral_Grow(0x84c818, 0x0)
	/usr/local/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbff3e0 sp=0x7ffeefbff378
runtime.MCentral_CacheSpan(0x84c818, 0x0)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbff418 sp=0x7ffeefbff3e0
runtime.MCache_Refill(0x8ee000, 0x12, 0x0)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbff440 sp=0x7ffeefbff418
runtime.mcacheRefill_m()
	/usr/local/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbff460 sp=0x7ffeefbff440
runtime.onM(0x698ef0)
	/usr/local/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbff468 sp=0x7ffeefbff460
runtime.mallocgc(0x120, 0x565800, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbff518 sp=0x7ffeefbff468
runtime.newobject(0x565800, 0x8ee000)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbff540 sp=0x7ffeefbff518
runtime.newG(0x2b0ca)
	/usr/local/go/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbff558 sp=0x7ffeefbff540
allocg(0x833440)
	/usr/local/go/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbff568 sp=0x7ffeefbff558
runtime.malg(0x8000, 0x833600)
	/usr/local/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbff598 sp=0x7ffeefbff568
runtime.mpreinit(0x833e40)
	/usr/local/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbff5b0 sp=0x7ffeefbff598
mcommoninit(0x833e40)
	/usr/local/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbff5d8 sp=0x7ffeefbff5b0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbff600 sp=0x7ffeefbff5d8
runtime.rt0_go(0x7ffeefbff638, 0x5, 0x7ffeefbff638, 0x0, 0x0, 0x5, 0x7ffeefbff818, 0x7ffeefbff81f, 0x7ffeefbff823, 0x7ffeefbff827, ...)
	/usr/local/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbff608 sp=0x7ffeefbff600
```

**Comment by akimd** [comment] 2018-02-01 14:12
Thanks for the report.  Can you reproduce it each time?  I cannot reproduce it at all.  And indeed, it looks like https://github.com/golang/go/issues/20888 or https://github.com/golang/go/issues/17335.

**Comment by VojtechVitek** [comment] 2018-02-01 17:49
Yeah, I could reproduce it every single time I ran `docker run`. However, after factory-resetting my Docker for Mac, it went away.

**Comment by akimd** [comment] 2018-02-02 15:38
That's weird...

But I guess there's nothing more we can do at this point, so I'll close this issue.  Thanks for the report!

**Closed by akimd** 2018-02-02 15:38 UTC
Labels: status/0-triage, version/18.02.0-ce-rc1-mac50
