### ISSUE TITLE
Docker Preview RC2 Apple Silicon Circle CI build failure

### ISSUE THREAD

**Issue by bkuhlmann** [docker/for-mac#5513] opened 2021-03-27 16:14 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 422782D7-4AF2-4E68-8529-2D6339D029BE/20210327160251

### Expected behavior

I'm expecting the image built on an Apple Silicon behaves the same as the same image built on an Apple Intel machine. Unfortunately, this is not the case.

### Actual behavior

When I build [this image](https://github.com/bkuhlmann/docker-alpine-ruby/blob/main/Dockerfile) on an Apple Silicon machine, I can run and use the image without issue but when uploaded to Docker Hub so I can run within Circle CI, I get the following error:

``` 
CircleCI was unable to run the job runner because we were unable to execute commands in build container.

This typically means that the build container entrypoint or command is terminating the container prematurely, or interfering with executed commands.  Consider clearing entrypoint/command values and try again.
```

Building the same image and uploading to Docker Hub for an Apple Intel machine does not exhibit this behavior at all.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? I couldn't even get Docker Preview to run on Apple Silicon prior to the RC2 release.
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: macOS 11.2.3 (20D91)
  - Docker Desktop Version: 3.3.0 (62345)

### Steps to reproduce the behavior

1. Use an Apple Silicon machine with Docker Preview RC2.
1. Use this [Dockerfile](https://github.com/bkuhlmann/docker-alpine-ruby/blob/main/Dockerfile) to build an image.
1. Release the newly built image to [Docker Hub](https://hub.docker.com/r/bkuhlmann/alpine-ruby). *NOTE: This is currently built on an Apple Intel machine so I can use it.*
1. Attempt to [use this image via Circle CI](https://github.com/bkuhlmann/mac_os-config/blob/main/.circleci/config.yml#L6) and notice you get a [build failure](https://app.circleci.com/pipelines/github/bkuhlmann/mac_os-config/145/workflows/eae596c0-d64e-49b3-8868-8b79399f3b95/jobs/430).

**Comment by StefanScherer** [comment] 2021-03-27 17:26
Hi @bkuhlmann 
Thanks for this ticket and detailed report.
Well, this is not a bug in Docker Desktop RC2 for Apple Silicon, this is the expected behaviour. As you may know the Apple Silicon machines have a different CPU than Intel. It's like two different cars, one uses gasoline and the other Diesel. Docker Desktop on Mac starts a Linux VM, but still one for the matching CPU of the Mac machine.
So, on an Intel Mac you run Linux containers that match `amd64` CPU architecture, on an Apple Silicon Mac you run Linux containers that expect `arm64` CPU architecture.
When you build images on an Apple Silicon machine they will work fine on other Linux machines with an ARM CPU, like the Raspberry Pi 64bit, or cloud machines or baremetal machines with a 64bit ARM CPU.

Most of the CPU's in the cloud are Intel/AMD based machines and this also applies to CircleCI. They have a preview to provide arm/arm64 builds -> https://github.com/CircleCI-Public/arm-preview-docs
As you can see, more and more services in the cloud also adopt ARM CPU's, but maybe you still want to run Intel images and build them on your new Apple Silicon Mac machine.

In Docker Desktop we already have something built in that should help you bridging the gap between these two different CPU architectures.

Docker Desktop is able to run images for a different CPU architecture with the help of the QEMU emulator. You always could build and run images for eg. the Raspberry Pi on an Intel Mac. Now with the Apple Silicon machines it's the other way around that QEMU is used to build and run Intel machines.

The buildx feature is also enabled in Docker Desktop which brings a lot of power to build images for both CPU architectures in parallel. So your users don't have to run the image with an emulator, but they will use the native image that fits the underlying CPU.

Try to build your image on your Mac machine (it should work on both Intel and Apple Silicon, so it doesn't matter where you run it) with the following command:

```
docker buildx build --platform linux/amd64,linux/arm64 -t bkuhlmann/alpine-ruby:latest .
```

or add the `--push` flag to build and push the image:

```
docker buildx build --platform linux/amd64,linux/arm64 -t bkuhlmann/alpine-ruby:latest --push .
```

Welcome to the world of multi-architecture images 😄 

After you have pushed that image you should see both architectures on Docker Hub as well.
Our official images like the `ruby` image that you use already are built for multiple CPU architectures, so it picks the best ruby image for each of the parallel builds.

**Comment by StefanScherer** [comment] 2021-03-27 17:48
I'll close this ticket, but please feel free to comment if you have questions about multi architecture images.

**Closed by StefanScherer** 2021-03-27 17:48 UTC
Labels: area/m1, version/3.3.0

**Comment by bkuhlmann** [comment] 2021-03-27 23:01
:bow: Stefan. Well, this has been a huge eye opener and leveling up experience. I had to get used to how `buildx` works but I think I've got my images building for `linux/amd64` and `linux/arm64` now. I haven't pushed these up to Docker Hub yet but looking forward to doing so.

Thanks for all of the feedback, links, and help on this. This has been great. By the way, is there a way to each Docker Compose to use `buildx`? I was failing to good documentation/examples for this. I even tried switching out `build` with `buildx` in the YAML to no avail. I'm assuming I'm doing something wrong or that this is still too early to be supported by Docker Compose?

**Comment by ocean** [comment] 2021-03-29 01:24
Hi @bkuhlmann , I’ve been having a lot of “fun” with multi-arch images on my M1 MBP, and have been building part of my local dev stack with the `docker buildx build …` set of commands.

However I’m looking at attacking a Compose powered build soon, and so was looking around for docs like you, and found the `docker buildx bake …` command, which seems to enable builds (in parallel even) with the `buildx` BuildKit tool set, allowing multiple architectures, and it reads `docker-compose.yml` files. 

I’ve not tried it yet, but here’s the info for getting it working https://github.com/docker/buildx#buildx-bake-options-target

Wow, that’s a lot of “builds” 😅

**Comment by bkuhlmann** [comment] 2021-03-29 14:40
:bow: *Drew*. Yeah, I spent the entire weekend sorting out my multi-platform builds: [Docker Alpine Base](https://www.alchemists.io/projects/docker-alpine-base) and [Docker Alpine Ruby](https://www.alchemists.io/projects/docker-alpine-ruby). I'm happy with the results as I now have ARM 64 and AMD 64 builds being produced via my Apple Silicon machine. :tada: More work to be done, though.

Thanks for the link. I was digging into `buildx` more this weekend too but was confused by `bake` so will dig into this more as well. :wink:
