### ISSUE TITLE
docker system df reports incorrect reclaimable space

### ISSUE THREAD

**Issue by edarchis** [docker/for-mac#1168] opened 2017-01-20 09:31 UTC
### Expected behavior

docker system df should report the reclaimable space from inactive images:
```
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              51                  33                  10.07 GB              2.1 GB (20%)
```

### Actual behavior

```
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              51                  33                  10.07 GB            -2.431e+09 B (-24%)

```
### Information

  - Diagnostic ID: 9962A50D-A0BC-4536-9D99-ADEE5376A0E3
  - System installed a few versions ago and upgraded along the way
  - Nothing unusual about the installed images. A lot of them have been deleted already, maybe this could be the problem ?

### Steps to reproduce the behavior

No idea, only occurred on my laptop. Open to investigating space usage of various components.

**Comment by dsheets** [comment] 2017-01-20 11:16
This is a duplicate of docker/docker#30257. Please track it there.

**Closed by dsheets** 2017-01-20 11:16 UTC
Labels: area/docker, kind/bug, status/1-acknowledged
