### ISSUE TITLE
A96F4CD5-817F-4427-89D3-655E2AE24200

### ISSUE THREAD

**Issue by jspenc72** [docker/for-mac#699] opened 2016-09-25 16:51 UTC
### Actual behavior
Hard drive space is not freed up when docker images or containers are removed using docker rmi or docker rm
I have tried deleting all images and all containers with no success.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

**Comment by MagnusS** [comment] 2016-09-26 09:43
Thanks for the report. This looks like a duplicate of #371, so I'm closing this issue - please reopen if this is not the case. We are working on a better solution for managing the disk image size.

**Closed by MagnusS** 2016-09-26 09:43 UTC
Labels: area/storage
