### ISSUE TITLE
docker ps hanging

### ISSUE THREAD

**Issue by johnny5v** [docker/for-mac#11] opened 2016-07-29 14:42 UTC
### Expected behavior
docker ps should return immediately
### Actual behavior
docker ps command hangs forever
### Information

Diagnostic ID: F4F5D337-2486-44AE-B5B0-B7A76548E67B
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1.  rebooted machine, still happens
2. reinstalled and rebooted, still happens

**Comment by samoht** [comment] 2016-07-29 14:52
Can you provide more information on what you did before that happens, etc.. It is a bit hard for us to understand your issue and help you if you don't tell us more :-)

**Comment by matthieuauger** [comment] 2016-07-29 16:20
Thanks for your help @samoht,

I have the exact same issue. It appeared several weeks ago (8 maybe). Weird thing is that neither Docker for mac nor docker toolbox are working.

I tried to completely remove my docker installation by following [this guide](https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/) and fully resinstalling docker for mac. Reboot doesn't help either.

Got any tips how I can diagnose further ?

Thank you very much for your help,

```
Diagnostic ID: 592C3F97-F8AA-4884-B967-7AF18817487C
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by samoht** [comment] 2016-08-01 08:44
Does the 🐳 in the menu bar still moving? What status does it report?

**Comment by johnny5v** [comment] 2016-08-01 14:23
if you are asking if there is any animation on the icon, the answer is no, it's static all the time.

**Comment by samoht** [comment] 2016-08-01 15:20
@johnny5v do you have Toolbox installed too? What does `docker version` says? Do you have any `DOCKER_` env variables set in your terminal?

**Comment by dvinov-arivale** [comment] 2016-08-01 21:47
https://github.com/docker/for-mac/issues/56 and https://github.com/docker/for-mac/issues/52 seem to report the same issue.

**Comment by johnny5v** [comment] 2016-08-02 19:48
hi @samoht , the issue seems to be gone after installing docker-toolbox, thank you for your help.

**Comment by dvinov-arivale** [comment] 2016-08-02 20:29
I had had and still have Docker Toolbox installed:

```
Yaros-MacBook:arivale-coach-client ydvinov$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Comment by theunorthodoxdeveloper** [comment] 2016-08-05 08:35
I can confirm that I am having this exact same problem. I have rebooted my machine, and it still happens. I have reinstalled and rebooted my machine and it still happens.

Installing Docker Toolbox did not help either. I can run `docker` but as soon as I give it a command it just hangs, forever. 

When I run the diagnosis, I get the following output:

```
Diagnostic ID: 389BC070-E840-4CB0-8704-758A3B4E438F
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/simonfletcher/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/389BC070-E840-4CB0-8704-758A3B4E438F/20160805-093354/qemu-img-check.stdout 2> /tmp/389BC070-E840-4CB0-8704-758A3B4E438F/20160805-093354/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by djs55** [comment] 2016-09-05 09:46
In the original report it looks like the .qcow2 has become corrupt somehow:
```
Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096
](4096) off=0 len=-36864")
```
There is a known bug whose fix is due to be released this week (beginning 2016-09-05) which could allow 2 hypervisor processes to write to the same .qcow2 file, which is certain to cause corruption, which would manifest like this.

In the short term, the only workaround is to "Whale menu -> Uninstall and reset -> Reset to factory defaults". Unfortunately this removes containers and images so they will need to be rebuilt :(

I'll mark this issue as resolved by the fix which is about to be released, but if it still manifests after this week's update(s) then please create a fresh issue (since the root cause will probably be different)

**Closed by djs55** 2016-09-05 09:46 UTC
Labels: area/startup, kind/bug, version/1.12.0
