### ISSUE TITLE
Notifies "Docker has been updated!" every time i run the application

### ISSUE THREAD

**Issue by nkobber** [docker/for-mac#751] opened 2016-10-06 07:35 UTC
### Expected behavior
Only notify once that the application has been updated

### Actual behavior
Every time i open Docker for Mac it notifies:
Docker has been updated!
New version is 1.12.2-rc1-beta27

### Information
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/72A5CDAA-C8B9-4718-BBEF-49B1E9C18EBD/20161006-093310.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce the behavior
Run the application. It notifies.
Close and reopen the application. It notifies.
Do it again .. It notifies. You get the picture..

**Comment by nkobber** [comment] 2016-10-06 13:38
Reset to factory defaults fixes the issue

**Comment by dsheets** [comment] 2016-10-10 08:47
I believe this is a duplicate of #51. Thanks for your report -- our OS X integration team is working on fixing this issue.

**Closed by dsheets** 2016-10-10 08:47 UTC
Labels: osx/10.12.x, status/0-triage, version/beta27
