### ISSUE TITLE
Login fails when Sign In button is clicked, succeeds when hitting enter in login fields

### ISSUE THREAD

**Issue by rt3me** [docker/for-mac#4113] opened 2019-12-09 20:52 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BFA88F7A-BBD4-4A66-BFAB-389636ED3957/20191209201937

### Expected behavior
Successful login

### Actual behavior
Error in login dialog: Incorrect authentication credentials

### Information
  - Mac Version 10.15.1 (19B88)
  - Docker Version 2.1.0.5 (40693)

### Steps to reproduce the behavior
  1. Use correct login credentials on Docker Desktop macOS
  2. Click 'Sign In' button in Docker Desktop macOS and receive login error
  3. Try the same login information on hub.docker.com
  4. Successfully log in and log out of hub.docker.com
  5. Use correct login credentials on Docker Desktop macOS
  6. Hit enter with the cursor in either the Docker ID or Password field
  7. Successfully log in to Docker Desktop macOS

**Comment by stephen-turner** [comment] 2019-12-10 11:25
Thanks for the report, dupe of #4010. Will be fixed in this week's Edge release.

**Closed by stephen-turner** 2019-12-10 11:25 UTC
Labels: version/2.1.0.5
