### ISSUE TITLE
Proxy settings checkbox

### ISSUE THREAD

**Issue by bsrdjan** [docker/for-mac#966] opened 2016-11-18 08:10 UTC
Just a small feature request for the usability improvement. I need often to activate and deactivate proxy, in Preferences/Advanced tab of the docker OSX client. To activate I have to fill three fields (http, https proxy and no proxy) and when I deactivate to delete them. It would be nice having also a checkbox, to activate and deactivate proxy, not always to copy/paste three proxy strings.

**Comment by dsheets** [comment] 2016-11-18 10:13
Thanks for the feature request. I believe this is a duplicate of #908. Please subscribe to that issue for updates. If you think that #908 does not cover your use case, please feel free to re-open this issue with further explanation. Thanks!

**Closed by dsheets** 2016-11-18 10:13 UTC
