### ISSUE TITLE
Node.js debugging not working

### ISSUE THREAD

**Issue by tinganho** [docker/for-mac#1444] opened 2017-03-18 08:54 UTC
I suspect something happened with node debugging in some later releases of Docker.

It seems like there is something wrong with the debug connection between the debug client on the host with the node.js runtime debug server on a container.

Since, I can run the debug client on a `non-docker-container` environment. I suspect it might be something wrong with Docker.

This is the original issue: 
https://github.com/Microsoft/vscode/issues/22306

**Comment by djs55** [comment] 2017-03-21 16:17
Thanks for your report. I also read the linked vscode issue. Unfortunately I'm not familiar with the workings of vscode or node debugging, so I can only make a few guesses/suggestions.

I notice the `docker-compose.yml` has exposed ports
```
    ports:
      - "3000:3003"
      - "6000:5858"
```
If I'm reading the thread correctly vscode is configured to connect to `localhost:6000` which is forwarded to `container:5858` where hopefully `node` is listening. I recommend running
```
telnet localhost 6000
```
on the host. I don't know what the protocol looks like, but if you see some handshake then it's good evidence that Docker for Mac is working correctly. If the connection is established but then immediately closed then it could *either* be a timeout on a missing handshake, or perhaps more likely the proxy in Docker for Mac failed to connect to the internal container port. In this case it could be because `node` is listening by default on `127.0.0.1`-- that's a common secure default but if it's listening on the *container* localhost it won't be exposable via Docker for Mac. In this case, see if you can change the bind/listen address of `node` inside the container to `0.0.0.0`. It won't be accessible to the outside world unless you expose it via a `ports` declaration. Take care though if you're on an untrusted network -- you may wish to change the `docker-compose.yml` to something like:
```
    ports:
      - "127.0.0.1:6000:5858"
```
to only expose the debug port on `127.0.0.1` on the host (i.e. not accessible to other hosts on your local wifi)

Another possible experiment would be to run a command-line debug client on the host and connect it to `localhost:6000`. If this works then it suggests the problem is in vscode.

Let me know if there's anything else I can do to help. If you can provide simple step-by-step repro instructions then I could give them a try.

**Comment by tinganho** [comment] 2017-03-21 22:02
It seems like `mochajs` the testing lib I use, binds to `127.0.0.1`, I cannot telnet it (Connection closed by foreign host). Though when I run with `node --inspect=0.0.0.0:5858` I can telnet it. Though the debugger does not work.

> Another possible experiment would be to run a command-line debug client on the host and connect it to localhost:6000. If this works then it suggests the problem is in vscode.

Instead of command-line debug I tested the Chrome Devtools locally on my mac without a container. And it works. VSCode is showing an error here locally, which I will report.

Chrome Devtools can connect to a remote container, though it puts itself in a "zoombie" state. Nothing works.

**Comment by djs55** [comment] 2017-03-23 10:06
Thanks for your reply. It sounds to me like the problem is somewhere in VSCode rather than Docker, so I'll close this ticket. Let me know if you find some evidence which suggests a Docker-specific problem.

Thanks for your report and your interest in Docker for Mac!

**Closed by djs55** 2017-03-23 10:06 UTC
Labels: status/0-more-info-needed, status/0-triage
