### ISSUE TITLE
Docker daemon fails to start, ext4 filesystem corruption on vda2

### ISSUE THREAD

**Issue by andyspiers** [docker/for-mac#1150] opened 2017-01-17 12:26 UTC
### Expected behavior

docker works

### Actual behavior

docker doesn't work

docker ps returns:

`Error response from daemon: Bad response from Docker engine`

When probing inside the docker VM with
`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`

I can see that the docker daemon fails to start:

```
/ # service docker restart
 * Stopping docker
 * Starting Docker ...
mount: mounting /host_docker_app/com.docker.driver.amd64-linux/log on /var/log failed: No such file or directory
 [ ok ]
/ # EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670031: comm dockerd: deleted inode referenced: 3670053

/ # service docker status
 * status: crashed
 *
```

docker fails to start because of file system corruption - it expects things to be directories which have been corrupted to files. From /var/log/docker.log:

```
time="2017-01-17T09:46:17.703217338Z" level=debug msg="docker group found. gid: 50"
time="2017-01-17T09:46:17.703670027Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
time="2017-01-17T09:46:17.710913955Z" level=info msg="libcontainerd: new containerd process, pid: 4294"
time="2017-01-17T09:46:17.711945891Z" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
time="2017-01-17T09:46:17.717710488Z" level=debug msg="containerd: read past events" count=0
time="2017-01-17T09:46:17.718907638Z" level=debug msg="containerd: supervisor running" cpus=2 memory=1997 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
time="2017-01-17T09:46:17.719509159Z" level=debug msg="containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock"
time="2017-01-17T09:46:18.714637571Z" level=debug msg="Using default logging driver json-file"
time="2017-01-17T09:46:18.715243388Z" level=debug msg="Golang's threads limit set to 13950"
time="2017-01-17T09:46:18.715678797Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2017-01-17T09:46:18.718929030Z" level=debug msg="Using graph driver aufs"
time="2017-01-17T09:46:18.719370332Z" level=debug msg="Max Concurrent Downloads: 3"
time="2017-01-17T09:46:18.719757995Z" level=debug msg="Max Concurrent Uploads: 5"
time="2017-01-17T09:46:18.732856519Z" level=error msg="Error during layer Store.Cleanup(): lstat /var/lib/docker/aufs/mnt/58074f22a1202295ca27688c1e543f16853652cc660e70c80901bfc375527a41: structure needs cleaning"
time="2017-01-17T09:46:18.733330784Z" level=debug msg="Cleaning up old mountid : start."
time="2017-01-17T09:46:18.733808345Z" level=fatal msg="Error starting daemon: readdirent: not a directory"
```

I had some dmesg output showing ext4 corruption on /dev/vda2 but I lost it. Here's something approximate of what it looked like:

```
Jan 12 10:01:16 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 10:01:16 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 10:24:31 moby kernel: EXT4-fs (vda2): error count since last fsck: 80
Jan 12 10:24:31 moby kernel: EXT4-fs (vda2): initial error at time 1483647781: ext4_mb_generate_buddy:758
Jan 12 10:24:31 moby kernel: EXT4-fs (vda2): last error at time 1484215276: ext4_lookup:1583: inode 3670022
Jan 12 12:01:15 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 12:01:15 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 14:01:14 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 14:01:14 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 16:01:13 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 12 16:01:13 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 13 10:30:11 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
Jan 13 10:30:11 moby kernel: EXT4-fs error (device vda2): ext4_lookup:1583: inode #3670022: comm dhcpcd: deleted inode referenced: 3670020
```

It seems unusual that vda2 be mounted RW at 3 separate mount points. Could this be relevant?

```
/ # mount | grep vda
/dev/vda2 on /var type ext4 (rw,relatime,data=ordered)
/dev/vda2 on /run/log type ext4 (rw,relatime,data=ordered)
/dev/vda2 on /var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
```

### Information

Diagnostic ID: DBE461B5-1E9A-41CD-B2BE-3134AE60F9ED

This can only be fixed by wiping the helper VM (with "reset to factory defaults")

### Steps to reproduce the behavior

This happens on its own approximately every week (several times per month) and has been occuring for the last few months.

It's worth pointing out that I rarely restart my laptop and just use suspend/resume. At least once per working day, sometimes several times.

I generally just use one-shot containerized commands which take at most a few minutes to run. I don't leave any containers running in the background.

**Comment by dsheets** [comment] 2017-01-17 16:20
I see several critical errors in your log files. It looks like there were crashes in the process that manages the hypervisor and the virtual block device driver. This looks like the same issue as #1143. Thank you for your report, it has helped us find a pattern of behavior and prioritize fixing this issue. I'm going to close this issue as a duplicate of #1143 to help us manage the issue tracker better. Please subscribe to that issue for further updates and, if you'd like to help out, follow @ijc25's instructions there.

Thanks!

**Closed by dsheets** 2017-01-17 16:20 UTC
Labels: status/0-triage
