### ISSUE TITLE
Docker for Mac

### ISSUE THREAD

**Issue by YRM64** [docker/for-mac#2729] opened 2018-03-26 21:22 UTC
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment] 2018-03-27 07:51
dupe of #2730 i guess, closing

**Closed by pgayvallet** 2018-03-27 07:51 UTC
