### ISSUE TITLE
Files mounted via volumes are empty after saving a file from another volume

### ISSUE THREAD

**Issue by epoberezhny** [docker/for-mac#5045] opened 2020-11-04 17:26 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CAB63B58-3347-4160-B5CF-C896827216A4/20201104172308

### Expected behavior
Files mounted via volumes are **NOT** empty after saving a file from another volume
### Actual behavior
Files mounted via volumes are empty after saving a file from another volume
### Information

The problem appear with the 2.5.0.0 update
  - macOS Version: 10.15.7
### Steps to reproduce the behavior

  1. Clone https://github.com/epoberezhny/issue_example
  2. `docker-compose run --rm app bash`
  3. `echo 'added' >> dir_1/file_2.txt` from host machine
  4. See that `file_1.txt` inside the container is empty and has strange permissions `-rwxr-xr-x`

**Comment by thischarmingsam8** [comment] 2020-11-04 18:45
I am also having this issue, macOS Version 10.15.3

**Comment by Daanvdk** [comment] 2020-11-05 10:07
Same issue, macOS Version 10.15.5, only occured in 2.5.0.0.

**Comment by stephen-turner** [comment] 2020-11-05 10:07
@djs55 PTAL

**Comment by ZanMarolt** [comment] 2020-11-05 18:16
We are observing similiar issue, when files are compiled within the container. macOS 10.15.7, docker 2.5.0.0.

**Comment by stephen-turner** [comment] 2020-11-09 18:22
Can someone with this issue confirm whether it goes away when you switch back to osxfs in the experimental tab of the settings? Thank you.

**Comment by epoberezhny** [comment] 2020-11-09 18:27
> Can someone with this issue confirm whether it goes away when you switch back to osxfs in the experimental tab of the settings? Thank you.

The issue disappears when I switch to 'Use gRPC FUSE for file sharing'  in the experimental tab of the settings. Looks like it appears only on osxfs

**Comment by stephen-turner** [comment] 2020-11-09 18:32
Oh, that way round? It's osxfs only? That's strange, we didn't intentionally change the osxfs code, but I guess it was a side effect of some other change.

**Comment by yellowmamba** [comment] 2020-11-10 06:35
Yeah I can confirm switching back to osxfs works. I ran into this when mounting the same file in another container B, which empties the already mounted in container A when on gRPC FUSE mode.

**Comment by thischarmingsam8** [comment] 2020-11-10 07:57
> Yeah I can confirm switching back to osxfs works. I ran into this when mounting the same file in another container B, which empties the already mounted in container A when on gRPC FUSE mode.

@yellowmamba what version of docker for Mac are you using? This is the opposite of what me and @epoberezhny are experiencing, gRPC FUSE mode works and the issue only appears in osxfs mode

**Comment by yellowmamba** [comment] 2020-11-10 08:25
@thischarmingsam8 Docker for Mac is `2.5.0.0`, my OSX version is `10.15.7`. My problem is slightly different to OP though.

**Comment by yellowmamba** [comment] 2020-11-10 08:32
To clarify, these are the steps to replicate my issue with gRPC FUSE mode turned **on**

1. Launch a container A with a file mounted.
2. Inside container A, cat the mounted file and verify content is there.
3. In a new terminal session, launch a second container B mounting the same file
4. Inside container B, cat the mounted file and verify content is there
5. Back in container A, cat the file again and you will notice the file has been emptied.

Docker for Mac `2.5.0.0`
OSX version: `10.15.7`

This is _not_ an issue when I turn **off** gRPC FUSE mode (using the legacy osxfs)

**Comment by thischarmingsam8** [comment] 2020-11-10 08:45
That's interesting, could you try following OP's steps on your machine to check if you're affected? Maybe both problems are related

**Comment by azinck** [comment] 2020-11-10 19:40
For what it's worth, I'm also seeing the problem in osxfs mode. Turning on gRPC FUSE causes the problem to disappear, but unfortunately also causes terrible performance for me, which is why I prefer osxfs.

Docker for Mac: 2.5.0.1
OSX: 10.15.7

**Comment by thischarmingsam8** [comment] 2020-11-10 20:17
> For what it's worth, I'm also seeing the problem in osxfs mode. Turning on gRPC FUSE causes the problem to disappear, but unfortunately also causes terrible performance for me, which is why I prefer osxfs.
> 
> Docker for Mac: 2.5.0.1
> OSX: 10.15.7

Same for me, gRPC FUSE caused me a lot of problems so reverted to osxfs

**Comment by djs55** [comment] 2020-11-12 14:14
Thanks for your reports!

@epoberezhny your example also reproduces for me on `osxfs` but not on `grpcfuse`. Is grpcFUSE working well enough for you? If not, could you file separate tickets for any further problems you discover?

@azinck thanks for your feedback. There are some known performance issues with gRPC FUSE which are on our backlog. Could you describe your use-case a little more so that I can check if your case is covered?

@thischarmingsam8 sorry to hear about your gRPC FUSE problems. Let me know if there are tickets for them already. If not, feel free to file new ones.

@yellowmamba Unfortunately I was not able to reproduce your problem with the latest stable 2.5.0.1 (49550). Here's what I tried (with gRPC FUSE turned on):

In terminal 1:
```
$ ls
$ echo hello > example.txt
$ cat example.txt
hello
$ docker run -it -v $(pwd)/example.txt:/example.txt alpine sh
/ # cat /example.txt
hello
```
In terminal 2:
```
$ docker run -it -v $(pwd)/example.txt:/example.txt alpine sh
/ # cat /example.txt
hello
```
In terminal 1:
```
/ # cat /example.txt
hello
```
Does this repro look correct? If not let me know what I should change. Could you reproduce it again and upload diagnostics (from the Whale menu -> Support -> Upload) and quote the ID here? It's also possible to watch a live debug trace like this:
```
$ docker run -v /run:/run djs55/grpcfuse-control:2.3.0.3 stats calls --follow
...
14:12:40.674811988,120,remote,Open,Users/.../example.txt
14:12:40.677402879,120,remote,Open,15 OK
14:12:40.677955692,121,remote,Release,15
14:12:40.678537540,122,remote,GetAttr,Users/.../MAILPATH
14:12:40.679136172,121,remote,Release,OK
14:12:40.679707788,122,remote,GetAttr,ENOENT OK
...
```
which might give some clues as to what is happening.

**Comment by epoberezhny** [comment] 2020-11-12 20:15
Thanks @djs55! I'm not happy with the performance of grpcFUSE mode, especially when I install gems and node packages for a large rails project inside a container. That's why I prefer `osxfs` mode

**Comment by thischarmingsam8** [comment] 2020-11-12 20:48
Thanks @djs55 I'll check the existing tickets, the main issue with grpcFUSE mode for me is that I can't start any containers, they always timeout.

**Comment by djs55** [comment] 2020-11-16 21:14
@epoberezhny I have a candidate fix for this problem which fixes the file size and file modes bug with `osxfs`. It's here: https://desktop-stage.docker.com/mac/edge/49849/Docker.dmg unfortunately it's not been notarized yet. Let me know if you're able to try it!

**Comment by epoberezhny** [comment] 2020-11-17 21:05
Cool, thanks @djs55! Looks like the fix works!

**Comment by nacengineer** [comment] 2020-11-18 23:43
I think they fixed the bug that initially required you to use the legacy FS. So this is a "turn on that setting you had to turn off" when you updated to docker (i forget which version) a few months ago.

**Comment by lorenrh** [comment] 2020-12-07 15:48
The fix for this issue has been released in Edge 2.5.4, I’ll go ahead and close the ticket now.

**Closed by lorenrh** 2020-12-07 15:48 UTC
Labels: version/2.5.0.0

**Comment by stephen-turner** [comment] 2020-12-07 16:04
If you're on the Stable channel, we're planning a release including this later this week.

**Comment by TomaszG** [comment] 2020-12-23 08:56
Docker 3.0.3, the issue still occurs there. Is the fix included in it?
