### ISSUE TITLE
/secrets/{id}/update won't update label

### ISSUE THREAD

**Issue by andrewspringman** [docker/for-mac#3874] opened 2019-08-29 17:46 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CBC2EF1A-E473-44D0-A04F-475ED2D3AB81/20190829173309

### Expected behavior
Label on secret should be updated

### Actual behavior
returns message "rpc error: code = InvalidArgument desc = only updates to Labels are allowed"

### Information
  - macOS Version: Sierra 10.12.6
  - Docker Desktop version 2.1.0.1 (37199)

### Diagnostic logs
```
Diagnose succeeded
```

### Steps to reproduce the behavior

  1. init a swarm
  2. create a secret with a Label
```
docker secret create -l poi=qwe test hi.txt
```
  3. view the secret info via the api
```
curl --silent --unix-socket /var/run/docker.sock http:/v1.40/secrets/ptjbcxir3eu4yg6zgv080w7ft | jq '.'
```
with results:
```
{
  "ID": "ptjbcxir3eu4yg6zgv080w7ft",
  "Version": {
    "Index": 15
  },
  "CreatedAt": "2019-08-29T17:12:15.2576717Z",
  "UpdatedAt": "2019-08-29T17:12:15.2576717Z",
  "Spec": {
    "Name": "test",
    "Labels": {
      "poi": "qwe"
    }
  }
}
```
  4. update the label
```
curl -d '{"Labels":{"poi":"asd"}}' -X POST --silent --unix-socket /var/run/docker.sock http:/v1.40/secrets/ptjbcxir3eu4yg6zgv080w7ft/update?version=15 | jq '.'
```
with results:
```
{
  "message": "rpc error: code = InvalidArgument desc = only updates to Labels are allowed"
}
```

**Comment by guillaumerose** [comment] 2019-09-01 18:48
I can confirm this behaviour without the Docker Desktop proxy (docker 19.03.2). So the issue applies to all platforms. 

ping @thaJeztah

**Comment by thaJeztah** [comment] 2019-09-02 09:35
Thanks for reporting; this is not a bug, but because the update request does not have the `Name` set.

Let me add a bit of background on this;

- The API endpoints for Swarm objects (services, configs, secrets) use a `fetch -> modify spec -> post updated spec` flow, in which it's expected that the `Spec` in the update request contains the "desired state" of the object after updating, which means that (generally) all fields should be included in the update request.
- Omitting the `Name` field is equivalent to `"Name": ""`. which means: update the name, and set it to an empty string
- For the secret _data_, an exception is made, because requiring the field to be set would require users of the API to keep the actual secret data around (possibly in an insecure way). For that reason, the `Data` field must either:
  - Contain the same data as the original "create" request
  - Be omitted (`nil`)

It may seem a bit awkward to be required to set the `Name` field (why send the field if it's not updatable?); reason for this is that producing an error _now_ would allow us to enhance the endpoint in future (e.g. allow _renaming_ secrets or configs) without breaking existing users (by explicitly disallowing changing the field, we know for sure that nobody is using that in their API clients).

You can find the code emitting the error here; https://github.com/moby/moby/blob/8dedcb8c516b914157d8274d5e94f0b8660cb866/vendor/github.com/docker/swarmkit/manager/controlapi/secret.go#L64-L69


In the example below, you can see that creating the secret, and updating the label works if the `Name` field is included;


```bash
echo foo | docker secret create -l poi=qwe test -
# x011vbtzbnlaas5axifv5stgx

curl --silent --unix-socket /var/run/docker.sock 'http:/v1.40/secrets/x011vbtzbnlaas5axifv5stgx' | jq '.'
```

```json
{
  "ID": "x011vbtzbnlaas5axifv5stgx",
  "Version": {
    "Index": 1941
  },
  "CreatedAt": "2019-09-02T09:13:16.134097128Z",
  "UpdatedAt": "2019-09-02T09:13:16.134097128Z",
  "Spec": {
    "Name": "test",
    "Labels": {
      "poi": "qwe"
    }
  }
}
```

Update the label, and check the exit code:

```bash
curl -d '{"Name": "test", "Labels":{"poi":"asd"}}' -X POST --silent --unix-socket /var/run/docker.sock 'http:/v1.40/secrets/x011vbtzbnlaas5axifv5stgx/update?version=1941' | jq '.'
echo $?
0
```

Inspect the secret after updating to verify the label was updated:

```bash
curl --silent --unix-socket /var/run/docker.sock 'http:/v1.40/secrets/x011vbtzbnlaas5axifv5stgx' | jq '.'
```

```json                                                                                
{
  "ID": "x011vbtzbnlaas5axifv5stgx",
  "Version": {
    "Index": 1942
  },
  "CreatedAt": "2019-09-02T09:13:16.134097128Z",
  "UpdatedAt": "2019-09-02T09:15:47.477671025Z",
  "Spec": {
    "Name": "test",
    "Labels": {
      "poi": "asd"
    }
  }
}
```

**Comment by thaJeztah** [comment] 2019-09-02 09:37
Let me close this issue, because this is not a bug, but I hope the information above helps you further (thanks for the clear reproduction steps!). Feel free to continue the conversation after I closed this 👍

**Closed** 2019-09-02 09:37 UTC
Labels: version/2.1.0.1

**Comment by andrewspringman** [comment] 2019-09-03 14:12
I can confirm.  Using the id and version.index of my secret, your example worked.  Thanks!
