### ISSUE TITLE
Container takes 3 minutes to start; http requests 30+ seconds once up.

### ISSUE THREAD

**Issue by guice** [docker/for-mac#1149] opened 2017-01-16 23:55 UTC
### Expected behavior

docker container start up immediately, things process through in reasonable time.

### Actual behavior

docker container takes 3 minutes to start up and show itself in the logs. It seems to be related to only this mac book -- my image works fine on Digital Ocean account and other laptop.

Once up, HTTP requests take 30+ seconds to process.

### Information
```
Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.12.2 (build: 16C68)
logs: /tmp/201A6A3E-8984-4DD3-B6AB-8E7EA72E474B/20170116-152658.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
[20170116-152658.tar.gz](https://github.com/docker/for-mac/files/709641/20170116-152658.tar.gz)

### Steps to reproduce the behavior

I don't know how to reproduce this. [Here's a video demonstrating the problem](https://vimeo.com/199746000). It took 3 minutes for my nginx/fpm container to finally start -- from the time hitting docker-compose up, to the time logs finally disabled. 

It uses my custom `gpcentre/php7-fpm-nginx` image. This image runs fine on my DigitalOcean account and my other laptop. I ran into similar issues with `richarvey/nginx-php-fpm` thinking it was the image, I converted to my custom one.

### Docker-compose file
```
version: '2'
services:
  myfamli:
    image: gpcentre/php71-fpm-nginx
    env_file: .env
    ports:
      - "8080:80"
      - 443
    links:
      - db
    volumes:
      - ./myfamli:/var/www/html
      - ./etc/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
  db:
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
```

**Comment by guice** [comment] 2017-01-17 00:08
In my fpm/nginx logs, I'm seeing a 10+ second delay between requests. These two are part of the same request:

```
myfamli_1  | 2017-01-17 00:03:37,961 DEBG 'nginx' stdout output:
myfamli_1  | 172.18.0.1 - - [17/Jan/2017:00:03:37 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" "-"
myfamli_1  | 
myfamli_1  | 2017-01-17 00:03:42,889 DEBG 'php-fpm' stdout output:
myfamli_1  | - -  17/Jan/2017:00:03:32 +0000 "GET /index.php" 200
```

And these two
```
myfamli_1  | 2017-01-17 00:04:18,059 DEBG 'nginx' stdout output:
myfamli_1  | 172.18.0.1 - - [17/Jan/2017:00:04:18 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" "-"
myfamli_1  | 
myfamli_1  | 2017-01-17 00:04:26,931 DEBG 'php-fpm' stdout output:
myfamli_1  | - -  17/Jan/2017:00:04:15 +0000 "GET /index.php" 200
```

nginx and fpm are communication on unix socket: unix://var/lib/php-fpm/php-fpm.socket

**Comment by dsheets** [comment] 2017-01-17 12:02
Could you please try to put your volumes (`/var/lib/mysql` and `/var/www/html`) into Docker containers and see if that speeds up your application?

There are known performance issues with bind mounts (see #77) that we are working to address and may explain your slowdown.

If this isn't the primary cause of the performance problem you are seeing, it would be great to rule it out.

**Comment by guice** [comment] 2017-01-18 16:30
Yeah, you're right. Commenting out this line: ```      - ./myfamli:/var/www/html```

Allowed it to start up immediately. It's probably what's causing the HTTP slowness, too (but can't test that as that's the website ... without the website, I can't test the website. ;))

**Comment by mikeball** [comment] 2017-01-19 00:58
This sounds like another case of the mounted volume performance issues. See the issues below. I wasted several days tracking down these perf issues which are well known to the D4M team. D4M isn't in a usable state for anything that involves usage of volumes and can't believe they call it 1.0 wasting hundreds or thousands of developers days trying it out and then running into this problem.

https://github.com/docker/for-mac/issues/77
https://github.com/docker/for-mac/issues/1094
https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/258

My suggestion, just switch to solus linux :)

**Comment by guice** [comment] 2017-01-19 02:27
Company provided OSX laptop. And my personal laptop is OSX as well. Can't help it, I'm a huge fan of OSX. And, honestly, I have never found a PC based laptop that does the trackpad so well. It's extremely hard giving up the trackpad.

I don't have a desktop system. However, my servers are Debian based. :)

**Comment by samoht** [comment] 2017-01-31 17:52
Closing as a duplicate of #77. We are aware that volume sharing doesn't currently work well when used with software relying on active polling and scanning of a huge amount of files on startup. We are still actively working on fixing the issue. Thanks for your report!

**Closed by samoht** 2017-01-31 17:52 UTC
Labels: osx/10.12.x, status/0-more-info-needed, status/0-triage, version/1.12.6
