### ISSUE TITLE
Docker for mac app not running properly

### ISSUE THREAD

**Issue by xbax486** [docker/for-mac#1373] opened 2017-03-03 00:04 UTC
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Errors

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/31D8991A-0FF1-4752-8E84-511C3387236A/20170303-105659.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/andy.ba/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/andy.ba/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/andy.ba/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy.ba/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/andy.ba/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy.ba/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by rogaha** [comment] 2017-03-03 11:25
@xbax486 can you please try the following: 

```
Try the following steps:
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac
```

Let us know if it works.

**Comment by xbax486** [comment] 2017-03-03 11:30
Hi Rogaha,

Already tried that several times and the issue remains. Have to use another machine. There must be some broken part of my docker settings in my machine cause I tried to install the "Docker for mac" on another machine and the installation app went well. Right now I decide to use finish my work first.
Anyway, thanks for your help.

**Comment by rogaha** [comment] 2017-03-03 12:28
@xbax486 would be possible to perform a `reset to factory` it looks like the installation didn't go well here?

**Comment by xbax486** [comment] 2017-03-03 12:32
Never try that. Would try it next time. Thank you.

**Comment by MagnusS** [comment] 2017-03-08 16:04
Thanks for the report @xbax486. Since the issue is resolved for now I'm closing this issue. Please let us know if you experience this issue again, either by reopening this issue or creating a new one.

**Closed by MagnusS** 2017-03-08 16:04 UTC
Labels: osx/10.11.x, status/0-triage, version/17.03.0-ce-mac1
