### ISSUE TITLE
UI: missing label in password dialog

### ISSUE THREAD

**Issue by rbelouin** [docker/for-mac#3827] opened 2019-08-10 09:30 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I expect to see a label in the button of the dialog when I am being prompted to enter my password.

### Actual behavior

<img width="555" alt="Screenshot 2019-08-10 at 11 16 17" src="https://user-images.githubusercontent.com/459673/62820192-057fe380-bb61-11e9-9f7f-86305dbdd4d4.png">

### Information

  - macOS Version: 10.14.6 (18G87)
  - Docker Desktop Version: 2.1.0.1 (37199)

### Diagnostic logs

Will upload once the diagnosis completes, even though it might not help solve a UI issue.

### Steps to reproduce the behavior

  1. Upgrade Docker for Mac to the latest version
  2. Let it ask for permission when it needs to make changes

**Comment by mrackwitz** [comment] 2019-08-10 16:24
Seems like this is a duplicate of #2856. This prompt looks weird and shady with these misaligned UI components.

**Comment by rbelouin** [comment] 2019-08-11 08:24
@mrackwitz oh, I missed that one, thanks! I definitely agree with [the last comment](https://github.com/docker/for-mac/issues/2856#issuecomment-406423965) though. This bug makes me skeptical about how my password might be used.

**Comment by guillaumerose** [comment] 2019-08-14 11:58
You can read more in this issue: https://github.com/moby/moby/issues/39648#issuecomment-518192195

**Closed by guillaumerose** 2019-08-14 11:58 UTC
Labels: version/2.1.0.1
