### ISSUE TITLE
M1 preview: docker-compose depends_on doesn't seem to work

### ISSUE THREAD

**Issue by stijn-gravity** [docker/for-mac#5315] opened 2021-02-04 08:43 UTC
Reporting this here because this is not an issue for any of my coworkers who are not running on the M1 version. It is exclusive to the M1 preview.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features -> I have not, because I need them.
  - [ ] I have uploaded Diagnostics

### Expected behavior
Exerpt of the docker-compose file:
```
version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
  functions-mock:
    image: kennethreitz/httpbin
    restart: always
    ports:
    - "4001:80"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    restart: always
    ports:
    - "4000:8080"
    depends_on:
    - "postgres"
    volumes:
    - ./migrations:/hasura-migrations
    environment:
        ....obfuscated
volumes:
  db_data:

```

On older versions this would crash and restart because postgres was not started yet. After this restart this would work as intended.

### Actual behavior

On this new version the hasura/graphql-engine container keeps restarting. We can connect to postgres ourselves, and it started correctly. But the hasura/graphql-engine keeps restarting as if it's not there yet. The issue seems to lie in the connection between hasura/graphql-engine and postgres.

Logs from a single loop (this repeats) 
```
{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"port env var is not set, defaulting to 8080"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"server timeout is not set defaulting to 30 seconds"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 8080"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"waiting 30 for 8080 to be ready"}}

{"timestamp":"2021-02-04T08:45:03.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"failed waiting for 8080"}}
```

### Information
I asked a few colleagues with new M1 chips to test this, and they all had the same experience. All colleagues with old intel chips could run this without issues.

### Steps to reproduce the behavior
Additional dockerfile:
```
FROM hasura/graphql-engine:v1.0.0.cli-migrations

COPY migrations /hasura-migrations
```

If no immediate solution can be found we understand this. We are on a preview version and will have to deal with the consequences. A way to work around this issue we can't find ourselves, so any help in that direction would also be great.

**Comment by stephen-turner** [comment] 2021-02-04 13:43
Thanks for the report. From your description, it sounds like networking problems between the containers. There are lots of known networking problems in the current preview, so it might be good to retest when the next preview is available.

**Comment by stijn-gravity** [comment] 2021-02-04 14:11
@stephen-turner thank you for your reply. We will be looking forward to the new preview version.

For anyone stumbling on this specific issue also using an hasura image, we switched to an ARM version for local development, fedormelexin/graphql-engine-arm64,  found here: https://github.com/hasura/graphql-engine/issues/1266. It gets the job done for now in our case.

**Comment by DonikaV** [comment] 2021-02-09 07:36
!offtopic!

Reading so many comments / issues I understood that it was a bad idea to purchase the new MacBook m1 :|

**Comment by djs55** [comment] 2021-02-12 14:12
@stijn-gravity thanks for the update.

I think if the original `amd64` `hasura/graphql-engine` container keeps restarting but you've managed to work around it by switching to a native `arm64` image `fedormelexin/graphql-engine-arm64` then this suggests the problem is due to the `qemu` `amd64` emulation. Unfortunately the emulation isn't perfect and some images don't emulate correctly :( Emulation is also slow and memory intensive, so using a native `arm64` image -- as you have done -- is generally a good idea. Ideally there would be a "multi-arch" image which contains both amd64 and arm64 so you wouldn't have to modify your compose file at all.

Now that many more people have `arm64` machines I think it will become standard to build `amd64+arm64` multi-arch images, so hopefully this kind of problem will become less common in future.

**Comment by stephen-turner** [comment] 2021-05-07 08:08
In version 3.3.2, we are launching qemu with an additional argument that may help in some cases. We would be interested to know whether it has solved this problem.

However, note that qemu emulation should only ever be regarded as "best effort". As @djs55 said, even when it works it will use more memory and have worse performance. The real solution is to run arm64 containers on M1 hardware.

I'm going to close this ticket now, because there's nothing further that we can do.

**Closed by stephen-turner** 2021-05-07 08:08 UTC
Labels: area/m1, area/multiarch
