### ISSUE TITLE
Host volume mount painfully slow

### ISSUE THREAD

**Issue by bunchjesse** [docker/for-mac#965] opened 2016-11-17 17:58 UTC
Here's how I started the container:

```
docker run --rm -it -v /tmp:/hostmount -v /tmp ubuntu /bin/bash
```

**Test 1: Write to container outside of any mount**

```
root@8a50acfb8883:/# time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 0.199711 s, 513 MB/s

real	0m0.201s
user	0m0.000s
sys	0m0.200s
```

**Test 2: Write to a regular docker volume**

```
root@8a50acfb8883:/tmp# time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 0.146036 s, 701 MB/s

real	0m0.148s
user	0m0.010s
sys	0m0.130s
```

**Test 3: Write to a host volume mount**

```
root@8a50acfb8883:/hostmount# time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 31.0825 s, 3.3 MB/s

real	0m31.085s
user	0m0.060s
sys	0m1.160s
```

This issue makes D4M painfully slow in development when it makes sense to use a host mount.

**Comment by dsheets** [comment] 2016-11-18 10:59
This is a duplicate of #77. Please subscribe to that issue to follow progress.

**Closed by dsheets** 2016-11-18 10:59 UTC
Labels: status/0-triage
