### ISSUE TITLE
Unable to use docker after MAC sleep

### ISSUE THREAD

**Issue by lukaserat** [docker/for-mac#91] opened 2016-08-03 06:30 UTC
### Information

Diagnostic ID: 60A97509-144F-4CF4-82EE-5ECDF0149B5A
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment] 2016-09-09 14:07
It looks like the kernel in the VM had a problem:
```
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    0-...: (1 GPs behind) idle=575/1/0 softirq=516638/516642 fqs=0
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    5-...: (1 GPs behind) idle=449/1/0 softirq=273919/273920 fqs=0
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: (t=15299 jiffies g=166424 c=166423 q=26094)
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: rcu_sched kthread starved for 15299 jiffies! g166424 c166423 f0x0 s3 ->state=0x1
<Notice>: VM: 2016-08-03 04:35:57 +0000 UTC kern.info kernel: Task dump for CPU 0:
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    1-...: (1 ticks this GP) idle=d61/1/0 softirq=235788/235788 fqs=0
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Notice>: VM: 2016-08-03 04:35:57 +0000 UTC kern.info kernel: swapper/0       R  running task        0     0      0 0x00000000
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: 000000000000001d
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: (t=15299 jiffies g=166424 c=166423 q=26094)
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: rcu_sched kthread starved for 15299 jiffies! g166424 c166423 f0x0 s3 ->state=0x1
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: (t=15299 jiffies g=166424 c=166423 q=26094)
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: rcu_sched kthread starved for 15299 jiffies! g166424 c166423 f0x0 s3 ->state=0x1
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffffffff810a4db6 ffffffff81c3e0c0
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    2-...: (1 GPs behind) idle=b27/1/0 softirq=229708/229708 fqs=0
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffff88013fc16f40
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffffffff81c03e88 0000000000000001 ffffffff810a7ab4
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    4-...: (8 GPs behind) idle=029/1/0 softirq=211586/211586 fqs=0
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: (t=15299 jiffies g=166424 c=166423 q=26094)
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: 00000000000065ee
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: rcu_sched kthread starved for 15299 jiffies! g166424 c166423 f0x0 s3 ->state=0x1
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffffffff81c124c0 ffffffff81d22a00
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffff88013fc15ac0 ffffffff8107c25a
<Error>: VM: 2016-08-03 04:35:57 +0000 UTC kern.error kernel:    3-...: (1 ticks this GP) idle=4c5/1/0 softirq=215022/215022 fqs=0
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff810815d1>] ? kthread_parkme+0x16/0x16
<Notice>: VM: 2016-08-03 04:35:57 +0000 UTC kern.info kernel: Task dump for CPU 1:
<Notice>: VM: 2016-08-03 04:35:57 +0000 UTC kern.info kernel: swapper/1       R  running task        0     0      1 0x00000008
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffff88013fc4d720 0000000000000001 0000000000000001 ffffffffffffff10
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffffffff8103b2e4 0000000000000010 0000000000000246 ffff88013b17ff08
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: 0000000000000018 ffffffff8109610e ffffffff81015914 ffffffff810962d5
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: Call Trace:
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff8103b2e4>] ? native_safe_halt+0x2/0x3
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff8109610e>] ? current_clr_polling_and_test+0x15/0x24
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff81015914>] ? default_idle+0x16/0x24
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff810962d5>] ? cpu_startup_entry+0x145/0x208
<Notice>: VM: 2016-08-03 05:55:15 +0000 UTC daemon.info vsudd: Connection 146 to: 2376 from: 00000000
<Notice>: sending SIGTERM to com.docker.hyperkit pid 80106
<
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffff88013fc4d720 0000000000000001 0000000000000001 ffffffffffffff10
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: ffffffff8103b2e4 0000000000000010 0000000000000246 ffff88013b17ff08
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: 0000000000000018 ffffffff8109610e ffffffff81015914 ffffffff810962d5
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: Call Trace:
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff8103b2e4>] ? native_safe_halt+0x2/0x3
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff8109610e>] ? current_clr_polling_and_test+0x15/0x24
<Warning>: VM: 2016-08-03 04:35:57 +0000 UTC kern.warn kernel: [<ffffffff81015914>] ? default_idle+0x16/0x24
```
I think this is a duplicate of #87

**Closed by djs55** 2016-09-09 14:07 UTC
