### ISSUE TITLE
2.5.3 spins cpu with no containers running

### ISSUE THREAD

**Issue by b1rdex** [docker/for-mac#5094] opened 2020-12-03 01:17 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9A07268F-313A-4166-9AD5-0BE857C07B7E/20201203010849

### Information

  - macOS Version: 11.0.1 (20B29)

### Diagnostic logs

```
Docker for Mac: 2.5.3 (50261)
I can't find such menu...
```

### Steps to reproduce the behavior

  1. update
  2. hear the fan spinning 😁

**Comment by stephen-turner** [comment] 2020-12-03 10:13
Thanks for the report. Closing as a dupe of #5044. Please try the experimental build posted in that ticket.

**Closed by stephen-turner** 2020-12-03 10:13 UTC
Labels: version/11.0.1
