### ISSUE TITLE
Cpu very, very intensive after upgrade from 2.1.0.3 to 2.1.0.5 ( 130% - 150%)

### ISSUE THREAD

**Issue by gheorghemolnar** [docker/for-mac#4180] opened 2020-01-09 08:39 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:  6F204835-5234-4414-A261-27FDB731987C/20200109082730

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.5

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by m8rge** [comment] 2020-01-09 10:37
I believe this duplicate of https://github.com/docker/for-mac/issues/4064

**Comment by gheorghemolnar** [comment] 2020-01-28 09:05
I guess it's a webpack / docker issue.
Removing "--watch-poll" from webpack configuration solved high cpu usage, for me.

**Closed** 2020-01-28 09:05 UTC
Labels: version/2.1.0.5
