### ISSUE TITLE
Problem when multiple users on the same host want to use docker

### ISSUE THREAD

**Issue by Fedalto** [docker/for-mac#929] opened 2016-11-10 16:38 UTC
### Expected behavior

Multiple users on the same host can use docker.

### Actual behavior

After installing Docker, or updating, the `docker` cli commands are only accessible to the user which initiated the install/update process.

### Information

Digging a big, the docker command is in `/usr/local/bin/docker`, but it's only a symlink to `/Users/my_user/Library/Group Containers/group.com.docker/bin/docker`, which in turn is too a symlink to `/Applications/Docker.app/Contents/Resources/bin/docker`.

My problem is that a second user in the same host does not have access to go inside the `/Users/my_user/`. So my workaround is to remove `/usr/local/bin/docker` and replace it with a symlink directly to `/Applications/Docker.app/Contents/Resources/bin/docker`.

OS X 10.11.6
Docker version:
Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

**Comment by ijc25** [comment] 2016-11-15 13:48
I think this is in essence a duplicate of #799. The model today is that multiple users should work if you re-run `Docker.app` as the new user after switching, but this is something which we may enhance in the future, I've added a link to this bug to our internal ticket which is tracking this.

**Closed by ijc25** 2016-11-15 13:48 UTC
Labels: status/0-triage

**Comment by sbose78** [comment] 2017-06-04 21:07
Hi @justincormack , may I know if there been any progress on this?
Also, could you please elaborate your workaround?

**Comment by Fedalto** [comment] 2017-06-06 00:21
The workaround that I have for this is to run the following after every update:
```
$ ln -f -s /Applications/Docker.app/Contents/Resources/bin/* /usr/local/bin
```

Re-run `Docker.app` as the new user does not work because it will "lock" everyone else out.
It will overwrite the symlinks in `/usr/local/bin` to point to somewhere in the current user home, which may not be accessible to other users.

**Comment by thisconnect** [comment] 2017-06-12 11:44
Could this be added to the documentation or FAQ?
