### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jkamke** [docker/for-mac#76] opened 2016-08-02 16:50 UTC
### Expected behavior
Should be able to npm install in a --volume
### Actual behavior
```
npm ERR! Linux 4.4.15-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "standard-format"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EIO
npm ERR! errno -5
npm ERR! syscall read

npm ERR! EIO: i/o error, read
```
> Note: syscall can be fstat, read, close, or perhaps others

### Information

Diagnostic ID: 37413D5E-CD7C-494B-83F6-B5F2600D9B76
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)

### Steps to reproduce

From ~/
1. mkdir test
2. cd test
3. `docker run -it --rm -w /app -v "$PWD:/app" scispike/node:0.31.1 npm install standard-format`

**Comment by dsheets** [comment] 2016-08-02 17:00
I confirm that this issue is present in 1.12 stable and a patch has already been written which should arrive in the next stable hotfix/beta. I will leave this issue open until that time and then close it to give you a reminder to try your reproduction on that release.

**Comment by phairoh** [comment] 2016-08-02 17:35
@dsheets As this was working in the previous version of the beta (beta20 I believe) is there a location where we can download that version as a temporary solution? This has all but halted my team's development.

**Comment by FrenchBen** [comment] 2016-08-02 18:10
@phairoh Unless you're constantly adding a ton of packages, you can get around this pretty easily by using an on-build.

```
FROM node:6.2-onbuild
ONBUILD RUN npm install --no-optional

VOLUME ["/usr/src/app"]
EXPOSE 3000 3001
CMD ["npm", "run", "dev"]
```
Build it:
```
docker build -t my-npm-image .
```
Run it:
```
docker run --rm -it -p 3000:3000 -p 3001:3001 -v $PWD/src:/usr/src/app/src my-npm-image
```

This will bind-mount the `src` directory which is where 99.9% of development happens. Building it like such it perhaps not ideal, but a LOT faster to use, since your modules only need to be installed once, when the image is built.
If you need new packages, add them to the `package.json` and rebuild the image, then re-launch your container. 
All iNotify events will be triggered properly, since the watch is usually set for `src`

**Comment by phairoh** [comment] 2016-08-02 18:20
@FrenchBen Thanks for your reply, however due to a non-conventional way that we are running the docker container your solution would require a complete change to our workflow.  As it turns out we are moving to a more conventional approach so in a few days time this will no longer be an issue, but that means that as of right now we are halted. We're investigating other workarounds, but again that is just more time spent not coding.

**Comment by dsheets** [comment] 2016-08-03 16:15
Beta 21.1 has been released which should resolve this issue. Please re-open if it does not.

**Closed by dsheets** 2016-08-03 16:15 UTC
Labels: area/mounts, kind/bug, version/1.12.0

**Comment by ringods** [comment] 2016-08-03 20:57
@dsheets how long does it usually take before the auto-update finds the new version? I'm on beta21 currently.

**Comment by FrenchBen** [comment] 2016-08-03 20:58
@ringods you can force-check it by going to the Moby menu -> Check for Updates

**Comment by ringods** [comment] 2016-08-03 21:01
@FrenchBen I know. But that one says I'm on beta21 and that it is the newest version. If I understand @dsheets I need the 21.1 beta drop to have this fixed.

**Comment by MagnusS** [comment] 2016-08-03 21:01
The version shown in `About Docker` will still be 1.12.0-beta21 after the upgrade, but the build number should be 11019.

**Comment by ringods** [comment] 2016-08-03 21:03
Allright! Got it. Quite confusing though with these version numbers. :-)

**Comment by Kaijun** [comment] 2016-08-04 06:18
@dsheets thanks for ur effort, but is there hotfix/update for the **stable** version?

**Comment by dsheets** [comment] 2016-08-04 09:44
@Kaijun my understanding of the current plan is that this bugfix will reach stable early next week in a hotfix in order to ensure the fix does not introduce a worse regression than the defects it corrects. Right now, stable 1.12 and beta are close enough that switching channels either direction shouldn't cause any issues but they will likely diverge, perhaps incompatibly, later in the 1.13 release cycle and so switching from beta back to stable may not be possible without resetting your installation at that time.

We're still adjusting to having multiple release channels so we appreciate your thoughts on how we can do this sort of thing better while still exercising caution for stable users.

**Comment by Kaijun** [comment] 2016-08-04 11:45
@dsheets no offence, i'm curious if you have test cases or test flow to validate the every functionality and right behaviours of docker before releasing a new version of either stable or beta channel? 
I know it iterates itself version by version really quickly, but i've seen a lot of times that a patch of hotfix comes few hours later directly after releasing a new version.

**Comment by dsheets** [comment] 2016-08-04 13:20
@Kaijun yes we have both unit and integration tests and perform significant manual testing before releases. We use many open source components, some of which we wrote, which contain their own tests which are run prior to integration into the product. We are constantly expanding our test suite and attempting to improve code coverage. However, the product is quite intricate internally due to both inherent complexity and our rapid development methodology. In many cases, this complexity is not easy to cover with tests. Consider that you are being given:

1. A young, heavily modified hypervisor with novel components
2. A custom Linux distribution with a patched kernel
3. A new shared file system designed from the ground-up to provide a level of operating system integration never attempted
4. A userspace networking stack

Most of these components are multi-threaded and rely on other components having a known state. In this particular case, the cause of the bug was fairly complex and not easily reproducible outside of an application integration test (a sufficiently large `npm install`). Here's what happened:

> An OS X system process is listening to FSEvents generated by container file system actions and then performs file system actions in response. These system calls generate their own FSEvents that, due to the design of the OS X FSEvents API, are bundled with the container's FSEvents and then delivered to the Linux VM. The Linux VM then simulates the system calls that would trigger `inotify` events and those system calls are "placated" by a specialized event-handling file system. This file system turns off the dcache for the directory entry in question in Linux and then responds with appropriate messages to have the event-triggering system call succeed. The response that was used in the case of creation events (bundled with Finder attribute updates by FSEvents) told Linux that the dentry node in question was a symlink when it should actually have indicated a regular file. Despite having caching turned off, the Linux VFS maintains a node table which keeps track of very basic (more basic than inodes or dentries) metadata like file type and file size. If that node table is corrupted by loading incorrect file types into it (for instance), the Linux VFS will catch this inconsistency and return `EIO`. This only happens with specific timings of execution of both host and guest threads.

And here's how we fixed it:

> We added a new `mknod` event stream system call message to avoid corrupting the Linux VFS node table. We then used this call for creation event delivery. In the process, we updated various pieces of the event delivery system in order to deal with correctly invalidating the Linux dcache. During this process, we found a deadlock during a specific interleaving of Linux kernel threads which took several days to uncover and debug. That issue never reached a release build and its resolution required us to create a second, parallel Linux VFS notification message stream to the regular file system request/response stream.

We very much want to deliver a quality product even in the face of this complexity. I have added an `npm install` test to our release test suite as it seems to regularly pick up issues like this.

Finally, due to our aggressive release schedule, we must triage issues rapidly and determine which ones *must* be fixed for the next release. Every release contains known bugs that we have not had time to address. We have now split releases along stability channels to improve quality for those customers that demand it while not sacrificing our development velocity. Our goal is to provide a consistently good experience on the stable channel but getting to that point will take some time as we branch our development.

I'm curious about which hotfixes you felt contained obvious issues that should have been caught in QA? For most of the beta, we attempted to release every Tuesday but often did not release until Thursday or Friday due to QA holds.

I'm really sorry you've experienced this issue and I hope this explanation has given you a little insight into our process and this specific problem. I can assure you that we are very aware of the need to focus on test and QA now that we are out of beta.

**Comment by Kaijun** [comment] 2016-08-04 13:44
@dsheets thanks for the explanation and many many thanks for all ur efforts and hard work!

**Comment by bschwind** [comment] 2016-08-05 05:26
@dsheets Thank you so much for the awesome communication and quick turnaround! It's rare to see that level of detail when explaining an issue.

**Comment by ringods** [comment] 2016-08-08 12:54
@dsheets unfortunately, I still have a problem with `npm install`. It has an option to let you install directly from Github. When using that, I get file permission errors.

You can read the complete report here:
https://github.com/wercker/step-npm-install/issues/16

Can you trace these permission errors to the current file system implementation?

**Comment by dsheets** [comment] 2016-08-08 12:57
@ringods interesting. Could you please open a new issue with exact reproduction steps? I'm not familiar with either wercker or npm (very much). It is possibly an osxfs issue but it's difficult to say without an easy reproduction.

**Comment by ringods** [comment] 2016-08-13 13:50
@dsheets here it is: https://github.com/docker/for-mac/issues/263
