### ISSUE TITLE
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory.  on mac m1

### ISSUE THREAD

**Issue by xiazemin** [docker/for-mac#5282] opened 2021-01-21 03:11 UTC
% docker version
Client:
 Cloud integration: 1.0.2
 Version:           20.10.1
 API version:       1.41
 Go version:        devel +37a32a1833 Thu Dec 3 21:34:39 2020 +0000
 Git commit:        831ebeae96
 Built:             Wed Dec 16 02:33:22 2020
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

**Comment by lee997** [comment] 2021-01-21 15:49
I had same issue and found the problem is the firewall on Mac has been open, the docker on mac m1 will keep "starting" status when the firewall is open. The issue was fixed after I close it.

**Comment by xiazemin** [comment] 2021-01-21 23:45
my firewall is closed

**Comment by xiazemin** [comment] 2021-01-22 02:22
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:14:41Z" level="error" msg="Logging system already setup"
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:14:42Z" level="error" msg="Cmd: "
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:18:02Z" level="error" msg="Docker Desktop UI (settings): 10:18:02.700 › Error for GET /registry/user
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:18:02Z" level="error" msg="Docker Desktop UI (settings): 10:18:02.700 › { error: true, type: 'Not Found', message: 'not logged in' }
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:18:02Z" level="error" msg="Docker Desktop UI (settings): 10:18:02.700 › 404
/Users/xiazemin/Library/Containers/com.docker.docker/Data/log/host/Docker.log:time="2021-01-22T02:18:02Z" level="error" msg="Docker Desktop UI (settings): 10:18:02.701 › {

**Comment by avirevivo1** [comment] 2021-01-28 21:21
Hi,
Facing the same issue.
On my All new MacBook Pro M1.

<img width="591" alt="Screen Shot 2021-01-28 at 9 07 34" src="https://user-images.githubusercontent.com/11374194/106200039-feb6b780-61be-11eb-9411-4e374e193eab.png">

I've installed Docker-AppleSilicon-Preview7
I've tried, installing nodejs, Rossetta.
Turned off Firewall
Nothing help.

Any Idea?
Thanks,
Avi

**Comment by liamfranke** [comment] 2021-02-07 01:54
Hi, Facing the same issue. Upon downloading the docker preview for M1 mac and tryong to copy and paste this command:

docker run -d -p 80:80 docker/getting-started

into docker throws this error.

**Comment by stephen-turner** [comment] 2021-05-07 19:00
I think this is obsolete, I'm going to close it. If there are still startup issues, please open a new ticket with diagnostics.

**Closed by stephen-turner** 2021-05-07 19:00 UTC
Labels: area/m1
