### ISSUE TITLE
UI Glitches on mouse over

### ISSUE THREAD

**Issue by stoune** [docker/for-mac#5719] opened 2021-05-25 09:15 UTC
When I do mouse over Docker for Mac Dashboard I see visual artifacts see attached screenshot:

<img width="1277" alt="Screenshot 2021-05-25 at 12 03 55" src="https://user-images.githubusercontent.com/1305362/119471352-e102f480-bd51-11eb-8751-a3478cd9c744.png">

I don't experience such behaviour on any other application, like VsCode or Chrome.

  - [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C8D69C81-D36B-4193-9811-8C9F4DAC9576/20210525090423

### Expected behavior

The UI should not have glitches.

### Actual behavior

The UI should does have glitches.

### Information

- Is it reproducible? - yes
- Is the problem new? - if I remember correctly it appeared at least one version ago
- macOS Version: 11.3.1 (20E241)
- Intel chip or Apple chip: MacBook Pro (16-inch, 2019), 2,6 GHz 6-Core Intel Core i7
- Docker Desktop Version: 3.3.3 (64133)

### Steps to reproduce the behavior
 
1. Open dashboard 
2. Mouse over on Opened UI

**Comment by stephen-turner** [comment] 2021-05-25 10:38
Thanks for the report, I'm closing it as a dupe of #5121.

**Closed** 2021-05-25 10:51 UTC
Labels: version/3.3.3
