### ISSUE TITLE
com.docker.hyperkit 30-50% CPU

### ISSUE THREAD

**Issue by danielkwinsor** [docker/for-mac#4944] opened 2020-09-25 18:27 UTC
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 9287747D-2A3F-4B41-A948-5C881E13628D/20200925182144

### Expected behavior
Low CPU when idle

### Actual behavior
I have constant CPU ranging from 30-50%
I have no docker containers running.
I have kubernetes with no pods.
I have limited the shared dirs to a subset of /Users

### Information
  - macOS Version:
10.15.6 (19G2021)

Was happening in 2.3.0.4 and possibly in 2.3.0.2 (not sure) and I'm currently on .5
Kubernetes was enabled around this time, and I've reset that several times.

### Diagnostic logs

```
Docker for Mac: version...

```

[dockerCPUSpindump.txt](https://github.com/docker/for-mac/files/5284627/dockerCPUSpindump.txt)
[Sample of com.docker.hyperkit.txt](https://github.com/docker/for-mac/files/5284628/Sample.of.com.docker.hyperkit.txt)

**Comment by stephen-turner** [comment] 2020-09-28 11:32
Please try the latest Edge release, we've made lots of CPU improvements.

Closing as dupe of #3499

**Closed by stephen-turner** 2020-09-28 11:32 UTC
Labels: version/2.3.0.5

**Comment by danielkwinsor** [comment] 2020-09-28 18:42
Leaving the laptop over the weekend, came back to 100% CPU usage.  Tried the edge version 2.3.7.0 and I am at 30% out of the box, with no running containers.
