### ISSUE TITLE
Cannot bind to specific IPs: cannot assign requested address.

### ISSUE THREAD

**Issue by tecnobrat** [docker/for-mac#4209] opened 2020-01-21 20:10 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `D101B22D-FABF-4C6B-A4D9-07BA9A23270D/20200121200047`

### Expected behavior

I should be able to bind to any IP on my mac.

### Actual behavior

Trying to bind explicitly to my mac's wifi address results in an error: `192.168.2.2:443: bind: cannot assign requested address.`

Binding to `127.0.0.1` or `0.0.0.0` explicitly does work, any other IP does not work.

### Information
  - macOS Version: `10.15.2 (19C57)`
  - Docker for Mac: 2.2.0.0 (42247)

### Steps to reproduce the behavior
  1. Use `ifconfig` to find your wifi or lan IP.
  2. Run `docker run -p 192.168.2.2:443:443 nginx`
  3. Receive this error:

  ```
  docker: Error response from daemon: driver failed programming external connectivity on endpoint elated_austin (f94e21669eb9ad9b6cc3d9cc4effd5beb78617d558c0213c2a3c72da10fbfbb0): Error starting userland proxy: listen tcp 192.168.2.2:443: bind: cannot assign requested address.
  ```

This error only started when upgrading to 2.2.0.0.  Downgrading to `2.1.0.4` and the problem goes away.

**Comment by arlaneenalra** [comment] 2020-01-21 21:18
I'll confirm this. It seems that binding to an IP directly fails.

**Comment by tecnobrat** [comment] 2020-01-21 21:26
Binding to `127.0.0.1` directly does work though, so its odd.

**Comment by thiagorb** [comment] 2020-01-22 06:38
I am also affected by this error. I was using an alias to bind the ports, so that it wouldn't conflict with other services running on the same ports.

To create an alias I use:
```
sudo ifconfig lo0 alias 10.10.10.10
```

And this docker-compose.yml used to work:
```
version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - 10.10.10.10:80:80
```

**Comment by lmakarov** [comment] 2020-01-22 07:04
> I was using an alias to bind the ports, so that it wouldn't conflict with other services running on the same ports.

Same motivation and confirming the same issue on 2.2.0.0.

**Comment by raido** [comment] 2020-01-22 09:53
Downgrading to v2.1.0 solves the issue for me: https://download.docker.com/mac/stable/40693/Docker.dmg

**Comment by lmakarov** [comment] 2020-01-24 17:59
Confirmed this issues applies to both Mac and Windows Docker Desktop versions.

Downgrading to the latest 2.1.x version (2.1.0.5) solves the problem. Here are the direct download links.
Mac: https://download.docker.com/mac/stable/40693/Docker.dmg
Windows: https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe

**Comment by christmasjumper** [comment] 2020-01-25 15:01
Also confirmed.

I mean come on, testing of something so basic must surely take place!?

**Comment by jaredkipe** [comment] 2020-01-27 15:57
I hit this today as well.  Downgrade I go...

**Comment by esteinborn** [comment] 2020-02-05 12:54
Any status on a fix for this issue?

**Comment by ryanissamson** [comment] 2020-02-06 19:24
I've downgraded, which resolves it, following.

**Comment by tekNorah** [comment] 2020-02-06 20:55
Here is the issue on the Windows side: https://github.com/docker/for-win/issues/5546

**Comment by danshumaker** [comment] 2020-02-11 16:25
Also experiencing this issue on Docker for Mac: 2.2.0.3

**Comment by alvarow** [comment] 2020-02-13 19:55
I also hit this. My specific IP in question is bound to `lo0` interface on Mac.

**Comment by leirissa** [comment] 2020-02-20 10:18
so will this be fixed soon?

**Comment by friek** [comment] 2020-02-20 13:26
Interestingly it does work when the IP you're attempting to bind to is added to the lo interface inside the docker virtual machine as well:
```bash
docker run -it --rm --privileged --pid=host justincormack/nsenter1
ip addr add 10.10.10.10/32 dev lo
```

Then add it locally (on MacOS):
```bash
sudo ifconfig lo0 alias 10.10.10.10/32
```

And run some service on it:
```bash
docker run -p 10.10.10.10:80:80 nginx
```

10.10.10.10:80 is then properly forwarded to the container.

**Comment by handelaar2** [comment] 2020-03-13 11:54
Also experiencing this issue on Docker for Mac: 2.2.0.4

**Comment by FernandoMiguel** [comment] 2020-03-16 18:22
@friek alias is not working for me!

**Comment by hollie** [comment] 2020-03-17 21:59
I can confirm I am experiencing the same issue with 2.2.0.4 on Mojave 10.14.6: unable to bind to a port when specifying an IP address.

I use this because I want a container only to be listening on a specific VLAN on my machine.

With 2.1.0.5 all is working as expected, so I too reverted to that version.

**Comment by kwiechmann** [comment] 2020-03-18 12:28
Tried 2.2.0.4 again on my local. The new GUI features promised were too tempting not to try again. Bummed like everyone else0. Sadly returning to 2.1.0.5.

```
$ fin project start
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Configuring NFS shares...
NFS shares are already configured
Resetting Docksal system services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (9443bb5547db8ef71b9fa8a29fb74483f0ce754a4e1941f21418c72e1dc7de22): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.
```

**Comment by simonykq** [comment] 2020-03-18 19:15
Same problem here after upgrading to `2.2`

```
ERROR: for mbai-docker_highcharts-export-server_1  Cannot start service highcharts-export-server: driver failed programming external connectivity on eCreating mbai-docker_mongo_1                    ... error
en tcp 10.254.254.254:8087: bind: cannot assign requested address
WARNING: Host is already in use by another container
```

**Comment by MikkelPaulson** [comment] 2020-03-18 21:26
You know what would be great? If we could get any indication at all from the Docker team that they consider this issue a priority. This has evidently broken Docker completely for a lot of people.

**Comment by alvarow** [comment] 2020-03-19 14:03
It sure did, we're starting to look for alternatives for our workflow since we'll have to change it, might as well see what's out there... Multirun seems instersting too.

**Comment by mrgauthier** [comment] 2020-03-25 21:25
Same issue updating to 2.2.0.4 on mac.  How frustrating...

**Comment by msneujink** [comment] 2020-03-26 08:23
Same issue here on Mac OS Catalina 10.15.3 and docker 2.2.0.4...

**Comment by stephen-turner** [comment] 2020-03-30 13:15
We have an Edge release coming out this week that will fix this.

**Comment by danshumaker** [comment] 2020-04-02 14:42
Still getting this error on newest versions (updated this morning)

macOS Version: 10.15.4
Docker for Mac: 2.2.0.5 (43884)

engine 19.03.8
compose 1.25.4

**Comment by friek** [comment] 2020-04-02 14:46
Well, that would be because 2.2.0.5 is not an edge release. As @stephen-turner already mentioned, this problem will be fixed in an Edge release first. See also the [release notes](https://docs.docker.com/docker-for-mac/edge-release-notes/).

**Comment by danshumaker** [comment] 2020-04-02 14:49
> Well, that would be because 2.2.0.5 is not an edge release. As @stephen-turner already mentioned, this problem will be fixed in an Edge release first. See also the [release notes](https://docs.docker.com/docker-for-mac/edge-release-notes/).

Cool, thx @friek , I'll try that now.

**Comment by stephen-turner** [comment] 2020-04-02 14:56
Yes, sorry, the patch was too big to port to the Stable branch. It would be good to get confirmation from anyone who's tried it on Edge 2.2.3.0 though.

**Comment by hhoechtl** [comment] 2020-04-02 14:56
It's very likely that this patch caused this error: https://github.com/docker/for-mac/issues/4415

**Comment by danshumaker** [comment] 2020-04-02 15:04
Just tried the 2.2.3.0 edge case and it does work.

**Comment by hhoechtl** [comment] 2020-04-02 15:29
5 of our employees have the issue https://github.com/docker/for-mac/issues/4415 (that's 100%).

**Comment by stephen-turner** [comment] 2020-04-02 18:12
The original issue is fixed, so I'm going to close this ticket. The discussion about the new issue can continue in #4415.

**Closed by stephen-turner** 2020-04-02 18:12 UTC
Labels: status/1-acknowledged, version/2.2.0.0

**Comment by bobland1** [comment] 2020-04-10 13:58
I am having this same issue with Docker for windows, will there be a fix for that?

**Comment by stephen-turner** [comment] 2020-04-14 08:35
@bobland1 Yes, it's already fixed on Edge, the ticket number is for-win#5546.

**Comment by lauripiisang** [comment] 2020-05-12 07:11
can anyone confirm, is this fixed on 2.3.0.2 ?

**Comment by richard-axual** [comment] 2020-05-12 07:19
I've tested it on my mac and it seems to be resolved

**Comment by pm-proctors** [comment] 2020-05-12 07:20
Can confirm it is resolved for me on 2.3.0.2.

**Comment by blueimp** [comment] 2020-05-12 07:34
It's part of the release notes for `2.3.0.2`:
> Fixed an issue where a container port could not be exposed on a specific host IP. See docker/for-mac#4209.

**Comment by hollie** [comment] 2020-05-12 07:40
Yes, confirming too that this is fixed as per the release notes and that it is working fine on my machine.

**Comment by lindycoder** [comment] 2020-05-12 13:14
It does work, but as reported in #4541 the network settings, in `docker inspect` or `docker ps` does not match the requested `ip:port`.

**Comment by tecnobrat** [comment] 2020-05-13 18:59
Can someone link to the PRs/Issues that fixed this bug?

I have a feeling that this was fixed in a way that only works if you're running docker/docker-compose from within OSX.  I can't seem to get this to work if I'm inside a container (with the docker socket mounted to the container)

My theory is that there is some sort of logic that detects the OS docker-compose/docker is running on.

**Comment by tecnobrat** [comment] 2020-05-13 20:07
So after debugging, I can confirm that running docker/docker-compose from linux, launches the containers differently (even though the docker server is running inside the docker-for-mac VM).

Adding this to my docker-compose.yml appears to make it work when starting from within a linux-based container:

```
ports:
  - "127.0.0.1::80"
  - "127.0.0.1::443"
labels:
  "desktop.docker.io/ports/443/tcp": "10.156.156.1:443"
  "desktop.docker.io/ports/80/tcp": "10.156.156.1:80"
```

After doing that, the containers launched within linux have the same details as the ones launched from the mac host, and it works properly.

**Comment by tecnobrat** [comment] 2020-05-14 14:11
A docker engineer clarified on another issue: https://github.com/docker/for-mac/issues/4541#issuecomment-628252116

**Comment by maietta** [comment] 2020-05-21 17:00
> Still getting this error on newest versions (updated this morning)
> 
> macOS Version: 10.15.4
> Docker for Mac: 2.2.0.5 (43884)
> 
> engine 19.03.8
> compose 1.25.4

Yep, mine is 19.03.9, a minor revision also with same problem.

**Comment by alvarow** [comment] 2020-05-21 17:08
> Yep, mine is 19.03.9, a minor revision also with same problem.

Docker Desktop Community 2.3.0.2 solves it. See release notes at https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2302

**Comment by GerBreOwn** [comment] 2020-06-27 14:05
I am running on a Raspberry Pi and am trying to assign these ports to a DigitalOcean droplet with a static IP. I have tried opening the ports with UFW. 
My Docker is: Client: Docker Engine - Community  Version: 19.03.12 and Docker-compose is version 1.26.0, build unknown.
I am getting the same errors on the **cheap** Raspberry Pi as others with **EXPENSIVE** macs are getting.
Is there a fix for this problem for all Docker systems???
Thanks
