### ISSUE TITLE
I have no idea how this happened, issue on update

### ISSUE THREAD

**Issue by dheerajchand** [docker/for-mac#310] opened 2016-08-16 19:13 UTC
### Steps to reproduce

1. Update Docker Beta

### Expected behavior

Docker Beta would update without error.

### Actual behavior

Error reported, leads to this screen

### Information

```
Diagnostic ID: 3DBDE51C-28A2-4A17-9AE8-436D40D1C684
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment] 2016-08-17 09:10
This is likely caused by the ongoing issues with macOS Sierra Beta and golang. This is a duplicate of #64.

**Closed by dsheets** 2016-08-17 09:10 UTC

**Comment by djs55** [comment] 2016-09-15 16:19
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
