### ISSUE TITLE
Docker Desktop 4.5 doesn't display full menu on macOS 12.2.1

### ISSUE THREAD

**Issue by cloudgeek7** [docker/for-mac#6206] opened 2022-02-27 16:37 UTC
Unable to view the full menu after upgrading Docker Desktop to 4.5 on macOS 12.2.1

  - [yes ] I have tried with the latest version of Docker Desktop

### Expected behaviour
To be able to see full menu from the Docker-desktop icon like the one mentioned here:
https://www.docker.com/blog/new-docker-menu-improved-release-highlights-with-docker-desktop-4-5/

### Actual behaviour
I only see the menu like the one below with limited options
<img width="319" alt="docker-desktop-icon-issue" src="https://user-images.githubusercontent.com/37217316/155890895-160b09be-118f-4f36-8a1d-fc7f91acf135.png">

### Information

  - macOS Version: macOS Monterey Version 12.2.1 (21D62)
  - Intel chip or Apple chip: Intel Iris Pro 1536 MB
  - Docker Desktop Version: 4.5

**Comment by cloudgeek7** [comment] 2022-02-27 16:44
The problem seems to be intermittent. Sometimes, I see the full menu (if I quit and restart docker-desktop). There is one more user who reported the same issue in our Docker community slack too.

**Comment by StefanScherer** [comment] 2022-02-28 08:42
@cloudgeek7 Thanks for the report. Could you send diagnostics that can be sent from the command line as well? https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal

**Comment by cloudgeek7** [comment] 2022-02-28 11:41
` ~   /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check                                                                                                                   INT ✘  12:39:35
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.`

**Comment by StefanScherer** [comment] 2022-02-28 13:31
Thank you, I'm looking into the diagnostics. So far the frontend can't communicate with the backend and therefore "thinks" you haven't accepted the license terms and restricts the menu. I'm digging deeper to find the root cause.

**Comment by StefanScherer** [comment] 2022-02-28 13:40
I'm consolidating all reports, looks like #6192 is about the same issue. I'll close this one as a duplicate, please follow the discussion in the other ticket when we found out more.

**Closed by StefanScherer** 2022-02-28 13:40 UTC
Labels: version/4.5.0
