### ISSUE TITLE
docker cli becomes unresponsive

### ISSUE THREAD

**Issue by raszi** [docker/for-mac#933] opened 2016-11-11 08:37 UTC
### Expected behavior

`docker ps` should list the running containers

### Actual behavior

`docker ps` is not responding

### Information

Diagnostic ID: `5AAC807B-5101-4540-B057-C1FBD773E8D7`

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/5AAC807B-5101-4540-B057-C1FBD773E8D7/20161111-092923.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior

1. Verify that `docker ps` works
2. Put your computer to sleep
3. `docker ps` will wait indefinitely, the JSON socket is not responding either.

```
curl -v --unix-socket /var/run/docker.sock http:/containers/json
*   Trying /var/run/docker.sock...
* Connected to http (/Users/ikaraszi/Library/Containers/com.docker) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
>
```

**Comment by raszi** [comment] 2016-11-11 08:38
It could be related to #927

**Comment by raszi** [comment] 2016-11-11 08:39
And #921

**Comment by brnewby602** [comment] 2016-11-11 21:07
I am seeing the same behavior.  CLI became unresponsive, restarted docker and now it hangs on 'Docker starting...'

Diagnostic ID: 070F4D24-1D22-4380-B222-509EDEE087C7

**Comment by ijc25** [comment] 2016-11-14 10:28
@raszi Thanks for your report. I'm investigating.

@brnewby602 your logs do not seem to indicate the same issues, which is unsurprising since there are a variety of possible reasons for the symptom "docker does not start". You may have been suffering from #819 which was resolved in v1.12.3. I'm unsure if you are still seeing this after your factory reset, if so then please open a new ticket specifically for your case.

**Comment by ijc25** [comment] 2016-11-14 11:23
@raszi We have a workaround in place for older versions of OSX (10.10.x and earlier 10.11.x) which suffered from a bug on the OSX Hypervisor.framework (ACPI crashes after resume). The workaround is to freeze the hyperkit processes corresponding to the virtual CPUs around sleep.

However we also believe this workaround is itself responsible for at least some of the issues seen after resume even on newer OSX versions where the ACPI issue is no longer present. With newer versions of Docker for mac the default is now to no longer to apply the workaround for OSX 10.12 and 10.11.6 onwards, but this change is not made retrospectively on upgrades from older versions of docker for mac.

Your logs show that the workaround is still active and that you are running 10.11.6 so it would be worth trying to disable the workaround by doing the following:
```
cd ~/Library/Containers/com.docker.docker/Data/database
git reset --hard
echo "please do not freeze" > com.docker.driver.amd64-linux/on-sleep
git commit -a -m "disable freeze workaround"
```
(see also https://github.com/docker/for-mac/issues/85#issuecomment-245877874)

If you see similar behaviour after you have disabled the old workaround then please do let us know. In the meantime I will close this issue assuming this addresses things for you.

**Comment by raszi** [comment] 2016-11-14 11:58
@ijc25 thanks for the quick turnaround.

I just wanted to note that the mentioned directory contained a lots of changes in my case:

```
## master
D  com.docker.driver.amd64-linux/disk/full-sync-on-flush
D  com.docker.driver.amd64-linux/etc/docker/daemon.json
D  com.docker.driver.amd64-linux/etc/hostname
D  com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt
D  com.docker.driver.amd64-linux/etc/sysctl.conf
D  com.docker.driver.amd64-linux/expose-docker-socket
D  com.docker.driver.amd64-linux/filesystem
D  com.docker.driver.amd64-linux/hypervisor
D  com.docker.driver.amd64-linux/insecure-registry
D  com.docker.driver.amd64-linux/memory
D  com.docker.driver.amd64-linux/mounts
D  com.docker.driver.amd64-linux/native/boot-protocol
D  com.docker.driver.amd64-linux/native/port-forwarding
D  com.docker.driver.amd64-linux/native/uefi-boot-disk
D  com.docker.driver.amd64-linux/ncpu
D  com.docker.driver.amd64-linux/network
D  com.docker.driver.amd64-linux/on-sleep
D  com.docker.driver.amd64-linux/proxy-system/exclude
D  com.docker.driver.amd64-linux/proxy-system/http
D  com.docker.driver.amd64-linux/proxy-system/https
D  com.docker.driver.amd64-linux/proxy-verbose
D  com.docker.driver.amd64-linux/proxy/exclude
D  com.docker.driver.amd64-linux/proxy/http
D  com.docker.driver.amd64-linux/proxy/https
D  com.docker.driver.amd64-linux/schema-version
D  com.docker.driver.amd64-linux/slirp/dns
D  com.docker.driver.amd64-linux/slirp/docker
D  com.docker.driver.amd64-linux/slirp/host
D  com.docker.driver.amd64-linux/slirp/max-connections
D  com.docker.driver.amd64-linux/state/last-shutdown-time
D  com.docker.driver.amd64-linux/state/last-start-time
D  com.docker.driver.amd64-linux/vmnet-simulate-failure
```

**Comment by ijc25** [comment] 2016-11-14 14:58
@raszi thanks for the info. I think that is nothing to worry about but I'll ask around to be sure. If you don't hear from me again please assume everything is ok.

**Comment by ijc25** [comment] 2016-11-14 15:07
@raszi are you sure you performed the `git reset --hard` step before `echo` and `git commit`?

**Comment by raszi** [comment] 2016-11-14 15:48
The git status was before the reset of course. :)

**Comment by ijc25** [comment] 2016-11-14 15:51
Sorry, that wasn't obvious, but that being the case there is nothing to worry about here I think.

**Comment by brnewby602** [comment] 2016-11-14 16:13
I was on 1.12.3.  I had first attempted to execute the docker ps command and it just hung.  I restarted docker and then it never would start, just hung on 'Docker starting' (including reboot).  Performing the factory reset did resolve it.

**Comment by HerbCSO** [comment] 2016-11-15 17:56
I've been having the same issues and applied the workaround from [this comment](https://github.com/docker/for-mac/issues/933#issuecomment-260311428) - will comment here if I run into problems again.

**Comment by raszi** [comment] 2016-11-16 08:02
The same issue happened again with the applied workaround.

**Comment by raszi** [comment] 2016-11-16 10:08
And again :(

*Diagnostic ID*: 5AAC807B-5101-4540-B057-C1FBD773E8D7

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/5AAC807B-5101-4540-B057-C1FBD773E8D7/20161116-110459.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by ijc25** [comment] 2016-11-16 16:03
@raszi thanks for the report and additional diagnostics. Looking at your logs it seems like not long after waking your DNS settings changed (not unexpected, you probably moved to another location) and we rebooted the VM in order to apply the change.

Unfortunately it seems like something went wrong during the reboot process and things didn't recover. I've escalated this case to a new internal issue.

**Comment by HerbCSO** [comment] 2016-11-16 18:52
I've also run into problems after removing the workaround as per [this comment](https://github.com/docker/for-mac/issues/933#issuecomment-260311428).

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/2D55EB1E-B038-4F1C-B3A6-69A540BF3700/20161116-184125.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

It's entirely possible that I had DNS changes as well - I'm usually connected to a VPN that resets when my computer wakes up from sleep.

**Comment by b0elter** [comment] 2016-11-17 17:14
I think I may also be experiencing this issue after DNS/route/VPN changes.

> Unfortunately it seems like something went wrong during the reboot process and things didn't recover.

Is there anything I can inspect to confirm my issue is related to DNS/route/VPN?

I also had the following occur when trying to diagnose:
`Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)`

**Comment by ijc25** [comment] 2016-11-18 13:47
@b0elter unfortunately the diagnostics program sometimes incorrectly reports that it has failed to upload (we have an internal issue already to fix this) so it is worth providing your diagnostic ID anyway.

**Comment by sandrodz** [comment] 2016-12-13 10:52
I'm seeing this issue on daily bases, it is becoming super annoying.

**Comment by raszi** [comment] 2017-01-01 11:46
It started to appear again in the new version: `1.12.5 (14777)`

_Diagnostic ID_: `5AAC807B-5101-4540-B057-C1FBD773E8D7`

```
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/5AAC807B-5101-4540-B057-C1FBD773E8D7/20170101-124416.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by raszi** [comment] 2017-01-01 11:50
Restarting docker fixed the issue.

I still have the `com.docker.driver.amd64-linux/on-sleep` in place, so that did not really help, but the previous version did not have this issue (or for some reason it did not cause these hiccups on my machine).

**Comment by samoht** [comment] 2017-01-31 14:51
@raszi your log contains:

```
Dec 28 18:36:05 istkarm2 Docker[com.docker.driver.amd64-linux][573] <Notice>:
        Assertion failed: (nr == 1), function kick_rx, file src/pci_virtio_sock.c, line 765.
```

which is similar to  docker/hyperkit#50 

Can you try to upgrade to 1.13 to see if the issue is till there? Thanks!

For the other ones on the thread (@b0elter, @HerbCSO, brnewby602) please open a new issue with a diagnostic ID. This will help us to keep track of individual issue (and we will de-duplicate the issues ourself if we find that the root causes are indeed identical). Thanks!

**Comment by HerbCSO** [comment] 2017-01-31 15:36
FYI, I did file #1159 after the upgrade to 0.13.0 broke for me, but after [this fix](https://github.com/docker/for-mac/issues/1159#issuecomment-274461041) things have worked fine for me since then. Thanks!

**Comment by samoht** [comment] 2017-01-31 15:47
@HerbCSO great to hear, thanks again for your report!

**Comment by dave-tucker** [comment] 2017-02-15 13:27
@raszi can you confirm if the upgrade to 1.13 fixed this for you?

**Comment by timcosta** [comment] 2017-02-15 15:11
I am on the beta release track, and have not seen this issue for some time now. I actually can't remember the last time i experienced it.

**Comment by rogaha** [comment] 2017-03-02 12:13
thanks for your feedback @HerbCSO. I'm closing this as it seems to be fixed in the newer versions.

**Closed by rogaha** 2017-03-02 12:13 UTC
Labels: area/hyperkit, osx/10.11.x, status/0-more-info-needed, status/1-acknowledged, version/1.12.3

**Comment by raszi** [comment] 2017-03-02 13:18
Same here, I could not see that for a long time. If it appears again I'll write a comment here.
