### ISSUE TITLE
docker import image failed : Error response from daemon: exec: "xz": executable file not found in $PATH

### ISSUE THREAD

**Issue by krikoon73** [docker/for-mac#5324] opened 2021-02-09 15:47 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 20DCE5E5-D0A8-46CE-B09D-9CDBF125BEE2/20210209153809

### Expected behavior
Importing container image from specific file (Arista ceos) : cEOS-lab-4.25.2F.tar.xy
### Actual behavior
```
> docker import cEOS-lab-4.25.2F.tar.xy ceosimage:ceos-4.25.2F
Error response from daemon: exec: "xz": executable file not found in $PATH
> xz --version
xz (XZ Utils) 5.2.5
liblzma 5.2.5
> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: RUAA:I7CS:M6GK:RGMU:E3UH:KOF4:XP3J:FNBJ:2SSP:DOMN:XKOC:GNIV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
>
> sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```
### Information

  - macOS Version: 11.1
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment] 2021-02-09 16:08
Thanks for reporting

```console
> xz --version
xz (XZ Utils) 5.2.5
liblzma 5.2.5
```

That's on the macOS host; I think what's needed is to have `xz` installed inside the VM in which the daemon runs (which is where the file would be extracted during import).

using `nsenter` to look what's in the VM, it looks like it's not present indeed;

```console
$ docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh -c 'gunzip --help'
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: gunzip [-cfkt] [FILE]...

Decompress FILEs (or stdin)

	-c	Write to stdout
	-f	Force
	-k	Keep input files
	-t	Test file integrity

$ docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh -c 'xz --version'
sh: xz: not found
```

**Comment by thaJeztah** [comment] 2021-02-09 16:16
Oh, actually , wrong container inside the vm; daemon runs in another container inside the VM, but confirmed that it also doesn't have `xz` installed.

**Comment by stephen-turner** [comment] 2021-02-09 16:20
Thanks for the report. This is a dupe of #5271, so I'm going to close this copy.

**Closed by stephen-turner** 2021-02-09 16:20 UTC
Labels: kind/enhancement, version/3.1.0
