### ISSUE TITLE
Error iptables FORWARD: Another app is currently holding the xtables lock

### ISSUE THREAD

**Issue by alexmac** [docker/for-mac#285] opened 2016-08-15 19:57 UTC
### Steps to reproduce

Seems correlated with a compose file that has lots of containers (20+) starting up, but it is intermittent
### Expected behavior

Containers should start without failure
### Actual behavior

docker-compose gives the following error for certain containers during the "creation" stage:

Cannot start service notes_db: driver failed programming external connectivity on endpoint deployment_notes_db_1 (e02bcc276684b4b70b85d462caed48dee2110bf1e6454fcb3b91253745e2c15d): Error iptables FORWARD: Another app is currently holding the xtables lock; waiting (1s) for it to exit
### Information

```
Diagnostic ID: E8C9B149-C537-4F80-B801-39B213B60E6F
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by samoht** [comment] 2016-10-10 09:57
Could you publish a way to reproduce that issue easily? Thanks!

**Comment by samoht** [comment] 2016-10-12 18:58
@dsheets have you seen that one before?

Detected symptom of problem 'invariant-violated' in E8C9B149-C537-4F80-B801-39B213B60E6F/20160815-125229.

An invariant within the code of one of the components was not held. Docker needs to be restarted.

May be related to docker/for-mac#89

The following log matches:
```
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.driver.amd64-linux][7165] <Notice>: VM: 2016-08-10 22:23:41 +0000 UTC daemon.info vsudd: Connection 4387 to: 2376 from: 00000000
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.driver.amd64-linux][7165] <Notice>: VM: 2016-08-10 22:23:41 +0000 UTC daemon.info vsudd: Connection 4388 to: 2376 from: 00000000
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.osxfs][7162] <Notice>: Volume.stop 5c0018fb91429851c19b600678f785368526f876765642067d3831b4929c913d (paths = [/Users/alex/.aws/credentials, /Users/alex/.aws/credentials])
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.osxfs][7162] <Error>: WATCH SUBSCRIBER REMOVAL INVARIANT VIOLATED
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.driver.amd64-linux][7165] <Notice>: VM: 2016-08-10 22:23:41 +0000 UTC daemon.info vsudd: 4204 Done. read: 310 written: 56039
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.driver.amd64-linux][7165] <Notice>: VM: 2016-08-10 22:23:41 +0000 UTC daemon.info vsudd: Connection 4389 to: 2376 from: 00000000
Aug 10 15:23:41 Alexanders-MBP Docker[com.docker.driver.amd64-linux][7165] <Notice>: VM: 2016-08-10 22:23:41 +0000 UTC kern.info kernel: br-849133a84293: port 2(veth427ed7b) entered disabled state
```

**Comment by justincormack** [comment] 2016-11-02 10:25
This is an upstream docker issue tracked here https://github.com/docker/docker/issues/26111

**Comment by dsheets** [comment] 2016-11-02 18:15
The invariant violation is not the root cause of this issue and is most likely harmless. It was fixed in the recently released Beta 29.3.

**Comment by samoht** [comment] 2016-11-03 21:40
Detected symptom of problem 'xtables-lock-held' in E8C9B149-C537-4F80-B801-39B213B60E6F/20160815-125229.

There is a global lock which protects the host firewall rules. Under heavy load, contention for this lock increases and eventually `iptables` commands time out. This failure is intermittent and a workaround is to repeat the failed command.

May be related to docker/for-mac#285 docker/docker#26111

**Closed by samoht** 2016-11-03 21:40 UTC
Labels: area/docker, area/network, kind/bug, osx/10.11.x, status/1-acknowledged, version/beta22

**Comment by caneraydinbey** [comment] 2017-05-30 18:41
I restarted docker and it worked
`sudo service docker stop`
then
`sudo service docker start`

**Comment by Mr-Sourdough** [comment] 2019-10-04 11:59
In my case it turned out that I had `ufw` enabled. Disabled it with `sudo ufw disable`.
