### ISSUE TITLE
Docker login to registry via VPN on Macbook M1 - Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by Laurens-T** [docker/for-mac#5293] opened 2021-01-25 15:23 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  Diagnostics ID: 

### Expected behavior
I'm trying to login to a remote registry that can be accessed via a VPN. I expected that this would work without any issues:
```bash
$ docker login the-remote-vpn-registry.com  # not the real registry
Username: ***
Password: ***
Login Succeeded
```

### Actual behavior
But instead I get 
```bash
$ docker login the-remote-vpn-registry.com
Username: ***
Password: ***
Error response from daemon: Get the-remote-vpn-registry.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Information

  - macOS Version: 11.1 (20C69)
  - MacBook Pro (13-inch, M1, 2020)

There is no issue with my VPN on M1 since I can access other services behind the same VPN. Trying to `curl` to the remote registry from the terminal return a response:
```bash
$ curl https://the-remote-vpn-registry.com
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
```

I have also noticed that I can't `curl` from inside a running container:
```bash
$ docker run --rm -it alpine
/ # apk add curl
OK: 8 MiB in 19 packages
/ # curl https://the-remote-vpn-registry.com
curl: (28) Failed to connect to https://the-remote-vpn-registry.com: Operation timed out
/ # curl google.com
<HTML><HEAD>...</BODY></HTML>
```

### Diagnostic logs

```
Docker for Mac: version 0.0.0 (1)  # M1 preview
Engine: 20.10.0
Compose: 1.27.4
Kubernetes: v1.19.3
Notary: 0.6.1
Credential helper: 0.6.3
Snyk: v1.424.4
```

### Steps to reproduce the behavior
- Install Docker Desktop preview  on Apple Macbook M1
- Connect to VPN
- Login to a remote registry

**Comment by mrteera** [comment] 2021-01-26 08:51
I have the same problem. I think we need to wait the next preview release.

**Comment by fkoehler** [comment] 2021-01-27 23:11
Same issue here

**Comment by Actonian1187** [comment] 2021-01-29 15:29
I have the same issue on my M1 MacBook. After disconnecting from the VPN I can login to AWS ECR.
On my Intel MacBook this works on or off VPN.
I want to add that is also affects pulling images.

> $ docker pull mysql
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by TCiPongor** [comment] 2021-02-01 14:03
I have the same issue on my M1 MacBook.
After disconnecting from the VPN I can login to hub and pull images.

**Comment by somax** [comment] 2021-02-01 15:26
Same issue on my M1 MBP when I use OpenVPN(Tunnelblick).  but with L2TP VPN is ok.

**Comment by bkiac** [comment] 2021-02-01 17:21
Same issue with WireGuard / Mullvad VPN

**Comment by blackbass1988** [comment] 2021-02-02 13:05
+1

**Comment by drastega** [comment] 2021-02-02 14:30
The same problem with my M1 MacBook and Tunnelblick

**Comment by JensPauwels** [comment] 2021-02-02 15:31
Same issue with with Tunnelblick and M1 MacBook

**Comment by morenocarullo** [comment] 2021-02-03 13:21
same issue here

**Comment by klim-wish** [comment] 2021-02-03 17:46
same issue with GlobalProtect VPN and M1 Mac mini.

**Comment by DevaraIchche** [comment] 2021-02-05 03:42
Same issue on Mac M1

**Comment by sailor-z** [comment] 2021-02-06 16:31
Same issue on Mac M1

**Comment by areman** [comment] 2021-02-07 14:41
+1

**Comment by malekmajkl** [comment] 2021-02-07 19:31
ran into same issue.
Macbook Air M1
VPN cisco 4.9.04043
1st try:
`
which docker
/usr/local/bin/docker

docker login -u ci my-company-registry
Password: 
Error response from daemon: Get my-company-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

2nd try:
`
docker run --privileged --name docker-local -v /opt/_docker:/var/lib/docker -d docker:dind

created alias in .zshrc 
alias docker="docker exec -it docker-local /usr/local/bin/docker"

which docker
docker: aliased to docker exec -it docker-local /usr/local/bin/docker

docker login -u ci my-company-registry
Password: 
Error response from daemon: Get my-company-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

no luck :( hope someone take look at it ASAP

**Comment by MonaxGT** [comment] 2021-02-09 13:41
Hi all! 
I have the same problem on my M1 MacBook.

**Comment by gabrieloshiro** [comment] 2021-02-12 00:08
Same issue on

- macos big sur 11.2.1
- Docker 3.1.0 (60984)

**Comment by maxbrizolla** [comment] 2021-02-16 11:25
Hi,

I have the same problem.

macOS BigSur 11.2.1
Docker 3.1.0 (60984)
Forticlientvpn

**Comment by ppraisethesun** [comment] 2021-02-16 11:40
Same issue on BigSur 11.2.1 
Docker version 20.10.3, build 48d30b5
Docker desktop 3.1.0
OpenVPN

**Comment by IrinaSurma** [comment] 2021-02-23 12:19
+1

**Comment by stephen-turner** [comment] 2021-02-23 17:23
https://github.com/docker/for-mac/issues/5208#issuecomment-767758990 may be helpful to some people watching this thread.

**Comment by ppraisethesun** [comment] 2021-02-23 18:20
> [#5208 (comment)](https://github.com/docker/for-mac/issues/5208#issuecomment-767758990) may be helpful to some people watching this thread.

I managed to log in, but trying to pull any image from that repository still fails with
 ```
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by tangledhelix** [comment] 2021-02-26 17:53
I see a lot of people saying they have this issue with a company registry, but I'm getting this trying to auth to docker hub. I use a VPN, but it happens whether the VPN is connected or not.

I removed my ~/.docker/ directory and restarted Docker, and I also did a `docker logout`, neither helped.

```
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This is on the Apple Silicon tech preview (3.1.0 (60984)).

**Comment by paulrwest** [comment] 2021-03-02 13:19
Same issue here.

Mac Pro M1, Big Sur 11.2.2
Docker version 20.10.3, build 48d30b5
OpenVpn

**Comment by javi-villa** [comment] 2021-03-08 08:38
+1 
BigSur 11.1
Docker version 20.10.3, build 48d30b5
OpenVpn

**Comment by filippetroviccc** [comment] 2021-03-09 14:06
Same for me also

Mac Pro M1, Big Sur 11.2.2
Docker version 20.10.3, build 48d30b5
OpenVpn

**Comment by Borozenets** [comment] 2021-03-13 13:59
+1

**Comment by Forus0322** [comment] 2021-03-16 09:57
Same issue on Mac M1

MacBook Pro M1, Big Sur 11.2.3
Docker version 20.10.3, build 48d30b5

**Comment by nmauduit** [comment] 2021-03-16 12:31
+1

MacBook Pro M1, Big Sur 11.1
Docker version 20.10.3, build 48d30b5
With fortinet vpn SSL 

Work without VPN

**Comment by vladimirka9** [comment] 2021-03-18 15:04
+1

**Comment by pgrzesiecki** [comment] 2021-03-19 10:46
same problem, this makes me impossible to work on apple mac m1

**Comment by czhDavid** [comment] 2021-03-19 10:49
Could we maybe lock this thread? I have subscribe to this, because I wan't to know when is it resolved. By I am getting a lot of spam from people who have some kind of need to post comments that do not move this issue forward and are not helpful in any way.

**Comment by ilyaglow** [comment] 2021-03-19 10:56
Seems related to #5322 which contains a workaround

**Comment by stephen-turner** [comment] 2021-03-26 16:32
Everyone watching this thread, please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves your VPN problems (and whether it causes any new problems!). Thank you.

Also we have too many tickets about VPNs, so I'm going to resolve this one as a dupe of #5208.

**Closed by stephen-turner** 2021-03-26 16:32 UTC
Labels: area/m1, version/11.1

**Comment by javi-villa** [comment] 2021-03-30 22:53
It works for me!
