### ISSUE TITLE
Docker Desktop with experimental support

### ISSUE THREAD

**Issue by danielchemko** [docker/for-mac#5702] opened 2021-05-18 16:49 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features

I attempt a docker login to a private repo (AWS ECR) and when in experimental mode, the container seems to be mapping all DNS requests to a provider which doesn't forward to my Mac's DNS servers? See below in reproduction. The mapped host for my AWS ECR is "192.168 ".. so either you're trying to proxy to a non-reachable service or something?

When I switch back to non-experimental mode, everything works as expected.

### Expected behavior

AWS ECR login succeeds

### Actual behavior

AWS ECR connection fails because its mapped to a non-reachable service (DNS or unreachable proxy host)

### Information

Real PC network 192.168.10.0/24

### Steps to reproduce the behavior

  1. Enable experimental 
  2. Docker login my-repo
  3. See error Error response from daemon: Get my-repo:port : proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: no route to host

**Comment by stephen-turner** [comment] 2021-05-19 10:40
Thanks for the report, I think this is a dupe of #5663. There is an experimental build in there that you can try.

**Closed by stephen-turner** 2021-05-19 10:40 UTC
