### ISSUE TITLE
DfM quits without warning mid-way through build

### ISSUE THREAD

**Issue by alexellis** [docker/for-mac#1574] opened 2017-04-27 14:19 UTC
### Expected behavior

Complete `docker build`

### Actual behavior

The build quits mid-way without any error or warning.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

This might be hard to repro - I have reset DfM several times.

```
37965642-5F3B-49D9-B0D3-36277741A685

Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/37965642-5F3B-49D9-B0D3-36277741A685/20170427-151805.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by dsheets** [comment] 2017-04-27 14:49
I see

```
Apr 27 14:17:52 moby root: 2017-04-27 14:17:52.649047 I | http: panic
serving @: runtime error: slice bounds out of range
Apr 27 14:17:52 moby root: goroutine 519 [running]:
Apr 27 14:17:52 moby root: net/http.(*conn).serve.func1(0xc42007f580)
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/net/http/server.go:1491 +0x12a
Apr 27 14:17:52 moby root: panic(0x17cb5e0, 0xc4200120d0)
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/runtime/panic.go:458 +0x243
Apr 27 14:17:52 moby root:
github.com/docker/docker/builder/dockerfile.run(0xc4221b6a20,
0xc42201b0c0, 0x1, 0x1, 0x0, 0xc422011260, 0x2f, 0x0, 0x0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:457
+0x98b
Apr 27 14:17:52 moby root:
github.com/docker/docker/builder/dockerfile.(*Builder).dispatch(0xc4221b6a20,
0x2, 0x6, 0xc4203d2150, 0xc420f4b1b0, 0x1)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:154
+0x9e0
Apr 27 14:17:52 moby root:
github.com/docker/docker/builder/dockerfile.(*Builder).build(0xc4221b6a20,
0x260cca0, 0xc4211e1fc0, 0x260cc60, 0xc4211e1fe0, 0x260c0a0,
0xc4211e1fa0, 0x0, 0x0, 0x0, ...)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/builder/dockerfile/builder.go:241
+0x33c
Apr 27 14:17:52 moby root:
github.com/docker/docker/builder/dockerfile.(*BuildManager).BuildFromContext(0xc4201b8240,
0x7fb114c58088, 0xc421158240, 0x261a5e0, 0xc421158100, 0x0, 0x0,
0xc42085f680, 0x260c0a0, 0xc4211e1fa0, ...)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/builder/dockerfile/builder.go:110
+0x308
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc4207dbf20,
0x7fb114c58088, 0xc421158240, 0x2625860, 0xc4221acd00, 0xc4216cd2c0,
0xc42129fb90, 0x0, 0x0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/router/build/build_routes.go:214
+0x87f
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/router/build.(*buildRouter).(github.com/docker/docker/api/server/router/build.postBuild)-fm(0x7fb114c58088,
0xc421158240, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0xc421297840, 0x1)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/router/build/build.go:27
+0x69
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7fb114c514c0,
0xc42129fc80, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0x0, 0x0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/router/local.go:84
+0x104
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7fb114c514c0,
0xc42129fc80, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0x7fb114c514c0, 0xc42129fc80)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27
+0xd8
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fb114c514c0,
0xc42129fbf0, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0xc4211b5cc0, 0xc421005290)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/middleware/version.go:48
+0x5b4
Apr 27 14:17:52 moby root:
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7fb114c514c0,
0xc42129fbf0, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0x756ea127720458, 0xc4201529b8)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/pkg/authorization/middleware.go:54
+0x923
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7fb114c514c0,
0xc42129fbf0, 0x2625860, 0xc4221acd00, 0xc4216cd2c0, 0xc42129fb90,
0x7fb114c514c0, 0xc42129fbf0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/middleware/debug.go:25
+0x9bf
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2625860,
0xc4221acd00, 0xc4216cd2c0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/server.go:140 +0x247
Apr 27 14:17:52 moby root:
net/http.HandlerFunc.ServeHTTP(0xc420951920, 0x2625860, 0xc4221acd00,
0xc4216cd2c0)
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/net/http/server.go:1726 +0x44
Apr 27 14:17:52 moby root:
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420485270,
0x2625860, 0xc4221acd00, 0xc4216cd2c0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103
+0x255
Apr 27 14:17:52 moby root:
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420aacaf0,
0x2625860, 0xc4221acd00, 0xc4216cd2c0)
Apr 27 14:17:52 moby root:
^I/go/src/github.com/docker/docker/api/server/router_swapper.go:29
+0x70
Apr 27 14:17:52 moby root:
net/http.serverHandler.ServeHTTP(0xc4202a6200, 0x2625860,
0xc4221acd00, 0xc4216cd2c0)
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/net/http/server.go:2202 +0x7d
Apr 27 14:17:52 moby root: net/http.(*conn).serve(0xc42007f580,
0x2627520, 0xc4211580c0)
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/net/http/server.go:1579 +0x4b7
Apr 27 14:17:52 moby root: created by net/http.(*Server).Serve
Apr 27 14:17:52 moby root: ^I/usr/local/go/src/net/http/server.go:2293 +0x44d
```

so I think this is a duplicate of #1550.

**Closed by dsheets** 2017-04-27 14:49 UTC
