### ISSUE TITLE
Slow disk and/or network I/O after 1.12.0

### ISSUE THREAD

**Issue by hodgesmr** [docker/for-mac#1211] opened 2017-01-25 01:18 UTC
### Expected behavior
Unit and integration tests that do network and disk I/O should mimic native performance.

### Actual behavior
My application's test suit that does network and disk I/O is severely degraded **after** `1.12.0`

### Information

I use Docker primarily for local development. I've been relying heavily on version `1.12.0` because anything after that `1.12.1` - `1.13.*` has _severe_ performance degradation as exhibited by my application's test suite.

It's a simple Django app that does network calls and Postgresql I/O via tests. On `1.12.0` my suite runs around _270.150 seconds_. Any version after that shows numbers around _1180.750 seconds_.

I keep relying on `1.12.0` for this reason.

**Comment by justincormack** [comment] 2017-01-25 09:27
cc @djs55 is this sync related?

**Comment by djs55** [comment] 2017-01-25 10:21
I can't be sure without a reproduction but it could be this: https://github.com/docker/for-mac/issues/668#issuecomment-250406582

Summary is: when Docker 1.12.0 sends a `fsync`/`flush` command to the storage (e.g. to commit a transaction to the disk) this was ignored, meaning that transactions in a database like postgres could be lost if the system lost power. This bug was fixed in 1.12.1: now a `fsync`/`flush` from the VM issues [fsync](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/fsync.2.html) on the host with the `F_FULLFSYNC` option. The [macOS docs](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/fsync.2.html) say:

> For applications that require tighter guarantees about the integrity of their data, Mac OS X provides the F_FULLFSYNC fcntl.  The F_FULLFSYNC fcntl asks the drive to flush all buffered data to permanent storage.  Applications, such as databases, that require a strict ordering of writes should use F_FULLFSYNC to ensure that their data is written in the order they expect.  Please see fcntl(2) for more detail.

The behaviour of 1.12.1+ is correct but slow.

Since there are legitimate use cases where correctness is not a concern (e.g. because the image is going to be thrown away or can easily be rebuilt), we added an incorrect but fast option to return to the original behaviour. Unfortunately this isn't wired up in the UI, but can be switched on as follows:

```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ git reset --hard
HEAD is now at 313b5d5 Docker started 1475165023
$ mkdir -p com.docker.driver.amd64-linux/disk
$ echo false > com.docker.driver.amd64-linux/disk/full-sync-on-flush
$ git add com.docker.driver.amd64-linux/disk/full-sync-on-flush
$ git commit -s -m "Disable flushing"
[master a35bdea] Disable flushing
 1 file changed, 1 insertion(+)
 create mode 100644 com.docker.driver.amd64-linux/disk/full-sync-on-flush
```
The VM should automatically reboot and the mode should be switched.

Could you give that a go and let us know what happens? If it doesn't help, could you provide a representative repro case of some sort and upload a diagnostic? Thanks!

**Comment by hodgesmr** [comment] 2017-01-25 13:40
Hi @djs55,

Thanks for the quick response! Disabling flushing did the trick! My tests are back to expected wall-time speed now.

**Comment by marceloandrader** [comment] 2017-01-27 14:58
This workaround can be applied to a linux host too?

**Comment by dsheets** [comment] 2017-01-27 15:00
@marceloandrader no, this workaround is only for Docker for Mac. I'm closing this issue as a duplicate of #668 in light of @hodgesmr test result.

**Closed** 2017-01-27 15:00 UTC
Labels: status/1-acknowledged

**Comment by fuxx** [comment] 2019-01-07 22:39
@djs55 In the current version I have (2.0.0.0-mac81) the folder `~/Library/Containers/com.docker.docker/Data/database/` does not exist anymore. 
How can I change the flush behaviour?

**Comment by robmosca-travelperk** [comment] 2020-02-06 14:02
Indeed @djs55, In the current version the folder ~/Library/Containers/com.docker.docker/Data/database/ is not present... Wondering how to disable F_FULLFSYNC
