### ISSUE TITLE
Feature Request: configurable disk size

### ISSUE THREAD

**Issue by HariSekhon** [docker/for-mac#838] opened 2016-10-24 20:21 UTC
Feature request to add configurable disk size when setting up Docker for Mac.

Docker easily runs out of space and needs to have both the qcow disk and the filesystem expanded, which I currently do via a tedious qemu gparted process.

Coupled with bug in issue #820 which results in the regular loss of the disk to get it working again via factory reset which recreates the disk back to it's default size, and we really, really need a simple way of just specifying the initial size of the qcow disk.

**Comment by samoht** [comment] 2016-11-03 22:37
Closing as duplicate of #371

**Closed by samoht** 2016-11-03 22:37 UTC
Labels: status/0-triage

**Comment by HariSekhon** [comment] 2016-11-15 11:58
@samoht 

This is not a duplicate of issue #371 - that is a bug about space reclaim.

This is around the fact that the qcow2 image comes pre-configured to only 60GB but I am downloading way more than 60GB of docker images for all my test suites so I currently have to manually resize the docker image to be able to fit them.

**Comment by samoht** [comment] 2016-11-15 12:13
Sorry I wasn't very clear, but the resolution of #371 will actually involves resolving your use-case too. See end of the comment of https://github.com/docker/for-mac/issues/371#issuecomment-249533736 where we are planning to first expose a way to control the size of the disk.

**Comment by HariSekhon** [comment] 2016-11-15 12:51
Ah, ok thanks, that was a long thread I missed that bit.
