### ISSUE TITLE
Docker failing to build...

### ISSUE THREAD

**Issue by begrafx** [docker/for-mac#5201] opened 2020-12-30 16:31 UTC
I'm unsure if there was an update pushed, or what is causing this, but suddenly I find myself... basically "dead in the water" as far as Docker is concerned. I am using DDEV, and if I attempt to start ANY of my projects, I get something like this:

`$ ddev start
Starting wbmg-dir...
Building db
Building web
Recreating ddev-wbmg-dir-db ... done
Recreating ddev-wbmg-dir-dba ... done
Recreating ddev-wbmg-dir-web ... 
 
ERROR: for ddev-wbmg-dir-web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
 
ERROR: for web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Failed to start wbmg-dir: Failed to run docker-compose [-f /Users/brianeller-mini/Projects/wbmg-dir/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 33f3288968e4
Step 3/6 : ARG username
 ---> Using cache
 ---> 7327c0d7b5ec
Step 4/6 : ARG uid
 ---> Using cache
 ---> d14253dd700d
Step 5/6 : ARG gid
 ---> Using cache
 ---> 2793bfac38a3
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 36b4efa0ea2b

Successfully built 36b4efa0ea2b
Successfully tagged drud/ddev-dbserver-mariadb-10.2:v1.16.0-wbmg-dir-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 9e6709a9d711
Step 3/6 : ARG username
 ---> Using cache
 ---> 66905806fe61
Step 4/6 : ARG uid
 ---> Using cache
 ---> 77f1d0be5576
Step 5/6 : ARG gid
 ---> Using cache
 ---> f631b81c70c8
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 1c19bf95738e

Successfully built 1c19bf95738e
Successfully tagged drud/ddev-webserver:v1.16.3-wbmg-dir-built
', stderr='Building db
Building web
Recreating ddev-wbmg-dir-db ... done
Recreating ddev-wbmg-dir-dba ... done
Recreating ddev-wbmg-dir-web ...

ERROR: for ddev-wbmg-dir-web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).' `

It was working fine one day, and the next morning.... this. The problem seems to be based around

`Failed to start wbmg-dir: Failed to run docker-compose [-f /Users/brianeller-mini/Projects/wbmg-dir/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE`

how do I get docker working again?

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 14DD065F-AFAF-4D2E-833A-08847468832E/20201230161001

### Expected behavior

Container builds, and I am able to work on my project

### Actual behavior

See above

### Information

  - macOS Version:
  
  Mojave

### Diagnostic logs

```
Docker for Mac: version... 3.03 (51017)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-01-04 11:28
Thanks for the report, this appears to be a dupe of #4957.

**Closed by stephen-turner** 2021-01-04 11:28 UTC
Labels: version/3.0.3
