### ISSUE TITLE
vmstateevent invalid json

### ISSUE THREAD

**Issue by fewspider** [docker/for-mac#447] opened 2016-08-29 01:15 UTC
### Information

Diagnostic ID: 7358D213-E9DF-4E6D-ACF0-9D1D06EB3832
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A304a)

### Steps to reproduce

![2016-08-29 09 14 55](https://cloud.githubusercontent.com/assets/3256161/18038319/12dca858-6dc9-11e6-9719-1c15e47b4d0e.png)

**Comment by Serg1i** [comment] 2016-08-30 07:34
+1 have the same on Sierra latest build:

Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A313a)
logs: /tmp/7B134082-076A-4012-B90D-A67CF3A1C8EE/20160830-103113.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by dsheets** [comment] 2016-09-01 09:14
This is a duplicate of #64 which has been fixed in the beta channel. The fix for this issue should reach the stable channel within the week.

**Closed by dsheets** 2016-09-01 09:14 UTC
Labels: area/startup, osx/10.12 (beta), version/1.12.0

**Comment by djs55** [comment] 2016-09-15 16:10
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
