### ISSUE TITLE
Unable to pull docker image due to lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving

### ISSUE THREAD

**Issue by sgykfjsm** [docker/for-mac#1340] opened 2017-02-25 15:51 UTC
### Expected behavior
`docker pull` should download the image from docker hub
### Actual behavior
```
$ docker pull busybox
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving
```
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/EB790255-59A8-42E5-987F-99B68D05D961/20170226-003005.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
Diagnostic ID: EB790255-59A8-42E5-987F-99B68D05D961

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: GFWZ:ZMTT:XG7N:75LR:QXZ3:FQQ6:EIUW:OAEP:ZPWS:ADL6:36IQ:XK2X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-02-25T15:35:12.937238749Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior

1. Download the stable channel installer from https://docs.docker.com/docker-for-mac/install/ and install the latest Docker for mac. 
2. Run `docker pull busybox` When I use 1.12.3, `docker pull` works fine.

**Comment by MagnusS** [comment] 2017-03-07 19:01
Thanks for the reports. This looks like a duplicate of https://github.com/docker/for-mac/issues/1025 which has been fixed in the latest 17.03.x releases on both beta and stable channel. I'm closing this issue for now, but please let us know if the new version doesn't resolve the issue for you.

**Closed by MagnusS** 2017-03-07 19:01 UTC
Labels: status/0-triage, version/1.13.1
