### ISSUE TITLE
Cannot pull images when using Experimental mode

### ISSUE THREAD

**Issue by aaronhmiller** [docker/for-mac#5653] opened 2021-05-04 07:35 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: lost patience for waiting to get the ID, but it should be there w/ timestamp near this report

### Expected behavior
docker pull postgres
should pull an image
### Actual behavior
docker pull postgres
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
### Information
Problem is reproducible.
Problem occurred after 3.3.2 update
3.3.2 fixed the TLS issue #5572 I ran into but seems to have broken pull capabilities in combination w/ new Big Sur virtualization.framework
  - macOS Version: 11.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.2 (63878)

### Workaround
Disable `Experimental` mode, and use legacy hypervisor.framework

### Steps to reproduce the behavior
1. enable Experimental feature Apple virtualization
2. attempt to pull any docker image (i.e. docker pull postgres)
3. notice error "https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection" and inability to pull any images due to the error

**Comment by boboldehampsink** [comment] 2021-05-04 08:38
Seeing this too, thanks for the workaround

**Comment by trulyspinach** [comment] 2021-05-04 13:28
same problem

**Comment by djs55** [comment] 2021-05-04 13:57
@aaronhmiller thanks for the report. The networking under `virtualization.framework` is a bit different to the networking with our other platforms. I have a developer build which switches `virtualization.framework` over to use `vpnkit`, the same as the others: https://desktop-stage.docker.com/mac/stable/arm64/64012/Docker.dmg . To make sure it's being used, verify that `useVpnkit` is set to `true` in `~/Library/Group\ Containers/group.com.docker/settings.json`. It should be `true` already in 3.3.2, but it's not currently hooked up to anything.

This developer build has only been lightly tested. I've been building and pushing images without problems, although I'm also running macOS 11.4 beta (20F5046g) so it's possible I'm benefiting from additional bugfixes from that.

If you get a chance to try it, let me know how it goes. If it goes wrong, upload a diagnostic and quote the ID here and I'll take a look.

**Comment by trulyspinach** [comment] 2021-05-04 15:16
@djs55 does their happen to be a amd64 build of your development build?
I am having the problem on intel based Mac and willing to give it a spin now.

**Comment by djs55** [comment] 2021-05-04 16:35
@trulyspinach ah, sorry I keep forgetting to provide 2 links. I've edited the comment to include an `amd64` link. In general both builds should be available for each build number so you can replace `arm64` with `amd64`. Let me know how it goes!

**Comment by przemub** [comment] 2021-05-04 16:36
The same here, but also in non-experimental mode with HyperKit. Rollbacking to 3.3.1 for now.

**Comment by trulyspinach** [comment] 2021-05-04 23:53
@djs55 Thanks. Tried pulling some image with your development version even without editing the `setting.json` file and it seems to be working.

**Comment by aaronhmiller** [comment] 2021-05-05 18:12
you do excellent work @djs55! I just loaded your dev build `3.3.2 (64012)` on Intel and here's a single screenshot that proves everything working: 
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/223486/117186801-0e323780-ad90-11eb-91e4-900759621ea3.png">

Looking forward to 3.3.3 containing your official fix when y'all make it ready, but given this is in the experimental area, understand it might be lower priority. I've been using the Big Sur virtualization.framework because it just feels snappier and suspect it's the long range plan for Docker.

**Comment by fgerards** [comment] 2021-05-06 07:13
I can confirm this problem using 3.3.2 on a Macbook Air 2020 with Silicon Chip (M1) and latest Mac OS Big Sur update
![Bildschirmfoto 2021-05-06 um 09 10 39](https://user-images.githubusercontent.com/1511030/117256423-f79ce680-ae4a-11eb-83ac-1521dabbb71e.png)

![Bildschirmfoto 2021-05-06 um 09 11 52](https://user-images.githubusercontent.com/1511030/117256761-5b271400-ae4b-11eb-9d2a-08b89223a00b.png)

**Comment by cetzold** [comment] 2021-05-06 12:31
@djs55 Thanks. This version works on my Intel iMac with Big Sur 11.3.1

**Comment by aaronhmiller** [comment] 2021-05-06 15:05
@fgerards I don't have the cool (in all senses) M1 to test on, but feel confident if you need resolution now, you'll get it by installing the dev-build referenced by djs55 in this thread.

**Comment by fgerards** [comment] 2021-05-06 22:01
@aaronhmiller :i updated to 3.3.3 released today, but this doesnt seem to include the fix you mentioned - will try the dev-build

**Comment by aaronhmiller** [comment] 2021-05-06 22:32
thanks @fgerards of course I read this only *after* Docker Desktop forced me to upgrade to 3.3.3...<le sigh> I suppose paying $5/month might be worth the hassle of forced upgrades.

**Comment by 0x1301FDF** [comment] 2021-05-08 12:00
@djs55 same problem in 3.3.3 when "Use new virtualization framework"

**Comment by aaronhmiller** [comment] 2021-05-08 18:07
@0x1301FDF yeah, @djs55 's fix in the dev build here above didn't make it into 3.3.3. Seems reasonable to expect it in 3.3.4 though.

**Comment by im-kulikov** [comment] 2021-05-27 08:49
Hi there 👋 any updates?

**Comment by wunderkind2k1** [comment] 2021-06-03 07:44
Hi. Could this be a duplivate of https://github.com/docker/for-mac/issues/5410 ?

**Comment by im-kulikov** [comment] 2021-06-03 15:23
@wunderkind2k1 it's very similar

**Comment by djs55** [comment] 2021-06-10 16:10
Thanks everyone for your help on this issue. The fix in the dev build should have been released in Docker Desktop 3.4.0. I'll close this ticket but if the bug is still present, upload a new set of diagnostics and ping me here with the ID and I'll take a look / re-open the ticket.

**Closed by djs55** 2021-06-10 16:10 UTC
Labels: area/network, version/3.3.2

**Comment by fgerards** [comment] 2021-06-10 17:38
Tested v3.4.0 on Big Sur 11.40 on M1 with new virtualization framework and no pull errors - seems gone, thanks a lot

**Comment by aaronhmiller** [comment] 2021-06-10 18:17
Tested 3.4.0 on OSX 11.3.1 Intel using new virtualization framework and pulled w/o issue. Thank you for the fix @djs55
