### ISSUE TITLE
Docker crashed loading after an update from 20

### ISSUE THREAD

**Issue by greenkiwi** [docker/for-mac#115] opened 2016-08-03 23:05 UTC
### Information

Diagnostic ID: 3A99680F-14C0-420D-B7C1-D9A3B1669FC1
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment] 2016-08-09 02:03
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 02:03 UTC

**Comment by djs55** [comment] 2016-09-15 16:30
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
