### ISSUE TITLE
Translations don't appear in the popup asking to confirm factory reset

### ISSUE THREAD

**Issue by devantoine** [docker/for-mac#5552] opened 2021-04-07 08:50 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Translation shows up.

### Actual behavior
Only translation's keys are displayed.

![Factory Reset popup](https://pbs.twimg.com/media/EyW7KJPWYAIaChE?format=png&name=large)

### Information
  - macOS Version: BigSur 11.2.3
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior
1. Open Docker dashboard
2. Go to troubleshot
3. Click on "Reset to factory default"

I'm not able to reproduce it anymore.

**Comment by stephen-turner** [comment] 2021-04-07 10:15
Thanks, this is a duplicate of #5457. Will be fixed in the next release.

**Closed by stephen-turner** 2021-04-07 10:15 UTC
