### ISSUE TITLE
Docker Apple Silicon preview version doesn't start 

### ISSUE THREAD

**Issue by lfdp** [docker/for-mac#5234] opened 2021-01-09 07:57 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Stehos** [comment] 2021-01-09 08:43
Hi there, I tried to use Docker preview with M1 last week with N8N container and everything was working properly. Now I figured out that Docker Desktop is starting in loop and nothing helped. I tried to restart, reinstall. No errors received. Thank you for your advice.

**Comment by shirishshukla** [comment] 2021-01-10 10:56
big Sure 11.1 (M1), docker service not start .. status always "starting" .

**Comment by ntt2k** [comment] 2021-01-10 22:07
I confirmed the same error on **the latest MacOS Big Sure 11.1 (M1)** using **Docker-AppleSilicon-Preview7.dmg** -->

<img width="725" alt="Screen Shot 2021-01-10 at 3 59 32 PM" src="https://user-images.githubusercontent.com/4227421/104136768-cb220380-535d-11eb-969b-15a238366e9f.png">

**Comment by tobtherusch** [comment] 2021-01-11 13:32
> big Sure 11.1 (M1), docker service not start .. status always "starting" .
> 
> Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

same problem here.

**Comment by pzrq** [comment] 2021-01-12 05:46
> big Sure 11.1 (M1), docker service not start .. status always "starting" .
> 
> Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

Same error here, my diagnostics ID in case it helps: DDF3FA44-300B-421B-84DD-AAFEE084B027/20210112031840

**Comment by jmuel** [comment] 2021-01-17 05:23
I'm seeing the same issue. It was working in Big Sur 11.0 but now it fails with the "bad CPU type in executable" error. I tried deleting everything and redownloading the newest version of docker but it showed the same error.

**Comment by jmuel** [comment] 2021-01-17 05:39
Hmm, this actually resolved itself after I reactivated Rosetta. There might just be something turning it off when you upgrade?

**Comment by pzrq** [comment] 2021-01-20 21:36
Still happening on and off for me (some days Docker Preview 7 works, some days `docker ps` returns `Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory`).

Digging a little deeper, it looks like the problem is currently with `com.docker.vmnetd` command 13, which returns `exit status 69` whatever that means:

```
...
2021-01-20 14:00:42.616413+1100  localhost com.docker.vmnetd[329]: Command 7 successfully executed
2021-01-20 14:00:42.619391+1100  localhost com.docker.vmnetd[329]: Received a connection
2021-01-20 14:00:42.619479+1100  localhost com.docker.vmnetd[329]: Received command: 10
2021-01-20 14:00:42.620896+1100  localhost com.docker.vmnetd[329]: Command 10 successfully executed
2021-01-20 14:00:42.621394+1100  localhost com.docker.vmnetd[329]: Received a connection
2021-01-20 14:00:42.621463+1100  localhost com.docker.vmnetd[329]: Received command: 12
2021-01-20 14:00:42.621728+1100  localhost com.docker.vmnetd[329]: Command 12 successfully executed
...
2021-01-21 07:44:45.347340+1100  localhost com.docker.vmnetd[329]: Received a connection
2021-01-21 07:44:45.348559+1100  localhost com.docker.vmnetd[329]: Received command: 13
2021-01-21 07:44:45.359867+1100  localhost Docker[3800]: (libboringssl.dylib) [com.apple.network:boringssl] boringssl_context_new_session_handler(1202) [C8.1:2][0x12f425820] New session available
2021-01-21 07:44:45.359883+1100  localhost Docker[3800]: (libboringssl.dylib) [com.apple.network:boringssl] boringssl_context_new_session_handler(1202) [C8.1:2][0x12f425820] New session available
2021-01-21 07:44:45.373027+1100  localhost com.docker.vmnetd[329]: Error handling command: exit status 69
...
```

Haven't made time to look into any other logs yet to see if there's more light to be shed on this heisenbug.

**Comment by araiczyk** [comment] 2021-02-03 16:45
Same problem here. Any news?

**Comment by Stehos** [comment] 2021-02-03 18:06
@araiczyk It started to work for me. I just made "factory reset" in Docker Desktop.

**Comment by araiczyk** [comment] 2021-02-03 18:40
Update: I've selected Troubleshoot-Clean/Purge Data, and voila, it's working now.

<img width="1240" alt="Captura de Pantalla 2021-02-03 a la(s) 15 37 01" src="https://user-images.githubusercontent.com/87342/106793262-fe427480-6635-11eb-8be4-c6114486b6a6.png">

**Comment by christianbalderrama** [comment] 2021-02-22 13:54
Tried @araiczyk suggestion but it didn't work in my case. BigSur 11.2.1 and I reinstalled Docker v3.1.0

**Comment by shirishshukla** [comment] 2021-02-22 16:42
Installed parallels with [ubuntu](https://ubuntu.com/download/server/arm) VM and docker inside it .. working well .

**Comment by roelzkie15** [comment] 2021-03-26 08:55
It will solve by purging/cleaning or resetting to factory default but.... this is time taxing because not all the application has a fast docker image build.

Hope there is a solution that will fix this issue without resetting or purging/cleaning the docker.

**Comment by pzrq** [comment] 2021-05-07 06:42
Seems to have gone away for me at least in [Docker Desktop 3.3.1 (63152)](https://docs.docker.com/docker-for-mac/apple-silicon/) so I'd be inclined to close this issue.

**Comment by stephen-turner** [comment] 2021-05-07 18:54
Yes, I think this is old, I'll close it.

**Closed by stephen-turner** 2021-05-07 18:54 UTC
Labels: area/m1, version/0.0.0
