### ISSUE TITLE
After upgrade to 1.12.2-rc1-beta27 docker will not start

### ISSUE THREAD

**Issue by disrvptor** [docker/for-mac#721] opened 2016-09-29 00:47 UTC
[20160928-204212.tar.gz](https://github.com/docker/for-mac/files/499543/20160928-204212.tar.gz)
### Expected behavior

Docker starts and is available via the CLI
### Actual behavior

After upgrading to 1.12.2-rc1-beta27 Docker will not start. The icon in the menu is continuously animated, but docker is unavailable.

``` bash
$ docker ps
Error response from daemon: dial unix /Users/guypascarella/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```
### Information

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/910BE839-553E-4385-A50D-98BB47FEA3DC/20160928-204212.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/guypascarella/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior
1. Start Docker

**Comment by Multiply** [comment] 2016-09-29 06:54
I am having a similar issue. Same exact error as above, however, the Whale is not animated, but simply static, as if Docker is running as it should.

Output from moby:
```
 [ ok ]
 * Checking system state ...
✓ Drive found: vda
✓ Drive mounted: /dev/vda2 on /var type ext4 (rw,relatime,data=ordered)
✓ Network connected:           inet addr:192.168.65.2  Bcast:192.168.65.15  Mask:255.255.255.240
✓ Process transfused running
✓ Process dockerd running: /usr/bin/dockerd --pidfile=/run/docker.pid -H unix:///var/run/docker.sock --swarm-default-advertise-addr=eth0 --debug
✓ Process containerd running: docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc --debug
```

**Comment by marclennox** [comment] 2016-09-30 02:50
Same here, animated whale never ends.

**Comment by bilus** [comment] 2016-09-30 08:58
Same here, I'm stuck.

**Comment by dsheets** [comment] 2016-09-30 09:20
There are many possible reasons for the symptom you are describing. It would really help us to understand the cause and possible remedies if you would run :whale: -> `Diagnose & Feedback` -> `Diagnose & Upload` and then paste your diagnostic ID back here or open a new issue.

Thanks!

**Comment by bilus** [comment] 2016-09-30 09:32
I uninstalled and reinstalled the latest beta and it still won't start. Another diagnostic ID: 00F81869-B2C6-425F-A836-FC3DC81B2477

**Comment by bilus** [comment] 2016-09-30 09:36
I reset to factory defaults but it still won't start: A1E67A4D-59B6-40A3-B409-A22942EE4C3D

**Comment by bilus** [comment] 2016-09-30 09:46
I installed the stable version. I hope the ^ will help someone.

**Comment by disrvptor** [comment] 2016-09-30 11:19
Factory reset did nothing for me. Ultimately I re-installed the stable version and it worked fine.

**Comment by dangogh** [comment] 2016-09-30 16:35
same here with El Capitan -- cli and diagnostic upload failed -- all else passed: ```Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/91DCDFD1-6285-4902-8BB5-C0B023421E8D/20160930-103258.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed```

Moving back to stable version..

**Comment by dangogh** [comment] 2016-09-30 17:19
retracting that..   reboot and resetting docker cleared that up.  Back on beta.

**Comment by szechyjs** [comment] 2016-10-01 00:30
Having the same problem...

859B1187-7545-4158-B652-664859C22897

**Comment by tomyedwab** [comment] 2016-10-02 23:03
Same here I believe: 5C11704E-3D1F-4226-AC18-54BF71D4795C
Factory reset did help for a few minutes but then it wedged itself again.

**Comment by arnobeck** [comment] 2016-10-03 11:00
I've got the same problem since beta27 : 4B613D51-A22A-4618-B62D-D7ED714B7729
Uninstall, factory reset, reboot, nothing fix this.

**Comment by bladechen** [comment] 2016-10-04 06:59
D6DD2885-3E92-431E-A025-98D622F8EC1F

**Comment by lagofvc** [comment] 2016-10-04 18:23
Joining the thread. Experiencing the same issue : F8720F0F-9EE9-40C9-95D8-6AF2DF876E3A
Mac OSX 10.11

**Comment by shogsbro** [comment] 2016-10-04 19:09
+1. Issue resolved by docker Reset and Restart.

**Comment by lagofvc** [comment] 2016-10-04 19:21
Thanx @shogsbro !  That did it for me too!

**Comment by TheBigBear** [comment] 2016-10-05 15:16
184CF0F1-B1EE-4A98-8F6B-196016BE5A3E same worked fine until now but after this update to Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c) the icon stays animated and I can't start or connect to any container

**Comment by TheBigBear** [comment] 2016-10-05 15:29
will using the reset to factory settings loose all my downloaded (pull) containers?

**Comment by lagofvc** [comment] 2016-10-05 15:36
yes.  any images you want to keep you could push up to your dockerhub account

**Comment by TheBigBear** [comment] 2016-10-05 15:54
@lagofvc but isn't this a catch 22 situation? I can't use or connect to docker at all to do ANYTHING, right now, including pushing an image up to my dockerhub account?
Is there any way to get a nem of the images, whilst docker ps doesn't work? Maybe somehow peek inside the docker qcow2 file and get a list of installed/cached images?

**Comment by lagofvc** [comment] 2016-10-05 15:56
hmmm great question man!   I went through this last night and luckily on my other laptop i had no issues and it had the images i cared about.  But i see your dilemma.  I will let more experienced folks answer that for you.

**Comment by samoht** [comment] 2016-11-04 09:53
Detected symptom of problem 'large-certificate' in 184CF0F1-B1EE-4A98-8F6B-196016BE5A3E/20161005-174134.

Since Beta27, Docker for Mac uses the hosts certificates directly. However, there was an issue with large certificates that you unfortunately hit. This was fixed by Beta28. Please upgrade. Thanks for using our product!

May be related to docker/for-mac#721

**Closed by samoht** 2016-11-04 09:53 UTC
Labels: osx/10.11.x, status/0-triage, version/beta27
