### ISSUE TITLE
Update failing on macOS 14.0 with M1 chip

### ISSUE THREAD

**Issue by spowelljr** [docker/for-mac#7000] opened 2023-09-28 20:12 UTC
### Description

I have six Mac machines, four with Intel chips and two with M1 chips. All machines started with macOS 13.6 and Docker Desktop 4.23.0. I updated all the machines to macOS 14.0 and then tried updating Docker Desktop to 4.24.0. All the Intel machines updated successfully, but both the M1 machines are failing to update. I click `Download update` and then `Update and restart`, Docker closes and doesn't re-open and there are no Docker processes running on the machine. If I re-open Docker Desktop it's still on 4.23.0. I've tried restarting the machines and tried updating multiple times without success.

### Reproduce

macOS 14.0 with M1 chip
Docker Desktop 4.23.0

Click `Download update` and then `Update and restart`

Docker Desktop closes and doesn't re-open and the update is not applied

### Expected behavior

Docker Desktop restarts and the update to 4.24.0 is successful

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.4
    Path:     /Users/jenkins/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0-desktop.1
    Path:     /Users/jenkins/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jenkins/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jenkins/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.7
    Path:     /Users/jenkins/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jenkins/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jenkins/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.24.1
    Path:     /Users/jenkins/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 5.799GiB
 Name: docker-desktop
 ID: 8a509a28-dce2-4fd9-9231-1d4ff1a5cf92
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

CFF2BD8D-1196-42F8-AB7B-B3E9C66651D3/20230928200935

**Comment by Mercbot7** [comment] 2023-10-02 19:05
I have just updated to MacOS 14.0 at the end of last week. My Docker Desktop said there was an update so I ran through the process. It killed Docker Desktop, never updated, corrupted the Application and never restarted. I downloaded the latest app from here: https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module

And that one is telling me fatal-error-incompatible-cpu-detected.

I reset to defaults(probably did not need to do that).

Rebooted.

Tried again, no luck.

Downloaded the installer from here:
https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64

installed.

and now it is starting just fine. I had configure everything ...again.

Maybe it is a bad link and that is what the updater is doing?

**Comment by bsousaa** [comment] 2023-10-03 08:29
@Mercbot7 @ddbrodsky can you share a diagnostics id to help us troubleshooting?

**Comment by woodardj** [comment] 2023-10-04 11:31
I'm on MacOS 12.0.1 on an Apple M1, ran the 4.24 update yesterday and now Docker won't boot at all. The Desktop client displays errors about "Failing to Fetch Extensions", but the engine won't start.

**Comment by adayush** [comment] 2023-10-04 11:35
I don't have macOS 14 but I was having a similar issue since I updated Docker Desktop to the latest version.
Here's how I fixed it:

1. Uninstalled Docker
2. Deleted all these directories
```~/Library/Caches/com.docker.docker
~/Library/Cookies/com.docker.docker.binarycookies
~/Library/Group Containers/group.com.docker
~/Library/Logs/Docker Desktop
~/Library/Preferences/com.docker.docker.plist
~/Library/Preferences/com.electron.docker-frontend.plist
~/Library/Saved Application State/com.electron.docker-frontend.savedState
~/.docker
/Library/LaunchDaemons/com.docker.vmnetd.plist
/Library/PrivilegedHelperTools/com.docker.vmnetd
/usr/local/lib/docker```

3. Installed Docker Desktop [v4.18.0](https://docs.docker.com/desktop/release-notes/#4180)
4. Don't open docker. Restart the device then open it

After this, I got the old version working. Then tried updating to the latest and it also worked.
Hope this helps you :D

**Comment by bsousaa** [comment] 2023-10-04 15:01
@woodardj can you share a diagnostics id? https://docs.docker.com/desktop/troubleshoot/overview/

**Comment by jyeary** [comment] 2023-10-04 16:17
I am having the same issue. Here is my diagnostic ID 
E0C91E24-52A4-4473-A01E-C4E856A49EB4/20231004161212

**Comment by jyeary** [comment] 2023-10-04 16:17
I have an M1 on MacOS 14

**Comment by dopsun** [comment] 2023-10-06 14:14
Same issue here.
I have the M2 Max with Mac OS 14.0. Currently running 4.23.0 (120376). Once updated to 4.24, Docker Engine started (green), but Kubernetes will be in state of "is starting", and failed after a long time out.

I restored 4.23 with Time Machine, everything works fine.

**Comment by nfantone** [comment] 2023-10-13 16:24
Same over here — also on M1.

Update `4.24.2` downloads, Docker asks for a restart, quits but never comes back again. After manually opening it, update is not applied. Rinse and repeat.

**Comment by spowelljr** [comment] 2023-10-13 17:20
An update since 4.24.2 came out today, tried to update from 4.23.0 and still getting the same thing. I forgot to mention that I have a third M1 machine that's running macOS 13.6 and that machine has had no issues updating, which makes me think it's a macOS 14.0 specific issue, but @nfantone's above comment says otherwise.

**Comment by nfantone** [comment] 2023-10-13 17:58
Correct. Can confirm that neither `4.24.0` nor `4.24.2` worked for me on `13.6`.

**Comment by Mercbot7** [comment] 2023-10-13 18:35
# Update

Tried to update to `4.24.2`. Same thing occurred. 
- The upgrade seems to partially complete.
- The app is corrupted.

I had to download from the link I originally posted and install manually.

Something of note. I am not running as an Admin user, rather a Standard user.

**Comment by claudiu-cristea** [comment] 2023-10-14 13:04
Same here,

* MacBookPro Intel Core i9 (2019)
* macOS 14.0
* Trying to update from 4.23.0 (120376) to 4.24.2 (124339)
* Pressing "Download", then "Update and restart"
* The button turns gray showing "Installing update"
* After a while Docker desktop is closing but never reopen
* If I'm manually open it, it shows the same  4.23.0 version

**Comment by steemax** [comment] 2023-10-15 09:37
I have the same problems as described above

- MacBookPro M1 pro
- Trying to update from 4.23.0 (120376) to 4.24.2 (124339)

**Comment by bsousaa** [comment] 2023-10-16 12:25
It sounds like the failure is happening because the update is triggered by a different user who originally installed Docker Desktop. Can you confirm if that was the case?

**Comment by dopsun** [comment] 2023-10-16 13:22
For me, it's under same user. I double checked in Activity Monitor, and processes with name like `Docker` and `docker` (all lower case), `com.docker.*` (there are a few) are all under my current active user.

My MacOS only has one user other than `root`, so the installation process is from my current user account. I downloaded dmg from site, and install from there.

**Comment by bsousaa** [comment] 2023-10-16 13:26
@dopsun can you share a diagnostics id?

**Comment by claudiu-cristea** [comment] 2023-10-16 13:27
> It sounds like the failure is happening because the update is triggered by a different user who originally installed Docker Desktop. Can you confirm if that was the case?

It's no the case here. Also, I have "Diagnostics" menu item from where to share in Settings

**Comment by dopsun** [comment] 2023-10-16 13:33
@bsousaa  diagnostics id:  D6E5FA9E-CBC3-458F-8422-94DE231875B9/20231016133052

**Comment by claudiu-cristea** [comment] 2023-10-16 13:38
@bsousaa done. Finished with:

```
Diagnostics ID:     9B6011EC-3B16-48B3-82A2-75A63B779AF3/20231016133528 (uploaded)
```

**Comment by dopsun** [comment] 2023-10-16 13:40
By the way, I have tried updating to new version, failed and using TimeMachine restored to old version. Done thing several times already. Clarify this just in case there are strange log entries in diagnostics logs.

**Comment by jasonkarns** [comment] 2023-10-16 20:19
I have the same issue. Docker originally installed through homebrew. Docker configured to automatically install updates. User account is not an admin.

After docker attempted a restart, Docker is now corrupt:
![image](https://github.com/docker/for-mac/assets/119972/d997a7ed-f449-49ac-a981-5d7fec35d58a)

![image](https://github.com/docker/for-mac/assets/119972/45b53595-9d63-48b4-b2ae-aba01fca0309)


No diagnostics ID:
```
$ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
-bash: /Applications/Docker.app/Contents/MacOS/com.docker.diagnose: No such file or directory
```

**Comment by AaronBeaudoin** [comment] 2023-11-02 16:06
I am experiencing this issue as well. Currently on version 4.23.0 (120376). Trying to update to version 4.24.2 (124339). I press "Download update" and then "Update and restart" and then after a short time Docker closes and never reopens. When I reopen it manually it is still on version 4.23.0.

**Comment by meOates** [comment] 2023-11-05 22:24
Docker was running fine under Mac v.4.23
Just ran the update to v.4.25.0 and the same issues reported above.
I keep getting the error: Docker Engine stopped
 Extensions Failed to fetch extensions
Is there a way to roll-back to previous Desktop version?
Here is my Diagnostic ID:
D160C6AB-F619-4D50-893C-C3AF13F7551B/20231105180919

This issue seems pervasive enough that maybe there should be some documentation warning or recommended solutions in the Docker Docs, no?

**Comment by claudiu-cristea** [comment] 2023-11-17 08:25
@bsousaa 

I see 4.25.1 is out but I'm still stuck on 4.23.0. Any chance to fix this or, at least, provide some guidance to fix ourselves. I've provided the requested diagnostic ID here https://github.com/docker/for-mac/issues/7000#issuecomment-1764505266 but never got a response.

Also, could you, please, change the title of the issue and remove the "with M1 chip" part. I'm on Intel processor and the issue still occur

**Comment by dopsun** [comment] 2023-11-17 09:28
> This issue seems pervasive enough that maybe there should be some documentation warning or recommended solutions in the Docker Docs, no?

For my case, I rollback to old version by recover from Time Machine backup. Go to Application folder where Docker app installed, and enter Time Machine to take last known good old version of app back.

**Comment by bsousaa** [comment] 2023-11-17 10:27
@claudiu-cristea @dopsun, from our investigation it looks like this failure is happening because the user who originally installed Docker Desktop on your machine is different.

Can you confirm what user is displayed with `ls -al /Applications/Docker.app`?

Case it's the same user, please confirm and submit a diagnostics id.

**Comment by bsousaa** [comment] 2023-11-17 10:33
`whoami`? 
Please share a diagnostics id? You can generate one from the terminal. See https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

**Comment by dopsun** [comment] 2023-11-17 10:38
@bsousaa 

Diagnostics ID:     D6E5FA9E-CBC3-458F-8422-94DE231875B9/20231117103408 (uploaded)

```
dopsun@Dops-MacBook-Pro ~ % whoami
dopsun
```

**Comment by claudiu-cristea** [comment] 2023-11-17 10:39
My user:

```
$ whoami
clau
$ id
uid=501(clau) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)
```

Diagnostic ID: `9B6011EC-3B16-48B3-82A2-75A63B779AF3/20231117103518`

**Comment by bsousaa** [comment] 2023-11-17 10:41
@claudiu-cristea your output above shows that Docker Desktop was originally installed by the user `503`. The update must run with that same user.

**Comment by claudiu-cristea** [comment] 2023-11-17 10:48
@bsousaa, that's very weird because I've always ran with this user. For instance 4.23.0 update wasn't so long ago and for years I didn't change the user nor reinstall macOS. It seems that the issue appeared more or less after macOS Sonoma upgrade.

Should I change the ownership of `/Applications/Docker.app/Content` from 503 to my user?

**Comment by bsousaa** [comment] 2023-11-17 10:59
It's probably best making a clean install. Make sure you save any relevant images, uninstall or factory reset and reinstall.

**Comment by spowelljr** [comment] 2023-11-17 14:39
Ah, the ownership does seem to be the problem, it seems whoever installed Docker Desktop on these two M1 machines did so as root. I did notice previously that every time I would update Docker Desktop on those machines it would have odd prompts that didn't happen on my other M1 machine. Thanks for getting to the root of the problem @bsousaa!

**Comment by dopsun** [comment] 2023-11-17 15:11
So, what have you don is `chown -r` on two folders above? @spowelljr

**Comment by spowelljr** [comment] 2023-11-17 15:20
> So, what have you don is `chown -r` on two folders above? @spowelljr

I just deleted the Docker Desktop application and downloaded a fresh install.

**Comment by claudiu-cristea** [comment] 2023-11-17 17:26
Fixed by removing and reinstalling the new. Permissions look good now

**Comment by dopsun** [comment] 2023-11-18 02:32
![snapshot](https://github.com/docker/for-mac/assets/11390044/bc588e6c-5ee9-4eba-b669-d40f6a294007)
Actually, when I'm trying to uninstall, here is an issue. Not sure if this one helps as well.

**Comment by dopsun** [comment] 2023-11-18 03:30
Mine also got fixed. Root cause also related with permission, but there are some differences comparing to @claudiu-cristea @spowelljr,  as I cannot uninstall Docker initially.

For my case, it seems the new MacOS Privacy & Security settings causing this issue. Here are steps for me to bring my Docker to latest version:

* Enable Docker Full Disk Access
* Uninstall docker
* Disable Docker Full Disk Access (icon still there, but I'm not sure if this matters)
* Install new docker, latest version


_Here are a bit longer background, just for your information_

My Docker's current installation was done quite some time ago, across several generations of MacOS. One possibility is that some legacy files, as I shared in my last comment, cannot be changed under new MacOS protection. 

One error triggers me to think in this direction, is after initial uninstall failed, and then I restart and uninstall docker, it gives a hints of one files cannot ulink, which is  `~/Library/Containers/com.docker.helper/.com.apple.containermanagerd.metadata.plist`. I find that even cannot change it with sudo within terminal. So, that's when I think maybe give Docker Full Disk Access to uninstall, and it succeed.

Thanks @bsousaa help getting to root cause.

**Comment by bsousaa** [comment] 2023-11-22 11:10
I'm closing this issue as this was caused by the user updating Docker Desktop being different from the user who originally installed. 
Different ACL's on the filesystem break the update process. We improved the update mechanism to detect this situation and prevent the update from starting in this scenario happen in the future.

**Closed by bsousaa** 2023-11-22 11:10 UTC
Labels: status/triage, area/installer, version/4.23.0, version/4.25.0

**Comment by spowelljr** [comment] 2023-11-22 14:15
Thanks for resolving this @bsousa! Not sure on implementation, but having a notification to the user that a different user was detected during update instead of a silent failure would likely prevent other issues like this being created in the future. I also understand this might be a very niche case though and hard to justify dev time, just my thoughts.

**Comment by Mercbot7** [comment] 2023-11-22 14:15
@bsousaa What version will this fix be in? What directories are we supposed to `chown`?

The upgrade to `4.25.2` from `4.25.1` has been the same with no fix. I have deleted the app and re-installed every upgrade since `4.24.0` and nothing has been resolved nor direction on what to do to fix this.

_"Different ACL's on the filesystem break the update process. We improved the update mechanism to detect this situation and prevent the update from starting in this scenario happen in the future."_

Does this mean that my app will no longer auto update? How do I resolve this?

**Comment by bsousaa** [comment] 2023-11-22 15:53
@Mercbot7 the update process should work fine if you are updating with the same user. You can verify who originally installed with `ls -al /Applications/Docker.app`.

If the update process keeps failing and you are running with the same user I suggest you open a new issue with a corresponding diagnostics id.
