### ISSUE TITLE
Resources -> File Sharing Does Not Allow Selection of Symlink at root of Boot Volume

### ISSUE THREAD

**Issue by banagale** [docker/for-mac#5127] opened 2020-12-13 18:43 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: D94E7E33-86C2-4F3C-8258-04904B8F16CC/20201213182346

### Expected behavior
Docker -> Preferences -> Resources -> File Sharing -> + -> File Select Dialog

This dialog does not allow you to select a symlink created by `synthetic.conf` in the root of a boot volume and add the path to the list of shared Resources.

Docker should recognize user intent of adding a symlink files by parsing the origin folder and adding it to the list.

### Actual behavior
Selecting a symlink (looks like a folder with a shortcut arrow decoration) from 
Docker -> Preferences -> Resources -> File Sharing -> + -> File Select Dialog causes the file dialog to close and no folder to be added to the list.

### Information
  - Is it reproducible? Yes.
  - Is the problem new? No?
  - Did the problem appear with an update? Yes?

### Steps to reproduce the behavior
Presume your docker project requires a mount to a root level volume such as 

```
    volumes:
      - /product_name/:/product_name/
```

As of Catalina, [you must use](https://automatica.com.au/2020/01/create-empty-directories-and-symlinks-at-the-root-of-the-boot-volume-on-macos-catalina-10-15-synthetic-conf/) the `etc/synthetic.conf` file to provide a mapping to MacOS such as:

```
# synthetic.conf
# note tab space is required (and this filetype may not support comments)
product_name   /System/Volumes/Data/Users/username/code/consulting/client/product_name
```

After reboot MacOS creates a symlink in the root path which allows access to the mapped path.

Previously, it seemed like it was sufficient to share the mapped path to resources, which is selectable and addable using the UI.

Either I was mistaken previously, or something changed recently where the path of the symlink is now required to either or also required to be shared to the shared files list, in this example `/product_name`. 

However, this does is not possible using the same UX of a normal folder. 

I also tried adding it by typing in the path `/product_name` and that also did not work.

I resorted to editing the settings json file (`~/Library/Group\ Containers/group.com.docker/settings.json`) directly as [suggested here](https://stackoverflow.com/a/62842115/4028977), by adding 

```
{
  "filesharingDirectories" : [
    "\/Users",
    "\/Volumes",
    "\/private",
    "\/tmp",
    "\/product_name"
  ],
```

And restarting Docker. Then the path was shown in the list of file sharing and I no longer saw the error:

```
ERROR: for web  Cannot start service web: Mounts denied:
The path /product_name
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

In addition, and I may be wrong on this part, it seemed like I was then able to add paths to other symlinks in the root folder by typing them in. However these symlinks are still not selectable in the above mentioned file modal.

  - macOS Version:
```
Docker for Mac: 3.0.1
```

**Comment by stephen-turner** [comment] 2020-12-14 09:13
Thanks for the report, I'm marking this as a dupe of #5028.

**Closed by stephen-turner** 2020-12-14 09:13 UTC
Labels: version/3.0.1

**Comment by banagale** [comment] 2020-12-14 19:55
Ah, I wish I'd seen that. Thank you.
