### ISSUE TITLE
High CPU from the desktop app

### ISSUE THREAD

**Issue by acdha** [docker/for-mac#4911] opened 2020-09-14 21:06 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D338C45A-CF61-4ED0-B620-C25186D02FEE/20200914210353

### Expected behavior

Docker with no containers running would use on negligible CPU

### Actual behavior

Docker.app is using ~133% CPU

This may be related to #4617 but it's happening in stable.

### Information

  - macOS Version:

ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

### Diagnostic logs

```
Docker for Mac: version 2.3.0.4

```

### Steps to reproduce the behavior

  1. Open Docker.app

**Comment by acdha** [comment] 2020-09-14 21:11
A factory reset appears to have fixed this issue but it's unclear what will cause it to return

**Comment by stephen-turner** [comment] 2020-09-15 10:07
You might like to try the latest Edge release, we've fixed a lot of CPU issues recently.

**Comment by stephen-turner** [comment] 2020-09-15 10:08
Thanks for the report. I'm going to close it as a dupe of #3499 and docker/roadmap#12.

**Closed by stephen-turner** 2020-09-15 10:07 UTC
Labels: version/2.3.0.4

**Comment by acdha** [comment] 2020-09-15 11:14
#3499 is the hyperkit process but what I reported was the app process.

**Comment by stephen-turner** [comment] 2020-09-15 11:51
We've fixed CPU issues in various places (and docker/roadmap#12 is general). I would advise trying Edge.
