### ISSUE TITLE
Fatal error: vmstateevent invalid json

### ISSUE THREAD

**Issue by eyablokov** [docker/for-mac#149] opened 2016-08-05 17:39 UTC
### Information

Diagnostic ID: C940B1B9-7206-44FE-B426-2A9CEBFBA749
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A269f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Didn't do anything special. I've updated to the new macOS Sierra just yesterday. Understand that's the beta, but maybe it'll help with some possible faults.
Thank you.
[C940B1B9-7206-44FE-B426-2A9CEBFBA749.tar.gz](https://github.com/docker/for-mac/files/404307/C940B1B9-7206-44FE-B426-2A9CEBFBA749.tar.gz)

**Comment by dsheets** [comment] 2016-08-05 17:44
Duplicate of #64.

**Closed** 2016-08-09 01:28 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
