### ISSUE TITLE
Cannot login on mac

### ISSUE THREAD

**Issue by ypanyukov** [docker/for-mac#874] opened 2016-10-31 07:55 UTC
### Expected behavior
success login
### Actual behavior
Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on 192.168.65.1:53: no such host
### Information

osx 10.12.1
Docker version 1.12.1, build 6f9534c

  Diagnosis ID FDEEA220-16CD-4C7D-9244-243F283B8849
 Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/FDEEA220-16CD-4C7D-9244-243F283B8849/20161031-105212.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce the behavior

  1. docker login
  2. input user & password

**Comment by mchiang0610** [comment] 2016-11-01 15:26
@ypanyukov I am able to login, and unable to reproduce.  Would it be possible for you to restart Docker for Mac or do a factory reset? 

Thanks for being a Docker user. I'm closing this for now, but if problems persist, please feel free to reply. We can always reopen the ticket.

**Closed by mchiang0610** 2016-11-01 15:26 UTC
Labels: osx/10.12.x, status/0-triage, version/1.12.1
