### ISSUE TITLE
Docker asks toupgrade or uninstall Virtualbox.

### ISSUE THREAD

**Issue by dileepkeeppalli** [docker/for-mac#1635] opened 2017-05-22 13:28 UTC
Docker shout start
Fatal Error
Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
VirtualBox v4.3.28 is currently installed.

**Comment by gtardif** [comment] 2017-05-23 09:24
Docker for Mac will not start if the kernel drivers from a Virtualbox version earlier than 4.3.30 are installed. Earlier versions of Virtualbox did not run reliably with applications that use Hypervisor.framework (such as Docker for Mac) which would result in system crashes.

Please upgrade Virtualbox or uninstall it. (To completely uninstall Virtualbox, please follow https://www.virtualbox.org/manual/ch02.html#idm871.)

(duplicate of docker/for-mac#78)

**Closed by gtardif** 2017-05-23 09:24 UTC
Labels: status/0-triage
