### ISSUE TITLE
Docker asks to create a symlink after every OS restart.

### ISSUE THREAD

**Issue by cperezabo** [docker/for-mac#6634] opened 2022-12-13 16:20 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Start at login without asking for permissions

### Actual behavior
It asks for permissions to create a symlink
<img width="370" alt="W1euE-2" src="https://user-images.githubusercontent.com/3604722/207386276-8747786a-8b90-43f2-a4ee-2ea8d917937d.png">
### Information
  - macOS Version: 13.0.1
  - Intel chip or Apple chip: M1 Pro
  - Docker Desktop Version: 4.15.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: is the com.docker.vmnetd process responding?
    Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory

The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.
```
### Steps to reproduce the behavior
Restart the computer

**Comment by aiordache** [comment] 2022-12-13 17:45
Hi @cperezabo! 
Can you try setting `authDeclinedInstallSettings` to true in `~/Library/Group\ Containers/group.com.docker/settings.json` and see if you still get the prompt on OS restart? Sorry for this, should be fixed in the next release.

**Comment by obriencj** [comment] 2022-12-15 20:46
Does setting authDeclinedInstallSettings to true also prevent it from altering ~/.profile ?

**Comment by cperezabo** [comment] 2022-12-15 21:55
I haven't tried, @aiordache said it will be fixed in next release, so I prefer not to touch the installation and let Docker fix itself.

**Comment by f-lombardo** [comment] 2022-12-16 08:48
> setting `authDeclinedInstallSettings` to true in `~/Library/Group\ Containers/group.com.docker/settings.json` 

This removes the dialog at login, but makes docker containers not available from external applications such as PhPStorm, that rises this error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock`

**Comment by aiordache** [comment] 2022-12-16 17:54
Hi :wave: 
To give some context, in Docker Desktop v4.15 we have changed a bit its setup to allow it to run fully unprivileged by default.
Previous versions of Docker Desktop enforced the installation of a privileged process(`com.docker.vmnetd`) that was handling configurations needing root access. That was a blocker for users that do not have/want to provide privileged access. This requirement was removed in v4.15.
By default, there should not be a privileged process running anymore, but, whenever Docker Desktop runs a configuration that requires privileged access, it prompts for password with a description of what it wants to do.  All configurations are documented in [here](https://docs.docker.com/desktop/mac/permission-requirements/). 

We are working on improving the setup and docs to provide more information on what is being configured and what it is needed for. But this may take a bit more time and iterations.

@f-lombardo The prompt you get on startup is triggered by the missing `/var/run/docker.sock`. The docker socket on MacOS is at `~/.docker/run/docker.sock` but as many tools rely on the default socket path of the Docker Engine `/var/run/docker.sock`, we need to create a symlink `/var/run/docker.sock   ->  ~/.docker/run/docker.sock` for backwards compatibility.
The problem is /var/run is a tmpfs so when you restart your machine, the content of that directory is removed; and unprivileged users cannot write to /var/run so Docker Desktop cannot create the symlink without root access. 
If you reject the prompt, the symlink is not created and clients relying on the default socket path won't work. 
We have this case [documented](https://docs.docker.com/desktop/mac/permission-requirements/). 

@obriencj You shell profile is updated only if you reject the prompt on the first startup which tries to add symlinks to docker binaries to `/usr/local/bin`. If you reject, Docker Desktop places the binaries under ~/.docker/bin and updates your shell profile to add this directory to your $PATH. Otherwise, when you run `docker` commands you'll get errors as the command won't be found.

**Comment by obriencj** [comment] 2022-12-16 20:06
Is there not a setting to tell docker desktop "please leave my profile alone" at startup? I notice it's doing it every single time.

**Comment by justinpawela** [comment] 2022-12-17 21:37
> and your shell profile will be updated.

> Is there not a setting to tell docker desktop "please leave my profile alone"

I agree with this sentiment. Unless I am misunderstanding how this works, it seems like either I have to give Docker Desktop privileged access or accept that it's going to help itself to modifying my carefully crafted shell profile. It seems (in a way) like a false choice.

I **fully** support the work to move Docker Desktop to an unprivileged process. However—and I think in the same spirit—I would prefer some way to opt out of Docker Desktop making changes for me. I understand this presents an avenue for beginners to shoot themselves in foot and that explaining `PATH` is an unenviable job. Hopefully the current situation is temporary and some "I actually know what I'm doing" option can be integrated, even if it's not the default and only mentioned on the help page.

**Comment by BeInLife** [comment] 2022-12-27 09:56
The question is -> How would it be handled if there are 2 users? I'm using 2 different users on the same machine (both use docker) for different contexts and it's quite annoying to restart docker every time I log in into different profile.

**Comment by rfay** [comment] 2023-01-04 15:27
This is a super-serious problem, looking forward to the fix. Every docker restart and every reboot of the computer requires manual intervention with a password, which means that the DDEV test runners all fail on a restart, etc.

**Comment by jcosentino** [comment] 2023-01-14 07:02
On Docker Desktop 4.16.1 (95567) on M1 Mac, setting **authDeclinedInstallSettings** to true does not work for me any longer. The file is still `~/Library/Group\ Containers/group.com.docker/settings.json` right?

**Comment by troyxmccall** [comment] 2023-01-14 20:19
i had this issue with 

```
OS: macOS 12.6.2 21G320 arm64 
Host: Macmini9,1 
Kernel: 21.6.0 
```

running 
```
docker: 4.16.1,95567
```


I was able to remediate by 

1) fully reinstalling `4.16.1,95567` via homebrew `brew cask reinstall docker --cask`
2) updating my macOS login items for my user to launch docker
3) also launch docker desktop on login from docker-desktop

see:

![login-settings-workaround](https://user-images.githubusercontent.com/129784/212494624-421b74d1-35f3-49fb-9f34-a0c345d21e2f.png)


for full transparency, this is my 

```
~/Library/Group\ Containers/group.com.docker/settings.json 
```

```json
{
  "backupData": false,
  "dockerAppLaunchPath": "/Applications/Docker.app",
  "displayedDeprecate1014": false,
  "diskFlush": "",
  "diskQcowCompactAfter": 0,
  "diskQcowKeepErased": 0,
  "diskQcowRuntimeAsserts": false,
  "diskStats": "",
  "vpnKitMTU": 1500,
  "vpnKitAllowedBindAddresses": "0.0.0.0",
  "vpnKitMaxConnections": 2000,
  "authDeclinedInstallSettings": false,
  "settingsVersion": 24,
  "autoStart": true,
  "activeOrganizationName": "",
  "useCredentialHelper": true,
  "credentialHelper": "docker-credential-osxkeychain",
  "disableTips": false,
  "tipLastViewedTime": 1673551679018,
  "tipLastId": 39,
  "updateAvailableTime": 0,
  "updateInstallTime": 0,
  "disableUpdate": true,
  "openUIOnStartupDisabled": false,
  "analyticsEnabled": true,
  "displayedTutorial": true,
  "disableHardwareAcceleration": false,
  "displayRestartDialog": true,
  "displayedElectronPopup": [],
  "latestBannerKey": "",
  "acceptCanaryUpdates": false,
  "useNightlyBuildUpdates": false,
  "autoDownloadUpdates": false,
  "lastLoginDate": 0,
  "themeSource": "system",
  "containerTerminal": "system",
  "allowExperimentalFeatures": true,
  "enableSegmentDebug": false,
  "dataFolder": "/Users/mode/Library/Containers/com.docker.docker/Data/vms/0/data",
  "memoryMiB": 8192,
  "swapMiB": 1024,
  "cpus": 4,
  "diskSizeMiB": 61035,
  "diskTRIM": true,
  "vpnkitCIDR": "192.168.65.0/24",
  "socksProxyPort": 0,
  "proxyHttpMode": "system",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "overrideProxyExclude": "",
  "filesharingDirectories": [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp",
    "/var/folders"
  ],
  "kubernetesEnabled": false,
  "showKubernetesSystemContainers": false,
  "kubernetesInitialInstallPerformed": false,
  "useVirtualizationFramework": true,
  "useVirtualizationFrameworkVirtioFS": true,
  "useVirtualizationFrameworkRosetta": false,
  "useGrpcfuse": true,
  "useVpnkit": true,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": true,
  "useWindowsContainers": false,
  "noWindowsContainers": false,
  "requireVmnetd": false,
  "wslEngineEnabled": false,
  "licenseTermsVersion": 2,
  "deprecatedCgroupv1": false,
  "useContainerdSnapshotter": false,
  "lifecycleTimeoutSeconds": 600,
  "exposeDockerAPIOnTCP2375": false,
  "enhancedContainerIsolation": false,
  "extensionsEnabled": true,
  "onlyMarketplaceExtensions": true,
  "showExtensionsSystemContainers": false,
  "useBackgroundIndexing": true
}
```

**Comment by romatou** [comment] 2023-01-16 04:33
> On Docker Desktop 4.16.1 (95567) on M1 Mac, setting **authDeclinedInstallSettings** to true does not work for me any longer. The file is still `~/Library/Group\ Containers/group.com.docker/settings.json` right?

Yes. It no longer works as explained by @aiordache in [comment](https://github.com/docker/for-mac/issues/6634#issuecomment-1349254061) above

**Comment by romatou** [comment] 2023-01-16 04:37
> We'll replaced this with a Docker signed wrapper in the next release to make sure it is not being prevented from running due to codesigning issues.

@aiordache, can _Docker Inc._ and _Docker_ in the _Allow in the Background_ section of _Login Items_ on macOS Ventura to be combined as one application (screenshot attached)?

<img width="518" alt="Screenshot 2023-01-16 at 9 36 53 AM" src="https://user-images.githubusercontent.com/49362229/212599619-8827bbc8-d7ff-416f-b392-2c32087a4970.png">

**Comment by aiordache** [comment] 2023-01-18 16:05
Hi👋 
Thank you all for your feedback. We are reworking the UX to address most of the concerns you expressed and are aiming to resolve these in the very near future. We want to make Docker Desktop more transparent about the configurations applied on the host and enable you to customize them.

@obriencj @justinpawela Sorry for the shell profile update, we shouldn't do that and we will fix this with the UX rework. Setting `authDeclinedInstallSettings` to false causes Docker Desktop to apply an unprivileged configuration as when you reject the prompt so you get the profile updated.

@BeInLife We cannot share the same instance of Docker Desktop between two users due to security reasons.

@rfay @jcosentino @romatou Do you still get the prompt on every restart? v4.16.1 should have the fix for the socket setup that was causing the prompts. If you restart your machines, you can check if `/var/run/docker.sock` symlink is being created before the startup of Docker Desktop. If it is missing, can you check why the launch daemon did not run properly? You can run the command below to retrieve information about it
```
sudo launchctl print system/com.docker.socket
```

@romatou We will check how to group the Login items. Thanks for the feedback!

**Comment by jcosentino** [comment] 2023-01-18 20:45
> /var/run/docker.sock

I do still get that prompt on restart.
Here is the result of `sudo launchctl print system/com.docker.socket`:

> system/com.docker.socket = {
> 	active count = 0
> 	path = /Library/LaunchDaemons/com.docker.socket.plist
> 	type = LaunchDaemon
> 	state = not running
> 
> 	program = /Library/PrivilegedHelperTools/com.docker.socket
> 	arguments = {
> 		/Library/PrivilegedHelperTools/com.docker.socket
> 		/Users/johncosentino/.docker/run/docker.sock
> 		/var/run/docker.sock
> 	}
> 
> 	default environment = {
> 		PATH => /usr/bin:/bin:/usr/sbin:/sbin
> 	}
> 
> 	environment = {
> 		XPC_SERVICE_NAME => com.docker.socket
> 	}
> 
> 	domain = system
> 	minimum runtime = 10
> 	exit timeout = 5
> 	runs = 1
> 	last exit code = 1
> 
> 	spawn type = background (5)
> 	jetsam priority = 40
> 	jetsam memory limit (active) = (unlimited)
> 	jetsam memory limit (inactive) = (unlimited)
> 	jetsamproperties category = daemon
> 	jetsam thread limit = 32
> 	cpumon = default
> 	probabilistic guard malloc policy = {
> 		activation rate = 1/1000
> 		sample rate = 1/0
> 	}
> 
> 	properties = partial import | runatload | managed LWCR | has LWCR
> }
>

**Comment by aiordache** [comment] 2023-01-19 09:12
@jcosentino Can you run directly the binary of the launch daemon and check exit code and if it creates the symlink?
```
$ /Library/PrivilegedHelperTools/com.docker.socket /Users/johncosentino/.docker/run/docker.sock /var/run/docker.sock
```
If everything works fine, can your add the fields below in your `/Library/LaunchDaemons/com.docker.socket.plist`, reload configuration for the launch daemon and restart?
```
<key>StandardOutPath</key>
<string>/tmp/docker-socket.stdout.txt</string>
<key>StandardErrorPath</key>
<string>/tmp/docker-socket.stderr.txt</string>
```
To reload the plist:
```
$ sudo /bin/launchctl unload /Library/LaunchDaemons/com.docker.socket.plist
$ sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.socket.plist
```
After you restart you should have the two files in /tmp. Check them for logged errors or any hint on why it doesn't create the symlink.  

If you have the item in System Preferences-> Users&Groups -> Login Items, check it is not disabled.

You could also check the Console -> Log Reports -> launchd.log for anything related to com.docker.socket

**Comment by christophermclellan** [comment] 2023-01-19 09:24
Regarding @obriencj's question:

> Is there not a setting to tell docker desktop "please leave my profile alone" at startup? I notice it's doing it every single time.

We're working on this as a top priority, thanks for the feedback and apologies for the current inconvenience. We have two potential approaches that we'd love some feedback on, so we can get started on implementing asap. If anyone is able to spare ~30 mins of their time to provide some insights, please email me at chris.mclellan@docker.com (or alternatively, I can try to reach out via email if you have one on your profile).

**Comment by jcosentino** [comment] 2023-01-19 15:48
> @jcosentino Can you run directly the binary of the launch daemon and check exit code and if it creates the symlink?
> 
> ```
> $ /Library/PrivilegedHelperTools/com.docker.socket /Users/johncosentino/.docker/run/docker.sock /var/run/docker.sock
> ```
> 
> If everything works fine, can your add the fields below in your `/Library/LaunchDaemons/com.docker.socket.plist`, reload configuration for the launch daemon and restart?
> 
> ```
> <key>StandardOutPath</key>
> <string>/tmp/docker-socket.stdout.txt</string>
> <key>StandardErrorPath</key>
> <string>/tmp/docker-socket.stderr.txt</string>
> ```
> 
> To reload the plist:
> 
> ```
> $ sudo /bin/launchctl unload /Library/LaunchDaemons/com.docker.socket.plist
> $ sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.socket.plist
> ```
> 
> After you restart you should have the two files in /tmp. Check them for logged errors or any hint on why it doesn't create the symlink.
> 
> If you have the item in System Preferences-> Users&Groups -> Login Items, check it is not disabled.
> 
> You could also check the Console -> Log Reports -> launchd.log for anything related to com.docker.socket
Here's the result of that command:
```
johncosentino@Johns-MacBook-Pro ~ % /Library/PrivilegedHelperTools/com.docker.socket /Users/johncosentino/.docker/run/docker.sock /var/run/docker.sock
os.Symlink(/Users/johncosentino/.docker/run/docker.sock, /var/run/docker.sock): symlink /Users/johncosentino/.docker/run/docker.sock /var/run/docker.sock: file exists
```
Here are some screenshots of what I see:

This shows the docker.sock symlink, when I try to view the original:
<img width="722" alt="docker sock cannot be found" src="https://user-images.githubusercontent.com/1408654/213487722-6da3b19d-17db-45d6-a311-b92e9b706aa6.png">

This shows that I do see the symlink even though it is prompting to create one:
<img width="722" alt="docker symlink exists" src="https://user-images.githubusercontent.com/1408654/213487727-e4ab48bf-a814-46d9-af2f-2c28902e8f90.png">

This shows the Get Info on that symlink file:
<img width="271" alt="docker symlink info" src="https://user-images.githubusercontent.com/1408654/213487731-179d8693-1073-4120-944b-d521ff650a10.png">

Here are my login items, Docker is enabled:
<img width="827" alt="login items" src="https://user-images.githubusercontent.com/1408654/213487732-bf742f2e-e021-4a9e-b04f-b98e6712d1b9.png">

I wanted to note that the stdout and stderr outputs are empty even after enabling them.

Also, this is my launchd.log with the non-docker items removed:
[launchd.log](https://github.com/docker/for-mac/files/10458269/launchd.log)

**Comment by aiordache** [comment] 2023-01-19 18:23
@jcosentino Thank you for the information, the launchd.log you attached contains this error:
```
(com.docker.socket) <Error>: Unknown key for plist importer (key: ServiceDescription type: string)
```
Can you modify again the plist to remove that property, unload/load it again, restart the machine and see if this fixes?

**Comment by jcosentino** [comment] 2023-01-19 22:47
> 

I removed that, now I don't see that error in the logs. But the issue with the symlink prompt is still present

**Comment by dakala** [comment] 2023-01-20 06:58
Upgrading to 4.16.1 a short while ago, seemed to make the symlink prompt go away - it was there before the upgrade.  When it's starting up, a red message appears transiently at the bottom of the window - disappears too quickly for me to read it. However, the old "Docker Desktop wants to create ... symlink" doesn't show up. 

Perhaps unrelated, but the "Start Docker Desktop when you log in" setting stopped working.

<img width="278" alt="Screenshot 2023-01-20 at 06 46 17" src="https://user-images.githubusercontent.com/285543/213635889-d5ae133d-b521-40cf-a026-a373d1635941.png">

<img width="486" alt="Screenshot 2023-01-20 at 06 43 47" src="https://user-images.githubusercontent.com/285543/213635954-6e45b9d8-cfe9-4494-816e-43ce7ed64b5a.png">

<img width="1023" alt="Screenshot 2023-01-20 at 06 45 41" src="https://user-images.githubusercontent.com/285543/213636113-f588e0cd-1a69-422c-b429-021fd986165b.png">

**Comment by aiordache** [comment] 2023-01-20 16:35
@jcosentino Have you checked again the exit code/runs reported by the launchctl print command? 
You can test manualy the login item without needing to restart all the time.

Remove first the symlink if it exists:
```
 $ sudo rm /var/run/docker.sock                     
Password:
$ ls -al /var/run/docker.sock  
ls: /var/run/docker.sock: No such file or directory
```
Run the login item
```
$  sudo launchctl kickstart system/com.docker.socket
Password:
```
Check the symlink was created right after. If not created, check again the exit code reported by launchctl print and if other errors were reported in the console for com.docker.socket
```
$ ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  35 Jan 20 17:08 /var/run/docker.sock -> /Users/toto/.docker/run/docker.sock
```


@dakala You are right, the start on login does not work anymore. Thank you for reporting it and sorry for the regression. We'll fix it and check why it was not caught by our tests.
Concerning the red message, may be caused by the GUI querying some backend/VM component too fast and it did not boot yet. We'll talk with the frontend team to see how to improve this. Thanks!

**Comment by jcosentino** [comment] 2023-01-20 17:10
> 

It is present:

> johncosentino@Johns-MacBook-Pro ~ % ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  44 Jan 20 11:53 /var/run/docker.sock -> /Users/johncosentino/.docker/run/docker.sock
johncosentino@Johns-MacBook-Pro ~ % sudo rm /var/run/docker.sock
johncosentino@Johns-MacBook-Pro ~ % sudo launchctl kickstart system/com.docker.socket
johncosentino@Johns-MacBook-Pro ~ % ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  44 Jan 20 11:54 /var/run/docker.sock -> /Users/johncosentino/.docker/run/docker.sock


Here's my launchd.log with only the docker entries:
[launchd.log](https://github.com/docker/for-mac/files/10468525/launchd.log)

This was all done during a startup where Docker desktop autolaunched and prompted for my password in order to create the symlink. I allowed it, then ran those commands. The launchd log snapshot was saved after I input the commands (and after the startup of Docker Desktop).

**Comment by aiordache** [comment] 2023-01-20 19:09
@jcosentino I am a bit confused about your setup. 

Please turn off the autolaunch of Docker Desktop, restart your machine and then check if the symlink exists. Do not start Docker Desktop yet.

- If the symlink does not exist after machine reboot, the problem is again in the setup of the Login item. Starting Docker Desktop prompts you to create the symlink as the prompt is triggered by it missing.


- If the symlink exists after reboot, then the Login item runs correctly. Check the source of the symlink :
```
ls -l /var/run/docker.sock       
lrwxr-xr-x ...  /var/run/docker.sock -> /Users/toto/.docker/run/docker.sock
```
 Starting Docker Desktop should not prompt you to create the symlink anymore as it already exists. 
If Docker Desktop still prompts you, accept the prompt and then check again the source of the symlink it created. Is it the same as the one before starting Docker Desktop?


Can you upload a diagnostics bundle for us to see if any error related to the setup is being logged, the version of your OS etc.

**Comment by jcosentino** [comment] 2023-01-20 23:05
I turned off autostart and restarted my laptop. I checked for the docker.sock file:
```
johncosentino@Johns-MacBook-Pro ~ % ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  44 Jan 20 17:58 /var/run/docker.sock -> /Users/johncosentino/.docker/run/docker.sock
```

Here's my diagnostic ID:
`7575278B-3F97-408F-9302-F12090E1F1B4/20230120225959`

**Comment by rfay** [comment] 2023-01-27 18:19
I have not been having trouble with the request for password to create symlink in 4.16.2 on several machines running Ventura. 

As noted elsewhere, on the first reboot or logout/login after upgrade Docker Desktop doesn't auto-start even though configured to do so.

**Comment by subigre** [comment] 2023-01-29 14:48
Hi everyone, I never had this issue before but after reinstalling my MacBook and Docker Desktop (4.16.2) on it, I have now the same pop-up asking me my password to create a symlink. I tired to set `authDeclinedInstallSettings` to `true` but it is not working.
Is there any fix currently r we have to wait for a new release?

**Comment by thomasriise** [comment] 2023-01-29 15:00
I get this also on macOS 13.2 (22D49) and Docker version 4.16.2 (95914) on a Macbook Pro M1 16GB.

<img width="293" alt="Screenshot 2023-01-29 at 15 55 40" src="https://user-images.githubusercontent.com/45291874/215335054-933df7f4-4c1e-4c5b-9d6c-6cb296b58ee6.png">

**Comment by ShutdownRepo** [comment] 2023-02-01 11:32
Same issue here

**Comment by zxzjim** [comment] 2023-02-02 08:09
Same issue here, please fix it....
Docker desktop 4.16.2 (95914)
Ventura 13.2

**Comment by rfay** [comment] 2023-02-03 20:22
I thought this was probably solved, I think I did see it go away on some mac test-runners, but just had it again, 4.16.2.

**Comment by pkishino** [comment] 2023-02-06 02:32
Yes, same here.. the actual symlink is created and if I cancel the request docker will startup properly and everything works..but the request seems bugged

**Comment by tejashs** [comment] 2023-02-07 20:21
Same here. I still get the popup from osascript about creating simlink. Canceling it works and Docker desktop starts just fine.

**Comment by onedr0p** [comment] 2023-02-07 20:55
Same issue here, please fix it....

Docker desktop 4.16.2 (95914)
Ventura 13.2

**Comment by edoardopirovano** [comment] 2023-02-08 10:54
Also getting this issue.

**Comment by bronson** [comment] 2023-02-09 19:32
I don't understand why this feature even exists in Docker. Because I want Docker to start on login, I added it to Preferences -> General -> Login Items:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1776/217918237-60172bbb-730c-422a-bb5f-c7d24848c481.png">

Which works great, except for this irratating dialog popping up on every login.

**Comment by luisdnodrizat** [comment] 2023-02-21 08:37
any updates? same issue here
Docker desktop 4.16.2 (95914)
Ventura 13.2

**Comment by holly-cummins** [comment] 2023-02-24 11:46
Same here. I've confirmed that the symlink does exist, and yet I get a GUI prompt to create it after every reboot. This is a blocker for headless docker:

```
githubactions@administrators-Mac-mini ~ % ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  71 24 Feb 06:41 /var/run/docker.sock -> /Users/githubactions/.local/share/containers/podman/machine/podman.sock
```

**Comment by chaizeg** [comment] 2023-02-27 17:58
Closing this issue because a fix has been released in Docker Desktop 4.17.0 . See the [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Closed by chaizeg** 2023-02-27 17:58 UTC
Labels: version/4.16.2

**Comment by waimun** [comment] 2023-03-31 02:05
@BeInLife I have a similar use case as you that is running Docker with two local users. One way is to quit the other one, and follow the commands here to recreate the symlink again. https://github.com/docker/for-mac/issues/6634#issuecomment-1398638982

**Comment by romatou** [comment] 2023-05-09 06:10
Hi @aiordache,

> @romatou We will check how to group the Login items. Thanks for the feedback!

Any updates on this one? 👆
