### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by aldwnesx** [docker/for-mac#6657] opened 2023-01-02 15:53 UTC
I have the following at top of Dockerfile

`FROM --platform=linux/amd64 ubuntu:20.04 as image_name
`

I am able to build the image on M1. In the past few days the container is running fine, but suddenly today it keeps crashing due to:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

I have tried resetting and reinstalling docker but keep getting this. Any idea what is causing it? No changes to image and code

**Comment by pavelgnom** [comment] 2023-01-13 00:48
I have a pretty similar issue, trying to build a `linux/arm64` image on my Intel Mac and getting the same error.

**Comment by Naist4869** [comment] 2023-01-26 05:40
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```bash
docker run -it --rm -p=0.0.0.0:9222:9222 --platform linux/amd64 --name=chrome-headless -v /Users/lan/Desktop/chromedata/:/data alpeware/chrome-headless-stable 

```

> Looking for CA certificate in /data/certificates
Keystore created
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
basename: missing operand
Try 'basename --help' for more information.
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so,
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.
Segmentation fault

**Comment by pejrich** [comment] 2023-01-26 18:40
Yup. Getting this too. Kinda frustrating that the last time this issue was discussed it was just closed and locked without a solution. https://github.com/docker/for-mac/issues/5123

**Comment by y86** [comment] 2023-07-14 13:18
At least for the problem described with the Erlang image, it seems the problem is related to this issue with qemu and jit compilers: https://gitlab.com/qemu-project/qemu/-/issues/1034 that has been solved here https://gitlab.com/qemu-project/qemu/-/commit/9719f125b803f4e0fda834cd74a60dfa4ca398e2 10 days ago.

How long does it usually take until this fix on qemu lands on a new docker desktop version?

**Comment by dgageot** [comment] 2024-01-04 10:20
Hello everyone! Has anyone been able to reproduce with Docker Desktop 4.26? It contains a lot of fixes to the emulation layer, especially with Rosetta enabled.

**Comment by dgageot** [comment] 2024-01-26 15:11
Hey everyone! I'm going to assume this is fixed and close the issue. Feel free to ping me if you think it should be re-opened

**Closed by dgageot** 2024-01-26 15:11 UTC
Labels: area/emulation

**Comment by jeeeyul** [comment] 2024-05-02 05:07
@dgageot  I could reproduce this problem with Docker Desktop 4.29.

I tried to build a linux/arm64 image on Intel Mac. 
Installing `openjdk-11-jdk` by `apt-get` from `buildpack-deps` reproduces this problem.

**Comment by Coo3n** [comment] 2024-05-03 19:38
> @dgageot I could reproduce this problem with Docker Desktop 4.29.
> 
> I tried to build a linux/arm64 image on Intel Mac. Installing `openjdk-11-jdk` by `apt-get` from `buildpack-deps` reproduces this problem.

░░░░░░▄█▀█▄░░░░░░░░░░░░░░░
░▄█▀▀▀▀░░░░▀█▄▄▄▄▄▄▄░░░░░░
█▀░░░░░░░░░░░░░░░░░▀█░░░░░
▀▄░▄░░░░░░░░░░░░░░░▄█░░░░░
░█████▄▄▄▄▄██▄▄▄█▀▀█░░░░░░
░█▀█░░░░▀░░░░░▀░░░░█▀▀▀▀▀█
░█░███▄▄▄▄░░░▄▄▄▄▄██▀▀██░█
░█░███░████▀████░███░░█░░█
░█▄███░████░████░███░░█░█▀
░░░███░████░████░███░░█░█░
░░░███░████░████░███▄▄█░█░
░░░███░████░████░███░░░▄█░
░░░███░████░████░███▀▀▀▀░░
░░▄███▄████░████▄███▄░░░░░
░░███▀███████████▀███░░░░░
░░░░▀▀▀██▄▄▄▄▄██▀▀▀░░░░░░░

**Comment by Coo3n** [comment] 2024-05-03 19:40
> @dgageot I could reproduce this problem with Docker Desktop 4.29.
> 
> I tried to build a linux/arm64 image on Intel Mac. Installing `openjdk-11-jdk` by `apt-get` from `buildpack-deps` reproduces this problem.
how are you?

**Comment by Misiu** [comment] 2025-04-07 10:04
I have a .NET9 app and I try to build it on Windows 10 with this command:
```
docker build --platform linux/arm64/v8 -f Next.Web/Dockerfile .
```
I get this error:

> qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> Segmentation fault (core dumped) 

Docker Desktop 4.40.0 (187762)
WSL:  2.4.13.0

**Comment by rayne-jiang** [comment] 2025-04-20 22:51
I got the same issue with .NET8 app when I was trying to build it on amd64

`docker build --platform=linux/amd64`

Got error

> [build 6/8] RUN dotnet restore --use-current-runtime --packages /root/.nuget/packages:
> 5.799   Determining projects to restore...
> 12.61 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> 12.72 Segmentation fault
