### ISSUE TITLE
macOS Sierra Public Beta 3, docker crashes on build

### ISSUE THREAD

**Issue by sunny-kiev** [docker/for-mac#150] opened 2016-08-05 19:32 UTC
### Information

Diagnostic ID: 531E647B-2124-4093-B065-DC8DA646B6A9
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/sunny/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/sunny/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/sunny/Library/Containers/com.docker.docker/Data/s51: check if service is running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by avsm** [comment] 2016-08-08 14:58
Duplicate of #64 -- please see https://github.com/docker/for-mac/issues/64#issuecomment-238191340 for progress on getting this working.

**Closed by avsm** 2016-08-08 14:58 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
