### ISSUE TITLE
Adding "empty" insecure registries causes fatal error

### ISSUE THREAD

**Issue by pontusolsson** [docker/for-mac#2606] opened 2018-02-14 10:27 UTC
### Expected behavior
Adding registries through the GUI should not be able to cause a fatal error.

### Actual behavior
Adding an empty string as an insecure registry and pressing "Apply & Restart" causes docker to crash with fatal error until .docker/daemon.json is modified or docker is reset to factory defaults.

This is easily done by mistake as pressing "Apply & Restart" while still entering text in the field causes the changes to be discarded. 

### Steps to reproduce the behavior

  1. Choose Preferences from Docker Menu
  2. Press Daemon -> Basic
  3. Press "+" under insecure registries
  4. (optional) enter text (i e) "127.0.0.1/32" Don't press enter or tab!
  5. press Apply & Restart

**Comment by pgayvallet** [comment] 2018-02-14 10:39
Duplicate of https://github.com/docker/for-mac/issues/2478

**Closed by pgayvallet** 2018-02-14 10:39 UTC
