### ISSUE TITLE
issues turning off Use gRPC FUSE for file sharing

### ISSUE THREAD

**Issue by couchmeka** [docker/for-mac#6496] opened 2022-09-24 18:09 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
disabling Use gRPC FUSE for file sharing for file sharing and apply and restart 
### Actual behavior
restarts and re checks Use gRPC FUSE for file sharing
### Information

  - macOS Version: Mac OS Monterey V 12.6
  - Intel chip or Apple chip: Apple chip 
  - Docker Desktop Version: Docker version 20.10.17

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mschatz** [comment] 2022-09-26 00:12
Same here. I uncheck this to turn it off, but it turns itself back on when I hit "Apply & Restart". This is with Docker version 20.10.17, build 100c701 on Monterey 12.0.1 with an Apple M1. Note I need to disable this for miniwdl (https://github.com/chanzuckerberg/miniwdl)

Thanks! Mike

**Comment by nicks** [comment] 2022-09-26 05:19
thanks for reporting! I'm going to mark this as a duplicate of https://github.com/docker/for-mac/issues/6467. That issue has a workaround. We're hoping to fix this in the next release.

**Closed by nicks** 2022-09-26 05:19 UTC

**Comment by mschatz** [comment] 2022-09-26 13:58
Thank you for pointing this out!
