### ISSUE TITLE
In-place sed replacement on file in a bind mounted dir with Docker for Mac maxes one CPU core out

### ISSUE THREAD

**Issue by davoustp** [docker/for-mac#728] opened 2016-09-30 09:06 UTC
### Expected behavior

From a container, in-place editing a file (using sed) which lies in a bind-mounted directory should work flawlessly (_even if slow - acknowledging performance issue with osxfs bind mounting here_).

### Actual behavior

When doing several in-place edits quickly (performed with sed in a loop in the project to reproduce), the container just stalls at some point: the sed process in the container just **runs forever**, maxing one full CPU core out doing so.

### Information
Diagnostic ID: 003EF2BA-7EB9-43E8-B04E-D400EEC58694

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1808)
logs: /tmp/003EF2BA-7EB9-43E8-B04E-D400EEC58694/20160930-104319.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

Github project to reproduce the issue is located at https://github.com/davoustp/dockerformac-mountissue

### Steps to reproduce the behavior

1. Build the image from the GitHub project:
`docker build .`
2. Run the container without bind mounting:
`docker run --rm {imageId}`
No issue
3. Run it with bind mounting the directory where file edit takes place (in $HOME/tmp directory in this example):
`docker run --rm -v $HOME/tmp:/tmp {imageId}`

The process never ends an one CPU core is maxed out.

**Comment by dsheets** [comment] 2016-10-10 16:42
Thanks for your report and excellent reproduction! This looks like a duplicate of #495 as I could reproduce it with Beta 27 but cannot with the branch that will be released as Beta 28. I will add your test case to our test suite. The fix should reach the stable channel along with 1.12.2. Thanks, again!

**Closed by dsheets** 2016-10-10 16:42 UTC
Labels: area/mounts, osx/10.10.x, status/0-triage, version/1.12.1
