### ISSUE TITLE
Container Toolbar Scrolls Out of View

### ISSUE THREAD

**Issue by miles-po** [docker/for-mac#5393] opened 2021-02-25 21:14 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The toolbar remains in place while scrolling down through container logs.

### Actual behavior
Scrolling down through logs scrolls the toolbar out of view so that one must scroll back to the top to stop/delete a container.

### Information

  - macOS Version: 11.1
  - Docker Desktop Version: 3.1.0 (51484)

Reproducible, new problem, appeared with an update.

### Steps to reproduce the behavior

  1. Start a container that prints more than a page's worth of text into the console
  2. Scroll down to the bottom
  3. Notice that the toolbar is no longer accessible

**Comment by stephen-turner** [comment] 2021-02-26 09:00
Thanks, this is a dupe of #5290. Fix coming soon.

**Closed by stephen-turner** 2021-02-26 09:00 UTC
Labels: version/3.1.0
