### ISSUE TITLE
block in `Kubernetes is starting`

### ISSUE THREAD

**Issue by cnskyboy88** [docker/for-mac#3019] opened 2018-06-20 14:28 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:4B7F6E41-79F5-4E20-A531-DEA9C237F049/20180620-222339

### Information

  - macOS Version: 10.12.5 Beta (16F71b)

### Diagnostic logs

```
Docker for Mac: 18.05.0-ce-mac67 (25042)

```

### Steps to reproduce the behavior

  1. reinstall docker for mac
  2. start with kubernetes

**Comment by djs55** [comment] 2018-06-20 15:45
I believe this is a duplicate of #2990. There's an experimental build with a candidate fix, described in this comment: https://github.com/docker/for-mac/issues/2990#issuecomment-398798486

**Closed by djs55** 2018-06-20 15:45 UTC
