### ISSUE TITLE
Docker Desktop is not showing Containers

### ISSUE THREAD

**Issue by gonzs** [docker/for-mac#6349] opened 2022-06-08 17:43 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1AD10F09-2560-481D-8D16-C2D2B0A37011/20220608173806

### Expected behavior
Docker containers to appear in UI

### Actual behavior
I can see containers via CLI but UI doesn't show anything, just a black screen.

![image](https://user-images.githubusercontent.com/7064337/172682616-e751e33f-480a-4639-ad7d-26a0b824d49f.png)

### Information
  - macOS Version: Monterrey 12.4
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.9.0

### Steps to reproduce the behavior
  1. ... No steps to reproduce
  2. ...

**Comment by nicks** [comment] 2022-06-08 22:46
Thanks for reporting! I think this is likely a duplicate of https://github.com/docker/for-win/issues/12759, so closing this issue to centralize discussion of workarounds there.

**Closed by nicks** 2022-06-08 22:46 UTC
Labels: version/4.9.0
