### ISSUE TITLE
Very slow outgoing and incoming trafic

### ISSUE THREAD

**Issue by sebastienDevibim** [docker/for-mac#727] opened 2016-09-29 16:50 UTC
### Expected behavior

Have a normal outgoing trafic with a normal ping
### Actual behavior

Every time the outgoing trafic is very slow and can reach 30 seconds to reach an external server.
### Information

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/91E57AEB-F466-4D96-A2E8-E4C6E8546025/20160929-184705.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. Make a request to an external service (Twitter API or personnel server in my case)
2. Observe than the answer is very slow to come

**Comment by dsheets** [comment] 2016-09-29 16:53
Does this reproduce for you under all circumstances? Is there a very simple test case that reproduces the behavior? Do you have unusual network components in your environment (e.g. VPN, proxy, strange middleboxes, unusual link types like bluetooth, etc)?

**Comment by sebastienDevibim** [comment] 2016-09-29 16:58
I'm always connected through ethernet.
I don't have any VPN or proxy, only a Freebox (a French router) between my computer and the internet.
I didn't have the problem before the last update (beta 27).
You can try to reproduce it by trying to connect to the Twitter API with TwitterOAuth in php.
The problem is not the Twitter API because it has a normal response time on a Debian server with the same php code.

**Comment by spassig** [comment] 2016-09-30 11:26
Same for me after upgrading to "1.12.2-rc1-beta27". Also Docker restarts automaticaly for more often. OS Version 10.12.

**Comment by andreychernih** [comment] 2016-10-04 02:01
I can confirm network performance degraded significantly in beta 27.

**Comment by martintrojer** [comment] 2016-10-04 08:06
One more datapoint from me. Unbearably slow in 1.12.1

**Comment by tadayosi** [comment] 2016-10-06 03:28
I had a similar issue with incoming ssh connections to a guest OS. It was resolved by changing the DNS configuration on the host Mac OS (explicitly setting `8.8.8.8` at the top).

Mac OS: 10.11.6, Docker: 1.12.1

**Comment by samoht** [comment] 2016-10-12 18:44
Your logs contains two issue: one is docker/hyperkit#50 and docker/vpnkit/131. The first one should be fixed in latest (and upcoming) Beta releases, the second one is being working on.

**Comment by martintrojer** [comment] 2016-11-12 12:25
Still extremely slow in 1.12.3 (macOS 10.12.1).

About 10x slower than 1.12.0-a

**Comment by dsheets** [comment] 2016-11-14 10:08
Perhaps you are experiencing #668 ([workaround](https://github.com/docker/for-mac/issues/668#issuecomment-250406582)) and the issue is block device performance rather than network-related?

**Comment by martintrojer** [comment] 2016-11-14 11:17
@dsheets didn't help :(

**Comment by ijc25** [comment] 2016-11-14 14:54
Please can someone provide a set of specific reproduction steps?

Using "the Twitter API with TwitterOAuth in php" was mentioned above but what we actually need is a _specific_ set of steps which a developer can follow in order to demonstrate the problem. A Dockerfile would be one convenient way to encapsulate that, but really a script or even just list of specific commands to run would suffice.

Please assume that the developer trying to repro the issue is not familiar with any particular web technology of framework etc (for instance personally I don't have the first clue how one interacts with TwitterOAuth in any language, let alone php).

**Comment by sebastienDevibim** [comment] 2016-11-14 16:25
@ijc25 
Here is an example of how you can test :

Dockerfile :
```
FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive

RUN (apt-get update && apt-get upgrade -y -q && apt-get dist-upgrade -y -q && apt-get -y -q autoclean && apt-get -y -q autoremove)

RUN apt-get install -y -q curl

CMD ["/bin/bash"]
```

Docker commands made to build and run :
```
docker build -t test .
docker run -dit -h test.local test
docker exec -it containerId "/bin/bash"
```

Command to launch in container :

``` curl -o /dev/null -s -w %{time_connect}:%{time_starttransfer}:%{time_total} http://www.google.com```

I've got these results on the container :
5.554:5.608:5.608

Directly on my Mac I've got these results :
0.119:0.161:0.161

You can see than there is a big difference at the connection time.

Thanks for trying to help us !

**Comment by ijc25** [comment] 2016-11-14 17:07
@sebastienDevibim thank you very much for the repro steps. I have escalated this issue into our internal tracker.

**Comment by stvleung** [comment] 2016-11-17 20:10
I just want to comment that I also experienced this issue, but the latest beta: `Version 1.12.3-beta30.1 (13946)` fixed it for me. Thanks!

**Comment by ijc25** [comment] 2016-11-18 11:09
@stvleung thanks for the info.

@sebastienDevibim @martintrojer @andreychernih @tadayosi @spassig Are you able to try beta30.1 and if so do you also see an improvement? Be aware that if you are switching from the stable to beta channel then a factory reset will be required which will lose your current containers.

**Comment by sebastienDevibim** [comment] 2016-11-19 20:50
@ijc25 Seems ok for me thanks for the fix !

**Comment by ijc25** [comment] 2016-11-21 10:27
Thanks for confirming! Closing this issue.

**Closed by ijc25** 2016-11-21 10:27 UTC
Labels: area/network, kind/performance, osx/10.12.x, status/1-acknowledged, version/beta27
