### ISSUE TITLE
Container does not start with ECI and Rosetta enabled

### ISSUE THREAD

**Issue by kingtistel** [docker/for-mac#6886] opened 2023-06-22 12:01 UTC
Hi, I've come across a different issue:
(Docker business support sent me here)
If I have "Enhanced Container Isolation" enabled along side "Use Rosetta for x86/amd64 emulation on Apple Silicon" then the container does not start, emitting an error:
`rosetta error: Failed to get stack rlimit`

So if I want the benefit of Rosetta I need to disable ECI.

### Two steps reproduction
0. Make sure you have both ECI and "Use Rosetta for x86/amd64 emulation on Apple Silicon" enabled.
1. docker pull --platform=linux/amd64 hello-world
2. docker run --rm hello-world
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> rosetta error: Failed to get stack rlimit

Diagnostic ID: 59ACAA94-FE89-4B40-80A2-608E2C4632A9/20230620115220

_Originally posted by @kingtistel in https://github.com/docker/roadmap/issues/384#issuecomment-1599531719_

**Comment by bsousaa** [comment] 2023-06-23 08:30
We are investigating and will get back to you soon.

**Comment by kingtistel** [comment] 2023-10-02 19:16
After updating to macOS Sonoma and Docker Desktop v4.24 - this issue is resolved.

**Comment by ctalledo** [comment] 2023-10-12 18:40
Thanks @kingtistel for reporting and following up on this.

The problem is fixed on Docker Desktop v4.22 and after (we've verified this on macOS 13 (Ventura) and macOS 14 (Sonoma). 

Closing now.

**Closed by ctalledo** 2023-10-12 18:40 UTC
Labels: status/triage, status/needs-investigating, version/4.20.1
