### ISSUE TITLE
Jhipster registry cannot start in Docker M1 new Desktop version

### ISSUE THREAD

**Issue by thapatwat** [docker/for-mac#5763] opened 2021-06-16 11:52 UTC
Jhipster registry cannot start in Docker M1 As I mention on title ,
I used Registry image version: v6.3.0 in docker hub. Monitor log has show error as below when I start docker container
<img width="1440" alt="Screen Shot 2564-06-07 at 21 24 59" src="https://user-images.githubusercontent.com/85997637/122213755-7b7ad180-ced3-11eb-8aa6-2cad75a913cc.png">
I'm not sure is that your problem, Jhipster side or I did something wrong.
Please answer me if you guy know how to solve this issue. Thank you

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

runnable on localhost port 8761

### Actual behavior

<img width="1440" alt="Screen Shot 2564-06-07 at 21 24 59" src="https://user-images.githubusercontent.com/85997637/122213755-7b7ad180-ced3-11eb-8aa6-2cad75a913cc.png">

### Information

  - macOS Version: 11.1
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: Docker Desktop 3.4.0 (65384)

**Comment by StefanScherer** [comment] 2021-06-17 07:13
Thanks @thapatwat, but there's too few information. I looked at the Hipster Docker Hub image, they only provide linux/amd64 images. Please ping them to provide a native linux/arm64 image that works on the M1 without emulation. At least that would improve performance, but I don't know if that solves your problem entirely.
I'm going to close this ticket, because it's not a bug in Docker Desktop.

**Closed by StefanScherer** 2021-06-17 07:13 UTC
