### ISSUE TITLE
Unable to login and pull from insecure registry

### ISSUE THREAD

**Issue by vce-xx** [docker/for-mac#2374] opened 2018-01-08 16:08 UTC
### Expected behavior

With Docker for Mac Version 17.12.0-ce-rc4-mac44 (21438)
```
cat pwd.txt | docker login -u xxx --password-stdin myregistry:5000
Login Succeeded
```

### Actual behavior

With Docker for Mac Version **17.12.0-ce-mac45** (21669)
```
cat pwd.txt | docker login -u xxx --password-stdin myregistry:5000
Error response from daemon: login attempt to http://myregistry:5000/v2/ failed with status: 400 Bad Request
```

### Information

Docker unable to login and pull from insecure registry with Docker for Mac Version 17.12.0-ce-mac45 (21669)
The registry is a Registry:2 image from Docker hub (updating the image didn't fix the issue) exposing port 5000 without certificate.
Docker for Mac is configured to use the insecure registry : 
```
{
  "debug" : true,
  "experimental" : true,
  "insecure-registries" : [
    "myregistry:5000"
  ]
}
```
Reverting to Docker for Mac Version 17.12.0-ce-rc4-mac44 (21438) fixed the issue.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.12.5 (build: 16F2073)
logs: /tmp/77CC86A0-C321-4DE6-8DEC-D7887045C5C2/20180108-165014.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install an insecure registry on LAN
  2. Configure Docker for Mac to use the insecure registry
  3. docker login on that registry

**Comment by deguif** [comment] 2018-01-08 16:12
I got the same issue after upgrading this morning.
Reverting to RC4 fixes the issue.

**Comment by djs55** [comment] 2018-01-08 20:18
Thanks for the report -- I can reproduce this locally. I'm investigating now.

**Comment by djs55** [comment] 2018-01-09 14:51
This is believed fixed in today's stable release `17.12.0-ce-mac46` available from https://download.docker.com/mac/stable/21698/Docker.dmg

Let us know if this works for you.

Thanks again for your report!

**Closed by djs55** 2018-01-09 14:51 UTC
Labels: osx/10.12.x, status/0-triage, version/17.12.0-ce-mac45

**Comment by vce-xx** [comment] 2018-01-09 15:17
Back to normal.
Perfect !
Thanks

**Comment by akurkin** [comment] 2018-01-10 11:07
is there any info how to get this as an edge build? or when it will be available?

**Comment by ThomasNegeli** [comment] 2018-01-10 22:11
@djs55 seems not to be fixed.
I updated via docker internal updater, and now I can not push to our insecure registry.
If I use the previous docker version, I can push.

**Comment by Schnitzel** [comment] 2018-01-11 20:05
I've got the same problem: Trying to push into an OpenShift Registry of Minishift.

Tested with `17.12.0-ce-mac46` and it fails, going back to `17.09.0-ce-mac35` (from https://jsok.github.io/docker-for-mac-versions/) works again.

Also verified that when running a Docker in Docker with 17.12 stable that one can connect to it, so it looks like a problem on Mac only.
