### ISSUE TITLE
docker-compose is dead sluggish after the new update (1.12.1)

### ISSUE THREAD

**Issue by kishaningithub** [docker/for-mac#661] opened 2016-09-17 04:17 UTC
### Issue

After the new upgrade (1.12.1) docker-compose is dead sluggish
in starting and stopping containers.. It takes like 15 mins :-O

Kindly note i am starting via docker-compose run and stopping
via docker-compose stop (Attached the scripts and yml)
### Information
- Diagnostic ID: AA29E5F0-DC99-41D9-B944-0648349F074B
- Attached my docker-compose.yml, run.sh and stop.sh in a zip file
  [docker-compose-attach.zip](https://github.com/docker/for-mac/files/477970/docker-compose-attach.zip)

**Comment by djs55** [comment] 2016-09-17 08:05
Thanks for the report. I can't seem to replicate the `docker-compose` sluggishness on my machine here which suggests the problem is an interaction between Docker for Mac and some environments.

This might be another example of #133 -- I suspect each API call made by `docker-compose` is performing a (M)DNS lookup due to a `.local` search domain and timing out after 5s. Each `docker-compose` command typically does lots and lots of API calls.

Could you try editing `/etc/hosts` on the Mac and appending
```
127.0.0.1 localunixsocket.local
```
If that doesn't work, could you capture DNS traffic on your Mac and post it here (if you're comfortable with that). Something like:

```
$ sudo tcpdump -n -i en0 port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
09:05:38.979499 IP 192.168.1.103.54772 > 192.168.1.2.53: 21703+ A? googlemail.l.google.com. (41)
09:05:39.022385 IP 192.168.1.2.53 > 192.168.1.103.54772: 21703 4/0/0 A 74.125.206.19, A 74.125.206.83, A 74.125.206.17, A 74.125.206.18 (105)
09:05:41.870840 IP 192.168.1.103.50740 > 192.168.1.2.53: 44850+ A? www.cam.ac.uk. (31)
09:05:41.937576 IP 192.168.1.2.53 > 192.168.1.103.50740: 44850 1/0/0 A 131.111.150.25 (47)
```

**Comment by kishaningithub** [comment] 2016-09-17 14:03
Hi, Adding the `127.0.0.1 localunixsocket.local` to `/etc/hosts` did not work :-(
Posting the tcp dump here
```
➜  ~ sudo tcpdump -n -i en0 port 53
Password:
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
19:31:57.826372 IP 192.168.1.7.58748 > 192.168.1.1.53: 51051+ A? localunixsocket. (33)
19:31:58.899337 IP 192.168.1.7.58748 > 192.168.1.1.53: 51051+ A? localunixsocket. (33)
19:32:01.970691 IP 192.168.1.7.58748 > 192.168.1.1.53: 51051+ A? localunixsocket. (33)
19:32:11.058583 IP 192.168.1.7.58748 > 192.168.1.1.53: 51051+ A? localunixsocket. (33)
19:32:20.170356 IP 192.168.1.7.3591 > 192.168.1.1.53: 40509+ A? github.com. (28)
19:32:21.041157 IP 192.168.1.1.53 > 192.168.1.7.3591: 40509 1/0/0 A 192.30.253.113 (44)
19:32:27.904471 IP 192.168.1.7.64707 > 192.168.1.1.53: 64281+ A? localunixsocket. (33)
19:32:28.979227 IP 192.168.1.7.64707 > 192.168.1.1.53: 64281+ A? localunixsocket. (33)
19:32:29.134327 IP 192.168.1.7.55404 > 192.168.1.1.53: 44054+ PTR? lb._dns-sd._udp.0.1.168.192.in-addr.arpa. (58)
19:32:29.504521 IP 192.168.1.7.37326 > 192.168.1.1.53: 64843+ A? api.github.com. (32)
19:32:30.376977 IP 192.168.1.1.53 > 192.168.1.7.37326: 64843 1/0/0 A 192.30.253.117 (48)
19:32:30.571070 IP 192.168.1.7.52044 > 192.168.1.1.53: 49789+ A? secure.screenhero.com. (39)
19:32:31.076530 IP 192.168.1.1.53 > 192.168.1.7.52044: 49789 4/0/0 A 52.206.176.99, A 52.1.137.121, A 52.205.68.133, A 52.20.80.34 (103)
19:32:32.060273 IP 192.168.1.7.64707 > 192.168.1.1.53: 64281+ A? localunixsocket. (33)
19:32:41.135066 IP 192.168.1.7.64707 > 192.168.1.1.53: 64281+ A? localunixsocket. (33)
19:32:54.772734 IP 192.168.1.7.58811 > 192.168.1.1.53: 4811+ A? www.googleapis.com. (36)
19:32:55.058864 IP 192.168.1.1.53 > 192.168.1.7.58811: 4811 5/0/0 CNAME googleapis.l.google.com., A 216.58.197.42, A 216.58.197.74, A 172.217.26.202, A 216.58.220.42 (134)
19:32:55.733107 IP 192.168.1.7.50112 > 192.168.1.1.53: 56368+ A? d3hb26arjl8wb7.cloudfront.net. (47)
19:32:56.640210 IP 192.168.1.7.40637 > 192.168.1.1.53: 43092+ A? clients4.google.com. (37)
19:32:56.764532 IP 192.168.1.7.50112 > 192.168.1.1.53: 56368+ A? d3hb26arjl8wb7.cloudfront.net. (47)
19:32:57.101995 IP 192.168.1.1.53 > 192.168.1.7.50112: 56368 8/0/0 A 54.230.191.244, A 54.230.191.16, A 54.230.191.112, A 54.230.191.49, A 54.230.191.106, A 54.230.191.62, A 54.230.191.33, A 54.230.191.152 (175)
19:32:57.102024 IP 192.168.1.1.53 > 192.168.1.7.40637: 43092 2/0/0 CNAME clients.l.google.com., A 216.58.196.110 (77)
19:32:57.415713 IP 192.168.1.7.1644 > 192.168.1.1.53: 16183+ A? clients4.google.com. (37)
19:32:57.968226 IP 192.168.1.7.52782 > 192.168.1.1.53: 58706+ A? localunixsocket. (33)
19:32:58.008570 IP 192.168.1.1.53 > 192.168.1.7.1644: 16183 2/0/0 CNAME clients.l.google.com., A 172.217.26.206 (77)
19:32:58.167749 IP 192.168.1.7.40378 > 192.168.1.1.53: 49901+ A? clients4.google.com. (37)
19:32:58.409353 IP 192.168.1.1.53 > 192.168.1.7.40378: 49901 2/0/0 CNAME clients.l.google.com., A 216.58.220.46 (77)
19:32:59.044957 IP 192.168.1.7.52782 > 192.168.1.1.53: 58706+ A? localunixsocket. (33)
19:33:02.110713 IP 192.168.1.7.52782 > 192.168.1.1.53: 58706+ A? localunixsocket. (33)
19:33:07.710359 IP 192.168.1.7.41048 > 192.168.1.1.53: 30609+ A? docs.google.com. (33)
19:33:07.711240 IP 192.168.1.7.14928 > 192.168.1.1.53: 12210+ A? ssl.gstatic.com. (33)
19:33:08.299241 IP 192.168.1.1.53 > 192.168.1.7.41048: 30609 1/0/0 A 216.58.197.46 (49)
19:33:08.299976 IP 192.168.1.1.53 > 192.168.1.7.14928: 12210 1/0/0 A 172.217.26.195 (49)
^C
33 packets captured
905 packets received by filter
0 packets dropped by kernel
```

**Comment by gbougeard** [comment] 2016-09-19 08:29
I have a lot of `Read timed out` errors between docker-compose components (I did not get them in the previous stable version). My MacBookPro fan is also at his maximum when running docker-compose.
I tried the `localunixsocket` trick but did not solve it.

To reproduce, I started spinnaker through docker-compose : https://github.com/spinnaker/spinnaker/tree/master/experimental/docker-compose

**Comment by gbougeard** [comment] 2016-09-20 08:17
Is it possible to rollback to the last stable version? I can't work/use docker-compose right now.

**Comment by sdball** [comment] 2016-09-20 15:20
@gbougeard You can still download 1.12.0 at https://download.docker.com/mac/stable/1.12.0.11213/Docker.dmg. I tracked that down because I similarly needed to downgrade due to #668

**Comment by gbougeard** [comment] 2016-09-20 15:25
thx. I downgraded and now it's better.

**Comment by kishaningithub** [comment] 2016-09-25 06:16
This issue seems to be fixed for me.. This is what i id.

1. Connect to a "really fast" internet. 
2. Do all stuffs with docker compose. (Worked as it did in the previous version).
3. Connect to your regular internet. (No sluggishness now)

Those who face the same issue, Kindly try this out and report in comments.
If this works for everyone i think we can close out this issue.

**Comment by ijc25** [comment] 2016-11-18 15:42
I think this is the same underlying issue as is tracked in #93 so closing as a dup of that, please subscribe there for further updates.

Note also https://github.com/docker/for-mac/issues/93#issuecomment-261558230.

**Closed by ijc25** 2016-11-18 15:42 UTC
Labels: area/compose, status/1-acknowledged, version/1.12.1
