### ISSUE TITLE
Can't build images because docker crashed

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4793] opened 2020-07-22 00:46 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20200722004247

### Expected behavior
`docker build` works

### Actual behavior
```
failed to dial gRPC: unable to upgrade to h2c, received 502
```

### Information
  - macOS Version: 10.15.5

### Diagnostic logs
Doesn't exist in current Docker for Mac

### Steps to reproduce the behavior
Not sure, Docker crashed while I was building and using it

**Comment by stephen-turner** [comment] 2020-07-23 11:13
This seems to be a dupe of moby/moby#37959, so I'll close this copy. Users on that ticket have reported that turning off experimental features fixes it.

**Closed by stephen-turner** 2020-07-23 11:13 UTC
Labels: version/2.3.3.0
