### ISSUE TITLE
Docker suddenly broken, cannot connect to deamon after update 21

### ISSUE THREAD

**Issue by npalm** [docker/for-mac#83] opened 2016-08-02 21:49 UTC
### Information

Diagnostic ID: AE006447-CE28-4DC7-990A-213F505561FC
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment] 2016-09-09 09:20
I see some of these:
```
Mirage-block error: Unknown write: End_of_file at file /Users/310230212/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 offset 20692992000 with buffer of length 1536
```
although the qcow2 seems currently intact. The write error would cause the block device to freeze and any process (like the `docker` engine) which tries to write to it to block in disk sleep until the VM is restarted.

This looks like #71 -- there's a known issue which can cause (rarely) more than one hypervisor process to access the disk at once, which can lead to various forms of corruption. The issue can be triggered over an update.

The issue is fixed in recent betas, could you install beta 25 and open a fresh issue with fresh diagnostics if that fails?

**Closed by djs55** 2016-09-09 09:20 UTC
Labels: area/startup, osx/10.11.x, status/1-acknowledged, status/3-fixed, status/4-fix-released-beta, version/1.12.0
