### ISSUE TITLE
Docker Crashes on MacOSX Sierra

### ISSUE THREAD

**Issue by seneca** [docker/for-mac#130] opened 2016-08-04 14:14 UTC
### Information

Diagnostic ID: 64653D37-5222-4FCF-971A-B0AD4A2342A8
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by tgautier** [comment] 2016-08-05 14:17
Duplicate of #64

**Comment by dave-tucker** [comment] 2016-08-09 01:31
Closing as confirmed as a dupe of #64

**Closed by dave-tucker** 2016-08-09 01:31 UTC

**Comment by djs55** [comment] 2016-09-15 16:29
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
