### ISSUE TITLE
not able to pull an image from docker repository

### ISSUE THREAD

**Issue by srinivasvadla** [docker/for-mac#3597] opened 2019-03-27 07:34 UTC
Hello i am unable to pull an image from the docker repository saying that 
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such 
 please help out me .

Thank you.

**Comment by albertoal** [comment] 2019-03-28 03:54
Seems like a duplicate of https://github.com/docker/for-mac/issues/1317 

Could be a transient DNS problem - try restarting Docker and if that doesn't work check out the other approaches people are trying on that issue.

**Comment by srinivasvadla** [comment] 2019-03-28 05:31
Thank you , i resolved by adding these  below 

$ sudo mkdir -p /etc/systemd/system/docker.service.d
$ sudo vi /etc/systemd/system/docker.service.d/http_proxy.conf
[Service]
Environment="HTTP_PROXY=<your proxy here>/"
Environment="HTTPS_PROXY=<your proxy here>/"
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker

And make sure it is not solving by connecting with LAN .mostly try with  by using WIFI .
Thank you.

**Comment by ulrich** [comment] 2019-03-28 13:23
Thank you @srinivasvadla

**Closed by ulrich** 2019-03-28 13:23 UTC
