### ISSUE TITLE
Lack of code-signing on Autoupdate.app causes upgrade annoyance with Google Santa

### ISSUE THREAD

**Issue by noahwilliamsson** [docker/for-mac#1290] opened 2017-02-11 21:54 UTC
### Expected behavior

It should be possible to upgrade Docker for Mac on a system where [Google Santa](https://github.com/google/santa) is installed and running in LOCKDOWN mode, with the Docker app's code-signing certificate previously whitelisted in Santa's database (e.g. `sudo santactl rule --whitelist --certificate --path /Application/Docker.app`).

(Google Santa is a binary whitelisting/blacklisting system for macOS)

### Actual behavior

After accepting the upgrade from 1.13.0 to 1.13.1 (via the "New version available" popup) and the download has finished, Google Santa blocks the execution of the autoupdate application (screenshot [1]).  This causes the "Updating Docker" window to hang indefinitely (screenshot [2]).

![1-santa-block](https://cloud.githubusercontent.com/assets/91926/22857748/3a7945aa-f0ab-11e6-90d8-2022cadf6f31.png)

![2-docker-update-hang](https://cloud.githubusercontent.com/assets/91926/22857721/d0ba8d4a-f0aa-11e6-8348-a9b2edec9260.png)

### Information

```
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/1CFD6C8A-5277-496C-BFD5-CF1B31B270BC/20170211-223628.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
$ santactl fileinfo ~/Library/Caches/com.docker.docker/org.sparkle-project.Sparkle/Autoupdate.app
Path                 : /Users/REMOVED/Library/Caches/com.docker.docker/org.sparkle-project.Sparkle/Autoupdate.app/Contents/MacOS/Autoupdate
SHA-256              : f47f4475b520e4a068d922107c95c840bb1c7106d4d753febc2ffa77226c959c
SHA-1                : 1d0d92c952f3b013025fa095d00726ec1a338507
Bundle Version       : 1.15.1
Bundle Version Str   : 1.15.1
Type                 : Executable (x86-64)
Code-signed          : No
Rule                 : Blacklisted (Unknown)
```

### Steps to reproduce the behavior

  1. Install an older version of Docker for Mac like 1.13.0 (sorry, not sure where to find them)
  2. Install a [recent release](https://github.com/google/santa/releases) of Google Santa
  3. Switch Santa into [LOCKDOWN mode](https://github.com/google/santa/wiki/Configuration#clientmode) by issuing

          sudo defaults write /var/db/santa/config.plist ClientMode -int 2  # To switch back to MONITOR mode, use '-int 1'

  4. Whitelist the code-signing certificate used in Docker.app

          $ sudo santactl rule --whitelist --certificate --path /Applications/Docker.app
          Added rule for SHA-256: e38f2b2ad07738bb94ec7d59ffb6043193cf91624a49b346b95ea502a074dd0e.

          $ santactl fileinfo /Applications/Docker.app
          Path                 : /Applications/Docker.app/Contents/MacOS/Docker
          SHA-256              : 1c27e144c1274d6c0cbbe27180d93ca1f56b2c705c414df32f663c47c9e5f641
          SHA-1                : 57943b8031de8a03aa34ccf0ec6c71b3c96f9e94
          Bundle Name          : Docker
          Bundle Version       : 15072
          Bundle Version Str   : 1.13.0
          Type                 : Executable (x86-64)
          Code-signed          : Yes
          Rule                 : Whitelisted (Certificate)
          Signing Chain:
               1. SHA-256             : e38f2b2ad07738bb94ec7d59ffb6043193cf91624a49b346b95ea502a074dd0e
                  SHA-1               : 76f37f2abd8aacb2918299992a4f2edd5aaf556e
                  Common Name         : Developer ID Application: Docker Inc (9BNSXJN65R)
                  Organization        : Docker Inc
                  Organizational Unit : 9BNSXJN65R
                  Valid From          : 2014/05/07 16:21:10 +0200
                  Valid Until         : 2019/05/08 16:21:10 +0200
          
               2. SHA-256             : 7afc9d01a62f03a2de9637936d4afe68090d2de18d03f29c88cfb0b1ba63587f
                  SHA-1               : 3b166c3b7dc4b751c9fe2afab9135641e388e186
                  Common Name         : Developer ID Certification Authority
                  Organization        : Apple Inc.
                  Organizational Unit : Apple Certification Authority
                  Valid From          : 2012/02/01 23:12:15 +0100
                  Valid Until         : 2027/02/01 23:12:15 +0100
          
               3. SHA-256             : b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024
                  SHA-1               : 611e5b662c593a08ff58d14ae22452d198df6c60
                  Common Name         : Apple Root CA
                  Organization        : Apple Inc.
                  Organizational Unit : Apple Certification Authority
                  Valid From          : 2006/04/25 23:40:36 +0200
                  Valid Until         : 2035/02/09 22:40:36 +0100

  5. Go to the Docker menu and click "Check for updates...", accept the update and watch Santa block the autoupdater execution
  6. Annoyance 1/2: either whitelist the autoupdate application or turn off Santa's LOCKDOWN mode.

           $ sudo santactl rule --whitelist --path ~/Library/Caches/com.docker.docker/org.sparkle-project.Sparkle/Autoupdate.app
          Added rule for SHA-256: f47f4475b520e4a068d922107c95c840bb1c7106d4d753febc2ffa77226c959c.
           # Alternative: Disable Santa's LOCKDOWN mode
           $ sudo defaults delete /var/db/santa/config.plist ClientMode

  7. Annoyance 2/2: Forcefully kill Docker, restart it and then check for updates again

**Comment by dsheets** [comment] 2017-02-12 14:57
Thanks for your detailed report. We are tracking this issue and hope to ship a signed auto-updater soon. I will bump up our priority for fixing this. I am going to close this issue as a duplicate of #1202 so if you'd like to track its progress, please subscribe to that ticket.

Thanks for using Docker for Mac!

**Closed by dsheets** 2017-02-12 14:57 UTC
Labels: area/gui, kind/bug, osx/10.11.x, status/1-acknowledged, version/1.13.0
