### ISSUE TITLE
Docker pull from private, self signed registry fails

### ISSUE THREAD

**Issue by tengelmeier** [docker/for-mac#5618] opened 2021-04-23 07:40 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 11.2.3 + VPN (Cisco AnyConnect)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. Fresh install of Docker desktop
  2. try to pull from a private registry with a self signed certificate or build with a reference to an image in local registry

--> Error as expected when doing docker pull

  3. Import the registry certificate in the keychain as in the Mac readme, validate the certificate is there, set to "always trust" and contains the registry host name
  
Expected: Docker pull working
--> Still an error on docker pull : 'error response from daemon: Get https://private_registry/v2/: x509: certificate signed by unknown authority'

4. add` "insecure-registries" : ["private_registry:5000"]` to the docker env settings

Expected: Docker pull working
real: 'error response from daemon: Get https://private_registry/v2/: x509: certificate signed by unknown authority'

5. toggle `buildkit: true` 
Expected: Docker pull working
real: 'error response from daemon: Get https://private_registry/v2/: x509: certificate signed by unknown authority'

**Comment by stephen-turner** [comment] 2021-04-23 08:02
Thanks for the report. This seems to be a dupe of #5617 so I'll close this copy. See my note on the other ticket for a development build to try.

**Closed by stephen-turner** 2021-04-23 08:02 UTC
Labels: version/11.2.3 + VPN
