### ISSUE TITLE
Minimum width too large on MacOS 

### ISSUE THREAD

**Issue by tonytx05** [docker/for-mac#5851] opened 2021-07-17 02:08 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Entire desktop window is visible on-screen. 

### Actual behavior
Window width cannot be reduced enough to make the entire window visible

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2

### Steps to reproduce the behavior
- Change display scaling from default to "looks like 1280x800".
- Move dock from bottom of screen to the left side.
- Maximize the Docker Desktop window.
- Right side of window is not visible.

<img width="780" alt="Screen Shot 2021-07-16 at 21 06 48" src="https://user-images.githubusercontent.com/16763539/126022163-83ed5be7-2b05-4d5f-8e49-5aa2ed903bbd.png">

<img width="1280" alt="Screen Shot 2021-07-16 at 21 03 57" src="https://user-images.githubusercontent.com/16763539/126022167-95c4e60d-ae67-470a-b549-fd25d5230d79.png">

**Comment by StefanScherer** [comment] 2021-07-19 05:57
Thanks @tonytx05 for the report and details how to reproduce. I'll close this ticket as it's a duplicate of #5847 where we track the issue and post further updates.

**Closed by StefanScherer** 2021-07-19 05:57 UTC
