### ISSUE TITLE
update of xcode (12.2) on bigsur killed latest edge version

### ISSUE THREAD

**Issue by xinity** [docker/for-mac#5067] opened 2020-11-15 10:49 UTC
I've updated xcode to 12.2 has suggested by the system upgrade mechanism (especially to be able to do a brew upgrade on bigsur).
This then everytime I boot my mac, I have this error: 
![image](https://user-images.githubusercontent.com/1799009/99183036-5786c000-2739-11eb-8fcf-3253158387cf.png)

and after setting factory reset to default:
<img width="598" alt="Screenshot 2020-11-15 at 11 38 02" src="https://user-images.githubusercontent.com/1799009/99182941-98320980-2738-11eb-91a3-82cfce03d9c0.png">

The reset to factory defaults never finishes (started 12hours ago and still on going).

  - [X] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
reset to factory default succeeded

### Actual behavior
infinite retry of reset to factory default

### Information
this behavior happened after updating xcode to 12.2 on bigsur (macos 11) before this update, Docker desktop was working perfectly on bigsur.
  - macOS Version: bigsur 11.0.1 (20B29)

Docker for Mac: latest edge release

Diagnostics ID:     DDD8B6F1-E704-4DC5-851A-CB2F26633A2E/20201115143912 (uploaded)

### Steps to reproduce the behavior
- Update to bigsur
- update xcode to 12.2
- restart
...

**note**: This behavior also breaks the shutdown / restart mechanism, the only way is to force shutdown manually :'(

**Comment by StefanScherer** [comment] 2020-11-15 17:08
Thanks @xinity for uploading the diagnostics.
It looks very similar to the crash when VirtualBox also is installed, reported in #4997
The current Stable release 2.5.0.1 has a fix for Big Sur and it's going into next Edge release as well.

**Comment by stephen-turner** [comment] 2020-11-16 10:32
Yes, it's definitely a dupe of #4997, I'll close this copy.

**Closed by stephen-turner** 2020-11-16 10:32 UTC
Labels: version/2.4.2.0
