### ISSUE TITLE
Docker vm exit on MacOS with reason VMX

### ISSUE THREAD

**Issue by mansab** [docker/for-mac#1345] opened 2017-02-27 09:47 UTC
### Expected behavior
Docker for MacOS should keep running and the hypervisor subprocess should not shutdown while executing long running processes.

### Actual behavior
Docker daemon dies and hypervisor subprocess shuts down with the following messages in the console.log:

```
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: vm exit[0]
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    reason          VMX
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: Interface will have uuid 3d3c66d1-513a-45da-b242-403ba33ab6ff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    rip             0xffffffff81841afd
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: Connection established with MAC=c0:ff:ee:c0:ff:ee and MTU 1500
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    inst_length     5
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: virtio-9p: initialising path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/s40,tag=db
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    status          0
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: virtio-9p: initialising path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/s51,tag=port
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    exit_reason     2
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: linkname /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    qualification   0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: COM1 connected to /dev/ttys000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    inst_type               0
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: COM1 linked to /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]:    inst_error              0
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_PIN_BASED_CTLS:           0x000000000000003f
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_PRI_PROC_BASED_CTLS:      0x00000000b5186dfa
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_SEC_PROC_BASED_CTLS:      0x00000000000000aa
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_ENTRY_CTLS:               0x00000000000093ff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_EXCEPTION_BITMAP:         0x0000000000040000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_CR0_MASK:                 0x00000000e0000031
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_CR0_SHADOW:               0x0000000080050033
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_CR4_MASK:                 0x0000000000002000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_CR4_SHADOW:               0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CS_SELECTOR:        0x0000000000000010
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CS_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CS_ACCESS_RIGHTS:   0x000000000000a09b
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CS_BASE:            0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_DS_SELECTOR:        0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_DS_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_DS_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_DS_BASE:            0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_ES_SELECTOR:        0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_ES_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_ES_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_ES_BASE:            0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_FS_SELECTOR:        0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_FS_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_FS_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_FS_BASE:            0x00007f0cdebd2740
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GS_SELECTOR:        0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GS_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GS_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GS_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GS_BASE:            0xffff88033fc00000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_SS_SELECTOR:        0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_SS_LIMIT:           0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_SS_ACCESS_RIGHTS:   0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_SS_BASE:            0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_LDTR_SELECTOR:      0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_LDTR_LIMIT:         0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_LDTR_ACCESS_RIGHTS: 0x000000000001c000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_LDTR_BASE:          0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_TR_SELECTOR:        0x0000000000000040
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_TR_LIMIT:           0x0000000000002087
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_TR_ACCESS_RIGHTS:   0x000000000000008b
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_TR_BASE:            0xffff88033fc16080
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GDTR_LIMIT:         0x000000000000007f
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_GDTR_BASE:          0xffff88033fc09000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_IDTR_LIMIT:         0x00000000ffffffff
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_IDTR_BASE:          0x0000000000000000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CR0:                0x0000000080050033
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CR3:                0x000000015c4f3000
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_CR4:                0x00000000000426b0
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: VMCS_GUEST_IA32_EFER:          0x0000000000000d01
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: rip: 0xffffffff81841afd rfl: 0x0000000000010083 cr2: 0xffff88033fc04ff8
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: rax: 0x0000000000000000 rbx: 0xffff88033fc00028 rcx: 0x000000000000000b rdx: 0xffff88033fc00028
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: rsi: 0x000000000000000e rdi: 0xffffc900076570a8 rbp: 0x00007ffe53ff0ba0 rsp: 0xffffc90007656fa8
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: r8:  0x0000000000030001 r9:  0x00000000000028d4 r10: 0x0000000002baf380 r11: 0x000035f59a07b939
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: r12: 0xffffc900076570a8 r13: 0xffffc900076570a8 r14: 0x000000000000000b r15: 0x0000000000030001
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: Hypervisor subprocess has shutdown
Feb 27 10:22:15 MacBook-Pro-2 Docker[92527]: Fatal unexpected exception: Socket.Closed
Feb 27 10:22:15 MacBook-Pro-2 Docker[92528]: Socket.Stream: caught socket is not connected
Feb 27 10:22:15 --- last message repeated 1 time ---
Feb 27 10:22:15 MacBook-Pro-2 Docker[401]: Reap com.docker.osxfs (pid 92527): exit status 1
Feb 27 10:22:15 MacBook-Pro-2 Docker[92529]: TRIM is enabled but auto-compaction disabled: compacting now
Feb 27 10:22:15 MacBook-Pro-2 com.apple.xpc.launchd[1] (com.apple.ReportCrash[94226]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
Feb 27 10:22:15 MacBook-Pro-2 Docker[406]: VM shutdown at 2017-02-27 10:22:15 +0100 CET
Feb 27 10:22:16 MacBook-Pro-2 Docker[401]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 92529)
Feb 27 10:22:16 MacBook-Pro-2 Docker[401]: Signal terminated to com.docker.driver.amd64-linux (pid 92529)
Feb 27 10:22:16 MacBook-Pro-2 Docker[92529]: sending SIGTERM to com.docker.hyperkit pid 92534
Feb 27 10:22:16 MacBook-Pro-2 Docker[406]: VM shutdown at 2017-02-27 10:22:16 +0100 CET
Feb 27 10:22:17 MacBook-Pro-2 Docker[92528]: Socket.Stream: caught connection refused
Feb 27 10:22:17 MacBook-Pro-2 com.apple.xpc.launchd[1] (com.apple.nowplayingtouchui): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Feb 27 10:22:17 MacBook-Pro-2 Docker[92528]: Socket.Stream: caught connection refused
Feb 27 10:22:27 --- last message repeated 9 times ---
Feb 27 10:22:27 --- last message repeated 9 times ---
Feb 27 10:22:27 MacBook-Pro-2 com.apple.xpc.launchd[1] (com.apple.nowplayingtouchui): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Feb 27 10:22:29 MacBook-Pro-2 Docker[92528]: Socket.Stream: caught connection refused
Feb 27 10:22:31 --- last message repeated 3 times ---
Feb 27 10:22:31 MacBook-Pro-2 Docker[401]: Reap com.docker.driver.amd64-linux (pid 92529): exit status 0
Feb 27 10:22:31 MacBook-Pro-2 Docker[401]: Stop 2 children with order 2: com.docker.osxfs (pid 92527), com.docker.slirp (pid 92528)
Feb 27 10:22:31 MacBook-Pro-2 Docker[401]: Signal terminated to com.docker.slirp (pid 92528)
Feb 27 10:22:31 MacBook-Pro-2 Docker[401]: Reap com.docker.slirp (pid 92528): signal: terminated
Feb 27 10:22:32 MacBook-Pro-2 Docker[401]: Starting com.docker.osxfs, com.docker.slirp, com.docker.driver.amd64-linux
Feb 27 10:22:32 MacBook-Pro-2 Docker[401]: Start com.docker.osxfs (pid 94233)
Feb 27 10:22:32 MacBook-Pro-2 Docker[401]: Start com.docker.slirp (pid 94234)
Feb 27 10:22:32 MacBook-Pro-2 Docker[401]: Start com.docker.driver.amd64-linux (pid 94235)
Feb 27 10:22:32 MacBook-Pro-2 Docker[401]: Supervisor restarted %d0
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Sending SIGKILL to com.docker.hyperkit 92534
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Acquired hypervisor lock
Feb 27 10:22:32 MacBook-Pro-2 Docker[94233]: Logging to Apple System Log
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Docker is not responding: Get http://./info: dial unix /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused: waiting 0.5s
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: Logging to Apple System Log
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: Setting handler to ignore all SIGPIPE signals
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: vpnkit version c5bdb42fbb8c6af51f9a158e491d3dae89caae85 with hostnet version   uwt version 0.0.3 hvsock version 0.11.2
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: starting port forwarding server on port_control_url:fd:4 vsock_path:/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/@connect
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: hosts file has bindings for localhost broadcasthost
Feb 27 10:22:32 MacBook-Pro-2 Docker[94234]: Add(2): DNS configuration changed to: nameserver 10.1.0.1#53
        order 0
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: OSX version = 10.12.3, default value of on-sleep = no not freeze
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: hypervisor: native
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: filesystem: osxfs
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: network: hybrid
Feb 27 10:22:32 MacBook-Pro-2 Docker[94233]: Using protocol TwoThousand msize 16384
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Hypervisor: native; BootProtocol: direct; UefiBootDisk: /Users/tw-macbookpro/UefiBoot.qcow2
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Syslog socket is /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/*00000002.00000202
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Logfile is /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/syslog
Feb 27 10:22:32 MacBook-Pro-2 Docker[94235]: Launched[94240]: /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 12288M -c 6 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=3d3c66d1-513a-45da-b242-403ba33ab6ff,path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,ahci-hd,file:///Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=0 -s 4,virtio-9p,path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac vsyscall=emulate -F /Users/tw-macbookpro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/716E6E28-BC14-435D-BA04-D548A0530642/20170227-103558.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Tried with the following MacOS-docker resource configurations:

a)
CPUs: 8
Memory: 16

b)
CPUs: 6
Memory: 12

### Steps to reproduce the behavior

1. Run a couple of docker containers, for example, 'Openshift for MacOS' and execute long running processes in these docker containers 'For example npm test, npm install, etc'.

**Comment by dsheets** [comment] 2017-02-28 15:37
This is a duplicate of #1170. Please subscribe there for updates. Thanks for your report and for using Docker for Mac!

**Closed by dsheets** 2017-02-28 15:37 UTC
Labels: status/0-triage, version/1.13.1
