### ISSUE TITLE
Fatal Error : vmstateevent invalid json

### ISSUE THREAD

**Issue by Mindgames** [docker/for-mac#193] opened 2016-08-09 12:00 UTC
### Actual behavior

Overall performing very bad on MacOS, sucking up a lot of resources and get processes locked.
....

About 1 minute after startup of Docker application it crashes or lock up.   Was using Beta build and had similar issues there so downgraded but it seems issues is still remaining so i guess it could be MacOS related, running beta 3. 

![image](https://cloud.githubusercontent.com/assets/2171273/17515449/b578777c-5e38-11e6-915a-245badfbc9e0.png)

Also seeing this in terminal 
`
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json`

### Information

Diagnostic ID: 84B44316-9632-4DE9-9864-B45B42E59733
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start Docker application
2. Run any docker command ( docker ps ) or just wait.

**Comment by dave-tucker** [comment] 2016-08-09 12:11
Closing as a dupe of #64

**Closed by dave-tucker** 2016-08-09 12:11 UTC

**Comment by djs55** [comment] 2016-09-15 16:27
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
