### ISSUE TITLE
M1 Docker Desktop RC Inter-container networking to port 80 is completely broken (something else listening?)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5476] opened 2021-03-19 04:45 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

The bottom line is that all previous releases of the M1 Docker Desktop tech preview have worked fine with [ddev](https://github.com/drud/ddev), and suddenly in this release (3.3.0 62029) all intercontainer TCP networking is broken. 

Normally I should be able to create a trivial "hello" index.html in a directory and `ddev config` and `ddev launch` and it pops a browser and there I am with the content of the index.html. But no more. Now I get 500 errors, apparently the reverse proxy trying to communicate to the web container and failing.

I've boiled this down to a simple docker-compose that I think will demonstrate the problem.

### Actual behavior

In a directory, put this docker-compose.yaml. I used ddev images just because they have the tools installed in them that I want to use, like ping and curl and wget, etc. I've tested with other images and I don't think it makes a difference.

```
version: "3.6"
services:
  web1:
    container_name: web1
    hostname: web1
    image: drud/ddev-webserver:v1.16.7
    command: bash -c "echo 'this is web1' >/var/www/html/index.html && /start.sh"
  web2:
    container_name: web2
    hostname: web2
    image: drud/ddev-webserver:v1.16.7
    command: bash -c "echo 'this is web2' >/var/www/html/index.html && /start.sh"
```

Now we'll try out some simple networking between these two webservers. It doesn't matter which direction you go; both webservers have a simple index.html in them, and the behavior turns out the same either way.

```
$ docker-compose up -d
Starting web2 ... done
Starting web1 ... done

$ docker-compose exec web1 bash
root@web1:/# ping -c1 web1
PING web1 (172.19.0.2) 56(84) bytes of data.
64 bytes from web1 (172.19.0.2): icmp_seq=1 ttl=64 time=0.132 ms

root@web1:/# ping -c1 web2
PING web2 (172.19.0.3) 56(84) bytes of data.
64 bytes from web2.tmp_default (172.19.0.3): icmp_seq=1 ttl=64 time=0.248 ms

root@web1:/# curl localhost/index.html
this is web1
root@web1:/# curl web1/index.html
this is web1

root@web1:/# curl web2/index.html
lookup web2 on 192.168.65.5:53: no such host

root@web1:/# curl -I web2/index.html
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 19 Mar 2021 04:24:59 GMT
Content-Length: 45

root@web1:/# curl 172.19.0.3/index.html
^C

$ wget web2/index.html
--2021-03-19 04:29:17--  http://web2/index.html
Resolving web2 (web2)... 172.19.0.3
Connecting to web2 (web2)|172.19.0.3|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-03-19 04:29:17 ERROR 500: Internal Server Error.
```

I can telnet to port 80 on web2 and it connects, but I can't successfully do a GET

It looks to me like I'm talking to a listener on the other end that is not my container, like something else is listening on port 80

In fact, I can go into the target containers /etc/nginx/sites-enabled/nginx-site-default.conf and add additional ports to the listen directive, like this:

```
listen 80;
listen 8000;
listen 8080;
listen 8888;
```

and then `nginx -s reload` to reread the config.

and `curl http://web2:8000/index.html` works perfectly, I get "this is web2"

So it appears to me that something else is sitting on port 80, but it's only on access from another container.

### Information

This is completely new with this release. I've never seen this in another docker desktop on any platform.
It happens every time.

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0 62029

### Steps to reproduce the behavior

Explained above.

**Comment by djs55** [comment] 2021-03-19 09:26
Thanks for the report. I can reproduce this too. It looks like a buggy `iptables` rule is redirecting the internal traffic to the external HTTP proxy:

With:
```
mkdir networking
cd networking
cat > docker-compose.yml <<EOT
services:
  one:
    image: nginx
  two:
    image: nginx
EOT
docker compose up
```
and then
```
cd networking
docker compose exec two sh
# curl http://one
lookup one on 192.168.65.5:53: no such host
```

If I look in the log:
```
tail -f ~/Library/Containers/com.docker.docker/Data/log/vm/http-proxy.log 
2021-03-19T09:22:28Z http-proxy 2021/03/19 09:22:28 [060] INFO: Got request / one GET /
2021-03-19T09:22:28Z http-proxy time="2021-03-19T09:22:28Z" level=info msg="GET http://one/"
2021-03-19T09:22:28Z http-proxy 2021/03/19 09:22:28 [061] INFO: Got request / one GET http://one/
2021-03-19T09:22:28Z http-proxy 2021/03/19 09:22:28 [061] INFO: Sending request GET http://one/
2021-03-19T09:22:28Z http-proxy 2021/03/19 09:22:28 [061] INFO: error read response one lookup one on 192.168.65.5:53: no such host:
```

Good thing you caught this, because the code is used everywhere now! It's a shame the CI missed this, I'll add a test case ...

**Comment by djs55** [comment] 2021-03-23 10:32
@rfay I think I've got a fix for this issue. If you'd like to try it a notarised M1 build is here: https://desktop-stage.docker.com/mac/stable/arm64/62146/Docker.dmg

With this build I can:
```
root@web1:/# curl web2/index.html
this is web2
root@web1:/# curl -I web2/index.html
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 23 Mar 2021 10:29:41 GMT
Content-Type: text/html
Content-Length: 13
Last-Modified: Tue, 23 Mar 2021 10:28:48 GMT
Connection: keep-alive
ETag: "6059c2e0-d"
Accept-Ranges: bytes
```
which looks healthier.

If this build looks good, the fix will be in the next RC (which should probably be sooner rather than later given this bug is a bit of a blocker)

**Comment by olivere** [comment] 2021-03-23 11:11
@djs55 I had similar issues described in this issue (dockerized nginx proxying other containers didn't work with RC1, and nginx simply couldn't resolve one container by name any more). I just downloaded the above Docker release 62146, and everything works fine again.

So, works for me again. Thank you. Hoping for RC2 soon :-)

**Comment by rfay** [comment] 2021-03-23 12:23
This build is completely unusable for me. I first got kernel crash on initial startup (no factory reset).

<img width="551" alt="Screenshot_3_23_21__5_56_AM" src="https://user-images.githubusercontent.com/112444/112145486-0d5a9300-8ba0-11eb-9840-8cb4e0a03267.png">

Then I did a factory reset and went at it again, and thought I had it, but ddev pulls a number of images at startup the first time (and because of factory reset they had to be pulled).

Now I get the null pointer kernel crash during image pulls, 

<img width="598" alt="Cursor" src="https://user-images.githubusercontent.com/112444/112145621-34b16000-8ba0-11eb-9c1f-06628468141f.png">

Despite a couple of factory resets, I haven't been able to get anything going. `ddev start` doesn't start, just fails with a kernel crash during initial image pulls.

**Comment by djs55** [comment] 2021-03-23 16:56
@rfay Thanks for giving it a go, sorry it wasn't usable. I've got another experimental build which might help with the crashing problem: https://desktop-stage.docker.com/mac/stable/arm64/62178/Docker.dmg . So far it hasn't crashed at all for me, but the crashes are a bit random. Let me know if it's better (or worse... I really hope not). If it fails could you upload a diagnostic so I can take a deeper look?

Note the internal networking in this build is slightly different to the previous M1 builds-- it's more similar to the traditional Intel builds where all the network connections come from `127.0.0.1` rather than `192.168.65.x` or `192.168.64.x`.  Watch out for this if you're using the host `/etc/exports`. Hopefully the DNS entries `*.docker.internal` are pointing to sensible places.

This build hasn't passed our CI fully yet but I think the remaining problems are Kubernetes networking related. I'll hopefully fix these in a day or two.

**Comment by djs55** [comment] 2021-03-23 16:57
@olivere thanks for letting me know the networking fix works for you!

**Comment by rfay** [comment] 2021-03-23 19:30
@djs55 thanks for 62178. A casual visit with it had everything working and no crashses, and everything working (just a little bit of exploration) Thanks!

Oh... /etc/exports changes again :) I'll rework the script for setting that up again.  It will be nice for the behavior to be the same as intel mac though.

**Comment by rfay** [comment] 2021-03-25 04:39
I could swear that 62178 is faster on a multi-arch build. Is that possible?

**Comment by olivere** [comment] 2021-03-25 06:34
I can confirm that 62146, while working for me in general, is super slow. I was running a pretty exhaustive set of unit tests against it running an Elasticsearch container, and it even timed out. Trying 62178 later today.

**Comment by rfay** [comment] 2021-03-25 12:42
I also think that 62178 is more stable doing a multi-arch build. I just did several large builds without a docker desktop crash.

**Comment by giannoug** [comment] 2021-03-25 14:35
I've just installed build 62178 (linked above) and overall it feels really snappy. A Cassandra database schema init I use for my project took about 1/8th of the time it needed with the latest release (build 62019). Most importantly some nginx amd64 containers started working again. They were all crashing with `[emerg] 66#66: io_setup() failed (38: Function not implemented)` at 62019 but they were working fine with the Tech Preview.

**Comment by evanbarter** [comment] 2021-03-25 18:11
I am experiencing worse performance for CPU-bound tasks on 62178. Yarn builds/running a test suite are between 25%-50% slower than the current RC 1 build (62029?). Can't speak for IO-bound tasks or stability.

**Comment by rinasek** [comment] 2021-03-26 13:28
I just tested a couple of builds with 62178 and it is pretty darn snappy. For the past couple of days I've had issues with networking and DBs now everything works without problem.

**Comment by rfay** [comment] 2021-03-26 21:49
Awesome results for me. Everything seems to work great for ddev, and super fast. I don't have much time on it yet, but everything looks great.  Default settings.

**Comment by stephen-turner** [comment] 2021-03-28 10:41
Fixed in RC2, so closing this ticket.

**Closed by stephen-turner** 2021-03-28 10:41 UTC
