### ISSUE TITLE
jenkins user stops working randomly - "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

### ISSUE THREAD

**Issue by vikramvi** [docker/for-mac#812] opened 2016-10-17 14:41 UTC
### Expected behavior

Jenkins user should always be able to run docker command
### Actual behavior

Refer to ticket https://github.com/docker/for-mac/issues/799
Even after doing this , jenkins user sometimes stops working randomly. Have observed this couple of times in last 3 days
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1909)
logs: /tmp/BD6F5CAF-E36D-4AA6-B8A6-4B6034AD018D/20161017-163153.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1.  Per https://github.com/docker/for-mac/issues/799 , got jenkins working. 
2. Later added new plugins to jenkins 
3. Restarted jenkins
4. Restarted mac mini
5. Ran jenkins job
### Actual Results
1. After this saw the failure 
      bash-3.2$ whoami
      jenkins
      bash-3.2$ docker ps
     Cannot connect to the Docker daemon. Is the docker daemon running on this host?
2. Again did steps as per https://github.com/docker/for-mac/issues/799
   
    and also given rwx group permissions to 
   
    /usr/local/bin/docker
    /Users/buildserver/Library/Group Containers/group.com.docker/bin/docker
    /Applications/Docker.app/Contents/Resources/bin
1. In jenkins job configuration , I have environment variable set to 
   /Applications/Docker.app/Contents/Resources/bin , to indicate docker is present here

**Comment by ijc25** [comment] 2016-11-15 16:19
As discussed in #799 this is not currently a supported configuration. It seems likely to me that (parts of) the workaround may need to be reapplied whenever `Docker.app` is restarted (including after host restart).

**Comment by samoht** [comment] 2017-01-31 15:26
Closing as a duplicate of #492 (these are not exactly the same issues, but we should address the root cause of supporting multiple users more widely). @vikramvi please subscribe to #492 if you want to be kept informed of progress related to multi-user support.

**Closed by samoht** 2017-01-31 15:26 UTC
Labels: osx/10.10.x, status/1-acknowledged, version/1.12.1
