### ISSUE TITLE
Time isn't synced between machine and docker

### ISSUE THREAD

**Issue by steffenix** [docker/for-mac#693] opened 2016-09-23 02:52 UTC
### Expected behavior

Time should be synced between machine and docker container
### Actual behavior

Time isn't synced between machine and docker container
### Information
- Docker for Mac: version: 1.12.1
- OS X: version 10.12
### Steps to reproduce the behavior
1. Start with mounting localtime as a volume `/etc/localtime:/etc/localtime:ro`
2. use date on your local machine and your docker running container
3. Time is different

**Comment by steffenix** [comment] 2016-09-23 03:14
Seems a restart fixed the issue.

**Comment by slot** [comment] 2016-09-30 13:44
My colleague @ashishbagri7 and I had the same issue, after restart of docker itself the time is synced. I suspect it has to do with hibernation of the Mac itself. I'll try to reproduce.

**Comment by mauritsl** [comment] 2016-10-18 11:43
I had the same issue, originally posted in Docker issue queue:
https://github.com/docker/docker/issues/27488

A restart also fixes the problem for me.

**Comment by mauritsl** [comment] 2016-10-20 09:12
Time is not synced to docker because timezone is not synced on Mac automatically, according to this issue: https://github.com/docker/docker/issues/27488

```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 nlams2-ntp-001. .GPSs.           1 u  57m  256  100   13.581  -27830.  16.63
```
However, checkbox "Set date and time automatically" is checked in the Date & Time settings on MacOS and synced with "Apple Americas/U.S. (time.apple.com.)" (running El Capitan).

I can reproduce this behavior consistently. Yesterday morning I restarted Docker. Time in container was identical to time on host machine, and was still identical at the end of the workday (did not hibernate my Mac in the meanwhile). Mac was hibernated in the evening and tonight. Clock is now over 13 hours behind.

```
$ date;docker run -it --rm -e TZ=Europe/Amsterdam ubuntu:16.04 date
Thu Oct 20 11:07:08 CEST 2016
Wed Oct 19 21:31:01 CEST 2016
```

**Comment by jaggerwang** [comment] 2016-10-21 09:23
meet the same problem, both mac os and docker is the newest.

**Comment by justincormack** [comment] 2016-10-27 08:54
@mauritsl there is no `*` on your `ntpq -p` output which means it is not synced, at which point it will not sync with the VM. Your offset is quite a way off. This seems somewhat common, but we don't know why...

Should look like:
```
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*nlams2-ntp-002. .GPSs.           1 u  362   64   40  148.735   65.509 207.916
```

**Comment by ijc25** [comment] 2016-10-27 10:07
> there is no * on your ntpq -p output which means it is not synced

The "If your system does not have access to an NTP server" paragraph near the end of https://docs.docker.com/docker-for-mac/troubleshoot/ contains a possible workaround for this sort of thing (namely adding the local clock as a low priority NTP source).

**Comment by ijc25** [comment] 2016-11-15 17:46
Closing as a duplicate of #17

**Closed by ijc25** 2016-11-15 17:46 UTC
Labels: osx/10.12.x, status/0-triage, version/1.12.1
