### ISSUE TITLE
macOS unix socket error

### ISSUE THREAD

**Issue by monoflash** [docker/for-mac#1962] opened 2017-08-15 16:23 UTC
Service running in the docker container, service opened unix socket.
On the host machine, binding the folder, in which the unix socket is placed.
Host machine is macOS, on the host machine, unix socket is visible in folder, but there is no access to communicate with unix socket.
If run the client in the another docker container and provide it with the same socket, then the socket is available and working.
If the host machine is running on linux, there is no such problem.

Version 17.07.0-ce-rc2-mac22 (18909)
Channel: edge
d9a9cf3b45

**Comment by ebriney** [comment] 2017-08-23 12:48
Hi @monoflash :
osxfs, the component developed for filesharing doesn't yet support host<->vm unix socket sharing.
This on the roadmap but there is ETA for now.

**Comment by dsheets** [comment] 2017-08-29 15:29
https://docs.docker.com/docker-for-mac/osxfs/#file-types describes the behavior of sockets in shared file system fragments. This is a duplicate of #483 which is tracking the development of this feature. Thanks for your report and please subscribe to #483 for future updates.

**Closed by dsheets** 2017-08-29 15:29 UTC
Labels: area/mounts, kind/feature, status/0-triage, status/2-in-progress

**Comment by JulyIghor** [comment] 2020-01-22 00:09
> Hi @monoflash :
> osxfs, the component developed for filesharing doesn't yet support host<->vm unix socket sharing.
> This on the roadmap but there is ETA for now.

any news on this?

**Comment by monoflash** [comment] 2020-01-22 09:05
Why a question to me?
I’m not a docker developer, and moreover, for the macOS, docker it has been working extremely badly for half a year now...
But the problem with the unix socket remained the same, new problems were added.
