### ISSUE TITLE
Docker for Mac 3.4.0 creates dir instead of file in nested bind mount, fails to spawn container in subsequent runs

### ISSUE THREAD

**Issue by fnkr** [docker/for-mac#5761] opened 2021-06-16 06:13 UTC
When mounting a file within a mounted directory, Docker for Mac 3.4.0 creates a directory (instead of a file) within the mounted directory. Subsequent `docker run` commands using the same volumes will fail.

Example:

```
touch /tmp/file
docker run --rm -it --volume=/tmp/dir:/dir --volume=/tmp/file:/dir/file alpine echo ok
docker run --rm -it --volume=/tmp/dir:/dir --volume=/tmp/file:/dir/file alpine echo ok
```

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Using Docker for Mac 3.3.3 after running the commands from above:

```
/tmp/dir      <- directory
/tmp/dir/file <- empty file
```

### Actual behavior

Using Docker for Mac 3.4.0 after running the commands from above:

```
/tmp/dir      <- directory
/tmp/dir/file <- directory
```

### Information

  - macOS Version: 11.4 (Big Sur)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.4.0

### Steps to reproduce the behavior

Create `/tmp/file` and run the `docker run` command twice. After the first run, there will be a directory at `/tmp/dir/file`, which prevents further `docker run` commands with the same bind mounts from succeeding.

```
➜ touch /tmp/file

➜ find /tmp/dir
find: /tmp/dir: No such file or directory

➜ docker run --rm -it --volume=/tmp/dir:/dir --volume=/tmp/file:/dir/file alpine echo ok
ok

➜ find /tmp/dir -type d
/tmp/dir
/tmp/dir/file

➜ docker run --rm -it --volume=/tmp/dir:/dir --volume=/tmp/file:/dir/file alpine echo ok
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/private/tmp/file" to rootfs at "/dir/file" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

**Comment by StefanScherer** [comment] 2021-06-17 08:53
Thanks @fnkr for the report. We're investigating.

**Comment by StefanScherer** [comment] 2021-06-17 14:09
I'll close this as it's a dupe of #5748 and we have a fix for both.

**Closed by StefanScherer** 2021-06-17 14:09 UTC
Labels: version/11.4, version/3.4.0
