### ISSUE TITLE
recurrent crash on m1 mac 

### ISSUE THREAD

**Issue by bayeslearner** [docker/for-mac#5331] opened 2021-02-11 06:45 UTC
It worked for a few days, but it started to crash after a machine wakeup from sleep. 
Crash error is 
1970-01-01T00:00:12Z dockerd time="1970-01-01T00:00:12.594683089Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."

  - [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
1970-01-01T00:00:12Z dockerd time="1970-01-01T00:00:12.594683089Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment] 2021-02-12 10:46
@bayeslearner could you update to the latest tech preview build on https://docs.docker.com/docker-for-mac/apple-m1/ and see if the problem still reproduces? If it does, could you click on the Whale menu then "Troubleshoot" then "Get support", wait for the diagnostics to be generated, then "Uplopad to get a Diagnostic ID" and then quote the ID here? The logs will help us understand the problem.

**Comment by jtneal** [comment] 2021-02-16 17:55
I get this error as well. Every morning after waking up my mac the error is there.
I've never used swarm.
It started maybe a week or so ago after my first reboot in a few weeks.
I'm on 3.1.0 (51484).

![image](https://user-images.githubusercontent.com/5340961/108101917-e74c4b00-7055-11eb-86c6-ef8737a64170.png)

**Comment by mark-night** [comment] 2021-02-17 07:33
Same here, not on M1 but an Intel mac. 
When it happens, if try to launch Docker Desktop again, for most of the time, it takes a long time and then raise a fatal error `The operation couldn’t be completed. (Docker.VmnetdError error 1.)`, then if you kill com.docker.vmnetd and restart Docker, sometime it works sometime it doesn't. The safer way is always to reboot the machine......

macOS (all 11.x versions and the last version in 10.15)
Docker Desktop version: 3.1.0(51484) (and all recent versions since the last macOS 10.15 version was released)

**Comment by rfay** [comment] 2021-02-25 15:18
I have this, M1. It happens when doing a docker build and absolutely nothing else. M1. Diagnostics 165EF212-DB99-4FE1-90A4-E516A309B23F/20210225151532

**Comment by awilderink** [comment] 2021-03-02 08:10
Same problem here

**Comment by stephen-turner** [comment] 2021-05-07 19:02
I think this is obsolete, I'm going to close it. If there are still issues, please open a new ticket with diagnostics.

**Closed by stephen-turner** 2021-05-07 19:02 UTC
Labels: area/m1, version/3.1.0, version/3.1.0(51484)
