### ISSUE TITLE
Failed installation on Mac

### ISSUE THREAD

**Issue by dapi** [docker/for-mac#283] opened 2016-08-15 11:37 UTC
### Information

Diagnostic ID: 1C9989F6-214D-42B0-AD81-26FDE6F83267
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/danil/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/1C9989F6-214D-42B0-AD81-26FDE6F83267/20160815-143412/qemu-img-check.stdout 2> /tmp/1C9989F6-214D-42B0-AD81-26FDE6F83267/20160815-143412/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/danil/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/danil/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/danil/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/danil/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/danil/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by jagtesh** [comment] 2016-08-15 15:10
@dapi Can you please add steps to reproduce this, including the expected behaviour?

**Comment by AndreyAntipov** [comment] 2016-08-15 18:47
@jagtesh Hi, i also have absolutely similar problem on macOS 10.12. beta 4 and 5 (fresh install).
Also reported similiar issue a few days ago https://github.com/docker/for-mac/issues/265

As workaround installed a Docker Toolbox.


Brew packages
```shell
➜  ~ brew list
autoconf	automake	fish		gdbm		gettext		libtool		makedepend	pcre		pcre2		pkg-config	watch		xz
➜  ~ 
```

**Comment by AndreyAntipov** [comment] 2016-08-15 18:49
Also, very strange that 

~/Library/Containers/com.docker.docker/Data absolutely empty.

**Comment by dsheets** [comment] 2016-08-17 09:43
This is likely due to ongoing issues with golang and macOS Sierra Beta. This is a duplicate of #64.

**Closed by dsheets** 2016-08-17 09:43 UTC

**Comment by djs55** [comment] 2016-09-15 16:20
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
