### ISSUE TITLE
Changing CPU Count to 10 on M1 Max breaks docker for desktop

### ISSUE THREAD

**Issue by Elycin** [docker/for-mac#6090] opened 2021-12-12 22:00 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A (I am unable to provide as docker desktop gets stuck for over 5 minutes on Diagnosing)
  - https://user-images.githubusercontent.com/33913289/145731176-11387854-eb86-4405-84c0-8df165f72b27.png

### Expected behavior
Docker works.

### Actual behavior
Docker for desktop enters a perpetual boot loop that breaks docker.

### Information
On the latest MacOS (12.0.1) for a M1 Max (aarch64) using Docker Desktop (4.3.1), when changing the CPU count to use 10 cores (8 high performance and 2 power efficiency cores), docker enters a perpetual boot loop where the engine rapidly attempts to restart itself, to only fail. The only way to get docker to continue working is to factory reset Docker Desktop.

### Steps to reproduce the behavior
1. No Dockerfile is required to reproduce.
2. Open docker desktop, go to preferences, click the resources tab
3. Change the processor core count to 10 on a MacOS Device with Apple Silicon.
4. Apply

### Steps to temporarily fix docker
1. Open the troubleshooting panel.
2. Factory reset docker desktop.

### Video:
I've managed to successfully reproduce the bug and record it: https://streamable.com/4cv64t

I hope this helps, if there's any more information I can provide please feel free to ask.

**Comment by Elycin** [comment] 2021-12-12 22:12
8 cores works fine.

**Comment by StefanScherer** [comment] 2021-12-13 08:11
Thanks for the report. Yes, the maximum is 8 cores on the M1. I'm closing this ticket as it is a duplicate of #6063

**Closed by StefanScherer** 2021-12-13 08:11 UTC
Labels: area/m1

**Comment by Elycin** [comment] 2021-12-13 08:13
Hi @StefanScherer,

Thanks for the information. I'm a little confused as the information provided by the operating system, and via nproc reports that there is indeed 10 cores in total. I just wanted to confirm that what you are saying is a limitation imposed by docker? 

Thanks,
Ely
