### ISSUE TITLE
Docker for Mac fails to update

### ISSUE THREAD

**Issue by deitch** [docker/for-mac#5723] opened 2021-05-27 11:13 UTC
- [ X ] I have tried with the latest version of Docker Desktop
  - [ X ] I have tried disabling enabled experimental features
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID:     0D8F1E74-D514-483A-BDDB-4026568EB889/20210527111109 (uploaded)

### Expected behavior

Upgrades work

### Actual behavior

Upgrades don't. 

D4M has the "upgrade ready icon" in the menu bar, and I can select "Update and restart", but it keeps coming back to the same place, same version, same "ready to update".

I have tried it at least 5 or 6 times, over several hours if not days, lost count.

### Information

  - macOS Version: 11.3
  - Intel chip or Apple chip: Intel (late 2016 MacBookPro 13")
  - Docker Desktop Version: 3.3.1 (63152)

**Comment by MasterOdin** [comment] 2021-05-28 12:56
Having the same issue, it's really quite annoying. Has persisted across a number of docker desktop restarts as well as machine restarts.

macOS version: 11.3.1
Intel chip
Docker Desktop Version: 3.3.1
Diagnostics ID: 082a4be8-2358-4c0d-ae4a-6589b73b7470/20210528121547

**Comment by prodrammer** [comment] 2021-05-29 21:49
I had this same issue upgrading from 3.3.1 to 3.3.3. After going through the update process, the "about" menu showed the same version: 3.3.1. I found that if I manually restarted docker by closing it from the menu bar, then opening it again from the applications folder, that the version number was updated as expected.

**Comment by carellen** [comment] 2021-05-30 05:30
Same problem on macOS 10.14.6...

**Comment by deitch** [comment] 2021-05-30 12:47
Hey you're right @prodrammer . Thanks!

question is, what happens with the next update. I will leave the issue open until that happens.

**Comment by StefanScherer** [comment] 2021-06-04 19:00
Thanks for the diagnostics id. We're investigating the issue.

**Comment by Randgalt** [comment] 2021-06-06 08:17
Me too

**Comment by flowl** [comment] 2021-06-15 11:43
Duplicate of https://github.com/docker/for-mac/issues/5677

**Comment by oittaa** [comment] 2021-06-16 20:47
Same issue with Docker Desktop Version: 3.3.3

The application just restarts, but the version stays the same.

**Comment by jamesarosen** [comment] 2021-06-17 22:40
Same issue. Diagnostic id `406F2DC8-9AD3-45F4-838E-6102D02ACF3C/20210617222002`.

**Comment by StefanScherer** [comment] 2021-06-24 08:20
Hi @deitch Thank you for the report.
We see more users to have this issue, but we're still investigating why this happens to some users. We couldn't reproduce it on our test machines yet. But we're looking into it. I'll close this ticket as it's a duplicate of #5677 

As a workaround stop Docker Desktop and download the latest version (3.5.0) from https://docs.docker.com/docker-for-mac/install/
We're still looking to reproduce this situation and fully understand why this happens for some users.

**Closed by StefanScherer** 2021-06-24 08:20 UTC
Labels: version/3.3.1
