### ISSUE TITLE
hogging CPU resources

### ISSUE THREAD

**Issue by iamart** [docker/for-mac#7017] opened 2023-10-06 22:10 UTC
### Description

Starting since 4.24.0(or 4.23?) after running a container `Virtual Machine Service for Docker` along with `kernel_task` consumes 100%+ of CPU.
Stopping container does not help; restarting doesn't always help most of the time; though quitting Docker and opening it back gets rid of pesky issue for sure.
This overheats my M1 and making use of the machine difficult.

### Reproduce

run containers.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.0 (122432)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/iamart/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/iamart/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/iamart/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/iamart/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/iamart/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/iamart/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/iamart/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/iamart/.docker/cli-plugins/docker-scout

Server:
 Containers: 24
  Running: 23
  Paused: 0
  Stopped: 1
 Images: 230
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 9
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: c4f42bc1-ec3d-4ac5-a172-976d37fcca64
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

2C16F3F9-22C4-4E9E-B10B-94BD69D8A3A6/20231006220742

**Comment by dgageot** [comment] 2023-11-28 10:13
@iamart Can you share which container you've started that triggers this behaviour? thanks!

**Comment by dgageot** [comment] 2024-01-31 14:09
I'm going to close this issue because we don't have a way to reproduce. Lots of CPU usage improvements went in since 4.24, I'm going to assume this is fixed.

**Closed by dgageot** 2024-01-31 14:09 UTC
Labels: status/triage, area/performance, version/4.24.0

**Comment by Fierozen** [comment] 2024-08-07 14:30
@iamart are you using Jetbrains IDE tools? I have a similar problem. Reading about issue "Docker process doesn't free up memory - macOS, Apple Silicon, Virtualization.framework #6120" #6120 and looking some of the images there, I see Intellij IDEA. But I just ran a test without any Jetbrains tools running and "Virtual Machine Service for Docker" still consumed 8.55 GB which it is not releasing though the job is done. So, maybe nothing to do with Jetbrains.

**Comment by iamart** [comment] 2024-08-07 15:06
@Fierozen no, I am not.

**Comment by elyobo** [comment] 2024-11-21 04:17
Standard high cpu docker experience on the latest homebrew version. Stopping docker entirely stops the CPU usage, but starting it up again immediately results 350%+ consumption. The _container_ cpu usage is apparently minimal.

![Image](https://github.com/user-attachments/assets/b5fcae07-9b46-4d16-81c0-cb1f82e4e461)
