### ISSUE TITLE
Default the Docker for Mac storage driver to overlay2 instead of aufs

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#516] opened 2016-09-04 22:38 UTC
### Expected behavior

The storage driver should be selectable and default to overlay2 instead of problematic aufs.
`docker info` should report:
```
Storage Driver: overlay2
```
Note the kernel is post-4.0 so it does support overlayfs and the new overlay2 which fixes inode depletion.
Btw similar request has been made for Docker for Windows:
https://forums.docker.com/t/mobylinuxvm-defaults-to-aufs-instead-of-overlay/13695

### Actual behavior
```
Server Version: 1.12.1
Storage Driver: aufs
Kernel Version: 4.4.19-moby
```
### Steps to reproduce the behavior

  1. Install latest Docker for Mac
  2. Notice the storage driver is aufs.

**Comment by martijn** [comment] 2016-09-15 09:36
The overlay2 storage driver depends on Linux kernel support, which is not and will probably never be available in OS X.

**Comment by dagguh** [comment] 2016-09-28 10:29
Is there a workaround?

**Comment by samoht** [comment] 2016-10-14 12:19
We will be switching to overlayfs in the next Beta (Beta29) so closing that issue.

**Closed by samoht** 2016-10-14 12:19 UTC
Labels: area/docker, area/linux, kind/enhancement, status/1-acknowledged

**Comment by neerolyte** [comment] 2017-02-11 11:46
The switch away from AUFS seems to be a massive performance hit - is that expected?

**Comment by dsheets** [comment] 2017-02-11 17:13
@neerolyte We need more information about what you were running (version, config, etc) and what you are running now. Have you tried the work-around in https://github.com/docker/for-mac/issues/668#issuecomment-250406582 ? If that does not improve the performance regression you are seeing, could you please open a new issue with more information and a diagnostic ID from :whale: ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload`?

**Comment by neerolyte** [comment] 2017-02-11 22:12
@dsheets Thanks, I was primarily looking to confirm whether overlay2 was expected to be slower (e.g the upgrade might have happened due to security or reliability concerns despite the performance drop). I've switched from some older (probably early 1.12.x, but not sure) repeatedly upgraded version to 1.13.0 - I did a factory reset to resolve other issues and performance has been terrible after the reset (manually switching back to AUFS improves it, but causes some stability issues I didn't seem to have previously).

I will gather detailed metrics and lodge a proper report if the performance regression isn't expected behaviour - I mainly just wanted to find out if it was expected.

The majority of my workload is build time stuff - installing packages, copying in code, etc. The slow down seems to be across all build steps (e.g copy, commit and operations that massage a lot of files like `chown -R` are much slower) and across at least Scientific/CentOS 6 + Oracle Linux 7. I'm not using volumes so `osxfs` isn't involved.

**Comment by neerolyte** [comment] 2017-02-12 00:18
Turning off `full-sync-on-flush` dropped average uncached build time for my main build from 4m30s to 2m30s, (and cached from 3s to 1s) so that's great, ta! Still curious about whether it'd be expected for overlay2 to be slower than aufs under the same settings though.
