### ISSUE TITLE
amd64 emulation alters observed process commands

### ISSUE THREAD

**Issue by aronatkins** [docker/for-mac#6794] opened 2023-04-04 19:14 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

`pgrep` can identify the sleeping command.

### Actual behavior

`pgrep` does not identify the sleeping command.

### Information

This problem occurs on Apple Silicon hosts using emulation (either qemu or Rosetta). The process listing shows the emulation wrapper program as the running command, not the actual target binary.

### Steps to reproduce the behavior

From one terminal:

```bash
docker run --platform linux/amd64 --name sleeper -it --rm ubuntu:jammy /usr/bin/sleep
```

From a second terminal:

```bash
# Returns nothing.
docker exec -it sleeper pgrep -xf "^/usr/bin/sleep.*120.*"

# Returns "1", the sleep PID.
docker exec -it sleeper pgrep -xf "^.*/usr/bin/sleep.*120.*"
#> 1

# Returns the current processes including the emulation programs.
docker exec -it sleeper ps auxww
#> docker exec -it sleeper ps auxww
#> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
#> root         1  0.2  0.0 144796  1736 pts/0    Ss+  19:10   0:00 /rosetta/rosetta /usr/bin/sleep 120
#> root         7  0.0  0.0 149220  4936 pts/1    Rs+  19:10   0:00 /usr/bin/ps auxww
```

The first `pgrep` command discovers the `sleep` process in other environments that do not use emulation. It fails to find the process when using qemu/Rosetta emulation because the emulation wrapper program is listed as the running command rather than `/usr/bin/sleep`.

The second `pgrep` command is necessary to discover the `sleep` process when using emulation. There are many other options to perform the same process-listing search; this example shows one way that the original command could be adjusted.

Tested with Docker Desktop 4.17.0 on macOS 12.6.3. Reproducible on multiple hosts with either qemu or Rosetta.

**Comment by dgageot** [comment] 2023-11-17 17:42
Hello @dometto, unfortunately, this is not something that can be fixed.

With Rosetta enabled, you'll see something like:
```
cat /proc/1/cmdline | xargs -0 echo
/rosetta/rosetta /bin/bash /bin/bash
```

With Qemu, it'll be:
```
cat /proc/1/cmdline | xargs -0 echo
/usr/bin/qemu-x86_64 /bin/bash /bin/bash
```

It's actually a feature of the Linux Kernel to preserve this `argv0`element.

**Comment by dgageot** [comment] 2023-11-17 17:43
Closing as duplicate of https://github.com/docker/for-mac/issues/7058

**Closed by dgageot** 2023-11-17 17:43 UTC

**Comment by aronatkins** [comment] 2023-11-17 18:01
@dgageot - Thanks for the additional details.

Unfortunately, it sounds like you're saying that in-container process lists will differ when using Docker Desktop on macOS+Apple Silicon. These differences show up compared to running with a Linux host or when using Docker Desktop on macOS+Intel.

This caused problems for us because we were using the same process-search commands in CI (Linux hosts) as we used locally (macOS hosts; mix of Intel and Apple Silicon).

**Comment by dgageot** [comment] 2023-11-17 18:24
I'm really sorry but yes, that's going to be different. Because the amd64 emulation happens on the userspace, some things will be different. Those things include how binaries are started, with which command line.
Again, sorry for the inconvenience but that's not something we can fix.
