### ISSUE TITLE
ADD with tar.gz from remote wrongly results in archive been decompressed

### ISSUE THREAD

**Issue by ChristopherHackett** [docker/for-mac#1847] opened 2017-07-11 10:08 UTC
In dockerfile reference it says for ADD

> If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed. When a directory is copied or unpacked, it has the same behavior as tar -x, the result is the union of:

https://docs.docker.com/engine/reference/builder/#add

Historically this has been true 

However 

```
FROM ubuntu:trusty
ADD https://github.com/docker/cli/archive/master.zip /usr/local/bin/
ADD https://curl.haxx.se/download/curl-7.54.1.tar.gz /usr/local/bin/
RUN ls -la /usr/local/bin/
```

Results in 
```
Step 1/4 : FROM ubuntu:trusty
 ---> aae2b63c4946
Step 2/4 : ADD https://github.com/docker/cli/archive/master.zip /usr/local/bin/
Downloading  4.652MB/4.652MB
 ---> Using cache
 ---> 9969dd5621da
Step 3/4 : ADD https://curl.haxx.se/download/curl-7.54.1.tar.gz /usr/local/bin/
Downloading  3.521MB/3.521MB

 ---> e12d5457e1de
Removing intermediate container 3091cf80cf43
Step 4/4 : RUN ls -la /usr/local/bin/
 ---> Running in e9bea0b27ee4
total 4556
drwxr-xr-x  1 root root    4096 Jul 11 09:30 .
drwxr-xr-x  1 root root    4096 Nov 23  2016 ..
drwxr-xr-x 13 1000 1000    4096 Jun 14 06:13 curl-7.54.1
-rw-------  1 root root 4651953 Jan  1  1970 master.zip
 ---> 523c10b1e9a7
Removing intermediate container e9bea0b27ee4
Successfully built 523c10b1e9a7
```
Notice curl-7.54.1 (which was a remote tar.gz file) is a directory where as the zip format archive is a file. 

This is a breaking change and requires users to change dockerfiles. 

<details>
  <summary> $ docker version </summary>
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
</details>

<details>
  <summary> $ docker info </summary>
$ docker info
Containers: 48
 Running: 0
 Paused: 0
 Stopped: 48
Images: 197
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: GLG7:BGAY:6AQW:7ECT:IFYI:46ZP:QAP2:SLPT:PAN2:ECP3:O3KL:OH2V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-07-11T09:39:26.333465616Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
</details>

**Comment by dsheets** [comment] 2017-07-13 14:03
This is a duplicate of #1725 and https://github.com/moby/moby/issues/33849 which should be fixed in the upcoming 17.06.1 release. Thanks for your report!

**Closed by dsheets** 2017-07-13 14:03 UTC
Labels: status/0-triage
