### ISSUE TITLE
Docker issues on mac

### ISSUE THREAD

**Issue by ratbhatt** [docker/for-mac#663] opened 2016-09-17 14:27 UTC
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 6A0FBE15-9AC1-4DEC-B5A2-B107BCB82690
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/ratbhattacharya/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ratbhattacharya/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/ratbhattacharya/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by dave-tucker** [comment] 2016-09-19 13:37
Thanks for the report @ratbhatt 
I'm afraid there isn't much we can do here without a better description of what the problem is.
You may also have better luck installing the latest beta (beta26)
I'm closing for now, but please feel free to add some more information and then we can re-open.

**Closed by dave-tucker** 2016-09-19 13:37 UTC
Labels: osx/10.11.x, status/0-triage, version/beta24
