### ISSUE TITLE
COPY --from command does not seem to support variables.

### ISSUE THREAD

**Issue by mdgreenwald** [docker/for-mac#2155] opened 2017-10-17 18:32 UTC
### Expected behavior
Variable passed to `COPY --from=${VARIABLE} /src /dest` command would resolve.

### Actual behavior
Variable is not resolved and instead generates error which indicates an invalid image name.
```Service 'nginx' failed to build: invalid from flag value $name: invalid reference format```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
50A907DF-6AD6-46D8-BB63-C833ED2F502F

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Copy zipped docker-compose and Dockerfile-nginx files into a folder.
  2. run the command from that folder: `docker-compose build --build-arg name="image_name" nginx`

Output should be: ```ERROR: Service 'nginx' failed to build: invalid from flag value $name: invalid reference format```

[dockerfiles.zip](https://github.com/docker/for-mac/files/1392135/dockerfiles.zip)

**Comment by ebriney** [comment] 2017-10-23 10:41
Hi @mdgreenwald .
`COPY --from` must specify a multistage image alias
so you should use a Dockerfile like:
```
ARG name
FROM ${name} as base

FROM nginx:1.12.1-alpine

COPY --from=base /source/ /destination/
```
in order to get it works

**Comment by thaJeztah** [comment] 2017-10-23 15:43
Correct, the `--from` option does not currently support variables; see https://github.com/moby/moby/issues/34482 for more information.

I'll close this issue because this is not currently supported, thus not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-10-23 15:43 UTC
Labels: status/1-acknowledged

**Comment by lmapii** [comment] 2018-03-13 10:50
@ebriney's solution does not seem to work for me:  calling `docker build -f api.Dockerfile -t thing-api:latest --build-arg arch=arm .` for the following (snippet) Dockerfile
```
FROM build-base AS amd64
RUN make clean && make native

FROM build-base AS arm
RUN make clean && make xcompile TARGET_ARCH=arm TARGET_OS=linux

ARG arch=amd64
FROM ${arch} as build
# won't work either:
# COPY /thing-api /thing-api

FROM scratch
COPY --from=base /thing-api/api/src/main /main

EXPOSE 8080
CMD ["./main"]
````

will produce 
```

Step 21/31 : FROM build-base AS amd64
 ---> bebf039c68b3
Step 22/31 : RUN make clean && make native
 ---> Using cache
 ---> 6b4b2a185443
Step 23/31 : FROM build-base AS arm
 ---> bebf039c68b3
Step 24/31 : RUN make clean && make xcompile TARGET_ARCH=arm TARGET_OS=linux
 ---> Using cache
 ---> 8ca0e7d07364
Step 25/31 : ARG arch=amd64
 ---> Using cache
 ---> 3b98282551aa
Step 26/31 : FROM ${arch} as build
 --->
Step 27/31 : COPY /thing-api /thing-api
COPY failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder093457154/thing-api: no such file or directory
make: *** [production] Error 1
```

However, if I replace `--from=base` with either `--from=arm` or `--from=amd64` it'll work just fine.

**Comment by ebriney** [comment] 2018-03-13 11:53
Hi @lmapii,
If you want to use it in `FROM` you must declare it before every `FROM` or it will be local to the previous one. It's bit strange I know.

```
# global arg
ARG arch=amd64

FROM build-base AS amd64
# local arg
ARG arch2=x86
RUN make clean && make native

FROM build-base AS arm
RUN make clean && make xcompile TARGET_ARCH=arm TARGET_OS=linux

FROM ${arch} as build

FROM scratch
COPY --from=build /thing-api/api/src/main /main

EXPOSE 8080
CMD ["./main"]
```

**Comment by lmapii** [comment] 2018-03-13 13:31
Hello @ebriney - Thanks a lot for the feedback - I would have never guessed that and I tried quite some things ;) Now that you put it like that it kinda makes sense > and best of all it works. Very much appreciated !

**Comment by ebriney** [comment] 2018-03-13 13:49
You're welcome. Same thing on my side, I read the docs  and tried to make it works and finally asked to a colleague which gave me the (stupid) explanation.

**Comment by MartinMuzatko** [comment] 2018-09-21 13:32
wow. this made me struggle for a few hours. thanks @mdgreenwald for reporting this.

**Comment by srobinson** [comment] 2019-01-02 23:32
Same here. Does anyone know of a workaround?

COPY --from=image:${version}

**Comment by darwin** [comment] 2019-04-25 18:13
This article describes a workaround (section 'Using build arguments in ` — from`'):
https://medium.com/@tonistiigi/advanced-multi-stage-build-patterns-6f741b852fae

Don't overlook:
> Remember that any arguments used in FROM commands need to be defined before the first build stage.

**Comment by qhaas** [comment] 2019-09-02 15:04
Found an edge case that impacts the (much appreciated) workaround by @ebriney, it occurs when one attempts to use an `ARG` to set the value of `FROM` in future build stages:
```
ARG DEPLOY_IMAGE=deploy-image
FROM ${DEPLOY_IMAGE} as deploy-image

ARG BASE_IMAGE=centos:7
FROM ${BASE_IMAGE}
```
`BASE_IMAGE` is part of `deploy-image` and thus is blank when used by the final `FROM`

**Comment by jamshid** [comment] 2020-01-07 07:01
Thanks for explanations I finally got it. All the ARGs, then FROMs, have to be at the **beginning** of the Dockerfile.
```
ARG REGISTRY_URL
ARG FOO_BRANCH
ARG BAR_BRANCH
FROM ${REGISTRY_URL}foo-src:${FOO_BRANCH} AS my-foo
FROM ${REGISTRY_URL}bar:${BAR_BRANCH} AS my-bar

FROM centos:8

COPY --from=my-foo /deliverables/*.rpm /deliverables/
COPY --from=my-bar /deliverables/*.rpm /deliverables/

RUN yum install -y /deliverables/*.rpm && yum clean all
