### ISSUE TITLE
Docker fails to start after update to 1.13.0

### ISSUE THREAD

**Issue by nemines** [docker/for-mac#1162] opened 2017-01-19 22:47 UTC
### Expected behavior
Docker should start after update to 1.13.0 (stable channel).
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/6217392/22128548/4ac55d08-def5-11e6-9331-adce9a67b747.png)

### Information
Diagnostic ID: B59EFE1C-7918-4985-A584-BB046AE0FB4F
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/B59EFE1C-7918-4985-A584-BB046AE0FB4F/20170120-093609.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/aloro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/aloro/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/aloro/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/aloro/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/aloro/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/aloro/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
Start docker on Mac.

**Comment by tjshipe** [comment] 2017-01-20 03:32
This looks like a duplicate of #1159 

Did you try [this solution](https://github.com/docker/for-mac/issues/1159#issuecomment-273899215)?

**Comment by nemines** [comment] 2017-01-20 03:51
Oh, apologies. I did not find the other tickets when I first looked it up, just the older one on the beta version.
I've fixed it by uninstalling through terminal and installing a new version, the was mostly for flagging and it can be closed.

**Closed** 2017-01-20 09:05 UTC
