### ISSUE TITLE
aufs corruption

### ISSUE THREAD

**Issue by dominikknafelj** [docker/for-mac#20] opened 2016-07-29 19:33 UTC
### Expected behavior

Creating a docker image via docker-compose up 
### Actual behavior

Step 9 : ADD Gemfile /myapp/Gemfile
 ---> 09a5fd9d54e8
ERROR: Service 'kcs' failed to build: {u'stream': u' ---> 09a5fd9d54e8\n'}
docker-compose up
ERROR: Bad response from Docker engine
### Information

The docker deamon doesnt strart 
Diagnostic ID: 285B74E3-14F5-4AED-83A9-263F76942063
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. ...
2. ...

**Comment by samoht** [comment] 2016-08-01 08:52
Could you share a simple way to fully reproduce the issue? I will make it much easier for us a lot to help you.

**Comment by djs55** [comment] 2016-09-05 13:20
```
time="2016-07-29T19:30:29.850130125Z" level=debug msg="Using graph driver aufs"
time="2016-07-29T19:30:29.965847953Z" level=debug msg="Failed to load layer sha256:266b8cbf3569f4f96b5004155636dfc72f17f74db8cd09d0e7aefa0cf35c1914: failed to get diff id for sha256:266b8cbf3569f4f96b5004155636dfc72f17f74db8cd09d0e7aefa0cf35c1914: invalid checksum digest format"
time="2016-07-29T19:30:29.977711736Z" level=debug msg="Failed to load layer sha256:66137f9b924207d8b3c389f8a29bbbfe7718f40b9fed60adee55b8d0fc4ae53d: failed to get diff id for sha256:66137f9b924207d8b3c389f8a29bbbfe7718f40b9fed60adee55b8d0fc4ae53d: invalid checksum digest format"
time="2016-07-29T19:30:29.984795655Z" level=debug msg="Failed to load layer sha256:9c854c9b6eb0afb0ac4608b511f5c3fa7541745f794fe543fd3615bd7eb33b25: failed to get diff id for sha256:9c854c9b6eb0afb0ac4608b511f5c3fa7541745f794fe543fd3615bd7eb33b25: invalid checksum digest format"
time="2016-07-29T19:30:29.990813570Z" level=debug msg="Failed to load layer sha256:d00ac27ee35d235d8a38c08213030bf0c8945bb0e8c824ae3979427ee9db7bda: failed to get diff id for sha256:d00ac27ee35d235d8a38c08213030bf0c8945bb0e8c824ae3979427ee9db7bda: invalid checksum digest format"
time="2016-07-29T19:30:29.993598009Z" level=debug msg="Failed to load mount 2e22fd27539908485c00656cbeac8e6aeb5a07e7cffd137aa68f7701beddc145: invalid mount id value"
time="2016-07-29T19:30:29.996618773Z" level=debug msg="Failed to load mount 5d0864fccd487912aa3e9a6cc404b32ddfa49810d5155b2120afde7c0b006e43: invalid mount id value"
time="2016-07-29T19:30:29.996947119Z" level=debug msg="Failed to load mount 624ab5e08279ca7ff374b94c367ffb5071a5bb097f0a9d56416ab2912d218c51: invalid mount id value"
time="2016-07-29T19:30:29.997707113Z" level=debug msg="Failed to load mount 91a515861db18b08244ec879d8055f422bccfe54b775306b2d5d1e9154bfb545: invalid mount id value"
time="2016-07-29T19:30:29.998101462Z" level=debug msg="Failed to load mount c29f740e9987622461e9b1bfe54ae0025afe52e500cac512b717fad4ca33261c: invalid mount id value"
time="2016-07-29T19:30:29.998447755Z" level=debug msg="Failed to load mount ef17917a1218727546e2f33c66536954502353ed4fe5770b49a3bc8baf8b6b51: invalid mount id value"
time="2016-07-29T19:30:29.998676715Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-07-29T19:30:29.998879698Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-07-29T19:30:30.122301234Z" level=debug msg="Cleaning up old mountid : start."
time="2016-07-29T19:30:30.124579797Z" level=fatal msg="Error starting daemon: layer does not exist"
```
This is the same class of error as reported here: http://stackoverflow.com/questions/39258122/cant-start-docker.

Without a repro case there's not much we can do. My best guess is that this could have been caused by a previous upgrade from 1.10 (from toolbox). The best workaround I can offer is to use "Whale menu -> Preferences -> Uninstall / Reset -> Reset to factory defaults". Note this has the side-effect of removing all containers and images so these will need to be rebuilt.

**Comment by justincormack** [comment] 2016-10-15 08:42
Reopening as it is not fixed yet, even though we don't have a repro case, it clearly affects lots of people. We are looking at switching to `overlay2` not aufs, which we hope will alleviate this, in the next beta.

**Comment by samoht** [comment] 2016-11-03 23:09
This is now fixed in Beta29.

**Comment by samoht** [comment] 2017-01-30 20:25
Closing the issue as we are now shipping overlay2 in both the stable and beta channels.

**Closed by samoht** 2017-01-30 20:25 UTC
Labels: area/linux, kind/bug, osx/10.11.x, status/4-fix-released-beta, version/1.12.0
